(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/btn1.png?1471864662070", id:"btn1"},
		{src:"images/btn2.png?1471864662070", id:"btn2"},
		{src:"images/dib.png?1471864662070", id:"dib"},
		{src:"images/LightGreyBackgroundHd51.jpg?1471864662070", id:"LightGreyBackgroundHd51"},
		{src:"images/logostforexcom2.png?1471864662070", id:"logostforexcom2"},
		{src:"images/moneypng17_03.png?1471864662071", id:"moneypng17_03"},
		{src:"images/moneypng17_06.png?1471864662071", id:"moneypng17_06"},
		{src:"images/moneypng17_08.png?1471864662071", id:"moneypng17_08"},
		{src:"images/moneypng17_12.png?1471864662071", id:"moneypng17_12"}
	]
};



// symbols:



(lib.btn1 = function() {
	this.initialize(img.btn1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,350,127);


(lib.btn2 = function() {
	this.initialize(img.btn2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,350,127);


(lib.dib = function() {
	this.initialize(img.dib);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,284,250);


(lib.LightGreyBackgroundHd51 = function() {
	this.initialize(img.LightGreyBackgroundHd51);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,700,438);


(lib.logostforexcom2 = function() {
	this.initialize(img.logostforexcom2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,294,81);


(lib.moneypng17_03 = function() {
	this.initialize(img.moneypng17_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,255,247);


(lib.moneypng17_06 = function() {
	this.initialize(img.moneypng17_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,234,280);


(lib.moneypng17_08 = function() {
	this.initialize(img.moneypng17_08);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,153,289);


(lib.moneypng17_12 = function() {
	this.initialize(img.moneypng17_12);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,104,161);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.LightGreyBackgroundHd51();
	this.instance.setTransform(0,0,0.938,0.938);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,656.9,411);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AJ7B6IAIhGIgWAAIgcitIAXAAIAYCVIAFAAIASiVIAYAAIgdDzgAICB6IAAjzIBGAAIAAAXIgvAAIAADcgAHPB6IAAhwIAGhUIgCgBIgwDFIggAAIAAjzIAYAAIAABvIgHBZIACAAIAxjIIAfAAIAADzgAFRB6IAAh6IgrAAIAAB6IgYAAIAAjzIAYAAIAABmIArAAIAAhmIAWAAIAADzgADkB6Iggh6IgJAAIAAB6IgXAAIAAjzIAXAAIAABmIAKAAQAIAAAFgFQAFgFAAgIIAAgwQAAgHADgIQACgFAFgFQAFgFAGgDQAGgDAIAAIABAAIAAAXIgBAAQgMABAAAMIAAAyQAAAKgFAIQgFAKgJADIAgB+gAgNB6IAAjzIAVAAIAABRIAgAAQAOAAAJAKQAKAJAAAOIAABgQAAAOgKAKQgJAJgOAAgAAIBjIAgAAQAKAAAAgKIAAhiQAAgKgKAAIggAAgAhXB6IAAjcIgdAAIAAgXIBQAAIAAAXIgcAAIAADcgAiaB6IgKhIIgqAAIgKBIIgXAAIAhjzIAqAAIAhDzgAinAcIgRh+IgCAAIgRB+IAkAAgAkbB6IAAhkIggAAQgOAAgKgJQgKgKAAgMIAAhwIAYAAIAAByQgBAHALAAIAgAAIAAh5IAXAAIAADzgAmJB6IgKhIIgpAAIgKBIIgXAAIAhjzIApAAIAhDzgAmVAcIgSh+IgBAAIgSB+IAlAAgAoBB6Iggh6IgJAAIAAB6IgXAAIAAjzIAXAAIAABmIAKAAQAIAAAFgFQAFgFAAgIIAAgwQAAgHADgIQADgFAEgFQAFgFAGgDQAGgDAIAAIACAAIAAAXIgCAAQgMABAAAMIAAAyQAAAKgFAIQgFAKgJADIAhB+gAqMB6QgOAAgKgJQgKgKABgOIAAixQgBgOAKgJQAKgKAOAAIAOAAQAOAAAKAKQAKAJAAAOIAAAbIgYAAIAAgbQAAgKgKAAIgOAAQgLAAAAAKIAACxQAAAKALAAIAOAAQAKAAAAgKIAAglIAYAAIAAAlQAAAOgKAKQgKAJgOAAg");
	this.shape.setTransform(109.1,40.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#212B37").s().p("AJ7B6IAIhHIgWAAIgcisIAXAAIAYCWIAFAAIASiWIAYAAIgdDzgAICB6IAAjzIBGAAIAAAXIgvAAIAADcgAHPB6IAAhvIAGhWIgCAAIgwDFIggAAIAAjzIAYAAIAABvIgHBZIACAAIAxjIIAfAAIAADzgAFRB6IAAh5IgrAAIAAB5IgYAAIAAjzIAYAAIAABmIArAAIAAhmIAWAAIAADzgADkB6Iggh5IgJAAIAAB5IgXAAIAAjzIAXAAIAABmIAKAAQAIAAAFgFQAFgFAAgIIAAgwQAAgIADgHQACgGAFgFQAFgEAGgDQAGgDAIAAIABAAIAAAXIgBAAQgMABAAAMIAAAyQAAAKgFAJQgFAIgJAEIAgB+gAgNB6IAAjzIAVAAIAABRIAgAAQAOAAAJAJQAKAKAAAOIAABgQAAANgKAKQgJAKgOAAgAAIBjIAgAAQAKAAAAgKIAAhiQAAgKgKAAIggAAgAhXB6IAAjcIgdAAIAAgXIBQAAIAAAXIgcAAIAADcgAiaB6IgKhIIgqAAIgKBIIgXAAIAhjzIAqAAIAhDzgAinAdIgRh/IgCAAIgRB/IAkAAgAkbB6IAAhkIggAAQgOAAgKgKQgKgJAAgMIAAhwIAYAAIAAByQgBAIALAAIAgAAIAAh6IAXAAIAADzgAmJB6IgKhIIgpAAIgKBIIgXAAIAhjzIApAAIAhDzgAmVAdIgSh/IgBAAIgSB/IAlAAgAoBB6Iggh5IgJAAIAAB5IgXAAIAAjzIAXAAIAABmIAKAAQAIAAAFgFQAFgFAAgIIAAgwQAAgIADgHQADgGAEgFQAFgEAGgDQAGgDAIAAIACAAIAAAXIgCAAQgMABAAAMIAAAyQAAAKgFAJQgFAIgJAEIAhB+gAqMB6QgOAAgKgKQgKgKABgNIAAixQgBgOAKgJQAKgKAOAAIAOAAQAOAAAKAKQAKAJAAAOIAAAcIgYAAIAAgcQAAgKgKAAIgOAAQgLAAAAAKIAACxQAAAKALAAIAOAAQAKAAAAgKIAAgmIAYAAIAAAmQAAANgKAKQgKAKgOAAg");
	this.shape_1.setTransform(109.1,43.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).wait(1));

	// Слой 1
	this.instance = new lib.btn1();
	this.instance.setTransform(0,0,0.63,0.63);

	this.instance_1 = new lib.btn2();
	this.instance_1.setTransform(0.6,3,0.634,0.634);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,220.5,80);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AvFT1QgfgQgPgqQgLgdgEgyQgKiNAHhVQAKh8AuhZQAkhHBChCIAYgXIABgBQApg2BJg2ICChcIBCgtQAngZAggOQAhgOAtgIQAYgFA5gHQBjgMA1gOQChgoB7hyIAagYQAYgtgGgrQgEgZgSgeQgFgJgdgpQhVh4ghiSQgiiRAWiRQAIg8Adh0QANgvAIgWQANglARgbQAmg8BYg1QBgg5BugcQBtgcBwAEIAAgGIADAAQAvAHBJAVQBuAgBDArQAvAfA2A3IADADIgJAJQgZAZgvgFQgbgDg4gTQiTgzifAkQigAkhuBuQguAtgWArQgzBfAWCAQAPBWA6BzQAhBABECAQA0BtAIBkQAKB1g4BTQghAwg6AmQgqAchHAhQkKB7j9AxQiTAdgfAJQhiAdg5A2QhVBQgZCcQgHAvgFBVQgGBegEAmQgLBUgfApQgWAcghAMQgPAFgOAAQgSAAgRgIg");
	this.shape.setTransform(103.3,127.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,206.7,255.5);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AEODHIADhmQACgzAFgmQAGgqALgnQAMgqAUgrIAAgDIhkAAIAAglICJAAIAAAsQgUAqgMAqQgLAngGApQgFAmgCAyIgCBlgAAPDHQgTAAgPgPQgPgPAAgWIAAklQAAgVAPgQQAQgPASAAIAUAAQAWAAAPAQQAPAPAAAVIAAElQAAAWgPAQQgQAOgVAAgAABA9IAABTQAAAHAFAGQAGAEAGAAIAPAAQAHAAAFgFQAFgFAAgHIAAiqgAAGibQgFAFAAAGIAACQIAxhYIAAg4QAAgGgGgFQgFgGgGAAIgPAAQgHABgFAFgAiYDHQgVAAgPgPQgPgPAAgWIAAklQAAgVAPgQQAQgPAUAAIAUAAQAWAAAPAQQAPAPAAAVIAAElQAAAWgPAQQgQAOgVAAgAimA9IAABTQAAAHAFAGQAGAEAGAAIAPAAQAHAAAFgFQAFgFAAgHIAAiqgAihibQgFAFAAAGIAACQIAxhYIAAg4QAAgGgGgFQgFgGgGAAIgPAAQgHABgFAFgAlrDHIAAgmIAmAAIAAlCIgoAAIAAglIBOAAIAAFnIAmAAIAAAmg");
	this.shape.setTransform(38.5,30.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1.9,10.8,73.4,39.9);


(lib.Анимация104 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.moneypng17_03();
	this.instance.setTransform(-112.4,-108.9,0.882,0.882);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-112.4,-108.9,224.9,217.8);


(lib.Анимация102 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.moneypng17_06();
	this.instance.setTransform(-103.1,-123.4,0.882,0.882);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-103.1,-123.4,206.3,246.9);


(lib.Анимация100 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.moneypng17_08();
	this.instance.setTransform(-67.4,-127.4,0.882,0.882);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.4,-127.4,134.9,254.8);


(lib.Анимация98 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.moneypng17_12();
	this.instance.setTransform(-45.8,-71,0.882,0.882);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-45.8,-71,91.7,142);


(lib.Анимация97 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgTIA8iDQAGgOAAgZIAAgsQAAgGgFgFQgFgFgFgBIgRAAQgHAAgFAGQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAjgJASIg9CFQgPAmAAAVIAAASIBSAAIAAAmgAgUXPQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMANAAAWIAACaQAAAVgPAPQgPAQgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAGAHAAIASAAQARAAAAgSIAAiQQAAgHgGgGQgHgFgGgBQgSAAgIAOQgHAKAAAYIgmAAIAAjjIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAQAAAVIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgQAAgVIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgsQAAgGgFgFQgFgFgHgBIgSAAQgHABgFAFQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAQQgPAPgWAAgAgbqEQgHAMAAAWIAABwQAAAHAFAFQAFAFAHAAIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgEgHgBQgSABgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGAsQgFAlgCAyIgBBlgAgU7DQgVAAgQgQQgPgPAAgVIAAiOQAAgRAJgLQAIgKANgEQgLgEgIgKQgIgJAAgNIAAhLQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABLQAAANgJALQgIAJgKADQAdAQAAAaIAACOQAAAVgPAPQgPAQgVAAgAgi+KIAACQQAAARARABIAQAAQAPgBAAgRIAAiQQAAgSgPAAIgQAAQgRAAAAASgEgAaggnQgGAFAAAHIAABJQAAARASAAIAKAAQAPAAAAgRIAAhJQAAgRgPgBIgKAAQgHABgFAFgEgAUglHQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgVAPgQQAPgPAWAAIAXAAQAVAAAQAPQAPAQAAAVIAAEnQAAAWgPAPQgQAPgVAAgEgAegqrQgFAFAAAGIAAB9QAAAHAFAGQAGAEAHAAQASABAJgQQAIgMAAgVIAAheQAAgGgFgFQgGgGgHAAIgRAAQgHAAgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация96 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAgmIAnAAIAAlEIgpAAIAAglIBMAAIAAFpIAnAAIAAAmgEgBFAhTIAAg3QAAgVAEgSQAEgSAKgTIA8iCQAGgOAAgaIAAgrQAAgHgFgGQgFgEgFAAIgRAAQgHgBgFAGQgFAFAAAHIAAArIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJATIg9CFQgPAlAAAXIAAASIBSAAIAAAlgAgUXPQgWAAgPgPQgPgQAAgVIAAg+IAmAAIAAA7QAAARARAAIARAAQARAAAAgRIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggNIBMiWIhVAAIAAglIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMAOQAMAMAAAWIAACaQAAAVgPAQQgPAPgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAFAHABIASAAQARgBAAgRIAAiQQAAgHgGgGQgHgFgGAAQgSAAgIANQgHALAAAWIgmAAIAAjiIB3AAIAAAlIhRAAIAAB1QAOgMAVAAQAWAAAQAPQARAPAAAWIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgPAAgWIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgsQAAgGgFgFQgFgGgHAAIgSAAQgHAAgFAGQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAVIAACXQAAAWgPAPQgPAPgWAAgAgbqFQgHAMAAAWIAABxQAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgFgHABQgSAAgKAOgAglw/IADhmQACgzAFgmQAGgsALgnQAKgrAUgqIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGArQgFAmgCAyIgBBlgAgU7DQgVAAgQgPQgPgPAAgWIAAiOQAAgQAJgMQAIgJANgGQgLgEgIgIQgIgLAAgNIAAhKQAAgWAPgPQAPgPAWAAIAQAAQATAAAPAPQAQAPAAAWIAABKQAAAPgJAKQgIAJgKACQAdARAAAaIAACOQAAAWgPAPQgPAPgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgRgPgBIgQAAQgRABAAARgEgAaggnQgGAFAAAGIAABKQAAARASAAIAKAAQAPAAAAgRIAAhKQAAgRgPAAIgKAAQgHAAgFAGgEgAUglHQgWAAgPgQQgPgPAAgVIAAg/IAlAAIAAA8QAAAHAFAFQAGAFAHABIARAAQAHgBAGgFQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAVgPAPQgQAQgVAAgEgAegqrQgFAFAAAHIAAB9QAAAHAFAFQAGAEAHAAQASAAAJgOQAIgNAAgWIAAhcQAAgHgFgFQgGgGgHABIgRAAQgHgBgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация95 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgSIA8iEQAGgOAAgZIAAgsQAAgGgFgFQgFgGgFAAIgRAAQgHABgFAFQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJAUIg9CEQgPAlAAAWIAAASIBSAAIAAAmgAgUXPQgWAAgPgQQgPgOAAgWIAAg+IAmAAIAAA7QAAARARABIARAAQARgBAAgRIAAiSQAAgIgGgFQgFgGgGAAQgLAAgHAGQgHAEgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMANAAAXIAACZQAAAWgPAOQgPAQgWAAgAAINLIAAhQIhTAAIAAgjIBFkcIA0AAIAAEcIAhAAIAAAjIghAAIAABQgAglLYIAtAAIAAhpIAHiEgAgUDHQgVAAgQgPQgPgPAAgWIAAg+IAmAAIAAA7QAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiQQAAgHgGgFQgHgHgGAAQgSAAgIAOQgHAKAAAYIgmAAIAAjjIB3AAIAAAlIhRAAIAAB1QAOgMAVAAQAWAAAQAPQARAQAAAVIAACXQAAAWgPAPQgQAPgVAAgAgUm7QgWAAgPgQQgPgPAAgVIAAknQAAgWAPgPQAPgPAWAAIAXAAQAWAAAPAPQAPAPAAAWIAAAuIglAAIAAgrQAAgHgFgFQgFgFgHAAIgSAAQgHAAgFAFQgFAFAAAHIAABoQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAPQgPAQgWAAgAgbqEQgHAMAAAVIAABxQAAAHAFAFQAFAFAHABIASAAQARAAAAgSIAAiQQAAgIgFgFQgFgEgHgBQgSABgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgDIhiAAIAAglICHAAIAAAsQgUArgMApQgLAngGAsQgFAkgCAzIgBBlgAgU7DQgVAAgQgQQgPgPAAgVIAAiPQAAgPAJgMQAIgKANgEQgLgFgIgJQgIgKAAgMIAAhLQAAgWAPgPQAPgPAWAAIAQAAQATAAAPAPQAQAPAAAWIAABLQAAAOgJAKQgIAIgKAEQAdAQAAAZIAACPQAAAVgPAPQgPAQgVAAgAgi+KIAACQQAAASARAAIAQAAQAPAAAAgSIAAiQQAAgRgPAAIgQAAQgRAAAAARgEgAaggnQgGAFAAAHIAABJQAAASASAAIAKAAQAPAAAAgSIAAhJQAAgSgPABIgKAAQgHgBgFAGgEgAUglHQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgVIAAiCQAAgVAPgQQAPgPAWAAIAXAAQAVAAAQAPQAPAQAAAVIAAEnQAAAWgPAPQgQAPgVAAgEgAegqrQgFAFAAAGIAAB9QAAAIAFAEQAGAGAHAAQASgBAJgPQAIgMAAgWIAAhdQAAgGgFgFQgGgFgHgBIgRAAQgHABgGAFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация94 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAgmIAnAAIAAlEIgpAAIAAglIBMAAIAAFpIAnAAIAAAmgEgBFAhTIAAg3QAAgVAEgSQAEgSAKgTIA8iCQAGgOAAgaIAAgsQAAgGgFgGQgFgEgFAAIgRAAQgHgBgFAGQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJATIg9CFQgPAlAAAXIAAASIBSAAIAAAlgAgUXPQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAARARABIARAAQARgBAAgRIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggNIBMiWIhVAAIAAglIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMAOAAAVIAACaQAAAVgPAPQgPAQgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAFAHABIASAAQARAAAAgSIAAiQQAAgHgGgGQgHgFgGAAQgSAAgIANQgHAKAAAXIgmAAIAAjiIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAPAAAWIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgPAAgWIAAknQAAgWAPgPQAPgPAWAAIAXAAQAWAAAPAPQAPAPAAAWIAAAuIglAAIAAgsQAAgGgFgFQgFgGgHAAIgSAAQgHAAgFAGQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAWgPAPQgPAPgWAAgAgbqFQgHAMAAAXIAABwQAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgFgHAAQgSAAgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGArQgFAlgCAzIgBBlgAgU7DQgVAAgQgPQgPgPAAgWIAAiOQAAgQAJgMQAIgJANgGQgLgEgIgIQgIgLAAgNIAAhKQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABKQAAAPgJAKQgIAJgKACQAdARAAAaIAACOQAAAWgPAPQgPAPgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgSgPAAIgQAAQgRAAAAASgEgAaggnQgGAFAAAGIAABKQAAARASAAIAKAAQAPAAAAgRIAAhKQAAgQgPgBIgKAAQgHABgFAFgEgAUglHQgWAAgPgQQgPgPAAgVIAAg/IAlAAIAAA8QAAAHAFAFQAGAGAHAAIARAAQAHAAAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAVgPAPQgQAQgVAAgEgAegqrQgFAFAAAHIAAB8QAAAHAFAGQAGAEAHAAQASAAAJgOQAIgNAAgVIAAhdQAAgHgFgFQgGgGgHABIgRAAQgHgBgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация93 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgSIA8iEQAGgOAAgZIAAgrQAAgHgFgFQgFgGgFAAIgRAAQgHABgFAFQgFAFAAAHIAAArIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJAUIg9CEQgPAlAAAWIAAASIBSAAIAAAmgAgUXPQgWAAgPgPQgPgPAAgWIAAg/IAmAAIAAA8QAAARARABIARAAQARgBAAgRIAAiSQAAgIgGgFQgFgFgGgBQgLABgHAFQgHAEgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMAOQAMAMAAAXIAACZQAAAWgPAPQgPAPgWAAgAAINLIAAhQIhTAAIAAgjIBFkcIA0AAIAAEcIAhAAIAAAjIghAAIAABQgAglLYIAtAAIAAhpIAHiEgAgUDHQgVAAgQgPQgPgPAAgWIAAg+IAmAAIAAA7QAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiQQAAgHgGgFQgHgHgGAAQgSAAgIAOQgHAKAAAYIgmAAIAAjjIB3AAIAAAlIhRAAIAAB1QAOgMAVAAQAWAAAQAPQARAQAAAVIAACXQAAAWgPAPQgQAPgVAAgAgUm7QgWAAgPgQQgPgPAAgVIAAknQAAgWAPgPQAPgPAWAAIAXAAQAWAAAPAPQAPAPAAAWIAAAuIglAAIAAgrQAAgHgFgFQgFgFgHAAIgSAAQgHAAgFAFQgFAFAAAHIAABoQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAPQgPAQgWAAgAgbqEQgHAMAAAVIAABxQAAAHAFAFQAFAFAHABIASAAQARAAAAgSIAAiQQAAgIgFgFQgFgEgHgBQgSABgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgDIhiAAIAAglICHAAIAAAsQgUArgMApQgLAngGAsQgFAkgCAzIgBBlgAgU7DQgVAAgQgQQgPgPAAgVIAAiPQAAgPAJgMQAIgKANgEQgLgFgIgJQgIgKAAgMIAAhLQAAgWAPgPQAPgPAWAAIAQAAQATAAAPAPQAQAPAAAWIAABLQAAAOgJAKQgIAIgKAEQAdAQAAAZIAACPQAAAVgPAPQgPAQgVAAgAgi+KIAACQQAAASARAAIAQAAQAPAAAAgSIAAiQQAAgRgPAAIgQAAQgRAAAAARgEgAaggnQgGAFAAAHIAABJQAAASASAAIAKAAQAPAAAAgSIAAhJQAAgSgPABIgKAAQgHgBgFAGgEgAUglHQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgVIAAiCQAAgVAPgQQAPgPAWAAIAXAAQAVAAAQAPQAPAQAAAVIAAEnQAAAWgPAPQgQAPgVAAgEgAegqrQgFAFAAAGIAAB9QAAAIAFAEQAGAGAHAAQASgBAJgPQAIgMAAgWIAAhdQAAgGgFgFQgGgFgHgBIgRAAQgHABgGAFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация92 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlFIgpAAIAAglIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgTIA8iCQAGgOAAgaIAAgsQAAgGgFgFQgFgFgFgBIgRAAQgHAAgFAGQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJATIg9CFQgPAmAAAVIAAASIBSAAIAAAmgAgUXPQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMAOAAAVIAACaQAAAVgPAPQgPAQgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAFAHABIASAAQARAAAAgSIAAiQQAAgHgGgGQgHgFgGAAQgSAAgIANQgHAKAAAXIgmAAIAAjiIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAPAAAWIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgPAAgWIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgsQAAgGgFgFQgFgFgHgBIgSAAQgHABgFAFQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAWgPAPQgPAPgWAAgAgbqFQgHAMAAAXIAABwQAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgFgHAAQgSAAgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgpAUgrIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGAsQgFAkgCAzIgBBlgAgU7DQgVAAgQgPQgPgQAAgVIAAiOQAAgRAJgLQAIgKANgFQgLgEgIgIQgIgKAAgOIAAhKQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABKQAAAOgJALQgIAJgKACQAdARAAAaIAACOQAAAVgPAQQgPAPgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgSgPAAIgQAAQgRAAAAASgEgAaggnQgGAFAAAGIAABKQAAARASAAIAKAAQAPAAAAgRIAAhKQAAgQgPgBIgKAAQgHABgFAFgEgAUglHQgWAAgPgQQgPgOAAgWIAAg/IAlAAIAAA8QAAAHAFAFQAGAGAHAAIARAAQAHAAAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAWgPAOQgQAQgVAAgEgAegqrQgFAFAAAGIAAB9QAAAHAFAGQAGAEAHAAQASABAJgPQAIgNAAgVIAAheQAAgGgFgFQgGgGgHABIgRAAQgHgBgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация91 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAgmIAnAAIAAlEIgpAAIAAglIBMAAIAAFpIAnAAIAAAmgEgBFAhTIAAg3QAAgVAEgSQAEgSAKgTIA8iCQAGgOAAgaIAAgrQAAgHgFgGQgFgEgFAAIgRAAQgHgBgFAGQgFAFAAAHIAAArIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAjgJASIg9CFQgPAlAAAXIAAASIBSAAIAAAlgAgUXPQgWAAgPgPQgPgPAAgWIAAg+IAmAAIAAA7QAAARARAAIARAAQARAAAAgRIAAiSQAAgIgGgFQgFgGgGABQgLgBgHAGQgHAEgGALIgggNIBMiWIhVAAIAAglIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMAOQAMANAAAWIAACZQAAAWgPAPQgPAPgWAAgAAINLIAAhQIhTAAIAAgjIBFkcIA0AAIAAEcIAhAAIAAAjIghAAIAABQgAglLYIAtAAIAAhpIAHiEgAgUDHQgVAAgQgPQgPgQAAgVIAAg+IAmAAIAAA7QAAAHAFAFQAFAFAHAAIASAAQARAAAAgRIAAiQQAAgHgGgFQgHgHgGABQgSAAgIANQgHALAAAWIgmAAIAAjiIB3AAIAAAlIhRAAIAAB1QAOgMAVAAQAWAAAQAPQARAPAAAWIAACXQAAAVgPAQQgQAPgVAAgAgUm7QgWAAgPgQQgPgOAAgWIAAknQAAgWAPgPQAPgPAWAAIAXAAQAWAAAPAPQAPAPAAAWIAAAuIglAAIAAgsQAAgGgFgFQgFgGgHABIgSAAQgHgBgFAGQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAVIAACXQAAAWgPAOQgPAQgWAAgAgbqFQgHAMAAAWIAABxQAAAHAFAFQAFAGAHAAIASAAQARgBAAgRIAAiQQAAgIgFgFQgFgFgHABQgSAAgKAOgAglw/IADhmQACgzAFgmQAGgsALgnQAKgqAUgrIAAgDIhiAAIAAglICHAAIAAAsQgUAqgMAqQgLAngGArQgFAmgCAyIgBBlgAgU7DQgVAAgQgPQgPgPAAgWIAAiPQAAgPAJgMQAIgJANgGQgLgDgIgJQgIgLAAgNIAAhKQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABKQAAAOgJALQgIAIgKADQAdARAAAZIAACPQAAAWgPAPQgPAPgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgRgPAAIgQAAQgRAAAAARgEgAaggnQgGAFAAAGIAABKQAAARASAAIAKAAQAPAAAAgRIAAhKQAAgRgPAAIgKAAQgHAAgFAGgEgAUglHQgWAAgPgQQgPgPAAgVIAAg/IAlAAIAAA8QAAAHAFAFQAGAFAHABIARAAQAHgBAGgFQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgVIAAiCQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAVgPAPQgQAQgVAAgEgAegqrQgFAFAAAHIAAB9QAAAHAFAEQAGAFAHABQASAAAJgPQAIgNAAgWIAAhcQAAgHgFgFQgGgFgHAAIgRAAQgHAAgGAFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgTIA8iDQAGgOAAgZIAAgsQAAgGgFgFQgFgFgFgBIgRAAQgHAAgFAGQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAjgJATIg9CEQgPAmAAAVIAAASIBSAAIAAAmgAgUXPQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMANAAAWIAACaQAAAVgPAPQgPAQgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAGAHAAIASAAQARAAAAgSIAAiQQAAgHgGgGQgHgFgGgBQgSAAgIAOQgHAKAAAYIgmAAIAAjjIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAQAAAVIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgQAAgVIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgsQAAgGgFgFQgFgFgHgBIgSAAQgHABgFAFQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAQQgPAPgWAAgAgbqEQgHAMAAAWIAABwQAAAHAFAFQAFAFAHAAIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgEgHgBQgSABgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGAsQgFAlgCAyIgBBlgAgU7DQgVAAgQgQQgPgPAAgVIAAiOQAAgRAJgLQAIgKANgEQgLgEgIgKQgIgJAAgNIAAhLQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABLQAAANgJALQgIAJgKADQAdAQAAAaIAACOQAAAVgPAPQgPAQgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgSgPAAIgQAAQgRAAAAASgEgAaggnQgGAFAAAHIAABJQAAARASAAIAKAAQAPAAAAgRIAAhJQAAgRgPgBIgKAAQgHABgFAFgEgAUglHQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgVAPgQQAPgPAWAAIAXAAQAVAAAQAPQAPAQAAAVIAAEnQAAAWgPAPQgQAPgVAAgEgAegqrQgFAFAAAGIAAB9QAAAHAFAGQAGAEAHAAQASABAJgQQAIgMAAgVIAAheQAAgGgFgFQgGgGgHAAIgRAAQgHAAgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация89 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAgmIAnAAIAAlEIgpAAIAAglIBMAAIAAFpIAnAAIAAAmgEgBFAhTIAAg3QAAgVAEgSQAEgSAKgTIA8iCQAGgOAAgaIAAgrQAAgHgFgGQgFgEgFAAIgRAAQgHgBgFAGQgFAFAAAHIAAArIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJATIg9CFQgPAlAAAXIAAASIBSAAIAAAlgAgUXPQgWAAgPgPQgPgQAAgVIAAg+IAmAAIAAA7QAAARARAAIARAAQARAAAAgRIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggNIBMiWIhVAAIAAglIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMAOQAMANAAAVIAACaQAAAVgPAQQgPAPgWAAgAAINLIAAhQIhTAAIAAgjIBFkcIA0AAIAAEcIAhAAIAAAjIghAAIAABQgAglLYIAtAAIAAhpIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAFAHAAIASAAQARAAAAgRIAAiQQAAgHgGgGQgHgFgGAAQgSAAgIANQgHALAAAWIgmAAIAAjiIB3AAIAAAlIhRAAIAAB1QAOgMAVAAQAWAAAQAPQARAPAAAWIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgPAAgWIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgsQAAgGgFgFQgFgGgHAAIgSAAQgHAAgFAGQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAVIAACXQAAAWgPAPQgPAPgWAAgAgbqFQgHAMAAAWIAABxQAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgFgHABQgSAAgKAOgAglw/IADhmQACgzAFgmQAGgsALgnQAKgrAUgqIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGArQgFAmgCAyIgBBlgAgU7DQgVAAgQgPQgPgPAAgWIAAiOQAAgQAJgMQAIgJANgGQgLgEgIgIQgIgLAAgNIAAhKQAAgWAPgPQAPgPAWAAIAQAAQATAAAPAPQAQAPAAAWIAABKQAAAPgJAKQgIAJgKACQAdARAAAaIAACOQAAAWgPAPQgPAPgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgRgPgBIgQAAQgRABAAARgEgAaggnQgGAFAAAGIAABKQAAARASAAIAKAAQAPAAAAgRIAAhKQAAgRgPAAIgKAAQgHAAgFAGgEgAUglHQgWAAgPgQQgPgPAAgVIAAg/IAlAAIAAA8QAAAHAFAFQAGAFAHABIARAAQAHgBAGgFQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAVgPAPQgQAQgVAAgEgAegqrQgFAFAAAHIAAB9QAAAHAFAFQAGAEAHAAQASAAAJgOQAIgNAAgWIAAhcQAAgHgFgFQgGgGgHABIgRAAQgHgBgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация88 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("Ag3DHIAAglIAnAAIAAlCIgpAAIAAgmIBMAAIAAFoIAnAAIAAAlg");
	this.shape.setTransform(-1.6,287.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCCCCC").s().p("Ag7DHIAAg4QAAgTAEgTQAEgSAKgSIA8iCQAGgOAAgZIAAgsQAAgGgFgFQgFgGgHAAIgPAAQgHABgFAFQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJAUIg9CCQgPAmAAAVIAAASIBSAAIAAAmg");
	this.shape_1.setTransform(-1.1,223.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCCCCC").s().p("AgLDHQgVAAgQgQQgPgPABgVIAAg/IAlAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiQQAAgIgGgGQgFgEgHgBQgKABgHAEQgHAFgGAJIgfgMIBLiUIhUAAIAAgmIB4AAIAAAxIg3BlQAGgFAJAAQAWAAAMANQAMANAAAWIAACYQgBAVgPAPQgPAQgWAAg");
	this.shape_2.setTransform(-1,159);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCCCCC").s().p("AAHDHIAAhQIhTAAIAAgiIBFkbIAzAAIAAEbIAhAAIAAAiIghAAIAABQgAgmBVIAtAAIAAhoIAHiEg");
	this.shape_3.setTransform(0.1,94.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CCCCCC").s().p("AgLDHQgWAAgQgQQgPgOABgWIAAg+IAlAAIAAA7QAAAHAFAFQAFAGAIAAIARAAQARgBAAgRIAAiQQAAgHgGgGQgHgFgIgBQgQAAgHAOQgIAKAAAYIglAAIAAjjIB2AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQASAPgBAWIAACXQAAAWgPAOQgPAQgWAAg");
	this.shape_4.setTransform(-0.9,30.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CCCCCC").s().p("AgMDHQgVAAgPgQQgPgPAAgVIAAklQAAgVAPgQQAPgPAVAAIAYAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgrQAAgHgFgFQgGgFgGgBIgTAAQgHABgFAFQgEAFgBAHIAABoQARgOATAAQAXAAAQAPQAPAPAAAWIAACUQAAAVgPAPQgPAQgWAAgAgSAAQgIAKAAAWIAABwQABAHAEAFQAFAFAHAAIATAAQARAAAAgRIAAiQQAAgFgFgGQgFgEgHgBQgTABgJAPg");
	this.shape_5.setTransform(-0.9,-34.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#CCCCCC").s().p("AgaDHIAChmQADgzAEgmQAHgqAKgoQAKgqAVgqIAAgDIhiAAIAAglICHAAIAAAsQgUArgMApQgLAngGAqQgFAkgCAzIgDBlg");
	this.shape_6.setTransform(-1.1,-98.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CCCCCC").s().p("AgJDHQgVAAgQgQQgPgPAAgVIAAiPQAAgNAJgMQAIgKANgEQgLgFgIgJQgJgJABgNIAAhLQAAgWAPgPQAPgPAWAAIANAAQAWAAAPAPQAQAPAAAWIAABLQAAANgJALQgIAJgKADQAdAQAAAXIAACPQAAAVgPAPQgPAQgWAAgAgYAAIAACQQABASARAAIANAAQARAAABgSIAAiQQgBgQgRAAIgNAAQgRAAgBAQgAgQibQgFAFAAAHIAABJQAAASASAAIAIAAQARAAAAgSIAAhJQAAgRgRAAIgIAAQgHAAgGAFg");
	this.shape_7.setTransform(-1.1,-163);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CCCCCC").s().p("AgMDHQgVAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAGgBIASAAQAHABAGgGQAEgFAAgHIAAh9QgQAPgTAAQgVAAgRgPQgQgQAAgTIAAiCQAAgWAPgPQAPgPAVAAIAYAAQAVAAAQAPQAPAPAAAWIAAElQAAAWgPAPQgQAPgVAAgAgVibQgFAFAAAGIAAB9QAAAIAFAEQAGAGAGgBQASAAAKgPQAIgMgBgVIAAheQAAgGgEgFQgGgGgHAAIgSAAQgGAAgGAGg");
	this.shape_8.setTransform(-0.9,-227.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CCCCCC").s().p("Ag3DHIAAglIAnAAIAAlCIgpAAIAAgmIBMAAIAAFoIAnAAIAAAlg");
	this.shape_9.setTransform(-1.6,-291.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.7,-324,23.5,648);


(lib.Анимация87 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGAwZIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAmVIAAg4QAAgTAEgTQAEgSAKgSIA8iEQAGgOAAgZIAAgsQAAgGgFgFQgFgGgFAAIgRAAQgHABgFAFQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJAUIg9CEQgPAmAAAVIAAASIBSAAIAAAmgAgUcRQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiSQAAgIgGgFQgFgFgGgBQgLABgHAFQgHAEgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMANAAAWIAACaQAAAVgPAPQgPAQgWAAgAAISNIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglQbIAtAAIAAhqIAHiEgAgUIJQgVAAgQgQQgPgOAAgWIAAg+IAmAAIAAA7QAAAHAFAFQAFAGAHAAIASAAQARgBAAgRIAAiQQAAgJgGgGQgHgFgGgBQgSAAgIAOQgHAMAAAYIgmAAIAAjlIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAPAAAWIAACZQAAAWgPAOQgQAQgVAAgAgUh5QgWAAgPgQQgPgPAAgVIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgrQAAgHgFgFQgFgFgHgBIgSAAQgHABgFAFQgFAFAAAHIAABoQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAPQgPAQgWAAgAgblCQgHAMAAAWIAABwQAAAHAFAFQAFAFAHAAIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgEgHgBQgSABgKAPgAglr9IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgDIhiAAIAAglICHAAIAAAsQgUArgMApQgLAngGAsQgFAkgCAzIgBBlgAgU2BQgVAAgQgQQgPgPAAgVIAAiPQAAgPAJgMQAIgKANgEQgLgFgIgJQgIgJAAgNIAAhLQAAgWAPgPQAPgPAWAAIAQAAQATAAAPAPQAQAPAAAWIAABLQAAANgJALQgIAJgKADQAdAQAAAZIAACPQAAAVgPAPQgPAQgVAAgAgi5IIAACQQAAASARAAIAQAAQAPAAAAgSIAAiQQAAgSgPAAIgQAAQgRAAAAASgAga7lQgGAFAAAHIAABJQAAASASAAIAKAAQAPAAAAgSIAAhJQAAgRgPAAIgKAAQgHAAgFAFgEgAUggFQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgVIAAiCQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAWgPAPQgQAPgVAAgEgAeglpQgFAFAAAGIAAB9QAAAIAFAEQAGAGAHgBQASAAAJgPQAIgMAAgVIAAheQAAgGgFgFQgGgGgHAAIgRAAQgHAAgGAGgEgBGgqJIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlg");
	this.shape.setTransform(-0.1,-2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8,-311.7,15.9,619.5);


(lib.Анимация67 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("ABBCHIAAhoIAKh7Ig4DjIglAAIg4jjIAKB9IAABmIgfAAIAAkNIAqAAIA1DeIA2jeIAqAAIAAENg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9.6,-13.5,19.3,27.2);


(lib.Анимация64 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgRCHQgTAAgOgOQgNgNAAgUIAAivQAAgTANgOQAOgOATAAIAiAAQAUAAAOAOQANAOAAATIAACvQAAAUgNANQgOAOgUAAgAgghXIAACvQAAAQAPAAIAiAAQAQAAAAgQIAAivQAAgPgQAAIgiAAQgPAAAAAPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.4,-13.5,13,27.2);


(lib.Анимация61 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("ABBCHIAAhoIAKh7Ig4DjIglAAIg4jjIAKB9IAABmIgfAAIAAkNIAqAAIA1DeIA2jeIAqAAIAAENg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9.6,-13.5,19.3,27.2);


(lib.Анимация58 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgKCuIAKhNIgaAAIgokOIAgAAIAiDuIADAAIAhjuIAfAAIgvFbg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.7,-17.4,13.5,34.9);


(lib.Анимация55 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgLCHQgTAAgOgOQgNgNAAgUIAAivQAAgTANgOQAOgOATAAIAXAAQAUAAANAOQAOAOAAATIAAAaIggAAIAAgaQAAgPgPAAIgXAAQgPAAAAAPIAACvQAAAQAPAAIAXAAQAPAAAAgQIAAgrIAgAAIAAArQAAAUgOANQgNAOgUAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.9,-13.5,11.8,27.2);


(lib.Анимация52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgPATQgPAAgJgKQgKgJAAgOIAAgEIAZAAIAAAFQAAALAKAAIAdAAQAKAAAAgLIAAgFIAZAAIAAAEQAAAOgKAJQgKAKgPAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5,-1.9,10.1,3.9);


(lib.Анимация49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AApCHIAAhwIAHh9IhLDtIgrAAIAAkNIAeAAIAAB+IgIBwIBMjuIAsAAIAAENg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.2,-13.5,14.4,27.2);


(lib.Анимация46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgzB9QgMgMAAgTIAAhKQAAgTAOgMQAOgNASAAIAxAAIAAhAQAAgPgQAAIgbAAQgHAAgEAEQgFAEAAAHIAAAaIgfAAIAAgaQAAgUANgOQAPgNAUAAIAbAAQAUAAAOAOQANAOAAATIAADeIgaAAIgFgMIgiAMIgSACQgTAAgNgLgAgcAJQgEAFAAAGIAABHQAAAOAPAAIAHAAIAqgQIAAhUIgxAAQgGAAgFAEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.4,-13.6,12.9,27.4);


(lib.Анимация43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("Ag/CHIAAkNIBRAAQASAAAOAOQAOAOAAATIAAArQAAAMgIAKQgHAKgMAEQAMADAIAKQAHAJAAANIAAA9QAAAUgNANQgPAOgSAAgAggBoIAyAAQAPAAAAgQIAAg7QAAgKgHgGQgHgHgKAAIgpAAgAgggXIApAAQAKAAAHgIQAHgGAAgKIAAgoQAAgPgPAAIgyAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.4,-13.5,12.9,27.2);


(lib.Анимация40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgOCHIAAkNIAdAAIAAENg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-13.5,3.2,27.2);


(lib.Анимация37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgOCHIAAjtIgrAAIAAggIBzAAIAAAgIgrAAIAADtg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.8,-13.5,11.7,27.2);


(lib.Анимация34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("Ag8CHIAAkNIAgAAIAABPIAoAAQAUAAAPAPQAHAHADAJQAEAJAAAKIAABaQAAAKgEAKQgDAJgHAGQgHAHgJAEQgJAEgKAAgAgcBoIAtAAQANAAAAgNIAAhlQAAgNgNAAIgtAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.1,-13.5,12.4,27.2);


(lib.Анимация31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgzB9QgMgMAAgTIAAhKQAAgTAOgMQAOgNATAAIAwAAIAAhAQAAgPgQAAIgcAAQgGAAgEAEQgFAEAAAHIAAAaIgfAAIAAgaQgBgUAOgOQAPgNATAAIAcAAQATAAAOAOQAOAOAAATIAADeIgaAAIgFgMIgiAMIgSACQgUAAgMgLgAgcAJQgEAFAAAGIAABHQAAAOAQAAIAFAAIArgQIAAhUIgwAAQgGAAgGAEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.4,-13.6,12.9,27.4);


(lib.Анимация28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgRCvQgSAAgOgOQgOgOAAgTIAAjPQAAgRAFgMQAFgMAKgHQAMgLAfgKQAQgFAGgEQAKgHAAgKIAgAAQAAANgFAKQgDAIgJAHQgJAIgdAJQgpALAAAcIAAAGIAigMIAOgDQAUAAAOANQAOAOAAAUIAACqQAAATgOAOQgPAOgTAAgAANg5IgtAQIAACpQAAAGAEAFQAFAFAFAAIAjAAQAQAAAAgQIAAiqQAAgQgQAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.4,-17.5,12.9,35.2);


(lib.Анимация25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgzB9QgMgMAAgTIAAhKQAAgTAOgMQAOgNASAAIAxAAIAAhAQAAgPgQAAIgbAAQgHAAgFAEQgEAEAAAHIAAAaIggAAIAAgaQAAgUAOgOQAPgNATAAIAcAAQAUAAAOAOQANAOAAATIAADeIgaAAIgFgMIgiAMIgSACQgTAAgNgLgAgbAJQgFAFAAAGIAABHQAAAOAPAAIAGAAIArgQIAAhUIgxAAQgFAAgFAEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.4,-13.6,12.9,27.4);


(lib.Анимация22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("Ag8CvIAAlbIAaAAIAGAMIAcgMQAGgCAJAAQATAAANANQAOAMAAATIAAC6QAAATgNAMQgNAMgVABQgIgBgGgCIgcgMIAABagAAJiOIglAPIAAC0IAlAOIAFABQAQAAAAgNIAAi3QAAgOgQAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.1,-17.5,12.3,35.1);


(lib.Анимация19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgzB9QgMgMAAgTIAAhKQAAgTAOgMQAPgNASAAIAxAAIAAhAQAAgPgQAAIgcAAQgGAAgFAEQgFAEABAHIAAAaIggAAIAAgaQAAgUAOgOQAOgNAUAAIAcAAQATAAAOAOQANAOAAATIAADeIgaAAIgFgMIghAMIgSACQgVAAgMgLgAgbAJQgEAFgBAGIAABHQABAOAPAAIAGAAIArgQIAAhUIgxAAQgGAAgFAEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.4,-13.6,12.9,27.4);


(lib.Анимация17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("AgICvQgTAAgOgOQgOgOAAgTIAAg2IAhAAIAAA2QAAAOAOAAIARAAQAOAAAAgOIAAhlQAAgPgHgFQgGgGgNAAIgQAAIAAgdIAQAAQAMAAAHgKQAHgJAAgOIAAhCQAAgOgOAAIgRAAQgOAAAAAOIAAAnIghAAIAAgnQAAgTAOgOQAOgOATAAIARAAQATAAAOAOQAOAOAAATIAABDQAAAPgHALQgGANgOAFQANAFAHAKQAHAIAAAOIAABrQAAATgOAOQgOAOgTAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.6,-17.5,11.4,35.2);


(lib.Анимация9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("ApqD0QgkAAAAgiIAAmiQAAgkAkAAITWAAQAiAAABAkIAAGiQgBAigiAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.5,-24.5,131,49);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация67("synched",0);
	this.instance.setTransform(9.7,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,19.3,27.2);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация64("synched",0);
	this.instance.setTransform(6.5,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,13,27.2);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация61("synched",0);
	this.instance.setTransform(9.7,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,19.3,27.2);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация58("synched",0);
	this.instance.setTransform(6.8,17.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,13.5,34.9);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация55("synched",0);
	this.instance.setTransform(5.9,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,11.8,27.2);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация52("synched",0);
	this.instance.setTransform(7.2,2);

	this.instance_1 = new lib.Анимация49("synched",0);
	this.instance_1.setTransform(7.2,21.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,14.4,35.5);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация46("synched",0);
	this.instance.setTransform(6.5,13.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.9,27.4);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация43("synched",0);
	this.instance.setTransform(6.5,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.9,27.2);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация40("synched",0);
	this.instance.setTransform(16.5,14);

	this.instance_1 = new lib.Анимация34("synched",0);
	this.instance_1.setTransform(6.2,13.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,18.1,27.6);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация37("synched",0);
	this.instance.setTransform(5.9,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,11.7,27.2);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация31("synched",0);
	this.instance.setTransform(6.5,13.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.9,27.4);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация28("synched",0);
	this.instance.setTransform(6.5,17.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.9,35.2);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация25("synched",0);
	this.instance.setTransform(6.5,13.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.9,27.4);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация22("synched",0);
	this.instance.setTransform(6.1,17.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.3,35.1);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация19("synched",0);
	this.instance.setTransform(6.5,13.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.9,27.4);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация17("synched",0);
	this.instance.setTransform(5.7,17.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,11.4,35.2);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация102("synched",0);
	this.instance.setTransform(103.2,123.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,206.3,246.9);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация104("synched",0);
	this.instance.setTransform(112.4,108.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,224.9,217.8);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация98("synched",0);
	this.instance.setTransform(45.9,71);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,91.7,142);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация100("synched",0);
	this.instance.setTransform(67.5,127.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,134.9,254.8);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// money-png-17_12.png
	this.instance = new lib.Символ22();
	this.instance.setTransform(24.4,-260.5,1,1,0,0,0,45.9,71);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:30,x:24.3,y:342.1},69).wait(1));

	// money-png-17_08.png
	this.instance_1 = new lib.Символ21();
	this.instance_1.setTransform(-140.5,-169.7,1,1,0,0,0,67.5,127.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:-15,y:432.9},69).wait(1));

	// money-png-17_06.png
	this.instance_2 = new lib.Символ24();
	this.instance_2.setTransform(282.7,-185,1,1,0,0,0,103.2,123.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({rotation:15,y:417.5},69).wait(1));

	// money-png-17_03.png
	this.instance_3 = new lib.Символ23();
	this.instance_3.setTransform(105.4,-191.6,1,1,0,0,0,112.4,108.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({rotation:-15,y:410.9},69).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-208,-331.5,593.8,289.2);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ26();
	this.instance.setTransform(5.7,18,1,1,0,0,0,5.7,17.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:14.5},9).to({y:18},75).wait(1));

	// Слой 4
	this.instance_1 = new lib.Символ27();
	this.instance_1.setTransform(21.6,21.7,1,1,0,0,0,6.5,13.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({y:18.2},9).to({y:21.7},71).wait(1));

	// Слой 5
	this.instance_2 = new lib.Символ28();
	this.instance_2.setTransform(37.6,25.4,1,1,0,0,0,6.1,17.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({y:21.9},9).to({y:25.4},66).wait(1));

	// Слой 6
	this.instance_3 = new lib.Символ29();
	this.instance_3.setTransform(53.7,21.7,1,1,0,0,0,6.5,13.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(14).to({y:18.2},9).to({y:21.7},61).wait(1));

	// Слой 7
	this.instance_4 = new lib.Символ30();
	this.instance_4.setTransform(70.1,17.6,1,1,0,0,0,6.5,17.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(19).to({y:14.1},9).to({y:17.6},56).wait(1));

	// Слой 8
	this.instance_5 = new lib.Символ31();
	this.instance_5.setTransform(86.5,21.7,1,1,0,0,0,6.5,13.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(24).to({y:18.2},9).to({y:21.7},51).wait(1));

	// Слой 10
	this.instance_6 = new lib.Символ32();
	this.instance_6.setTransform(101,21.6,1,1,0,0,0,5.9,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(29).to({y:18.1},9).to({y:21.6},46).wait(1));

	// Слой 9
	this.instance_7 = new lib.Символ33();
	this.instance_7.setTransform(118.1,21.8,1,1,0,0,0,9,13.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(34).to({y:18.3},9).to({y:21.8},41).wait(1));

	// Слой 12
	this.instance_8 = new lib.Символ34();
	this.instance_8.setTransform(137.8,21.6,1,1,0,0,0,6.5,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(39).to({y:18.1},9).to({y:21.6},36).wait(1));

	// Слой 13
	this.instance_9 = new lib.Символ35();
	this.instance_9.setTransform(154.2,21.7,1,1,0,0,0,6.5,13.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(44).to({y:18.2},9).to({y:21.7},31).wait(1));

	// Слой 14
	this.instance_10 = new lib.Символ36();
	this.instance_10.setTransform(171.3,17.5,1,1,0,0,0,7.2,17.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(49).to({y:14},9).to({y:17.5},26).wait(1));

	// Слой 16
	this.instance_11 = new lib.Символ37();
	this.instance_11.setTransform(196.9,21.6,1,1,0,0,0,5.9,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(54).to({y:18.1},9).to({y:21.6},21).wait(1));

	// Слой 17
	this.instance_12 = new lib.Символ38();
	this.instance_12.setTransform(220.8,25.4,1,1,0,0,0,6.8,17.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(59).to({y:21.9},9).to({y:25.4},16).wait(1));

	// Слой 18
	this.instance_13 = new lib.Символ39();
	this.instance_13.setTransform(239.8,21.6,1,1,0,0,0,9.7,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(64).to({y:18.1},9).to({y:21.6},11).wait(1));

	// Слой 19
	this.instance_14 = new lib.Символ40();
	this.instance_14.setTransform(259.4,21.6,1,1,0,0,0,6.5,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(69).to({y:18.1},9).to({y:21.6},6).wait(1));

	// Слой 20
	this.instance_15 = new lib.Символ41();
	this.instance_15.setTransform(279,21.6,1,1,0,0,0,9.7,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(74).to({y:18.1},9).wait(1).to({y:21.6},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-0.3,288.6,43.3);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dib();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ10();
	this.instance_1.setTransform(103.5,131.6,1,1,0,0,0,103.3,127.7);
	this.instance_1.alpha = 0.43;
	this.instance_1.filters = [new cjs.BlurFilter(24, 24, 1)];
	this.instance_1.cache(-2,-2,211,260);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.8,-8.1,295.8,284);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ9();
	this.instance.setTransform(142,125,1,1,0,0,0,142,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:127.3},14,cjs.Ease.get(-1)).to({y:125},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.8,-8.1,295.8,284);


(lib.Символ4копия = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}
	this.frame_49 = function() {
		this.stop();
	}
	this.frame_59 = function() {
		this.stop();
	}
	this.frame_69 = function() {
		this.stop();
	}
	this.frame_79 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(10).call(this.frame_49).wait(10).call(this.frame_59).wait(10).call(this.frame_69).wait(10).call(this.frame_79).wait(1));

	// Слой 3
	this.instance = new lib.Анимация89("synched",0);
	this.instance.setTransform(101.1,-226.3);

	this.instance_1 = new lib.Анимация90("synched",0);
	this.instance_1.setTransform(101.1,-162.3);
	this.instance_1._off = true;

	this.instance_2 = new lib.Анимация91("synched",0);
	this.instance_2.setTransform(101.1,-97.5);
	this.instance_2._off = true;

	this.instance_3 = new lib.Анимация92("synched",0);
	this.instance_3.setTransform(101.1,-33.5);
	this.instance_3._off = true;

	this.instance_4 = new lib.Анимация93("synched",0);
	this.instance_4.setTransform(101.1,30.6);
	this.instance_4._off = true;

	this.instance_5 = new lib.Анимация94("synched",0);
	this.instance_5.setTransform(101.1,95.3);
	this.instance_5._off = true;

	this.instance_6 = new lib.Анимация95("synched",0);
	this.instance_6.setTransform(101.1,159.7);
	this.instance_6._off = true;

	this.instance_7 = new lib.Анимация96("synched",0);
	this.instance_7.setTransform(101.1,224.1);
	this.instance_7._off = true;

	this.instance_8 = new lib.Анимация97("synched",0);
	this.instance_8.setTransform(101.1,288.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},9).to({state:[{t:this.instance_2}]},10).to({state:[{t:this.instance_3}]},10).to({state:[{t:this.instance_4}]},10).to({state:[{t:this.instance_5}]},10).to({state:[{t:this.instance_6}]},10).to({state:[{t:this.instance_7}]},10).to({state:[{t:this.instance_8}]},10).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true,y:-162.3},9).wait(71));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:false},9).to({_off:true,y:-97.5},10).wait(61));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},10).to({_off:true,y:-33.5},10).wait(51));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(19).to({_off:false},10).to({_off:true,y:30.6},10).wait(41));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(29).to({_off:false},10).to({_off:true,y:95.3},10).wait(31));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(39).to({_off:false},10).to({_off:true,y:159.7},10).wait(21));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(49).to({_off:false},10).to({_off:true,y:224.1},10).wait(11));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(59).to({_off:false},10).to({_off:true,y:288.2},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(93.2,-503.9,15.8,555.1);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_79 = function() {
		this.parent.second.play();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(79).call(this.frame_79).wait(11));

	// Слой 4
	this.instance = new lib.Анимация87("synched",0);
	this.instance.setTransform(108.8,-257.4);

	this.instance_1 = new lib.Анимация88("synched",0);
	this.instance_1.setTransform(108.8,322.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance}]},9).to({state:[{t:this.instance}]},10).to({state:[{t:this.instance}]},10).to({state:[{t:this.instance}]},10).to({state:[{t:this.instance}]},10).to({state:[{t:this.instance}]},10).to({state:[{t:this.instance}]},10).to({state:[{t:this.instance}]},10).to({state:[{t:this.instance_1}]},10).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-191.8},9).to({y:-128.4},10).to({y:-64.1},10).to({y:0.7},10).to({y:65},10).to({y:129.7},10).to({y:193.8},10).to({y:258.4},10).to({_off:true,y:322.9},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(100.8,-569.1,15.8,619.5);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ApqD0QgkAAAAgiIAAmiQAAgkAkAAITWAAQAiAAABAkIAAGiQgBAigiAAg");
	mask.setTransform(65.5,24.5);

	// Слой 5
	this.instance = new lib.Символ5();
	this.instance.setTransform(48.3,26.1,1,1,0,0,0,40.1,33.6);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2 - копия
	this.second = new lib.Символ4копия();
	this.second.setTransform(55,25.9,1,1,0,0,0,57.1,33.6);

	this.second.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.second).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ4();
	this.instance_1.setTransform(65.7,26.2,1,1,0,0,0,57.1,33.6);

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 1
	this.instance_2 = new lib.Анимация9("synched",0);
	this.instance_2.setTransform(65.5,24.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,49);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AtFBiIAAieIAMAAIADAFIANgFIAHgBQAJAAAGAGQAGAFAAAJIAABUQAAAJgFAGQgGAFgKAAIgHgBIgNgFIAAApgAskguIgSAHIAABRIASAGIACABQAHAAAAgGIAAhTQAAgHgHAAgAw7BVIAAgXIg7AAIAAAXIgOAAIAAglIAKAAQAEgLAEgYIABgiIAAgnIA5AAIAABsIALAAIAAAlgAxjgVQAAAugIAXIAlAAIAAhdIgdAAgAQ6AxQAFAAADgEQACgDACgHQABgKAAgZIAAgmQAAgJAHgGQAGgGAJAAIAhAAIAAB6IgOAAIAAhsIgTAAQgHAAAAAHIAAAmQAAAggEAMQgDAKgFAEQgGAGgKAAgA1UA6QgGgFAAgJIAAgiQAAgJAHgEQAGgGAJAAIAXAAIAAgdQAAgHgHAAIgOAAQgDAAgCACQgCABAAAEIAAAMIgOAAIAAgNQAAgIAGgHQAGgGAJAAIAOAAQAJAAAGAHQAGAGAAAIIAABlIgLAAIgDgFIgQAFIgIABQgKAAgFgFgA1JAFQgCACAAADIAAAgQAAAHAHAAIACAAIAVgHIAAgnIgXAAQgDAAgCACgAWYA/IgWg8IgHAAIAAA8IgPAAIAAh6IAPAAIAAAyIALAAQAEAAADgDQADgDAAgEIAAgSQAAgJAGgHIAHgFQAEgBAFAAIABAAIAAAOIgBAAQgIAAAAAIIAAATQAAAHgEAFQgDAGgHABIAXA+gAU5A/QgJAAgGgHQgGgGAAgJIAAhPQAAgJAGgGQAHgGAIAAIAOAAQAJAAAGAGQAHAGAAAJIAAApIgrAAIAAAmQAAAHAHAAIAOAAQAHAAAAgHIAAgTIAPAAIAAATQAAAJgHAGQgGAHgJAAgAUygmIAAAdIAcAAIAAgdQAAgHgHAAIgOAAQgHAAAAAHgATZA/IAAh6IAmAAQAIAAAHAGQAGAGAAAJIAAAUQAAAFgEAFQgDAEgFACQAFACAEADQADAFAAAFIAAAcQAAAJgGAGQgHAHgIAAgATnAwIAYAAQAHAAAAgHIAAgbQAAgEgDgDQgEgEgEAAIgUAAgATngJIAUAAQAEAAAEgDQADgDAAgFIAAgSQAAgHgHAAIgYAAgASjA/QgJAAgGgHQgGgGAAgJIAAhPQAAgJAGgGQAGgGAJAAIARAAQAJAAAGAGQAGAGAAAJIAABPQAAAJgGAGQgGAHgJAAgAScgmIAABPQAAAHAHAAIARAAQAHAAAAgHIAAhPQAAgHgHAAIgRAAQgHAAAAAHgAQNA/QgJAAgGgHQgGgGAAgJIAAhPQAAgJAGgGQAHgGAIAAIAOAAQAJAAAGAGQAHAGAAAJIAAApIgrAAIAAAmQAAAHAHAAIAOAAQAHAAAAgHIAAgTIAPAAIAAATQAAAJgHAGQgGAHgJAAgAQGgmIAAAdIAcAAIAAgdQAAgHgHAAIgOAAQgHAAAAAHgAPaA/IAAgtIgWAAQgFAAgEgCQgEgCgEgDQgDgDgBgEQgCgEAAgDIAAg4IAOAAIAAA6QAAAEAGAAIAZAAIAAg+IAOAAIAAB6gAo8A+IAAhrIgUAAIAAgPIA2AAIAAAPIgUAAIAABrgAqAA+QgJAAgHgGQgGgHAAgIIAAgmIgRAAIAAA7IgOAAIAAh6IAOAAIAAAzIARAAIAAgeQAAgIAGgHQAHgGAJAAIAQAAQAJAAAHAGQAGAHAAAIIAABQQAAAJgGAGQgHAGgJAAgAqHgmIAABPQAAAHAHAAIAQAAQAHAAAAgHIAAhPQAAgHgHAAIgQAAQgHAAAAAHgArTA+IAAg7IgLAAIgTA7IgPAAIATg8QgIgCgFgFQgFgHAAgIIAAgTQAAgIAGgHQAHgGAIAAIAlAAIAAB6gArxgmIAAASQAAAEADAEQAEADAEAAIATAAIAAgkIgXAAQgHAAAAAHgAt4A+QgJAAgGgGQgGgHAAgIIAAhQQAAgIAGgHQAHgGAIAAIAOAAQAJAAAGAGQAHAHAAAIIAAAqIgrAAIAAAmQAAAHAHAAIAOAAQAHAAAAgHIAAgUIAPAAIAAAUQAAAJgHAGQgGAGgJAAgAt/gmIAAAdIAcAAIAAgdQAAgHgHAAIgOAAQgHAAAAAHgAvYA+IAAh6IAmAAQAIAAAHAGQAGAHAAAJIAAATQAAAGgEAEQgDAFgFACQAFABAEAEQADAEAAAGIAAAcQAAAJgGAGQgHAGgIAAgAvKAwIAYAAQAHAAAAgHIAAgbQAAgFgDgDQgEgDgEAAIgUAAgAvKgJIAUAAQAEAAAEgEQADgDAAgEIAAgSQAAgHgHAAIgYAAgAwOA+QgJAAgGgGQgGgGAAgJIAAhPQAAgJAGgHQAGgGAJAAIARAAQAJAAAGAGQAGAHAAAJIAABPQAAAJgGAGQgGAGgJAAgAwVgmIAABPQAAAHAHAAIARAAQAHAAAAgHIAAhPQAAgHgHAAIgRAAQgHAAAAAHgAzFA+IAFhnIgaBnIgRAAIgahnIAFBnIgPAAIAAh6IAUAAIAYBlIAahlIATAAIAAB6gA16A+IAAhOIgcAAIAABOIgQAAIAAifIAQAAIAABDIAcAAIAAhDIAPAAIAACfg");
	this.shape.setTransform(60.3,42.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.setTransform(79.9,24.5,1,1,0,0,0,65.5,24.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84.4,-576.5,289.5,628.8);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_14 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(14).call(this.frame_14).wait(11));

	// Слой 1
	this.instance = new lib.Символ20();
	this.instance.setTransform(335.5,476,1,1,0,0,0,127.5,144.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14).to({alpha:0},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,593.8,289.2);


// stage content:



(lib.stforex = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		stage.canvas.addEventListener("mouseover", fl_Clickover.bind(this));
		
		function fl_Clickover()
		{
		    this.money.gotoAndPlay(1);
		   
		}
		
		stage.canvas.addEventListener("mouseout", fl_Clickout.bind(this));
		
		function fl_Clickout()
		{
		    this.money.gotoAndPlay(15);
		    
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// text2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#212B37").s().p("ATVCVIAHg2IgTAAIgci7IAXAAIAZCmIADAAIAWimIAWAAIgiDxgADzCVIAAjxIASAAIAEAIIAUgIQAGgBAFAAQANAAAKAIQAJAJAAANIAACBQAAANgJAJQgIAIgPAAQgGAAgFgBIgUgIIAAA+gAEJg9IAAB9IAbAKIADABQALgBAAgIIAAiAQAAgJgLgBIgDAAgAicCVIAAjxIASAAIADAIIAVgIQAFgBAHAAQAMAAAJAIQAKAJAAANIAACBQAAANgJAJQgJAIgOAAQgGAAgFgBIgVgIIAAA+gAiHg9IAAB9IAcAKIAEABQAKgBABgIIAAiAQgBgJgKgBIgEAAgAmxCVIAAg2IhcAAIAAA2IgYAAIAAhNIAOAAQAGgKADgOQADgNACgPQADgVABghIAAhyIBXAAIAADcIATAAIAABNgAnvgiQABAfgDAVQgGAlgHARIA5AAIAAjFIgqAAgAvFCVIAAjxIASAAIADAIIAUgIQAGgBAGAAQANAAAJAIQAJAJAAANIAACBQABANgKAJQgIAIgOAAQgGAAgGgBIgUgIIAAA+gAuwg9IAAB9IAbAKIAEABQALgBAAgIIAAiAQAAgJgLgBIgEAAgA1hCVIAAg2IhbAAIAAA2IgYAAIAAhNIAOAAQAFgKAEgOQAEgNABgPQAEgVAAghIAAhyIBXAAIAADcIAUAAIAABNgA2egiQAAAfgCAVQgGAlgHARIA5AAIAAjFIgqAAgASRCDIAAgkIhZAAIAAAkIgWAAIAAg5IAPAAQAHgSAGgjQABgTAAgjIAAg7IBXAAIAACmIARAAIAAA5gARWghQAABHgNAkIA3AAIAAiQIgqAAgAWhBfIAAilIgeAAIAAgWIBRAAIAAAWIgdAAIAAClgAU+BfQgOAAgJgKQgKgKABgNIAAh5QAAgOAJgKQAKgJANAAIAVAAQANAAAKAJQAKALAAANIAABAIhBAAIAAA5QAAAMALAAIAVAAQALAAAAgMIAAgeIAWAAIAAAeQAAANgKALQgKAJgNAAgAUzg7IAAAsIArAAIAAgsQAAgLgLAAIgVAAQgLAAAAALgAP/BfIAAhaIgwAAIAABaIgWAAIAAi7IAWAAIAABNIAwAAIAAhNIAVAAIAAC7gANsBfQgOAAgKgKQgJgKAAgNIAAh5QAAgOAKgKQAJgJAOAAIAVAAQANAAAJAJQALALAAANIAABAIhCAAIAAA5QAAAMAMAAIAVAAQALAAgBgMIAAgeIAXAAIAAAeQAAANgLALQgJAJgNAAgANgg7IAAAsIArAAIAAgsQABgLgLAAIgVAAQgMAAAAALgAMdBfIAAhIIAHhWIgoCeIgbAAIgmieIAHBXIAABHIgWAAIAAi7IAdAAIAmCaIAmiaIAdAAIAAC7gAJaBfQgOAAgJgJQgJgKAAgOIAAh5QAAgNAJgLQAJgJAOAAIAZAAQANAAAKAJQAKALAAANIAAB5QAAAOgKAKQgKAJgNAAgAJPg7IAAB5QAAAMALAAIAZAAQALAAAAgMIAAh5QAAgLgLAAIgZAAQgLAAAAALgAIRBfIgihaIgLAAIAABaIgVAAIAAi7IAVAAIAABNIASAAQAHAAADgFQAFgEAAgGIAAgbQAAgPAKgKQAEgFAHgDQAFgCAHAAIACAAIAAAWIgCAAQgLAAgBANIAAAcQAAAKgFAJQgGAIgJADIAiBegAGBBfQgNAAgLgKQgIgKgBgNIAAh5QAAgOAKgKQAKgJANAAIAVAAQAOAAAJAJQAKALAAANIAABAIhBAAIAAA5QAAAMALAAIAVAAQALAAAAgMIAAgeIAWAAIAAAeQAAANgKALQgJAJgOAAgAF2g7IAAAsIArAAIAAgsQAAgLgLAAIgVAAQgLAAAAALgABCBfIAAi7IA5AAQANAAAKAJQAKALAAANIAAAeQgBAIgFAHQgEAHgJADQAJACAFAGQAFAHAAAJIAAAqQgBAOgIAKQgLAJgNAAgABYBKIAjAAQALAAAAgMIAAgpQAAgGgFgGQgEgEgIAAIgdAAgABYgPIAdAAQAIAAAEgFQAFgFAAgGIAAgcQAAgLgLAAIgjAAgAgOBfQgNAAgKgJQgKgKABgOIAAh5QgBgNAKgLQAKgJANAAIAXAAQAOAAAJAJQAKALAAANIAAB5QAAAOgKAKQgJAJgOAAgAgZg7IAAB5QAAAMALAAIAXAAQALAAAAgMIAAh5QAAgLgLAAIgXAAQgLAAAAALgAjtBfQgOAAgKgKQgJgJAAgOIAAiQQAAgMADgIQAEgIAHgGQAIgHAWgGQAMgEAFgDQAGgFABgHIAWAAQgBAJgCAHQgDAGgGAFQgHAFgTAHQgfAHAAATIAAAFIAZgIIAKgDQAOAAAKAKQAKAKAAANIAAB2QAAANgKALQgLAJgNAAgAjZhCIggAKIAAB2QABAEADAEQACAEAFAAIAZAAQALAAAAgMIAAh2QAAgLgLAAgAk8BfIAAhOIAGhXIg3ClIgeAAIAAi7IAWAAIAABYIgGBOIA3imIAdAAIAAC7gAqMBfIAAhOIAFhXIg2ClIgeAAIAAi7IAVAAIAABYIgFBOIA3imIAeAAIAAC7gAsJBfIAAhOIAFhXIg2ClIgeAAIAAi7IAVAAIAABYIgFBOIA3imIAdAAIAAC7gAwJBfIAAilIgeAAIAAgWIBRAAIAAAWIgdAAIAAClgAxMBfIAAhOIAFhXIg2ClIgeAAIAAi7IAVAAIAABYIgFBOIA3imIAdAAIAAC7gAzJBfIAAhIIAHhWIgoCeIgbAAIgnieIAIBXIAABHIgWAAIAAi7IAdAAIAmCaIAmiaIAdAAIAAC7gAq1h4QgLAAgGgIQgHgHAAgKIAAgDIARAAIAAAEQABAHAGAAIAWAAQAHAAAAgHIAAgEIARAAIAAADQAAAKgHAHQgHAIgJAAg");
	this.shape.setTransform(430,-68.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// text
	this.instance = new lib.Символ12();
	this.instance.setTransform(434.5,96.7,1,1,0,0,0,144.3,21.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// schet
	this.instance_1 = new lib.Символ1();
	this.instance_1.setTransform(440.1,174,1,1,0,0,0,65.5,24.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// btn
	this.instance_2 = new lib.Символ13();
	this.instance_2.setTransform(438.7,258,1,1,0,0,0,110.2,40);
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// logo
	this.instance_3 = new lib.logostforexcom2();
	this.instance_3.setTransform(326.8,5.5,0.878,0.878);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// dibro
	this.instance_4 = new lib.Символ8();
	this.instance_4.setTransform(147.5,175.5,1,1,0,0,0,142,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// money
	this.money = new lib.Символ25();
	this.money.setTransform(299.4,-57,1,1,0,0,0,296.9,238);

	this.timeline.addTween(cjs.Tween.get(this.money).wait(1));

	// fon
	this.instance_5 = new lib.Символ19();
	this.instance_5.setTransform(322.4,169.5,1,1,0,0,0,328.4,205.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(293.7,-277,657.2,802.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;