(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bg.jpg", id:"bg"},
		{src:"images/canada_big.png", id:"canada_big"},
		{src:"images/iihf_logo.png", id:"iihf_logo"},
		{src:"images/logo.jpg", id:"logo"},
		{src:"images/maska_01.png", id:"maska_01"},
		{src:"images/maska_02.png", id:"maska_02"},
		{src:"images/maska_03.png", id:"maska_03"},
		{src:"images/maska_05.png", id:"maska_05"},
		{src:"images/maska_06.png", id:"maska_06"},
		{src:"images/maska_07.png", id:"maska_07"},
		{src:"images/pole.png", id:"pole"},
		{src:"images/rus_big.png", id:"rus_big"}
	]
};



// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.canada_big = function() {
	this.initialize(img.canada_big);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,243,241);


(lib.iihf_logo = function() {
	this.initialize(img.iihf_logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,76,109);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,144,43);


(lib.maska_01 = function() {
	this.initialize(img.maska_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,144,145);


(lib.maska_02 = function() {
	this.initialize(img.maska_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,145,145);


(lib.maska_03 = function() {
	this.initialize(img.maska_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,151,145);


(lib.maska_05 = function() {
	this.initialize(img.maska_05);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,146,157);


(lib.maska_06 = function() {
	this.initialize(img.maska_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,151,157);


(lib.maska_07 = function() {
	this.initialize(img.maska_07);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,143,156);


(lib.pole = function() {
	this.initialize(img.pole);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,184);


(lib.rus_big = function() {
	this.initialize(img.rus_big);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,230,227);


(lib.Символ38 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.maska_07();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,143,156);


(lib.Символ37 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.maska_06();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,157);


(lib.Символ36 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.maska_05();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,146,157);


(lib.Символ33 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.maska_03();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,145);


(lib.Символ32 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.maska_02();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,145,145);


(lib.Символ31 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.maska_01();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,144,145);


(lib.Символ29 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmhA5QgBAAAAAAQgBAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIACgOIgvAAIgDAOIgCAEQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgPAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAFggQAAAAABgBQAAgBAAAAQAAgBABAAQAAgBAAAAIAFgBIADAAIAFgFIAFgHIADgIIAIgqQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAQABAAABAAIA4AAQABAAABAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAABIgLA+IAGAAIAEABQAAAAABABQAAAAAAABQAAAAAAABQgBABAAAAIgFAgQAAABgBABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQgBAAgBAAgAm2gTQgCAMgDAHQgDAIgEAGIAXAAIAIgtIgRAAgAkwAnIgDgEIgFgMQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIAEgDIAHgFIAGgGIAEgIIADgOIAGgeQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIA4AAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAABIgOBPIgCAFIgFABIgOAAIgEgBQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIALg+IgPAAIgCAMQgEASgCAEQgGAMgDAFQgFAGgGAFIgMAHIgDABIgBAAgABNAkIgGgDQgDgCgCgDIgEgFIgCgHIgBgHIABgIIAEgWQABgGAEgJIAFgGIAFgFQAEgDAKgDQAFgCAMgBQAHAAAGACQAFABAEADQAEADADAFQACAEABAGQABAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQgBACgDABIgNAEQgBABgBAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAQgBgFgCgCQgDgCgGAAIgGABQgDABgCACIgDAEIgCAGIgFAVIAAAGIACAFIAEACIAGABQAFAAAEgCQAEgCACgFIAEgDQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABIANAFQABAAABABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAABAAAAQgDAGgFAEIgJAHIgMAEQgGACgHAAQgMgBgFgCgAokAkIgGgDQgDgCgCgDIgEgFIgCgHIgBgHIABgIIAEgWQABgGAEgJIAFgGIAFgFQAEgDAKgDQAFgCAMgBQAHAAAGACQAFABAEADQAEADADAFQACAEABAGQAAAAABABQAAABAAAAQAAABAAAAQgBABAAAAQgBACgDABIgNAEQgBABgBAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAQgBgFgCgCQgDgCgGAAIgGABQgDABgCACIgDAEIgCAGIgFAVIAAAGIACAFIAEACIAGABQAFAAAEgCQAEgCACgFIAEgDQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABIANAFQABAAABABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAABAAAAQgDAGgFAEIgJAHIgMAEQgGACgHAAQgMgBgFgCgAHqAlQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBIABgEIAOgWIgRg5QgCgGAFAAIAQAAQAFAAABABQABAAAAABQABAAAAABQAAAAAAABQABABAAAAIAIAdIARgdQABgDACgBIAGgBIAQAAQABAAABAAQAAAAABABQAAAAAAAAQABAAAAABIgCAEIgxBQIgDAEIgHABgAHCAlIgHgBQgDgBgBgEIgHgXIgDgFQgBgBgEAAIgCAAIgFAdQAAABgBABQAAAAAAABQAAAAgBABQAAAAAAABIgFABIgOAAQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAOhPIACgEQABgBAAAAQABAAAAAAQABgBAAAAQABAAABAAIAPAAQAAAAABAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAABIgFAdIADAAIAYgeIAEgEIAHgBIAPAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQgBAAAAABQAAABgBAAIgfAmIAEAEIADAGIALAeQAAABABABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAgAE2AlQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQABgBAAgBIAOhPIACgEQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIAmAAQAHAAAFACQAFACADADQAEAEABAEQABAFgBAGQgBAGgDAFQgDAEgGADIAAABQAMAFgDAQQgBAGgDAFQgDAEgFADQgFAEgGABQgGACgHAAgAFOAQIAPAAQAEAAADgCQACgCABgEQAAgEgBgCQgCgBgEAAIgPAAgAFUgSIANAAQAEAAACgCQACgCABgDQABgEgCgCQgCgCgEAAIgMAAgAEbAlIgHgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAgBAAgBIgBgJIgcAAIgFAJIgEAFIgGABIgPAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABgBIAshQIADgEIAFgBIAPAAIAEABQAAAAAAABQABAAAAABQAAAAAAABQABAAAAABIAPBQQAAABAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAgAEOACIgCgOIAAgPIABgDIgBAAQgDAMgDAGIgIAOIAQAAgACjAlQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIALg+IgTAAQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIADgMQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABgBABAAQAAAAABAAIBAAAQABAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAABIgCAMQAAABgBAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAIgTAAIgLA+QAAABgBABQAAAAAAABQAAAAgBABQAAAAAAABIgFABgAguAlQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQABgBAAgBIAOhPIACgEQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIAPAAQABAAABAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABIgEAWIAOAAQAGAAAGACQAGADAEAEQAEAFABAGQABAGgBAGQgCAHgDAGQgDAGgFAEQgFAEgGACQgEACgIAAgAgWAOIANAAQAFAAADgDQABgCAAgFQABgEgBAAQgBgDgEAAIgNAAgAhoAlQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIALg+IgTAAQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIADgMQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABgBABAAQAAAAABAAIBAAAQABAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAABIgCAMQAAABgBAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAIgTAAIgLA+QAAABgBABQAAAAAAABQAAAAgBABQAAAAAAABIgFABgAiXAlIgHgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIgBgJIgcAAIgFAJIgEAFIgGABIgPAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABgBIAshQIADgEIAFgBIAPAAIAEABQAAAAAAABQABAAAAABQAAAAAAABQABAAAAABIAPBQQAAABAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAgAikACIgCgOIAAgPIABgDIgBAAQgDAMgDAGIgIAOIAQAAgAl7AlQgBAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAOhPIACgEQABgBAAAAQABAAAAAAQABgBAAAAQABAAABAAIA2AAQABAAABAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABIgCAMQAAABgBAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAIgiAAIgCAMIAbAAQABAAABAAQABAAAAAAQABAAAAABQAAAAABAAIAAAEIgCAMQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAIgbAAIgCAMIAjAAIAEABQABAAAAABQAAAAAAABQAAAAAAABQAAABAAAAIgCAMQAAABgBABQAAAAAAABQAAAAgBABQAAAAAAABIgFABg");
	this.shape.setTransform(56.7,5.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,113.5,11.5);


(lib.Символ27 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0948B0").s().p("ArAD0QhjABgBhlIAAkgQABhjBjgBIWBAAQBjABABBjIAAEgQgBBlhjgBg");
	this.shape.setTransform(80.5,24.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,161,49);


(lib.Символ24 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D22D27").s().p("AJICLQgKgEgJgGQgIgFgHgJQgHgHgEgJQgEgJgDgKQgCgLAAgLIAPhdQADgQAMgdIANgSIAQgPQAMgJAdgLQAPgFAlgCIAaACQANABAKAEQALAFAIAGQAJAFAGAIQAHAIAEAJQAFAJACAKQACAKAAAMIgOBdQgJAggHANIgNARIgQAQQgZAPgPAFQghAGgTABQgkgEgOgEgAKMhGQgIADgGAEQgHAFgEAHQgEAHgBAJIgOBMQgBAJABAHQACAHAEAFQAFAEAIADQAHACAKAAQArAAAHglIANhMQACgIgCgIQgBgGgFgGQgFgEgHgDQgHgCgLAAQgKAAgJACgAAxCLQgKgEgJgGQgIgFgHgJQgHgHgEgJQgEgJgBgKQgCgLAAgLIANhdQADgQAMgdIANgSIAQgPQAMgJAdgLQAPgFAlgCIAaACQANABAKAEQALAFAIAGQAJAFAGAIQAHAIAEAJQAFAJACAKQACAKAAAMIgOBdQgJAggHANIgNARIgQAQQgZAPgPAFQghAGgTABQgkgEgOgEgAB1hGQgIADgGAEQgHAFgEAHQgEAHgBAJIgOBMQgBAJABAHQACAHAEAFQAFAEAIADQAHACAKAAQArAAAHglIANhMQACgIgCgIQgBgGgFgGQgFgEgHgDQgHgCgLAAQgKAAgJACgASYCPQgRABgGgHQgFgGADgRIACgPQADgQAIgHQAIgHASAAIATAAQARAAAGAHQAFAGgCARIgDAPQgDARgIAGQgIAHgRgBgAPqCMQgJAAgDgDQgDgDABgKIAKg3QAEgVAIgaQAJgYAOgdIgEAAQgQAfgWAfIgdAsQgIALgNAAIgZAAQgIAAgDgCQgEgCgCgHIgPgsQgGgQgHguIgEAAQADAfAAAYQgBAagEATIgJA3QgCAKgEADQgEADgKAAIgpAAQgJAAgDgDQgDgDABgKIAsjyQABgKAEgDQAFgEAJAAIAkAAQALAAAEACQAEADACAHIAqB+IBXh9QAFgIAEgDQAFgCAKAAIAnAAQAKAAACAEQADADgBAKIgrDyQgCAKgEADQgEADgJAAgAGdCMQgKAAgDgDQgDgEACgJIAQhaIhMAAIgQBaQgBAJgEAEQgFADgJAAIgsAAQgJAAgDgDQgDgEABgJIAsjyQACgKAEgDQAEgEAJAAIAsAAQAJAAADAEQADADgBAKIgQBXIBMAAIAPhXQABgKAFgDQAEgEAKAAIAsAAQAJAAADAEQADADgCAKIgrDyQgCAJgEAEQgEADgJAAgAh4CMQgJAAgDgDQgDgEABgKIAYhzIAUgtIgDAAQgiA4gRAWIhFBbQgHAJgLgBIgwAAQgJAAgDgDQgDgEACgJIArjyQABgJAFgEQAEgDAJgBIAsAAQAKABADADQADAEgCAJIgLBCQgGAegGATQgEAMgQAiIADAAIAzhPIBGhbQAGgIALAAIAvAAQAJAAADAEQADADgBAKIgrDyQgCAJgEAEQgFADgJAAgAmLCMQgJAAgDgDQgDgEABgJIAii+IhJAAIgiC+QgCAJgEAEQgEADgKAAIgsAAQgJAAgDgDQgDgEACgJIArjyQACgKAEgDQAEgDAJgBIDDAAQAJABADADQADAEgBAJIgsDyQgBAJgEAEQgFADgJAAgAqVCMQgKAAgDgDQgDgDACgKIAKg3QADgVAJgaQAJgYANgdIgEAAQgPAfgWAfIgeAsQgHALgNAAIgaAAQgHAAgEgCQgDgCgCgHIgPgsQgGgQgIguIgDAAQADAfgBAYQgBAagDATIgKA3QgBAKgFADQgEADgJAAIgqAAQgJAAgDgDQgDgDACgKIArjyQABgKAFgDQAEgEAKAAIAkAAQAKAAAEACQAFADACAHIAqB+IBWh9QAFgIAFgDQAEgCAKAAIAoAAQAJAAADAEQADADgCAKIgrDyQgCAKgEADQgEADgJAAgAxJCMQgKAAgDgDQgDgEACgJIArjyQACgKAEgDQAEgDAKgBICjAAQAJABADADQAEAEgCAJIgGAjQgCAKgEADQgFAEgJAAIhnAAIgGAjIBSAAQAKAAADADQACAEgBAJIgGAhQgCAKgEADQgFAEgJAAIhSAAIgHAlIBrAAQAJAAADAEQACADgBAJIgGAkQgCAJgEAEQgEADgKAAgAy2CMQgKAAgDgDQgDgEACgJIANhMQgRADgXAAQgjgDgNgFQgJgDgIgGQgHgGgFgGQgGgIgDgIQgDgIgCgKQgCgPAEgiIALg5QABgJAEgEQAEgDAKgBIAsAAQAJABADADQADAEgBAJIgMA/QgBAKABAGQABAHAEAEQAEAEAIADQAIABAMAAQARAAAMgCIARhgQACgKAEgDQAEgDAKgBIAsAAQAJABADADQADAEgCAJIgrDyQgCAJgEAEQgEADgJAAgASfA4QgJAAgCgEQgDgCACgJQACgNAEgKQADgKAGgIQAKgLASgJIAagOIAKgHQALgIACgPQACgKgGgGQgGgGgOAAQgQAAgJAGQgLAGgKARQgGAJgEACQgFACgIgDIghgOQgIgEgBgEQgCgEAFgKQAJgQALgLQAMgMANgIQAOgIARgEQASgDAVgBQAYABATAFQASAGANALQAMAMAFAPQAFAPgEASQgBAMgFALQgEAJgHAJQgLAOgQAIIgnATQgQAKgCAMQgBAJgEACQgEAEgJAAg");
	this.shape.setTransform(134,14.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,268,29.4);


(lib.Символ23 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0948B0").s().p("AHZCrQgJAAgDgEQgDgDABgKIAIgrIiPAAIgHArQgCAKgEADQgEAEgKAAIgrAAQgJAAgDgEQgDgDABgKIARhfQACgJAFgDQADgEAKAAIAIAAQAKgHAHgJQAIgJAFgMQAHgJAEgRIAYh/QACgJAFgEQAEgEAIAAICrAAQAKAAADAEQADAEgCAJIgiC+IATAAQAJAAADAEQADADgCAJIgQBfQgCAKgFADQgDAEgKAAgAGag7QgHAigJAZQgJAZgMASIBGAAIAYiKIgzAAgAnwBuQgKgEgJgGQgJgGgGgIQgHgHgEgJQgFgJgCgKQgCgLgBgLIAQhdQACgRANgcIANgSIAQgPQALgJAdgLQAQgFAlgDIAaADQAMABALAEQAKAEAJAGQAJAGAGAIQAHAIAEAIQAEAKACAKQADAKAAAMIgOBdQgJAggHANIgNARIgQAPQgZAQgQAEQggAHgTAAQgkgDgOgEgAmshjQgJACgFAFQgHAFgEAHQgEAHgCAJIgNBLQgCAKACAHQACAHAEAEQAEAFAJADQAHACAKAAQArAAAGgmIAOhLQABgJgBgHQgCgHgFgFQgEgEgHgDQgIgCgKAAQgLAAgIACgANpBvQgJAAgDgDQgDgEACgJIAii+Ig6AAQgKAAgCgEQgDgEABgJIAGgjQADgKADgDQAEgEAKAAIDBAAQAJAAADAEQAEAEgCAJIgGAjQgCAJgFAEQgEAEgJAAIg6AAIgiC+QgCAJgEAEQgEADgKAAgAJKBvQgKAAgDgDQgCgEABgJIAsjyQABgKAEgDQAFgEAJAAICjAAQAJAAADAEQAEAEgBAJIgHAjQgCAJgEAEQgFAEgIAAIhoAAIgGAiIBTAAQAJAAADAEQADAEgCAJIgGAjQgCAJgEACQgEAEgKAAIhSAAIgGAlIBqAAQAJAAADAEQACADAAAJIgHAkQgBAJgEAEQgFADgKAAgAA8BvQgHAAgCgEQgBgEAFgIIAphDIgzivQgFgRARAAIAuAAQAPAAAFADQAEACADAKIAXBXIAzhXQAGgKAEgCQAGgDANAAIAxAAQAHAAACAEQABAEgFAJIiTD0QgFAJgGADQgFACgNAAgAjXBvQgJAAgDgDQgDgEACgIIArjzQACgKAEgDQAEgEAKAAICpAAQAJAAADAEQADADgCAKIgEAeQgCAJgFAEQgDAEgIAAIhvAAIgGAiIAyAAQAVAAAQAHQAQAGALANQAJAOAEAQQAEAPgEAVQgEAUgGAQQgJAQgOALQgOALgRAGQgSAFgVAAgAiPAwIAoAAQAOAAAIgHQAIgGACgNQACgNgFgHQgGgEgOAAIgoAAgArXBvQgJAAgDgDQgDgEACgJIAii+Ig6AAQgKAAgCgEQgDgEABgJIAGgjQADgKADgDQAEgEAKAAIDBAAQAJAAADAEQAEAEgCAJIgGAjQgCAJgFAEQgEAEgJAAIg6AAIgiC+QgCAJgEAEQgEADgKAAgAttBvQgQAAgGgDQgHgDgDgKIgVhGQgEgLgFgEQgFgEgKAAIgHAAIgPBZQgCAJgFAEQgDADgKAAIgsAAQgKAAgDgDQgCgEABgJIAsjyQABgKAFgDQADgEAKAAIAsAAQAKAAACAEQAEAEgDAJIgPBWIAJAAIBHhYQAIgJAFgDQAHgDANAAIAuAAQAJAAACAFQACAFgHAIIhcByQAHAFAEAHQAFAHAEAKIAjBfQACAJgDAFQgEAFgKAAg");
	this.shape.setTransform(105.6,17.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,211.2,34.3);


(lib.Символ22 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0948B0").s().p("Ag4CRQgRAAgGgHQgFgGADgRIACgOQADgRAIgHQAIgGASAAIATAAQARAAAGAGQADAHgCARIgBAOQgDARgIAGQgIAHgRAAgAgxA5QgJAAgCgDQgDgDACgJQACgMAEgKQADgKAGgIQAKgLASgKIAYgNIAKgIQALgHACgPQACgLgGgFQgGgHgOAAQgOAAgJAHQgLAGgKAQQgGAJgEADQgFACgIgEIghgNQgIgEgBgEQgCgFAFgJQAJgQALgMQAMgMANgIQAOgHARgEQASgEATAAQAYAAATAFQASAHANAKQAMAMAFAPQAFAQgEASQgBALgFALQgEAJgHAJQgLAOgQAHIgnAUQgQALgCALQgBAJgCADQgEADgJAAg");
	this.shape.setTransform(10.6,14.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,21.3,29.1);


(lib.Символ21 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.rus_big();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,230,227);


(lib.Символ20 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.canada_big();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,243,241);


(lib.Символ19 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgEAxQgBgGAFgCIALgEQAGgCABAGQACAHAEAFQADAGAFADQAFAEAHABQAGACAJAAQALAAAJgCQAJgCAGgDQAGgEAEgGQAEgGABgHQACgJgEgGQgEgGgJgDQgJgDgPgCIgSgCQgJgCgIgEQgJgCgFgGQgGgGgCgJQgCgKACgLQACgMAGgJQAGgJAJgGQAKgHAMgDQANgDAQAAQAMAAAKADQAJACAHAFQAHAFAFAHQAEAHAEAKQABAFgGADIgLAEQgGADgCgGQgCgGgDgFQgDgEgEgDQgFgEgGgBQgGgCgIAAQgLAAgIACQgIACgGADQgGAEgDAFQgEAFgBAHQgBAIACAFQADAGAHADQAJAEAXADQANACAJADQAJADAJADQAJAGADALIACALIgBAOQgCAMgGAKQgGAJgJAGQgKAHgNADQgNADgRAAQg2AAgHgrgAhnBYQgHAAgBgFIghikQgBgGAGAAIAKAAQAKAAABAFIAWB2IACAXIABAAIAKgWIBBh3IAEgEIAIgBIAIAAQAHAAgEAGIhZCkQgDAFgGAAg");
	this.shape.setTransform(14.6,9.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,29.2,18.6);


(lib.Символ18 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D22D27").s().p("AHxC1QgKAAgDgEQgEgEACgLIAIgtIiKAAIgIAtQgCALgEAEQgFAEgKAAIg8AAQgKAAgDgEQgDgEACgLIAThwQACgKAFgEQAFgEAKAAIAKAAQAKgIAIgJQAIgJAFgJQAIgPAJgqIAShlQACgKAFgEQAFgEAKAAIDCAAQAKAAADAEQAEAEgCAKIgjDBIAVAAQAKAAAEAEQADAEgCAKIgUBwQgCALgFAEQgEAEgLAAgAG7g8QgGAcgIAYQgIAWgLASIA3AAIAXh/IgnAAgAMyB1QgPAAgHgFQgFgEgBgLIgCgVIhPAAIgKAVQgFALgHAEQgHAFgPAAIg8AAQgKAAgCgFQgCgEAFgJICNkHQAEgJAGgDQAFgDAKAAIA+AAQAKAAAEADQAFADABAIIAwEIQABAJgEAEQgEAFgKAAgAMMAAIgDggQgCgXADgaIACgJIgFAAQgIAogIASIgQAgIAlAAgAC0B1QgQAAgGgFQgGgEgBgLIgCgVIhPAAIgKAVQgEALgHAEQgIAFgOAAIg7AAQgJAAgCgFQgCgEAFgJICKkHQAFgJAFgDQAFgDAKAAIA/AAQAJAAAFADQAEADACAIIAvEIQACAJgEAEQgEAFgKAAgACOAAIgDggQgCgXADgaIABgJIgEAAQgJAogIASIgPAgIAlAAgAiMB1QgKAAgDgEQgEgEACgLIAQhaIg+AAIgQBaQgCALgFAEQgEAEgLAAIg8AAQgLAAgDgEQgEgEADgLIAukDQACgLAFgEQAEgEALAAIA8AAQALAAADAEQADAEgCALIgPBXIA+AAIAQhXQACgLAEgEQAFgEAKAAIA9AAQAKAAAEAEQADAEgCALIguEDQgCALgFAEQgFAEgKAAgAmVB1QgPAAgHgFQgFgEgBgLIgCgVIhPAAIgKAVQgFALgHAEQgHAFgPAAIg8AAQgKAAgCgFIAAgBQgFAGgKAAIg5AAQgSAAgHgEQgHgEgEgMIgWhGQgFgSgJAAIgEAAIgPBZQgCALgFAEQgEAEgLAAIg8AAQgLAAgDgEQgDgEABgLIAvkDQABgKAFgEQAFgEAKAAIA9AAQAKAAADAEQAEAEgCAKIgPBXIAHAAIA/hZQAHgKAGgEQAGgCARAAIA8AAQAKAAADAFQACAGgHAJIhaB/QAHAHAFANIAmBqIABAFIAAAAICNkHQAEgJAGgDQAFgDAKAAIA+AAQAKAAAEADQAFADABAIIAwEIQABAJgEAEQgEAFgKAAgAm7AAIgDggQgCgXADgaIACgJIgFAAQgIAogIASIgQAgIAlAAg");
	this.shape.setTransform(89.3,18.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,178.6,36.3);


(lib.Символ17 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0948B0").s().p("ABbCZQgOgCgMgFQgLgFgKgGQgKgHgHgIQgHgJgGgKQgFgKgCgLQgCgMgBgNIAQhfQADgSAOgeIAOgUIASgQQANgKAggNQASgFApgCQAYAAASAFQASAFAOAKQAOAJAJAPQAIAPAEASQACAKgEAGQgDAFgLAEIg3ASQgLADgEgCQgEgDgDgJQgCgOgHgFQgGgFgPAAQgVAAgKAIQgJAIgDAUIgNBDQgDAUAGAIQAGAJAWAAQANgBAJgGQALgFAGgNQAGgKAFgCQAGgDAJAEIA3AUQAJAEACAFQACAGgGAKQgLASgNAOQgOAPgRAJQgSAKgWAEQgVAFgZAAgAi2CZQgOgCgMgFQgLgFgKgGQgJgHgIgIQgHgJgFgKQgFgKgDgLQgCgMAAgNIAPhfQADgSAOgeIAPgUIASgQQANgKAggNQASgFAogCQAYAAASAFQATAFAOAKQANAJAJAPQAGAPAEASQACAKgEAGQgDAFgIAEIg3ASQgLADgEgCQgFgDgDgJQgCgOgHgFQgGgFgOAAQgWAAgJAIQgJAIgEAUIgMBDQgDAUAGAIQAGAJAVAAQANgBAKgGQAKgFAGgNQAHgKAFgCQAFgDAJAEIA3AUQAKAEACAFQABAGgGAKQgKASgNAOQgOAPgSAJQgSAKgVAEQgWAFgYAAgAnXCZQgOgCgMgFQgLgEgKgGQgJgHgIgJQgHgIgFgKQgFgKgCgLQgDgMAAgNIAOhcQADgUAPgfIAOgUQAIgJAKgHIAVgOIAZgJQARgGApgCIAeACQAOADALAEQAMAEAJAHQAKAGAHAJQAIAJAFAJQAEAKADANQACALAAANIgCAcIgMBAQgJAkgIAPIgPAUIgSAQIgUANIgZAJQglAIgWAAgAmvg9QgLAHgDAQIgOBMQgCAQAHAJQAIAHASABQATgBAKgHQAKgJADgQIAOhMQADgPgIgIQgIgJgRABQgTgBgKAJgALTCUQgLAAgDgDQgDgEABgLIANhLIgEAAQgJABgGAEQgGAEgGAKIgfA3QgHAMgJAEQgJAEgSgBIg4AAQgMABgCgHQgCgGAHgKIAog+QAMgVAJgIQgJgHgGgJQgGgJgDgKQgDgKgBgMQAAgMADgPQAEgYAKgUQALgSAQgMQARgMAVgGQAWgHAaAAIB7AAQAJAAAEAFQAEADgCALIgvEDQgCALgEAEQgFADgKAAgAK1g7QgGAGgCAKQgCAKAEAFQAFAFAKAAIAgAAIAHgoIgfAAQgLAAgGAEgAG7CUQgKABgEgFQgDgEACgLIAJgwQAEgaAGgRIAag9IgDAAQgfA2gXAhIg1BMQgHAJgNgBIhCAAQgKAAgEgDQgEgEADgLIAukDQACgLAFgDQAEgFAKAAIA9AAQAKAAAEAFQADADgBALIgJAxQgGAggHATQgGAUgSAhIAEAAIAfgzQALgUAMgQIA1hNQAHgIANAAIBCAAQAJAAAEAEQADAEgCAKIguEEQgCALgEAEQgFADgKAAgAtCCUQgLAAgDgDQgEgEACgLIAukDQACgLAFgDQAEgFALAAIB4AAQAZABATAHQATAIANARQANAPADAWQAFAUgFAaQgFAagLAQQgKATgRAMQgQANgXAGQgVAGgaAAIgqAAIgLBAQgCALgFAEQgFADgKAAgArWgQIAdAAQALABAHgIQAIgHACgKQACgKgFgHQgFgIgMACIgdAAg");
	this.shape.setTransform(85.2,15.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,170.4,31.1);


(lib.Символ16 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AlpBdQgFgBABgFIAXh9QABgFABgDQACgCAFgCIASgEQAJgBALgBQALABAHACQAHADAFAFQAEAGABAHQACAIgCAKIgFAaQgCAJgEAIQgEAIgGAEQgGAFgJADQgIADgLgBIgLgBIgOgEIgHApQgBAFgFABgAlCglQgDACgBADIgLA+QAJADAPACQAGAAAFgCQAFgBAEgDQAEgDADgFQACgFABgGIAFgZIAAgLQgBgEgCgDQgDgDgFgCQgFgCgGABQgMAAgKACgAKdAxQgHgDgEgFQgEgFgBgIQgCgIACgJIALg7QABgFAEAAIAJAAQAEAAAAAFIgLA8QgBAFABAFQAAAEADADQADADAEABQAFACAGAAQALAAAMgDQADgCABgDIANhLQABgFAFAAIAIAAQAFAAgBAFIgOBRQgBAFgCADIgHADIgTAGQgKACgKgBQgKAAgIgCgAE1AxQgIgDgEgFQgFgGgCgIQgBgHACgKIAFgbQABgJAEgIQAEgHAHgFQAGgFAJgDQAIgCALAAQAJABAGABQAHACAEADQAFADADAGQADAFABAGQABAGgFABIgGACQgGACgBgFQgBgIgGgFQgGgEgKAAQgHAAgFACQgFABgEADQgDADgDAEIgEALIgFAcQgBAGABAEQABAEADAEQACADAFABQAFABAGAAQAUABAJgSQADgFAFACIAGACQAFACgDAFQgDAHgFAFQgFAFgGADQgGAEgHACQgHACgIgBQgLAAgIgCgAjiAxQgIgDgEgGQgFgHgBgIQgCgIACgJIAEgXQACgKAFgHQAEgIAHgFQAGgGAJgCQAJgCALgBQAKABAIACQAIACAFAFQAFAFACAGQACAHgCAIQgBAIgEAEQgEAGgGACQgGADgIACQgIABgLAAQgMAAgQgCIgCAIQgBAGABAEQABAEADAEQADADAEABQAFACAHAAQAKAAAHgEQAIgDAFgGQAEgFAEADIAFADQAEADgEAFIgIAJIgLAGIgNADIgOABQgLAAgIgCgAjJgnQgGACgEADQgEAEgDAEQgDAFgBAGIgBAGQAOADAOABIALgCIAJgDIAGgEIADgHQABgFgBgDQgBgEgDgDQgDgCgFgBQgFgBgHAAQgGAAgFABgApXAxQgIgDgFgFQgFgGgBgIQgCgHACgKIAFgbQACgJAEgIQAEgHAGgFQAHgFAIgDQAJgCALAAQAIABAHABQAGACAFADQAFADACAGQADAFABAGQABAGgFABIgGACQgFACgBgFQgCgIgGgFQgFgEgLAAQgGAAgFACQgFABgEADQgEADgCAEIgEALIgFAcQgBAGABAEQAAAEADAEQADADAFABQAEABAHAAQAUABAJgSQACgFAFACIAHACQAFACgDAFQgEAHgEAFQgFAFgGADQgGAEgHACQgIACgIgBQgKAAgIgCgAISAxIgDgIQAAgEADgCIAHgDQAFgDADgFQAJgQAEgQIAKgoQABgFAEAAIA9AAQAFAAgBAFIgQBbQgBAGgFAAIgIAAQgFAAABgGIAOhPIgkAAIgHAdQgEAQgEALQgEAKgFAGQgEAFgFAEIgLAFIgCABIgCAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBgBAAgAHFAxQgFAAABgGIAFgeIgaAAIgZAfQgDAFgHAAIgHAAQgBAAgBgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAABAAQAAgBAAgBQABAAAAgBIAbggQgEgCgEgDQgDgDgCgDQgCgEgBgFIABgLQABgIADgGQAEgGAFgEQAFgFAHgBQAHgDAIAAIAsAAQAFAAgBAFIgQBbQgBAGgFAAgAGkggQgFAFgCAIQgCAJAEAEQAEAFAIAAIAeAAIAGgkIgdAAQgIABgGAEgAD3AxQgEAAABgGIAKg8IABgKQgBgDgCgEQgCgCgEgCQgEgCgGABQgLgBgNAGQABAHgBAKIgLA8QgBAGgFAAIgIAAQgFAAABgGIALg8IAAgKQAAgEgDgDQgCgCgEgCQgEgCgGABQgKgBgJAEQgDACgBACIgNBLQgBAGgFAAIgIAAQgFAAABgGIAOhQIADgIQACgCAFgCQAJgDAIgCIASgCQAIAAAGACQAGADAEAEQAKgEAJgDQAKgCAIAAQAKABAHACQAGACAEAGQAEAFABAIQABAHgCAJIgLA7QAAAGgFAAgABTAxQgFAAABgGIAFgeIgaAAIgZAfQgDAFgHAAIgHAAQgBAAgBgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAABAAQAAgBAAgBQABAAAAgBIAbggQgEgCgEgDQgDgDgCgDQgCgEgBgFIABgLQABgIADgGQAEgGAFgEQAFgFAHgBQAHgDAIAAIAsAAQAFAAgBAFIgQBbQgBAGgFAAgAAyggQgFAFgCAIQgCAJAEAEQAEAFAIAAIAeAAIAGgkIgdAAQgIABgGAEgAgTAxQgEAAABgGIAKg8IABgKQgBgDgCgEQgCgCgEgCQgEgCgGABQgLgBgNAGQABAHgBAKIgLA8QgBAGgFAAIgIAAQgFAAABgGIALg8IAAgKQAAgEgDgDQgCgCgEgCQgEgCgGABQgKgBgJAEQgDACgBACIgNBLQgBAGgFAAIgIAAQgFAAABgGIAOhQIADgIIAHgEQAJgDAIgCIASgCQAIAAAGACQAGADAEAEQAKgEAJgDQAKgCAIAAQAKABAHACQAGACACAGQAEAFABAIQABAHgCAJIgJA7QAAAGgFAAgAmLAxQgFAAABgGIALg8IAAgKQAAgDgCgEQgDgCgEgCQgEgCgFABQgMgBgNAGQACAHgCAKIgLA8QgBAGgEAAIgJAAQgFAAABgGIALg8IABgKQgBgEgCgDQgDgCgEgCQgEgCgFABQgLgBgJAEQgDACAAACIgOBLQgBAGgEAAIgJAAQgEAAAAgGIAPhQIADgIQACgCAFgCQAIgDAJgCIASgCQAIAAAGACQAGADAEAEQAKgEAJgDQAJgCAJAAQAJABAHACQAHACAEAGQADAFABAIQACAHgCAJIgLA7QgBAGgFAAgArpAxQgFAAAAgGIAYiBQAAgGAGAAIA4AAQAJABAHACQAHADAEAEQAEAFACAHQABAIgBAIQgCAMgGAHQgGAHgJAFIAAAAQAFABAEAEQADADADAFQACAFAAAFQABAFgCAGQgBAJgFAHQgEAHgGAFQgHAFgIACQgJACgJABgArYAfIArAAQAGgBAFgBIAIgEIAFgIIADgJIABgIQgBgEgDgDQgCgDgEgBQgEgCgGAAIgrAAgArNgeIAoAAQAFgBAFgBQAEgBADgDQAEgDACgEIADgJIAAgKQgBgEgCgCQgCgDgEgBQgEgBgGgBIgnAAg");
	this.shape.setTransform(75.1,9.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,150.2,18.6);


(lib.Символ15 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.pole();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,400,184);


(lib.Символ12 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1957C9").s().p("AGWBiQgIgDgGgEIgLgKQgEgFgDgHQgEgGgBgIIgCgPIABgRIAJgxQADgMAJgVIAJgMIALgLQAJgHAVgIQALgDAagCIATACIAQADIAOAIQAGAEAFAFQAFAGADAGQADAHACAIQABAHAAAIIgBASIgJAwQgGAXgFAKIgKAMIgLALQgSALgLAEQgYAEgOAAQgZgBgKgEgAHHg0QgGACgFAEQgEADgDAFQgDAFgBAHIgKA1QgBAHABAFQABAFAEADQADAEAFACQAGABAHAAQAfAAAEgbIAKg1QABgGgBgGQgBgFgDgDQgEgEgFgCQgFgBgHAAQgIAAgGABgAA5BiQgIgDgGgEQgGgFgFgFQgFgFgDgHQgDgGgCgIIgCgQIACgQIAJgyQACgMAJgVIAKgMIALgKQAIgHAWgIQALgEAagBQAPAAAMADQAMAEAJAGQAIAFAGAKQAGAKACAMQABAGgCADQgCAEgHACIgdAKQgGABgDgBQgDgBgCgHQgBgJgGgFQgGgEgMAAQgIAAgGABQgGACgFAEQgEADgDAGQgDAGgBAHIgJAxQgBAHABAGQAAAGADADQAEAEAFACQAGABAIAAQALAAAIgEQAIgFAFgJQAEgHADgBQAEgCAFACIAeALQAFADABADQABAEgDAFQgGANgJAJQgJAJgLAGQgMAGgNADQgOADgQAAQgZgBgKgEgAiEBiQgIgDgGgEIgLgKQgEgFgDgHQgEgGgBgIIgCgPIABgRIAJgxQADgMAJgVIAJgMIALgLQAJgHAVgIQALgDAagCIATACIAQADIAOAIQAGAEAFAFQADAGADAGQADAHACAIQABAHAAAIIgBASIgJAwQgEAXgFAKIgKAMIgLALQgSALgLAEQgYAEgOAAQgZgBgKgEgAhTg0QgGACgFAEQgEADgDAFQgDAFgBAHIgKA1QgBAHABAFQABAFAEADQADAEAFACQAGABAHAAQAfAAAEgbIAKg1QABgGgBgGQgBgFgDgDQgEgEgFgCQgFgBgHAAQgIAAgGABgAtpBiQgHgDgGgEIgLgKQgFgFgDgHQgDgGgCgIIgCgPIACgRIAJgxQACgMAJgVIAKgMIALgLQAIgHAVgIQALgDAbgCIATACIAQADIAOAIQAGAEAEAFQAFAGADAGQAEAHABAIQACAHAAAIIgCASIgJAwQgGAXgFAKIgJAMIgLALQgTALgLAEQgXAEgOAAQgagBgKgEgAs4g0QgGACgEAEQgFADgDAFQgCAFgCAHIgJA1QgCAHACAFQABAFADADQADAEAGACQAFABAIAAQAeAAAFgbIAKg1QABgGgBgGQgBgFgEgDQgDgEgFgCQgGgBgHAAQgIAAgGABgARtBjQgGAAgDgCQgCgDABgHIAfitQACgHADgCQADgDAGAAIB2AAQAGAAADADQACACgBAHIgFAZQgBAHgDACQgDADgHAAIhKAAIgEAZIA7AAQAHAAACADQACADgBAGIgFAXQgBAHgDACQgDADgHAAIg7AAIgFAbIBNAAQAGAAACADQACACgBAHIgEAZQgBAHgDADQgDACgHAAgAQaBjQgHAAgCgCQgCgDABgHIARhSIAOghIgCAAQgYAngNAQIgyBCQgEAGgJAAIghAAQgHAAgCgCQgCgDABgHIAfitQABgHADgCQADgDAHAAIAfAAQAHAAACADQACACgBAHIgIAwQgEAVgEANQgDAJgMAYIACAAIAUggIBDhZQAFgGAIAAIAhAAQAHAAACACQACADgBAHIgfCtQgBAHgDADQgDACgHAAgANUBjQgHAAgCgCQgCgDABgHIALhAIg2AAIgLBAQgBAHgEADQgDACgGAAIggAAQgHAAgCgCQgCgDABgHIAfitQACgHADgDQADgCAGAAIAgAAQAHAAACACQACADgBAHIgLA+IA2AAIALg+QABgHADgDQADgCAHAAIAgAAQAGAAACACQACADgBAHIgeCtQgCAHgDADQgDACgHAAgAKaBjQgHAAgCgCQgCgDABgHIAKg2IgHAAQgKAAgFADQgFACgFAJIgXAoQgEAIgGACQgFACgMAAIgeAAQgHAAgBgDQgCgEAFgGIArhBQgHgEgEgGQgFgGgCgFQgDgHAAgJQgBgJACgJQADgQAHgMQAHgMAKgIQAKgIAOgEQAOgEAQAAIBQAAQAHAAACADQACACgBAHIgfCtQgCAHgCADQgDACgHAAgAJ8gsQgFAFgCAIQgBAKADAEQAEAFAJgBIAeAAIAHgkIgeAAQgJAAgGAFgADwBjQgGAAgDgCQgCgDACgHIAYiIIgqAAQgGAAgDgDQgCgCABgHIAFgZQABgHADgCQADgDAHAAICKAAQAHAAADADQACACgCAHIgEAZQgBAHgDACQgDADgHAAIgqAAIgYCIQgCAHgCADQgDACgHAAgAljBjQgHAAgCgCQgCgDABgHIAfitQABgHADgDQADgCAHAAIBSAAQAOAAALAEQALAEAHAHQAHAHACALQADAJgDANQgCAOgHAJQgGAJgMAHIAAACQAZAJgGAnQgCANgHAKQgGAKgLAHQgKAGgNAEQgNADgPAAgAkwA2IAhAAQAJAAAFgEQAFgFACgIQABgIgDgEQgEgEgJAAIghAAgAkigWIAbAAQAJAAAFgEQAEgEACgHQABgIgDgEQgEgEgJAAIgbAAgAm3BjQgHAAgCgCQgCgDABgHIARhSIAOghIgCAAQgYAngMAQIgyBCQgFAGgIAAIgiAAQgHAAgCgCQgCgDABgHIAfitQABgHADgCQADgDAHAAIAgAAQAGAAADADQACACgBAHIgJAwQgEAVgEANQgDAJgLAYIACAAIAUggIBChZQAFgGAIAAIAiAAQAGAAACACQACADAAAHIgfCtQgCAHgDADQgDACgGAAgAqnBjQgHAAgCgCQgCgDABgHIAYiIIgpAAQgHAAgCgDQgCgCABgHIAEgZQACgHADgCQADgDAGAAICLAAQAHAAACADQACACgBAHIgFAZQgBAHgDACQgDADgHAAIgpAAIgZCIQgBAHgDADQgDACgGAAgAxFBjQgGAAgDgCQgCgDABgHIAfitQACgHADgCQADgDAGAAIBOAAQAgAAAQAUQAIAKADAOQADANgDARQgDAQgHALQgHAMgLAIQgLAIgOAEQgOAEgQAAIgjAAIgIAwQgCAHgCADQgDACgHAAgAwGgIIAcAAQAJABAHgHQAGgFACgJQACgJgFgGQgEgGgKAAIgcAAgAyZBjQgGAAgCgCQgCgDABgHIAYiIIg1AAIgYCIQgCAHgCADQgDACgHAAIggAAQgGAAgDgCQgCgDABgHIAfitQACgHADgCQADgDAGAAICMAAQAHAAACADQACACgBAHIgfCtQgBAHgDADQgDACgHAAg");
	this.shape.setTransform(129.7,10.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,259.4,20.7);


(lib.Символ11 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D22D27").s().p("AKHDAQgPgFgMgIQgMgIgJgLQgJgLgGgNQgHgMgDgPQgDgOAAgRIADgiIARhiQAFgXASgoIASgZIAWgVQAQgNApgQQAWgHA0gDIAlADQASADAOAFQAPAGAMAIQAMAIAKALQAJALAGANQAGANADAOQAEAPAAAQIgVCEQgLAtgLASIgSAZIgWAVQgkAWgWAGQguAKgbAAQgygEgUgHgALnhmQgMADgJAHQgIAGgGAKQgFAKgDANIgTBrQgCANACAKQACAKAHAGQAGAHALADQALAEAOAAQA9AAAIg1IAUhrQACgNgCgKQgCgKgHgGQgHgHgKgDQgLgEgOAAQgPAAgMAEgAoyDKQgGgCgEgNIgXg0QgEgLAEgHQAEgHANgHQARgJANgMQANgMAKgPQAKgQAJgZQAIgYAGgjIAWh+QADgNAGgFQAGgFANAAIDqAAQAOAAAEAFQAEAFgCANIg9FXQgCANgGAFQgGAFgNAAIg/AAQgMAAgFgFQgEgFACgNIAwkOIhCAAIgJA0QgPBGgLAdQgXA0gOASQgWAcgWARQgVARgeAOQgJAEgGAAIgEgBgAOxDDQgNAAgEgFQgFgGADgMIA9lXQADgNAFgFQAGgFANAAIDnAAQANAAAEAFQAFAFgCANIgJAyQgCANgHAFQgGAFgNAAIiRAAIgJAyIB0AAQANAAAFAFQAEAFgDANIgIAvQgDANgGAGQgGAFgNAAIh0AAIgJA1ICWAAQANAAAEAEQAEAFgCAOIgJAyQgCANgGAFQgGAFgOAAgAG4DDQgWAAgIgFQgJgEgFgOIgfhjQgFgPgGgGQgIgGgOAAIgJAAIgWB+QgDANgGAFQgGAFgNAAIg+AAQgNAAgFgFQgEgGADgMIA8lXQADgNAGgFQAGgFANAAIA+AAQANAAAEAFQAFAGgDAMIgVB7IAMAAIBkh9QALgNAIgFQAJgDAUAAIBAAAQAMAAADAHQACAGgIALIiDCiQAKAGAHAIQAHAKAFAOIAwCKQAEAMgFAHQgFAIgNAAgAAuDDQgNAAgEgFQgEgGACgNIAZiEIAkhgIgEAAQgwBQgXAgIhhCBQgJALgQAAIhDAAQgNAAgEgFQgEgFACgNIA9lXQACgNAGgFQAGgFANAAIA+AAQAOAAAEAFQAEAFgCANIgQBeQgIAqgIAbQgHASgWAvIAEAAIAnhAICBiwQAKgLAPAAIBCAAQANAAAEAFQAEAFgBANIg9FXQgDANgGAFQgGAFgNAAgAtyDDQgNAAgFgFQgEgGADgMIA8lXQADgNAGgFQAGgFANAAIDmAAQANAAAFAFQAEAFgCANIgJAyQgCANgGAFQgGAFgNAAIiSAAIgIAyIB0AAQANAAAEAFQAEAFgCANIgJAvQgDANgGAGQgFAFgNAAIh0AAIgKA1ICWAAQANAAAEAEQAEAFgCAOIgJAyQgCANgGAFQgGAFgNAAgAzcDDQgNAAgEgFQgFgGADgMIA9lXQADgNAFgFQAGgFANAAIChAAQAcAAAWAHQAVAIAOAOQANAPAFATQAFAVgEAYQgFAbgNASQgMARgYAPIgBACQAzAWgNBLQgEAagNAUQgNATgUANQgUANgaAHQgZAHgeAAgAx2BqIBAAAQARAAAKgIQAKgJADgQQADgQgHgIQgHgIgSAAIhAAAgAxbgtIA0AAQARAAAKgIQAKgHACgPQADgPgHgIQgHgIgRAAIg1AAg");
	this.shape.setTransform(126.5,20.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,253.1,40.8);


(lib.Символ10 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.iihf_logo();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,76,109);


(lib.Символ8 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0044B2").s().p("AFVBTQgJgEgFgGQgFgHgCgKQgCgJADgLIAGgiQACgKAEgJQAFgJAIgFQAHgGAKgDQALgDANABQANAAAKACQAKACAIADQAFACABADQACACgBAGIgRBfQgBAFgGACIgYAFQgNABgNAAQgMABgIgEgAFzgVQgHACgFADQgEADgDAGQgDAGgCAFIgFAhQgCAHACAGQAAAGAEADQADAEAFACQAFACAHAAQALAAAVgEIAOhNQAAgEgDgBQgLgEgMAAQgJAAgGACgABRBUQgJgEgGgGQgGgGgCgJQgDgIACgLIAHgnQACgIAFgJQAFgIAIgHQAIgFAKgEQALgCANAAQAMgBAKAEQAJADAGAGQAGAHACAIQACAJgBAJIgHAnQgCAKgFAJQgFAIgIAGQgIAGgKADQgLACgNAAQgMAAgKgCgABtgVQgHACgEADQgFADgDAGQgDAEgCAFIgGAnQgBAGABAFQABAFAEADQADADAGADQAGABAHAAQAIAAAGgBQAHgDAEgDQAFgDADgFQADgFABgGIAIgnQABgFgCgEQgBgGgEgDQgDgDgGgCQgGgCgHAAQgIAAgGACgAgyBTQgIgDgFgGQgFgHgCgJQgBgJACgLIANhHQABgGAFAAIALAAQAFAAgBAGIgNBHQgBAHABAGQABAFADAEQADADAFACQAGACAHAAQAOAAAMgEQAEgCABgEIAQhaQABgGAGAAIAKAAQAFAAgBAGIgRBiQgBAGgDADQgCACgGACQgLAFgKABQgMACgMAAQgMABgJgEgAnNBTQgJgEgGgHQgFgHgCgJQgBgKACgLIAFgfQACgJAGgJQAFgJAIgHQAIgGALgDQAKgEANABQAMAAAKACQAJAEAGAFQAGAGADAIQACAIgCAJQgCAIgEAFQgFAHgHAEQgHAEgKACQgKACgNAAQgOAAgUgDIgCAKQgBAHABAFQABAGAEADQADAEAGACQAFACAIAAQAMAAAJgEQAJgEAHgIQAFgFAEACIAGAFQAFADgEAGQgFAGgGAFQgFADgHAEQgHADgJABQgIABgJAAQgNABgKgEgAmvgWQgHACgEAEQgGAEgDAGQgDAGgCAEIgBAIQARADARAAIANgBIAKgDQAFgDACgDQADgDABgEQABgFgBgEQgBgFgEgCQgDgDgGgCQgGgBgIAAQgIAAgGACgAJRBTQgGAAACgGIANhKIAAgKQgBgGgCgDQgDgDgFgCQgEgCgHAAQgOAAgQAHQADAIgDAKIgNBLQgBAGgGAAIgKAAQgGAAACgGIANhKQABgGgBgEQAAgGgDgDQgDgDgFgCQgFgCgHAAQgMAAgLAEQgDACgBADIgQBbQgBAGgGAAIgKAAQgGAAABgGIAShiIADgJQADgCAFgCQALgFAKgBQALgCALAAQAJgBAIADQAHADAFAEQALgEALgDQALgDALABQALgBAIAEQAIADAFAGQAFAGABAKQABAJgCAJIgNBJQgBAGgGAAgAEMBTQgGAAACgGIAIgwIg9AAIgIAwQgBAGgGAAIgKAAQgGAAABgGIAUhuQABgGAGAAIAKAAQAFAAgBAGIgHArIA8AAIAIgrQABgGAGAAIAKAAQAGAAgBAGIgUBuQgBAGgGAAgAh8BTQgFAAABgGIANhJQABgGgBgEQgBgGgDgDQgDgEgGgCQgFgCgIAAQgOAAgOAEQgDACgBADIgQBbQgBAGgGAAIgKAAQgGAAABgGIAShiIADgJQADgCAFgCQALgFAMgBQAMgCANAAQAMgBAIAEQAJADAFAGQAFAHABAJQACAJgCAJIgNBJQgBAGgGAAgAj/BTQgFAAABgGIAJg3QADgLAHgUIgBAAQgHALgJAMIgeApQgEADgEAAIgGAAQgEAAgCgDIgQgoQgFgNgCgLIgBAAQgBAXgBAJIgKA2QgBAGgGAAIgIAAQgGAAABgGIAUhtQABgHAGAAIAHAAQAFAAADAFIAbBFIA0hFQADgFAGAAIAIAAQAGAAAAAHIgUBtQgBAGgGAAgAoXBTQgGAAABgGIAKg9QgZAEgQAAQgQAAgLgEQgLgEgGgIQgGgFgCgMQgBgLACgPIAIgoQABgGAGgBIALAAQAGABgBAGIgIAqQgCAKABAHQABAHAEAFQAEAEAHACQAHACALAAIAXgBQAKgBAIgDIANhKQABgGAGgBIALAAQAGABgBAGIgcCcQgBAGgGAAg");
	this.shape.setTransform(62.5,8.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,125,17.4);


(lib.Символ7 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0044B2").s().p("AASCRQgGAAABgHIAtj5QABgKADgEQAEgEAKgEQAPgGASgCQASgDATAAQAVAAAOAFQAOAFAJAKQAJAKABAPQADAPgDATIgKA4QgEARgHAOQgHAPgNAJQgLAJgQAFQgQAFgUAAQgMAAgPgDQgOgDgPgIIgOBXQgDAHgGAAgABbhxQgHADgCAIIgXCCQAOAGANADQAOAFANAAQAOAAAKgFQALgDAJgGQAHgIAGgJQAFgLADgMIAJg2QADgOgCgJQgCgLgGgGQgGgIgLgDQgJgDgOAAQgiACgPAFgAEXA7QgOgFgHgMQgJgKgCgPQgBgPADgRIAJg4QADgTAIgOQAHgOAMgJQAMgIAQgFQARgEAWAAQATAAAPADQARACAMAGQAJAFADAEQABADgBAKIgcCbQgCAGgIAEQgUAFgVADQgTADgUAAQgTAAgOgGgAFFh1QgLADgJAGQgJAHgEAKQgGAKgCAOIgKA2QgCANABAJQACAKAFAHQAGAHAJAEQAKAFAOAAQAPAAAPgEQAPgBANgFIAZiGQABgIgIgDIgUgFIgXgCQgPAAgMADgAiHA7QgOgFgJgKQgHgKgDgOQgCgOADgRIAWh4QABgIAIAAIALAAQAIAAgCAIIgWB5QgCALABAKQACAKAGAHQAFAGALADQAJAFAOAAIAbgDQANgCALgEQAJgEAAgIIAciYQABgIAGAAIALAAQAIAAgCAIIgaChQgCAKgEAEQgEAEgJAEQghANgpAAQgUAAgNgGgAj7A7QgIAAACgHIAShoQAFgVAJgcIgBAAQgKAQgQAWIg8BPQgFAFgFAAIgHAAQgFAAgCgFIgghNQgIgTgEgVIgCAAQgCAmgDANIgSBmQAAAHgJAAIgJAAQgHAAABgHIAhi3QABgIAIAAIAJAAQAGAAACAGIAxCAIBdh/QAEgHAIAAIAKAAQAIAAgBAIIgiC3QgCAHgHAAg");
	this.shape.setTransform(48.7,16.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(5.6,1.8,86.2,29.2);


(lib.Символ6 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0044B2").s().p("AHQA+QgKgDgFgGQgGgGgCgJQgCgJABgKIACgKIgbAAIgIAvQgBAGgGAAIgKAAQgGAAABgGIAUhuQABgHAGABIAKAAQAFgBgBAHIgIAtIAcAAIABgLQACgKAFgJQAFgIAIgFQAHgGAKgDQALgDAMAAQANAAAJAEQAJADAGAGQAGAGACAJQACAJgCALIgHAlQgCALgEAIQgFAIgIAGQgHAGgLACQgKADgMAAQgNAAgJgDgAHrgqQgGABgFADQgEAEgDAFQgDAFgBAGIgHAmQgBAGABAEQABAFAEAEQADADAFACQAGABAHABQAHgBAGgBQAGgCAFgEQAFgCADgGQADgFABgFIAHgmQABgGgBgGQgBgEgEgEQgDgDgGgCQgFgBgIAAQgHAAgGACgAEfA+QgJgFgGgHQgFgGgCgKQgBgKACgLIAFgcQACgLAGgKQAFgJAIgGQAIgGALgDQAKgEANAAQAMAAAKADQAJADAGAGQAGAGADAHQACAJgCAJQgCAJgEAGQgFAGgHACQgHAEgKADQgKABgNABQgOgBgUgDIgCALQgBAGABAGQABAFAEAEQADAEAGACQAFACAIAAQAMgBAJgDQAJgFAHgIQAFgFAEADIAGAEQAFADgEAGQgFAHgGAEQgFAEgHADQgHADgJACQgIABgJAAQgNAAgKgDgAE9grQgHABgEAEQgGAFgDAFQgDAGgCAHIgBAIQARADARAAIANgBIAKgDQAFgDACgEQADgDABgFQABgGgBgEQgBgEgEgDQgDgDgGgBQgGgBgIAAQgIAAgGACgAhXA+QgJgEgGgFQgGgHgCgIQgDgIACgLIAHglQACgLAFgJQAFgIAIgGQAIgGAKgDQALgDANAAQAMAAAKAEQAJADAGAGQAFAGABAJQACAIgBALIgFAlQgCALgFAIQgFAIgIAHQgIAFgKADQgLADgNAAQgMAAgKgDgAg7gqQgHABgEADQgFAEgDAFQgDAFgCAGIgGAmQgBAFABAFQABAGAEACQADAEAGACQAGABAHABQAIgBAGgBQAHgCAEgEQAFgCADgGQADgFABgFIAIgmQABgGgCgFQgBgFgEgEQgDgDgGgBQgGgCgHAAQgIAAgGACgAmGA+QgJgEgGgFQgGgHgCgIQgDgIACgLIAHglQACgLAFgJQAFgIAIgGQAIgGAKgDQALgDANAAQAMAAAKAEQAJADAGAGQAGAGACAJQACAIgBALIgHAlQgCALgFAIQgFAIgIAHQgIAFgKADQgLADgNAAQgMAAgKgDgAlqgqQgHABgEADQgFAEgDAFQgDAFgCAGIgGAmQgBAFABAFQABAGAEACQADAEAGACQAGABAHABQAIgBAGgBQAHgCAEgEQAFgCADgGQADgFABgFIAIgmQABgGgCgFQgBgFgEgEQgDgDgGgBQgGgCgHAAQgIAAgGACgADiA+QgFAAgCgBQgBgCgBgDIgLgjQgCgHgEgDQgFgEgIABIgWAAIgIAvQgBAGgGABIgKAAQgGgBABgGIAUhtQABgHAGABIAKAAQAFgBgBAHIgHAtIAVAAIAsgvQACgDACgBIAIAAIAJAAQAEgBAAADQABACgEADIgvAwQAGACAEADQAEAEACAIIAOArQADAHgIAAgABmA+QgFAAgCgBQgBgCgBgDIgLgjQgCgHgEgDQgFgEgIABIgWAAIgIAvQgBAGgGABIgKAAQgGgBABgGIAUhtQABgHAGABIAKAAQAFgBgBAHIgHAtIAVAAIAsgvQACgDACgBIAIAAIAJAAQAEgBAAADQABACgEADIgvAwQAGACAEADQAEAEACAIIAOArQADAHgIAAgAiVA+IgGgBIgDgFIgYgrIgmArQgEAFgIABIgKAAQgIAAAGgHIAzg3Igeg1QgEgIAJABIAIAAQAHAAACAEIAWApIAkgpQAFgEAGAAIALAAQAIgBgGAIIgwA1IAfA3QAEAHgJAAgAnRA+QgFAAABgGIANhHQABgIgBgFQgBgFgDgEQgDgDgGgCQgFgCgIAAQgOgBgOAFQgDABgBAEIgQBbQgBAGgGAAIgKAAQgGAAABgGIAShiIADgJQADgDAFgCQALgEAMgCQAMgCANAAQAMAAAIAEQAJADAFAGQAFAHABAJQACAJgCALIgNBHQgBAGgGAAg");
	this.shape.setTransform(55.3,6.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,110.7,13.1);


(lib.Символ3 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.logo();
	this.instance.setTransform(12.5,12);

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0044B2").s().p("AtjE/IAAp+IbFAAQAJALg3D7QgcB8gdB7QgNBEgbAeQgdAfg/AAg");
	this.shape.setTransform(86.8,32);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,173.7,64);


(lib.Символ2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#0000FF").ss(1,1,1).p("Egu3gXbMBdvAAAMAAAAu3MhdvAAAg");
	this.shape.setTransform(300,150);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-1,602,302);


(lib.Символ1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.bg();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.Символ39 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ38();
	this.instance.setTransform(-531.3,-468.1,1,1,0,0,0,71.5,78);

	this.instance_1 = new lib.Символ38();
	this.instance_1.setTransform(-531.3,53,1,1,0,0,0,71.5,78);

	this.instance_2 = new lib.Символ37();
	this.instance_2.setTransform(-531.3,-294.4,1,1,0,0,0,75.5,78.5);

	this.instance_3 = new lib.Символ36();
	this.instance_3.setTransform(-531.3,-120.7,1,1,0,0,0,73,78.5);

	this.instance_4 = new lib.Символ38();
	this.instance_4.setTransform(-531.3,574.1,1,1,0,0,0,71.5,78);

	this.instance_5 = new lib.Символ37();
	this.instance_5.setTransform(-531.3,226.7,1,1,0,0,0,75.5,78.5);

	this.instance_6 = new lib.Символ36();
	this.instance_6.setTransform(-531.3,400.4,1,1,0,0,0,73,78.5);

	this.addChild(this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-606.8,-546.1,151,1198.3);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// maska_07.png - копия
	this.instance = new lib.Символ39();
	this.instance.setTransform(495.5,574,1,1,0,0,0,75.5,271);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-297},49).to({_off:true},1).wait(50));

	// maska_07.png
	this.instance_1 = new lib.Символ39();
	this.instance_1.setTransform(495.5,1616,1,1,0,0,0,75.5,271);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:745},49).to({y:53},50).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-186.8,-243.2,151,2240.3);


(lib.Символ26 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ29();
	this.instance.setTransform(82.4,25.7,1.1,1.1,0,0,0,56.8,5.7);

	// Слой 1
	this.instance_1 = new lib.Символ27();
	this.instance_1.setTransform(80.5,24.5,1,1,0,0,0,80.5,24.5);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,161,49);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ26();
	this.instance.setTransform(77.5,24.5,1,1,0,0,0,80.5,24.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.05,scaleY:1.05,x:77.4,y:27.5},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3,0,161,49);


(lib.Символ13 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.setTransform(129.7,61.5,1,1,0,0,0,129.7,10.3);

	this.instance_1 = new lib.Символ11();
	this.instance_1.setTransform(130.8,20.4,1,1,0,0,0,126.5,20.4);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,259.4,71.9);


(lib.Символ9 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ8();
	this.instance.setTransform(58.3,8.1,0.93,0.93,0,0,0,62.5,8.7);

	this.instance_1 = new lib.Символ7();
	this.instance_1.setTransform(68.8,38.8,0.99,0.99,0,0,0,46.1,15.6);

	this.instance_2 = new lib.Символ6();
	this.instance_2.setTransform(55.4,64.2,1,1,0,0,0,55.4,6.5);

	this.addChild(this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,116.4,70.8);


(lib.Анимация3 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ31();
	this.instance.setTransform(0,-641.2,1,1,0,0,0,72,72.5);

	this.instance_1 = new lib.Символ33();
	this.instance_1.setTransform(0,53,1,1,0,0,0,75.5,72.5);

	this.instance_2 = new lib.Символ32();
	this.instance_2.setTransform(0,226.6,1,1,0,0,0,72.5,72.5);

	this.instance_3 = new lib.Символ31();
	this.instance_3.setTransform(0,400.2,1,1,0,0,0,72,72.5);

	this.instance_4 = new lib.Символ33();
	this.instance_4.setTransform(0,-467.6,1,1,0,0,0,75.5,72.5);

	this.instance_5 = new lib.Символ32();
	this.instance_5.setTransform(0,-294.1,1,1,0,0,0,72.5,72.5);

	this.instance_6 = new lib.Символ31();
	this.instance_6.setTransform(0,-120.5,1,1,0,0,0,72,72.5);

	this.addChild(this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-75.5,-713.7,151,1186.4);


(lib.Символ40 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ35();
	this.instance.setTransform(232.2,910.8,0.8,0.8,-17,0,0,75.5,78.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-40.6,691.6,633.4,1747.4);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Анимация3("synched",0);
	this.instance.setTransform(74.8,-256.3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(49).to({_off:false},0).to({y:576.7},50).wait(1));

	// Слой 1
	this.instance_1 = new lib.Анимация3("synched",0);
	this.instance_1.setTransform(74.8,56.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:784.7},49).to({y:1618.7},50).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.7,-657,151,1186.4);


(lib.Символ30 = function() {
	this.initialize();

	// left
	this.instance = new lib.Символ34();
	this.instance.setTransform(14.5,11.8,0.8,0.8,-17,0,0,75.5,233.2);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-249.4,-685.9,387.7,941.4);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_249 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_264 = function() {
		this.stop(0);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(249).call(this.frame_249).wait(15).call(this.frame_264).wait(11));

	// rigt
	this.instance = new lib.Символ40();
	this.instance.setTransform(998.1,-407.6,1,1,0,0,0,341.2,599.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(170).to({_off:false},0).to({x:698.1},9,cjs.Ease.get(1)).to({x:718.1},5,cjs.Ease.get(1)).wait(56).to({x:698.1},4,cjs.Ease.get(1)).to({x:958.1},5,cjs.Ease.get(1)).wait(1).to({x:998.1},0).to({x:698.1},9,cjs.Ease.get(1)).to({x:718.1},5,cjs.Ease.get(1)).wait(1).to({x:698.1},5,cjs.Ease.get(1)).to({x:958.1},4,cjs.Ease.get(1)).wait(1));

	// left
	this.instance_1 = new lib.Символ30();
	this.instance_1.setTransform(-184.7,45,1,1,0,0,0,72,72.5);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(170).to({_off:false},0).to({x:55.3},9,cjs.Ease.get(1)).to({x:35.3},5,cjs.Ease.get(1)).wait(56).to({x:55.3},4,cjs.Ease.get(1)).to({x:-184.7},5,cjs.Ease.get(1)).wait(1).to({x:55.3},9,cjs.Ease.get(1)).to({x:35.3},5,cjs.Ease.get(1)).wait(1).to({x:55.3},5,cjs.Ease.get(1)).to({x:-184.7},4,cjs.Ease.get(1)).wait(1));

	// btn
	this.instance_2 = new lib.Символ25();
	this.instance_2.setTransform(243.2,126.1,1,1,0,0,0,80.5,24.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(170).to({_off:false},0).to({y:66.1,alpha:1},9,cjs.Ease.get(1)).to({y:76.1},5,cjs.Ease.get(1)).wait(55).to({x:283.2},5,cjs.Ease.get(1)).to({x:183.2,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:243.2,y:126.1},0).to({y:66.1,alpha:1},9,cjs.Ease.get(1)).to({y:76.1},5,cjs.Ease.get(1)).wait(1).to({x:283.2},5,cjs.Ease.get(1)).to({x:183.2,alpha:0},4,cjs.Ease.get(1)).wait(1));

	// text3-2
	this.instance_3 = new lib.Символ24();
	this.instance_3.setTransform(241.3,71.9,1,1,0,0,0,134,14.7);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(170).to({_off:false},0).to({y:17.9,alpha:1},9,cjs.Ease.get(1)).to({y:21.9},5,cjs.Ease.get(1)).wait(55).to({x:281.3},5,cjs.Ease.get(1)).to({x:181.3,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:241.3,y:71.9},0).to({y:17.9,alpha:1},9,cjs.Ease.get(1)).to({y:21.9},5,cjs.Ease.get(1)).wait(1).to({x:281.3},5,cjs.Ease.get(1)).to({x:181.3,alpha:0},4,cjs.Ease.get(1)).wait(1));

	// text3-1
	this.instance_4 = new lib.Символ23();
	this.instance_4.setTransform(241.1,-57.2,1,1,0,0,0,105.6,17.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(170).to({_off:false},0).to({y:-16.2,alpha:1},9,cjs.Ease.get(1)).to({y:-17.2},5,cjs.Ease.get(1)).wait(55).to({x:181.1},5,cjs.Ease.get(1)).to({x:301.1,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:241.1,y:-57.2},0).to({y:-16.2,alpha:1},9,cjs.Ease.get(1)).to({y:-17.2},5,cjs.Ease.get(1)).wait(1).to({x:181.1},5,cjs.Ease.get(1)).to({x:301.1,alpha:0},4,cjs.Ease.get(1)).wait(1));

	// rus_big
	this.instance_5 = new lib.Символ21();
	this.instance_5.setTransform(-199.4,171.3,1,1,0,0,0,115,113.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(95).to({_off:false},0).to({x:11.5,y:85.3},9,cjs.Ease.get(1)).to({x:0.5,y:97.3},5,cjs.Ease.get(1)).wait(50).to({x:10.5,y:87.3},5,cjs.Ease.get(1)).to({x:-99.5,y:167.3,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// canada_big
	this.instance_6 = new lib.Символ20();
	this.instance_6.setTransform(701.5,-116.1,1,1,0,0,0,121.5,120.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(95).to({_off:false},0).to({x:468.5,y:-3.1},9,cjs.Ease.get(1)).to({x:478.5,y:-13.1},5,cjs.Ease.get(1)).wait(50).to({x:468.5,y:-3.1},5,cjs.Ease.get(1)).to({x:548.5,y:-53.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// ?
	this.instance_7 = new lib.Символ22();
	this.instance_7.setTransform(241,156.9,1,1,0,0,0,10.6,14.6);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(92).to({_off:false},0).to({y:94.9,alpha:1},9,cjs.Ease.get(1)).to({y:96.9},5,cjs.Ease.get(1)).wait(53).to({x:231},5,cjs.Ease.get(1)).to({x:291,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// canada
	this.instance_8 = new lib.Символ18();
	this.instance_8.setTransform(241.1,122.3,1,1,0,0,0,89.2,18.1);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(92).to({_off:false},0).to({y:60.3,alpha:1},9,cjs.Ease.get(1)).to({y:62.3},5,cjs.Ease.get(1)).wait(53).to({x:231.1},5,cjs.Ease.get(1)).to({x:291.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// vs
	this.instance_9 = new lib.Символ19();
	this.instance_9.setTransform(242.6,88.7,0.82,0.82,0,0,0,14.6,9.2);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(92).to({_off:false},0).to({y:28.7,alpha:1},9,cjs.Ease.get(1)).wait(63).to({alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// rus
	this.instance_10 = new lib.Символ17();
	this.instance_10.setTransform(241.1,-70,1,1,0,0,0,85.2,15.6);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(92).to({_off:false},0).to({y:2,alpha:1},9,cjs.Ease.get(1)).to({y:0},5,cjs.Ease.get(1)).wait(53).to({x:261.1},5,cjs.Ease.get(1)).to({x:181.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// text2-1
	this.instance_11 = new lib.Символ16();
	this.instance_11.setTransform(243.2,-103.5,1,1,0,0,0,75.1,9.3);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(92).to({_off:false},0).to({y:-31.5,alpha:1},9,cjs.Ease.get(1)).to({y:-33.5},5,cjs.Ease.get(1)).wait(53).to({x:263.2},5,cjs.Ease.get(1)).to({x:183.2,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// text1-2
	this.instance_12 = new lib.Символ13();
	this.instance_12.setTransform(352.9,55.9,1,1,0,0,0,129.7,36);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(19).to({_off:false},0).to({y:25.9,alpha:1},10,cjs.Ease.get(1)).to({y:35.9},5,cjs.Ease.get(1)).wait(40).to({x:342.9},5,cjs.Ease.get(1)).to({x:602.9,alpha:0},5,cjs.Ease.get(1)).wait(5).to({_off:true},1).wait(185));

	// logo
	this.instance_13 = new lib.Символ10();
	this.instance_13.setTransform(168.5,65.5,1,1,0,0,0,38,54.5);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(14).to({_off:false},0).to({y:25.5,alpha:1},10,cjs.Ease.get(1)).to({y:35.5},5,cjs.Ease.get(1)).wait(47).to({x:158.5},5,cjs.Ease.get(1)).to({x:418.5,alpha:0},5,cjs.Ease.get(1)).wait(3).to({_off:true},1).wait(185));

	// text1-1
	this.instance_14 = new lib.Символ9();
	this.instance_14.setTransform(64.1,66,1,1,0,0,0,58.1,35.4);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(9).to({_off:false},0).to({y:26,alpha:1},10,cjs.Ease.get(1)).to({y:36},5,cjs.Ease.get(1)).wait(55).to({x:54.1},5,cjs.Ease.get(1)).to({x:314.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(185));

	// bg3
	this.instance_15 = new lib.Символ15();
	this.instance_15.setTransform(776.8,123.1,1,1,-12,0,0,200,92);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({x:457.8,y:190.1},9,cjs.Ease.get(1)).to({x:467.8,y:200.1},5,cjs.Ease.get(1)).wait(59).to({x:443.8,y:203},5,cjs.Ease.get(1)).to({x:771.8,y:132.2},5,cjs.Ease.get(1)).wait(7).to({regX:199.9,rotation:-17,x:7.7,y:328.8},0).to({x:278.7,y:219.8},9,cjs.Ease.get(1)).to({x:267.7,y:226.8},5,cjs.Ease.get(1)).wait(55).to({x:277.7,y:216.8},5,cjs.Ease.get(1)).to({x:-16.4,y:330.8,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:57.7,y:326.8,alpha:1},0).to({x:277.7,y:216.8},9,cjs.Ease.get(1)).to({x:267.7,y:226.8},5,cjs.Ease.get(1)).wait(55).to({x:287.7,y:206.8},6,cjs.Ease.get(1)).to({x:27.7,y:346.8},4,cjs.Ease.get(1)).wait(1).to({x:57.7,y:326.8},0).to({x:277.7,y:216.8},9,cjs.Ease.get(1)).to({x:267.7,y:226.8},5,cjs.Ease.get(1)).wait(1).to({x:287.7,y:206.8},6,cjs.Ease.get(1)).to({x:27.7,y:346.8},3,cjs.Ease.get(1)).wait(1));

	// bg2
	this.instance_16 = new lib.Символ15();
	this.instance_16.setTransform(621.7,-280.9,1,1,-18,0,0,200,92);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({x:384.7,y:-169.9},9,cjs.Ease.get(1)).to({x:394.7,y:-179.9},5,cjs.Ease.get(1)).wait(57).to({x:377.7,y:-172.9},5,cjs.Ease.get(1)).to({x:672.7,y:-266.9},5,cjs.Ease.get(1)).wait(9).to({scaleX:0.88,scaleY:0.88,x:535.7,y:-250.9},0).to({x:308.7,y:-185.9},9,cjs.Ease.get(1)).to({x:323.7,y:-187.9},5,cjs.Ease.get(1)).wait(55).to({x:313.7,y:-177.9},5,cjs.Ease.get(1)).to({x:548.7,y:-255.9,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:453.7,y:-267.9,alpha:1},0).to({x:313.7,y:-177.9},9,cjs.Ease.get(1)).to({x:323.7,y:-187.9},5,cjs.Ease.get(1)).wait(55).to({x:303.7,y:-167.9},6,cjs.Ease.get(1)).to({x:543.7,y:-267.9},4,cjs.Ease.get(1)).wait(1).to({x:453.7},0).to({x:313.7,y:-177.9},9,cjs.Ease.get(1)).to({x:323.7,y:-187.9},5,cjs.Ease.get(1)).wait(1).to({x:303.7,y:-167.9},6,cjs.Ease.get(1)).to({x:543.7,y:-267.9},3,cjs.Ease.get(1)).wait(1));

	// bg1
	this.instance_17 = new lib.Символ15();
	this.instance_17.setTransform(-289.2,135.1,1,1,16,0,0,200,92);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({x:-77.3,y:182.1},9,cjs.Ease.get(1)).to({x:-87.3,y:172.1},5,cjs.Ease.get(1)).wait(55).to({x:-67.3,y:182.1},5,cjs.Ease.get(1)).to({x:-296.3,y:113},5,cjs.Ease.get(1)).wait(10).to({_off:true},1).wait(185));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-506.8,-430.2,1498.3,708.8);


// stage content:



(lib._600x300 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		var _this = this;
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		  function fl_MouseOverHandler_5()
		{
		    _this.an.gotoAndPlay(250);
		
		    
		}
		
		
		stage.canvas.onmouseout = fl_MouseOutHandler_23;
		
		  function fl_MouseOutHandler_23()
		{
		    _this.an.gotoAndPlay(265);
		
		
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// ramka
	this.instance = new lib.Символ2();
	this.instance.setTransform(300,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// logo
	this.instance_1 = new lib.Символ3();
	this.instance_1.setTransform(86.8,32,1,1,0,0,0,86.8,32);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// an
	this.an = new lib.Символ5();
	this.an.setTransform(122.8,157.2,1,1,0,0,0,63.4,34.7);

	this.timeline.addTween(cjs.Tween.get(this.an).wait(1));

	// bg
	this.instance_2 = new lib.Символ1();
	this.instance_2.setTransform(300,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-147.4,-157.7,1498.3,708.8);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;