(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 25,
	color: "#FFFFFF",
	manifest: [
		{src:"images/Crowdscore.png", id:"Crowdscore"},
		{src:"images/MONACO.jpg", id:"MONACO"},
		{src:"images/phil.png", id:"phil"}
	]
};



// symbols:



(lib.Crowdscore = function() {
	this.initialize(img.Crowdscore);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,150,150);


(lib.MONACO = function() {
	this.initialize(img.MONACO);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,800,533);


(lib.phil = function() {
	this.initialize(img.phil);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,50,65);


(lib.Символ49 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.phil();
	this.instance.setTransform(-25,-32.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-25,-32.5,50,65);


(lib.Символ48 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003042").s().rr(-171.7,-141.85,343.4,283.7,10.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-171.6,-141.8,343.4,283.7);


(lib.Символ47 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACDE8QgbgLgUgTQgTgVgLgbQgLgcAAggQAAghAMgdQAKgcAVgUQAUgVAbgMQAcgLAhAAQAgAAAbALQAaALAUAUQAUAVAKAcQALAcAAAhQAAAggLAcQgLAcgUAVQgTAUgbALQgcAMghAAQggAAgcgMgACZB9QgNASAAAhQAAAhAQATQAOARAXAAQAZAAANgSQAOgRAAggQAAghgPgUQgPgSgYAAQgYAAgOASgAjmE7IFnp1IBkAAIlmJ1gAj8giQgagLgUgUQgTgVgLgcQgLgbAAggQAAghALgdQALgcAUgVQATgVAcgKQAcgMAhAAQAgAAAcALQAaALAUAVQAUAUAKAcQALAcAAAhQAAAggLAdQgLAcgUATQgUAWgbALQgcALghAAQggAAgcgLgAjmjiQgOASAAAhQAAAgAPATQAPASAYAAQAZAAAOgSQAOgSAAgfQAAgigQgTQgPgSgYAAQgYAAgOASg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-34,-32.8,68.1,65.7);


(lib.Символ46 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADHE5QgpgLgggYQgggZgSgjQgTgmAAgxQAAgbAKgZQAJgYARgVQAQgTAWgPQAVgMAZgHQgWgHgRgMQgSgOgMgRQgNgRgHgVQgHgVAAgWQAAgqAQgiQAQgfAdgXQAcgWAlgLQAlgLAqAAQAsAAAmALQAmALAcAWQAdAXAQAfQARAiAAAqQAAAXgHAVQgHAVgNARQgNARgRANQgRANgUAGQAbAIAWANQAVAOAQAVQAPAUAIAYQAIAYAAAaQAAAwgSAmQgSAjghAZQgfAYgrAMQgpAMgxAAQguAAgpgMgADxAtQgUAHgOAMQgNAMgIARQgHAQAAAVQAAAUAHARQAIASAOAMQAOANATAHQAVAHAYAAQAZAAAWgHQAUgHAPgNQAOgMAIgSQAIgRAAgUQAAgVgIgQQgHgRgPgMQgPgMgUgHQgVgGgaAAQgZAAgUAGgADfjLQgNAKgHAOQgHAQAAATQAAAlAXAVQAMALAQAFQARAHAWAAQAXAAASgHQARgFANgLQAXgWAAgkQAAgTgHgQQgHgOgNgKQgZgSgqAAQgoAAgXASgAmME4QgqgKgpgTIAlhhIA6ASQAnAKAjAAQAsAAAegNQAegLATgYQATgXAJgkQAIgiAAgvIgDAAQgTAagkATQgVAMgYAGQgbAGgeAAQgsAAgmgMQglgOgcgZQgdgagPgjQgQgnAAgwQAAgzARgqQAQgoAfgdQAfgdAqgPQAqgOAyAAQAkAAAfAGQAdAHAaAMQAYANAVARQATARAQAWQAPAWALAZIASA0QANA1AAA+QAABAgMA4QgWBOgVAgQgPAagUATQgWAVgZAOQgbAPghAIQghAIgnAAQgxAAgwgNgAlNjVQgUAIgPAPQgPAPgHAVQgHAUAAAYQAAAVAHASQAHATAPAPQAOAPAVAIQAXAJAbAAQAaAAAWgIQAUgJAPgOQAPgOAIgTQAIgTAAgVQAAgYgIgVQgJgVgPgPQgPgPgWgJQgWgIgbAAQgZAAgVAJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-52,-32.5,104,65.2);


(lib.Символ45 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACFE0QgygOglgXIAohXQAhAQArAIQAoAHArAAQAaAAAYgIQAWgHAQgPQARgOAJgVQAJgVAAgZQABgYgIgTQgGgUgOgOQgPgPgUgHQgUgGgZAAQgeAAgZAIQgVAIgTARIhbgvIApkrIFsAAIAABqIkYAAIgTCCQAegNBIgFQAvAAAmANQAnAOAcAaQAdAbAPAkQARAngBAyQAAAxgRApQgRAnghAdQggAcgtAPQguAPg2AAQhUgHgigKgAlgE5QgqgLgfgYQghgZgSgjQgSgmAAgxQgBgbAKgZQAKgYARgVQAPgTAWgPQAVgMAZgHQgVgHgSgMQgRgOgNgRQgNgRgHgVQgGgVAAgWQAAgqAPgiQAQgfAdgXQAcgWAmgLQAkgLAqAAQAsAAAmALQAmALAdAWQAdAXAQAfQARAiAAAqQAAAXgIAVQgHAVgNARQgNARgRANQgRANgUAGQAbAIAWANQAWAOAPAVQAPAUAIAYQAIAYAAAaQAAAwgSAmQgSAjggAZQgfAYgsAMQgpAMgxAAQguAAgogMgAk3AtQgTAHgOAMQgOAMgIARQgGAQgBAVQABAUAGARQAIASAOAMQAOANATAHQAVAHAYAAQAZAAAWgHQAVgHAOgNQAOgMAJgSQAHgRAAgUQAAgVgHgQQgIgRgPgMQgOgMgVgHQgVgGgaAAQgYAAgVAGgAlJjLQgNAKgHAOQgGAQgBATQAAAlAYAVQAMALAPAFQARAHAWAAQAXAAATgHQAQgFANgLQAXgWABgkQAAgTgIgQQgHgOgMgKQgagSgqAAQgnAAgYASg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-49.6,-32.5,99.2,65.2);


(lib.Символ44 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADEE+QgegGgZgNQgZgMgVgSQgTgRgPgWQgVgdgXhGQgOg0AAg/QAAg+AOg5IARg5QAJgYAMgVIAFgIQAQgZAUgUQAVgVAagOQAbgQAggHQAhgIAnAAQAwAAAwAMQAqAKApAUIglBgQhOgbg2AAQgqAAgfAMQgdAMgTAXIgBABQgTAYgJAjQgIAjgBAuIAEAAQASgbAkgTQAVgLAYgGQAcgHAeAAQAqAAAmANQAmANAcAZQAcAbAQAjQARAnAAAwQAAAzgSApQgRApgeAdQgfAcgrAPQgqAPgxAAQgkAAgfgHgADSAOQgVAIgPAPQgPAOgHATQgJASAAAVQABAZAIAVQAHAUARAQQAPAPAWAIQAWAIAaAAQAZAAAVgIQAUgIAPgQQAPgPAIgUQAHgUAAgYQAAgVgHgTQgIgTgOgOQgPgQgVgIQgWgIgbAAQgaAAgWAIgAm6E6ID2oKIkoAAIAAhqIGuAAIAABqIj3IKg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-49.3,-32.5,98.6,65.2);


(lib.Символ43 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjOE+QgegGgZgNQgZgMgVgSQgTgRgPgWQgVgdgXhGQgNg0AAg/QAAg4ALg0IABgLIASg5QALgdAPgYQAQgZAUgUQAVgVAagOQAbgQAggHQAigIAmAAQAwAAAwAMQAoAKApAUIglBgQhMgbg2AAQgqAAgfAMQgeAMgTAYQgTAYgJAjQgFATgCAYQgCASAAAUIAEAAQAMgRASgNQALgJANgHQAVgLAZgGQAbgHAeAAQArAAAlANQAkANAbAZQAdAbAQAjIACAGQAOAkABAtQAAAzgSApQgRApgeAdQgeAcgpAPQgrAPgxAAQgkAAgfgHgAjAAOQgVAIgPAPQgOAOgJATQgIASAAAVQAAAZAJAVQAHAUARAQQAPAPAWAIQAWAIAaAAQAaAAAUgIQAVgIAOgQQAOgPAJgUQAHgUAAgYQAAgVgHgTQgIgTgOgOQgPgQgVgIQgWgIgbAAQgaAAgWAIgAEWE6IAAneIgBgCIhXAiIgshaIClhcIBYAAIAAJ0g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-40,-32.5,80,65.2);


(lib.Символ42 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFDE7IAAiIIklAAIAAhZIEymUIBsAAIAAGQIBNAAIAABdIhNAAIAACIgACbBWICoAAIAAjhgAjkE7IAAiIIkkAAIAAhZIEymUIBsAAIAAGQIBNAAIAABdIhNAAIAACIgAmMBWICoAAIAAjhg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-52.2,-31.5,104.4,63);


(lib.Символ41 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACoE5QgpgLgggYQgggZgSgjIgGgOQgNghAAgoQAAgbAKgZQAHgRAKgQIAJgMQAQgTAWgPQAVgMAZgHQgWgHgRgMQgSgOgMgRQgNgRgHgVQgHgVAAgWQAAgqAQgiQAQgfAdgXQAcgWAlgLQAlgLAqAAQAsAAAmALQAmALAcAWQAdAXAQAfQARAiAAAqQAAAXgHAVQgHAVgNARQgNARgRANQgRANgUAGQAbAIAWANQAVAOAQAVQAPAUAIAYQAIAYAAAaQAAAwgSAmQgSAjghAZQgfAYgrAMQgpAMgxAAQguAAgpgMgADSAtQgUAHgOAMQgNAMgIARQgHAQAAAVQAAAUAHARQAIASAOAMQAOANATAHQAVAHAYAAQAZAAAWgHQAUgHAPgNQAOgMAIgSQAIgRAAgUQAAgVgIgQQgHgRgPgMQgPgMgUgHQgVgGgaAAQgZAAgUAGgADAjLQgNAKgHAOQgHAQAAATQAAAlAXAVQAMALAQAFQARAHAWAAQAXAAASgHQARgFANgLQAXgWAAgkQAAgTgHgQQgHgOgNgKQgZgSgqAAQgoAAgXASgAnnE6IAAhkIDNjAQAfgbASgUIAOgTQAOgSAHgTQAHgUAAgWQAAgYgIgTQgIgRgPgNQgOgMgSgFQgSgGgUAAQgrAAgpAKIhEAVIgphVQA3gcAtgLQAxgMA8AAQAwAAAoANQAnAOAcAaQAcAaAOAkQAPAlAAAsQAAAmgOAkQgNAdgVAdIgDADQgUAagdAcIiuCUIEZAAIAABpg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-48.9,-32.5,97.8,65.2);


(lib.Символ40 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaFAIAAhkIDMjBQAvgqAQgXQANgTAHgSQAIgVAAgVQAAgYgJgTQgIgSgPgMQgNgMgTgGQgRgGgUAAQgrAAgqALIhDAVIgnhWQA1gbAtgMQAwgMA8AAQAxAAAnAOQAnANAcAaQAcAaAPAkQAPAlAAAtQAAAlgPAkQgNAggYAeQgTAZgdAcIiuCUIEZAAIAABqgAkNFAIAAneIgCgDIhXAjIgshbIClhbIBZAAIAAJ0g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-40.3,-32,80.7,64.1);


(lib.Символ39 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhTFAIg1gMQgugPgfgVIAnhTQAbANAsAJQAoAIAgABQAbAAAUgGQAVgFAQgMQAQgMAIgSQAIgSAAgXQAAgZgMgUQgKgTgTgNQgRgMgXgGQgTgFgXAAIhAAAIAAhYIBEAAQApAAAagQQAPgJAIgOQAJgPAAgUQAAgVgHgPQgHgQgNgKQgNgLgTgFQgRgFgYAAQgaAAgkAGIhCAQIgjhWQBkgpBRAAQArAAAoANQAlAMAcAYQAcAYAPAgQAPAgAAAmQAAAXgGAVQgFAUgLASQgLARgQAMQgQALgUAHQAaAIAUAMQAUAPAOASQAPAUAHAYQAIAYAAAdQAAAwgTAnQgSAkghAZQggAYgrALQgrAMgvAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-21.4,-32.5,42.8,65.2);


(lib.Символ27 = function() {
	this.initialize();

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEFBYQgNgEgJgKQgJgIgFgNQgDgIgCgTQAAgPAFgLQAFgLAIgJQAJgKANgFQAHgCAUgCQAOAAALAEQAMAEAIAJQAIAJAFALQADAKAAAPIAAANIhWAAQAAAHADAEQADAFAEACQAEADAGACQAGABAHABQAKgBALgCQAJgBAIgEIAKAcQgKAGgPADQgNACgPAAQgUAAgJgEgAE3ANQAAgJgFgEQgDgDgEgCQgEgCgGAAQgKAAgHAFQgHAEgDALIAxAAIAAAAgAihBZQgNgDgKgFIAHgcQAXAKAQAAQAQAAABgJQAAgGgKgDIgVgHIgMgEQgGgEgEgEQgFgFgDgGQgCgHAAgIQAAgJAEgIQADgIAIgFQAHgFAJgCQAJgCALAAQAMAAANACQANADAKAEIgHAdQgUgJgRAAQgJAAgEADQgCACAAAEQAAADAKAEIAWAHIALAFQAHAEAEAEQAFAFACAFQADAIAAAIQAAAKgFAJQgEAHgIAFQgGAFgKACQgJACgLAAQgOABgOgEgAkwBZQgIgCgFgGQgGgFgDgHQgDgIAAgJQAAgMAFgIQAEgHAIgGQAHgFAKgDQAKgCANAAIAUABIAAgCQAAgPgRAAIgoAFIgIgdQAKgDAQgDQARgCALAAQANAAAJADQAKADAHAFQAGAGADAHQAEAJAAAIIAAAwQAAAKAPgDIAAAcQgOAGgOAAQgKABgHgFQgGgFgCgIQgEAHgHAFQgFADgGABQgGACgIAAQgKAAgJgDgAkkAxQAAAHAFAFQAEAEAIAAQAKAAAGgGQAHgFAAgKIAAgLIgOgBQgaACAAAPgAFxBaIAAh/IAiAAIAFAbQAKgcAjAAIAAAnIgEAAQgJAAgHACQgHADgFADQgFAFgCAHQgCAHAAAJIAAA1gACcBaIAAhQQAAgHgCgDQgEgHgKAAQgFAAgEACQgDACgCADQgDAFAAAHIAABOIgrAAIAAhRQAAgGgCgEQgFgGgJAAQgJAAgEAHQgEADAAAIIAABPIgqAAIAAh/IAgAAIAGATQAEgJAJgGQAKgGAKAAQAMAAAIAEQAFACADAFQAFAEACAGQAHgKAHgFIALgEQAIgCAIAAQAKAAAHACQAJADAHAGQAGAHAEAKQAEALAAAMIAABOgAnEBaIAAirIAsAAIAACHIBHAAIAAAkgAj0g8QgFgGAAgHQAAgHAFgHQAGgEAHAAQAIAAAGAEQAGAGAAAIQAAAHgGAGQgGAFgIAAQgHAAgGgFgAkzg8QgFgGAAgHQAAgHAFgHQAGgEAHAAQAJAAAFAEQAGAGAAAIQAAAHgGAGQgFAFgJAAQgIAAgFgFg");
	this.shape.setTransform(4.6,-0.9);

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FF970B","#FF620B"],[0.039,1],0,-34.8,0,34.9).s().p("ArfElQhrAAAAhrIAAlzQAAhrBrAAIW/AAQBrAAAABrIAAFzQAABrhrAAg");
	this.shape_1.setTransform(3.2,0,1.126,1.126);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-91.8,-33,190.1,66.1);


(lib.Символ23 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("EglNAHcIAAu3MBKbAAAIAAO3g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-238.2,-47.6,476.6,95.3);


(lib.Символ22 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHtBNQgMgEgIgJQgIgIgFgKQgDgHgBgQQAAgNAEgKQAEgKAIgIQAIgJALgEIALgEIAMAAQAKAAAOAEQAKAFAHAHQAGAIAEALQACAIAAALIAAAKIhVAAQAAAHADAHQADAFAFAFQAFADAGADQAHACAIAAQAQAAASgIIAIASQgHAFgNADQgMACgLAAQgRgCgIgCgAIhAOQAAgGgCgGQgBgDgEgFQgDgEgGgDQgGgDgHAAQgHABgGACQgGACgEAEQgFAEgDAEQgDAFgBAIIBAAAIAAAAgAGVBPQgFgCgFgFQgDgEgCgHQgBgHgBgKIAAg9IgQAAIAAgOIAQgCIAEgiIAVAAIAAAhIAdAAIAAARIgdAAIAAA+QAAAJACAFQAFADAIAAIAOgCIABARQgMAEgKAAQgJAAgHgCgAEkBOQgKgDgJgEIAFgRQAVAIAPAAQANAAAFgDQAGgFAAgHQAAgDgDgDIgHgFIgWgHIgLgEQgGgDgEgEQgFgEgCgGQgDgFAAgGQAAgIADgGQAEgHAFgDQAGgFAHgCQAIgBAIAAQAKgBAMADQAKACAIAEIgFARQgRgGgQgBQgKABgGADQgFAEgBAGQAAADADACIAHAFIAXAGIALAEQAHADADAEQAFAEADAGQACAGAAAHQAAAJgDAGQgDAGgGAFQgGAEgJACQgHACgKAAQgMAAgMgDgABYBNQgLgFgJgIQgJgHgEgMIgDgKIgCgNQAAgJAFgNQAEgKAJgJQAJgIALgEQAHgDARgBQAJAAAQAEQALAEAJAIQAJAJAEAKQAFANAAAJIgCANIgDAKQgEAMgJAHQgJAIgLAFQgQAEgJAAQgRgCgHgCgABhgNQgHADgGAGQgEAEgCAHQgDAGAAAJQAAAIADAHQACAHAEAGQAGAFAHADQAGADAJAAQAJAAAHgDQAHgDAFgFQAFgGACgHQADgHAAgIQAAgJgDgGQgCgHgFgEQgFgGgHgDQgHgDgJAAQgJAAgGADgAgrBNQgFgDgEgDQgEgEgDgFIgDARIgSAAIAAifIAYAAIAAA+IAHgJIAKgGQAJgCAKAAIAMAAIAJAEQALAFAGAJQAIAHADAKQAEALAAAMQAAAMgEALQgEAKgHAIQgHAIgLAFQgMAEgIAAQgQgBgHgDgAgmgNQgGADgGAGQgEAEgDAHQgCAGgBAJQAAAIAEAHQACAIAFAFQAFAGAGACQAHADAHAAQAIAAAHgDQAFgCAEgFQAEgGACgHQACgHAAgJQAAgJgCgHQgCgGgEgFQgEgFgFgDQgHgDgIAAQgHAAgHADgAi4BQIgLgDQgKgFgIgIQgGgIgFgLQgDgLAAgMQAAgNADgJQAEgKAHgIQAHgIAKgFIALgEIANAAQAKAAAIACIAKAGIAIAIIAAg9IAXAAIAACfIgTAAIgCgRQgDAFgEAEIgJAGIgLADIgLABgAi3gNQgGADgFAFQgEAFgCAGQgDAHAAAJQAAAJADAHQACAHAEAGQAFAFAGACQAGADAIAAQAIAAAGgDQAHgCAFgGQAEgFADgIQACgHAAgIQAAgJgCgGQgDgHgEgEQgFgGgGgDQgIgDgHAAQgIAAgGADgAnNBPQgHgDgGgFQgGgEgDgHQgCgGAAgJQAAgKADgHQAEgHAHgEQAHgEAIgDQAJgCAKAAQANABANACIAAgHQAAgEgCgFQgBgFgEgCQgGgEgMAAIgSABIgRAFIgFgSIAUgFQAOgDALABQAKAAAIABQAJADAFAFQAGAFACAGQAEAIAAAHIAAA0QAAAHAGAAIAIgCIAAAUQgFADgLAAQgIAAgFgEQgHgFAAgIQgDAIgKAGIgJADIgOABQgIAAgIgCgAnFAcQgFADgCADQgDAEAAAGQAAAFACADQABAEAEACQAGAEAJAAIALgBQAGgCAEgDQAEgDADgFQADgEgBgFIAAgMQgLgBgLAAQgMAAgIACgAoVBPQgGgCgFgFQgDgEgCgHQgBgHAAgKIAAg9IgQAAIAAgOIAQgCIADgiIAUAAIAAAhIAfAAIAAARIgfAAIAAA+QAAAJAEAFQADADAJAAIAOgCIABARQgNAEgKAAQgIAAgGgCgADHBPIAAhxIATAAIADAVIAFgJQADgEAEgCIAKgFQAHgBAHAAIADAAIAAAVIgEAAQgHAAgGACQgGABgEAEQgFAEgDAEQgCAHAAAJIAAA9gAkTBPIAAhEQAAgGgCgFQgBgEgDgEQgEgEgEgCQgFgCgGAAQgHAAgGADQgFADgEAEQgDAFgDAEQgBAGAAAHIAAA/IgYAAIAAhxIATAAIADAUQAMgWAZABQAJgBAHADQAJADAGAFQAFAHAEAJQADAJAAALIAABEg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-56.8,-8.1,113.6,16.3);


(lib.Символ21 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADqBhQgJgBgHgEQgIgEgEgFQgFgHAAgIQAAgIAEgFQADgFAGgEQgFgDgEgFQgCgFAAgFQAAgLAMgIQgFgFgDgEQgCgGAAgIQgBgIAEgIQADgHAGgFQAGgGAIgCQAJgDALAAQAIAAAGACIApAAIAAARIgRADQADACACAFQACAFAAAGQAAAKgDAFQgEAHgHAFQgGAEgIADQgIACgJAAQgPgCgGgDQgHADAAAFQAAANAngBQAJAAAHABQAIACAFADQAFAEADAFQADAFAAAIQAAAJgFAHQgEAGgHAEQgIADgJACQgIACgKAAQgJAAgIgCgADiA6QgDAEABAEQAAAEACADQADACAEACQAIADAKAAQAMAAAHgDQAEgCADgCQADgDAAgEQAAgFgEgDQgFgDgKAAQgVAAgIgCQgEACgCADgADxgiQgFACgDADQgCACgDAEIgBAJQAAAFABAEIAFAFQADADAFACQAEABAGAAQAFAAAFgBQAEgCADgDQADgBABgEQACgEAAgFIgCgJQgBgEgDgCQgDgDgEgCQgFgCgFAAQgGAAgEACgABbA9QgFgCgDgEQgDgGgBgNIAAiGIAXAAIAACEQAAAJALABIAKgBIAAASQgJACgKAAQgIAAgFgCgAihA9QgHgCgFgFQgGgFgDgHQgDgGAAgJQAAgKAEgHQADgHAIgDQAGgDAJgCQAJgCAKAAQANAAANACIAAgHQAAgGgCgFQgBgEgEgDQgHgEgLAAIgSACIgRAEIgFgSIAUgFQANgCALAAQALAAAHACQAJACAGAFQAFAFADAHQADAHAAAJIAAAyQAAAHAHAAIAIgBIAAATQgFADgMAAQgHAAgFgEQgHgEAAgJQgEAJgJAFIgKADIgNABQgJAAgIgCgAiYALQgFACgDADQgCAEAAAGQAAAFABADQACAEAEACQAFAEAJAAIALgBQAGgCAFgDQAEgDACgEQADgFAAgEIAAgMQgMgCgLAAQgMAAgHADgACYA9IAAhbIgNgEIAAgRIAlAAIAABwgAAYA9IAAhBQAAgHgCgGQgBgFgEgEQgEgDgEgCQgFgCgEAAQgHAAgFADQgFACgEAFQgEAEgCAGQgBAGAAAHIAAA9IgZAAIAAhwIATAAIAEATQALgVAYAAQAIAAAIACQAIADAGAGQAGAGADAJQAEAJgBANIAABCgAkJA9IgohwIAaAAIAcBWIAAAAIAchWIAaAAIgoBwgACYhIQgEgEAAgGQAAgGAEgEQAEgFAGAAQAGAAAEAFQAFAEAAAGQAAAFgFAFQgFAEgFAAQgGAAgEgEg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-30.6,-9.9,61.2,19.9);


(lib.Символ20 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhbBLQgIgCgFgFQgGgFgDgHQgDgHAAgIQAAgKAEgHQAEgHAHgFQAGgEAJgBQAJgCAKAAQANAAANACIAAgHQAAgEgCgFQgBgEgEgDQgGgEgMAAIgSACIgRADIgFgSIAUgEQANgDALAAQALABAIACQAIACAGAEQAGAFACAIQADAGAAAKIAAAyQAAAGAHAAIAIAAIAAATQgFADgMAAQgHAAgFgEQgHgFAAgIQgEAJgJAEIgKAEIgNABQgJAAgHgCgAhTAZQgFACgCADQgDAEAAAGQAAAFACADQABADAEADQAFAEAKAAIALgCQAGgBAEgDQAEgEADgDQACgFAAgFIAAgLQgLgCgLgBQgNABgHADgABdBLIAAhDQAAgIgCgDQgBgFgEgEQgDgDgFgCQgEgCgGAAQgHAAgGACQgFADgEAFQgEAEgCAFQgBAFAAAGIAABAIgYAAIAAhwIASAAIAEATQALgVAagBQAJAAAHADQAIADAGAGQAGAGADAIQAEAKAAALIAABEgAgrg4QgDgEAAgEQAAgGADgDQADgDAFAAQAFAAADADQAEADAAAGQAAAEgEAEQgDADgFAAQgFAAgDgDgAhbg4QgDgEAAgEQAAgGAEgDQADgDAEAAQAFAAAEADQADADAAAGQAAAEgDAEQgEADgFAAQgEAAgEgDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-11.7,-7.7,23.5,15.5);


(lib.Символ19 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkMBjIAAiWIATAAIADARQADgFAFgEQAEgEAFgCQAKgEAMAAQAMAAAKAEQAKAFAHAIQAHAIAEAKQAEAMAAAKQAAAMgEALQgDALgHAIQgIAIgJAFQgPAEgJAAQgLAAgIgCIgJgFQgFgEgDgFIAAA0gAjhgeQgHACgEAFQgFAGgDAHQgDAHAAAHQAAAIADAIQACAHAFAFQAFAFAGADQAHADAIAAQAHAAAGgDQAGgDAFgFQAFgFACgHQADgIAAgIQAAgHgDgHQgCgHgFgFQgFgGgGgCQgGgDgHAAQgIAAgGADgABlA+IgMgDQgLgFgIgIQgIgIgEgLQgFgLAAgMQAAgKAFgLQAEgLAIgIQAJgIALgFIAMgDIANgBQAKAAAJACQAIACAIAEIgIASQgMgGgOAAQgKAAgIAEQgHADgFAGQgEAGgCAHQgCAGAAAFQAAAHACAHQACAHAFAGQAFAFAHAEQAHADAKAAQANAAANgFIAHARQgGAEgLACQgKACgJAAgAgtA9QgIgCgFgFQgGgFgDgHQgDgGAAgJQAAgKAEgHQAEgHAHgDQAGgDAJgCQAJgCAKAAQANAAALACIAAgHQAAgGgCgFQgBgEgCgDQgGgEgMAAIgSACIgRAEIgFgSIAUgFQANgCALAAQALAAAGACQAIACAGAFQAGAFACAHQADAHAAAJIAAAyQAAAHAHAAIAIgBIAAATQgFADgMAAQgHAAgFgEQgHgEAAgJQgEAJgHAFIgKADIgNABQgJAAgHgCgAglALQgFACgCADQgDAEAAAGQAAAFACADQABAEAEACQAFAEAKAAIALgBQAGgCAEgDQAEgDABgEQACgFAAgEIAAgMQgJgCgLAAQgNAAgHADgAhzA9QgFgCgDgEQgDgGgBgNIAAiGIAXAAIAACEQAAAJAKABIALgBIAAASQgJACgKAAQgIAAgFgCgADxA9IgfgsIgNAPIAAAdIgYAAIAAifIAYAAIAABkIAsg1IAcAAIguAzIAtA9g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-26.9,-9.9,53.9,19.9);


(lib.Символ18 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAiA3QgMgFgIgIQgJgIgEgKQgBgHgBgRQAAgKABgLQAFgLAHgJQAIgIALgEIAMgEIAMgBQAJAAAPAFQAKAEAGAIQAHAIADAKQADAKAAAMIAAAIIhWAAQAAAHAEAGQACAGAGAEQAEAEAHACQAGADAJAAQAPAAASgIIAJASQgIAEgMADQgMADgLAAQgSgCgHgCgABVgHQAAgGgCgFQgBgGgDgEQgEgEgFgDQgGgDgIAAQgHAAgFADQgGACgFAEQgEAEgDAGQgDAFgCAHIBAAAIAAAAgACFA5IAAhxIATAAIADAVIAFgJQADgEAFgDIAKgEQAFgBAIAAIADAAIAAAVIgEAAQgHAAgFABQgHACgEAEQgFAEgCAGQgDAHAAAJIAAA7gAgxA5IAAhFQAAgGgBgFIgEgIQgDgDgFgCQgEgCgFAAQgHAAgEADQgFACgDAEQgDAEgCAGQgCAFAAAHIAABAIgYAAIAAhGQAAgFgBgFQgBgFgDgDQgDgDgFgCQgDgCgGAAQgGAAgFADQgEACgEAEQgDAEgCAGQgBAFgBAHIAABAIgYAAIAAhxIATAAIAEASQACgFAEgDIAHgHQAKgFAKAAIALACIAKAEQAEADADAEQADAEACAFQACgEAEgEIAJgHIAKgFIAKgCQALAAAIADQAJADAFAGQAGAFADAJQACAJAAALIAABFg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.4,-5.9,38.8,11.9);


(lib.Символ17 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA+BlQgJgBgHgEQgIgEgEgFQgFgHAAgIQAAgIAEgFQADgFAGgEQgGgDgDgFQgDgFAAgFQAAgLAMgIQgEgFgDgGQgDgEAAgIQAAgIAEgIQADgHAGgFQAGgGAIgCQAIgDALAAQAJAAAGACIAoAAIAAARIgQADQADACACAFQACAFAAAGQAAAJgEAGQgDAHgHAFQgGAEgJADQgIACgJAAQgOgCgHgDQgGADAAAFQAAANAngBQAJAAAHABQAIACAFADQAFAEADAFQADAFAAAIQAAAJgFAHQgEAGgIAEQgHADgJACQgIACgKAAQgJAAgIgCgAA2A+QgDAEAAAEQAAAEADADQADACAEACQAIADAKAAQALAAAIgDQAEgCADgCQADgDAAgEQAAgFgFgDQgEgDgKAAQgVAAgJgCQgDACgCADgABEgeQgEACgDADQgDACgCAEIgBAJQAAAFABAEIAFAFQADADAEACQAFABAFAAQAGAAAEgBQAFgCADgDQADgDABgCQACgEAAgFIgCgJQgBgEgDgCQgDgDgFgCQgEgCgGAAQgFAAgFACgAk3BlQgJgBgHgEQgIgEgEgFQgFgHAAgIQAAgIAEgFQADgFAGgEQgGgDgDgFQgDgFAAgFQAAgLAMgIQgEgFgDgGQgDgEAAgIQAAgIAEgIQADgHAGgFQAGgGAIgCQAIgDALAAQAJAAAGACIAoAAIAAARIgQADQADACACAFQACAFAAAGQAAAJgEAGQgDAHgHAFQgGAEgJADQgIACgJAAQgOgCgHgDQgGADAAAFQAAANAngBQAJAAAHABQAIACAFADQAFAEADAFQADAFAAAIQAAAJgFAHQgEAGgIAEQgHADgJACQgIACgKAAQgJAAgIgCgAk/A+QgDAEAAAEQAAAEADADQADACAEACQAIADAKAAQALAAAIgDQAEgCADgCQADgDAAgEQAAgFgFgDQgEgDgKAAQgVAAgJgCQgDACgCADgAkxgeQgEACgDADQgDACgCAEIgBAJQAAAFABAEIAFAFQADADAEACQAFABAFAAQAGAAAEgBQAFgCADgDQADgDABgCQACgEAAgFIgCgJQgBgEgDgCQgDgDgFgCQgEgCgGAAQgFAAgFACgAC5A/QgMgEgIgIQgJgIgEgLQgDgHgBgQQAAgLAEgLQAEgLAIgIQAIgIAKgFIAMgDIAMgBQAJAAAPAEQAKAFAGAHQAHAIADALQADAKAAAKIAAAKIhWAAQAAAHAEAGQACAFAGAFQAFAEAGACQAHACAIAAQAPAAATgIIAIASQgIAFgMADQgMACgLAAQgSgBgHgDgADsAAQAAgEgBgFQgCgGgDgEQgEgFgFgCQgGgDgHAAQgHAAgGACQgGACgFAEQgEAEgDAGQgDAGgBAFIA/AAIAAAAgAjLBBQgIgCgFgFQgGgFgDgHQgDgGAAgJQAAgKAEgHQAEgHAHgEQAGgDAJgBQAJgCAKAAQANAAANACIAAgHQAAgGgCgFQgBgEgEgDQgGgEgMAAIgSACIgRAEIgFgSIAUgFQANgCALAAQALAAAIACQAIACAGAFQAGAFACAHQADAHAAAJIAAAyQAAAHAHAAIAIgBIAAATQgFADgMAAQgHAAgFgEQgHgEAAgJQgEAJgJAFIgKADIgNABQgJAAgHgCgAjDAPQgFACgCADQgDAEAAAGQAAAFACADQABAEAEACQAFAEAKAAIALgBQAGgCAEgDQAEgDADgEQACgFAAgEIAAgMQgLgCgLAAQgNAAgHADgAEcBBIAAhwIATAAIADAVIAFgJQADgEAFgDIAKgEQAGgCAHAAIADAAIAAAVIgEAAQgHAAgFACQgHABgEAEQgFAEgCAHQgDAGAAAIIAAA8gAgRBBIAAhBQAAgHgCgGQgBgFgEgEQgDgDgFgCQgEgCgGAAQgHAAgGADQgFACgEAFQgEAEgCAGQgBAGAAAFIAAA/IgYAAIAAhwIASAAIAEATQALgVAaAAQAJAAAHACQAIADAGAGQAGAGABAJQAEAJAAANIAABCgAi6hEQgGgFAAgJQAAgJAGgGQAGgFAIAAQAIAAAGAFQAGAGAAAJQAAAJgGAFQgGAGgIAAQgIAAgGgGgAizhaQgDADAAAFQAAAFADADQADADAEAAQAFAAADgDQADgDAAgFQAAgFgDgDQgDgDgFAAQgEAAgDADg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-34.5,-10.3,69.1,20.7);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgjBNIA9iEIhNAAIAAgVIBnAAIAAAVIg9CEg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EEFFFF").s().p("AgkBOIA+iGIhOAAIAAgVIBpAAIAAAVIg+CGg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#DDFFFF").s().p("AgkBQIA/iKIhQAAIAAgVIBrAAIAAAVIg/CKg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCFFFF").s().p("AglBRIBAiMIhRAAIAAgVIBtAAIAAAVIhACMg");

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BBFFFF").s().p("AgmBTIBBiPIhSAAIAAgWIBvAAIAAAWIhCCPg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#AAFFFF").s().p("AgnBVIBDiSIhUAAIAAgXIBxAAIAAAXIhDCSg");

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#99FFFF").s().p("AgoBXIBFiVIhWAAIAAgYIBzAAIAAAYIhECVg");

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#88FFFF").s().p("AgpBYIBGiXIhYAAIAAgYIB3AAIAAAYIhGCXg");

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#77FFFF").s().p("AgpBaIBHibIhaAAIAAgYIB5AAIAAAYIhICbg");

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#66FFFF").s().p("AgqBbIBIidIhbAAIAAgYIB7AAIAAAYIhJCdg");

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#75FFFF").s().p("AgqBaIBIibIhaAAIAAgYIB5AAIAAAYIhICbg");

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#85FFFF").s().p("AgpBZIBGiZIhYAAIAAgYIB3AAIAAAYIhGCZg");

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#94FFFF").s().p("AgoBXIBFiVIhXAAIAAgYIB1AAIAAAYIhFCVg");

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#A3FFFF").s().p("AgnBWIBDiUIhUAAIAAgXIBxAAIAAAXIhDCUg");

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#B3FFFF").s().p("AgmBUIBCiRIhTAAIAAgWIBvAAIAAAWIhCCRg");

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#C2FFFF").s().p("AgmBSIBBiOIhRAAIAAgVIBtAAIAAAVIhBCOg");

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#D1FFFF").s().p("AglBRIBAiMIhQAAIAAgVIBrAAIAAAVIg/CMg");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#E0FFFF").s().p("AgkBQIA/iJIhQAAIAAgWIBrAAIAAAWIg/CJg");

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F0FFFF").s().p("AgjBOIA9iGIhOAAIAAgVIBpAAIAAAVIg+CGg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.2,-7.7,10.4,15.4);


(lib.Символ15 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACtBPQgGgCgEgFQgEgEgBgHQgCgHAAgKIAAg9IgQAAIAAgOIAQgCIAEgiIAUAAIAAAhIAeAAIAAARIgeAAIAAA+QAAAJADAFQAEADAJAAIANgCIABARQgMAEgKAAQgJAAgGgCgAgoBNQgKgFgJgIQgIgHgFgMIgEgKIgBgNQAAgJAFgNQAFgKAIgJQAJgIAKgEQAIgDARgBQAJAAAOAEQALAEAJAIQAIAJAFAKQAFANAAAJIgBANIgEAKQgFAMgIAHQgJAIgLAFQgOAEgJAAQgRgCgIgCgAgfgNQgHADgFAGQgEAEgDAHQgCAGAAAJQAAAIACAHQADAHAEAGQAFAFAHADQAIADAIAAQAJAAAGgDQAGgDAFgFQAFgGACgHQADgHAAgIQAAgJgDgGQgCgHgFgEQgFgGgGgDQgGgDgJAAQgIAAgIADgAisBNQgFgDgDgDQgFgEgDgFIgCARIgTAAIAAifIAXAAIAAA+IAIgJIAKgGQAIgCAKAAIANAAIAMAEQAJAFAIAJQAGAHAEAKQAEALgBAMQABAMgEALQgEAKgHAIQgHAIgKAFQgPAEgJAAQgPgBgHgDgAingNQgHADgFAGQgEAEgDAHQgDAGABAJQAAAIACAHQADAIAFAFQAEAGAHACQAHADAIAAQAHAAAGgDQAHgCAEgFQAEgGADgHQACgHAAgJQAAgJgCgHQgDgGgEgFQgEgFgHgDQgGgDgHAAQgJAAgGADgABGBPIAAhxIATAAIADAVIAFgJQADgEAFgCIAKgFQAFgBAIAAIADAAIAAAVIgEAAQgHAAgFACQgHABgEAEQgFAEgCAEQgDAHAAAJIAAA9g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-21.1,-8.1,42.2,16.3);


(lib.Символ14 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEBLQgHgCgGgFQgFgEgDgIQgDgGAAgJQAAgKAEgGQAEgIAGgEQAHgEAHgCQAIgCAKAAQAOAAANADIAAgIQAAgEgCgEQgBgFgFgDQgFgDgMAAIgSABIgQAEIgEgSIASgEQANgDALAAQAKAAAJACQAIACAFAFQAHAFACAHQADAHAAAKIAAAxQAAAHAGAAIAJgBIAAATQgFADgMABQgIgBgEgEQgHgEAAgIQgEAIgJAFIgKAEIgNABQgJAAgGgDgAACAZQgCADgCACQgEAFAAAGQAAAEACADQACAEACACQAFAEAKABIALgCQAFgBAEgDQAFgEADgEQACgFAAgEIAAgMQgMgCgKAAQgNAAgIADgABmBLIAAhwIAUAAIADAVIAEgJQADgEAFgDIAKgEQAGgBAIAAIACAAIAAAUIgDAAQgIABgFABQgHABgEAFQgFAEgCAFQgCAGgBAJIAAA8gAhwBLIAAiCIgyAAIAAgWIB9AAIAAAWIgzAAIAACCg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-16.3,-7.8,32.7,15.6);


(lib.Символ13 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADOBPQgIgDgGgFQgFgEgDgHQgDgGAAgJQAAgKAEgHQADgHAIgEQAGgEAJgDQAJgCAKAAQANABANACIAAgHQAAgEgCgFQgBgFgEgCQgHgEgLAAIgSABIgRAFIgFgSIATgFQAOgDALABQAKAAAIABQAJADAGAFQAFAFADAGQADAIAAAHIAAA0QAAAHAHAAIAIgCIAAAUQgFADgMAAQgHAAgGgEQgGgFAAgIQgEAIgJAGIgKADIgNABQgJAAgHgCgADWAcQgFADgDADQgCAEAAAGQAAAFACADQABAEADACQAGAEAJAAIALgBQAHgCADgDQAFgDACgFQADgEAAgFIAAgMQgLgBgMAAQgMAAgHACgAADBQIgJgDQgLgFgIgIQgIgIgEgLQgFgLAAgNQAAgLAFgKQAEgLAIgHQAIgJALgEIALgEIAMAAQALgBAJADQAIACAIAEIgIASQgMgHgOAAQgKAAgIAFQgFADgFAGQgEAEgDAGQgBAHAAAHQAAAHABAGQADAIAFAFQAFAGAEADQAIAEAKAAQANAAANgGIAHARQgGAEgLADQgKACgJAAgAiGBNQgLgEgJgJQgIgIgFgKQgDgHgBgQQAAgNAEgKQAFgKAHgIQAIgJALgEIALgEIAMAAQAJAAAPAEQAKAFAHAHQAGAIAEALQACAIAAALIAAAKIhVAAQgBAHAEAHQADAFAFAFQAFADAGADQAHACAIAAQAPAAATgIIAJASQgJAFgMADQgMACgLAAQgRgCgIgCgAhSAOQAAgGgCgGQgBgDgEgFQgDgEgGgDQgFgDgIAAQgHABgGACQgGACgEAEQgFAEgDAEQgDAFgBAIIBAAAIAAAAgACQBPIgfgsIgOAPIAAAdIgYAAIAAifIAYAAIAABkIAsg2IAcAAIgtA0IAtA9gAj9BPIgohxIAZAAIAcBXIABAAIAbhXIAaAAIgnBxg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-29.4,-8.1,58.9,16.3);


(lib.Символ12 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhRA3QgLgFgJgIQgIgIgEgKQgDgHgCgRQAAgKAEgLQAFgLAHgJQAIgIALgEIALgEIANgBQAJAAAOAFQAKAEAHAIQAGAIAEAKQADAKAAAMIgBAIIhVAAQAAAHADAGQADAGAFAEQAFAEAHACQAGADAIAAQAQAAASgIIAJASQgIAEgMADQgMADgMAAQgRgCgIgCgAgdgHQAAgGgCgFQgBgGgEgEQgDgEgGgDQgFgDgIAAQgHAAgGADQgGACgEAEQgFAEgDAGQgDAFgBAHIBAAAIAAAAgABfA5IAAhCQAAgHgCgFQgBgGgEgDQgDgEgFgCQgEgCgGAAQgHAAgGADQgFADgEAEQgEAFgCAGQgBAGAAAGIAAA+IgYAAIAAhxIASAAIAEAUQALgWAaAAQAJAAAHADQAIADAGAFQAGAGADAJQAEAKAAANIAABCg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-11.9,-5.9,23.9,11.9);


(lib.Символ11 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACHBPQgHgDgGgFQgFgEgDgHQgEgGAAgJQAAgKAFgHQADgHAHgEQAHgEAJgDQAIgCAKAAQAOABANACIAAgHQAAgEgDgFQgBgFgEgCQgGgEgLAAIgSABIgSAFIgFgSIAUgFQAOgDAKABQALAAAIABQAJADAFAFQAGAFADAGQACAIAAAHIAAA0QABAHAGAAIAJgCIAAAUQgFADgNAAQgHAAgFgEQgGgFAAgIQgEAIgKAGIgKADIgMABQgKAAgHgCgACPAcQgEADgDADQgDAEAAAGQAAAFACADQACAEADACQAGAEAJAAIALgBQAGgCAEgDQAEgDADgFQADgEAAgFIAAgMQgMgBgLAAQgMAAgIACgAhEBPQgHgDgFgFQgGgEgDgHQgDgGAAgJQAAgKAEgHQAEgHAGgEQAHgEAJgDQAIgCAKAAQAOABANACIAAgHQAAgEgCgFQgCgFgEgCQgFgEgMAAIgSABIgSAFIgEgSIAUgFQANgDALABQAKAAAJABQAIADAFAFQAGAFABAGQADAIAAAHIAAA0QAAAHAGAAIAJgCIAAAUQgFADgMAAQgGAAgEgEQgHgFAAgIQgEAIgJAGIgKADIgNABQgJAAgIgCgAg8AcQgEADgDADQgDAEAAAGQAAAFACADQACAEAEACQAFAEAKAAIALgBQAGgCAEgDQAEgDADgFQACgEAAgFIAAgMQgLgBgMAAQgMAAgIACgAi5BNQgFgDgEgDQgEgEgCgFIgEARIgTAAIAAifIAZAAIAAA+IAIgJIAJgGQAJgCAKAAIAMAAIALAEQALAFAGAJQAIAHADAKQADALABAMQgBAMgDALQgEAKgHAIQgIAIgKAFQgOAEgIAAQgQgBgHgDgAi0gNQgGADgFAGQgFAEgDAHQgDAGAAAJQABAIADAHQACAIAFAFQAEAGAHACQAHADAHAAQAIAAAGgDQAGgCAFgFQAEgGADgHQACgHAAgJQAAgJgCgHQgDgGgEgFQgFgFgGgDQgGgDgIAAQgHAAgHADgAAmBPIAAhxIATAAIAEAVIAEgJQAEgEAEgCIAKgFQAGgBAIAAIACAAIAAAVIgDAAQgIAAgFACQgHABgEAEQgFAEgCAEQgCAHgBAJIAAA9g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-22.4,-8.1,44.8,16.3);


(lib.Символ10 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah4BnIAAiWIATAAIADARQADgFAFgEQAEgEAFgCQAKgEALAAQAMAAALAEQAJAFAIAIQAHAIAEAKQAEAMAAAKQAAAMgEALQgEALgGAIQgIAIgJAFQgPAEgJAAQgLAAgIgCIgKgFQgEgEgEgFIAAA0gAhOgaQgGACgFAFQgEAGgEAHQgCAGAAAIQAAAIACAIQADAHAFAFQAEAFAHADQAGADAJAAQAGAAAHgDQAGgDAEgFQAGgFACgHQADgIAAgIQAAgIgDgGQgCgHgGgFQgEgGgGgCQgHgDgGAAQgIAAgHADgAAhBBQgIgCgGgFQgFgFgDgHQgDgGAAgJQAAgKAEgHQADgHAIgEQAGgDAJgBQAJgCAJAAQAOAAANACIAAgHQAAgGgCgFQgCgEgEgDQgFgEgMAAIgSACIgRAEIgFgSIATgFQAOgCALAAQAKAAAIACQAJACAGAFQAGAFACAHQADAHAAAJIAAAyQAAAHAHAAIAIgBIAAATQgFADgMAAQgHAAgGgEQgGgEAAgJQgEAJgJAFIgKADIgNABQgJAAgHgCgAApAPQgFACgCADQgDAEgBAGQABAFACADQABAEADACQAGAEAKAAIAKgBQAHgCADgDQAFgDACgEQADgFAAgEIAAgMQgLgCgLAAQgNAAgHADgAAyhEQgGgFAAgJQAAgJAGgGQAGgFAIAAQAIAAAGAFQAGAGAAAJQAAAJgGAFQgGAGgIAAQgIAAgGgGgAA4haQgDADABAFQgBAFADADQAEADAEAAQAFAAACgDQADgDAAgFQAAgFgDgDQgCgDgFAAQgEAAgEADg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-12.1,-10.3,24.3,20.7);


(lib.Символ9 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACyBNQgMgEgIgJQgJgIgEgKQgDgHgBgQQAAgNADgKQAFgKAHgIQAIgJALgEIAMgEIAMAAQAJAAAPAEQAKAFAGAHQAHAIADALQADAIAAALIgBAKIhVAAQAAAHAEAHQACAFAGAFQAEADAHADQAGACAJAAQAPAAASgIIAJASQgIAFgMADQgMACgLAAQgSgCgHgCgADlAOQAAgGgCgGQgBgDgDgFQgEgEgFgDQgGgDgIAAQgHABgFACQgGACgFAEQgEAEgDAEQgDAFgCAIIBAAAIAAAAgAAsBQIgLgDQgKgFgHgIQgIgIgDgLQgFgLAAgMQABgNADgJQAEgKAHgIQAHgIALgFIALgEIAMAAQAKAAAIACIAJAGIAJAIIAAg9IAYAAIAACfIgTAAIgEgRQgCAFgEAEIgJAGIgKADIgMABgAAtgNQgGADgEAFQgFAFgDAGQgCAHAAAJQAAAJACAHQADAHAFAGQAEAFAGACQAHADAHAAQAIAAAGgDQAGgCAFgGQAGgFACgIQADgHAAgIQAAgJgDgGQgCgHgGgEQgEgGgHgDQgGgDgIAAQgHAAgHADgAjnBPQgHgDgGgFQgFgEgDgHQgDgGgBgJQABgKAEgHQADgHAHgEQAGgEAKgDQAIgCAKAAQANABAOACIAAgHQAAgEgCgFQgCgFgEgCQgGgEgMAAIgSABIgRAFIgEgSIATgFQAOgDAKABQALAAAIABQAJADAFAFQAGAFACAGQADAIAAAHIAAA0QAAAHAHAAIAIgCIAAAUQgEADgNAAQgHAAgFgEQgGgFgBgIQgEAIgIAGIgLADIgNABQgJAAgHgCgAjfAcQgFADgCADQgDAEAAAGQAAAFACADQACAEADACQAGAEAJAAIALgBQAGgCAEgDQAFgDACgFQACgEABgFIAAgMQgMgBgLAAQgNAAgHACgAkwBPQgFgCgFgFQgDgEgCgHQgBgHgBgKIAAg9IgQAAIAAgOIAQgCIAEgiIAVAAIAAAhIAdAAIAAARIgdAAIAAA+QAAAJACAFQAFADAIAAIAOgCIABARQgMAEgKAAQgJAAgHgCgAEVBPIAAhxIATAAIADAVIAFgJQADgEAFgCIAKgFQAFgBAIAAIADAAIAAAVIgEAAQgHAAgFACQgHABgEAEQgFAEgCAEQgDAHAAAJIAAA9gAgsBPIAAhEQAAgGgCgFQgCgEgEgEQgDgEgFgCQgEgCgGAAQgHAAgFADQgGADgDAEQgFAFgCAEQgBAGAAAHIAAA/IgYAAIAAhxIASAAIAFAUQAKgWAaABQAJgBAIADQAIADAFAFQAHAHACAJQAEAJAAALIAABEgAi3g1QgDgDAAgFQAAgEAEgEQADgDAEAAQAFAAADADQAEAEAAAEQAAAFgEADQgDAEgFAAQgEAAgEgEgAjng1QgCgDAAgFQAAgEADgEQADgDAEAAQAFAAAEADQADADAAAFQAAAFgDADQgEAEgFAAQgEAAgEgEg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-33.8,-8.1,67.6,16.3);


(lib.Символ8 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADWBNQgLgFgJgIQgIgIgEgLQgDgGgCgRQAAgMAEgKQAFgKAHgJQAIgIALgFIALgDIANgBQAJAAAOAEQAKAFAHAIQAGAHAEALQADAIAAAMIgBAKIhVAAQAAAHADAGQADAGAFAEQAFAEAHACQAGACAIABQAQgBASgHIAJASQgIAEgMADQgMACgMAAQgRgBgIgCgAEKANQAAgGgCgFQgBgEgEgEQgDgFgGgCQgFgDgIAAQgHAAgGACQgGACgEAEQgFAFgDADQgDAGgBAHIBAAAIAAAAgAgDBPQgIgDgFgFQgGgFgDgGQgDgHAAgJQAAgJAEgIQAEgGAHgFQAGgEAHgCQAJgCAKAAQANAAANACIAAgHQAAgEgCgFQgBgEgEgDQgGgEgMAAIgSACIgPAEIgFgSIASgFQANgCALAAQALAAAIACQAIADAGAEQAGAFACAHQADAHAAAIIAAA0QAAAGAHAAIAIgBIAAAUQgFADgMAAQgHAAgFgFQgHgEAAgJQgEAJgJAFIgKAEIgNAAQgJAAgFgBgAADAcQgDADgCADQgDADAAAHQAAAEACAEQABADACACQAFAFAKAAIALgCQAGgCAEgDQAEgDADgEQACgEAAgFIAAgMQgLgCgLAAQgNAAgHADgAhMBPQgGgDgEgFQgDgDgCgIQgCgGAAgKIAAg9IgQAAIAAgPIAQgCIAEghIAUAAIAAAhIAeAAIAAARIgeAAIAAA+QAAAJADAEQAEADAJABIAOgCIABARQgNADgKAAQgJAAgGgBgABnBPIAAhxIATAAIADAVIAFgJQADgEAEgDIAKgEQAGgBAIgBIACAAIAAAVIgDAAQgHAAgGACQgGACgFADQgEAEgDAFQgCAGAAAKIAAA9gAiZBPIAAhcIgNgEIAAgRIAlAAIAABxgAj4BPIgohxIAaAAIAcBWIAAAAIAchWIAZAAIgnBxgAiZg3QgEgEAAgGQAAgGAEgEQAEgEAGgBQAGABAEAEQAFAEAAAGQAAAGgFAEQgEAEgGAAQgGAAgEgEg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-28.9,-8.1,57.9,16.2);


(lib.Символ7 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFKBPQgGgCgEgFQgDgEgCgHQgCgHAAgKIAAg9IgQAAIAAgOIAQgCIADgiIAVAAIAAAhIAeAAIAAARIgeAAIAAA+QAAAJADAFQAEADAIAAIAPgCIABARQgNAEgKAAQgJAAgGgCgADIBPQgHgDgFgFQgGgEgDgHQgDgGAAgJQAAgKAEgHQAEgHAGgEQAHgEAJgDQAIgCALAAQANABANACIAAgHQAAgEgCgFQgCgFgEgCQgFgEgMAAIgSABIgSAFIgEgSIAUgFQANgDALABQAKAAAJABQAIADAFAFQAGAFADAGQADAIAAAHIAAA0QAAAHAGAAIAJgCIAAAUQgFADgMAAQgIAAgEgEQgHgFAAgIQgEAIgJAGIgKADIgNABQgJAAgIgCgADQAcQgEADgDADQgDAEAAAGQAAAFACADQACAEAEACQAFAEAKAAIALgBQAGgCAEgDQAEgDADgFQACgEAAgFIAAgMQgLgBgMAAQgMAAgIACgABdBOQgJgDgJgEIAFgRQAUAIAQAAQANAAAFgDQAGgFAAgHQAAgDgDgDIgIgFIgVgHIgLgEQgHgDgEgEQgEgEgDgGQgCgFAAgGQAAgIADgGQADgHAGgDQAFgFAIgCQAIgBAHAAQALgBAMADQAJACAJAEIgFARQgSgGgQgBQgKABgFADQgGAEAAAGQAAADADACQACADAFACIAWAGIAMAEQAGADAEAEQAFAEACAGQADAGAAAHQAAAJgDAGQgEAGgGAFQgFAEgJACQgIACgJAAQgMAAgNgDgAjFBNQgLgEgIgJQgJgIgEgKQgDgHgBgQQAAgNADgKQAFgKAIgIQAHgJALgEIALgEIANAAQAJAAAOAEQALAFAGAHQAHAIADALQADAIAAALIgBAKIhVAAQAAAHADAHQADAFAFAFQAFADAHADQAGACAJAAQAPAAATgIIAIASQgIAFgMADQgMACgLAAQgSgCgIgCgAiRAOQAAgGgBgGQgCgDgEgFQgDgEgGgDQgFgDgHAAQgHABgHACQgFACgFAEQgFAEgDAEQgCAFgBAIIA/AAIAAAAgAlJBNQgFgDgEgDQgEgEgCgFIgEARIgTAAIAAifIAZAAIAAA+IAIgJIAJgGQAJgCAKAAIAMAAIALAEQALAFAGAJQAIAHADAKQADALABAMQgBAMgDALQgEAKgHAIQgIAIgKAFQgOAEgIAAQgQgBgHgDgAlEgNQgGADgFAGQgFAEgDAHQgDAGAAAJQABAIADAHQACAIAFAFQAEAGAHACQAHADAHAAQAIAAAGgDQAGgCAFgFQAEgGADgHQACgHAAgJQAAgJgCgHQgDgGgEgFQgFgFgGgDQgGgDgIAAQgHAAgHADgAAbBPIAAhcIgNgEIAAgRIAkAAIAABxgAhDBPIgohxIAaAAIAcBXIAAAAIAchXIAZAAIgnBxgAAbg2QgEgFAAgFQAAgHAEgDQAEgFAFAAQAHAAADAFQAFADAAAHQAAAFgFAFQgEADgGAAQgFAAgEgDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-36.8,-8.1,73.6,16.3);


(lib.Символ6 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFMBPQgGgCgEgFQgEgEgCgHQgBgHAAgKIAAg9IgQAAIAAgOIAQgCIADgiIAVAAIAAAhIAeAAIAAARIgeAAIAAA+QAAAJADAFQAEADAIAAIAOgCIABARQgMAEgKAAQgJAAgGgCgABoBOQgKgDgJgEIAFgRQAVAIAOAAQANAAAGgDQAGgFAAgHQAAgDgDgDIgHgFIgWgHIgLgEQgGgDgFgEQgEgEgDgGQgCgFAAgGQgBgIAEgGQADgHAGgDQAFgFAIgCQAIgBAHAAQALgBAMADQAJACAJAEIgFARQgSgGgQgBQgKABgFADQgGAEAAAGQAAADADACQACADAFACIAWAGIAMAEQAGADAEAEQAEAEADAGQADAGAAAHQAAAJgDAGQgDAGgHAFQgGAEgIACQgIACgJAAQgMAAgMgDgAjYBPQgFgDgDgEQgDgFgCgNIAAiGIAYAAIAACEQAAAIAKACIAKgBIAAASQgIACgLAAQgHAAgFgCgAEIBPIgfgsIgOAPIAAAdIgXAAIAAifIAXAAIAABkIAsg2IAcAAIgtA0IAsA9gAAkBPIAAhcIgMgEIAAgRIAkAAIAABxgAgWBPIAAhEQAAgGgCgFQgBgEgDgEQgEgEgEgCQgFgCgGAAQgHAAgGADQgFADgEAEQgDAFgCAEQgCAGAAAHIAAA/IgYAAIAAhxIATAAIADAUQAMgWAZABQAJgBAHADQAJADAGAFQAFAHAEAJQABAJAAALIAABEgAibBPIAAhcIgOgEIAAgRIAlAAIAABxgAkTBPIgyhFIgTAWIAAAvIgYAAIAAiYIAYAAIgCBOIABAAIBDhOIAbAAIg5BEIA/BUgAAkg2QgDgFAAgFQAAgHADgDQAEgFAGAAQAHAAADAFQAFADAAAHQAAAFgFAFQgEADgGAAQgGAAgEgDgAibg2QgFgFAAgFQAAgHAFgDQADgFAHAAQAFAAAFAFQAEADAAAHQAAAFgEAFQgFADgFAAQgHAAgDgDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-37,-8.1,74,16.3);


(lib.Символ1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.MONACO();
	this.instance.setTransform(-400,-257.9,0.986,0.986);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-400,-257.9,788.6,525.4);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(39).call(this.frame_39).wait(1));

	// Символ 37
	this.instance = new lib.Символ47();
	this.instance.setTransform(61.3,-28.3,0.419,0.419);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).to({alpha:1},10).wait(26));

	// Символ 36
	this.instance_1 = new lib.Символ39();
	this.instance_1.setTransform(-13.1,-1.6,1.112,1.112,-5.2);

	this.instance_2 = new lib.Символ40();
	this.instance_2.setTransform(-16.7,-2.1,1.112,1.112,-5.2);

	this.instance_3 = new lib.Символ41();
	this.instance_3.setTransform(-16.1,-1.4,1.112,1.112,-5.2);

	this.instance_4 = new lib.Символ42();
	this.instance_4.setTransform(-20.1,-1.2,1.112,1.112,-5.2);

	this.instance_5 = new lib.Символ43();
	this.instance_5.setTransform(-18.1,-2.6,1.112,1.112,-5.2);

	this.instance_6 = new lib.Символ44();
	this.instance_6.setTransform(-16.8,-0.3,1.112,1.112,-5.2);

	this.instance_7 = new lib.Символ45();
	this.instance_7.setTransform(-16.1,-1.7,1.112,1.112,-5.2);

	this.instance_8 = new lib.Символ46();
	this.instance_8.setTransform(-12,-1.8,1.112,1.112,-5.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_2}]},5).to({state:[{t:this.instance_3}]},7).to({state:[{t:this.instance_4}]},5).to({state:[{t:this.instance_5}]},5).to({state:[{t:this.instance_6}]},7).to({state:[{t:this.instance_7}]},5).to({state:[{t:this.instance_8}]},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.2,-39.8,54.1,76.5);


(lib.Символ26 = function() {
	this.initialize();

	// Слой 3
	this.instance = new lib.Символ27();
	this.instance.setTransform(1.3,-62.9,1.185,1.185);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-107.5,-102.1,225.2,78.3);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 22
	this.instance = new lib.Символ22();
	this.instance.setTransform(-192.8,-27);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(23).to({x:-96.2,y:-115.8,alpha:0},0).to({y:-121.6,alpha:1},14,cjs.Ease.get(1)).wait(102).to({y:-128.7,alpha:0},10,cjs.Ease.get(-1)).wait(1));

	// Символ 21
	this.instance_1 = new lib.Символ21();
	this.instance_1.setTransform(-190.4,-114.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(20).to({_off:false},0).to({y:-119.8,alpha:1},14,cjs.Ease.get(1)).wait(103).to({y:-127,alpha:0},10,cjs.Ease.get(-1)).wait(3));

	// Символ 20
	this.instance_2 = new lib.Символ20();
	this.instance_2.setTransform(-240.7,-115.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(17).to({_off:false},0).to({y:-121.2,alpha:1},14,cjs.Ease.get(1)).wait(104).to({y:-128.3,alpha:0},10,cjs.Ease.get(-1)).wait(5));

	// Символ 19
	this.instance_3 = new lib.Символ19();
	this.instance_3.setTransform(5.8,-140.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(14).to({_off:false},0).to({y:-145.8,alpha:1},14,cjs.Ease.get(1)).wait(105).to({y:-153,alpha:0},10,cjs.Ease.get(-1)).wait(7));

	// Символ 18
	this.instance_4 = new lib.Символ18();
	this.instance_4.setTransform(-48.4,-139.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(11).to({_off:false},0).to({y:-145.4,alpha:1},14,cjs.Ease.get(1)).wait(106).to({y:-152.5,alpha:0},10,cjs.Ease.get(-1)).wait(9));

	// Символ 17
	this.instance_5 = new lib.Символ17();
	this.instance_5.setTransform(-110.2,-140.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(8).to({_off:false},0).to({y:-146.2,alpha:1},14,cjs.Ease.get(1)).wait(107).to({y:-153.4,alpha:0},10,cjs.Ease.get(-1)).wait(11));

	// Символ 16
	this.instance_6 = new lib.Символ16();
	this.instance_6.setTransform(-157.3,-141.6);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(5).to({_off:false},0).to({y:-147.3,alpha:1},14,cjs.Ease.get(1)).wait(107).to({y:-154.5,alpha:0},10,cjs.Ease.get(-1)).wait(14));

	// Символ 15
	this.instance_7 = new lib.Символ15();
	this.instance_7.setTransform(-190.7,-141.8);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(2).to({_off:false},0).to({y:-147.6,alpha:1},14,cjs.Ease.get(1)).wait(108).to({y:-154.7,alpha:0},10,cjs.Ease.get(-1)).wait(16));

	// Символ 14
	this.instance_8 = new lib.Символ14();
	this.instance_8.setTransform(-236,-141.5);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({y:-147.2,alpha:1},14,cjs.Ease.get(1)).wait(108).to({y:-154.4,alpha:0},10,cjs.Ease.get(-1)).wait(18));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-252.4,-149.3,116.4,130.5);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 6
	this.instance = new lib.Символ6();
	this.instance.setTransform(-220,13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(149));

	// Символ 13
	this.instance_1 = new lib.Символ13();
	this.instance_1.setTransform(-109.5,-37.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(21).to({_off:false},0).to({y:-47.3,alpha:1},14,cjs.Ease.get(1)).wait(104).to({y:-54.4,alpha:0},10,cjs.Ease.get(-1)).wait(1));

	// Символ 12
	this.instance_2 = new lib.Символ12();
	this.instance_2.setTransform(-158.8,-35.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(18).to({_off:false},0).to({y:-45.1,alpha:1},14,cjs.Ease.get(1)).wait(104).to({y:-52.2,alpha:0},10,cjs.Ease.get(-1)).wait(4));

	// Символ 11
	this.instance_3 = new lib.Символ11();
	this.instance_3.setTransform(-201.3,-37.3);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({y:-47.3,alpha:1},14,cjs.Ease.get(1)).wait(105).to({y:-54.4,alpha:0},10,cjs.Ease.get(-1)).wait(6));

	// Символ 10
	this.instance_4 = new lib.Символ10();
	this.instance_4.setTransform(-244.8,-36);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(12).to({_off:false},0).to({y:-45.9,alpha:1},14,cjs.Ease.get(1)).wait(105).to({y:-53.1,alpha:0},10,cjs.Ease.get(-1)).wait(9));

	// Символ 9
	this.instance_5 = new lib.Символ9();
	this.instance_5.setTransform(12.7,-62.4);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(9).to({_off:false},0).to({y:-72.3,alpha:1},14,cjs.Ease.get(1)).wait(105).to({y:-79.5,alpha:0},10,cjs.Ease.get(-1)).wait(12));

	// Символ 8
	this.instance_6 = new lib.Символ8();
	this.instance_6.setTransform(-59.6,-62.3);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(6).to({_off:false},0).to({y:-72.3,alpha:1},14,cjs.Ease.get(1)).wait(105).to({y:-79.4,alpha:0},10,cjs.Ease.get(-1)).wait(15));

	// Символ 7
	this.instance_7 = new lib.Символ7();
	this.instance_7.setTransform(-134.7,-62.4);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(3).to({_off:false},0).to({y:-72.3,alpha:1},14,cjs.Ease.get(1)).wait(106).to({y:-79.5,alpha:0},10,cjs.Ease.get(-1)).wait(17));

	// Символ 6
	this.instance_8 = new lib.Символ6();
	this.instance_8.setTransform(-220,-62.4);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({y:-72.3,alpha:1},14,cjs.Ease.get(1)).wait(107).to({y:-79.5,alpha:0},10,cjs.Ease.get(-1)).wait(19));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-257,-70.5,74,92.3);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ23();
	this.instance.setTransform(0,198.6,0.808,1.475,0,0,0,0,0.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(99).to({_off:false},0).to({y:163.4},16,cjs.Ease.get(-1)).to({y:132.6},14,cjs.Ease.get(1)).wait(291).to({y:206},20,cjs.Ease.get(-1)).wait(10));

	// Слой 1
	this.instance_1 = new lib.Символ1();
	this.instance_1.setTransform(0,0,0.541,0.541);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:0.48,scaleY:0.48,alpha:1},34,cjs.Ease.get(1)).wait(65).to({scaleY:0.47,y:-14},16,cjs.Ease.get(-1)).to({scaleY:0.47,y:-26.2},14,cjs.Ease.get(1)).to({scaleX:0.58,scaleY:0.56,y:-25.2},270).wait(30).to({scaleX:0.48,scaleY:0.48,y:0,alpha:0},20).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-216.5,-139.6,426.9,284.4);


(lib.Анимация1 = function() {
	this.initialize();

	// Слой 4
	this.instance = new lib.Символ38();
	this.instance.setTransform(10.6,-0.7);

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#005468").s().p("AljAfQgcgCAbABQAbABABgTQAAgQA0gEQAzgEBBgOQBAgNA2ANQAqAMAEAAQA+gIAbgCQAvgDAWAYQAMANDFgaQh4AUhXAIQhXAIg9AAQg7ABhbAGQhaAGgzAAIgQAAQgoAAgYgCg");
	this.shape.setTransform(-20.1,-38.2);

	// Слой 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0087A5").s().p("ArAGYQghgggJgYQgmgHgNgTQgGgJgBgPQABgUBVgjQBcglAJgXQAIgRAWgXQgMgFgHgKQgHgKABgOQAAgMALgMQAMgNAWgJQhCgOgXgNQgXgNgBgXQAFgRAIgUQAKgaALgOIAAgCQAAgHACgEQgYgHgtgDIhdgFQhvgJAAg0QAAgjBigMQBlgHBGgJQAKgLAQgMQAlgdAdgJQABgSANgEQAPgYB5gQQBqgNBjAAQArAAAqAPIAKAEQB5gWCugQQDEgTB8gSQB7gSCLgEQCLgFhQAqQhQAqgDAGIAGACQAHgJAJgGQBCgvAvBXQAkBCAAA0QAAAqgHAjQgNBBgfAAQgaAAgRgKIgYAbQg1A1gUAAQgUAAgLgKQgNAJgJAAQgcAAgJgWQgEgHgBgIQgUgDgIgSQgDgHgBgHQgPAHgWAGIgZAHQACAHAAAIQgBAJgGAKQAeAFAXANQAiATgIAeQBEATAYAlQAPAXAAAsQgBBmgzArQhOBBjlABQgJACgIAAQhvAAh+goQh6goAAgfIABgIQgfABghAAIg8AAQAEAHAAAIQAAANgNAMQgSATgsADQgYABgWATQgTASgiAAIglgDQgegEgMABQgXACgYgMQgLgGgJgGQgHAAgUAFQgUAGgIAAQgcAAgJgVIgFgXQAAgPAXgQIAIgFQgqAUgRBBQgPA6gDAGQgNAegaAAQgcAAgngmgAqYE/IgFADIALANQAEgGACgMIgBAAIgLACgAEZEFIALACIgJgDgAJuC/QABAegKAWQAIgIACgKQgEgqAOgXQgHgCgJgBQAGANgBAVgAnJCjIgsALIgDACQA2ADAdAKIAJgFIABgBQgUgFgIgSIAAgCIgSAFgAgbCgIAVgBIACgEIgUgCIgDAHgAFPCBIAlAFIADgDQAMgOALgBQgXABgoAMgAKijSQgKADg4ATQgIAMgKALIgBACQAfAFALATIABABQAZgpAWggIgFABg");
	this.shape_1.setTransform(-0.1,-0.9);

	// Слой 1
	this.instance_1 = new lib.Crowdscore();
	this.instance_1.setTransform(-111.2,-111.2,1.483,1.483);

	this.addChild(this.instance_1,this.shape_1,this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-111.2,-111.2,222.4,222.4);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(1));

	// Слой 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003042").s().p("An2EiIAApcQAsgWA2AAQBZAAA/A8QBAA9gBBUQAABNgyA2QAyA5AABQQAABTg3A6Qg4A7hPAAQhHAAg0gvgACNDmQgUhYAAh7QAAh6AUhXQAFgWAFgQQhugChPgOQhdgQAAgWQAAgXBdgPQBbgQCEAAQCEAABdAQQBdAPAAAXQAAAWhdAQQhOAOhpABQAGARAFAWQAUBXAAB6QAAB7gUBYQgUBXgdAAQgcAAgUhXg");
	this.shape.setTransform(-290.6,-10.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(19));

	// Слой 1
	this.bt = new lib.Символ26();
	this.bt.setTransform(81,-45.7,0.912,0.912,0,0,0,-2.5,-63.1);
	this.bt.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.bt).to({scaleX:0.78,scaleY:0.78,x:81.1,alpha:1},9,cjs.Ease.get(-1)).to({scaleX:0.64,scaleY:0.64,y:-45.6,alpha:0},10,cjs.Ease.get(-1)).wait(1));

	// Слой 3
	this.instance = new lib.Символ48();
	this.instance.setTransform(94.8,-45.3);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.852},9).to({alpha:0},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-340.9,-187.2,607.5,283.7);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().rr(-133.3,-15.9,266.6,31.8,10.7);
	this.shape.setTransform(1.1,-25.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(449));

	// Символ 5
	this.instance = new lib.Символ5();
	this.instance.setTransform(89.9,20.8,0.911,0.911);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(129).to({_off:false},0).to({_off:true},150).wait(171));

	// Символ 4
	this.instance_1 = new lib.Символ4();
	this.instance_1.setTransform(97.8,-47.8,0.911,0.911);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(279).to({_off:false},0).to({_off:true},151).wait(20));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-132.1,-41.6,266.6,31.8);


(lib.Символ25 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Анимация1("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-111.2,-111.2,222.4,222.4);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ25();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.94,scaleY:0.94},15,cjs.Ease.get(-1)).to({scaleX:0.88,scaleY:0.88},14,cjs.Ease.get(1)).to({scaleX:0.95,scaleY:0.95},16,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1},14,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-111.2,-111.2,222.4,222.4);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Crowdscore();
	this.instance.setTransform(-425.9,-280.2);

	this.instance_1 = new lib.Символ24();
	this.instance_1.setTransform(0,0,1,1,-33.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[]},1).to({state:[{t:this.instance_1}]},43).to({state:[{t:this.instance_1}]},15).to({state:[{t:this.instance_1}]},5).to({state:[{t:this.instance_1}]},355).to({state:[{t:this.instance_1}]},10).wait(21));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(44).to({_off:false},0).to({scaleX:0.56,scaleY:0.56,rotation:0,x:-1.1,y:-5,alpha:1},15,cjs.Ease.get(-1)).to({scaleX:0.62,scaleY:0.62},5,cjs.Ease.get(1)).wait(355).to({scaleX:0.4,scaleY:0.4,alpha:0},10).wait(21));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-425.9,-280.2,150,150);


// stage content:



(lib.smartson300250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.addEventListener("mouseover", fl_mouseover.bind(this));
		function fl_mouseover()
		{
		this.but.gotoAndPlay(1);
			
		}
		
		document.addEventListener("mouseout", fl_mouseout.bind(this));
		
		function fl_mouseout()
		{
		this.but.gotoAndPlay(11);
			
		}
		
		
		
		this.but.bt.addEventListener("mouseover", fl_mouseover1.bind(this));
		function fl_mouseover1()
		{
		this.but.bt.gotoAndPlay(1);
			
		}
		
		this.but.bt.addEventListener("mouseout", fl_mouseout1.bind(this));
		
		function fl_mouseout1()
		{
		this.but.bt.gotoAndPlay(11);
			
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 6
	this.instance = new lib.Символ49();
	this.instance.setTransform(272.1,29.9,0.804,0.804);
	this.instance.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance.cache(-27,-34,54,69);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 4
	this.but = new lib.Символ32();
	this.but.setTransform(64.1,174.1,1,1,0,0,0,0,9.4);

	this.timeline.addTween(cjs.Tween.get(this.but).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ30();
	this.instance_1.setTransform(151.1,319.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 3
	this.instance_2 = new lib.Символ2();
	this.instance_2.setTransform(60.3,64.2,0.768,0.768,-14.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 2
	this.instance_3 = new lib.Символ3();
	this.instance_3.setTransform(147.4,125.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-159.8,32.6,667.6,401.9);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;