(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/arrow.png?1466005601231", id:"arrow"},
		{src:"images/bg.jpg?1466005601231", id:"bg"},
		{src:"images/clode.png?1466005601231", id:"clode"},
		{src:"images/fuel_64x64.png?1466005601231", id:"fuel_64x64"},
		{src:"images/gold_64x64.png?1466005601231", id:"gold_64x64"},
		{src:"images/logo.png?1466005601231", id:"logo"},
		{src:"images/money_64x64.png?1466005601231", id:"money_64x64"},
		{src:"images/upir_02.png?1466005601231", id:"upir_02"},
		{src:"images/upir_05.png?1466005601231", id:"upir_05"},
		{src:"images/upir_08.png?1466005601231", id:"upir_08"},
		{src:"images/upir_13.png?1466005601231", id:"upir_13"},
		{src:"images/upir_16.png?1466005601231", id:"upir_16"}
	]
};



// symbols:



(lib.arrow = function() {
	this.initialize(img.arrow);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,25,24);


(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.clode = function() {
	this.initialize(img.clode);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,215,112);


(lib.fuel_64x64 = function() {
	this.initialize(img.fuel_64x64);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,64,64);


(lib.gold_64x64 = function() {
	this.initialize(img.gold_64x64);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,64,64);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,139,90);


(lib.money_64x64 = function() {
	this.initialize(img.money_64x64);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,64,64);


(lib.upir_02 = function() {
	this.initialize(img.upir_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,307,623);


(lib.upir_05 = function() {
	this.initialize(img.upir_05);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,121,142);


(lib.upir_08 = function() {
	this.initialize(img.upir_08);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,91,113);


(lib.upir_13 = function() {
	this.initialize(img.upir_13);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,242,131);


(lib.upir_16 = function() {
	this.initialize(img.upir_16);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,62);


(lib.Символ75 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.Символ74 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Eg5oAfFMAAAg+JMBzRAAAMAAAA+Jg");
	this.shape.setTransform(369,199);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,738,398);


(lib.Символ72 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhcCrQgRgBgCgGIgBgbQABgTACgRQADgSAcAAQAShSAIhGQAFhHAaAAIB3ABQAeABAGAcQAFAbgEAtIgKB4QANAAAAANIABA3QABAQgJACQgIACgHAAQgUABgDgHQgDgEgBgLQgCgKgBgQQhwADgggBIgCAYIAAADQAAATgHAAgAgEhBIgQBOQgLAyAqgEIAigBQAYABAEgHQAFgIAAgbIADhHQAAglgxAAIgUgBIAAAAQgMAAgEAbgAC+CPQgXgCgFguQgGgwAAg+QAAg/AHgtQAFgrAdgCIAtgCQAPAAAYADQAdABAEATQAEATAAAMQAAAMgKAIQgNAJgQABIg2AAIgCArQAygGAIAHQAGAIABAQQABAQgCAMQgDANgzAFQgBATACAMIA5gFQARgBAKAVQAJAWgJASQgHARgxAHQgqAFgYAAIgGAAgAkzB2QgFgEgBgIIgIjjQgBgJAGgEQAFgGAHAAQBAgBBIAKQAWAAAAASQAAAMgDAHQgFAHgOgBIg0gBQgkgBgLADQgCAKADAyIAEBCQACARAAAeQAAAfgVAEIgMABQgKAAgEgEg");
	this.shape.setTransform(40.7,17.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFF00").s().p("AGBCZQgNgFgIgOQgHgPALgSQAJgSAZACQAYACAGARQAFAJAAAHQAAAJgEAGQgGAOgPAEIgOABQgHAAgGgBgAhvB9IgEgZQgDgPAKgHQALgGATgEQAVgCARgaQgSgogYgiQgYgmgEgMQgEgNAJgJQAJgIAPgDQAPgEAOAOQAOANAcA0QAXhDANgQQAOgQAMACQANACAQAOQARAOgdA8Ig9B1QgeA/gsABIgNABQgdAAgDgIgAB7B5QgFgEgBgJIgJjjQAAgIAGgEQAEgGAIAAQA/gBBJAKQAVAAABASQAAAMgEAGQgEAIgOgBIg0gBQglgBgLADQgCAKADAxIAFBCQACASAAAeQAAAfgVAEIgMABQgKAAgEgEgAkjB2IACgtQgDgkACgoQABgqgCgnQgDgmAQgPQAPgPATAAIAPgBIAYADQAZAEAfATQAcASAIAoQAHAwgKAVQgLAYgXANQgXAMgaADIgjAEQAHA+gEACQgDABgbAAgAjyhRQgEAhAGAjQAIAiAsgLQAtgKgCgmQgBglgOgSQgPgQgfgCIgEAAQgbAAgFAegAnOB4QgYAAABg5QABg6gChHQgDhHAYABQAZABAHAJQAHAKgDA8QAagRAXgiQAXghARADQAQACAGAQQAFAQgDAOQgFANgTAVQgTAXgQAXIArArQAVAWABAUQABATgKAKQgLAKgTABQgRAAgNgYQgMgYgRgQQgSgQgBAUQAAAtgCALQAAAJgXAAIgKgBgAFyBDQgJgDgBgOQgCgPAPgYIAdguQAPgYgPgIQgPgGgMAEQgMADgOALQgNALgJgTQgKgUAAgPQAAgQAdgMQAcgNAkACQAjABAWAaQAXAbgEAjQgDAigXASQgXATgIAPIgNAYQgEAIgRABIgGAAQgMAAgHgEg");
	this.shape_1.setTransform(48.8,54.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,97.5,70.1);


(lib.Символ71 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.arrow();
	this.instance.setTransform(0,18,1,1,-46);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,34.6,34.7);


(lib.Символ69 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FC582F").s().p("AlVFWIAAqrIKrAAIAAKrg");
	this.shape.setTransform(34.3,34.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,68.5,68.5);


(lib.Символ68 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FC582F").s().p("AlVFWIAAqrIKrAAIAAKrg");
	this.shape.setTransform(34.3,34.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,68.5,68.5);


(lib.Символ66 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEA02").s().p("AkTEUQhyhzgBihQABigByhzQBzhyCggBQChABBzByQByBzABCgQgBChhyBzQhzByihABQiggBhzhyg");
	this.shape.setTransform(39.1,39.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,78.2,78.2);


(lib.Символ65 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEA02").s().p("AkTEUQhyhzgBihQABigByhzQBzhyCggBQChABBzByQByBzABCgQgBChhyBzQhzByihABQiggBhzhyg");
	this.shape.setTransform(39.1,39.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,78.2,78.2);


(lib.Символ64 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#513F82").s().p("Al8D3IAAntIHWiaIEjGQIkjGQg");
	this.shape.setTransform(38.2,40.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,76.3,80.2);


(lib.Символ63 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#513F82").s().p("Al8D3IAAntIHWiaIEjGQIkjGQg");
	this.shape.setTransform(38.2,40.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,76.3,80.2);


(lib.Символ54 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AA/g7IABAAIgBgBQgGABhjA6QhwA+ACAAQDcg+A+gRQAXgHAAAAQACAAhbgiQAAAAgBAAg");
	this.shape.setTransform(15.4,77.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AofE6IgBgBIAXgGIAAAAIhZgiIBZAiIAAAAIgXAGIkcBRQgCAABwhAQBlg5AGgBIABABIgBgBQioh1AAibQAAi3DsiDQDsiBFLgBQFOABDrCBQDsCDAAC3QAAC4jsCCQjrCDlOAAQlLAAjsiDgApiERIAAAAIgBAAIABAAg");
	this.shape_1.setTransform(83,44.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,0,167,89);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Al7C1IgHgCQgEgBAAgIIAWhZQAEgRgEgFQADgHANgBQAHAAAGADQAFAOACAUIAFASQAMgGAGgSIAGgMQgBgLAXAHIAJAeQAJAZADAVIAEAdQgBAIgEAAIgHACIgHAAQgEAAgEgXIgJgiQgKgFgQAzQgEAGgFAAQgFAAgCgFIgEgIIgCgJQgFgdgIgNQgGAZgIArQgDACgEAAIgFgBgAFuCzQgFgDAAgIQgBgJAHgCQAGgCAGACQAGABACAFQACAFgBADQgBAEgDADQgDADgFABIgBAAQgEAAgFgDgAD3CnQgPgPABgNQgLgBgWAAIgCAfQgCAIgIABQgIAAgEgCQgEgCACgIQAAhZACgHQACgHAGgCQAFgCAHABQAGABgBAJIAAAkQAUADAOgEQABgSAOgUQAOgTAbABQAcABAPANQAQANgBAcQgBAbgQAYQgIAMgKAGQgLAGgOABIgFAAQgXAAgOgNgAEiBOQgLACgJANQgJANABAOQABAOAHAHQAHAHAOgCQAOgDAIgMQAJgMgDgOQgDgPgHgHQgGgGgIAAIgFABgAgPCoQgNgLgFgWQgGgXAOgdQANgcAVgJQAXgJAGACQAIAEAEAKQACAIgCAJIgEAGQgCADgPAFQgQAGgIAQQgHAQABAKQABAKAJACQAKABAIgEIAMgIQAGgEAHAFQAFADACAEIABhDQAAgSADgDQACgCAFgBQAEAAAHACQAHADgBAqIABASQALgRAOgNQAOgNAKgLQAKgMAHABQAHABACAHQACAGgBAuQgBAtgCAIQgDAHgHACQgGABgEAAQgEgBgCgFQgCgFAEgtQgPANgUAWQgTAWgNABQgGAAgDgCQgDgCAAgQIgEAJQgVAPgTAAIgBAAQgQAAgMgLgAhvCoQgNgLgFgWQgGgXAOgdQANgcAXgJQAXgJAGACQAIAEAEAKQACAIgCAJIgEAGQgCADgPAFQgQAGgIAQQgJAQABAKQABAKALACQAKABAIgEIAMgIQAGgEAHAFQAHAEABAGQABAGgHAOQgVAPgTAAIgBAAQgSAAgMgLgAj1CtQgDgCABgaIABhHQABgSACgDQADgCAEgBQAEAAAIACQAHADgBAqIAAASQALgRAPgNQAOgNAKgLQAJgMAIABQAHABACAHQABAGAAAuQgBAtgDAIQgCAHgHACQgHABgEAAQgDgBgCgFQgCgFAEgtQgQANgTAWQgUAWgNABQgFAAgEgCgAFoCEQgCgRgBgYQgBgXABgOQABgNASABQAQACgBAMIgHBVQAAAHgLABQgLAAgCgRgABcAFQgJgBAAgDIgBgKIACgRQABgIANAAQAIgmAEghQACghAMAAIA4AAQAOABADANQACAMgCAVIgEA4QAGAAAAAGIAAAaQABAFgEABIgHABQgKABgBgEQgCgBgBgQIhEABIgBANQAAAHgDAAgACEhoIgHAlQgFAYAUgCIAQgBQALABACgEQACgDAAgNIABgiQABgRgXAAIgJAAIgBAAQgFAAgDAMgAiQgcQgRgSgBgbIAAgCIAAABQgFALgLAGQgKAGgMABIgRACQAEAdgCABIgOAAIgOgBIABgVQgCgRABgTQABgUgBgSQgBgRAHgHQAHgHAJAAIAHgBIALACQALACAPAIQANAJADASIACALQADgOAIgMQAOgWAXgDQAWgEAQAFQAQAEALAPQALAPAAAZQAAAZgIAWQgJAWgmADIgNABQgbAAgOgOgAhshwQgTADgCAZQgBAYAMAHQANAGAMAAQALAAAIgHQAIgGADgSQADgTgOgJQgMgHgNAAIgJABgAjchwQgCAPADAQQADARAVgFQAUgGAAgRQgBgSgGgIQgHgHgPgBIgCAAQgMAAgCAOgADTgUQgEgCACgZIABhIQAAgSADgCQACgDAFAAQAEgBAHADQAHACgBAqIABASQALgQAOgNQAOgNAKgMQAKgMAHABQAHACACAGQACAHgBAtQgBAtgCAIQgDAIgHABQgGACgEgBQgEgBgCgFQgCgFAEgsQgPAMgUAWQgTAXgNAAQgGAAgDgCgAgegUQgEgCACgZIABhIQAAgSADgCQACgDAFAAQAEgBAHADQAHACgBAqIABASQAJgQAOgNQAOgNAKgMQAKgMAHABQAHACACAGQACAHgBAtQgBAtgCAIQgDAIgHABQgGACgEgBQgEgBgCgFQgCgFAEgsQgPAMgUAWQgRAXgNAAQgGAAgDgCgAlwgZIgBgMIABhQQgVACgBgIQgBgIACgFQABgGALgCQALgBATABIBQADQADAAADACQACACABAGQAAAGgEAFQgFAFgDgBQgDAAADAUQACAfgBAXQgBAGgEACQgEACgGgBQgHAAAAgIIAAgYIgEgyQglABgIABIgDBNQgBAIgDACIgMADIgEABQgFAAAAgDgAAGiQQgNAAgHgJQgHgJgCgKQgBgFAHgDQAHgDAEAHQAEAHACACQAEABAKAAQAJAAAFgEQAFgEADAEIAGAGQADADgNAJQgLAIgOAAIgBAAg");
	this.shape.setTransform(39.2,18.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,78.4,36.5);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("Ah2BNQgIAAgBgDIAAgNIABgQQABgJANAAQAJgkADghQADghAMAAIA4ABQAOAAACANQADANgCAUIgFA3QAGAAAAAGIABAZQAAAIgEABIgHABQgJAAgCgDQgBgEgCgPIhDABIgBAMQAAAJgDAAgAhNgfIgIAjQgFAXAUgCIAQAAQALAAACgDQACgEABgMIABggQAAgRgXAAIgJgBIAAAAQgFAAgDANgAEnA3QgJgDgBgKQgBgKANgfQAMgdANgUQANgVAbAEQAQACAGATQAFASAGAhQAHAjgDAFQgDAFgGACQgGACgMAAQgMAAgBgbQgKgBgPABQgCAIgEAJQgEAIgKACIgIABQgGAAgFgCgAFPgFQAAAFAQAAQASAAgFgTQgBgMgJgEIgBAAQgKAAgIAegAAEA3QgGgDgBgKQgBgKAKgfQAMgdANgUQANgVAcAEQAPACAGATQAGASAGAhQAGAjgDAFQgCAFgHACQgGACgMAAQgMAAgBgbQgKgBgPABQgBAIgFAJQgEAIgKACIgHABQgGAAgGgCgAAtgFQgBAFARAAQARAAgFgTQAAgMgKgEIAAAAQgKAAgIAegAjsAqQgRgSgBgZQAAgbAOgWQAOgVAXgEQAWgDAQAEQAQAFALAPQALAPAAAZQAAAXgIAWQgJAVgmAEIgNABQgbAAgOgPgAjIgoQgTADgCAZQgBAXAMAGQANAGAMAAQALAAAIgGQAIgHADgQQADgSgOgJQgLgHgOAAIgJAAgAByAzIABgVQgCgQABgSQABgTgBgSQgBgSAHgHQAHgHAJAAIAHAAIALABQALACAPAJQANAIADATIACAHIgBgGQgBghALABQALAAAEAEQADAFgBAcQAMgIAKgQQALgPAIABQAHABADAIQACAHgBAGQgCAGgJAKQgJALgHAKIATATQAKAKABAKQAAAJgFAEQgFAFgIAAQgIAAgGgLQgGgLgIgHQgIgIgBAJIAAAaQgBAFgPgBQgLAAABgaIAAgqQgBAJgCAGQgFAJgLAGQgKAFgMACIgRABQAEAdgCABIgOABgACJgoQgCAPADARQADAOAVgFQAUgDAAgSQgBgRgGgIQgHgIgPgBIgBAAQgNAAgCAOgAl5AtIgBgLIABhOQgVABgBgIQgBgHACgGQABgGALgBQALgCATABIBQAEQADAAADACQACACABAGQAAAFgEAFQgFAFgDAAQgDgBADAVQACAdgBAWQgBAHgEACQgEACgGgBQgHgBAAgHIAAgYIgEgxQglABgIACIgDBLQgBAIgDACIgMADIgEAAQgFAAAAgDg");
	this.shape.setTransform(40.1,7.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,80.1,15.6);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AA5BNQgIAAgBgDIAAgNIABgQQABgJANAAQAJgkADghQADghAMAAIA4ABQAOAAACANQADANgCAUIgFA3QAGAAAAAGIABAZQAAAIgEABIgHABQgJAAgCgDQgBgEgCgPIhDABIgBAMQAAAJgDAAgABigfIgIAjQgFAXAUgCIAQAAQALAAACgDQACgEABgMIABggQAAgRgXAAIgJgBIAAAAQgFAAgDANgAjeA/QgPgGgDgYQgCgYAFglQAFgnAPgFQAQgCAPADQAPACAJAJQAJAJABAUQAAAVgIAFQALAIABAMQACAMgDASQgDARgcADIgTABQgOAAgJgDgAjQALQgBAEAAAPQgDAHATAAQATAAgBgOQgBgNgKgDIgQgBQgGABAAAEgAjNgtIgBAWQAAAEAJABQAIABAGgDQAHgEAAgHQAAgHgDgFQgDgFgKgBIgEAAQgIAAgBAEgAn8A+QgFgCgBgHIABgFIgBgMQgCgHABgKQABgNgBgLQgBgMAAgZQgdAHgIgHIgCgNIACgHQAFgGAFABQAEgBAMAAIAcACQAQABAUgBQADAUgMgBIgSgBIgBAjQAAAVACAJIABALIAAAJQAEAVgGAFIgIABQgFAAgFgCgAGxA7IgHgCQgEgBAAgIIAWhXQAEgRgEgFQADgHANgBQAHAAAGADQAFAOACAUIAFASQAMgGAGgSIAGgMQgBgLAXAHIAJAeQAJAYADAUIAEAdQgBAIgEAAIgHACIgHAAQgEAAgEgXIgJgiQgKgDgQAxQgEAGgFAAQgFAAgCgFIgEgIIgCgJQgFgdgIgLQgGAXgIArQgDACgEAAIgFgBgACtA6IACgcIABgZIAAgOQgBgIABgLIACghQgDgIAGAAIAQABQAFAAgBAHQgEAGgBANIgBASIADAGIAWACQAdACAAgCQAFgNAAgPQgBgIABgIIATAAQAIgEAAADIgIAdQgBAGAAAKIAAAYQAAAJADAJQADAJACALQABAGgEABIgHADQgIACgKgDIgBgHIgBgPQAAgMgCgJQgCgIguAGQgEAHgCANIgBAUQADAIgDABQgEABgDgBIgHAAIgGgBgAE4AqQgRgSAAgZQgBgbAOgWQAPgVAWgEQAXgDAPAEQAQAFALAPQALAPABAZQAAAXgJAWQgJAVglAEIgNABQgcAAgOgPgAFcgoQgTADgBAZQgCAXANAGQANAGALAAQAMAAAIgGQAHgHADgQQAEgSgPgJQgLgHgOAAIgJAAgAg7AqQgRgSgBgZQAAgbAOgWQAOgVAXgEQAWgDAOAEQAQAFALAPQALAPAAAZQAAAXgIAWQgJAVgkAEIgNABQgbAAgOgPgAgXgoQgTADgCAZQgBAXAMAGQANAGAMAAQAJAAAIgGQAIgHADgQQADgSgOgJQgKgHgNAAIgJAAgAmrA1QgIgBgEgGQgEgGABgLQACgWgCgkQgCgmAKgBQAKgBAFACQAFACABAKIgBAfIAUgBQAJAAAMAJQANAIAAAUQABAWgLAKQgFAFgHACQgGADgHAAIgIAAIgYgBgAmbgDQgEADgCADIgDAQQgCALATADQAZAAABgSQgBgNgHgCQgGgFgIAAQgJAAgDACgAlhAkIABgQIgCgiQAAgLgEgOQgHgXASgCQAUgHgHAYQgCAWAAAVIABAZIABASQABAKgFACIgPABIgBAAQgIAAAJgQg");
	this.shape.setTransform(55.6,7.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,111.3,15.6);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAZBIQgKgBgDgVQgCgWAAgcQAAgdADgVQACgUAOgBIAUgBIATACQANAAACAJQACAJAAAFQAAAGgFAEQgGAEgHAAIgZAAIgBAUQAXgDADAEQADADABAIQAAAFgBAHQgBAGgYACQAAAJABAFIAagCQAIgBAFAKQAEAKgEAJQgEAIgWADQgTADgLAAIgEgBgAEvBGQgFgBgBgHIABgFIgBgMQgCgHABgLQABgNgBgMQgBgKAAgZQgdAHgIgHIgCgNIACgIQAFgFAFAAQAEgBAMABIAcABIAZABIALAAQADAUgMgBIgSgBIgBAjQAAAUACAJIABAMIAAAJQAEAVgGAEIgIABQgFAAgFgCgAjDA/QgJgDgBgKQgBgKANgfQAMgdANgUQANgVAbAEQAQACAGATQAFASAGAhQAHAjgDAFQgDAFgGACQgGACgMAAQgMAAgBgbQgKgBgPABQgCAIgEAJQgEAIgKACIgIABQgGAAgFgCgAibABQAAAHAQgBQASAAgFgSQgBgMgJgEIgBAAQgKAAgIAcgACUAzQgRgSAAgbQgBgaAOgVQAPgWAWgDQAXgEAPAFQAQAEALAPQALAPABAZQAAAXgJAWQgJAWglADIgNABQgcAAgOgOgAC4gfQgTADgBAZQgCAWANAHQANAGALAAQAMAAAIgHQAHgGADgSQAEgRgPgJQgLgHgOAAIgJABgAhQA9QgCgCgBgEIgEhoQAAgEADgCQACgDADAAQAeAAAhAEQAKAAABAJQAAAFgCADQgCAEgHgBIgYAAQgRgBgFACQgBAEACAXIACAeIABAWQAAAOgKACIgGABQgEAAgCgCgAlNA7IgEAAQgJgCgBgGIgBgHIAAgeIAAgOIACgfQABgSALgCQAMgCAEAIQAFAHgEAlQgDAjAHAAQAHABAEgCQAFgBABgKQABgKABgRIAAgdQABgJADgDQAEgDAJgBQAJgBAAAPIgCA0QAAAQAFAAIARACQALABgDgpQgEgrAFgDQAFgCAFAAQAGABAEAFQAEAFACAyQACA0gPABg");
	this.shape.setTransform(35,7.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,69.9,14.6);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AGQBSQgFgDAAgIQgBgJAHgCQAGgCAGACQAGABACAFQACAFgBADQgBAEgDADQgDADgFABIgBAAQgEAAgFgDgAAtBUIgGAAIgHgBIACgcIABgZIABgQQgBgIAAgJIACghQgCgIAFAAIARABQAEAAgBAHQgEAGgBANIAAARIACAFIAXACQAdACgBgCQAGgLAAgPQgCgIACgIIASAAQAIgEAAADIgHAdQgCAGAAAIIAAAaQAAAJAEAJQADAJACALQAAAGgDABIgHADQgIACgKgDIgCgHIAAgPQAAgMgCgJQgCgIgvAGQgEAHgBANIgCAUQADAIgDABIgDAAIgEAAgAmcBUIgGAAIgHgBIACgcIABgZIABgQQgBgIAAgJIACghQgCgIAFAAIARABQAEAAgBAHQgEAGgBANIAAARIACAFIAXACQAdACgBgCQAGgLAAgPQgCgIACgIIASAAQAIgEAAADIgHAdQgCAGAAAIIAAAaQAAAJAEAJQADAJACALQAAAGgDABIgHADQgIACgKgDIgCgHIAAgPQAAgMgCgJQgCgIgvAGQgEAHgBANIgCAUQADAIgDABIgDAAIgEAAgACjBQQgIgDgBgKQgBgKAMgfQAMgdANgUQANgVAcAEQAPACAGATQAGASAGAhQAGAjgDAFQgCAFgHACQgGACgMAAQgMAAgBgbQgKgBgPABQgBAIgFAJQgEAIgKACIgHABQgGAAgGgCgADMASQgBAHARgBQARAAgFgUQAAgKgKgEIAAAAQgKAAgIAcgAkmBQQgIgDgBgKQgBgKAMgfQAMgdANgUQANgVAcAEQAPACAGATQAGASAGAhQAGAjgDAFQgCAFgHACQgGACgMAAQgMAAgBgbQgKgBgPABQgBAIgFAJQgEAIgKACIgHABQgGAAgGgCgAj9ASQgBAHARgBQARAAgFgUQAAgKgKgEIAAAAQgKAAgIAcgAh4BOQgBgCgBgLIABgWQgeAGgRgOQgRgNAAgRIgCgXQgBgJACgEQABgDAHgDQAGgDAHACQAHABAAAHQgBAHAAAIIABAPQABAHADAEQAEAEAIACQAJACAHgCQAGgBACgGQABgGACgUQABgWACgCQADgCADAAQADAAAGACQAHACAAAHIABAaQAAAQgCAgQgCAfgEADQgEADgJAAQgIAAgCgCgAETBMQgDgCABgaIABhFQABgSACgDQADgCAEgBQAEAAAIACQAHADgBAoIAAASQALgRAPgLQAOgNAKgLQAJgMAIABQAHABACAHQABAGAAAsQgBAtgDAIQgCAHgHACQgHABgEAAQgDgBgCgFQgCgFAEgtQgQANgTAWQgUAWgNABQgFAAgEgCgAhOBMQgDgCABgaIABhFQABgSACgDQADgCAEgBQAEAAAIACQAHADgBAoIAAASQALgRAPgLQAOgNAKgLQAHgMAIABQAHABACAHQABAGAAAsQgBAtgDAIQgCAHgHACQgHABgEAAQgBgBgCgFQgCgFAEgtQgQANgTAWQgUAWgNABQgFAAgEgCgAGKAjQgCgRgBgWQgBgXABgOQABgNASABQAQACgBAMIgHBTQAAAHgLABQgLAAgCgRgAE5guQgOgBgHgJQgIgJgBgKQgCgFAHgDQAHgCAFAHQAEAGAEACQAEACAJAAQAKAAAFgEQAEgEADAEIAGAGQADADgMAJQgLAIgOAAIgCAAg");
	this.shape.setTransform(42.6,8.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,85.2,17);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AjCCwQgJAAAAgDIgBgNIACgQQABgJANAAQAIgmAEghQACghAMAAIA4ABQAOAAADANQACANgCAUIgEA5QAGAAAAAGIAAAZQABAIgEABIgHABQgKAAgBgDQgCgEgBgPIhEABIgBAMQAAAJgDAAgAiaBCIgHAlQgFAXAUgCIAQAAQALAAACgDQACgEAAgMIABgiQABgRgXAAIgJgBIAAAAQgGAAgDANgAEaCmQgGgCgDgGQgEgHAFgJQAFgIALABQALABADAIQACAEAAADQAAAEgBADQgDAHgHABIgGABIgHgBgAg/CjQgLgBgCgVQgDgWAAgeQAAgdADgVQADgUANgBIAVgBIASACQANAAACAJQACAJAAAFQAAAGgFAEQgFAEgIAAIgZAAIgBAUQAXgDAEAEQADADAAAIQABAHgBAHQgCAGgXACQgBAJABAFIAbgCQAIgBAEAKQAEAKgEAJQgDAIgXADQgTACgLAAIgDAAgAC0CYQgIgBgEgGQgEgGABgLQACgWgCgmQgCgmAKgBQAKgBAFACQAFACABAKIgBAfIAUgBQAJAAAMAJQANAIAAAWQABAWgLAKQgFAFgHACQgGADgHAAIgIAAIgYgBgADEBeQgEADgCAFIgDAQQgCALATADQAZAAABgSQgBgNgHgEQgGgFgIAAQgJAAgDACgAkjCUQgCgGABgMIgBgfQgGgCgJAUQgKAVgBAHQgCAIgPgCQgDAAgEgCQgEgCACgHIAHgaQAGgTARgNQAAgEgIgOQgEgLgIgDQgIgBAAgLQAAgKAQABQAQAAAFAPQAFAPAKALQAAgMACgLQAAgMAJAAIALACQAGABgCAiQAMgJADgEQADgEAEgMQAEgMAJgBQAJgBAEADQAEACAAAIQAAAHgFABQgFAAgGAOIgJATQAOAMAHATQAIATgEAHQgEAHgGABQgHAAgDgJQgCgKgMgPQgMgQgEAAQgEAAgBAKIgBAWQAAALgBAGQgCAGgJAAQgJAAgBgFgAAiCWIgEAAQgJgCgBgGQgBgGAAgfQAAgeACgRQABgSALgCQAMgCAEAIQAFAHgEAlQgDAlAHAAQAHABAEgCQAFgBABgKQABgKABgTIAAgdQABgJADgDQAEgDAJgBQAJgBAAAPIgCA2QAAAQAFAAIARACQALABgDgrQgEgrAFgDQAFgCAFAAQAGABAEAFQAEAFACA0QACA0gPABgAETB/QgEgCAAgGQgBgHAHgLIANgXQAHgLgHgDQgHgDgFACQgGABgGAFQgGAFgFgJQgEgJAAgHQAAgHANgGQANgGARABQAQABAKAMQALAMgCAQQgBAQgLAJQgLAJgDAHIgGALQgCAEgIAAIgDAAQgFAAgEgBgAjjgdQgKgBgDgWQgCgWAAgdQAAgeADgUQACgUAOgBIAUgBIATABQANABACAIQACAJAAAGQAAAFgFAEQgGAEgHABIgZAAIgBAUQAXgDADADQADAEABAHQAAAIgBAGQgBAGgYACQAAAJABAGIAagDQAIAAAFAKQAEAKgEAIQgEAIgWADQgTADgLAAIgEAAgACtggQgFgBgBgHIABgFIgBgMQgCgHABgLQABgNgBgMQgBgMAAgZQgdAHgIgHIgCgNIACgIQAFgFAFAAQAEgBAMABIAcABQAQABAUAAQADAUgMgBIgSgBIgBAjQAAAWACAJIABAMIAAAJQAEAVgGAEIgIABQgFAAgFgCgAgbgzQgRgSgBgbQAAgcAOgVQAOgWAVgDQAWgEAQAFQAQAEALAPQALAPAAAZQAAAZgIAWQgJAWgmADIgNABQgZAAgOgOgAAHiHQgRADgCAZQgBAYAMAHQALAGAMAAQALAAAIgHQAIgGADgSQADgTgOgJQgLgHgOAAIgJABgAkZgoQgBgCgBgMIABgVQgeAGgRgOQgRgOAAgQIgCgaQgBgJACgDQABgEAHgDQAGgCAHABQAHABAAAHQgBAHAAAIIABAQQABAJADAEQAEAEAIACQAJABAHgBQAGgCACgFQABgGACgWQABgWACgCQADgDADAAQADAAAGADQAHACAAAHIABAZQAAASgCAgQgCAggEADQgEADgJAAQgIAAgCgCgAD+goQgIgBgEgGQgEgGABgLQACgWgCgnQgCgmAKgBQAKAAAFABQAFACABALIgBAfIAUgBQAJAAAMAIQANAJAAAWQABAWgLAJQgFAFgHADQgGACgHABIgIAAIgYgBgAEOhiQgEACgCAFIgDAQQgCAMATADQAZAAABgTQgBgMgHgFQgGgFgIAAQgJAAgDADgAiIgpQgCgCgBgEIgEhqQAAgEADgCQACgCADAAQAegBAhAFQAKAAABAIQAAAGgCADQgCADgHAAIgYgBQgRAAgFABQgBAFACAXIACAfIABAWQAAAPgKABIgGABQgEAAgCgCgAFIg5IABgRIgCgkQAAgKgEgOQgHgXASgCQAUgIgHAYQgCAXAAAVIABAbIABARQABALgFABIgPACIgBAAQgIAAAJgQg");
	this.shape.setTransform(13.5,16.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21.5,-1.5,69.9,35.4);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AiwBKQgJgBAAgDIgBgMIACgRQAAgIANAAQAJgkAEghQACghAMAAIA4AAQAOABACANQADAMgCAVIgEA2QAFAAAAAGIABAaQAAAHgEABIgHABQgJABgCgEQgBgDgBgQIhEABIgBANQAAAJgDAAgAiIgjIgIAjQgFAYAVgCIAQgBQAKABACgEQACgDABgNIABggQABgRgYAAIgJAAIAAAAQgFAAgDAMgABAA4IgHgCQgEgCAAgHIAXhXQADgSgEgEQADgHAOgCQAGAAAGADQAFAOADAVIAEARQAMgFAGgTIAGgMQgBgLAXAHIAJAeQAJAaADASIAEAeQAAAHgEAAIgIACIgHABQgDAAgFgYIgJggQgKgFgQAyQgDAGgGAAQgFAAgCgFIgEgJIgBgIQgGgdgIgMQgGAXgHAsQgEACgEAAIgFgBgAg1A0QgIgDgBgKQgBgKANgdQALgfANgVQANgVAaAFQAPACAGASQAGASAGAhQAGAkgCAFQgDAFgGACQgHACgLAAQgMgBgCgbQgJgBgNABQgCAIgFAJQgDAJgLACIgHABQgGAAgGgCgAgMgIQgBAHAPgCQARABgEgUQgBgNgJgDIgBAAQgIAAgIAeg");
	this.shape.setTransform(18.8,7.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,37.5,14.9);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#8842D3").s().p("AFCBEQgFgDAAgIQgBgJAHgCQAGgCAGACQAGABACAFQACAFgBADQgBAEgDADQgDADgFABIgBAAQgFAAgEgDgADNBCQgJgDgBgKQgBgKANgfQAMgdANgUQANgVAbAEQAQACAGATQAFASAGAhQAHAjgDAFQgDAFgGACQgGACgMAAQgMAAgBgbQgKgBgPABQgCAIgEAJQgEAIgKACIgIABQgGAAgFgCgAD1AEQAAAHAQgBQASAAgFgSQgBgMgJgEIgBAAQgKAAgIAcgAgJBCQgIgDgBgKQgBgKAMgfQAKgdANgUQANgVAcAEQAPACAGATQAGASAGAhQAGAjgDAFQgCAFgHACQgGACgMAAQgMAAgBgbQgKgBgPABQgBAIgFAJQgEAIgKACIgIABQgEAAgFgCgAAeAEQgBAHARgBQARAAgFgSQAAgMgKgEIgBAAQgKAAgHAcgAjzBCQgJgDgBgKIABgEIgDAEQgVAPgTAAQgSAAgNgLQgNgLgFgWQgGgXAOgbQANgcAXgJQAXgJAGACQAIAEAEAKQACAIgCAJIgEAGQgCADgPAFQgQAGgIAQQgJAOABAKQABAKALACQAKABAIgEIAMgIQAGgEAHAFQAHAEABAGIAIgVQAMgdANgUQANgVAbAEQAQACAGATQAFASAGAhQAHAjgDAFQgDAFgGACQgGACgMAAQgMAAgBgbQgKgBgPABQgCAIgEAJQgEAIgKACIgIABQgGAAgFgCgAjLAEQAAAHAQgBQASAAgFgSQgBgMgJgEIgBAAQgKAAgIAcgAh/BCQgGAAgBgEIgCgKQAAgGACgEQACgFAHACQAIABABgJQABgKgCgYIgBgiQAAgJADgFQADgEAKgCQALgDAbABQAcABADABQADACABAJIACAhQACAWgBAbQgBAcgPgBQgJABgEgGQgDgGAChRQgYgBgPABQACAagBAZQAAAbgHAJQgGAIgPAAIgFAAgABpBAQgDgCAAgEIgEhoQAAgEACgCQACgDAEAAQAdAAAiAEQAKAAAAAJQAAAFgCADQgCAEgGgBIgYAAQgRgBgFACQgBAEABAXIACAeIABAWQAAAOgJACIgHABQgEAAgBgCgAE8AVQgCgRgBgWQgBgXABgOQABgNASABQAQACgBAMIgHBTQAAAHgLABQgLAAgCgRg");
	this.shape.setTransform(34.7,7.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,69.5,14.3);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AlmCzIgHgCQgEgCAAgHIAWhZQAEgSgEgEQADgHANgCQAHAAAGADQAFAOACAVIAFARQAMgFAGgTIAGgMQgBgLAXAHIAJAeQAJAaADAUIAEAeQgBAHgEAAIgHACIgHABQgEAAgEgYIgJghQgKgGgQA0QgEAGgFAAQgFAAgCgFIgEgJIgCgIQgFgdgIgOQgGAZgIAsQgDABgEAAIgFAAgAEMCkQgPgPABgMQgLgCgWAAIgCAfQgCAJgIAAQgIABgEgCQgEgCACgJQAAhYACgHQACgHAGgCQAFgDAHABQAGABgBAJIAAAlQAUACAOgEQABgSAOgTQAOgUAbABQAcABAPAOQAQANgBAbQgBAcgQAXQgIAMgKAGQgLAHgOAAIgFAAQgXAAgOgNgAE3BLQgLADgJANQgJAMABAOQABAOAHAIQAHAHAOgDQAOgDAIgMQAJgLgDgPQgDgOgHgIQgGgFgIAAIgFAAgAAECmQgLgLgFgXQgGgWAOgdQALgdAXgJQAXgJAGADQAIADAEALQACAIgCAIIgEAHQgCACgPAGQgQAFgIARQgJAQABAKQABAKALABQAKACAIgFIAMgIQAGgDAHAEQAFADACAEIABhDQAAgSADgCQACgDAFAAQAEgBAHADQAHACgBAqIABASQALgQAOgNQAOgNAKgMQAKgMAHABQAHACACAGQACAHgBAtQgBAtgCAIQgDAIgHABQgGACgEgBQgEgBgCgFQgCgFAEgsQgPAMgUAWQgTAXgNAAQgGAAgDgCQgDgBAAgRIgEAJQgVAPgTAAIgBAAQgSAAgMgKgAhaCmQgNgLgFgXQgGgWAOgdQANgdAXgJQAXgJAGADQAIADAEALQACAIgCAIIgEAHQgCACgPAGQgQAFgIARQgJAQABAKQABAKALABQAKACAIgFIAMgIQAGgDAHAEQAHAFABAGQABAGgHANQgVAPgTAAIgBAAQgSAAgMgKgAjgCqQgDgCABgZIABhIQABgSACgCQADgDAEAAQAEgBAIADQAHACgBAqIAAASQALgQAPgNQAOgNAKgMQAJgMAIABQAHACACAGQABAHAAAtQgBAtgDAIQgCAIgHABQgHACgEgBQgDgBgCgFQgCgFAEgsQgQAMgTAWQgUAXgNAAQgFAAgEgCgACKAHQgJAAAAgDIgBgLIACgQQABgJANAAQAIgmAEghQACghAMAAIA4ABQAOAAADANQACANgCAUIgEA5QAGAAAAAGIAAAZQABAGgEABIgHABQgKAAgBgDQgCgEgBgNIhEABIgBAMQAAAHgDAAgACyhlIgHAlQgFAXAUgCIAQAAQALAAACgDQACgEAAgMIABgiQABgRgXAAIgJgBIAAAAQgGAAgDANgAhigaQgRgSgBgbIAAgBIAAABQgFALgLAGQgKAFgMACIgRABQAEAdgCABIgOABIgOgCIABgVQgCgQABgUQABgTgBgSQgBgSAHgHQAHgHAJAAIAHAAIALABQALACAPAJQANAIADATIACALQADgOAIgNQAOgVAXgEQAWgDAQAEQAQAFALAPQAJAPAAAZQAAAZgIAWQgHAVgmAEIgNAAQgbAAgOgOgAg+huQgTADgCAZQgBAZAMAGQANAGAMAAQALAAAIgGQAIgHADgSQADgSgOgJQgLgIgOAAIgJABgAiuhuQgCAPADARQADAQAVgFQAUgFAAgSQgBgRgGgIQgHgIgPgBIgBAAQgNAAgCAOgAEBgRQgEgCACgaIABhHQAAgSADgDQACgCAFgBQAEAAAHACQAHADgBAqIABASQALgRAOgNQAOgNAKgLQAKgMAHABQAHABACAHQACAGgBAuQgBAtgCAIQgDAHgHACQgGABgEAAQgEgBgCgFQgCgFAEgtQgPANgUAWQgTAWgNABQgGAAgDgCgAAOgRQgEgCACgaIABhHQAAgSADgDQACgCAFgBQAEAAAHACQAHADgBAqIABASQALgRAOgNQAOgNAKgLQAKgMAHABQAHABACAHQACAGgBAuQgBAtgCAIQgDAHgHACQgGABgEAAQgEgBgCgFQgCgFAEgtQgPANgUAWQgTAWgNABQgGAAgDgCgAlCgXIgBgLIABhQIgJAAQgMgBgBgGQgBgHACgGQABgGALgBQALgCATABIBQAEQADAAADACQACACABAGQAAAFgEAFQgFAFgDAAQgDgBADAVQACAfgBAWQgBAHgEACQgEACgGgBQgHgBAAgHIAAgYIgEgzQglABgIACIgDBNQgBAIgDACIgMADIgEAAQgFAAAAgDgAA0iNQgPgBgHgJQgHgJgCgKQgBgFAHgDQAHgCAEAHQAEAGAEACQAEACAKAAQAJAAAFgEQAFgEADAEIAGAGQADADgNAJQgLAIgNAAIgCAAg");
	this.shape.setTransform(37.1,18);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,74.1,36);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgrAyQgEgFAAgEIAFgIIAFgHQAGgFAFAIQAFAHAGABIAMABQAEgBAIgGQAIgIABgKQAAgMgMgGQgJgHgNAJQgMAGgLABIgCgTQAAgNADgQIADgTQACgEAJAAIAUABIAYADQAPABgCASQgCAHgRgGIgWgBIgKACQgHAEADALQAtgIAKAUQAIAKgBAQQgBAVgKARQgIAPgbAEQgWgEgPgOgAiBA6QgEgCgCgDIgEgEQgCgBABgEQABgEAFgIQAGgIAPgLQgGgNgFgGIgKgMQgCgHADgCQADgDAJgDQAHgCAJATIAKAMIAYgVQAGgGAHAIQAGAHgFAJIgXAVIALAPQAKANAAAHQgEAHgFACQgFABgDgCQgJgIgNgUQgPAQgGAIQgEAFgEAAIgCAAgAA+ArQgOgRgBgeQABgZALgVQAPgUAbAFQAXAJAJALQAJAMAAAXQgBAfgHARQgHARgdACQgUgBgQgNgABOgdQgHAIgBAQQgEAYAHAHQAIAHAIACQAVAJAIgUQADgNABgRQAAgVgHgGQgIgFgLAAIgDAAQgKAAgFAJg");
	this.shape.setTransform(14.2,6.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,28.5,13.7);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AidA+QgFgCgCgCIgEgFQgCgBABgEQABgEAGgIQAFgIAQgLQgGgNgGgFIgKgNQgBgGACgDQADgDAJgCQAIgDAIATIAKAMIAYgVQAGgFAHAHQAHAIgGAIIgWAVIAKAQQALAMgBAHQgDAHgGACQgFABgDgCQgIgHgOgUQgPAPgGAIQgDAGgEAAIgCgBgABbAvQgPgRgBgeQACgYALgWQAPgUAbAFQAWAJAKAMQAJAMgBAWQgBAggHARQgGAQgeACQgTgBgQgNgABqgZQgGAJgCAPQgEAYAIAHQAIAIAHABQAWAJAHgUQAEgNABgRQAAgVgIgFQgHgFgMgBIgCAAQgKAAgGAJgAgJAvQgOgRgBgeQABgYALgWQANgUAbAFQAXAJAJAMQAJAMAAAWQgBAggHARQgHAQgdACQgUgBgOgNgAAFgZQgFAJgBAPQgEAYAFAHQAIAIAIABQAVAJAIgUQADgNABgRQAAgVgHgFQgIgFgLgBIgDAAQgKAAgFAJgAg5A5IADg5QAAgRgBgLQgHAHgHABQgEgBgBgFIgDgIQgBgEAHgFIAcgTQAGgBADAWQAEAWgCAYIgCAqIgCALQgFACgFAAQgFAAgGgDg");
	this.shape.setTransform(17.1,6.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,34.2,12.7);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.fuel_64x64();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,64,64);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.gold_64x64();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,64,64);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.money_64x64();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,64,64);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEA02").s().p("AlZFaQiPiQgBjKQABjKCPiPQCPiPDKgBQDKABCQCPQCQCPAADKQAADKiQCQQiQCQjKAAQjKAAiPiQg");
	this.shape.setTransform(49,49);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,98,98);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.arrow();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,25,24);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AihAmQgBgRAEgCQADgCAEgBIAKguQACgMAEgDQADgEAXAAQAXAAACAFQADAFAAASQAAARgCATQAPgBAAAMQAAANgBAEQAAAFgEABQgDABgHgBQgGAAABgIIAAgHQguAAgEACQABARgGABIgMAAQgGAAAAgQgAiAgOIgDAYQgBAGATAAQASAAgBgQIgBgZQAAgIgOAAIgBgBQgOAAgCAUgAlaAmQgJAGgGAAQgHAAgJgDQgKgDgJgJQgJgKABgTQABgTANgNQANgOASAAQAHAAAIAEQAGACADAEQADAEAAAEIABAKQABAGAAAKQgBAJABAGIADALQABAFADAFQAAAEgCABIgGAFQgDABgCAAQgGAAgEgHgAlsgaQgMAFgDAFQgDAGgCAKQgBANAIAFQAIAFAPgEQAEgEABgFIADgTIgBgJQgBgDgEgDQgDgCgFAAIgEAAgAkyArQgPgCAAgEIgBhIQABgHACgBQABgCAGgBQAGgBALAAQALAAAMAIQAMAHAAALQAAAMgFAEIAHAIQAEAGgBAMQAAAGgFAEQgEAFgJADQgPAEgMAAIgGAAgAkvADIgCANQgBAMASgFQASgEgDgIQgEgIgHgBIgMgCQgGAAgBADgAkugfQgBAAAAABQAAAAAAABQAAAAAAABQAAABAAABIAAAGQAAAAAAABQAAABABAAQAAABAAAAQABABAAAAQACABAFAAQAFAAAEgCQAEgCAAgEQgBgEgEgDQgEgCgGAAQgFAAgBABgAjsAeQgKgLgDgSQABgSAKgPQAKgOAUgBQAQgCAIAHQAMAGADARQABAJgHAFQgfATgQgHQgBALARADQAIAAAHgDIAKgJQAEgDAEABIAFAFIACAFQAEAFgUAMQgNAFgMAAQgUAAgJgJgAjMgcQgOAEgHAJQgHAIAaAAQAagHgFgJQgFgGgHAAIgHABgAg4AkIgCgEIgCgzQgBgdAMABQAMAAABAFQACAIgBALIAAARIAlgjQAHgFAFAAQAEgBADACQADABABAHIAAAZIAAAcQAAAMgEABQgDACgFAAQgGAAgBgDIgBgHIgBgVQgSAMgIAJIgNAMQgFAFgHAAQgGAAgDgCgAGTAmIhTgCQgDAAgDgCQgDgCABgTIABggQABgPADgEQACgDAJAAQAIAAgBALIACApIARAAIABgfQAAgWAFgBQAFgBAFAAQAEABACADQACADgBAxIAWgBIgBgtQgBgNAIAAQAHAAADACQAEACgCBHQABAKgOAAIgBAAgABbAlQgMAAACgIIAIgdIAJgeQACgKADgDQADgEAGgBQAGgBAEADQAFADAKAeQALgWAEgGQAEgGAJAAQAIAAAEAIQADAHADAOIAIAcQAEASgEADQgFADgGABQgHgEgDgLIgHgVIgNAYQgDAEgEACQgEACgFAAQgFAAgCgDIgGgOQgEgLgEgFIgLAhQgDAGgHAAIgBAAgAEfAkQgCgBgBgDQgCgDAAgHQgCgMABgOIABgaQAAgJACgDQACgDAHgBQAIAAAAAOIACA1QAAAOgFABIgEAAIgHAAgAGsANQgBgVABgMIADgUQACgHAGAAQAOABgBAHIgBAVQAagFAJAJQAJAJAAAPQgBAQgLAFQgKAFgWAAQgWAAgBgXgAHCAAIgCAKQAAAHAKABQARAAAAgLQAAgHgEAAQgEgCgJAAIgFAAQgBAAAAAAQgBAAAAAAQAAABgBABQAAAAAAAAgADTAjQgGAAgBgFQgBgGAAgbQgBgcACgIQABgIAIAAQAMABAAAHIABAVQAUgCALAGQALAHABAOQAAAQgKAGQgLAGgPABIgJAAIgNgBgADqgEQgKABgBADIgBAMQgBAKAKgBQAVAAgCgLQgBgKgDgCQgDgDgFAAIgEABgAntAZQgBgJABgZIAAggQAAgGAEgCQAEgCAFAAQAEABADACQAEADgBAVQAQAFARgFQAAgYAEgCQAEgDAFAAQAEABAFAEQAEAEgBARIgBAfQgBAPgCAHQgCAGgFAAIgJgCQgDgBgBgCIgBgZQgSAAgNADIgDAUQAAAIgKAAQgLAAgBgIg");
	this.shape.setTransform(49.5,5.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,99,10.9);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEB3B").s().p("ArlCSIgPgFQgIgDAAgPIAvi2QAHgjgJgKQAIgPAbgCQAOgBALAHQALAcAFArIAKAkQAZgLAMgnIALgYQAAgXAuAPIAUA+QARAyAHAqIAIA9QgBAPgJABQgIABgHADIgOABQgHAAgIgxIgVhFQgTgLgiBqQgHAMgMAAQgJAAgGgKIgLgjQgKg8gQgbQgMAzgRBZQgIAEgIAAQgFAAgFgBgAIrBzQgggfACgZQgWgCgugBIgDBAQgFASgQABQgRAAgHgDQgIgEADgSQABi1AEgOQAEgPALgEQAMgFANACQANACgBATQgBASABA5QAnAFAegIQADglAcgoQAdgpA4ADQA4ABAhAcQAhAcgDA4QgDA3ggAwQgQAZgWAMQgWANgcACIgLAAQgxAAgbgcgAKDhCQgXAFgSAbQgTAaACAbQACAdAPAPQAPAPAdgGQAcgFASgZQARgZgGgbQgGgegPgPQgMgMgRAAIgKABgAAJB3QgZgXgLguQgKgvAbg5QAZg7AvgTQAvgTAOAGQARAHAHAWQAFAQgEASQgDAHgFAGQgFAFgfAMQggALgSAiQgSAfACAVQACAUAWADQAWAEAQgKIAagQQAKgHAQAJQAKAGAEAIIADiIQAAglAFgFQAGgFAJgBQAIgBAPAFQAPAFgCBXIAAAiQAYgfAdgbQAdgbAVgYQAUgZAPADQAPACAEAOQADAOgCBdQgCBcgFAQQgFAQgOACQgOADgIgBQgIgCgDgKQgEgKAIhcQggAZgoAuQgoAugbABQgLABgIgFQgGgDABgjIgJATQgsAfgmABIgCAAQgkAAgbgWgAi8B3QgbgXgKguQgLgvAbg5QAcg7AvgTQAvgTANAGQARAHAHAWQAFAQgEASQgCAHgFAGQgFAFggAMQggALgSAiQgSAfACAVQACAUAXADQAWAEAPgKIAagQQALgHAPAJQAPAJACAMQACANgOAbQgtAfgmABIgCAAQgkAAgbgWgAnPCAQgIgEADg1IADiRQAAglAGgFQAFgFAJgBQAJgBAPAFQAPAFgCBXIAAAiQAYgfAdgbQAdgbAUgYQAUgZAPADQAPACAEAOQAEAOgCBdQgCBcgFAQQgGAQgOACQgNADgIgBQgIgCgEgKQgDgKAIhcQghAZgoAuQgoAugbABIgEAAQgIAAgGgEg");
	this.shape.setTransform(76.5,54.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AENDBQgSgBgBgHIAAgZQAAgSACgRQADgRAaAAQAShOAHhCQAGhEAYAAIB0ABQAcABAGAaQAFAbgEAqIgJByQAMAAAAANIABA0QAAAQgIACQgIACgGAAQgTABgEgHQgDgIgDgfQhsADgfgBIgCAZQgBATgFAAgAFhghIgQBKQgKAxApgEIAhgBQAXABAEgHQAEgIABgZIAChFQABgjgvAAIgTgBIgBAAQgKAAgGAagAjcB4QgjgkgBg4IAAgFIgCAEQgKAWgWANQgVAMgYADIgjADQAHA8gEABQgDABgZAAIgegDIACgrQgCgiACgpQABgmgCglQgCgkAOgPQAPgOASAAIAPAAIAWACQAYAEAdASQAbASAHAmIADAYQAHgeARgaQAdgtAvgHQAugHAhAKQAgAJAXAfQAVAfABAxQAAA0gQAtQgSAshOAIIgZACQg6AAgdgfgAiRgzQgnAHgEAxQgDAzAaANQAaANAYAAQAYgBAQgNQAQgOAHglQAGgjgegTQgXgPgcAAIgSABgAl5gzQgEAfAGAgQAHAiAqgKQArgLgBgiQgBglgOgPQgOgQgegCIgFAAQgZAAgEAcgAIDCKQgIgEADg1IADiRQAAglAGgFQAFgFAJgBQAJgBAPAFQAPAFgCBXIAAAiQAYgfAdgbQAdgbAUgYQAUgZAPADQAPACAEAOQAEAOgCBbQgCBegFAQQgGAQgOACQgNADgIgBQgIgCgEgKQgDgKAIhcQghAZgoAuQgoAugbABIgEAAQgIAAgGgEgAANCKQgHgEADg1IADiRQAAglAFgFQAGgFAJgBQAIgBAPAFQAPAFgCBXIAAAiQAYgfAdgbQAdgbAVgYQAUgZAPADQAPACAEAOQADAOgCBbQgCBegFAQQgFAQgOACQgOADgIgBQgIgCgDgKQgEgKAIhcQggAZgoAuQgoAugbABIgEAAQgJAAgGgEgAqrB/QgBgIABgPIADhOIgDhWQgqADgCgQQgCgQADgLQACgMAXgEQAWgDAoACIClAHQAHAAAFAFQAEAEACAMQABALgJALQgKAKgGgBQgGgBAGAqQADA/gBAuQgCAOgIAEQgIADgNgBQgOgCAAgPIgBgyIgIhlQhLACgRACIgHCdQgBARgGAEQgGADgTADIgIABQgLAAgBgGgABbh0QgdgBgPgSQgPgSgEgVQgCgLAOgFQAPgGAIAOQAJAOAIAEQAIADAUAAQAUAAAKgIQAKgJAFAIIANANQAGAHgaASQgXAQgcAAIgEAAg");
	this.shape_1.setTransform(73,19.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,153.1,69.7);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AA/g7QAFgGhuBAQhwA+ACAAQEvhWACAAQACAAhcgig");
	this.shape.setTransform(10.4,77.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgqgBQBuhAgFAGIBaAiIkxBWQgCAABwg+g");
	this.shape_1.setTransform(10.4,77.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Слой 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ao4E6QjsiCAAi4QAAi3DsiDQDsiBFMgBQFNABDsCBQDrCDABC3QgBC4jrCCQjsCDlNAAQlMAAjsiDg");
	this.shape_2.setTransform(80.5,44.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.9,0,167,89);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABRCEIgEgYQgDgOAKgGQAKgHATgCQATgDARgYQgSgngWghQgXgjgEgMQgEgMAIgJQAJgIAPgDQAOgDANANQANANAbAxQAYg/ANgQQANgQALACQAMACAQAOQAQANgbA4Ig7ByQgfA7gpACIgKAAQgfAAgCgIgAmHBrQgjglgBg4QgBg2AdgtQAdgsAvgHQAugHAhAJQAgAJAXAfQAXAfABA0QAAAygSAsQgSAthOAIIgZABQg6AAgdgegAk8hAQgnAGgEAzQgDAyAaAMQAaANAYAAQAYAAAQgOQAQgNAHglQAGgkgegTQgXgPgdAAIgRACgAGsCCQgDgEgBgXIABgtQg/AMgjgdQgjgcAAggQAAgigCgSQgDgSADgIQADgHANgGQAOgGAPADQAPADgCAOQgCAPABAQIACAhQACARAHAJQAGAGASAEQASADAOgDQAOgDADgKQADgMADgtQADguAFgEQAEgEAHAAQAHAAANAEQAMAEACAPQABAOAAAmQAAAmgEA/QgFBBgIAHQgIAGgSAAQgRAAgDgEgAiTCEQgNAAgCgGIgDgVQgBgNAEgJQAEgJAQADQARADABgTQABgUgDg0QgDg2ABgRQAAgRAGgKQAGgKAVgEQAWgFA5ACQA2ACAHADQAHACAAAUIAFBEQAFAugDA5QgDA5gdgBQgUABgHgMQgEgLADiqQgygCgdACQAEA1gCA1QgCA4gNATQgMAQgdAAIgNgBgAIDB9QgIgFADg0IADiSQAAglAGgEQAFgFAJgCQAJgBAPAFQAPAGgCBWIAAAjQAYggAdgbQAdgaAUgZQAUgYAPACQAPADAEAOQAEANgCBeQgCBbgFAQQgGAQgOADQgNADgIgCQgIgCgEgJQgDgLAIhcQghAagoAuQgoAugbAAIgEABQgIAAgGgEgAqqByQgCgJABgPIADgxIgDhyQgqACgBgPQgCgQACgMQADgMAWgDQAXgDAoACIClAHQAHAAAEAEQAFAFABALQACAMgKAKQgKALgFgBQgGgBAFAqQAEA+gBAvQgCANgJAEQgIAEgNgCQgNgBAAgQIgCgyIgHhlQhMACgRADIgGCdQgCAQgGAEQgGADgSAEIgJABQgKAAgBgGg");
	this.shape.setTransform(79.9,14.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFEB3B").s().p("Aj7CgQgSgBgBgHIAAgZQAAgSACgRQADgRAaAAQAShMAHhEQAGhEAYAAIB0ABQAcABAGAaQAFAbgEAqIgJByQAMAAAAANIABA0QAAAQgIACQgIACgGAAQgTABgEgHQgDgIgDgfQhsADgfgBIgCAZQgBATgFAAgAinhCIgQBKQgKAxApgEIAhgBQAXABAEgHQAEgIABgZIAChFQABgjgvAAIgTgBIgBAAQgKAAgGAagAAEByQgRgGgBgVQgCgUAXhAQAZg+AbgrQAbgqA5AJQAfAEAMAmQAMAlANBHQAMBIgFALQgGAKgNAFQgNAEgYgBQgZAAgCg5QgVgBgfACQgDAQgJASQgJATgUAEIgPABQgMAAgLgEgABWgMQgBANAjgBQAkAAgLgpQgBgZgTgHIgCAAQgVAAgQA9gAGxBXQgjgkgBg2IAAgFIgCAEQgKAUgWANQgVAMgYADIgjADQAHA8gEABQgDABgZAAIgegDIACgrQgCgiACgnQABgogCglQgCgkAOgPQAPgOASAAIAPAAIAWACQAYAEAdASQAbASAHAmIADAYQAHgeARgaQAdgtAvgHQAugHAhAKQAgAJAXAfQAXAfABAzQAAAygSAtQgSAshOAIIgZACQg6AAgdgfgAH8hUQgnAHgEAzQgDAxAaANQAaANAYAAQAYgBAQgNQAQgOAHgjQAGglgegTQgXgPgcAAIgSABgAEUhUQgEAfAGAiQAHAgAqgKQArgJgBgkQgBglgOgPQgOgQgegCIgEAAQgaAAgEAcgAnwBXQgjgkgBg2QgBg5AegsQAdgtAugHQAvgHAgAKQAhAJAXAfQAXAfAAAzQAAAygSAtQgRAshOAIIgZACQg7AAgdgfgAmlhUQgnAHgDAzQgEAxAbANQAaANAYAAQAYgBAQgNQAPgOAHgjQAGglgegTQgXgPgcAAIgSABgAKvBsQgXABABg4QABg1gChFQgDhFAXACQAYABAGAIQAHAJgCA6QAYgQAWggQAWggAQADQAQACAFAPQAFAPgDANQgEAMgTAVQgTAVgOAXIApApQAUAVABATQABATgKAJQgKAJgRABQgSAAgLgWQgMgXgRgPQgRgQgBASQAAAsgBAKQgBAIgUAAIgLAAgAsTBeQgBgIABgPIACgyIgChyQgqADgCgQQgCgQADgLQACgMAXgEQAWgDAoACIClAHQAHAAAFAFQAEAEACAMQABALgJALQgKAKgGgBQgGgBAGAqQADA/gBAuQgCAOgIAEQgIADgNgBQgOgCAAgPIgBgyIgIhlQhLACgRACIgHCdQgBARgGAEQgGADgTADIgIABQgLAAgBgGg");
	this.shape_1.setTransform(83.3,50.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,166.6,66.6);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.logo();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,139,90);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.upir_05();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,121,142);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.upir_08();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,91,113);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.upir_13();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,242,131);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.upir_16();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,120,62);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.upir_02();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,307,623);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.clode();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,215,112);


(lib.Символ73 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ74();
	this.instance.setTransform(368.9,199,1,1,0,0,0,368.9,199);
	this.instance.alpha = 0.488;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,738,398);


(lib.Символ70 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ71();
	this.instance.setTransform(17.3,17.3,1,1,0,0,0,17.3,17.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:107.3},9,cjs.Ease.get(1)).wait(5).to({x:186.3},9,cjs.Ease.get(1)).wait(7).to({x:17.3},9,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,34.6,34.7);


(lib.Символ67 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ65();
	this.instance.setTransform(39.1,39.1,1,1,0,0,0,39.1,39.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,78.2,78.2);


(lib.Символ62 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ69();
	this.instance.setTransform(34.2,34.2,1,1,0,0,0,34.2,34.2);

	this.instance_1 = new lib.Символ68();
	this.instance_1.setTransform(34.2,34.2,1.09,1.09,0,0,0,34.2,34.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,68.5,68.5);


(lib.Символ61 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ66();
	this.instance.setTransform(39.1,39.1,1,1,0,0,0,39.1,39.1);

	this.instance_1 = new lib.Символ67();
	this.instance_1.setTransform(39.1,39.1,1.12,1.12,0,0,0,39.1,39.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,78.2,78.2);


(lib.Символ60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ64();
	this.instance.setTransform(38.1,40.1,1,1,0,0,0,38.1,40.1);

	this.instance_1 = new lib.Символ63();
	this.instance_1.setTransform(38.1,40.1,1.14,1.14,0,0,0,38.1,40.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,76.3,80.2);


(lib.Символ56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 3
	this.instance = new lib.Символ62();
	this.instance.setTransform(195.1,46.5,0.88,0.88,0,0,0,34.2,34.2);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// 2
	this.instance_1 = new lib.Символ61();
	this.instance_1.setTransform(112.4,46.5,0.88,0.88,0,0,0,39.1,39.1);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// 1
	this.instance_2 = new lib.Символ60();
	this.instance_2.setTransform(29.7,46.5,0.88,0.88,0,0,0,38.1,40.1);
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 4
	this.instance_3 = new lib.Символ70();
	this.instance_3.setTransform(23.1,123,1,1,0,0,0,17.3,17.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8.6,6.3,236.6,134.1);


(lib.Символ55 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 1
	this.instance = new lib.Символ56();
	this.instance.setTransform(40.6,55.7,1,1,0,0,0,40.6,42.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:33.6,y:63.7,alpha:1},3,cjs.Ease.get(1)).wait(1).to({x:40.6,y:55.7,alpha:0},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.9,24.2,229.2,129.1);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ72();
	this.instance.setTransform(9.8,13.2,1,1,0,0,0,48.8,35);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:2,x:9.7},7,cjs.Ease.get(0.86)).to({rotation:0,x:9.8},7,cjs.Ease.get(0.86)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39,-21.8,97.5,70.1);


(lib.Символ52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ53();
	this.instance.setTransform(22.6,17.2,1,1,0,0,0,22.6,17.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.1,scaleY:1.1},9,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39,-21.8,97.5,70.1);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ51();
	this.instance.setTransform(-12.9,27.2,1.25,1.25,0,0,0,39.1,18.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.8,4.5,97.9,45.7);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ49();
	this.instance.setTransform(0.4,32.9,1,1,0,0,0,40.1,7.8);

	this.instance_1 = new lib.Символ48();
	this.instance_1.setTransform(0.4,-7.3,1,1,0,0,0,55.6,7.8);

	this.instance_2 = new lib.Символ47();
	this.instance_2.setTransform(0.4,12.4,1,1,0,0,0,35,7.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.2,-15.1,111.3,55.8);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 2
	this.instance = new lib.Символ50();
	this.instance.setTransform(50.4,-10.9,1,1,0,0,0,39.1,18.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(49).to({_off:false},0).to({y:-0.9,alpha:1},5,cjs.Ease.get(1)).wait(15).to({y:9.1,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// 1
	this.instance_1 = new lib.Символ46();
	this.instance_1.setTransform(77.9,7.7,1,1,0,0,0,77.9,17.7);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:17.7,alpha:1},4,cjs.Ease.get(1)).wait(40).to({y:27.7,alpha:0},5,cjs.Ease.get(0.71)).to({_off:true},1).wait(25));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.2,-25.1,111.3,55.8);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.instance = new lib.Символ45();
	this.instance.setTransform(168,52.5,1,1,0,0,0,77.9,17.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ54();
	this.instance_1.setTransform(83.7,45.5,1,1,0,0,0,82.7,44.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.5,1,166.5,89);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ43();
	this.instance.setTransform(82.7,44.5,1,1,0,0,0,82.7,44.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:86.7},9,cjs.Ease.get(0.99)).to({x:82.7},10,cjs.Ease.get(0.99)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.5,1,166.5,89);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ41();
	this.instance.setTransform(82.7,44.5,1,1,0,0,0,82.7,44.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:48.5},4,cjs.Ease.get(0.85)).to({y:44.5},5,cjs.Ease.get(0.85)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.5,1,166.5,89);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ36();
	this.instance.setTransform(42.8,7.4,1,1,0,0,0,18.8,7.4);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#8842D3").s().p("AiOBOQgIAAgBgDIAAgNIABgQQABgJANAAQAJglADggQADghAMAAIA4ABQAOAAACANQADANgCAUIgFA3QAGAAAAAGIABAZQAAAIgEABIgHABQgJAAgCgDQgBgEgCgPIhDABIgBAMQAAAJgDAAgAhlgeIgIAjQgFAXAUgCIAQAAQALAAACgDQACgEABgMIABggQAAgRgXAAIgJgBIAAAAQgFAAgDANgAGPA6QgFgDgBgIQAAgJAGgCQAGgCAHACQAGABACAFQABAFgBADQgBAEgDADQgCADgFABIgBAAQgFAAgEgDgAgSA4QgIgDgBgKQgBgKAMgfQAMgdALgUQANgVAcAEQAPACAGATQAGASAGAhQAGAjgDAFQgCAFgHACQgGACgMAAQgMAAgBgbQgKgBgPABQgBAIgFAJQgEAIgJACIgGABQgGAAgGgCgAAVgEQgBAFARgBQARAAgFgSQAAgMgKgEIAAAAQgKAAgIAegAC9ArQgRgSgBgZIAAgBIAAABQgFAJgLAGQgKAFgMACIgRABQAEAdgCABIgOABIgOgCIABgVQgCgQABgSQABgTgBgSQgBgSAHgHQAHgHAJAAIAHAAIALABQALACAPAJQANAIADATIACALQADgOAIgNQAOgVAXgEQAWgDAQAEQAQAFALAPQALAPAAAZQAAAXgIAWQgJAVgmAEIgNABQgbAAgOgPgADhgnQgTADgCAZQgBAXAMAGQANAGAMAAQALAAAIgGQAIgHADgQQADgSgOgJQgLgHgOAAIgJAAgABxgnQgCAPADARQADAOAVgFQAUgDAAgSQgBgRgGgIQgHgIgPgBIgBAAQgNAAgCAOgAkEArQgRgSgBgZQAAgbAOgWQAOgVAXgEQAWgDAQAEQAQAFALAPQALAPAAAZQAAAXgIAWQgJAVgmAEIgNABQgbAAgOgPgAjggnQgTADgCAZQgBAXAMAGQANAGAMAAQALAAAIgGQAIgHADgQQADgSgOgJQgLgHgOAAIgJAAgAE4A1QgLAAAAgaIAAg7QgCghALABQAMAAADAEQADAFgBAcQAMgIALgQQAKgPAIABQAIABACAIQADAHgCAGQgCAGgJAKQgJALgHAKIAUATQAKAKAAAKQABAJgFAEQgFAFgJAAQgIAAgGgLQgFgLgIgHQgJgIAAAJIgBAaQAAAEgKAAIgFAAgAmRAuIgBgLIABhOQgVABgBgIQgBgHACgGQABgGALgBQALgCATABIBQAEQADAAADACQACACABAGQAAAFgEAFQgFAFgDAAQgDgBADAVQACAdgBAWQgBAHgEACQgEACgGgBQgHgBAAgHIAAgYIgEgxQglABgIACIgDBLQgBAIgDACIgMADIgEAAQgFAAAAgDgAGJALQgCgPgBgYQgBgXABgOQAAgNATABQAPACAAAMIgIBTQAAAHgKABQgMAAgBgRg");
	this.shape.setTransform(42.5,26.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,84.9,34.3);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ37();
	this.instance.setTransform(42.6,17.2,1,1,0,0,0,42.5,17.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:42.4,scaleX:0.89,scaleY:0.89,x:42.5},13,cjs.Ease.get(1)).to({regX:42.5,scaleX:1,scaleY:1,x:42.6},6,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,84.9,34.3);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 5
	this.instance = new lib.Символ39();
	this.instance.setTransform(52,32.4,1.1,1.1,0,0,0,42.6,8.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(139).to({_off:false},0).to({y:37.4,alpha:1},5,cjs.Ease.get(1)).wait(15).to({y:42.4,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// 4
	this.instance_1 = new lib.Символ38();
	this.instance_1.setTransform(75.2,34.5,1,1,0,0,0,35,17.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(104).to({_off:false},0).to({y:39.5,alpha:1},5,cjs.Ease.get(1)).wait(25).to({y:44.5,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(25));

	// 3
	this.instance_2 = new lib.Символ35();
	this.instance_2.setTransform(52.8,25.5,1.18,1.18,0,0,0,42.5,17.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(69).to({_off:false},0).to({y:35.5,alpha:1},5,cjs.Ease.get(1)).wait(25).to({y:40.5,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(60));

	// 2
	this.instance_3 = new lib.Символ34();
	this.instance_3.setTransform(52.4,27.5,1.45,1.45,0,0,0,34.8,7.2);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(39).to({_off:false},0).to({y:37.5,alpha:1},5,cjs.Ease.get(1)).wait(20).to({y:47.5,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(95));

	// 1
	this.instance_4 = new lib.Символ31();
	this.instance_4.setTransform(50.6,32.5,1,1,0,0,0,37.1,18);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({y:37.5,alpha:1},4,cjs.Ease.get(1)).wait(30).to({y:42.5,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(125));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(13.5,14.5,74.1,36);


(lib.Символ24_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// money_64x64.png
	this.instance_1 = new lib.Символ25();
	this.instance_1.setTransform(32,29,1,1,0,0,0,32,32);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:-68},9,cjs.Ease.get(1)).to({x:-58},5,cjs.Ease.get(1)).wait(25).to({x:-48},5,cjs.Ease.get(1)).to({x:-148},5,cjs.Ease.get(1)).to({_off:true},1).wait(95));

	// gold_64x64.png
	this.instance_2 = new lib.Символ26();
	this.instance_2.setTransform(32.7,24,1,1,0,0,0,32,32);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(100).to({_off:false},0).to({x:-67.3},9,cjs.Ease.get(1)).to({x:-57.3},5,cjs.Ease.get(1)).wait(20).to({x:-47.3},5,cjs.Ease.get(1)).to({x:-142.3},5,cjs.Ease.get(1)).wait(1));

	// fuel_64x64.png
	this.instance_3 = new lib.Символ27();
	this.instance_3.setTransform(31.5,28,1,1,0,0,0,32,32);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(50).to({_off:false},0).to({x:-68.5},9,cjs.Ease.get(1)).to({x:-58.5},5,cjs.Ease.get(1)).wait(25).to({x:-48.5},5,cjs.Ease.get(1)).to({x:-158.5},5,cjs.Ease.get(1)).to({_off:true},1).wait(45));

	// 50
	this.instance_4 = new lib.Символ29();
	this.instance_4.setTransform(32.7,70.3,1,1,0,0,0,14.2,6.9);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(100).to({_off:false},0).to({x:-67.3},9,cjs.Ease.get(1)).to({x:-57.3},5,cjs.Ease.get(1)).wait(20).to({x:-47.3},5,cjs.Ease.get(1)).to({x:-142.3},5,cjs.Ease.get(1)).wait(1));

	// 100
	this.instance_5 = new lib.Символ28();
	this.instance_5.setTransform(32,69.7,1,1,0,0,0,17.1,6.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({x:-68},9,cjs.Ease.get(1)).to({x:-58},5,cjs.Ease.get(1)).wait(25).to({x:-48},5,cjs.Ease.get(1)).to({x:-148},5,cjs.Ease.get(1)).wait(1).to({x:31.5},0).to({x:-68.5},9,cjs.Ease.get(1)).to({x:-58.5},5,cjs.Ease.get(1)).wait(25).to({x:-48.5},5,cjs.Ease.get(1)).to({x:-158.5},5,cjs.Ease.get(1)).to({_off:true},1).wait(45));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-3,64,79.1);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// m (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AlZFaQiPiQgBjKQABjKCPiPQCPiPDKgBQDKABCQCPQCQCPAADKQAADKiQCQQiQCQjKAAQjKAAiPiQg");
	mask.setTransform(49,49);

	// priz
	this.instance = new lib.Символ24_1();
	this.instance.setTransform(139.5,44.5,1,1,0,0,0,32,32);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// krug
	this.instance_1 = new lib.Символ23();
	this.instance_1.setTransform(49,49,1,1,0,0,0,49,49);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,98,98);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 1
	this.instance = new lib.Символ22();
	this.instance.setTransform(49,49,1,1,0,0,0,49,49);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:0},3,cjs.Ease.get(1)).wait(1).to({alpha:1},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,171.5,98);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ20();
	this.instance.setTransform(12.5,12,1,1,0,0,0,12.5,12);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:21.5},9,cjs.Ease.get(1)).to({x:12.5},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,25,24);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ19();
	this.instance.setTransform(-93.5,104.1,1.24,1.24,0,0,0,49.5,5.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ18();
	this.instance_1.setTransform(-10.5,103,1,1,0,0,0,12.5,12);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-154.9,91,156.9,24);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 1
	this.instance = new lib.Символ17();
	this.instance.setTransform(12.5,12,1,1,0,0,0,12.5,12);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:0},3,cjs.Ease.get(1)).wait(1).to({alpha:1},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-154.9,91,156.9,24);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.instance = new lib.Символ30();
	this.instance.setTransform(66.4,24.1,1,1,0,0,0,37.1,18.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// bubble
	this.instance_1 = new lib.Символ14();
	this.instance_1.setTransform(80.5,44.5,1,1,0,0,0,80.5,44.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.4,0,166.5,89);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 1
	this.instance = new lib.Символ15();
	this.instance.setTransform(312,41.6,1,1,0,0,0,76.5,36.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:102},14,cjs.Ease.get(1)).to({x:107},5,cjs.Ease.get(1)).wait(20).to({x:102},5,cjs.Ease.get(1)).to({x:317},5,cjs.Ease.get(1)).to({_off:true},1).wait(50));

	// 2
	this.instance_1 = new lib.Символ12();
	this.instance_1.setTransform(316.3,47.7,1,1,0,0,0,83.3,33.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(49).to({_off:false},0).to({x:101.3},15,cjs.Ease.get(1)).to({x:106.3},5,cjs.Ease.get(1)).wait(20).to({x:101.3},5,cjs.Ease.get(1)).to({x:321.3},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(235.5,5,153.1,69.7);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// 2
	this.instance = new lib.Символ52();
	this.instance.setTransform(150,65,1,1,0,0,0,22.6,17.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({alpha:1},3,cjs.Ease.get(1)).wait(1).to({alpha:0},4,cjs.Ease.get(1)).wait(1));

	// 1
	this.instance_1 = new lib.Символ11();
	this.instance_1.setTransform(112.3,45,1,1,0,0,0,83.3,35);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({alpha:0},3,cjs.Ease.get(1)).wait(1).to({alpha:1},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(264.5,15,153.1,69.7);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// upir_16.png
	this.instance = new lib.Символ5();
	this.instance.setTransform(23,96,1,1,0,0,0,24,42);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:3,x:19,y:85},14,cjs.Ease.get(1)).to({rotation:0,x:23,y:96},10,cjs.Ease.get(1)).to({y:93},6,cjs.Ease.get(1)).to({regX:24.1,rotation:-1.8,x:18,y:94.2},5,cjs.Ease.get(1)).to({regY:42.1,rotation:-4,x:11.4,y:89.3},5,cjs.Ease.get(1)).to({regX:23.9,regY:42,rotation:-7,x:2.5,y:89.9},4,cjs.Ease.get(1)).to({regX:24,rotation:-8,x:-0.8,y:86.2},6,cjs.Ease.get(1)).wait(4).to({regX:23.9,rotation:-7,x:2.5,y:89.9},5,cjs.Ease.get(1)).to({regX:24.1,regY:42.1,rotation:-4,x:11.4,y:89.3},5,cjs.Ease.get(1)).to({regX:23.9,regY:42,rotation:-7,x:2.5,y:89.9},4,cjs.Ease.get(1)).to({regX:24,rotation:-8,x:-0.8,y:86.2},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:-11,x:-9.3,y:87.5},3,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:0,x:23,y:96},23,cjs.Ease.get(1)).to({regX:23.9,regY:42.1,rotation:19,x:38,y:110.2},10,cjs.Ease.get(1)).wait(15).to({regX:24,regY:42,rotation:0,x:23,y:96},10).wait(1));

	// upir_13.png
	this.instance_1 = new lib.Символ6();
	this.instance_1.setTransform(-185,127.5,1,1,0,0,0,34,45.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:-3,x:-184.9,y:124.5},14,cjs.Ease.get(1)).to({rotation:0,x:-185,y:127.5},10,cjs.Ease.get(1)).to({y:124.5},6,cjs.Ease.get(1)).to({rotation:-1.8,x:-189,y:132.2},5,cjs.Ease.get(1)).to({rotation:-4,x:-194.1,y:135.2},5,cjs.Ease.get(1)).to({rotation:-7,x:-199.9,y:146.4},4,cjs.Ease.get(1)).to({rotation:-8,x:-202.3,y:146.3},6,cjs.Ease.get(1)).wait(4).to({rotation:-7,x:-199.9,y:146.4},5,cjs.Ease.get(1)).to({rotation:-4,x:-194.1,y:135.2},5,cjs.Ease.get(1)).to({rotation:-7,x:-199.9,y:146.4},4,cjs.Ease.get(1)).to({rotation:-8,x:-202.3,y:146.3},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:-11,x:-207.3,y:158.1},3,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:0,x:-185,y:127.5},23,cjs.Ease.get(1)).to({rotation:10.8,x:-173.1,y:102},10,cjs.Ease.get(1)).wait(15).to({rotation:0,x:-185,y:127.5},10).wait(1));

	// upir_08.png
	this.instance_2 = new lib.Символ7();
	this.instance_2.setTransform(87.5,124.5,1,1,0,0,0,35.5,86.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:35.6,rotation:-9,x:90.6,y:124.6},14,cjs.Ease.get(1)).to({regX:35.5,rotation:0,x:87.5,y:124.5},10,cjs.Ease.get(1)).to({y:121.5},6,cjs.Ease.get(1)).to({regX:35.6,rotation:-1.8,x:83.3,y:120.6},5,cjs.Ease.get(1)).to({regX:35.5,rotation:-4,x:77.6,y:113.1},5,cjs.Ease.get(1)).to({rotation:-7,x:70.1,y:110.2},4,cjs.Ease.get(1)).to({rotation:-8,x:67,y:105.4},6,cjs.Ease.get(1)).wait(4).to({rotation:-7,x:70.1,y:110.2},5,cjs.Ease.get(1)).to({rotation:-4,x:77.6,y:113.1},5,cjs.Ease.get(1)).to({rotation:-7,x:70.1,y:110.2},4,cjs.Ease.get(1)).to({rotation:-8,x:67,y:105.4},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:-11,x:59.4,y:103.2},3,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:0,x:87.5,y:124.5},23,cjs.Ease.get(1)).to({rotation:54,x:78.7,y:143.6},10,cjs.Ease.get(1)).wait(15).to({rotation:0,x:87.5,y:124.5},10).wait(1));

	// upir_05.png
	this.instance_3 = new lib.Символ8();
	this.instance_3.setTransform(-55.5,32,1,1,0,0,0,60.5,116);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({rotation:4,x:-52.5},14,cjs.Ease.get(1)).to({rotation:0,x:-55.5},10,cjs.Ease.get(1)).to({y:35},6,cjs.Ease.get(1)).to({rotation:-1.8,x:-62.7,y:32.7},5,cjs.Ease.get(1)).to({rotation:-4,x:-71.1,y:36.9},5,cjs.Ease.get(1)).to({regX:60.6,rotation:-7,x:-83,y:35.9},4,cjs.Ease.get(1)).to({regX:60.5,rotation:-8,x:-86.5,y:39.7},6,cjs.Ease.get(1)).wait(4).to({regX:60.6,rotation:-7,x:-83,y:35.9},5,cjs.Ease.get(1)).to({regX:60.5,rotation:-4,x:-71.1,y:36.9},5,cjs.Ease.get(1)).to({regX:60.6,rotation:-7,x:-83,y:35.9},4,cjs.Ease.get(1)).to({regX:60.5,rotation:-8,x:-86.5,y:39.7},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:-11,x:-98.5},3,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:0,x:-55.5,y:32},23,cjs.Ease.get(1)).to({regX:60.6,rotation:-2,x:-40.2,y:28.7},10,cjs.Ease.get(1)).to({rotation:-15,y:28.6},5).to({rotation:-2,y:28.7},5).to({rotation:-15,y:28.6},5).to({regX:60.5,rotation:0,x:-55.5,y:32},10).wait(1));

	// upir_02.png
	this.instance_4 = new lib.Символ4();
	this.instance_4.setTransform(-50.5,41.6,1,1,0,0,0,143.5,61.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:-47.5},14,cjs.Ease.get(1)).to({x:-50.5},10,cjs.Ease.get(1)).to({y:38.6},6,cjs.Ease.get(1)).to({regX:143.6,rotation:-1.8,x:-57.3,y:42.1},5,cjs.Ease.get(1)).to({regY:61.5,rotation:-4,x:-65.8,y:40},5,cjs.Ease.get(1)).to({regX:143.5,regY:61.6,rotation:-7,x:-77,y:44.8},4,cjs.Ease.get(1)).to({rotation:-8,x:-81.1,y:42.6},6,cjs.Ease.get(1)).wait(4).to({rotation:-7,x:-77,y:44.8},5,cjs.Ease.get(1)).to({regX:143.6,regY:61.5,rotation:-4,x:-65.8,y:40},5,cjs.Ease.get(1)).to({regX:143.5,regY:61.6,rotation:-7,x:-77,y:44.8},4,cjs.Ease.get(1)).to({rotation:-8,x:-81.1,y:42.6},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:-11,x:-91.7,y:48.2},3,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:0,x:-50.5,y:41.6},23,cjs.Ease.get(1)).to({regX:143.6,rotation:1.8,x:-43.5,y:41.3},10,cjs.Ease.get(1)).wait(15).to({regX:143.5,rotation:0,x:-50.5,y:41.6},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-219,-84,362,687);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 2
	this.instance = new lib.Символ73();
	this.instance.setTransform(315.9,176,1,1,0,0,0,368.9,199);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},0).wait(4).to({alpha:0},4,cjs.Ease.get(1)).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ75();
	this.instance_1.setTransform(300,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({scaleX:1.1,scaleY:1.1},3,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53,-23,738,398);


(lib.Символ25_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance_1 = new lib.Символ24();
	this.instance_1.setTransform(107.5,56,0.62,0.62,0,0,0,107.5,56);
	this.instance_1.alpha = 0.422;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(40.9,21.3,133.3,69.5);


(lib.Символ23_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ25_1();
	this.instance.setTransform(107.5,56,1,1,0,0,0,107.5,56);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-322.3},135).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(40.9,21.3,133.3,69.5);


(lib.Символ22_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance_2 = new lib.Символ23_1();
	this.instance_2.setTransform(264.5,42.1,1.78,1.78,0,0,0,107.5,56);
	this.instance_2.alpha = 0.328;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(50).to({_off:false},0).to({_off:true},218).wait(49));

	// Слой 1 - копия: 2
	this.instance_3 = new lib.Символ23_1();
	this.instance_3.setTransform(264.5,92,1.263,1.263,0,0,0,107.5,56);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(92).to({_off:false},0).wait(225));

	// Слой 1
	this.instance_4 = new lib.Символ23_1();
	this.instance_4.setTransform(264.5,42,1,1,0,0,0,107.5,56);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(135).to({_off:true},1).wait(181));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(197.9,7.3,133.3,69.5);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.setTransform(85.5,44.5,1,1,0,0,0,80.5,44.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:48.5},9,cjs.Ease.get(1)).to({y:44.5},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,0,166.5,89);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ32();
	this.instance.setTransform(82.7,44.5,1,1,0,0,0,82.7,44.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:88.7},13,cjs.Ease.get(1)).to({x:82.7},11,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,0,166.5,89);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// speech_2
	this.instance = new lib.Символ40();
	this.instance.setTransform(93.3,-42.5,1,1,0,0,0,82.7,44.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({x:61.3,alpha:1},3,cjs.Ease.get(1)).wait(1).to({x:93.3,alpha:0},4,cjs.Ease.get(1)).wait(1));

	// speech_1
	this.instance_1 = new lib.Символ33();
	this.instance_1.setTransform(67.7,-43.5,1,1,0,0,0,82.7,44.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({alpha:0},3,cjs.Ease.get(1)).wait(1).to({alpha:1},4,cjs.Ease.get(1)).wait(1));

	// upir
	this.instance_2 = new lib.Символ3();
	this.instance_2.setTransform(152.5,309.5,1,1,0,0,0,153.5,311.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({regY:311.4,scaleX:0.9,scaleY:0.9,rotation:3,x:94.6,y:276.5},3).wait(1).to({regY:311.5,scaleX:1,scaleY:1,rotation:0,x:152.5,y:309.5},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-220,-88,371,689);


// stage content:



(lib._600x300 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var _this = this;
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		
		
		
		
		
		
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		  function fl_MouseOverHandler_5()
		{
		    _this.navedi.gotoAndPlay(1);
			_this.gift.gotoAndPlay(1);
			_this.text.gotoAndPlay(1);
			_this.upir.gotoAndPlay(1);
			_this.form.gotoAndPlay(1);
			_this.fon.gotoAndPlay(1);
		
		
		    
		}
		
		
		stage.canvas.onmouseout = fl_MouseOutHandler_23;
		
		  function fl_MouseOutHandler_23()
		{
		
			_this.navedi.gotoAndPlay(5);
			_this.gift.gotoAndPlay(5);
			_this.text.gotoAndPlay(5);
			_this.upir.gotoAndPlay(5);
			_this.form.gotoAndPlay(5);
			_this.fon.gotoAndPlay(5);
		
		
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// logo
	this.instance = new lib.Символ9();
	this.instance.setTransform(62.5,40,1,1,0,0,0,69.5,45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// navedi
	this.navedi = new lib.Символ16();
	this.navedi.setTransform(574.5,171.5,1,1,0,0,0,12.5,12);

	this.timeline.addTween(cjs.Tween.get(this.navedi).wait(1));

	// gift
	this.gift = new lib.Символ21();
	this.gift.setTransform(483,174,1,1,0,0,0,49,49);

	this.timeline.addTween(cjs.Tween.get(this.gift).wait(1));

	// form
	this.form = new lib.Символ55();
	this.form.setTransform(393.3,150,1,1,0,0,0,40.6,42.7);

	this.timeline.addTween(cjs.Tween.get(this.form).wait(1));

	// text
	this.text = new lib.Символ10();
	this.text.setTransform(431,39.4,1,1,0,0,0,83.3,35);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(1));

	// upir
	this.upir = new lib.Символ2();
	this.upir.setTransform(373.5,415.5,1,1,0,0,0,153.5,311.5);

	this.timeline.addTween(cjs.Tween.get(this.upir).wait(1));

	// cloude
	this.instance_1 = new lib.Символ22_1();
	this.instance_1.setTransform(547.5,220.5,3.19,3.19,0,0,0,107.5,56);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// bg
	this.fon = new lib.Символ1();
	this.fon.setTransform(300,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.fon).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(247,127,1313.9,728);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;