(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 305,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.Символ16 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(0,0,0,0.031)","rgba(0,0,0,0.431)","rgba(0,0,0,0)"],[0,0.435,1],-55.7,0,55.8,0).s().p("EgIsAlQMAAAhKfIRZAAMAAABKfg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-55.7,-238.4,111.5,477);


(lib.Символ12 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIOCPIAAgvIj1AAIAAjoIAuAAIAADHIA8AAIAAjHIAvAAIAADHIA7AAIAAjHIAvAAIAADHIAgAAIAABQgAgYCPIAAgvIiXAAIAAAvIgvAAIAAhQIASAAQAYggAMgqQAMgrAAg3IAAgbICTAAIAADHIAfAAIAABQgAhwhmQAAAygMAuQgMAsgTAZIBjAAIAAipIg4AAgA7TCPIAAgvIiXAAIAAAvIgvAAIAAhQIASAAQAYggAMgqQAMgrAAg3IAAgbICTAAIAADHIAhAAIAABQgA8rhmQAAAygMAuQgMAsgTAZIBjAAIAAipIg4AAgA/aCPIAAgvIiXAAIAAAvIgvAAIAAhQIASAAQAYggAMgqQAMgrAAg3IAAgbICTAAIAADHIAhAAIAABQgEggygBmQAAAygMAuQgMAsgTAZIBjAAIAAipIg4AAgAQ6BmIAAghIAGAAQAbAAALgGQALgGALgVIAEgHIhTilIA0AAIA5ByIA6hyIArAAIhVCoQgVAqgTAPQgPANgyAAgAA0BmIAAghIAGAAQAbAAALgGQALgGALgVIAEgHIhTilIA0AAIA5ByIA6hyIArAAIhVCoQgVAqgTAPQgPANgyAAgAmvBmIAAghIAGAAQAbAAALgGQALgGALgVIAEgHIhTilIA0AAIA5ByIA6hyIArAAIhVCoQgVAqgTAPQgPANgyAAgEgmGABFQgggiAAg2QAAg5AgghQAgghA3AAQA2AAAhAhQAgAhAAA4QAAA4ggAhQghAhg4AAQg1AAggghgEglggBVQgSAYAAAqQAAAnASAZQASAZAeAAQAfAAATgZQASgZAAgoQAAgpgSgYQgTgZgeAAQgfAAgSAZgEAplABgIAAjoIAwAAIAADogEAmsABgIAAjoIAvAAIAABiIAQAAQA0AAAUAMQAbAQAAAiQAAAogfATQgVANg2AAgEAnbABCIAPAAQAaAAANgKQANgKAAgUQAAgSgNgIQgNgIgaAAIgPAAgEAlAABgIAAhpIhhAAIAABpIgwAAIAAjoIAwAAIAABfIBhAAIAAhfIAxAAIAADogEAhFABgIAAiqIhqCqIgrAAIAAjoIAuAAIAACpIBripIArAAIAADogAddBgIgZg+IhhAAIgYA+IgkAAIBcjoIAxAAIBbDogAc4ACIgkhbIglBbIBJAAgAX6BgIAAjoIBSAAQArAAASAOQASAOAAAiQAAAmgYAVQgZATgsAAIgUAAIAABcgAYqgaIAJAAQAZAAAPgLQAOgMAAgUQAAgjgsAAIgTAAgAWfBgIgcg0QgUgkgPgPIgTAAIAABnIguAAIAAjoIAuAAIAABjQAOgBAHgGQAGgGASgeIAJgPQAPgZALgIQALgIAVAAIAMAAIAAAeQgNAAgFADQgGAEgIANIgUAiQgLASgVAKQATAFAMAKQALAJAPAbIAnBFgAMjBgIAAjoICTAAIAAAgIhiAAIAABBIBQAAIAAAgIhQAAIAABGIBpAAIAAAhgAJhBgIAAjoICSAAIAAAgIhiAAIAABBIBRAAIAAAgIhRAAIAABGIBqAAIAAAhgApzBgIAAjoICLAAIAAAgIhbAAIAABCIAQAAQAgAAAMACQANACAMAIQAbAQAAAiQAAAogfATQgVANg1AAgApDBCIAMAAQAaAAANgKQANgKAAgUQAAgSgMgIQgNgIgZAAIgOAAgAs2BgIAAiqIhrCqIgrAAIAAjoIAvAAIAACpIBqipIAsAAIAADogAwkBgIgKgXQgUgvgIgOQgIgMgKgIIgLAAIAABoIgtAAIAAhoIgLAAQgKAIgIANQgIAPgUAtIgIASIgCAFIgzAAQAKgSAPgiIAGgPQAOgdAKgKQAJgKAVgFQgMgFgGgIQgHgIgKgUIgFgJQgKgTgGgGQgHgGgKAAIAAgeQAaAAAOAJQANAJAOAcIALAVQAKAUAEAFQAFAFAJACIAAhjIAtAAIAABjQAJgDAGgFQAEgGAJgSIALgVQAOgcANgJQAOgJAaAAIAAAeQgKAAgHAGQgGAGgKATIgFAJQgKAUgHAIQgGAIgMAFQAUAFAKAKQAKAKAOAdIAGAPQAPAiAKASgA28BgIAAjoIBSAAQArAAASAOQASAOAAAiQAAAmgYAVQgZATgsAAIgUAAIAABcgA2MgaIAJAAQAZAAAPgLQAOgMAAgUQAAgjgsAAIgTAAgA5+BgIAAjoICSAAIAAAgIhiAAIAABBIBRAAIAAAgIhRAAIAABGIBqAAIAAAhgEgoDABgIAAjIIhhAAIAADIIgwAAIAAjoIDCAAIAADog");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-270.9,-14.3,542,28.8);


(lib.Символ10 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ATPCUIAAjrIAvAAIAAAiQASgmAmABQAgAAASAWQASAXAAAoQAAArgUAZQgVAaghABQgcAAgWgWIAABQgAT+gbIAABDQARATATAAQARAAALgQQAKgRAAgaQAAg1gjAAQgUgBgTAbgAdWBAQgagYAAgpQAAgoAXgZQAXgZAmABQAnAAARAXQARAZAAAyIhsAAQAGAxAxAAQAYAAAdgLIAAAiQghAKgeAAQgrgBgZgZgAergRQAAgsgcAAQgeAAgEAsIA+AAIAAAAgAWuBBQgYgZAAgoQAAgpAZgZQAXgZAqABQAqgBAYAZQAYAZAAApQAAApgYAYQgZAZgqAAQgpAAgYgZgAXTgsQgLAQAAAcQAAAbALARQAKAQATAAQAoAAAAg8QAAgcgLgQQgLgRgSAAQgSAAgLARgAQIBBQgYgZAAgoQAAgpAZgZQAXgZAqABQAqgBAYAZQAYAZAAApQAAApgYAYQgYAZgrAAQgpAAgYgZgAQtgsQgLAQAAAcQAAAbALARQALAQARAAQApAAAAg8QAAgcgLgQQgKgRgTAAQgTAAgKARgAK7BBQgZgZAAgoQAAgqAZgZQAZgXAsAAQAVgBAcAIIAAAhQgdgJgRAAQgWAAgMAQQgNAQAAAbQAAAZAOARQAOAQAXABQAVAAAWgKIAAAgQgdAJgZAAQgqAAgXgZgAmdBBQgYgZAAgoQAAgpAZgZQAYgZApABQAqgBAZAZQAXAZAAApQAAApgXAYQgZAZgrAAQgoAAgZgZgAl4gsQgLAQABAcQAAAbAKARQALAQASAAQApAAAAg8QAAgcgLgQQgLgRgTAAQgSAAgLARgArqBBQgZgZAAgoQAAgqAZgZQAZgXAsAAQAVgBAcAIIAAAhQgdgJgRAAQgWAAgNAQQgMAQAAAbQAAAZAOARQANAQAYABQAVAAAWgKIAAAgQgdAJgZAAQgpAAgYgZgA3UBDIgBAAQgYAXgbAAQgWgBgPgOQgOgOAAgWQAAgdAXgNQAXgPArAAIANAAIAAgRQAAgbggAAQgbAAgcAQIAAghQAggMAfABQBEgBABA3IAABLQgBAUANABIAHgBIABAaQgPAEgMABQgcAAgJgXgA4OAjQAAAKAGAGQAHAHAKgBQARAAARgPIAAgjIgLAAQgugBAAAdgAbjBWIAAhOIg/AAIAABOIgvAAIAAitIAvAAIAABEIA/AAIAAhEIAuAAIAACtgAN6BWIAAiNIg2AAIAAggICcAAIAAAgIg3AAIAACNgAGXBWIAAitIBFAAQAjABASAJQARALABATQAAAQgKALQgJALgTAFQAWAEALAMQAMAMAAARQAAAYgRAKQgRALglAAgAHDA5IAMAAQAbAAAIgEQAJgEAAgNQAAgNgLgHQgKgHgVAAIgOAAgAHDgQIAOAAQASABAJgHQAJgGAAgMQAAgJgJgEQgJgFgRAAIgPAAgACDBWIAAitIAuAAIAABAIAUAAQApAAATANQASALAAAcQAAAdgUAOQgUAOgsAAgACxA4IAOAAQASAAAKgGQAJgHAAgOQAAgMgJgGQgJgGgTAAIgOAAgAgBBWIAAiNIg3AAIAAggICaAAIAAAgIg2AAIAACNgAiFBWIAAhEIgSAAQgJAKgJATIgUAnIgxAAIAUgiIAEgIQARggAPgGQgTgGgIgJQgKgMAAgQQAAgfAagMQAOgGArgBIAwAAIAACtgAimg1QgIAHAAANQAAANAIAHQAJAGAPAAIAJAAIAAg0IgJAAQgQAAgIAGgAorBWIAAiNIg3AAIAAggICdAAIAAAgIg3AAIAACNgAvUBWIAAiNIg2AAIAAggICcAAIAAAgIg3AAIAACNgAxVBWIAAh2IhGB2IguAAIAAitIAsAAIAAB2IBFh2IAuAAIAACtgA1QBWIAAiNIg2AAIAAggICcAAIAAAgIg3AAIAACNgA7rBWIAAitIBFAAQAiABASAJQASALAAATQAAAQgKALQgJALgTAFQAWAEALAMQAMAMAAARQAAAYgRAKQgQALgmAAgA6/A5IALAAQAbAAAJgEQAIgEAAgNQAAgNgKgHQgKgHgWAAIgNAAgA6/gQIANAAQATABAIgHQAJgGAAgMQAAgJgJgEQgIgFgRAAIgPAAgA9IBWIgzhVIg3BVIgmAAIBKhyIhIh3IA5AAIAwBPIA0hPIAoAAIhIBvIBKB6g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-201,-14.8,402,29.7);


(lib.Символ9 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006699").s().p("EAmpACUIAAggIAEAAQATABAJgEQAJgFAGgKIAJgUIhFilIAvAAIAvBwIAxhwIAnAAIhLCpQgUAvgNAJQgOAKgqAAgAOGCUIAAjrIAvAAIAAAiQASgmAnABQAgAAARAWQATAXgBAoQAAArgUAZQgUAagiABQgbAAgXgWIAABQgAO1gbIAABDQARATAUAAQARAAALgQQAJgRABgaQAAg1gjAAQgVgBgTAbgAcoB9IAAgnIh3AAIAAAnIgtAAIAAhHIAQAAQAQgWAKgeQAIgdAAgoIAAgUICBAAIAACNIAeAAIAABHgAbfg3QAAAfgGAZQgHAcgNAZIBFAAIAAhuIgrAAgAAKB9IAAgnIiKAAIAAitIAvAAIAACNIA+AAIAAiNIAtAAIAACNIAdAAIAABHgA/3B9IAAgnIh3AAIAAAnIgtAAIAAhHIARAAQAQgWAJgeQAIgdAAgoIAAgUICBAAIAACNIAeAAIAABHgEghAgA3QAAAfgGAZQgGAcgOAZIBFAAIAAhuIgrAAgAeHBAQgagYAAgpQABgoAXgZQAXgZAmABQAmAAASAXQARAZAAAyIhsAAQAFAxAyAAQAXAAAegLIAAAiQghAKgeAAQgsgBgZgZgAfdgRQAAgsgdAAQgdAAgEAsIA+AAIAAAAgAUKBSIAAggQAeAJAWABQASgBAKgFQAJgHAAgMQAAgOgMgHQgMgHgZAAIgGAAIAAgZIAHAAQAWAAALgGQAKgFABgMQAAgKgJgFQgJgGgRAAQgUAAgaAJIAAgdQAbgJAdABQAkgBARALQASALAAAWQAAANgJAKQgIAKgQAIQATAGAJAJQAKAKAAAQQAAAZgWAOQgVAPgjABQgZgBghgHgARnBAQgagYAAgpQAAgoAYgZQAWgZAnABQAmAAARAXQASAZAAAyIhsAAQAFAxAyAAQAXAAAegLIAAAiQghAKgeAAQgsgBgZgZgAS9gRQAAgsgdAAQgdAAgEAsIA+AAIAAAAgAGcBHQgWgUgDgmIgcAAIAABJIgtAAIAAitIAtAAIAABJIAcAAQAEgnAVgSQAVgUAlABQApgBAVAYQAXAYAAArQAAAqgXAYQgVAYgpAAQglgBgVgSgAG7guQgJAQAAAeQAAAdAJAQQAJAPASAAQATAAAIgPQAJgQAAgdQAAgegJgPQgIgQgTAAQgSAAgJAPgAqyBAQgZgYAAgpQAAgoAXgZQAXgZAmABQAmAAASAXQASAZAAAyIhsAAQAEAxAyAAQAYAAAegLIAAAiQgiAKgeAAQgsgBgZgZgApbgRQAAgsgdAAQgeAAgEAsIA/AAIAAAAgEglMABBQgXgZAAgoQgBgpAZgZQAYgZAqABQApgBAYAZQAZAZAAApQAAApgZAYQgYAZgqAAQgpAAgZgZgEgkmgAsQgMAQAAAcQAAAbALARQALAQASAAQAoAAAAg8QAAgcgKgQQgLgRgSAAQgTAAgKARgEAkuABWIAAiNIg2AAIAAggICdAAIAAAgIg4AAIAACNgEAipABWIAAhOIg/AAIAABOIgvAAIAAitIAvAAIAABEIA/AAIAAhEIAvAAIAACtgAYzBWIAAh2IhFB2IguAAIAAitIArAAIAAB2IBGh2IAuAAIAACtgAMdBWIAAiNIg/AAIAACNIgvAAIAAitICdAAIAACtgADUBWIAAh2IhFB2IgvAAIAAitIAsAAIAAB2IBFh2IAvAAIAACtgAjnBWIAAh2IhGB2IguAAIAAitIAsAAIAAB2IBGh2IAuAAIAACtgAnhBWIAAiNIg3AAIAAggICdAAIAAAgIg3AAIAACNgAslBWIAAiNIg/AAIAACNIguAAIAAitICcAAIAACtgAxSBWIAAh2IhGB2IgvAAIAAitIAtAAIAAB2IBFh2IAvAAIAACtgA3wBWIAAitIAtAAIAACNIA0AAIAAiNIAtAAIAACNIA0AAIAAiNIAtAAIAACtgA5VBWIAAh2IhGB2IguAAIAAitIAsAAIAAB2IBFh2IAvAAIAACtgA8zBWIAAiNIg/AAIAACNIguAAIAAitICbAAIAACtgEgm/ABWIAAjJIhhAAIAADJIgxAAIAAjpIDCAAIAADpg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-264.2,-14.8,528.5,29.7);


(lib.Символ8 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006699").s().p("AQzCOIAAjqIAvAAIAAAgQASglAnAAQAfAAASAYQASAWAAApQAAAqgVAZQgTAagjAAQgbAAgWgVIAABQgARighIAABDQARATATAAQASAAAKgRQAKgQAAgbQAAg1gjAAQgUABgTAagAp6COIAAjqIAvAAIAAAgQATglAmAAQAgAAARAYQATAWgBApQAAAqgUAZQgUAagiAAQgbAAgXgVIAABQgApLghIAABDQARATAUAAQARAAALgRQAKgQAAgbQgBg1giAAQgUABgUAagAuNB2IAAgmIh3AAIAAAmIgtAAIAAhGIAQAAQARgVAIgdQAJgfgBgoIAAgTICCAAIAACMIAeAAIAABGgAvWg9QAAAfgHAcQgGAagNAYIBFAAIAAhuIgrAAgAxyB2IAAgmIh2AAIAAAmIgtAAIAAhGIAQAAQAQgVAKgdQAHgfABgoIAAgTICBAAIAACMIAdAAIAABGgAy6g9QAAAfgGAcQgHAagOAYIBGAAIAAhuIgrAAgAXRA7QgZgZABgoQAAgqAZgYQAYgZAsAAQAWAAAcAIIAAAiQgdgKgSAAQgVAAgNAQQgNAQAAAbQAAAZAPARQANARAXAAQAWAAAWgKIAAAgQgdAIgZAAQgqAAgYgYgAVhA9IgCAAQgXAWgbAAQgXAAgOgNQgOgPAAgVQgBgeAXgNQAYgQAqAAIANAAIAAgQQAAgbgfAAQgbAAgdAQIAAghQAggLAggBQBEABAAA2IAABLQAAAVANAAIAHgBIAAAaQgOAFgMgBQgdAAgIgWgAUnAdQgBAJAHAHQAGAGAKABQARgBARgQIAAgjIgLAAQgtABAAAcgALJA7QgXgZAAgoQAAgqAYgYQAYgYAqgBQApABAYAYQAZAZAAApQAAApgZAYQgYAYgqAAQgpAAgZgYgALugzQgKARgBAcQAAAbALAQQALARASAAQAoAAAAg8QAAgcgKgRQgLgQgSAAQgTAAgLAQgAAnA7QgZgZAAgpQAAgoAXgZQAWgYAngBQAmAAARAZQASAYAAAyIhsAAQAFAxAyABQAXgBAegKIAAAgQgiAKgdAAQgsAAgZgYgAA+gXIA/AAQAAgsgdAAQgdAAgFAsgAsuA7QgZgZAAgpQAAgoAXgZQAWgYAngBQAmAAARAZQASAYAAAyIhsAAQAFAxAyABQAXgBAegKIAAAgQgiAKgeAAQgrAAgZgYgAsXgXIA/AAQAAgsgdAAQgdAAgFAsgA3GA7QgYgZAAgoQgBgqAZgYQAYgYAqgBQApABAYAYQAZAZAAApQAAApgZAYQgYAYgqAAQgqAAgXgYgA2hgzQgMARAAAcQAAAbALAQQALARASAAQAoAAAAg8QAAgcgKgRQgLgQgSAAQgTAAgKAQgA/GA7QgZgZAAgoQAAgqAZgYQAYgYApgBQAqABAYAYQAYAZAAApQAAApgYAYQgYAYgqAAQgqAAgXgYgA+hgzQgLARAAAcQgBAbALAQQALARASAAQAoAAAAg8QABgcgLgRQgLgQgTAAQgSAAgKAQgAHEBQIADi5IgBgLIg7ADIABgNIgBgPICmAAIgBAPIABANIg5gDIACDEgAEzBQIAAjdIANABIAdAAIAMgBIAADdgAezBQIAAh2IhFB2IgvAAIAAisIAsAAIAAB1IBGh1IAuAAIAACsgAbVBQIAAiOIgpAAIAAADQAABQgRAeQgQAdgvAAIAAggQAWAAAGgZQAIgaAAhAIAAgZICFAAIAACsgAOtBQIAAiOIg3AAIAAgeICdAAIAAAeIg3AAIAACOgAg6BQIgLgVQgTglgQgPIgPAAIAABJIgsAAIAAisIAsAAIAABIQANAAAHgGQAFgEANgXIAEgIQALgUAKgGQAJgFAVAAIAIAAIAAAdIgFAAQgJAAgDADQgEADgGAMIgKARQgJAPgRAGQAPAEAIAFQAJAIALATIAXApIAHAKgAj2BQIgDgGIgHgOQgUgogMgPIgKAAIAABLIgrAAIAAhLIgLAAQgNAPgTAoIgHAOIgDAGIgwAAIAcg1QAKgSAHgHQAHgFAOgEQgSgHgLgVIgGgPQgHgNgNAAIAAgdQAaAAAKAFQAKAHAIAVIADAJQAHATAHAFQAFAFAOAAIAAhHIArAAIAABHQANAAAGgFQAGgFAGgTIAEgJQAIgVAKgHQAJgFAbAAIAAAdQgNAAgHANIgGAPQgLAVgSAHQAOAEAIAFQAHAHAKASIANAbIAOAagA44BQIAAiOIg/AAIAACOIguAAIAAisICbAAIAACsgAJGAaIAAgiIBRAAIAAAig");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-201.6,-14.2,403.2,28.5);


(lib.Символ7 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF33").s().p("APVBqIAAgjIiEAAIAAirIAkAAIAACTIBIAAIAAiTIAkAAIAACTIAXAAIAAA7gAUjA3QgTgUgDglIgYAAIAABJIglAAIAAirIAlAAIAABLIAYAAQADgoAUgTQATgVAiAAQAmAAAUAYQAUAYAAAsQAAApgUAYQgUAYgmAAQgiAAgUgVgAU8hAQgLASAAAhQAAAeALASQAKATATAAQATAAAMgSQAKgTABgfQgBgggKgSQgLgTgUAAQgSAAgLATgAxLAzQgYgZAAgnQAAgqAYgZQAYgZApAAQAnAAAYAZQAZAZAAApQAAApgZAYQgYAZgpAAQgoAAgXgZgAwug+QgPASAAAeQAAAdAOASQANATAXAAQAXAAAOgSQANgTAAgdQAAgegNgSQgOgTgWAAQgXAAgNATgASCBHIAAh9IhOB9IggAAIAAirIAjAAIAAB9IBOh9IAgAAIAACrgAMEBHIAAh9IhQB9IggAAIAAirIAjAAIAAB9IBPh9IAgAAIAACrgAIaBHIAAiTIg+AAIAAgYIChAAIAAAYIg+AAIAACTgAFfBHIAAirIBsAAIAAAYIhIAAIAAAwIA8AAIAAAXIg8AAIAAA0IBOAAIAAAYgAEQBHIAAiTIhIAAIAACTIgkAAIAAirICQAAIAACrgAg1BHIAAirIAkAAIAABIIAMAAQAWAAAKACQALACAIAFQAVANgBAYQABAdgXAPQgQAJglAAgAgRAxIALAAQARAAAKgHQAKgIgBgOQABgOgKgGQgKgFgSAAIgKAAgAiwBHIAAiTIg+AAIAAgYIChAAIAAAYIg+AAIAACTgAkXBHIgTguIhHAAIgSAuIgbAAIBDirIAlAAIBECrgAkyACIgbhDIgbBDIA2AAgAoGBHIAAiTIg+AAIAAgYIChAAIAAAYIg+AAIAACTgAp+BHIAAh9IhPB9IggAAIAAirIAjAAIAAB9IBOh9IAhAAIAACrgAs8BHIAAhGQgUALgWAAQgbAAgNgMQgNgOAAgdIAAg5IAkAAIAAA5QAAARAGAHQAGAHANAAQASAAAQgLIAAhNIAkAAIAACrgAzrBHIAAirIA9AAQAfAAAOAKQANALAAAZQABAcgTAQQgSANggAAIgPAAIAABEgAzHgTIAHAAQASAAALgIQAKgJAAgOQABgagiAAIgNAAgA06BHIAAiTIhIAAIAACTIgkAAIAAirICQAAIAACrg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-144.7,-10.6,289.5,21.3);


(lib.Символ4 = function() {
	this.initialize();

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF33").s().p("APVBqIAAgjIiEAAIAAirIAlAAIAACTIBHAAIAAiTIAkAAIAACTIAXAAIAAA7gAUjA3QgTgUgDglIgZAAIAABJIgkAAIAAirIAkAAIAABLIAZAAQADgoAUgTQATgVAiAAQAmAAAUAYQAUAYAAAsQAAApgUAYQgUAYgmAAQgiAAgUgVgAU7hAQgLASABAhQgBAeALASQALATATAAQATAAAMgSQAKgTABgfQgBgggKgSQgLgTgUAAQgSAAgMATgAxLAzQgXgZgBgnQABgqAXgZQAYgZAoAAQAoAAAYAZQAZAZAAApQAAApgZAYQgYAZgpAAQgoAAgXgZgAwvg+QgOASAAAeQAAAdAOASQANATAXAAQAXAAANgSQAOgTAAgdQAAgegOgSQgNgTgXAAQgWAAgOATgASCBHIAAh9IhOB9IghAAIAAirIAjAAIAAB9IBPh9IAgAAIAACrgAMEBHIAAh9IhQB9IgfAAIAAirIAiAAIAAB9IBPh9IAgAAIAACrgAIaBHIAAiTIg+AAIAAgYIChAAIAAAYIg+AAIAACTgAFfBHIAAirIBsAAIAAAYIhIAAIAAAwIA8AAIAAAXIg8AAIAAA0IBOAAIAAAYgAEQBHIAAiTIhIAAIAACTIgkAAIAAirICQAAIAACrgAg1BHIAAirIAkAAIAABIIAMAAQAWAAAKACQALACAIAFQAVANAAAYQAAAdgXAPQgQAJglAAgAgRAxIALAAQARAAAKgHQAKgIAAgOQAAgOgKgGQgKgFgSAAIgKAAgAiwBHIAAiTIg9AAIAAgYICgAAIAAAYIg+AAIAACTgAkXBHIgTguIhHAAIgSAuIgbAAIBDirIAlAAIBDCrgAkyACIgbhDIgbBDIA2AAgAoGBHIAAiTIg9AAIAAgYICgAAIAAAYIg+AAIAACTgAp+BHIAAh9IhPB9IggAAIAAirIAjAAIAAB9IBOh9IAhAAIAACrgAs8BHIAAhGQgUALgWAAQgbAAgNgMQgNgOAAgdIAAg5IAkAAIAAA5QAAARAGAHQAFAHAOAAQATAAAPgLIAAhNIAkAAIAACrgAzrBHIAAirIA9AAQAfAAAOAKQANALAAAZQABAcgTAQQgSANggAAIgQAAIAABEgAzIgTIAIAAQASAAALgIQAKgJAAgOQAAgaggAAIgPAAgA06BHIAAiTIhIAAIAACTIgkAAIAAirICQAAIAACrg");
	this.shape.setTransform(-3,1.6);

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#008FB2").s().p("EgltAEvIAApdMBLbAAAIAAJdg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-241.4,-30.3,483,60.8);


(lib.Символ1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#008FB2").s().p("Eg6GANqIAA7TMB0NAAAIAAbTg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-371.9,-87.5,744,175);


(lib.Символ13 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ16();
	this.instance.setTransform(757.8,469.8,1.781,2.434,0,-16.3,-4.6);
	this.instance.alpha = 0.379;

	this.instance_1 = new lib.Символ16();
	this.instance_1.setTransform(1945.4,418.4,2.544,2.437,0,-14.9,-1.4);
	this.instance_1.alpha = 0.359;

	this.instance_2 = new lib.Символ16();
	this.instance_2.setTransform(1513.9,469.8,1.781,2.434,0,-16.3,-4.6);
	this.instance_2.alpha = 0.379;

	this.instance_3 = new lib.Символ16();
	this.instance_3.setTransform(1194.7,484.3,3.933,2.438,0,-14.3,0);
	this.instance_3.alpha = 0.359;

	this.instance_4 = new lib.Символ16();
	this.instance_4.setTransform(417,418.4,2.544,2.437,0,-14.9,-1.4);
	this.instance_4.alpha = 0.359;

	this.instance_5 = new lib.Символ16();
	this.instance_5.setTransform(-14.4,469.8,1.781,2.434,0,-16.3,-4.6);
	this.instance_5.alpha = 0.379;

	this.instance_6 = new lib.Символ16();
	this.instance_6.setTransform(-333.6,484.3,3.933,2.438,0,-14.3,0);
	this.instance_6.alpha = 0.359;

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFE40F").s().p("Ejy1A3YMgAChRQIAAAAIgCtgIgPryQbPlZRJEkQLNChUWkMQPjjNJ+FiQHnCWNmieIBHgOQbOlZRIElQLOCgUXkNQPijMJ+FiQCpBWNVhGQZnkwQaEXQLNChUWkMQPjjNJ/FiQHmCWNmieIBGgOQbPlZRJElQLNCgUWkNQPjjMJ+FiQDNBpTGiAMAAABrlg");
	this.shape.setTransform(792.6,652.3);

	this.addChild(this.shape,this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-763.5,-146.7,3112.2,1194.4);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.75},4).to({alpha:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-270.9,-14.3,542,28.8);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ4();

	this.instance_1 = new lib.Символ7();
	this.instance_1.setTransform(-3.1,1.6,1.041,1.041);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CCFF").s().p("EgnRAE8IAAp3MBOjAAAIAAJ3g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape},{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-241.4,-30.3,483,60.8);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.setTransform(251.6,-370.6,1,1,0,0,0,-0.5,-2.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-1268.8},99).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ1();
	this.instance_1.setTransform(144,70,1.549,4.285);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-511.5,-515.2,3112.2,1194.4);


// stage content:
(lib.it640305 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 3
	this.instance = new lib.Символ5();
	this.instance.setTransform(317.5,260.5);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ11();
	this.instance_1.setTransform(328.2,42.7);

	this.instance_2 = new lib.Символ10();
	this.instance_2.setTransform(319.5,85.8);

	this.instance_3 = new lib.Символ9();
	this.instance_3.setTransform(321.4,164.8);

	this.instance_4 = new lib.Символ8();
	this.instance_4.setTransform(319.3,202.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]}).wait(1));

	// Слой 2
	this.instance_5 = new lib.Символ14();
	this.instance_5.setTransform(354,168.7,1,1,-3.2,0,0,-0.5,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(159.8,-315.2,3146.9,1323.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;