(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/aaa.png?1473835896806", id:"aaa"},
		{src:"images/agaagaaggaggaag.png?1473835896806", id:"agaagaaggaggaag"},
		{src:"images/asgasdga.png?1473835896806", id:"asgasdga"},
		{src:"images/dddd.png?1473835896806", id:"dddd"},
		{src:"images/fff.png?1473835896806", id:"fff"},
		{src:"images/ggg.png?1473835896806", id:"ggg"},
		{src:"images/sss.png?1473835896806", id:"sss"},
		{src:"images/w256h2561380453915MouseOptions256x256321.png?1473835896806", id:"w256h2561380453915MouseOptions256x256321"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.aaa = function() {
	this.initialize(img.aaa);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,689,156);


(lib.agaagaaggaggaag = function() {
	this.initialize(img.agaagaaggaggaag);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,128,128);


(lib.asgasdga = function() {
	this.initialize(img.asgasdga);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,158,76);


(lib.dddd = function() {
	this.initialize(img.dddd);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,18,13);


(lib.fff = function() {
	this.initialize(img.fff);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,456,161);


(lib.ggg = function() {
	this.initialize(img.ggg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1611,366);


(lib.sss = function() {
	this.initialize(img.sss);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,150,181);


(lib.w256h2561380453915MouseOptions256x256321 = function() {
	this.initialize(img.w256h2561380453915MouseOptions256x256321);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,256);


(lib.Символ59 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.fff();
	this.instance.parent = this;
	this.instance.setTransform(-103.4,-36.5,0.453,0.453);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-103.4,-36.5,206.8,73);


(lib.Символ57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.agaagaaggaggaag();
	this.instance.parent = this;
	this.instance.setTransform(96,-130,1.338,1.338);

	this.instance_1 = new lib.agaagaaggaggaag();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-307,-130,1.338,1.338);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-307,-130,574.3,171.3);


(lib.Символ55 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aj6BqIgDgCIgBgDIAAgZIhfAAIAAAZIgBADQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAIggAAQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIAAg4QAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAAAAAIAPAAIAdh2QACgIAEgGQAEgFAGgDQAGgDAGgBIAMgBIANABQAGABAFADQAGADAEAFQAFAGACAIIAcB2IAQAAQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIAAA4IgBADQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAAAAAgAkUAoIgWhqIgCgDIgCgBQgBAAAAAAQgBABAAAAQAAABgBAAQAAABAAABIgYBqIA1AAgAKNBNQgLgCgJgGQgIgGgFgKQgEgKgBgRIAAhPQABgQAEgKQAFgKAIgGQAJgGALgCQAKgCAMAAIAvAEQAFAAAAAEIAAAXIgBADQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgxAAQgIAAgFADQgDAEAAAJIAAAXIA/AAIAEABIABADIAAAXIgBADIgEAAIg/AAIAAAaQAAAKADADQAFAEAIAAIAxAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAIABADIAAAXQAAAFgFAAIgRADIgeAAQgMAAgKgBgAIABNQgLgCgIgGQgIgGgGgKQgEgKAAgRIAAhPQAAgQAEgKQAGgKAIgGQAIgGALgCQALgCALAAIAwAEQAEAAAAAEIAAAXIgBADQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAAAAAIgyAAQgJAAgDADQgDAEgBAJIAAAXIA/AAIAEABIABADIAAAXIgBADIgEAAIg/AAIAAAaQABAKADADQADAEAJAAIAyAAQAAAAAAAAQABAAAAAAQABAAAAABQAAAAABAAIABADIAAAXQAAAFgEAAIgRADIgfAAQgLAAgLgBgACeBNIgIgCQgIgBgDgDQgDgDgBgIIAAidQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAgBIAEgBIBlAAIAEABIACADIAAAZIgCAEIgEABIhAAAIAAAjIAQAAQAQAAAOACQANACALAHQAFADAEAEQAEAEADAGQAGAJAAARIAAABIgBAPIgFANQgDAFgEAFQgEAEgFADQgLAHgNACQgPACgPAAgACyAsIAOAAIASgBQAIgBAFgDQAEgDABgEQACgEAAgGIAAgBQAAgGgCgFQgBgEgEgCQgFgDgIgBIggAAgAAGBKQgLgEgKgJIgJgLQgDgGgDgIQgDgHgCgJIAAgUIAAgbIAAgTQACgJADgIIAGgNIAJgLQAKgJALgEQANgFAPAAQAPAAANAFQANAEALAJIAHALIAHANQAGAQAAAUIAAAbQAAALgBAJQgCAJgDAHQgCAIgFAGIgHALQgLAJgNAEQgNAEgPAAQgPAAgNgEgAALg7QgGAKAAAWIAAAbQAAAMABAIQACAIADAEQAIAKAPAAQAIAAAFgCQAHgDADgFQADgEACgIQACgIAAgMIAAgbQAAgWgHgKQgDgEgHgDQgFgCgIAAQgPAAgIAJgAn+BKQgNgEgJgJIgJgLQgEgGgDgIQgCgHgCgJIgBgUIAAgbIABgTQACgJACgIIAHgNIAJgLQAJgJANgEQANgFAPAAQAQAAANAFQANAEAKAJIAIALIAHANQAGAQAAAUIAAAbQAAALgCAJQgBAJgDAHQgDAIgEAGIgIALQgKAJgNAEQgNAEgQAAQgPAAgNgEgAn4g7QgHAKAAAWIAAAbQAAAMABAIQACAIAEAEQAIAKAOAAQAJAAAFgCQAGgDAEgFQADgEACgIQACgIAAgMIAAgbQAAgWgHgKQgEgEgGgDQgFgCgJAAQgOAAgIAJgAGVBMIgDgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhGIg8AAIAABGIgBAEIgEABIgfAAIgEgBIgCgEIAAipQAAAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAIAEgBIAfAAIAEABQAAAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAABBIA8AAIAAhBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIADgBIAgAAIADABIABADIAACpIgBAEIgDABgAi5BMIgDgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAiiQAAgGADgCQADgCAFgBIAygEQANAAANADQAOADAKAHQAKAGAHAMQADAFABAHQACAHAAAJIAAACQAAARgGALQgEAGgEAFIgJAGQgKAHgNACQgNADgNAAIgVgBIAAA7IgBAEIgDABgAiFhGIgQABIAAAxIAUABQAQAAAIgGQADgDACgFQACgEAAgHIAAgCQAAgHgCgEQgCgFgEgDQgHgFgQAAgApsBMIgCgBQgBAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBIAAiCIgBgEIgDgCIgGgBIgnAAIgGABIgDACIgBAEIAACCIgCAEIgEABIgfAAIgEgBIgBgEIAAh9QAAgKACgJQACgJAGgGQAFgHAKgEQALgDAPAAIApAAQAQAAAKADQAKAEAFAHQAGAGACAJQACAJAAAKIAAB9IgBAEIgDABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72.7,-10.6,145.5,21.3);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC3333").s().p("AySEUQhAgBAAg/IAAmnQAAg/BAgBMAklAAAQBAABAAA/IAAGnQAAA/hAABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-123.6,-27.6,247.2,55.2);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0794B3").s().p("APREwQgJgCgHgEQgIgFgHgGQgNgNgIgTQgJgVABgdIAAgpQgBgdAJgUQAIgVANgLQAOgNARgFQARgFATAAQASAAANACIASAEIAGACQACABAAAEIAAAgQAAAGgHAAIgxgCQgIAAgIACQgIADgFAGQgFAGgDALQgEALAAAQIAAApQAAARAEALQADAKAFAGQAFAHAIACQAIADAIAAIAwgDIABAAQAHAAAAAHIAAAfQAAAEgCACIgGACIgSAEQgNABgSAAQgTAAgRgFgAMNEzQgPgDgLgHQgLgIgHgOQgGgOAAgWIAAhtQAAgWAGgOQAHgOALgHQALgIAPgDQAPgCAPAAIA2ADIAJABQAHABAAAGIAAAeQAAABAAAAQAAABgBAAQAAABAAABQgBAAAAABQgCACgDAAIhCAAQgMAAgFAFQgEAEAAANIAAAeIBVAAQADAAACACIACAEIAAAfQAAADgCADQgCABgDAAIhVAAIAAAjQAAANAEAFQAFAEAMAAIBCAAQADAAACADQAAAAABABQAAAAAAAAQABABAAABQAAAAAAABIAAAfQAAAFgHACIhAADQgOAAgPgCgAFBEzQgSgDgNgEIgEgCQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAgaIABgEIAEgBIBDACQARAAAHgHQAHgHAAgOIgBgQQgBgFgCgEQgEgEgFgDQgFgCgIAAIg6AAQgDAAgCgCQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgbQAAgHAGAAIA5AAQAHAAAGgCQAGgDADgEQADgEABgFIABgLIAAgEQABgLgIgHQgGgHgSAAIhBAEIgCAAIgDgCIgCgEIAAgaQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAIAjgJQARgDAUAAQATAAAQADQAQAEAMAIQAKAIAHANQAFANAAASIAAAFQAAAPgIANQgIAOgNAIQAOAHAIANQAHANAAAQIAAAGQAAATgGAOQgHANgLAJQgLAJgQAFQgQADgSAAQgUAAgSgCgAiREzIgMgBQgKgCgEgEQgFgFAAgKIAAjXQAAgDADgCQACgCACAAICKAAIAFABQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABIAAAiQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgFACIhYAAIAAAwIAWgBQAWAAATAEQASACAOAJQAHAEAGAGQAGAGAEAHQAFAPABAWIAAADQgBALgCAJQgCAKgBAHQgEAHgGAGQgGAGgHAEQgOAJgSADQgTADgWAAgAh3EIIAUAAQAPAAAKgCQAKgCAGgDQAGgEABgGQADgGAAgHIAAgDQAAgIgDgFQgBgGgGgDQgGgEgKgBIgtgBgAqiEwQgSgGgNgMIgMgPQgEgIgFgKQgEgKgBgMQgCgNAAgOIAAgnQAAgOACgMQABgMAEgKQAFgKAEgJIAMgOQANgNASgFQASgGAUAAQAVAAARAGQARAFAOANQAHAGAEAIQAFAJAEAKQAJAUgBAcIAAAnQAAAOgCANQgCAMgEAKQgEAKgFAIQgEAIgHAHQgOAMgRAGQgRAFgVAAQgUAAgSgFgAqaB6QgKANAAAeIAAAnQAAAPACALQADALAFAGQAKAOAUAAQALAAAHgEQAIgDAFgHQAEgGADgLQADgLAAgPIAAgnQAAgegKgNQgFgHgIgDQgHgDgLAAQgUAAgKANgAugEyQgLgCgEgEQgEgFAAgKIAAjIQAAgLAEgEQAEgFAKgCIA6gDQAYAAATADQATAEANAIQAOAIAIANQAIANAAATIAAAHQAAAPgIANQgHANgNAHQAMAGAJANQAIAMAAARIAAAFQAAALgCAJQgCAJgEAHQgJAOgOAJQgOAIgSADQgTADgWAAgAt7EIIAbAAQAMAAAJgCQAIgCAGgEQAFgEACgFQACgFAAgHIAAgEQAAgMgHgJQgEgEgHgCQgGgCgKAAIglAAgAt7BqIAAA5IAlAAQAJAAAHgCQAHgDADgDQADgDACgFIACgKIAAgFQAAgNgKgHQgLgGgYAAgARUEzQgCAAgCgCQgCgCAAgDIAAgpQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAABgBQACgCACAAIAoAAQAFAAAAAHIAAApQAAADgCACQAAAAAAABQgBAAAAAAQgBAAAAABQgBAAAAAAgAJ9EzQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAgBgBAAQgCgCAAgDIAAhfIhRAAIAABfQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBABQgBAAgBAAIgqAAQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgDgCABgDIAAjnQgBgDADgCQABAAAAAAQABgBAAAAQABAAAAAAQABAAABAAIAqAAIAFABQAAABABAAQAAABABAAQAAABAAABQAAAAAAABIAABXIBRAAIAAhXQAAgDACgCQABAAAAAAQABgBAAAAQABAAABAAQAAAAABAAIArAAIAEABQABABAAAAQAAABABAAQAAABAAABQAAAAAAABIAADnQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBABQgBAAAAAAgAC+EzQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBgBAAAAQgCgCAAgDIAAiFQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgDACIhKCBQgFAHgDACQgFACgEAAIghAAQgFAAgEgEQgEgEAAgFIAAjhQAAgDADgCQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAnAAIAEABQABABAAAAQABABAAAAQAAABAAABQABAAAAABIAACLQAAABAAABQAAAAAAABQAAAAAAAAQABAAAAAAIADgDIBOiHIAFgIQAEgCAEAAIAiAAQAFAAAEADQACAEAAAFIAADhQABADgCACQAAAAgBABQgBAAAAAAQgBAAAAABQgBAAAAAAgAleEzQgDAAgDgCQgBgCAAgDIAAiFQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgDACIhLCBQgDAHgFACQgDACgGAAIggAAQgFAAgEgEQgEgEAAgFIAAjhQAAgDADgCQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAnAAIAEABQABABAAAAQAAABABAAQAAABAAABQAAAAAAABIAACLQAAABAAABQAAAAABABQAAAAAAAAQABAAAAAAIADgDIBNiHIAGgIQADgCAGAAIAgAAQAFAAAEADQADAEABAFIAADhQgBADgBACQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAgAxAEzQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgCgCAAgDIAAi/Ig2AAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBQgCgBAAgDIAAgiQAAgDACgCIAEgBICjAAIAFABQADACgBADIAAAiQABADgDABIgFACIg0AAIAAC/QAAADgDACQAAAAgBABQAAAAgBAAQAAAAgBABQgBAAAAAAgARaDoQgDAAgCgCQgCgCgBgDIgGikQAAAAABgBQAAgBAAAAQAAgBABAAQAAgBABAAIAEgCIAqAAIAEACQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAIgGCkQAAADgDACQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAmrAqQgKgEgIgGQgIgGgFgJQgEgJgCgIIAAgCIAEgBIAcAAQADAAABADQACAKAHAEQAHADAJAAQAJAAAHgDQAHgEACgKQABgDADAAIAdAAIADABIAAACQgCAIgFAJQgEAJgHAGQgJAGgKAEQgLAEgNAAQgNAAgLgEgAN4glQgNgCgKgHQgKgHgGgMQgFgMAAgUIAAhgQAAgUAFgMQAGgMAKgHQAKgHANgCQANgCAOAAIA4AEQAGAAAAAFIAAAbIgCAEQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIg7AAQgKAAgEAEQgFAEAAAMIAAAaIBMAAQAAAAABAAQAAAAABABQAAAAABAAQABAAAAABIABAEIAAAbQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBAAQgBABAAAAQgBAAAAAAQgBAAAAAAIhMAAIAAAfQAAALAFAFQAEAEAKAAIA7AAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAIAAAcQAAAFgGABIgUACIgkABQgOAAgNgCgALbgnIgOgGQgIgEgFgGQgMgLgIgRQgGgSgBgaIAAgkQABgaAGgSQAIgSAMgKQAMgLAPgFQAPgEARAAQAPAAAMABIARAEIAEACQABAAAAAAQAAABABAAQAAABAAABQAAAAAAABIAAAcQAAAGgFAAIgBAAIgrgCQgIAAgHACQgGACgFAGQgFAFgDAKQgCAJAAAPIAAAkQAAAPACAJQADAKAFAFQAFAGAGACQAHACAIAAIArgCIABAAQAFAAAAAGIAAAcQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgEACIgRAEQgMABgPAAQgRAAgPgEgACjgnIgOgGQgHgEgGgGQgMgLgHgRQgHgSAAgaIAAgkQAAgaAHgSQAHgSAMgKQAMgLAPgFQAQgEARAAQAPAAAMABIAQAEIAEACQABAAAAAAQABABAAAAQAAABAAABQAAAAAAABIAAAcQABAGgGAAIgBAAIgrgCQgIAAgGACQgHACgEAGQgFAFgDAKQgDAJAAAPIAAAkQAAAPADAJQADAKAFAFQAEAGAHACQAGACAIAAIArgCIABAAQAGAAgBAGIAAAcQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAIgEACIgQAEQgMABgPAAQgRAAgQgEgAhxgoQgPgFgNgLIgKgNQgEgHgEgJQgDgJgBgKQgCgLAAgNIAAgiQAAgNACgLQABgKADgJIAIgQIAKgNQANgLAPgFQAQgFARAAQASAAAQAFQAPAFANALIAKANIAIAQQAEASABAZIAAAiQgBANgCALQgBAKgBAJQgEAJgEAHIgKANQgNALgPAFQgQAFgSAAQgRAAgQgFgAhrjJQgIAMAAAbIAAAiQAAAOACAJQADAKADAFQAKAMARAAQAKAAAHgDQAGgDAFgGQAEgFADgKQABgJAAgOIAAgiQAAgbgIgMQgFgFgGgDQgHgDgKAAQgRAAgKALgAt0gjIgngDQgIgCgEgDQgEgEAAgKIAAi+QAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAQABgBAAAAQABAAAAAAIB6AAIAEACQAAAAABABQAAAAAAAAQAAABAAABQAAAAAAABIAAAeQAAAAAAABQAAABAAAAQAAABAAAAQgBAAAAABIgEABIhOAAIAAAqIATAAQATAAARADQAQACANAIQAGADAFAGQAFAFAEAGQAGANAAAUIAAACQAAAKgBAIQgCAJgDAGQgEAHgFAFQgFAFgGAEQgNAIgQACQgRADgTAAgAt5hLIARAAQAOAAAIgCQAJgBAGgDQAFgEACgFQABgFAAgHIAAgCQAAgHgBgFQgCgFgFgDQgGgDgJgBIgngBgAxGgoQgPgFgMgLIgKgNQgFgHgDgJQgDgJgCgKQgBgLAAgNIAAgiQAAgNABgLQACgKADgJIAIgQIAKgNQAMgLAPgFQAQgFASAAQASAAAQAFQAPAFAMALIAKANIAIAQQAHASAAAZIAAAiQAAANgCALQgBAKgEAJQgDAJgFAHIgKANQgMALgPAFQgQAFgSAAQgSAAgQgFgAw/jJQgJAMAAAbIAAAiQAAAOACAJQADAKAEAFQAJAMASAAQAJAAAHgDQAHgDAEgGQAEgFADgKQACgJAAgOIAAgiQAAgbgJgMQgEgFgHgDQgHgDgJAAQgSAAgJALgAQjglIgFgCQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAipIgvAAIgFgBQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAIAAgeQAAgBABAAQAAgBAAgBQAAAAABAAQAAgBAAAAIAFgCICQAAIADACQABAAAAABQABAAAAAAQAAABAAABQAAAAAAABIAAAeQAAAAAAABQAAABAAAAQAAABgBAAQAAAAgBABIgDABIgvAAIAACpQAAAAgBABQAAABAAAAQAAABgBAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAgAJjglIgEgCIgCgDIgLgwIg6AAIgLAwIgCADIgEACIgpAAQgEAAAAgFIAAAAIAAgBIAri0QACgLAFgGQAGgGAGgEQAHgDAHgBIAPgBIAPABQAIABAGADQAGAEAFAGQAFAGADALIArC0IAAABIAAAAQABAFgGAAgAJKiCIgShTIgDgBQgDAAgBAEIgSBQIArAAgAGVglQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBQgBgBAAAAIAAieIgBgEIgEgDIgHgCIguAAIgIACIgDADIgCAEIAACeQAAAAAAABQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgmAAIgEgCQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiYQAAgMADgLQACgKAHgIQAGgIAMgEQANgFASAAIAxAAQATAAAMAFQAMAEAHAIQAGAIADAKQACALAAAMIAACYQAAAAAAABQAAABAAAAQgBABAAAAQAAABAAAAIgFACgAjyglIgDgBIgEgDIg6hgIAABeQAAAAAAABQAAABgBAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgmAAIgEgCQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAjMQAAgBAAAAQAAgBABgBQAAAAAAAAQABgBAAAAIAEgCIAmAAIAEACQAAAAABABQAAAAAAAAQABABAAABQAAAAAAABIAABcIBAheQACgEAEAAIAsAAQAFAAAAADIgBAFIhGBiIBGBoIABADQAAADgEAAgAmsglIgEgCIgCgDIgLgwIg6AAIgLAwIgCADIgEACIgoAAQgGAAAAgFIAAAAIABgBIAri0QADgLAFgGQAFgGAGgEQAGgDAIgBIAPgBIAPABQAHABAHADQAGAEAGAGQAFAGACALIArC0IAAABIAAAAQAAAFgEAAgAnEiCIgThTIgDgBQgDAAgBAEIgRBQIArAAgApuglIgEgCIgCgDIgkioIgBgDIgDgBQgDAAgBAEIgkCoIgCADIgEACIgpAAQgEAAgBgFIAAAAIABgBIAri0QADgLAEgGQAFgGAHgEQAGgDAIgBIAPgBIAPABQAHABAHADQAHAEAEAGQAFAGADALIArC0IABABIAAAAQAAAFgGAAgAOfkNQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAAgbQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIAbAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABIAAAbQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAABQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAgANgkNQAAAAgBAAQAAAAgBgBQAAAAgBAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAAgbQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABAAQABAAAAgBQABAAAAAAQABAAAAAAIAcAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABIAAAbQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115.6,-31,231.2,62);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AroDIICsrLIUlFGIiaLBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.5,-51.7,149,103.4);


(lib.Символ44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFMC3Qgai3Aai2ICUAAQBHC5hHC0gAnfC3QhHi0BHi5ICTAAQAbC2gbC3g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51.6,-18.4,103.3,36.8);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B11519").s().rr(-80,-18.4,160,36.8,18.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-18.4,160,36.8);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0794B3").s().p("AK/BmQgTgVAAgoIAAgjQAAgoAUgUQAUgUAjAAQAjAAAUAVQAUAVAAAmIAAAjQAAAogUAVQgUAVgjAAQgkAAgUgVgALagfQgJANAAAYIAAAjQAAAZAJANQAJAMAUAAQATAAAKgMQAJgNAAgZIAAgjQAAgYgJgNQgKgMgTAAQgUAAgJAMgAAABmQgTgVAAgoIAAgjQAAgoATgUQAUgUAjAAQAjAAAUAVQATAVAAAmIAAAjQAAAogTAVQgUAVgjAAQgkAAgTgVgAAZgfQgJANAAAYIAAAjQAAAZAJANQAKAMAUAAQATAAAJgMQAJgNAAgZIAAgjQAAgYgJgNQgJgMgTAAQgUAAgKAMgAo3BtQgOgNAAgbIAAhZQAAgcAOgNQAOgNAhAAQATAAAQACQASABABACQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAABIAAAQQAAABAAAAQAAABAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQgBAAAAAAIg2AAQgMAAgEAFQgEAFAAANIAAAaIBHAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABIAAATIgCAEIgDABIhHAAIAAAiQAAAMAEAGQAEAFAMAAIA2AAQAAAAABAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAARQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgCABgPACQgPACgWAAQghAAgOgOgArJBmQgVgUAAgnIAAgnQAAgdAMgSQALgRARgIQARgGASAAIAaABIARADQAEACAAAEIAAARQAAAGgFAAIgBAAQgYgCgQAAQgnAAAAAvIAAAnQAAAxAnAAIApgCQAFAAAAAFIAAARQAAAFgEABIgRADIgaACQghAAgVgVgAtpB6QgPgCgGgCQgEgDAAgJIAAijQAAgIADgEQAEgDASgBIAegBQBRAAAAA1IAAAFQAAANgGAJQgGALgMAFQAaALAAAdIAAAEQAAAdgUAOQgUAOgoAAgAteBcIAWABQAXAAALgGQAKgGAAgPIAAgEQAAgNgJgIQgHgHgQAAIgiAAgAtegsIAAAzIAiAAQAfAAAAgWIAAgEQAAgOgLgFQgKgGgZAAgANmB5IgEgBIgBgEIAAgdQAAgGAFAAIAXAAQAFAAAAAGIAAAdIgBAEIgEABgAJ4B5QgEAAgBgFIgmicQgBgEgDAAQgDAAgCAEIgmCcQAAAFgEAAIgdAAQgEAAAAgFIAAgBIArijQAHgaAeAAQAeAAAGAaIAsCkQAAAFgFAAgAHOB5QgDAAgBgEIgMgzIg9AAIgMA0IgCACIgDABIgcAAQgFAAAAgFIABgBIArijQAHgaAdAAQAeAAAHAaIArCkQAAAFgFAAgAG2AlIgUhQIgDgBQAAAAgBAAQgBABAAAAQgBAAAAABQAAAAAAABIgUBOIAuAAgAEYB5QgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAiOQAAgIgCgCQgCgDgGAAIg1AAQgHAAgCADQgCACAAAIIAACOIgBAEQgBABAAAAQgBAAAAAAQgBABgBAAQAAAAgBAAIgZAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAAAgBIAAiOQAAgYAMgLQAKgKAaAAIA1AAQAZAAALAKQALALAAAYIAACOIgBAEIgEACgAisB5QAAAAgBAAQgBAAAAgBQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAiyQAAgFADgBQADgCASgCIAjgBQAlAAAUAPQATAPAAAeIAAADQAAASgJAOQgIANgRAHQgRAHgZAAIgXgBIAABEQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAiNgrIAAA9IAXAAQAVAAAJgIQAKgHAAgOIAAgDQAAgPgJgIQgKgHgVAAgAj4B5QAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiOQAAgIgCgCQgDgDgGAAIg0AAQgIAAgBADQgDACAAAIIAACOIgBAEQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAAAAAIgaAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAiOQAAgYALgLQALgKAaAAIA0AAQAZAAAMAKQAKALAAAYIAACOIgBAEIgDACgANpBBIgEgCQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBIgFiDQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAIAZAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABIABADIgDCDQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAgAn7hYQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAAAAAAAQgBgBAAgBQAAAAAAgBIAAgXQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAAAXQAAABAAAAQAAABAAABQAAAAgBAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAgAowhYQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBIAAgXQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAIATAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQAAAAABABQAAAAAAAAQAAABABAAQAAABAAAAIAAAXQAAABAAAAQgBABAAABQAAAAAAAAQgBABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90,-12.3,180,24.7);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0794B3").s().p("ALrDPQgMgLAAgZIAAhSQAAgYAMgMQAMgMAeAAQARAAAPABQAPACACABIAAAEIAAAPIgBADQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgwAAQgLAAgEAFQgEAEAAALIAAAaIBAAAIADABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAIAAARQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAIgDACIhAAAIAAAeQAAAMAEAEQAEAFALAAIAwAAIADABIABADIAAAPIgBAEIgPADQgNACgUAAQgeAAgMgNgAHRDPQgNgLAAgZIAAhSQAAgYANgMQAMgMAeAAQAQAAAPABQAPACACABIABAEIAAAPIgBADQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgwAAQgKAAgFAFQgEAEAAALIAAAaIBAAAIAEABIABADIAAARIgBADQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIhAAAIAAAeQAAAMAEAEQAFAFAKAAIAwAAIAEABIABADIAAAPIgBAEIgPADQgNACgUAAQgeAAgMgNgAFDDaQgPgBgEgCQgEgDAAgIIAAiUQAAgHADgDQADgDAQgBIAcgBQBIAAAAAwIAAAEQAAANgGAJQgFAJgLAFQAXAKAAAZIAAAEQAAAagRANQgSANgkAAgAFMDAIAUAAQAVAAAJgFQAJgFAAgOIAAgDQAAgMgHgGQgHgHgPAAIgeAAgAFMBEIAAAwIAeAAQAcAAAAgWIAAgDQAAgNgJgFQgJgFgWAAgAAeDPQgNgLAAgZIAAhSQAAgYANgMQAMgMAeAAQAQAAAPABQAPACACABIABAEIAAAPIgBADQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgwAAQgLAAgEAFQgEAEAAALIAAAaIBAAAIAEABIABADIAAARIgBADQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIhAAAIAAAeQAAAMAEAEQAEAFALAAIAwAAIAEABIABADIAAAPIgBAEIgPADQgNACgUAAQgeAAgMgNgAhjDJQgTgSAAgkIAAgiQAAgcAKgPQALgRAPgGQAOgGARAAIAXABQAMACADABQAEABAAAEIAAAQQAAAFgFAAIglgCQgiAAAAAsIAAAiQAAAtAiAAIAlgCQAFAAAAAEIAAAQQAAAEgEABIgmAFQgeAAgSgTgAktDaQgPgBgEgCQgEgDAAgIIAAiUQAAgHADgDQADgDAQgBIAcgBQBIAAAAAwIAAAEQAAANgGAJQgFAJgLAFQAXAKAAAZIAAAEQAAAagRANQgSANgkAAgAkkDAIAUAAQAUAAAKgFQAJgFAAgOIAAgDQAAgMgHgGQgHgHgPAAIgeAAgAkkBEIAAAwIAeAAQAcAAAAgWIAAgDQAAgNgJgFQgJgFgWAAgArXDaQgQgBgCgCQgDgCAAgEIAAihIABgEIAEgBIAXAAIADABIACAEIAAA7IAVgBQAhAAARAOQARAOAAAbIAAAEQAAASgHAMQgIAMgPAGQgPAHgWAAgArLCGIAAA6IAVAAQASAAAIgGQAJgHAAgOIAAgEQAAgPgJgGQgIgGgSAAgAttDaQgQgBgDgCQgCgCAAgEIAAiiQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIBmAAIAEACIABADIAAASQAAAFgFAAIhKAAIAAAlIAVgBQAhAAASAOQARAOAAAbIAAAEQAAASgIAMQgHAMgQAGQgPAHgWAAgAtiCGIAAA6IAVAAQATAAAIgGQAJgHAAgOIAAgEQAAgPgJgGQgJgGgSAAgANoDaQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgBgEIAAgaQAAgEAEAAIAVAAQAFAAAAAEIAAAaQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAgAJQDaQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAiiQAAgEACgBQADgCAQgCIAggBQAhAAASAOQARANAAAbIAAACQAAASgIANQgIAMgPAGQgPAGgWAAIgVgBIAAA+IgBADQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAgAJsBFIAAA4IAVAAQATAAAIgGQAJgHAAgPIAAgCQAAgOgJgHQgIgGgTAAgACdDaQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBIgBgDIAAiiQAAgEACgBQADgCAQgCIAggBQAhAAASAOQARANAAAbIAAACQAAASgIANQgIAMgPAGQgPAGgWAAIgVgBIAAA+QAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAgAC5BFIAAA4IAVAAQATAAAIgGQAJgHAAgPIAAgCQAAgOgJgHQgIgGgTAAgAmyDaQgEAAAAgFIgiiNQgCgEgDAAQAAAAgBAAQAAABgBAAQAAABgBAAQAAABAAABIgiCNQgBAFgEAAIgYAAQgFAAAAgFIABgBIAmiTQAGgYAaAAQAbAAAGAYIAnCUQAAAFgEAAgApWDaQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAimQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAIADgBIAYAAIADABQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAACmQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDACgANrCnIgDgBIgCgEIgDh3QAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAIAWAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAIgEB3IgBAEIgEABgAMWgaQgWgWAAgrIAAgqQAAggAMgUQAMgTASgIQASgHAUAAIAcABIATAEQAEACAAAEIAAATQAAAGgGAAIAAAAQgbgCgRAAQgpAAAAA0IAAAqQAAA1ApAAIAsgCQAGAAAAAGIAAATQAAAEgEACIgTAEIgcABQgkAAgWgWgAJxgSQgPgPAAgdIAAhjQAAgeAPgOQAPgOAkAAQAUAAASACQATACABABIABAFIAAASIgBAEQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAIg6AAQgNAAgFAFQgEAGAAANIAAAeIBMAAQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAAAABABQAAABAAAAQAAABAAAAIAAAVQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAIhMAAIAAAlQAAANAEAGQAFAFANAAIA6AAQAAAAABAAQABAAAAABQABAAAAAAQABABAAAAIABAEIAAASQAAABAAABQAAABAAAAQAAABAAAAQAAAAgBABIgSADQgQACgYAAQgkAAgPgOgAEFgHIgUgFQgDgCAAgCIAAgSQAAgFAFAAIAAAAQAoAEAPAAQAQAAAIgHQAHgHAAgQIAAgGQAAgdgaAAIgyAAQgFAAAAgFIAAgSQAAgGAFAAIAyAAQANAAAHgGQAGgHAAgOIAAgFQAAgbgfAAIg3AEQgFAAAAgFIAAgSQAAgCACgCIAWgFQASgDASAAQAiAAATAPQASAOAAAdIAAAFQAAAdgYANQALAGAHAMQAGALAAAOIAAAGQAAAdgTAQQgTAQghAAQgTAAgSgDgAhygFQgTgCgDgCQgDgCAAgFIAAjEIABgEQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIB7AAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAIABAEIAAAXQAAAFgGAAIhZAAIAAAsIAZAAQAoAAAVAQQATARAAAhIAAAFQAAAVgHAPQgKAPgSAHQgTAHgaAAgAhkhqIAABEIAZACQAXAAAKgIQAKgJAAgQIAAgFQAAgSgLgIQgKgHgWAAgAlugFQgTgCgDgCQgEgCAAgFIAAjDQAAgBAAAAQAAgBABgBQAAAAAAAAQABgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAdAAIADACQABAAAAABQAAAAAAAAQABABAAABQAAAAAAABIAABHIAZAAQAoAAAVAQQAVARAAAhIAAAFQAAAVgJAPQgKAPgSAHQgTAHgaAAgAlghqIAABEIAZACQAWAAALgIQAJgJAAgQIAAgFQAAgSgKgIQgKgHgWAAgAoXgaQgWgWAAgrIAAgqQAAggANgUQAMgTASgIQASgHAUAAIAcABIASAEQAFACAAAEIAAATQAAAGgGAAIgBAAQgagCgRAAQgqAAAAA0IAAAqQAAA1AqAAIAsgCQAGAAAAAGIAAATQAAAEgFACIgSAEIgcABQgkAAgXgWgAq7gSQgPgPAAgdIAAhjQAAgeAPgOQAPgOAkAAQAUAAASACQASACACABQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABIAAASQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAIg6AAQgNAAgEAFQgFAGAAANIAAAeIBNAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAABABAAQAAAAAAABQAAABABAAQAAABAAAAIAAAVQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIhNAAIAAAlQAAANAFAGQAEAFANAAIA6AAQABAAAAAAQABAAABABQAAAAABAAQAAABABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAASQAAABAAABQAAABAAAAQAAABgBAAQAAAAAAABIgSADQgQACgYAAQgkAAgPgOgAtmgFQgRgCgGgCQgFgEAAgJIAAizQAAgIAEgEQAEgEATgBIAhgBQBYAAAAA5IAAAGQAAAOgHAMQgHAMgNAFQAcAMAAAfIAAAFQAAAegVAQQgVAPgsAAgAtaglIAXABQAZAAALgHQALgGAAgQIAAgEQAAgPgJgIQgIgIgRAAIgkAAgAtai6IAAA5IAkAAQAhAAAAgaIAAgFQAAgOgLgGQgLgHgbAAgAIWgGQAAAAgBAAQgBgBAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAhXIhRAAIAABXIgBAEQgBAAAAABQgBAAAAAAQgBAAgBABQAAAAgBAAIgcAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAjIQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAcAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABABIABADIAABPIBRAAIAAhPQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAQABAAAAAAIAdAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABABIABADIAADIIgBAEQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAAAAAgACqgGIgEgCQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAiOQAAgBAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAABIg/CKQgDAHgEABQgEACgHAAIgcAAQgFAAgDgDQgEgEAAgFIAAjCQAAgFAGAAIAYAAQAGAAAAAFIAACWQAAAAAAABQAAAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAIBCiSIAFgHQADgCAFAAIAfAAQAEAAADADQAEAEAAAFIAADBQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAg");
	this.shape.setTransform(-0.1,-1.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90,-23.5,180,44.1);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.asgasdga();
	this.instance.parent = this;
	this.instance.setTransform(-47,-22.6,0.595,0.595);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-47,-22.6,94,45.2);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.fff();
	this.instance.parent = this;
	this.instance.setTransform(-228,-80.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-228,-80.5,456,161);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.w256h2561380453915MouseOptions256x256321();
	this.instance.parent = this;
	this.instance.setTransform(-14.4,-14.4,0.112,0.112);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.4,-14.4,28.8,28.8);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah9BfQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBgBAAAAIAAgWIhjAAIAAAWIgBADQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgMAAIgDgBIgBgDIAAgkQAAgEAEAAIAHAAIAliAQAEgRASAAQASAAAEAQIAmCBIAGAAQAEAAAAAEIAAAkIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAgAiMAzIgjh8QgBgEgDAAQgDAAgBAEIgiB8IBNAAgAK0BFQgMgBgCgCQgCgCAAgEIAAiVQAAgEAEAAIAMAAQAEAAAAAEIAABBIAYgBQBAAAgBAtIAAAEQABAuhAAAgAK4gHIAAA7IAYABQAYAAAKgHQAKgHAAgPIAAgEQAAgQgKgFQgKgHgYAAgAEpBFQgMgBgBgCQgDgCAAgEIAAiVQAAgEAFAAIALAAQAEAAABAEIAABBIAXgBQBAAAAAAtIAAAEQAAAuhAAAgAEugHIAAA7IAXABQAYAAAKgHQAKgHAAgPIAAgEQAAgQgKgFQgKgHgYAAgAlbA8QgMgKAAgVIAAhSQAAgWAMgJQAMgKAXAAIAlABIAHAAIABACIAAAMQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgrAAQgNAAgHAEQgGADgBAQIAAAeIBEAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABIABADIAAAIIgBADIgDABIhEAAIAAAjQABAOAFAEQAFAFAQAAIArAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAALIgBADQAAABgNAAIgfAAQgYAAgLgKgAneBFQgMgBgCgCQgCgCAAgEIAAiQIABgFQABgBAAAAQAAgBABAAQAAAAABAAQAAgBAAAAIAmgCQBBAAAAAqIAAAEQAAAMgHAJQgFAJgMAEQAMAEAGAKQAGAHABANIAAAEQAAAuhAAAgAnaA0IAYABQAYAAAKgHQAJgHABgPIAAgEQgBgaghAAIgiAAgAnahNIAAA3IAiAAQAgAAABgaIAAgEQAAgNgKgGQgKgGgZAAgAH1BFQgeAAAAgcIAAiBQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIADgCIALAAIADACIABADIAACBQAAAGACACQACACAGAAIAuAAIAAiLQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIAMAAIADACIABADIAACLIAtAAQAGAAACgCQACgCAAgGIAAiBQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAIALAAQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAABIABADIAACBQAAAcgeAAgAGlBFQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAiZQAAgEAEAAIAMAAQAEAAAAAEIAACZIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAgBAAgADpBFQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAAAAAgBIgCgDIAAiAIAAgBIgBABIggBBIgDADIgFABIgLAAQgDAAgCgBQgCgBgCgDIgYgwIgIgRIgBABIAACAIgBADIgDACIgLAAIgDgCQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIAAiWQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAABgBQAAAAABAAQAAAAABgBQAAAAABAAIAOAAQAFAAADAEIAkBMQAAAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQABAAAAAAQABgBAAAAQAAAAAAAAQABgBAAAAIAlhMQABgEAFAAIAPAAQAAAAABAAQAAABABAAQAAAAABAAQABABAAAAQABABAAAAQAAABAAAAQABABAAABQAAAAAAABIAACWQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAALBFIgDgBIgBgDIAAh/IAAgBIgBABIhCB/QgCAEgFAAIgNAAQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBQAAAAAAgBIAAiXQAAgEAEAAIAMAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABACIAAB/IABABIBDh/IACgEIAGgBIAMAAQABAAAAAAQABABAAAAQABAAAAAAQABABABAAQAAABAAAAQABABAAAAQAAAAAAABQABABAAAAIAACZQAAABgBAAQAAABAAAAQgBAAgBABQAAAAgBAAgAoWBFIgCgBIgDgIIgNgtIg5AAIgOAzIgCACIgCABIgNAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAgBIAqiNQAEgRARAAQASAAAFAQIAoCOIABABQAAAEgEAAgAosgBIgQg3IgEgSIgBgBIgBgBIgDgBIgCABIgBABIgUBKIAwAAgAqrBFQAAAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAhHIhMAAIAABHIgBADIgCACIgMAAIgDgCQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIAAiYQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAIADgCIAMAAIACACIABADIAAA/IBMAAIAAg/QAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIALAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAACYQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78.4,-9.5,156.8,19.2);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(0.2,1,1).p("AAaAAQAAALgIAHQgHAIgLAAQgKAAgHgIQgIgHAAgLQAAgKAIgHQAHgIAKAAQALAAAHAIQAIAHAAAKg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIgHQADgFAFAFQAHAFACAMQgIgJgJgIg");
	this.shape_1.setTransform(1,-1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C8EFEF").s().p("AgRASQgHgHgBgLQABgKAHgHQAHgHAKgBQALABAHAHQAHAHABAKQgBALgHAHQgHAHgLABQgKgBgHgHgAAAgRQALAJAHAIQgBgMgIgFQgDgDgDAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.6,-3.6,7.2,7.2);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa();
	this.instance.parent = this;
	this.instance.setTransform(-344.5,-78);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-344.5,-78,689,156);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#E8FFFA","#C4FFFF"],[0,1],0,324.8,0,-324.8).s().p("EgZmAwfMAAAhg9MAzNAAAMAAABg9g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-164,-310.3,328,620.8);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ggg();
	this.instance.parent = this;
	this.instance.setTransform(-293.5,-101.1,0.364,0.553);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-293.5,-101.1,586.9,202.3);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ggg();
	this.instance.parent = this;
	this.instance.setTransform(-259.5,-89.4,0.322,0.489);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-259.5,-89.4,519,178.9);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sss();
	this.instance.parent = this;
	this.instance.setTransform(-75,-90.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75,-90.5,150,181);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dddd();
	this.instance.parent = this;
	this.instance.setTransform(-9,-6.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9,-6.5,18,13);


(lib.Анимация2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFCC00").ss(3,1,1).p("AAN88Qg+PfgyG9Qg0HIAdG7QAdHDBmGjQA/D8A9D4");
	this.shape.setTransform(-16.1,-27.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.9,-214,29.8,373.6);


(lib.Символ58 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_5 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(5).call(this.frame_5).wait(5));

	// Слой 1
	this.instance = new lib.Символ57();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.242,0.242);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.5},4).wait(1).to({alpha:0},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.3,-31.5,139.1,41.5);


(lib.Символ56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 55
	this.instance = new lib.Символ55();
	this.instance.parent = this;
	this.instance.setTransform(-0.4,0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.09,scaleY:1.09,y:-4.7},0).wait(1));

	// Символ 53
	this.instance_1 = new lib.Символ53();
	this.instance_1.parent = this;

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("Az5ErQhFAAAAhFIAAnLQAAhFBFgBMAnzAAAQBFABAABFIAAHLQAABFhFAAg");
	this.shape.setTransform(0,-5.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-123.6,-27.6,247.2,55.2);


(lib.Символ54 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ56();
	this.instance.parent = this;
	this.instance.setTransform(2.4,0);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-132,-35.6,268.8,63.2);


(lib.Символ52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ51();
	this.instance.parent = this;
	this.instance.setTransform(0,-0.1,1.114,1.114,0,0,0,0,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:0,scaleX:1.09,scaleY:1.09,y:0},0).wait(1).to({scaleX:1.07,scaleY:1.07},0).wait(1).to({scaleX:1.05,scaleY:1.05},0).wait(1).to({scaleX:1.03,scaleY:1.03},0).wait(1).to({scaleX:1.02,scaleY:1.02},0).wait(1).to({scaleX:1.01,scaleY:1.01},0).wait(1).to({scaleX:1,scaleY:1},0).wait(1).to({scaleX:1,scaleY:1},0).wait(1).to({scaleX:0.99,scaleY:0.99},0).wait(1).to({scaleX:0.99,scaleY:0.99},0).wait(1).to({scaleX:0.98,scaleY:0.98},0).wait(1).to({scaleX:0.98,scaleY:0.98},0).wait(1).to({scaleX:0.97,scaleY:0.97},0).wait(1).to({scaleX:0.97,scaleY:0.97},0).wait(1).to({scaleX:0.97,scaleY:0.97},0).wait(1).to({scaleX:0.96,scaleY:0.96},0).wait(1).to({scaleX:0.96,scaleY:0.96},0).wait(1).to({scaleX:0.96,scaleY:0.96},0).wait(1).to({regY:-0.1,scaleX:0.96,scaleY:0.96,y:-0.1},0).wait(1).to({regY:0,scaleX:0.98,scaleY:0.98,y:0},0).wait(1).to({scaleX:1,scaleY:1},0).wait(1).to({scaleX:1.02,scaleY:1.02},0).wait(1).to({scaleX:1.03,scaleY:1.03},0).wait(1).to({scaleX:1.04,scaleY:1.04},0).wait(1).to({scaleX:1.05,scaleY:1.05},0).wait(1).to({scaleX:1.06,scaleY:1.06},0).wait(1).to({scaleX:1.07,scaleY:1.07},0).wait(1).to({scaleX:1.08,scaleY:1.08},0).wait(1).to({scaleX:1.08,scaleY:1.08},0).wait(1).to({scaleX:1.09,scaleY:1.09},0).wait(1).to({scaleX:1.09,scaleY:1.09},0).wait(1).to({scaleX:1.1,scaleY:1.1},0).wait(1).to({scaleX:1.1,scaleY:1.1},0).wait(1).to({scaleX:1.1,scaleY:1.1},0).wait(1).to({scaleX:1.1,scaleY:1.1},0).wait(1).to({scaleX:1.11,scaleY:1.11},0).wait(1).to({scaleX:1.11,scaleY:1.11},0).wait(1).to({scaleX:1.11,scaleY:1.11},0).wait(1).to({regY:-0.1,scaleX:1.11,scaleY:1.11,y:-0.1},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.8,-34.5,257.6,69.1);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ52();
	this.instance.parent = this;
	this.instance.setTransform(-13.1,-128.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141.9,-162.7,257.6,69.1);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A81B17").s().p("AB/FGIgZj1IgpArIguCsIhXgXICUouIBYAYIhBD0IC2jVIBWAXIi8DXIAmFWgAkHDlQghgJgWgQQgVgOgMgZQgZgtARhDIBPkiQAShEAsgbQAWgNAbgDQAbgDAhAJQBBARAYAuQAMAXABAcQADAdgJAhIhOEiQgJAigQAXQgQAYgVANQgYAPgaACIgOAAQgWAAgYgGgAinkDQgQAJgIAeIhREuQgIAeAJAPQAJAQAVAGQAUAGAQgKQAQgJAIgeIBRktQAJgfgKgQQgJgPgUgGQgIgCgIAAQgLAAgKAGg");
	this.shape.setTransform(71.2,-70.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.instance = new lib.Символ48();
	this.instance.parent = this;
	this.instance.setTransform(71.2,-71.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.3,-122.9,149,103.4);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ44();
	this.instance.parent = this;
	this.instance.setTransform(-0.3,0);

	this.instance_1 = new lib.Символ42();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-18.4,160,36.9);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ46();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-15},19,cjs.Ease.get(1)).to({rotation:15},37,cjs.Ease.get(1)).to({rotation:0},34,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-18.4,160,36.9);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ45();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-18.5,160,36.9);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ40();
	this.instance.parent = this;
	this.instance.setTransform(-12.6,1.5,1.409,1.409);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-49,alpha:1},9,cjs.Ease.get(1)).wait(36).to({y:1.5,alpha:0},9).wait(36));

	// Слой 1
	this.instance_1 = new lib.Символ39();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-12.6,-48.9,1.409,1.409);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:-99.4,alpha:0},9,cjs.Ease.get(1)).wait(36).to({y:-48.9,alpha:1},9).wait(36));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139.4,-82.1,253.6,101.1);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ34();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-6.8},14,cjs.Ease.get(0.98)).to({y:0},7,cjs.Ease.get(0.98)).wait(1).to({y:-6.8},14,cjs.Ease.get(0.98)).to({y:0},7,cjs.Ease.get(0.98)).wait(32));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.4,-14.4,28.8,28.8);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ30();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.7,-2.7,5.4,5.4);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ35();
	this.instance.parent = this;
	this.instance.setTransform(96.4,-0.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ33();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78.4,-15,189.2,28.8);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.servak = new lib.Символ58();
	this.servak.parent = this;
	this.servak.setTransform(6,17.2);

	this.timeline.addTween(cjs.Tween.get(this.servak).wait(1));

	// Слой 1
	this.instance = new lib.Символ59();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-103.4,-36.5,206.8,73);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.oblako2 = new lib.Символ26();
	this.oblako2.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.oblako2).wait(1).to({y:-1.7},0).wait(1).to({y:-3.2},0).wait(1).to({y:-4.6},0).wait(1).to({y:-5.9},0).wait(1).to({y:-7.1},0).wait(1).to({y:-8.1},0).wait(1).to({y:-9.1},0).wait(1).to({y:-10},0).wait(1).to({y:-10.7},0).wait(1).to({y:-11.4},0).wait(1).to({y:-12},0).wait(1).to({y:-12.5},0).wait(1).to({y:-13},0).wait(1).to({y:-13.4},0).wait(1).to({y:-13.7},0).wait(1).to({y:-14},0).wait(1).to({y:-14.3},0).wait(1).to({y:-14.5},0).wait(1).to({y:-14.8},0).wait(1).to({y:-14.9},0).wait(1).to({y:-15.1},0).wait(1).to({y:-15.2},0).wait(1).to({y:-15.4},0).wait(1).to({y:-15.5},0).wait(1).to({y:-15.6},0).wait(1).to({y:-15.7},0).wait(1).to({y:-15.8},0).wait(1).to({y:-15.9},0).wait(1).to({y:-16},0).wait(1).to({y:-14.4},0).wait(1).to({y:-12.9},0).wait(1).to({y:-11.5},0).wait(1).to({y:-10.3},0).wait(1).to({y:-9.1},0).wait(1).to({y:-8.1},0).wait(1).to({y:-7.1},0).wait(1).to({y:-6.3},0).wait(1).to({y:-5.5},0).wait(1).to({y:-4.8},0).wait(1).to({y:-4.2},0).wait(1).to({y:-3.7},0).wait(1).to({y:-3.2},0).wait(1).to({y:-2.8},0).wait(1).to({y:-2.4},0).wait(1).to({y:-2.1},0).wait(1).to({y:-1.8},0).wait(1).to({y:-1.6},0).wait(1).to({y:-1.4},0).wait(1).to({y:-1.2},0).wait(1).to({y:-1},0).wait(1).to({y:-0.9},0).wait(1).to({y:-0.7},0).wait(1).to({y:-0.6},0).wait(1).to({y:-0.5},0).wait(1).to({y:-0.4},0).wait(1).to({y:-0.3},0).wait(1).to({y:-0.2},0).wait(1).to({y:-0.1},0).wait(1).to({y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-103.4,-36.5,206.8,73);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ19();
	this.instance.parent = this;
	this.instance.setTransform(0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-194},64,cjs.Ease.get(1)).to({x:0.1},65,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-293.4,-101.1,586.9,202.3);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleY:1.03,y:4.7},0).wait(1).to({scaleY:1.06,y:9},0).wait(1).to({scaleY:1.09,y:12.8},0).wait(1).to({scaleY:1.11,y:16.2},0).wait(1).to({scaleY:1.13,y:19.2},0).wait(1).to({scaleY:1.15,y:21.8},0).wait(1).to({scaleY:1.16,y:24.1},0).wait(1).to({scaleY:1.18,y:26},0).wait(1).to({scaleY:1.19,y:27.7},0).wait(1).to({scaleY:1.2,y:29.2},0).wait(1).to({scaleY:1.21,y:30.5},0).wait(1).to({scaleY:1.21,y:31.6},0).wait(1).to({scaleY:1.22,y:32.5},0).wait(1).to({scaleY:1.22,y:33.3},0).wait(1).to({scaleY:1.23,y:34},0).wait(1).to({scaleY:1.23,y:34.6},0).wait(1).to({scaleY:1.24,y:35.1},0).wait(1).to({scaleY:1.24,y:35.6},0).wait(1).to({scaleY:1.24,y:36},0).wait(1).to({scaleY:1.24,y:36.4},0).wait(1).to({scaleY:1.25,y:36.7},0).wait(1).to({scaleY:1.25,y:37},0).wait(1).to({scaleY:1.25,y:37.3},0).wait(1).to({scaleY:1.25,y:37.5},0).wait(1).to({scaleY:1.22,y:32.9},0).wait(1).to({scaleY:1.19,y:28.8},0).wait(1).to({scaleY:1.17,y:25.1},0).wait(1).to({scaleY:1.15,y:21.8},0).wait(1).to({scaleY:1.13,y:18.9},0).wait(1).to({scaleY:1.11,y:16.3},0).wait(1).to({scaleY:1.1,y:14},0).wait(1).to({scaleY:1.08,y:12.1},0).wait(1).to({scaleY:1.07,y:10.4},0).wait(1).to({scaleY:1.06,y:8.9},0).wait(1).to({scaleY:1.05,y:7.6},0).wait(1).to({scaleY:1.04,y:6.5},0).wait(1).to({scaleY:1.04,y:5.5},0).wait(1).to({scaleY:1.03,y:4.7},0).wait(1).to({scaleY:1.03,y:3.9},0).wait(1).to({scaleY:1.02,y:3.3},0).wait(1).to({scaleY:1.02,y:2.7},0).wait(1).to({scaleY:1.01,y:2.3},0).wait(1).to({scaleY:1.01,y:1.8},0).wait(1).to({scaleY:1.01,y:1.4},0).wait(1).to({scaleY:1.01,y:1.1},0).wait(1).to({scaleY:1.01,y:0.8},0).wait(1).to({scaleY:1,y:0.5},0).wait(1).to({scaleY:1,y:0.2},0).wait(1).to({scaleY:1,y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-259.5,-89.4,519,178.9);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ9();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75,-90.5,150,181);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 1
	this.instance = new lib.Символ7();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({rotation:180},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9,-6.5,18,13);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ36();
	this.instance.parent = this;
	this.instance.alpha = 0.48;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-228,-80.5,456,161);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ24();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-164,-310.3,328,620.8);


(lib.s = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ4();
	this.instance.parent = this;
	this.instance.setTransform(-62,182.9,0.477,0.477);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-1148.4},99).wait(18).to({x:-62},0).to({x:-1148.4},117).to({_off:true},51).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ4();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:-1148.4},239).wait(47));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-228,-80.5,456,301.8);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_5 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(5).call(this.frame_5).wait(5));

	// Слой 1
	this.instance = new lib.Символ47();
	this.instance.parent = this;
	this.instance.setTransform(-71.2,71.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},4).wait(1).to({alpha:0},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.5,-51.7,149,103.4);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ38();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,-0.1,1,1,0,0,0,-12.7,-31.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:-12.6,regY:-31.6,scaleX:0.83,scaleY:0.83,x:0,y:0},11,cjs.Ease.get(1)).to({regX:-12.7,regY:-31.7,scaleX:1,scaleY:1,x:-0.1,y:-0.1},13,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-126.8,-50.5,253.6,101.1);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ31();
	this.instance.parent = this;
	this.instance.alpha = 0.609;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:10.6},21,cjs.Ease.get(0.94)).to({x:0},23,cjs.Ease.get(0.94)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.7,-2.7,5.4,5.4);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ak0EEIAAoGQCpBeB0hZQByBbC5hhIAhIHg");
	mask.setTransform(15.8,-8.2);

	// Слой 2 - копия: 2
	this.instance = new lib.Символ32();
	this.instance.parent = this;
	this.instance.setTransform(24,0.2);
	this.instance._off = true;

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(58).to({_off:false},0).to({x:39.4,y:-51.8},69,cjs.Ease.get(0.97)).to({_off:true},1).wait(16));

	// Слой 2 - копия: 2
	this.instance_1 = new lib.Символ32();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,12.2);
	this.instance_1._off = true;

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(20).to({_off:false},0).to({x:3.4,y:-43.8},69,cjs.Ease.get(0.97)).to({_off:true},1).wait(54));

	// Слой 2 - копия
	this.instance_2 = new lib.Символ32();
	this.instance_2.parent = this;
	this.instance_2.setTransform(24,0.2);
	this.instance_2._off = true;

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(27).to({_off:false},0).to({x:39.4,y:-51.8},69,cjs.Ease.get(0.97)).to({_off:true},1).wait(47));

	// Слой 2
	this.instance_3 = new lib.Символ32();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,12.2);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:3.4,y:-43.8},69,cjs.Ease.get(0.97)).to({_off:true},1).wait(74));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.7,9.5,5.4,5.4);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.oblako1 = new lib.Символ23();
	this.oblako1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.oblako1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-103.4,-36.5,206.8,73);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ20();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-20},34).to({y:0},50).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-293.4,-101.1,586.9,202.3);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 8
	this.rot = new lib.Символ8();
	this.rot.parent = this;
	this.rot.setTransform(-17,58.5);

	this.timeline.addTween(cjs.Tween.get(this.rot).wait(1));

	// Слой 4
	this.ok = new lib.Символ49();
	this.ok.parent = this;
	this.ok.setTransform(0.5,-29,1,1,0,0,0,0,9.8);

	this.timeline.addTween(cjs.Tween.get(this.ok).wait(1));

	// Символ 10
	this.instance = new lib.Символ10();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75,-90.5,150,181);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:30,x:-2.9,y:30},0).wait(1).to({x:-5.7},0).wait(1).to({x:-8.4},0).wait(1).to({x:-10.9},0).wait(1).to({x:-13.4},0).wait(1).to({x:-15.7},0).wait(1).to({x:-17.9},0).wait(1).to({x:-20},0).wait(1).to({x:-22},0).wait(1).to({x:-23.9},0).wait(1).to({x:-25.7},0).wait(1).to({x:-27.4},0).wait(1).to({x:-29},0).wait(1).to({x:-30.5},0).wait(1).to({x:-32},0).wait(1).to({x:-33.4},0).wait(1).to({x:-34.7},0).wait(1).to({x:-35.9},0).wait(1).to({x:-37.1},0).wait(1).to({x:-38.2},0).wait(1).to({x:-39.3},0).wait(1).to({x:-40.3},0).wait(1).to({x:-41.2},0).wait(1).to({x:-42.1},0).wait(1).to({x:-42.9},0).wait(1).to({x:-43.7},0).wait(1).to({x:-44.5},0).wait(1).to({x:-45.2},0).wait(1).to({x:-45.8},0).wait(1).to({x:-46.4},0).wait(1).to({x:-47},0).wait(1).to({x:-47.5},0).wait(1).to({x:-48},0).wait(1).to({x:-48.5},0).wait(1).to({x:-48.9},0).wait(1).to({x:-49.3},0).wait(1).to({x:-49.7},0).wait(1).to({x:-50},0).wait(1).to({x:-50.3},0).wait(1).to({x:-50.6},0).wait(1).to({x:-50.9},0).wait(1).to({x:-51.1},0).wait(1).to({x:-51.3},0).wait(1).to({regY:0,x:-51.5,y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-259.5,-89.4,519,178.9);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 - копия
	this.instance = new lib.Символ29();
	this.instance.parent = this;
	this.instance.setTransform(16.7,-19.1,0.75,0.75);

	this.instance_1 = new lib.Символ29();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-37.1,-8.3,2,2);

	this.instance_2 = new lib.Символ29();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-16.7,-8.3,0.824,0.824);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 2
	this.instance_3 = new lib.Символ29();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-46.7,-22.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Слой 1
	this.instance_4 = new lib.Символ28();
	this.instance_4.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-344.5,-78,689,156);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Растровое изображение 5
	this.man2 = new lib.Символ18();
	this.man2.parent = this;
	this.man2.setTransform(-17,89,1,1,0,0,0,-17,89);

	this.timeline.addTween(cjs.Tween.get(this.man2).wait(1).to({regX:0,regY:0,rotation:-0.8,x:-1.2,y:-0.2},0).wait(1).to({rotation:-1.8,x:-2.8,y:-0.5},0).wait(1).to({rotation:-3.3,x:-5.1,y:-0.8},0).wait(1).to({rotation:-5,x:-7.9,y:-1.1},0).wait(1).to({rotation:-6.9,x:-10.8,y:-1.4},0).wait(1).to({rotation:-8.5,x:-13.3,y:-1.5},0).wait(1).to({rotation:-9.7,x:-15.2,y:-1.6},0).wait(1).to({rotation:-10.6,x:-16.6},0).wait(1).to({rotation:-11.2,x:-17.6},0).wait(1).to({rotation:-11.6,x:-18.3},0).wait(1).to({rotation:-12,x:-18.8},0).wait(1).to({rotation:-12.2,x:-19.2},0).wait(1).to({rotation:-12.4,x:-19.5},0).wait(1).to({rotation:-12.6,x:-19.8},0).wait(1).to({rotation:-12.8,x:-20},0).wait(1).to({rotation:-12.9,x:-20.3,y:-1.5},0).wait(1).to({rotation:-13.1,x:-20.5},0).wait(1).to({rotation:-13.2,x:-20.7},0).wait(1).to({rotation:-13.4,x:-21},0).wait(1).to({rotation:-13.6,x:-21.3},0).wait(1).to({rotation:-13.8,x:-21.6},0).wait(1).to({rotation:-14.1,x:-22.1},0).wait(1).to({rotation:-14.5,x:-22.7,y:-1.4},0).wait(1).to({regX:-16.9,regY:89,rotation:-15,x:-16.8,y:89},0).wait(1).to({regX:0,regY:0,rotation:-14.3,x:-22.6,y:-1.4},0).wait(1).to({rotation:-13.6,x:-21.3,y:-1.5},0).wait(1).to({rotation:-12.6,x:-19.9},0).wait(1).to({rotation:-11.6,x:-18.2,y:-1.6},0).wait(1).to({rotation:-10.3,x:-16.2},0).wait(1).to({rotation:-8.9,x:-13.9,y:-1.5},0).wait(1).to({rotation:-7.3,x:-11.4,y:-1.4},0).wait(1).to({rotation:-5.5,x:-8.7,y:-1.2},0).wait(1).to({rotation:-3.7,x:-5.8,y:-0.9},0).wait(1).to({rotation:-1.9,x:-3,y:-0.5},0).wait(1).to({rotation:-0.2,x:-0.4,y:-0.1},0).wait(1).to({rotation:1.3,x:2,y:0.4},0).wait(1).to({rotation:2.6,x:4.1,y:0.9},0).wait(1).to({rotation:3.8,x:5.9,y:1.3},0).wait(1).to({rotation:4.8,x:7.4,y:1.8},0).wait(1).to({rotation:5.7,x:8.7,y:2.1},0).wait(1).to({rotation:6.4,x:9.8,y:2.5},0).wait(1).to({rotation:7,x:10.7,y:2.7},0).wait(1).to({rotation:7.5,x:11.5,y:3},0).wait(1).to({rotation:8,x:12.1,y:3.2},0).wait(1).to({rotation:8.3,x:12.7,y:3.4},0).wait(1).to({rotation:8.7,x:13.2,y:3.6},0).wait(1).to({rotation:9,x:13.6,y:3.7},0).wait(1).to({rotation:9.2,x:14,y:3.9},0).wait(1).to({rotation:9.5,x:14.4,y:4},0).wait(1).to({rotation:9.7,x:14.7,y:4.1},0).wait(1).to({rotation:9.9,x:15,y:4.2},0).wait(1).to({rotation:10,x:15.2,y:4.3},0).wait(1).to({rotation:10.2,x:15.5,y:4.4},0).wait(1).to({rotation:10.4,x:15.7,y:4.5},0).wait(1).to({rotation:10.5,x:15.9,y:4.6},0).wait(1).to({rotation:10.6,x:16.1,y:4.7},0).wait(1).to({rotation:10.8,x:16.3,y:4.8},0).wait(1).to({rotation:10.9,x:16.5},0).wait(1).to({rotation:11,x:16.7,y:4.9},0).wait(1).to({rotation:11.2,x:16.9,y:5},0).wait(1).to({rotation:11.3,x:17.1,y:5.1},0).wait(1).to({rotation:11.5,x:17.3,y:5.2},0).wait(1).to({rotation:11.6,x:17.5,y:5.3},0).wait(1).to({rotation:11.8,x:17.8,y:5.4},0).wait(1).to({rotation:12,x:18.1,y:5.5},0).wait(1).to({rotation:12.2,x:18.3,y:5.6},0).wait(1).to({rotation:12.4,x:18.7,y:5.7},0).wait(1).to({rotation:12.6,x:19,y:5.9},0).wait(1).to({rotation:12.9,x:19.4,y:6.1},0).wait(1).to({rotation:13.2,x:19.9,y:6.3},0).wait(1).to({rotation:13.6,x:20.4,y:6.5},0).wait(1).to({rotation:14,x:20.9,y:6.7},0).wait(1).to({rotation:14.4,x:21.6,y:7.1},0).wait(1).to({regX:-17,regY:89,rotation:15,x:-17,y:89},0).wait(1).to({regX:0,regY:0,rotation:14.4,x:21.6,y:7.1},0).wait(1).to({rotation:13.6,x:20.5,y:6.5},0).wait(1).to({rotation:12.7,x:19.1,y:5.9},0).wait(1).to({rotation:11.4,x:17.3,y:5.1},0).wait(1).to({rotation:10,x:15.1,y:4.3},0).wait(1).to({rotation:8.5,x:12.9,y:3.5},0).wait(1).to({rotation:7.1,x:10.9,y:2.8},0).wait(1).to({rotation:6,x:9.2,y:2.3},0).wait(1).to({rotation:5.1,x:7.8,y:1.9},0).wait(1).to({rotation:4.4,x:6.8,y:1.6},0).wait(1).to({rotation:3.9,x:6,y:1.4},0).wait(1).to({rotation:3.5,x:5.4,y:1.2},0).wait(1).to({rotation:3.2,x:5,y:1.1},0).wait(1).to({rotation:3,x:4.6,y:1},0).wait(1).to({rotation:2.8,x:4.3,y:0.9},0).wait(1).to({rotation:2.6,x:4},0).wait(1).to({rotation:2.5,x:3.8,y:0.8},0).wait(1).to({rotation:2.3,x:3.6},0).wait(1).to({rotation:2.2,x:3.4,y:0.7},0).wait(1).to({rotation:2.1,x:3.2},0).wait(1).to({rotation:2,x:3.1,y:0.6},0).wait(1).to({rotation:1.9,x:2.9},0).wait(1).to({rotation:1.7,x:2.7},0).wait(1).to({rotation:1.6,x:2.5,y:0.5},0).wait(1).to({rotation:1.4,x:2.2},0).wait(1).to({rotation:1.3,x:2,y:0.4},0).wait(1).to({rotation:1,x:1.6,y:0.3},0).wait(1).to({rotation:0.8,x:1.2,y:0.2},0).wait(1).to({rotation:0.4,x:0.7,y:0.1},0).wait(1).to({regX:-17,regY:89,rotation:0,x:-17,y:89},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75,-90.5,150,181);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.s();
	this.instance.parent = this;
	this.instance.setTransform(0.1,-35.4,0.503,0.503,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-25},19,cjs.Ease.get(1)).to({y:-35.4},20,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-114.7,-75.9,229.4,151.8);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ11();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:-3.8,y:-0.6},0).wait(1).to({x:-7.5,y:-1.3},0).wait(1).to({x:-11.1,y:-1.9},0).wait(1).to({x:-14.6,y:-2.4},0).wait(1).to({x:-17.9,y:-3},0).wait(1).to({x:-21.1,y:-3.5},0).wait(1).to({x:-24.2,y:-4.1},0).wait(1).to({x:-27.2,y:-4.6},0).wait(1).to({x:-29.9,y:-5},0).wait(1).to({x:-32.6,y:-5.5},0).wait(1).to({x:-35.1,y:-5.9},0).wait(1).to({x:-37.5,y:-6.3},0).wait(1).to({x:-39.7,y:-6.7},0).wait(1).to({x:-41.8,y:-7},0).wait(1).to({x:-43.8,y:-7.3},0).wait(1).to({x:-45.6,y:-7.7},0).wait(1).to({x:-47.4,y:-7.9},0).wait(1).to({x:-49,y:-8.2},0).wait(1).to({x:-50.5,y:-8.5},0).wait(1).to({x:-52,y:-8.7},0).wait(1).to({x:-53.3,y:-9},0).wait(1).to({x:-54.6,y:-9.2},0).wait(1).to({x:-55.8,y:-9.4},0).wait(1).to({x:-57,y:-9.6},0).wait(1).to({x:-58,y:-9.7},0).wait(1).to({x:-59,y:-9.9},0).wait(1).to({x:-60,y:-10.1},0).wait(1).to({x:-60.9,y:-10.2},0).wait(1).to({x:-61.8,y:-10.4},0).wait(1).to({x:-62.6,y:-10.5},0).wait(1).to({x:-63.4,y:-10.6},0).wait(1).to({x:-64.1,y:-10.8},0).wait(1).to({x:-64.8,y:-10.9},0).wait(1).to({x:-65.5,y:-11},0).wait(1).to({x:-66.2,y:-11.1},0).wait(1).to({x:-66.8,y:-11.2},0).wait(1).to({x:-67.4,y:-11.3},0).wait(1).to({x:-67.9,y:-11.4},0).wait(1).to({x:-68.5,y:-11.5},0).wait(1).to({x:-64.8,y:-10.9},0).wait(1).to({x:-61.2,y:-10.3},0).wait(1).to({x:-57.7,y:-9.7},0).wait(1).to({x:-54.3,y:-9.1},0).wait(1).to({x:-51,y:-8.6},0).wait(1).to({x:-47.8,y:-8},0).wait(1).to({x:-44.8,y:-7.5},0).wait(1).to({x:-41.9,y:-7},0).wait(1).to({x:-39.2,y:-6.6},0).wait(1).to({x:-36.6,y:-6.1},0).wait(1).to({x:-34.1,y:-5.7},0).wait(1).to({x:-31.7,y:-5.3},0).wait(1).to({x:-29.5,y:-5},0).wait(1).to({x:-27.4,y:-4.6},0).wait(1).to({x:-25.5,y:-4.3},0).wait(1).to({x:-23.6,y:-4},0).wait(1).to({x:-21.9,y:-3.7},0).wait(1).to({x:-20.2,y:-3.4},0).wait(1).to({x:-18.7,y:-3.1},0).wait(1).to({x:-17.2,y:-2.9},0).wait(1).to({x:-15.9,y:-2.7},0).wait(1).to({x:-14.6,y:-2.4},0).wait(1).to({x:-13.4,y:-2.2},0).wait(1).to({x:-12.2,y:-2.1},0).wait(1).to({x:-11.1,y:-1.9},0).wait(1).to({x:-10.1,y:-1.7},0).wait(1).to({x:-9.1,y:-1.5},0).wait(1).to({x:-8.2,y:-1.4},0).wait(1).to({x:-7.3,y:-1.2},0).wait(1).to({x:-6.5,y:-1.1},0).wait(1).to({x:-5.7,y:-1},0).wait(1).to({x:-5,y:-0.8},0).wait(1).to({x:-4.2,y:-0.7},0).wait(1).to({x:-3.6,y:-0.6},0).wait(1).to({x:-2.9,y:-0.5},0).wait(1).to({x:-2.3,y:-0.4},0).wait(1).to({x:-1.7,y:-0.3},0).wait(1).to({x:-1.1,y:-0.2},0).wait(1).to({x:-0.5,y:-0.1},0).wait(1).to({x:0,y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-344.5,-78,689,156);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ21();
	this.instance.parent = this;
	this.instance.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-293.4,-101.1,586.9,202.3);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.man1 = new lib.Символ6();
	this.man1.parent = this;
	this.man1.setTransform(-20,90,1,1,0,0,0,-20,90);

	this.timeline.addTween(cjs.Tween.get(this.man1).wait(1).to({regX:-0.6,regY:3.1,x:-0.6,y:4.4},0).wait(1).to({y:5.6},0).wait(1).to({y:6.7},0).wait(1).to({y:7.8},0).wait(1).to({y:8.9},0).wait(1).to({y:9.8},0).wait(1).to({y:10.7},0).wait(1).to({y:11.6},0).wait(1).to({y:12.4},0).wait(1).to({y:13.1},0).wait(1).to({y:13.8},0).wait(1).to({y:14.4},0).wait(1).to({y:15},0).wait(1).to({y:15.5},0).wait(1).to({y:16},0).wait(1).to({y:16.4},0).wait(1).to({y:16.8},0).wait(1).to({y:17.2},0).wait(1).to({y:17.6},0).wait(1).to({y:17.9},0).wait(1).to({y:18.2},0).wait(1).to({y:18.5},0).wait(1).to({y:18.8},0).wait(1).to({y:19},0).wait(1).to({y:19.2},0).wait(1).to({y:19.5},0).wait(1).to({y:19.7},0).wait(1).to({y:19.9},0).wait(1).to({y:20},0).wait(1).to({y:20.2},0).wait(1).to({y:20.4},0).wait(1).to({y:20.5},0).wait(1).to({y:20.7},0).wait(1).to({y:20.8},0).wait(1).to({y:21},0).wait(1).to({y:21.1},0).wait(1).to({y:21.3},0).wait(1).to({y:21.4},0).wait(1).to({y:21.5},0).wait(1).to({y:21.6},0).wait(1).to({y:21.8},0).wait(1).to({y:21.9},0).wait(1).to({y:22},0).wait(1).to({regX:-20,regY:90,x:-20,y:109},0).wait(1).to({regX:-0.6,regY:3.1,x:-0.6,y:20.9},0).wait(1).to({y:19.7},0).wait(1).to({y:18.5},0).wait(1).to({y:17.5},0).wait(1).to({y:16.4},0).wait(1).to({y:15.5},0).wait(1).to({y:14.6},0).wait(1).to({y:13.8},0).wait(1).to({y:13},0).wait(1).to({y:12.3},0).wait(1).to({y:11.6},0).wait(1).to({y:11},0).wait(1).to({y:10.4},0).wait(1).to({y:9.9},0).wait(1).to({y:9.4},0).wait(1).to({y:8.9},0).wait(1).to({y:8.5},0).wait(1).to({y:8.1},0).wait(1).to({y:7.8},0).wait(1).to({y:7.4},0).wait(1).to({y:7.1},0).wait(1).to({y:6.8},0).wait(1).to({y:6.6},0).wait(1).to({y:6.3},0).wait(1).to({y:6.1},0).wait(1).to({y:5.9},0).wait(1).to({y:5.7},0).wait(1).to({y:5.5},0).wait(1).to({y:5.3},0).wait(1).to({y:5.1},0).wait(1).to({y:4.9},0).wait(1).to({y:4.8},0).wait(1).to({y:4.6},0).wait(1).to({y:4.5},0).wait(1).to({y:4.3},0).wait(1).to({y:4.2},0).wait(1).to({y:4},0).wait(1).to({y:3.9},0).wait(1).to({y:3.8},0).wait(1).to({y:3.7},0).wait(1).to({y:3.6},0).wait(1).to({y:3.4},0).wait(1).to({y:3.3},0).wait(1).to({y:3.2},0).wait(1).to({regX:-20,regY:90,x:-20,y:90},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75,-90.5,150,181);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:-34.2,regY:-5.8,x:-34.2,y:-6},0).wait(1).to({y:-6.4},0).wait(1).to({y:-6.8},0).wait(1).to({y:-7.3},0).wait(1).to({y:-7.9},0).wait(1).to({y:-8.6},0).wait(1).to({y:-9.3},0).wait(1).to({y:-9.9},0).wait(1).to({y:-10.6},0).wait(1).to({y:-11.2},0).wait(1).to({y:-11.7},0).wait(1).to({y:-12.1},0).wait(1).to({y:-12.5},0).wait(1).to({y:-12.7},0).wait(1).to({y:-13},0).wait(1).to({y:-13.2},0).wait(1).to({y:-13.4},0).wait(1).to({y:-13.5},0).wait(1).to({y:-13.6},0).wait(1).to({y:-13.7},0).wait(1).to({y:-13.8},0).wait(1).to({y:-13.9},0).wait(1).to({y:-14},0).wait(1).to({y:-14.1},0).wait(2).to({y:-14.2},0).wait(1).to({y:-14.3},0).wait(1).to({y:-14.4},0).wait(2).to({y:-14.5},0).wait(1).to({y:-14.6},0).wait(1).to({y:-14.7},0).wait(1).to({y:-14.8},0).wait(1).to({y:-14.9},0).wait(1).to({y:-15},0).wait(1).to({y:-15.1},0).wait(1).to({y:-15.3},0).wait(1).to({y:-15.5},0).wait(1).to({regX:0,regY:0,x:0,y:-10},0).wait(1).to({regX:-34.2,regY:-5.8,x:-34.2,y:-15.5},0).wait(1).to({y:-15.1},0).wait(1).to({y:-14.7},0).wait(1).to({y:-14.2},0).wait(1).to({y:-13.7},0).wait(1).to({y:-13},0).wait(1).to({y:-12.4},0).wait(1).to({y:-11.7},0).wait(1).to({y:-11.1},0).wait(1).to({y:-10.5},0).wait(1).to({y:-10},0).wait(1).to({y:-9.5},0).wait(1).to({y:-9.1},0).wait(1).to({y:-8.8},0).wait(1).to({y:-8.6},0).wait(1).to({y:-8.4},0).wait(1).to({y:-8.2},0).wait(1).to({y:-8.1},0).wait(1).to({y:-7.9},0).wait(1).to({y:-7.8},0).wait(1).to({y:-7.7},0).wait(1).to({y:-7.6},0).wait(1).to({y:-7.5},0).wait(2).to({y:-7.4},0).wait(1).to({y:-7.3},0).wait(2).to({y:-7.2},0).wait(1).to({y:-7.1},0).wait(2).to({y:-7},0).wait(1).to({y:-6.9},0).wait(1).to({y:-6.8},0).wait(1).to({y:-6.7},0).wait(1).to({y:-6.6},0).wait(1).to({y:-6.5},0).wait(1).to({y:-6.3},0).wait(1).to({y:-6.2},0).wait(1).to({y:-6},0).wait(1).to({regX:0,regY:0,x:0,y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-344.5,-78,689,156);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_10 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(10));

	// Слой 15
	this.instance = new lib.Символ54();
	this.instance.parent = this;
	this.instance.setTransform(-112.9,104.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:17.2},9,cjs.Ease.get(1)).wait(1).to({y:104.8},9,cjs.Ease.get(1)).wait(1));

	// Слой 10
	this.instance_1 = new lib.Символ37();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-115.4,-496.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:-648.6,alpha:0},9,cjs.Ease.get(1)).wait(1).to({y:-496.6,alpha:1},9,cjs.Ease.get(1)).wait(1));

	// Слой 14
	this.instance_2 = new lib.Символ50();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-98.2,-361.3);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-345.3,alpha:1},9,cjs.Ease.get(1)).wait(1).to({y:-361.3,alpha:0},9).wait(1));

	// Слой 11
	this.instance_3 = new lib.Символ41();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-110,-397);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:-107.6,y:-662.6,alpha:0},9,cjs.Ease.get(1)).wait(1).to({x:-110,y:-397,alpha:1},9,cjs.Ease.get(1)).wait(1));

	// Слой 8
	this.instance_4 = new lib.Символ27();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-174.3,48.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({y:55,alpha:0},9,cjs.Ease.get(1)).wait(1).to({y:48.8,alpha:1},9,cjs.Ease.get(1)).wait(1));

	// Слой 7
	this.oblako = new lib.Символ25();
	this.oblako.parent = this;
	this.oblako.setTransform(-97.6,-307.5);

	this.timeline.addTween(cjs.Tween.get(this.oblako).to({regX:-0.1,scaleX:1.25,scaleY:1.25,x:-105.7,y:-360.2},9,cjs.Ease.get(1)).wait(1).to({regX:0,scaleX:1,scaleY:1,x:-97.6,y:-307.5},9).wait(1));

	// Слой 1
	this.instance_5 = new lib.Символ15();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,10);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({scaleX:1.25,scaleY:1.25,x:16,y:41.4},9,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1,x:0,y:10},9,cjs.Ease.get(1)).wait(1));

	// Слой 2
	this.instance_6 = new lib.Символ5();
	this.instance_6.parent = this;
	this.instance_6.setTransform(185.3,-484.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({scaleX:1.25,scaleY:1.25,x:246.9,y:-592.6},9,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1,x:185.3,y:-484.2},9,cjs.Ease.get(1)).wait(1));

	// Слой 12
	this.instance_7 = new lib.Символ43();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-142.6,-316.6,0.314,0.314,-15,0,0,-0.2,-0.4);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({regX:0,regY:0,scaleX:0.77,scaleY:0.77,rotation:0,x:-118.9,y:-53.7,alpha:1},9,cjs.Ease.get(0.95)).wait(1).to({regX:-0.2,regY:-0.4,scaleX:0.31,scaleY:0.31,rotation:-15,x:-142.6,y:-316.6,alpha:0},9,cjs.Ease.get(1)).wait(1));

	// Слой 13
	this.instance_8 = new lib.Анимация2("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(-157.9,-314.3,1,0.062);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({scaleY:0.78,y:-179.8,alpha:1},9,cjs.Ease.get(1)).wait(1).to({startPosition:0},0).to({scaleY:0.06,y:-314.3,alpha:0},9).wait(1));

	// Слой 3
	this.man = new lib.Символ16();
	this.man.parent = this;
	this.man.setTransform(-89,-137.5);

	this.timeline.addTween(cjs.Tween.get(this.man).to({scaleX:1.25,scaleY:1.25,x:-94.9,y:-166.4},9,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1,x:-89,y:-137.5},9,cjs.Ease.get(1)).wait(1));

	// Слой 6 - копия
	this.instance_9 = new lib.Символ14();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-50.5,-0.5);
	this.instance_9.alpha = 0.738;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({regX:-0.1,regY:-0.1,scaleX:1.25,scaleY:1.25,x:-47,y:4.1},9,cjs.Ease.get(1)).wait(1).to({regX:0,regY:0,scaleX:1,scaleY:1,x:-50.5,y:-0.5},9,cjs.Ease.get(1)).wait(1));

	// Слой 6
	this.instance_10 = new lib.Символ22();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-39.5,5.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({scaleX:1.25,scaleY:1.25,x:-33.2,y:11.3},9,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1,x:-39.5,y:5.2},9,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-344.5,-560.1,689,692.6);


// stage content:



(lib.ucl300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		stage.scaleX = stage.scaleY = 2;
		
		stage.canvas.width = 300 * 2;
		stage.canvas.height = 600 * 2;
		stage.canvas.style.width = "300px";
		stage.canvas.style.height = "600px";
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		var _this = this;
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		  function fl_MouseOverHandler_5()
		{
		    _this.main.gotoAndPlay(1);
			_this.main.man.man1.man2.rot.gotoAndStop(1);
			_this.main.man.man1.man2.ok.gotoAndPlay(1);
			_this.main.oblako.oblako1.oblako2.servak.gotoAndPlay(1);
		}
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		  function fl_MouseOutHandler_2()
		{
		    _this.main.gotoAndPlay(11);
			_this.main.man.man1.man2.rot.gotoAndStop(0);
			_this.main.man.man1.man2.ok.gotoAndPlay(6);
			_this.main.oblako.oblako1.oblako2.servak.gotoAndPlay(6);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Символ 2
	this.main = new lib.Символ2();
	this.main.parent = this;
	this.main.setTransform(260.5,535.2);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

	// Символ 3
	this.instance = new lib.Символ3();
	this.instance.parent = this;
	this.instance.setTransform(151.2,300.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(66,275.1,689,692.6);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;