(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 305,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/back.jpg?1469462355801", id:"back"},
		{src:"images/cbvcb.png?1469462355801", id:"cbvcb"},
		{src:"images/cvb.png?1469462355801", id:"cvb"},
		{src:"images/ert.png?1469462355801", id:"ert"},
		{src:"images/ertret.png?1469462355801", id:"ertret"},
		{src:"images/potop5640x305rez_03.png?1469462355801", id:"potop5640x305rez_03"},
		{src:"images/potop5640x305rez_06.png?1469462355801", id:"potop5640x305rez_06"},
		{src:"images/potop5640x305rez_09.png?1469462355801", id:"potop5640x305rez_09"},
		{src:"images/potop5640x305rez_15.png?1469462355801", id:"potop5640x305rez_15"},
		{src:"images/potop5640x305rez_18.png?1469462355801", id:"potop5640x305rez_18"},
		{src:"images/w256h2561380453915MouseOptions256x25632.png?1469462355801", id:"w256h2561380453915MouseOptions256x25632"}
	]
};



// symbols:



(lib.back = function() {
	this.initialize(img.back);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,305);


(lib.cbvcb = function() {
	this.initialize(img.cbvcb);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,187);


(lib.cvb = function() {
	this.initialize(img.cvb);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,111,186);


(lib.ert = function() {
	this.initialize(img.ert);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,106,184);


(lib.ertret = function() {
	this.initialize(img.ertret);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,124,186);


(lib.potop5640x305rez_03 = function() {
	this.initialize(img.potop5640x305rez_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,32,43);


(lib.potop5640x305rez_06 = function() {
	this.initialize(img.potop5640x305rez_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,40,31);


(lib.potop5640x305rez_09 = function() {
	this.initialize(img.potop5640x305rez_09);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,47,84);


(lib.potop5640x305rez_15 = function() {
	this.initialize(img.potop5640x305rez_15);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,118,152);


(lib.potop5640x305rez_18 = function() {
	this.initialize(img.potop5640x305rez_18);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,50,119);


(lib.w256h2561380453915MouseOptions256x25632 = function() {
	this.initialize(img.w256h2561380453915MouseOptions256x25632);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,256);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,0,0,0.4)").s().p("AhjBjQgpgpAAg6QAAg5ApgqQAqgpA5AAQA6AAApApQAqAqAAA5QAAA6gqApQgpAqg6AAQg5AAgqgqg");
	this.shape.setTransform(14.2,14.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,28.3,28.3);


(lib.Символ52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(2,1,1).p("ACNAAQAAA6gqApQgpAqg6AAQg5AAgqgqQgpgpAAg6QAAg5ApgqQAqgpA5AAQA6AAApApQAqAqAAA5g");
	this.shape.setTransform(14.2,14.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,30.3,30.3);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkHB1IgdhLIABBAIgCADIgFACIhHAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgDgJIgLjPQAAgCAFgBIBUgDQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAEBfIATguQAJgYAIgaQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIA6AEIAMADQAFABgBABIgBAGIgVA2IgfAsQAOAYALAaQANAbAIAeQABAEgJACIgVAEIguACQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBgArHBvQgKgCgJgEQgSgJgNgQQgNgQgHgWIgFgZIgCgZQAAgPAHgcQADgLAFgIIALgQQANgPASgIQAJgEALgCQAKgDALAAQAMAAAKADQAKACAJAEQASAJAMAPQAMAOAGAUQAGAaABAPQAAAWgHAXQgGAWgMASQgGAJgHAGQgIAIgJAFQgJAFgKADQgKADgNAAQgKAAgKgDgArFgEQgEAEAAARQAAASAGAMQAGAMAJAAQAJAAAHgMQAFgMAAgSQAAgRgFgEQgEgHgLAAQgMAAgGAHgAHEBvIgDgBIgIh8IgqgBQgBAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAhdQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIA6gBQA4AAA2ADQABAAAAAAQABABAAAAQABAAAAABQAAABAAAAIAABcQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgpAAIgLB6QAAAFgYAAgAEkBvQgFAAgBgDIgBgHIgGhjQgCgzAAg3IAAgEIAHgCIANgBIBJACIAFABIAAADIAAAGIAAAKIAAAPIgFC1QAAABAAABQAAABAAAAQAAABgBAAQAAABgBAAIgDABgAoJBvIgCgBIgJh8IgrgBQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAhdQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIA6gBQA4AAA3ADQABAAAAAAQABABAAAAQABAAAAABQAAABAAAAIAABcQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgqAAIgLB6QABAFgYAAgAJiBrIgSgFQgGgDAAgDIACjNIABgHIBWgCIAIACQABABABAAQABAAAAABQABAAAAAAQAAABAAAAIAAAcQAVABASAGQATAFAOAKQAOALAIAQQAEAHACAKQACAJAAAKQAAAMgCALQgCALgEALQgJAUgRAPQgIAIgJAFQgKAGgLAFQgMAEgNACQgNACgPAAgAKvA9IAJACQAKAAAJgGQAIgGAAgMQAAgHgDgFQgCgGgFgEQgFgFgGgCQgHgCgIAAgABLBrIgRgFQgHgDAAgDIABjNIACgHIBWgCIAJACQAAABABAAQABAAAAABQABAAAAAAQAAABAAAAIAAAcQAVABATAGQASAFAOAKQAOALAIAQQAEAHACAKQACAJAAAKQAAAMgCALQgCALgEALQgKAUgPAPQgIAIgKAFQgKAGgMAFQgLAEgNACQgNACgOAAgACYA9IAJACQAKAAAIgGQAJgGgBgMQAAgHgBgFQgDgGgFgEQgFgFgGgCQgHgCgIAAgAiTBvQgCAAgCgMIgMh6IgFhQQAAgDAHgDIARgFIA3gEQAOAAANACQAOACALAEQAXAIAOAPQAQAPAJAVQAFAKACALQACALgBANQABAJgCAJQgDAKgEAIQgHAQgOAKQgMALgTAFQgTAGgUABIAAAbQAAAAgBABQAAAAAAABQgBAAAAAAQgBABgBAAIgJACgAhCgGIAAAzQAQAAAKgJQAFgEACgFQADgGAAgGQAAgNgJgEQgJgGgJAAg");
	this.shape.setTransform(79,12);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,157.9,24);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABeELIgEgDIgDgaQgCgaAAgxIi0AAIgMBnQgBADgLAAIh+gBIgCgCIgMiyIAGgDIBOgFQAKgJAGgWQAGgXAAgdIgFjwIACgKQACgDAHAAIEUgCIBeAEIAHACIACAGIgIFJIAVACIgDBvIgOBLIgFABgABHBQIgIimIg5AAQgDA+gFAoQgHAqgJAWIBZAAgAnmCiQgIgCAAgEIADgfIAEgOQACgGADAAIATACQAcAAAMgKQALgJAAgKIgCgNQgCgFgGgEQgHgEgMgCIgggCQgGAAgBgIIgBgdQAAgBABAAQAAgBAAAAQABAAAAgBQABAAABAAIAaABQAbAAAKgJQAKgJAAgRQAAgOgLgKQgMgKgdAAIgaACIgJADQgEAAgGgLIgOgcIgihzIgEgZQAAgIAHgGQAIgHAMgEIAcgHIAjgDQAoAAAiALIAgANQAPAIANAKQAZAWAPAiQAHAQAEAVQAEAUAAAXQAAAZgGAUQgFATgIAOQgJANgMAIQgMAKgOAFQAXAHAMARQAMARAAAUQAAAUgKAPQgLAOgUAKQgVAKgdAFQgeAFgmAAgAq/CbIgFgCIgCgIIgEgnIgUAOIgPAGQgGAAgFgIIgHgPIgFAjIgDAIIgIAEIgUADIhpgBQgUgBAAgFIABgGIAxjCQAahgAfhhIAEgFIALgCIAVgCIB3ACIAQAEIAFAEIBTGPIAAACQAAAEgFAAgAr/AuIAXgQIAMgEIAIADIANAPIgahwgAK8CZIgFgEIgQjlIhOgBQgFAAAAgGIAAirQAAgFAFAAIBqgBQBnAABlAFQAFAAAAAFIAACpQAAAFgFAAIhMABIgUDiQAAAIgsAAgAFHCZQgNgBgFgEQgFgDgBgHIgHg6IgSk6QAAgGAIgEQAIgDAWgDIA8gEIC5gCQAFAAAAAFIgHB4IgGAnQgDAPgEAAIhhgDIgCArIBXgFIAOACQAEACAAAFIgOAxQgDAHg0AAIglgBIgCAuIBhAAQAFAAAAAJIgDBCIgGAFIgUAEIhkADgAQMCYIgugHIgggJQgMgFAAgHIACl6IADgNICegDIAQADQAGADAAADIAAAyQAnADAiAKQAiAKAaATQAZATAPAdQAIAPADARQAEASAAAUQAAAXgEAUQgEATgIATQgQAmgeAcQgOANgSALQgSALgVAHQgWAIgXAEQgYAEgbAAgARrA9IARACQASAAAQgKQAPgLAAgXQAAgMgEgIQgFgKgJgIQgIgIgMgEQgMgEgQAAgA0HCBIgQiIIgPjrQAAgGAMgGIAggJIBlgIQAaAAAYADQAYAEAVAIQAqAPAeAbQAeAcAQAmQAIATAEAVQADAUAAAXQAAAUgDASQgEARgHANQgPAdgaATQgZATgjAKQgiALgmACIAAAyQAAADgGADIgQADIh/ABQgCgBgEgXgAxshBIAABgQAeAAASgQQAJgIAEgIQAFgKAAgMQAAgXgQgLQgPgLgSAAg");
	this.shape.setTransform(131.9,27.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,263.9,54.6);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgsjxIDxDxIjxDygAjEBsIAAjWICKAAIAADWg");
	this.shape.setTransform(19.7,24.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,39.4,48.5);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,204,0,0.486)").s().p("AADEEQgXgBgxgFIgBAAIhMgIQgKgBgEgEQgCgDAAgEQAAgFAEgBQgEgPAAgXIABggIAAgHQAAgVgGgqQgCgTgHgLQgJgLgCgGQgCgEABgGIAAgLQAAgKgGgKIgLgSQgNgVADgQIABgFIAEgFIACgDQAIgJATgJQALgFAEgEIAIgMQAEgIADgKQAHgOAEgRQADgPAAgIQADgWACgFQADgIAHgGQAIgGAJgBQAJgBAIAFIAFADIACADIACADIACAEQACAGgBAIIgBAOQgBARAIARQAIAQAPAKIAQAKQAJAGACAIIAEAOQAEAHAMACQAVAEAdgCIAzgFQAIgBAEgDQAGgFAAgNQAAgPgBgLQgCgLgDgHQgEgHgJgLIghglIgKgOIgBgBIAAgBIgCgFQgDgIAEgMQAEgNAJgIIABABQAkAEANANIALALIAQAHIAKAFIABABIACABQAJAFAIAKQAJAKAQAVIANASQAEAJAAARIgBAlQAAAJgDAGQgDAIgHAAIAAAGIAAAAQAHAEAAAPIAAArQAAAKgDAFQgDADgBACIAAAHQAAAEgCACIgEAFIgBAHQgBADgFADIgFAGIgCAGIgFAIQgCAEABAJQAAAIgCAEQgBADgEAEIgGAFIgBAzIACA0QACAbgJALQgLANggAAQhKAAgmgCgABLjnIAEgBQAAAAABAAQABAAAAgBQAAAAABAAQAAAAAAgBIANABQgJgFgHADIAAgBIgEAFg");
	this.shape.setTransform(21.7,26.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,43.4,52.5);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,204,0,0.486)").s().p("AgaCsIhjgNQgYgDgPgFQgMgEgWgNQgtgcgQgQQgQgQgFgPQgFgPABghQABgxASgUIAMgKIALgKQAGgGAKgZQAOgjAdgjIABACQAJgBALAIIARAQQAJAHAfAMIAwARQAYAJANACQAJABARgBIBXgFQAigCAOgJQAFgEAPgSQAMgOALgDQAMgEAGAHQADAEABAMQABAKAFAPQALAhAHANIAPAbQAIAQgCANQAKACAFAQIANAyIAFAYQACAOgDALQgEALgIAIQgGAFgKAFIgSAJIgbASQgQAIgkAGQgsAIgcABIgOAAQglAAg9gIg");
	this.shape.setTransform(28.6,18.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,57.1,36.2);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.498)").s().p("AgxB0IgEgKQgCgLgFgLQgFgLgIgKIgLgSQgFgIgGgEQgCgBgKgBIgegDQgogDgOgRQgLgLAAgjQgBgVADgNQAEgKAJgRQALgQALgEQAhABASACQAcADAVAKQAKAEAFABQAEAAAGgBIAKgDQAPgFAeACQAdABANAIQgBgEACgEQACgEAEgCQAGgDAKABIBBABQALAAAFABQAJADAIAIQAKALACAKQACAKgEAKQgDAKgJAGQAEAGAMAGQAJAHACAOQABAJgDAQQgDATgJAFQgFADgMAAIg7gBQgMAAgEgFQgCgCgCgFIgDgGQgCgEgEgBQgEgBgCACQgKAVgBAJIgEARQgBAEgEAFIgIAIQgGAMgFAEQgLALgYgCIgRgCQgLgBgIACQACAHgHAEIgEABQgFAAgDgEg");
	this.shape.setTransform(20.4,12);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40.8,24.1);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.486)").s().p("AARB1QgUgBgRgHQgUgKgIgSIgEgLQgCgGgDgDQgvAPgxgGIgOgCQgTgHgHgYQgFgRADgWQADgRAGgFQAHgHACgDQACgEAAgPQgCgSAIgRQAIgRAPgMIAAABIA6ABQASABAAAJQARAGAPAMQAKAKAEACQAHADAOABIA8AEIADgCQAJgGAGAAIAAgCIBMACIAHABQAGAEAAAJIAAAEQAEABACACQAGAEAFAHQAMARADAVQADATgGATQgDAIgBAGIAAAJQABAGgBADQgDAIgLAEQgFACgPAAIgwgCQgJAAgEgDIgIgHQgEgEgEgBQADANgFAMQgEANgLAHQgOALgZAAIgFgBg");
	this.shape.setTransform(19.8,11.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,39.6,23.6);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AggBbIgBgBQgKgIgDgJQgFgKAAgMQAAgKAFgIQADgIAGgGIAGgJIACgHQAAgHgGgEQgGgEgJAAIgEABIgEAAIgCgBIgBgGIACgiQABgSAHgSQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAIAGgBQAXAAATAEIARAFIAOAHQAOAJAJAOQAHAOABAVQAAAKgCAHQgDAHgDAGQgJAMgQALQgMAIgEAHQgDAGgBAFIABAEIACADIADACIABACIgBADIgEACIgZALQgKADgFAAg");
	this.shape.setTransform(6.2,9.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.4,18.5);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhEBjIgPgEQgGgDAAgDIABi3IABgGIBNgCIAIACQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAAAYQASABAQAFQARAFAMAJQANAKAHAOQADAHACAIQACAJAAAHQAAALgCALQgCAKgEAJQgHATgPANQgHAGgJAGQgIAFgLAEQgKAEgMABQgJACgNAAgAAAA6IAHABQAJAAAHgFQAIgFAAgMQAAgFgCgFQgCgFgFgEQgEgEgGgCQgGgBgGgBg");
	this.shape.setTransform(9.1,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,18.2,20.7);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaBkIgCgBIgBgGIgHhpIgmAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBgBgBIAAhTQABgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIA0gBQAvAAAyADQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABSQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAIglAAIgKBtQAAAEgWAAg");
	this.shape.setTransform(7.8,10.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,15.6,20.5);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWAeIgHgMIgFgOIgDgJIABgDIAEgCIAogWIAGgCQADAAAEAGIAOAcIADAGQAAADgGAEIgtAVIgDABQgCAAgEgFg");
	this.shape.setTransform(3.8,3.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,7.7,7.2);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AATBiIgBgBIgBgEIgCgTIgLAHIgEADQgEAAgCgEIgDgHIgDARIgCAEIgDACIgJABIg0AAQgKgBAAgCIABgDIAYhdQANgvAPgvIACgCIAFgBIBBAAIAJACIACACIApDBIAAAAQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAgAgJAuIAJgIIAGgCIADABIAHAHIgNg1g");
	this.shape.setTransform(8.9,10.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,17.8,20.2);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhuBjQgKgEAAgDIACgHIAJgUQADgDAEAAIAIABQAIAAAFgMQADgIACgYIgDhzIABgEQABgCAEAAIC+ABIADABIABADIAAAGIgBAIIAAANIgDCiQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAAAIgEABIgLAAIg2gCQgEAAgBgCIgBgHIgGhpIgWgBIgHABQgDAfgCAWQgEAVgFAKQgFAJgHAHQgHAIgJAEQgTAKgWAAQgVAAgLgEg");
	this.shape.setTransform(12.1,10.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,24.3,20.7);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgsBjQgHgBgCgBQgDgCAAgDIgNi0QAAgDAEgCQAFgCAKgBIB1gDQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIgHBNQgCAHgBAAIgwgBIAAATIAqgDIAHABQAAABABAAQAAAAAAABQAAAAAAAAQABABAAAAIgHAaQgCADgZAAIgSgBIgBAXIAvAAQABAAAAAAQABAAAAABQAAAAAAABQAAABAAABIgBAgIgDACIgJACIgSACg");
	this.shape.setTransform(7,10);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,14,20.1);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA6B/IgJgBIgCgCIgBgMQgBgNAAgYIhWAAIgHAzQAAABgFAAIg9gBIgBgBIgHhJIAAgNIADgCIAngCQAEgEADgLQADgLAAgNIgDh1IACgFQAAAAAAAAQABgBAAAAQABAAAAAAQABAAABAAICzABIADABIABADIgECeIAKABIgBA2IgHAlIgDAAgAAmAjIgEhQIgVAAIgHAAQgCAegCATQgCAUgEALIAqAAg");
	this.shape.setTransform(12.3,12.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,24.6,25.8);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgRBmQgJgCgIgEQgQgIgLgOQgLgOgHgVQgDgKgBgLIgCgWQAAgPAGgYIAHgRIAKgPQAMgNAQgHQAIgEAJgCQAJgBAJgBQAKABAJABQAJACAIAEQAQAIALANQALANAFASQAGAXAAAOQAAATgGAUQgFAUgLAPQgFAJgHAGIgPALQgIAFgJACQgJADgLgBQgIAAgJgBgAgOgCQgEAFAAAOQAAAQAFALQAGALAHAAQAHAAAFgLQAGgLAAgQQAAgOgFgFQgEgFgJAAQgKAAgEAFg");
	this.shape.setTransform(8.6,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,17.3,20.8);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaBkIgCgBIgBgGIgHhpIgmAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBgBgBIAAhTQABgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIA0gBQAvAAAyADQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABSQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAIglAAIgKBtQAAAEgWAAg");
	this.shape.setTransform(7.8,10.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,15.6,20.5);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AADBjQgDAAAAgCIgCgHIgDhBQgNADgLAAQgNAAgJgEQgJgEgFgHQgGgHgDgGQgCgIgBgJIgBhPIABgBIAEgBIAJgBIAfAAQAEABgBADIgBBAIABAIIAEAEIAGABQAHAAACgDQACgDAAgCIgChDQAAgEAHgBIBOABIAEABIABAGIgDBaIgBAsIgBA2IgCACg");
	this.shape.setTransform(7.9,10.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,15.8,20.2);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68ATBIAmvZIAAgHIABgRIgBgKQAAgFACgEIAAAAIAAgFIAEAAIAEgFQAFgGgBgPQgBgOADgGQAFgIADgEIAEgOIAEgJQACgFAAgEQgCgJABgEQABgDAEgDIAIgGIAHgJQAEgFAEgCIAHgDIAKgIIAFgGQAJgLAIAAIACAAIACgBQCbhjEOADQBaABCyAJQCfAFBqgXQBqgWCshPQDDhaBQgXQBvgiCRgNQBZgHCtgCQCzgBBTgGQCSgKBwgfQBfgaC/hWQC5hUBngaQBpgbCKgIQBKgECtAAQCfACBXgGQCHgLBqgfQB/gmDdh+QDjiDB3gnQDDg+E9AKQBYADCwAJQCaAGBsgGQC5gLCyg1QCzg2CghbIAMAhQDdgcDhAPQBJAFBJAKQADgKALgBIAFgBIgBgCIBHAEIBCACQASABAHAEQAGACAMAJIARAKIAKALIAFAHIAbgFIAHAAMgA4AnPgEg5iACvIAAAAIAAgBIAAABgEA5jgS3IAEgBIgFgDg");
	this.shape.setTransform(377.3,122.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS/IAmvYIAAgIIABgRIgBgKQAAgFACgEIAAAAIAAgEIAEAAIAEgGQAFgGgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgGAAgDQgCgKABgEQABgDAEgDIAIgGIAHgIQAEgGAEgCIAHgCIALgIIAEgHQAJgKAIAAIADAAIABgBQCahkEPADQBaABCyAKQCfAEBqgVQBqgVCshPQDDhYBSgYQBwghCQgOQBcgICqgCQCxgDBUgFQCRgJBwggQBfgcC/hUQC6hSBmgZQBqgaCJgJQBNgFCrgBQCfAABXgHQCGgKBqggQB/gmDeh9QDkiBB5gmQDCg9E4AIQBaAACwAKQCaAEBtgHQC4gNCygyQCzg0CdhYIAPAfQDegbDeAOQBLADBJAKQADgKALgBIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARAKIAKAMIAFAGIAbgFIAHAAMgA4AnPg");
	this.shape_1.setTransform(377.3,122.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS+IAmvZIAAgHIABgSIgBgJQAAgGACgDIAAAAIAAgFIAEAAIAEgFQAFgGgBgPQgBgPADgFQAFgIADgEIAEgOIAEgJQACgFAAgEQgCgJABgEQABgEAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgGQAJgLAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgUQBqgUCthOQDDhXBSgZQBwghCTgNQBdgJCogEQCugEBWgDQCPgIBwgiQBfgeC/hSQC6hPBngYQBpgZCKgKQBOgICqgBQCegBBYgIQCFgLBqggQB/glDeh8QDliBB6gkQDDg7E0AFQBbgDCwAKQCaAEBugJQC4gNCxgyQC0gyCXhVIAVAeQDegaDbANQBNACBJAKQADgKALgCIAFgBIgBgBIBHADIBCADQASABAHAEQAGACAMAJIARAKIAKALIAFAHIAbgFIAHAAMgA4AnPg");
	this.shape_2.setTransform(377.3,122.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS8IAmvZIAAgHIABgRIgBgKQAAgFACgEIAAAAIAAgFIAEAAIAEgFQAFgGgBgPQgBgOADgGQAFgIADgEIAEgOIAEgJQACgFAAgEQgCgJABgEQABgDAEgDIAIgGIAHgJQAEgFAEgCIAHgDIALgIIAEgGQAJgLAIAAIADAAIABgBQCahjEPADQBaABCyAJQCfAFBqgTQBqgSCuhOQDChWBUgYQBxghCSgOQBggLCmgEIECgIQCPgGBvgjQBfgfC/hQQC6hNBngYQBpgYCKgMQBPgICrgDQCcgCBYgIQCFgMBqgfQB/gmDfh7QDmh/B8gjQDDg6EvADQBcgFCwAJQCbADBugKQC3gOCxgwQC0gwCThSIAZAcQDfgYDYAKQBPABBJAKQADgKALgBIAFgBIgBgCIBHAEIBCACQASABAHAEQAGACAMAJIARAKIAKALIAFAHIAbgFIAHAAMgA4AnPg");
	this.shape_3.setTransform(377.3,122.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS6IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgEIAEgOIAEgJQACgFAAgEQgCgKABgDQABgEAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgGQAJgLAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgSQBqgSCuhMQDEhWBUgXQBxgiCTgOQBhgLCkgFIEBgIQCOgGBvgkQBgghC/hOQC6hLBmgWQBpgWCKgOQBRgKCqgEQCcgEBYgJQCEgLBqggQB/glDgh6QDmh+B+giQDDg4ErAAQBdgICwAKQCbABBvgLQC2gQCxgtQC0gvCPhPIAeAcQDegYDXAJQBQAABJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_4.setTransform(377.3,123);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS5IAmvZIAAgHIABgSIgBgJQAAgGACgDIAAAAIAAgFIAEAAIAEgFQAFgGgBgPQgBgPADgFQAFgIADgEIAEgOIAEgJQACgFAAgEQgCgJABgEQABgEAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgGQAJgLAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgRQBqgQCvhLQDDhVBWgYQByghCTgPQBjgMCigGQCmgHBZgBQCOgEBugmQBfgjDAhLQC6hKBngUQBpgWCKgPQBTgMCogFQCcgFBYgJQCDgMBqggQB/glDhh5QDnh8B/giQDDg2EngDQBegKCwAKQCbAABxgMQC0gQCxgtQC0gtCLhLIAjAaQDdgWDWAHQBRgCBJAKQADgKALgCIAFgBIgBgBIBHADIBCADQASABAHAEQAGACAMAJIARAKIAKALIAFAHIAbgFIAHAAMgA4AnPg");
	this.shape_5.setTransform(377.3,123.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS3IAmvYIAAgIIABgRIgBgKQAAgFACgEIAAAAIAAgEIAEAAIAEgGQAFgGgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgGAAgDQgCgKABgEQABgDAEgDIAIgGIAHgIQAEgGAEgCIAHgCIALgIIAEgHQAJgKAIAAIADAAIABgBQCahkEPADQBaABCyAKQCfAEBqgPQBqgPCwhLQDChTBYgZQByggCUgQQBlgMCggIQCkgIBZABQCNgDBugoIEfhuQC6hHBngTQBpgVCKgQQBVgOCngGQCcgGBYgKQCCgMBqggQB/gmDih3QDnh8CCggQDCg0EigGQBggMCwAKQCbgCBygNQC0gRCxgrQCzgrCHhIIAnAZQDfgWDSAGQBTgEBJAKQADgKALgBIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARAKIAKAMIAFAGIAbgFIAHAAMgA4AnPg");
	this.shape_6.setTransform(377.3,123.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgOQBqgOCxhLQDChSBZgZQBygfCUgRQBogNCdgJQCigJBaACQCNgCBtgpQBfgmDAhHQC7hFBmgTQBqgTCJgSQBXgPCmgIQCbgHBZgKQCBgNBqggQB/gmDjh2QDnh6CEgfQDCgyEdgJQBigPCwAKQCbgDBzgOQCzgSCxgpQCzgqCDhFIAsAYQDegUDQADQBVgEBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_7.setTransform(377.3,123.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAEBqgMQBqgNCxhJQDDhSBagYQBzggCVgSQBpgNCagKQCggKBbADQCMgBBtgrQBfgnDAhFQC6hEBngQQBqgTCKgUQBYgQClgJQCagIBagLQCAgNBqggQB/gmDkh1QDoh4CGgfQDBgwEZgLQBjgSCwAKQCbgEB1gPQCxgUCxgnQCzgoB+hBIAxAWQDfgUDNADQBXgHBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_8.setTransform(377.3,123.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgMQBqgLCyhJQDDhRBagYQB0ggCWgSQBrgPCYgKQCegLBbADQCMABBsgsQBfgpDAhDQC7hBBngRIDzglQBagSCkgKQCagKBagLQB/gOBqggQB/glDkh1QDph3CIgdQDBgvEVgOQBkgUCwAKQCbgGB1gQQCxgUCxgmQCzgmB7g+IA1AVQDegTDMABQBYgIBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_9.setTransform(377.3,123.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgLQBqgKCzhIQDChPBdgZQBzggCWgTQBtgPCXgLQCbgMBdAEQCKACBsguQBfgqDAhBQC7g/BngPID0gnQBbgTCjgMQCagLBagLQB+gOBqggQB/glDlh0QDqh2CJgcQDBgtEQgRQBmgWCwAKQCbgHB2gRQCwgVCxgkQCzglB2g7IA6ATQDfgQDJgCQBagIBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_10.setTransform(377.3,123.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgKQBqgICzhHQDEhQBdgYQBzggCXgTQBvgQCUgNQCZgMBeAFQCKADBrgvQBfgsDAg/QC7g9BngOQBrgPCJgYQBdgVCjgNQCYgMBbgLQB9gPBqggQB/gmDmhxQDrh2CKgaQDCgsELgTQBngZCwAKQCbgIB4gTQCugWCxgiQCzgjByg3IA/ASQDegQDIgDQBbgLBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_11.setTransform(377.3,123.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgIQBqgIC0hGQDDhOBegZQB1gfCXgUQBygRCRgOQCWgNBfAHQCKADBqgwQBfguDAg9QC7g7BogMQBqgPCJgYQBfgYCigOQCYgNBbgMQB8gPBqggQB/gmDmhwQDsh0CMgaQDCgpEHgWQBogcCwAKQCbgJB5gUQCugXCwggQCzgiBvg0IBCARQDfgPDFgEQBdgMBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_12.setTransform(377.3,123.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgHQBqgGC0hHQDDhMBggZQB1gfCYgVQBzgQCQgPQCTgPBgAIQCJAEBqgyQBfgvDAg7QC8g5BngMQBrgMCJgbQBggYChgPQCYgOBagNQB8gQBqggQB/glDnhwQDshyCPgZQDBgpEDgYQBpgeCwAKQCbgLB6gVQCtgXCxgfQCyggBqgxIBHAPQDggNDCgGQBfgOBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_13.setTransform(377.3,123.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgGQBqgFC1hFQDDhMBhgZQB2gfCYgUQB1gTCNgPQCRgQBhAIQCJAGBpgzQBfgxDAg5QC8g3BogKQBqgMCJgcQBigaChgQQCWgQBbgNQB7gQBqggQB/glDohvQDthyCQgWQDCgoD9gbQBrggCwAKQCcgMB7gWQCsgZCwgdQCygeBmgtIBMANQDggMDAgIQBggPBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_14.setTransform(377.3,123.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgFQBqgEC1hEQDEhKBigZQB2gfCZgWQB3gTCKgRQCPgQBiAJQCIAHBqg1QBegyDAg2QC9g1BngKQBqgLCKgdQBjgbCfgSQCWgRBcgNQB6gRBqggQB/glDphuQDthwCSgWQDBglD6geQBsgjCwAKQCcgOB8gWIFbg1QCxgdBjgrIBQAOIGegWQBigPBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_15.setTransform(377.3,123.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgEQBqgCC2hEQDEhKBjgZQB2geCZgXQB5gTCJgSQCMgSBjALQCHAJBqg3QBeg0DAg0QC9gzBngJQBqgJCKgfQBmgdCcgTQCXgSBcgOQB5gRBqggQB/gmDqhsQDuhvCTgUQDCgkD0ggQBugmCwAKQCcgPB8gXIFcg1QCwgbBfgnIBVAMQDfgLC9gLQBjgRBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_16.setTransform(377.3,123.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgCQBqgCC3hCQDDhKBlgYQB2geCagXQB8gVCGgTQCKgTBjAMQCHAKBpg4QBeg2DAgzQC9gwBogHQBqgJCKggQBngfCbgTQCXgUBcgPQB4gRBqggQB/gmDrhrQDuhtCWgUQDBgiDwgjQBvgoCwAKQCcgQB+gZQCpgbCxgZQCxgZBagjIBZAJQDggJC6gMQBlgUBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_17.setTransform(377.3,123.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgBQBqAAC3hDQDEhHBmgZQB2geCcgYQB9gVCDgUQCHgUBmANQCFAKBpg5QBeg3DAgwQC9gvBogGQBqgICLghQBnghCbgUQCWgVBdgPQB3gSBqggQB/gmDshqQDuhsCYgTIGthFQBwgrCwAKQCcgRB/gaQCogdCxgXQCwgXBXghIBeAJQDggHC4gPQBmgUBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_18.setTransform(377.3,123.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAEBqACQBqAAC4hCQDEhGBngZQB3geCbgYIEBgrQCEgVBnAOQCFAMBog7QBeg5DAguQC9gtBpgFQBqgGCKgkQBqghCZgXQCVgVBegQQB2gSBqggQB/gmDthoQDvhrCagSQDAgfDogoQBxgtCwAKQCcgSCAgbQCngeCxgVQCwgWBSgdIBjAHQDggGC2gQQBogXBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_19.setTransform(377.3,123.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKIEJAHQBqACC5hBQDDhGBpgZQB3geCcgZIEBgtQCCgWBnAPQCEAOBog9QBfg6DAgsQC8grBpgDQBqgGCKgkQBrgkCagXQCUgXBegQQB1gTBqggQB/glDthoQDxhqCbgRQDBgcDigsQBzgvCwAKQCcgUCCgcQCmgeCwgUQCwgUBPgaIBnAHQDggHCzgSQBqgXBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_20.setTransform(377.3,123.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKIEJAIQBqADC6hAQDDhFBpgZQB5gdCcgaIEAgvQCAgXBoARQCEANBng9QBfg8DAgqQC9gpBpgDQBpgDCLgnQBsgkCZgZQCUgYBegRQB0gTBqggQB/glDuhnQDxhoCdgRQDBgaDdguQB1gyCwAKQCcgVCDgeQClgfCwgRQCxgTBJgXIBsAGQDhgFCwgUQBsgYBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_21.setTransform(377.3,123.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAEQBqAFC6hAQDEhDBqgaQB5gdCdgaQCFgZB6gXQB+gYBpARQCDAPBnhAQBfg9DAgoQC9gnBpgBQBqgDCKgoQBugmCXgaQCVgZBegSQBzgTBqggQB/glDvhmQDyhnCfgPQC/gZDagwQB2g1CwAKQCcgWCEgfQCkggCwgQQCwgRBGgTIBxADQDhgDCugWQBtgaBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_22.setTransform(377.3,123.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAFQBqAGC7g+QDDhEBsgYQB5geCegbQCHgZB5gYQB6gZBqASQCDAPBmhAQBfg/DAgmQC9gkBqgBQBqgBCKgqQBvgoCXgbIDxgtQBzgTBqggQB/gmDvhkQDzhmChgOQDAgWDVg0QB3g3CwAKQCdgYCEgfQCkghCvgPQCwgPBCgQIB2ACQDggCCtgXQBugbBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_23.setTransform(377.3,123.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAGQBqAIC8g/QDDhCBugZQB5gdCegbQCJgaB2gaQB4gaBrATQCCARBmhBQBfhBDAgjQC9gjBqABQBqgBCKgrQBygqCVgcIDxguQBygUBqggQB/glDwhkQDzhkCjgNQDAgVDRg3QB4g5CwAKQCcgZCGggQCjgjCwgNQCwgNA9gNIB6ACQDhgCCpgYQBxgdBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_24.setTransform(377.3,123.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAIQBqAHC8g9QDEhABvgaQB4gdCfgcQCMgZBzgcQB3gbBrAUQCCATBlhEQBfhCDAghQC+ghBpABQBrACCKgtQBzgrCUgdIDxgxQBxgUBqggQB/glDxhjQD0hjClgMQC/gTDNg5QB5g8CwAKQCcgbCHghQCigjCwgLQCwgMA5gJIB/AAQDggBCogaQBygeBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_25.setTransform(377.3,123.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAJQBqAJC9g8QDEhABvgZQB6gdCfgcQCOgcBxgcQBzgcBuAVQCAAUBlhFQBfhEDAggQC+geBqADQBqACCKguQB1gtCUgeIDwgyQBwgVBqggQB/glDyhiQD0hiCmgKQDAgSDIg7QB7g/CwAKQCdgcCHgiQChglCwgJQCwgKA1gGICDgCQDhABClgcQB0gfBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_26.setTransform(377.3,123.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAKQBqAKC9g7QDEg/BxgZQB7gdCggdQCOgcBwgdQBxgdBuAWQCAAVBkhHQBfhFDAgdQC+gcBqADQBqADCKgvQB3gvCTgfIDwg0QBvgVBqggQB/gmDzhfQD0hiCpgIQC/gRDDg+QB9hBCwAKQCdgdCIgjQCggmCwgHIDhgMICIgDQDgACCkgeQB1ggBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_27.setTransform(377.3,123.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAMQBqALC+g7QDEg+BygZQB6gcChgfQCRgcBtgeQBvgeBvAXQB/AWBkhIQBfhHDAgbQC/gaBqAEQBqAFCJgyQB5gvCSghIDwg1QBugWBqggQB/gmD0heQD1hgCrgIQC+gOC/hCQB+hDCwAKQCdgeCKglQCfgmCvgGQCwgHAsABICNgFQDhADCigfQB2gjBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_28.setTransform(377.3,123.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqANQBqAMC+g5QDFg+BzgZQB7gcChgeQCTgeBqggQBtgeBwAYQB/AXBjhJQBfhJDAgZQC/gYBqAGQBqAFCKgyQB6gyCRgiQCQghBggWQBtgWBqggQB/gmD1hdQD1hfCsgGQDAgNC6hEQB/hGCwAKQCdgfCLgnQCegnCvgEQCvgFAqADICRgEQDhADCfghQB4gjBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_29.setTransform(377.3,123.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAEBqAPQBqAOC/g6QDFg7B0gaQB7gcCigfQCVgeBpghQBpgfBxAZQB+AYBjhLQBfhKDAgXQC/gXBqAIQBqAGCKg0QB8gyCQgkQCPgjBhgWQBsgWBqggQB/gmD1hcQD3hdCugGQC/gLC1hGQCBhJCwAKQCdghCMgnQCdgoCvgDQCwgDAkAHICWgHQDhAGCdgjQB6gmBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_30.setTransform(377.3,123.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAPQBqAQDAg5QDEg7B1gaQB8gcCjgfQCXggBmghQBnghByAbQB+AZBihMQBfhMDAgVQDAgUBqAIQBpAICLg1QB9g1CPglQCOgkBigWQBrgXBqggQB/glD2hcQD4hcCvgFQC/gJCyhJQCBhLCwAKQCdgiCNgoQCdgpCvgBQCugCAiAKICagIQDhAGCagkQB8gnBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_31.setTransform(377.3,123.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAQQBqARDAg4QDFg6B2gZQB9gdCjgfQCZggBjgiQBlgjBzAcQB9AaBihOQBfhNDAgSQDAgTBqAKQBqAICKg3QB/g2COgmQCOglBigWQBqgYBqggQB/glD3hbQD4hbCxgDQC/gICthMQCDhNCwAKQCdgkCOgpQCcgqCvABQCvAAAcANICfgJQDhAHCZglQB9goBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_32.setTransform(377.3,123.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqARQBqATDBg4QDFg5B4gaQB8gbCkghQCaghBigjQBigjB0AcQB9AcBhhPQBfhPDAgQQDAgRBqAKQBqALCLg5QCAg4CNgnQCOgmBhgXQBqgYBqggQB/glD3haQD5hZC0gDQC+gFCphPQCEhQCwAKQCdgkCPgrQCbgqCvACQCvABAYARICjgLQDiAICWgnQB/gqBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_33.setTransform(377.3,123.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqATQBqATDCg3QDFg4B5gZQB9gcCkghQCcgiBggkQBgglB1AeQB7AdBhhQQBfhRDAgPQDAgOBqAMQBrAKCKg5QCCg5CNgoQCMgoBigXQBpgZBqggQB/gmD4hXQD6hZC1gBQC/gECjhRQCGhTCwAKQCdgmCQgrQCbgsCuAEQCuADAVAUICogMQDiAJCUgpQCAgqBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_34.setTransform(377.3,123.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAUQBqAUDDg2QDEg2B6gbIEig9QCfghBdgmQBegmB2AgQB7AdBghSQBehSDBgNQDBgMBqANQBrAMCKg7QCEg7CLgpQCMgpBigYQBogZBqggQB/glD5hXQD6hXC3AAQC/gDCfhUQCHhVCwAKQCdgnCSgsQCYgtCvAFQCuAFARAXICsgNQDiAKCSgqQCCgsBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_35.setTransform(377.3,123.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAWQBqAUDDg1QDFg2B7gaIEkg9QCggiBbgnQBbgnB3AhQB7AeBfhTQBfhUDAgLQDAgJBrAOQBrANCKg9QCGg8CKgrQCMgqBigZQBngZBqggQB/glD6hWQD6hWC6ABQC+gBCahWQCJhYCwAKQCdgpCTgtQCYgtCuAGQCuAHANAbICxgPQDiAMCPgsQCEgvBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_36.setTransform(377.3,123.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAWQBqAXDEg0QDEg2B9gZIEkg/QCjgjBZgnQBYgnB4AgQB6AgBfhVQBfhVDAgIQDBgIBqAOQBrAPCKg/QCHg9CKgsQCLgrBjgZQBmgaBqggQB/glD7hVQD7hUC7ACQC+AACWhZQCKhaCwAKQCegqCTgvQCXguCuAJQCuAIAIAeIC2gQQDjANCMguQCGgwBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_37.setTransform(377.3,123.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAYQBqAXDFgzQDEg0B+gaIElg/QCkgkBXgoQBXgpB4AiQB6AhBehWQBfhXDAgGQDBgGBrAQQBrAPCKg/QCJhACIgsQCLguBjgZQBlgaBqggQB/gmD8hTQD7hUC9AEQC/ADCRhdQCLhcCwAKQCegrCVgvQCVgwCvAKQCtAKAFAhIC6gRQDjAOCKgwQCHgwBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_38.setTransform(377.3,123.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAgBIAAgEIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIAKgIIAFgHQAJgKAIAAIACAAIACgBQCbhkEOAEQBaAACyAKQCfAFBqAZQBqAZDFgzQDFgzB/gaQB/gaCnglQCmglBUgqQBVgpB5AjQB5AjBehZQBehYDBgEQDCgEBqARQBrAQCKhBQCLhACHguQCKgvBkgaQBkgaBqggQB/glD9hTQD8hSC+AEQC/AFCMhfQCNhfCwAKQCegsCVgxQCVgxCvAMQCuAMgBAlIC/gTQDjAPCJgyQCIgxBJAJQADgKALgBIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPgEg5iAClIAAAAIAAgCIAAACgEA5jgTBIAEgBIgFgEg");
	this.shape_39.setTransform(377.3,123.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAYQBqAXDFgzQDEg0B+gaIElg/QClgkBWgoQBXgpB4AiQB6AhBehWQBfhXDAgGQDBgGBrAQQBrAPCKg/QCJhACIgsQCLguBjgZQBlgaBqggQB/gmD8hTQD7hUC+AEQC+ADCRhdQCLhcCwAKQCegrCVgvQCVgxCvALQCtAKAFAiIC6gSQDjAOCKgwQCHgwBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_40.setTransform(377.3,123.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAWQBqAXDEg0QDEg1B9gaIElg+QCigkBZgnQBYgnB4AgQB6AgBfhVQBfhVDAgIQDBgIBqAPQBrAOCKg+QCHg+CKgsQCLgrBjgZQBmgaBqggQB/gmD7hTQD7hVC7ACQC+ABCWhaQCKhaCwAKQCegqCTgvQCXguCuAJQCuAIAIAeIC2gQQDjANCMguQCGgwBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_41.setTransform(377.3,123.4);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAWQBqAVDDg2QDFg1B7gaIEkg9QCggkBbgmQBbgnB3AhQB7AfBfhUQBfhUDAgKQDBgKBqAOQBrANCKg9QCGg8CKgrQCMgqBigYQBngaBqggQB/glD6hWQD7hWC5ABQC+gBCahWQCJhYCwAKQCdgpCTgtQCYguCuAHQCvAHAMAbICxgPQDiAMCPgsQCEgvBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_42.setTransform(377.3,123.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAUQBqAVDDg3QDEg2B6gaIEig+QCfghBdgmQBegmB2AgQB7AeBghSQBehTDBgMQDBgMBqAMQBrAMCKg7QCEg6CLgqQCMgpBigYQBogZBqggQB/glD5hXQD7hXC2AAQC/gDCfhUQCHhVCwAKQCdgnCSgsQCYguCvAGQCvAFAPAXICtgNQDiALCSgrQCCgsBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_43.setTransform(377.3,123.4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqATQBqATDCg2QDFg4B5gaQB9gbCkgiQCdghBfglQBggkB1AdQB8AdBghQQBehRDBgOQDBgOBpAMQBrALCKg6QCDg6CMgoQCNgoBhgXQBpgZBqggQB/gmD4hXQD6hZC1AAQC/gFCjhRQCGhTCwAKQCdgmCRgrQCZgsCvADQCvAEATAUICpgLQDiAJCUgqQCAgqBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_44.setTransform(377.3,123.4);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqASQBqARDBg3QDFg4B4gaQB8gbCkgiQCbggBigjQBigkBzAdQB9AcBhhQQBfhPDAgQQDAgQBqAKQBqAKCLg4QCAg4CNgnQCNgnBjgXQBpgYBqggQB/gmD4hYQD4haC0gCQC/gGCohOQCEhRCwAKQCdglCPgqQCbgrCvACQCvACAYASICjgLQDjAICVgoQB/gpBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_45.setTransform(377.3,123.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAQQBqASDAg5QDFg5B3gaQB8gcCjggQCaggBjgiQBkgjBzAcQB+AaBhhOQBfhNDAgSQDAgTBqAKQBqAJCKg3QCAg2CNgmQCOgmBigWQBqgYBqggQB/glD3hbQD4haCygDQC/gICshMQCDhOCwAKQCdgjCOgqQCcgqCvABQCvAAAbAOICggKQDhAICYgmQB+gpBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_46.setTransform(377.3,123.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAPQBqAQDAg4QDEg8B2gZQB8gcCjgfQCXggBlghQBnghByAaQB+AZBihMQBfhMDAgVQDAgTBqAIQBqAICKg2QB9g1CPgkQCPgkBhgXQBrgXBqggQB/glD2hcQD3hbCxgFQC/gJCwhKQCChLCwAKQCdgiCOgoQCcgpCvgBQCugCAhALICbgJQDhAHCagkQB8gnBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_47.setTransform(377.3,123.4);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAEBqAPQBqAPC/g6QDFg8B0gZQB8gcCigfQCVgeBoghQBpghBxAaQB+AYBjhKQBfhLDAgXQC/gWBqAIQBqAGCKg0QB8gzCQgjQCPgjBhgWQBsgXBqggQB/glD2hcQD2heCvgFQC/gLC0hHQCBhJCwAKQCdghCNgnQCcgpCwgCQCvgDAjAIICXgHQDiAFCbgjQB7gmBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_48.setTransform(377.3,123.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqANQBqANC/g6QDEg8B0gaQB7gcChgeQCTgeBrggQBrggBwAZQB/AYBjhKQBfhJDAgYQC/gYBqAGQBqAGCKgzQB7gyCQgiQCPgjBigVQBsgWBqggQB/glD1hdQD2hfCsgGQC/gNC5hEQCAhHCwAKQCdggCLgmQCegnCvgEQCwgFAoAEICSgFQDhAECfghQB4glBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_49.setTransform(377.3,123.4);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAMQBqALC+g6QDEg9BzgaQB7gcCggfQCRgcBtgeQBugfBvAXQB/AXBkhIQBfhIDAgaQC/gbBqAGQBpAECLgxQB4gwCSgiQCQghBhgUQBtgWBqggQB/glD0heQD1hhCrgHQDAgOC9hCQB+hECwAKQCdgfCKglQCfgmCvgFQCwgHArACICOgFQDhADChggQB3giBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_50.setTransform(377.3,123.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqALQBqAKC9g7QDFg/BwgZQB7gcCggeQCQgcBugdQBxgeBuAXQCAAVBkhHQBfhGDAgdQC+gcBqAFQBqADCKgwQB4gvCSggIDwg0QBvgVBqggQB/gmDzhfQD1hhCpgIQC/gQDChAQB9hBCwAKQCdgdCJgkQCggmCvgHIDggKICJgDQDgACCkgeQB1giBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_51.setTransform(377.3,123.4);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAKQBqAJC9g8QDEhABwgZQB6gdCfgcQCOgcBxgdQBygcBuAWQCAAUBlhGQBfhEDAgfQC+gdBqACQBqADCKgvQB2gtCTgeIDwgzQBwgVBqggQB/gmDzhgQD0hiCmgJQDAgTDHg7QB7hACwAKQCdgcCHgjQChgkCwgJQCwgKA0gFICEgCQDhABClgdQB0gfBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_52.setTransform(377.3,123.4);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAIQBqAJC8g9QDFhBBugZQB5gdCfgcQCMgaBzgcQB1gcBsAVQCCATBlhEQBfhDDAghQC+gfBpACQBrAACKgsQBzgsCUgdIDxgyQBxgUBqggQB/gmDxhhQD0hkCmgKQC/gUDLg5QB6g9CwAKQCdgbCGgiQCigjCwgLQCwgLA3gIICBgBQDgAACngbQBzgeBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_53.setTransform(377.3,123.4);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAHQBqAHC8g+QDDhABugaQB6gdCegbQCKgaB1gbQB4gbBqAUQCCASBmhCQBfhCDAgiQC+gjBpABQBqAACKgrQBzgqCUgdIDygvQBxgUBqggQB/gmDwhiQD0hlCkgLQC/gWDPg3QB5g6CwAKQCcgZCGgiQCjgiCwgMQCvgNA9gLIB7AAQDhgBCpgZQBxgdBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_54.setTransform(377.3,123.4);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAGQBqAGC7g+QDEhDBsgZQB5gdCegbQCHgaB5gZQB5gaBqATQCDARBmhBQBfhADAglQC9gkBqAAQBqgBCKgqQBwgoCWgcIDygtQBygUBqggQB/glDwhlQDzhlChgNQDAgXDTg0QB4g4CwAKQCcgYCFggQCkghCwgPQCwgOA/gPIB4ACQDggCCsgXQBvgdBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_55.setTransform(377.3,123.4);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAEQBqAFC7g+QDDhEBrgZQB4gdCegbQCGgYB6gYQB8gZBpASQCDAPBnhAQBfg+DAgnQC9glBpgCQBqgCCLgpQBugnCXgaIDygsQBzgTBqggQB/gmDvhlQDyhnCggNQDAgZDYgxQB2g2CwAKQCdgXCDgfQClggCvgQQCxgQBEgSIByADQDhgDCugWQBtgaBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_56.setTransform(377.3,123.4);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKIEJAJQBqADC6hAQDEhEBpgZQB4gdCegaID/gwQB/gXBoARQCEAOBng/QBfg8DAgpQC9gnBpgDQBqgDCKgnQBtgmCYgZQCUgZBfgRQBzgTBqggQB/gmDuhlQDyhpCdgOQDBgaDcgwQB1gzCwAKQCdgWCCgeQClgfCwgRQCxgSBHgVIBuAEQDhgECwgUQBsgZBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_57.setTransform(377.3,123.4);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKIEJAHQBqACC5g/QDEhGBpgZQB3geCdgZIEAguQCBgWBnAPQCEAOBog9QBfg7DAgrQC9gpBpgEQBpgFCLglQBsgkCYgYQCUgYBfgQQB0gTBqggQB/gmDthmQDxhqCcgQQDBgbDgguQB0gwCwAKQCcgUCCgdQCmgfCwgTQCwgTBNgZIBpAHQDhgGCxgTQBrgYBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_58.setTransform(377.3,123.4);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqABQBqABC4hAQDFhHBngZQB3geCcgYIEBgsQCDgVBmAOQCFAMBog8QBfg5DAgtQC8gsBpgEQBqgGCKgkQBrgjCZgWQCVgXBegPQB1gTBqggQB/gmDthnQDwhrCbgRQDAgdDlgrQByguCwAKQCcgTCBgbQCngeCwgVQCwgVBQgbIBmAHQDggHC0gRQBpgWBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_59.setTransform(377.3,123.4);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqAAQBqAAC4hCQDDhHBngZQB3geCbgYQB+gWCCgUQCHgUBlANQCGALBog6QBeg4DAgvQC+guBngFQBqgHCLgjQBoggCbgXQCWgUBdgQQB2gSBqggQB/glDshqQDwhsCYgSIGqhGQBxgsCwAKQCcgSB/gbQCogcCxgXQCwgWBVgfIBgAIQDggHC2gPQBogWBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_60.setTransform(377.3,123.4);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgCQBqgBC3hCQDEhIBlgZQB3gfCagXQB8gUCFgUQCJgTBkAMQCGAKBpg4QBeg3DAgxQC9gwBogHQBqgHCKghQBoggCagUQCXgVBcgOQB4gSBqggQB/glDrhrQDvhtCXgUQDAggDvglQBvgpCwAKQCcgQB+gaQCpgdCxgWQCwgZBYgiIBdAJQDfgIC5gOQBmgTBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_61.setTransform(377.3,123.4);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgDQBqgCC2hDQDEhJBkgZQB2geCagXQB6gUCIgTQCKgSBjALQCIAJBpg3QBeg1DAgzQC9gyBogHQBqgKCJggQBngdCbgTQCYgTBcgPQB4gRBqggQB/glDrhsQDthuCWgUQDAgjDzgiQBugnCwAKQCcgPB9gZQCqgbCxgZQCxgaBbglIBYALQDggKC7gMQBkgSBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_62.setTransform(377.3,123.4);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgEQBqgEC2hDQDEhKBjgZQB1gfCagWQB4gTCJgSQCNgRBiAKQCIAIBqg2QBegzDAg1QC9g0BngIQBqgLCKgeQBlgcCdgTQCXgRBcgOQB5gRBqggQB/glDqhtQDthwCTgVQDBgkD3gfQBtglCwAKQCcgOB8gXIFbg1QCygcBggpIBTANIGdgWQBigQBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_63.setTransform(377.3,123.4);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgFQBqgFC1hEQDEhLBigZQB1gfCZgVQB2gTCLgRQCQgQBhAJQCJAHBqg0QBegyDAg3QC8g2BogKQBqgLCKgdQBigbCggRQCXgQBbgOQB6gQBqggQB/gmDphuQDthwCRgXQDCglD6gdQBsgiCwAKQCcgNB7gWQCsgZCwgdQCxgdBkgsIBPAOIGfgVQBhgPBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_64.setTransform(377.3,123.4);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgGQBqgGC1hGQDDhLBggZQB2gfCYgVQB1gSCNgPQCSgQBhAIQCJAGBpgzQBfgwDAg6QC8g3BogLQBqgMCJgcQBigZCggQQCXgPBbgNQB7gQBqggQB/gmDohuQDshyCQgYQDBgnD/gbQBrgfCwAKQCbgLB7gWQCtgZCwgeQCxgeBpguIBKAOQDfgNDBgHQBggPBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_65.setTransform(377.3,123.4);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgHQBqgIC0hGQDEhNBegYQB1gfCYgVQBygQCRgPQCUgPBgAIQCJAEBqgxQBfgvDAg8QC8g5BngMQBqgNCKgaQBfgZCigOQCXgOBbgMQB8gQBqggQB/gmDnhvQDsh0COgZQDBgoEEgYQBpgdCwAKQCbgKB6gUQCtgYCxggQCxggBsgyIBGAQQDggODDgFQBegNBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_66.setTransform(377.3,123.4);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgIQBqgJC0hGQDDhOBegZQB0gfCYgUQBwgQCSgOQCWgNBfAGQCLADBqgwQBfgtDAg9QC7g8BogNQBqgOCJgZQBfgXCigNQCXgMBcgNQB8gPBqggQB/gmDmhwQDsh1CMgZQDBgrEIgVQBogbCwAKQCcgJB3gTQCvgXCwghQCzgiBwg1IBBARQDfgPDGgEQBcgMBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_67.setTransform(377.3,123.4);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgKQBqgJCzhIQDDhOBdgZQB0gfCWgUQBvgPCUgNQCagNBdAGQCLACBrgvQBfgrDAg/QC7g+BngPQBqgOCKgYQBcgVCkgMQCYgMBbgLQB9gPBqggQB/gmDlhyQDrh1CLgbQDBgsENgSQBmgZCwAKQCbgIB3gSQCvgWCxgiQCzgkBzg4IA+ASQDegQDIgCQBbgKBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_68.setTransform(377.3,123.4);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgLQBqgLCzhIQDChPBcgZQB0gfCVgTQBtgPCXgMQCcgLBcAEQCLABBsgtQBfgqDAhCQC7g/BngPID0gnQBagTCkgLQCagKBagMQB+gOBqggQB/gmDlhzQDqh3CIgcQDCgtERgQQBlgWCwAKQCbgGB2gSQCwgUCxglQCzglB4g8IA4AUQDfgRDKgBQBZgIBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_69.setTransform(377.3,123.4);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgMQBqgMCyhIQDDhSBagYQB0ggCVgSQBqgOCagKQCdgLBcADQCMAABsgsQBfgoDAhEQC7hBBngRQBpgRCKgUQBagSCkgKQCagJBagMQB/gNBqggQB/gmDkh0QDph4CHgdQDCgvEVgNQBkgUCwAKQCbgFB1gQQCxgUCxgmQCzgnB8g+IA0AUQDegSDMABQBYgIBJALQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_70.setTransform(377.3,123.4);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgOQBqgNCxhJQDDhRBZgZQBzggCVgSQBpgNCbgJQCggKBbADQCMgBBtgrQBfgnDAhFQC6hEBngSQBqgSCKgUQBXgPCmgKQCagHBagLQCAgNBqggQB/gmDkh1QDoh5CEgfQDDgwEZgLQBjgRCwAKQCbgEB0gPQCygTCxgoQCzgoB/hCIAwAWQDfgTDOACQBWgFBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_71.setTransform(377.3,123.4);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS2IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgOQBqgPCxhKQDChTBYgYQBzghCUgQQBngMCdgJQCjgJBZACQCOgDBtgoQBfgmDAhHQC7hGBmgSQBqgUCJgSQBWgOCngJQCbgGBZgKQCBgNBqggQB/gmDjh2QDnh7CDgfQDCgzEfgIQBhgOCwAKQCbgDBzgOQCzgRCxgqQCygqCFhFIArAYQDegVDRAEQBUgEBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_72.setTransform(377.3,123.4);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS3IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgFAAgEQgCgKABgEQABgDAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgHQAJgKAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgQQBqgPCvhLQDDhTBYgZQBxggCVgRQBlgMCfgHQClgIBYAAQCPgDBtgnIEfhuQC6hIBngTQBqgVCJgQQBVgNCngHQCbgFBZgKQCCgMBqggQB/glDih4QDnh7CCghQDCg1EigFQBggMCwAKQCbgCBygNQC0gRCxgqQCygsCIhIIAnAZQDegWDTAGQBTgDBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_73.setTransform(377.3,123.3);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS5IAmvZIAAgHIABgRIgBgKQAAgFACgEIAAAAIAAgFIAEAAIAEgFQAFgGgBgPQgBgOADgGQAFgIADgEIAEgOIAEgJQACgFAAgEQgCgJABgEQABgDAEgDIAIgGIAHgJQAEgFAEgCIAHgDIALgIIAEgGQAJgLAIAAIADAAIABgBQCahjEPADQBaABCyAJQCfAFBqgRQBqgQCvhLQDDhVBWgYQByghCTgQQBjgLCigHQCmgGBZAAQCOgFBugmQBfgiDAhMQC6hKBngVQBpgVCKgPQBSgMCpgFQCcgFBYgIQCDgNBqgfQB/gmDhh5QDmh8CAgiQDCg2EogDQBegJCwAJQCbAABxgMQC0gQCxgsQC0gtCMhMIAiAaQDdgWDWAHQBRgCBJAKQADgKALgBIAFgBIgBgCIBHAEIBCACQASABAHAEQAGACAMAJIARAKIAKALIAFAHIAbgFIAHAAMgA4AnPg");
	this.shape_74.setTransform(377.3,123.2);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS6IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgEIAEgOIAEgJQACgFAAgEQgCgKABgDQABgEAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgGQAJgLAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgSQBqgSCuhMQDEhWBUgYQBxghCTgOQBhgLCkgFIEBgIQCOgFBvgmQBgggC/hOQC6hMBmgVQBpgXCKgOQBRgKCqgDQCcgEBYgJQCEgLBqggQB/glDgh6QDmh+B+gjQDDg3ErAAQBdgICwAKQCbABBvgLQC2gPCxguQC0gvCPhPIAeAbQDegXDXAJQBQAABJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_75.setTransform(377.3,123);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS8IAmvYIAAgIIABgRIgBgKQAAgFACgEIAAAAIAAgEIAEAAIAEgGQAFgGgBgOQgBgPADgGQAFgHADgFIAEgNIAEgJQACgGAAgDQgCgKABgEQABgDAEgDIAIgGIAHgIQAEgGAEgCIAHgCIALgIIAEgHQAJgKAIAAIADAAIABgBQCahkEPADQBaABCyAKQCfAEBqgTQBqgTCuhMQDChXBUgYQBxghCSgPQBfgJCngFIECgHQCPgHBvgjQBfgfC/hQQC6hOBngWQBpgZCKgLQBPgJCrgDQCcgCBYgIQCFgLBqggQB/gmDfh7QDlh/B9gkQDCg5EwADQBcgFCwAKQCbACBugKQC3gOCxgwQC0gwCUhSIAYAdQDfgZDZAKQBOABBJAKQADgKALgBIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARAKIAKAMIAFAGIAbgFIAHAAMgA4AnPg");
	this.shape_76.setTransform(377.3,122.8);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS+IAmvZIAAgHIABgSIgBgJQAAgGACgDIAAAAIAAgFIAEAAIAEgFQAFgGgBgPQgBgPADgFQAFgIADgEIAEgOIAEgJQACgFAAgEQgCgJABgEQABgEAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgGQAJgLAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgUQBqgUCthOQDDhYBSgYQBxghCRgOQBegJCogDQCvgEBUgEQCRgHBvgiQBfgeC/hSQC6hPBngYQBpgZCKgLQBOgHCqgCQCeAABYgIQCFgLBqggQB/glDeh9QDliAB6gkQDDg8E0AGQBbgDCwAKQCaAEBugJQC4gNCxgyQC0gyCXhVIAVAeQDdgaDcANQBNACBJAKQADgKALgCIAFgBIgBgBIBHADIBCADQASABAHAEQAGACAMAJIARAKIAKALIAFAHIAbgFIAHAAMgA4AnPg");
	this.shape_77.setTransform(377.3,122.7);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("rgba(102,153,255,0.318)").s().p("Eg68AS/IAmvYIAAgIIABgRIgBgKQAAgFACgDIAAAAIAAgFIAEAAIAEgFQAFgHgBgOQgBgPADgGQAFgHADgEIAEgOIAEgJQACgFAAgEQgCgKABgDQABgEAEgDIAIgFIAHgJQAEgFAEgCIAHgDIALgIIAEgGQAJgLAIAAIADAAIABgBQCahjEPADQBaAACyAKQCfAFBqgWQBqgVCshOQDDhZBSgYQBvghCRgOQBcgHCqgDQCxgDBUgFQCRgIBwghQBfgcC/hUQC6hRBmgaQBqgaCJgIQBNgHCrAAQCfABBXgIQCGgKBqggQB/gmDeh9QDkiBB4gmQDDg9E4AIQBaAACwAKQCaAFBtgIQC4gMCygzQCzg0CdhZIAPAgQDegbDeAOQBLAEBJAKQADgKALgCIAFgBIgBgCIBHAEIBCADQASABAHADQAGADAMAIIARALIAKALIAFAHIAbgGIAHAAMgA4AnPg");
	this.shape_78.setTransform(377.3,122.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_71}]},1).to({state:[{t:this.shape_72}]},1).to({state:[{t:this.shape_73}]},1).to({state:[{t:this.shape_74}]},1).to({state:[{t:this.shape_75}]},1).to({state:[{t:this.shape_76}]},1).to({state:[{t:this.shape_77}]},1).to({state:[{t:this.shape_78}]},1).to({state:[{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-6.6,754.6,257.9);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.back();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,640,305);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.potop5640x305rez_03();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,32,43);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.potop5640x305rez_06();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,31);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.potop5640x305rez_09();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,47,84);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(102,153,255,0.318)").s().p("AHfCvQgJAAgDgEQgCgFACgDQgNABgKgCQgFgBgDgDQgBgCAAgEIgBgHIgFgIIgBgJIgFgKQgCgGAAgMIABgiQAAgNgCgGIgEgIQgCgFABgDQgIABgDgMIgCgRIgEgLQgDgIAAgFIABgMQABgHgCgFQgCgFgJgFQgLgFgDgEQgDgEgBgGIgEABIgIADIgUACIgWABIgCABQgFABgDAEIgEAKQgEAFgLgBIgjAAQgJAAgDgFQgCgEAEgFQAEgDAFgCQjZACjigNQglgCgOANIgIAKQgFAGgFACQgEACgOAAQgRgBgKgCQgPgEgIgJIhHgJIgEAIQgFAMgCAOIAJgBQAGgCADABQAFAAAEADQAEADAAAEQgBAFgGAEIgLAGQgIAHAAASIABBYQAAAPgBAHQgEAQgSATQgKAKgHACQgFACgLAAIgrgCQgIAAgEgCIgKgHIgGgDIgFgEQgDgDAAgJIAAgiQAAgVACgKQADgIAIgQIAKgRIAHgKQADgEAAgLIgBhaQAAgOACgHQAGgNAAgHQgDgNACgGQADgFAMgGQASgIAOgPIABABIAuABQAJAAADAEQADADAAAFIgBAKQgBAGAEAJIAFAPQABAFgBAGQCeAACgAEQgEgEgBgEQAAgDACgCQABgBAAAAQABAAABgBQAAAAABAAQAAAAABAAIADgCIA6ABIAIABQAFAEAAAEQAAAEgEADIgBABIAAAAIgBABIABAAQCdAECgAKIAAgBIAEgIQACgEAIgBQAKgCACgCIAGgGQAFgDAHAAIAFgBIAAAAIAIgHIAHgIQAEgDAJAAIAEAAQACgDACgBQABAAABAAQABAAAAgBQABAAAAAAQAAgBAAAAIAVABQAJgEAKAIIAHAJIABAAQAKAFAHARIAHASIADAKIAFAKIAAAIIABAIIAGAHQAFADABAEIAAAKQABACADADIADAEIAAAJQAAADAEAGQACABAAAEIAAAHQABAHAEAGIAHAPIACAJQACAEAGAGIAEAIIAEAKQACAFAAARIAAATIABAFQABAMgFAGQgEAEgKADIgPAGQAFACAAAFQABAEgHAGIgFAEQgDACgHAAg");
	this.shape.setTransform(59.6,131.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.instance = new lib.potop5640x305rez_15();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,118,152);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.potop5640x305rez_18();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,50,119);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ert();
	this.instance.setTransform(502.7,-103.2);

	this.instance_1 = new lib.cvb();
	this.instance_1.setTransform(497.9,-104.8);

	this.instance_2 = new lib.cbvcb();
	this.instance_2.setTransform(490.5,-101.5);

	this.instance_3 = new lib.ertret();
	this.instance_3.setTransform(483.4,-100.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(502.7,-103.2,106,184);


(lib.Tween22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.w256h2561380453915MouseOptions256x25632();
	this.instance.setTransform(-30,-30,0.234,0.234);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30,-30,60,60);


(lib.Symbol36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AguA0IAAhnIAgAAIAAApIAPAAQAXgBAMAJQALAHAAARQAAAPgKAHQgLAIgTAAgAgOAdIAOAAQAPAAAAgLQAAgJgPAAIgOAAg");
	this.shape.setTransform(127,12.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhEA0IAAhnIAgAAIAABNIAVAAIAAhNIAeAAIAABNIAWAAIAAhNIAgAAIAABng");
	this.shape_1.setTransform(113.1,12.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAjA0IAAhnIAgAAIAABngAhCA0IAAhnIAgAAIAAApIARAAQAVgBAMAJQALAHAAARQAAAPgKAHQgLAIgRAAgAgiAdIAQAAQAPAAAAgLQAAgJgPAAIgQAAg");
	this.shape_2.setTransform(97.2,12.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAgA0IAAhOIgVBOIgVAAIgVhOIAABOIgaAAIAAhnIAqAAIAPA+IAQg+IAqAAIAABng");
	this.shape_3.setTransform(82.5,12.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AATA0IAAg4IglA4IgeAAIAAhnIAeAAIAAA4IAlg4IAeAAIAABng");
	this.shape_4.setTransform(64.7,12.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAhA/IAAgXIhAAAIAAAXIgaAAIAAgvIAKAAQAKgXgBggIAAgXIBWAAIAABOIAKAAIAAAvgAgJgjQABAWgIAdIAfAAIAAg0IgYAAg");
	this.shape_5.setTransform(52.6,13.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgqA0IAAhnIBUAAIAAAXIg0AAIAAAQIAwAAIAAAUIgwAAIAAAUIA1AAIAAAYg");
	this.shape_6.setTransform(41.5,12.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgvA0IAAhnIA7AAQAPABAIAHQAIAHAAALQAAAKgGAGQgEAFgHACQALACAFAGQAGAGAAAKQAAAIgEAGQgEAHgHADQgEADgIABIgOACgAgOAdIAOAAQAJAAADgCQADgEAAgFQAAgEgDgDQgDgDgJAAIgOAAgAgOgJIAOAAQAFAAADgDQADgDAAgEQAAgGgDgCQgDgDgFAAIgOAAg");
	this.shape_7.setTransform(30.7,12.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAXA0IgGgRIgiAAIgFARIghAAIAnhnIAhAAIAnBngAALAMIgLgkIgKAkIAVAAg");
	this.shape_8.setTransform(19.2,12.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AARA0IAAgqIghAAIAAAqIggAAIAAhnIAgAAIAAAlIAhAAIAAglIAgAAIAABng");
	this.shape_9.setTransform(7.5,12.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,133.6,23.1);


(lib.shape109 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(3,1,1).p("AETAAQAABxhRBRQhRBRhxAAQhwAAhRhRQhRhRAAhxQAAhwBRhRQBRhRBwAAQBxAABRBRQBRBRAABwg");
	this.shape.setTransform(27.5,27.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,58,58);


(lib.Символ54 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ53();
	this.instance.setTransform(14.2,14.2,1,1,0,0,0,14.2,14.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.3,scaleY:0.3},4).to({scaleX:1,scaleY:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,28.3,28.3);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ52();
	this.instance.setTransform(14.2,14.2,1,1,0,0,0,14.2,14.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Символ 53
	this.instance_1 = new lib.Символ54();
	this.instance_1.setTransform(14.2,14.2,1,1,0,0,0,14.2,14.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,30.3,30.3);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ49();
	this.instance.setTransform(79,12,1,1,0,0,0,79,12);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.32},4).to({alpha:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,157.9,24);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ47();
	this.instance.setTransform(131.9,27.2,1,1,0,0,0,131.9,27.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,263.9,54.6);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ48();
	this.instance.setTransform(135.8,42.5,1,1,0,0,0,131.9,27.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.32},4).to({alpha:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3.9,15.3,263.8,54.6);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ45();
	this.instance.setTransform(19.7,24.2,1,1,0,0,0,19.7,24.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.73,scaleY:0.73,x:71.4},4).to({scaleX:1,scaleY:1,x:19.7},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,39.4,48.5);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ40();
	this.instance.setTransform(21.7,26.2,1,1,0,0,0,21.7,26.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},4).to({alpha:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,43.4,52.5);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ46();
	this.instance.setTransform(-196.2,-19.4,0.583,0.583,0,0,0,136.6,38.1);

	this.instance_1 = new lib.Символ42();
	this.instance_1.setTransform(21.7,26.2,1,1,0,0,0,21.7,26.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1},{t:this.instance}]},1).to({state:[{t:this.instance_1}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ37();
	this.instance.setTransform(28.6,18.1,1,1,0,0,0,28.6,18.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},4).to({alpha:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,57.1,36.2);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ46();
	this.instance.setTransform(-196.2,-77.9,0.583,0.583,0,0,0,136.6,38.1);

	this.instance_1 = new lib.Символ39();
	this.instance_1.setTransform(28.6,18.1,1,1,0,0,0,28.6,18.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1},{t:this.instance}]},1).to({state:[{t:this.instance_1}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ32();
	this.instance.setTransform(19.8,11.8,1,1,0,0,0,19.8,11.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({alpha:0},0).wait(5).to({alpha:1},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,39.6,23.6);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ50();
	this.instance.setTransform(45.5,-63.3,0.799,0.799,0,0,0,79,12);

	this.instance_1 = new lib.Символ35();
	this.instance_1.setTransform(19.8,11.8,1,1,0,0,0,19.8,11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1},{t:this.instance}]},1).to({state:[{t:this.instance_1}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ36();
	this.instance.setTransform(20.4,12.1,1,1,0,0,0,20.4,12.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},4).to({alpha:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40.8,24.1);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.setTransform(448.9,-105.1,0.702,0.702,-0.9,0,0,586.6,-78.6);
	this.instance.alpha = 0.762;

	this._animationGuide_0 = new lib.Символ1();
	this._animationGuide_0.setTransform(25.1,7.9,0.702,0.702,0,0.9,-179.1,586.6,-78.6);
	this._animationGuide_0.alpha = 0.762;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this._animationGuide_0},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(7.8,-122.7,458.4,243.4);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.setTransform(377.3,125.7,1,1,0,0,0,377.3,125.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-6.6,754.6,257.9);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ6();
	this.instance.setTransform(16,21.5,1,1,0,0,0,16,21.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,32,43);


(lib.Символ1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// potop5640x305-rez_03.png
	this.instance_4 = new lib.Символ7();
	this.instance_4.setTransform(104.1,-21.5,1,1,0,0,0,14.1,39.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regX:14,rotation:-8.5,x:104.7,y:-22.8},9).to({regX:14.1,rotation:0,x:104.1,y:-21.5},10).wait(1));

	// Слой 3
	this.instance_5 = new lib.Символ38();
	this.instance_5.setTransform(103.8,51.5,1,1,0,0,0,28.6,18.1);
	new cjs.ButtonHelper(this.instance_5, 0, 1, 2, false, new lib.Символ38(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(20));

	// Слой 8
	this.instance_6 = new lib.Символ41();
	this.instance_6.setTransform(105.1,2.3,1,1,0,0,0,21.7,26.2);
	new cjs.ButtonHelper(this.instance_6, 0, 1, 2, false, new lib.Символ41(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(20));

	// potop5640x305-rez_06.png
	this.instance_7 = new lib.Символ5();
	this.instance_7.setTransform(106,-5.5,1,1,0,0,0,20,15.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({scaleY:1.08,y:-6.8},9).to({scaleY:1,y:-5.5},10).wait(1));

	// potop5640x305-rez_15.png
	this.instance_8 = new lib.Символ3();
	this.instance_8.setTransform(109.6,171,1,1,0,0,0,59.6,151);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({rotation:-1.5},9).to({rotation:0},10).wait(1));

	// potop5640x305-rez_09.png
	this.instance_9 = new lib.Символ4();
	this.instance_9.setTransform(102.5,4,1,1,0,0,0,23.5,42);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({regY:42.1,rotation:4.5,x:101.9,y:4.1},9).to({regY:42,rotation:0,x:102.5,y:4},10).wait(1));

	// potop5640x305-rez_18.png
	this.instance_10 = new lib.Символ2();
	this.instance_10.setTransform(103.1,-128.2,1,1,0,0,0,23.1,3.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({rotation:-0.9,x:103.8,y:-128.9},9).to({rotation:0,x:103.1,y:-128.2},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-198.4,-132,366.4,304);


(lib.Анимация4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ27();
	this.instance.setTransform(-0.4,8.8,1,1,0,0,0,3.8,3.6);

	this.instance_1 = new lib.Символ30();
	this.instance_1.setTransform(0,-3.1,1,1,0,0,0,6.2,9.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.2,-12.3,12.4,24.6);


(lib.Анимация3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ27();
	this.instance.setTransform(-0.4,8.8,1,1,0,0,0,3.8,3.6);

	this.instance_1 = new lib.Символ30();
	this.instance_1.setTransform(0,-3.1,1,1,0,0,0,6.2,9.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.2,-12.3,12.4,24.6);


(lib.Symbol26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol36();
	this.instance.setTransform(66.8,11.6,1,1,0,0,0,66.8,11.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,133.6,23.1);


(lib.sprite110 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shape109("synched",0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,58,58);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Tween22("synched",0);
	this.instance.setTransform(30,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,60,60);


(lib.Символ44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ43();
	this.instance.setTransform(357,65.5,0.278,0.278,0,0,0,19.8,24.2);

	this.instance_1 = new lib.Символ43();
	this.instance_1.setTransform(462,15.1,0.272,0.272,180,0,0,19.7,24.3);

	this.instance_2 = new lib.Символ43();
	this.instance_2.setTransform(188.3,49.2,0.503,0.503,180,0,0,19.7,24.3);

	this.instance_3 = new lib.Символ43();
	this.instance_3.setTransform(598.8,-77.2,0.503,0.503,0,0,0,19.7,24.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(178.4,-89.4,430.3,161.7);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ50();
	this.instance.setTransform(-430.7,44.9,0.799,0.799,0,0,0,79,12);

	this.instance_1 = new lib.Символ31();
	this.instance_1.setTransform(20.4,12.1,1,1,0,0,0,20.4,12.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1},{t:this.instance}]},1).to({state:[{t:this.instance_1}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ20();
	this.instance.setTransform(9.9,18.1,1,1,0,0,0,7.9,10.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:24.6},4).to({y:18.1},5).wait(37));

	// Слой 3
	this.instance_1 = new lib.Символ21();
	this.instance_1.setTransform(27.1,17.9,1,1,0,0,0,7.8,10.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({y:24.4},4).to({y:17.9},5).wait(33));

	// Слой 4
	this.instance_2 = new lib.Символ22();
	this.instance_2.setTransform(45,17.9,1,1,0,0,0,8.6,10.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(8).to({y:24.4},4).to({y:17.9},5).wait(29));

	// Слой 5
	this.instance_3 = new lib.Символ23();
	this.instance_3.setTransform(74.4,20.9,1,1,0,0,0,12.3,12.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(12).to({y:27.4},4).to({y:20.9},5).wait(25));

	// Слой 6
	this.instance_4 = new lib.Символ24();
	this.instance_4.setTransform(95.3,18.1,1,1,0,0,0,7,10);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(16).to({y:24.6},4).to({y:18.1},5).wait(21));

	// Слой 7
	this.instance_5 = new lib.Символ25();
	this.instance_5.setTransform(115.3,18.4,1,1,0,0,0,12.1,10.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(20).to({y:24.9},4).to({y:18.4},5).wait(17));

	// Слой 8
	this.instance_6 = new lib.Символ26();
	this.instance_6.setTransform(137.7,18.3,1,1,0,0,0,8.9,10.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(24).to({y:24.8},4).to({y:18.3},5).wait(13));

	// Слой 10
	this.instance_7 = new lib.Символ28();
	this.instance_7.setTransform(155.2,17.9,1,1,0,0,0,7.8,10.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(28).to({y:24.4},4).to({y:17.9},5).wait(9));

	// Слой 11
	this.instance_8 = new lib.Символ29();
	this.instance_8.setTransform(173.5,17.7,1,1,0,0,0,9.1,10.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(32).to({y:24.2},4).to({y:17.7},5).wait(5));

	// Слой 12
	this.instance_9 = new lib.Анимация3("synched",0);
	this.instance_9.setTransform(190.3,19.5);

	this.instance_10 = new lib.Анимация4("synched",0);
	this.instance_10.setTransform(190.3,26);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({startPosition:0},36).to({_off:true,y:26},4).to({_off:false,y:19.5},5).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(36).to({_off:false},4).to({_off:true,y:19.5},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2,7.2,194.5,26.7);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ16();
	this.instance.setTransform(16.4,38.9,1,1,0,0,0,16.4,38.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(7.8,-122.7,458.5,243.4);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ11();
	this.instance.setTransform(377.3,125.7,1,1,0,0,0,377.3,125.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-6.6,754.6,257.9);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ17();
	this.instance.setTransform(136.7,235.3,1,1,0,0,0,16.4,38.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ14();
	this.instance_1.setTransform(271.1,269.7,1,1,0,0,0,353.5,135.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ10();
	this.instance_2.setTransform(320,152.5,1,1,0,0,0,320,152.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-82.4,0,754.6,385.7);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ34();
	this.instance.setTransform(111.7,156.8,1,1,0,0,0,19.8,11.8);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.Символ34(), 3);

	this.instance_1 = new lib.Символ33();
	this.instance_1.setTransform(602.4,45.8,1,1,0,0,0,20.4,12.1);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2, false, new lib.Символ33(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ9();
	this.instance_2.setTransform(320,152.5,1,1,0,0,0,320,152.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-82.4,0,754.6,385.7);


(lib.sprite112 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol16();
	this.instance.setTransform(1.5,21.8,0.85,0.85,0,0,0,30,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({guide:{path:[1.5,21.7,1.5,21.3,1.5,20.9,1.5,15.3,5.6,11.2,9.7,7.1,15.3,7.1,21.1,7.1,25.2,11.2,29.3,15.3,29.3,20.9,29.3,26.7,25.2,30.8,21.1,34.9,15.3,34.9,9.7,34.9,5.6,30.8,3.3,28.5,2.3,25.7]}},29).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24,-3.7,51,51);


(lib.sprite113 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.sprite112();
	this.instance.setTransform(11.6,6.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30));

	// Layer 1
	this.instance_1 = new lib.sprite110();
	this.instance_1.setTransform(-8.7,-8.7,1.316,1.316);
	this.instance_1.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.5,-10.6,78.2,76.3);


(lib.Символ9_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance_3 = new lib.Symbol26();
	this.instance_3.setTransform(1.2,33.1,1,1,0,0,0,66.8,11.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Слой 1
	this.cir = new lib.sprite113();
	this.cir.setTransform(0.1,0.1,0.499,0.499,0,0,0,27.6,27.6);

	this.timeline.addTween(cjs.Tween.get(this.cir).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.6,-19,133.6,63.6);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 3
	this.instance = new lib.Символ9_1();
	this.instance.setTransform(458.6,173.6,0.499,0.499);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:547.6},4).to({x:458.6},5).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ18();
	this.instance_1.setTransform(99,18.4,1,1,0,0,0,99,18.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:-174},4).to({x:99},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2,7.2,490.5,188.6);


// stage content:



(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		stage.canvas.style.cursor = "none";
		this.pri.mouseEnabled = false;
		this.addEventListener("tick", fl_CustomMouseCursor1.bind(this));
		
		function fl_CustomMouseCursor1() {
			this.pri.x = stage.mouseX;
			this.pri.y = stage.mouseY;
		}
		var _this = this;
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		function fl_MouseOverHandler_5()
		    {
			    _this.txt.gotoAndPlay(1);
		    }
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		
		
		      function fl_MouseOutHandler_2()
		    {
			    _this.txt.gotoAndPlay(5);
		    }
		
			
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
		
		this.fon.x = - stage.mouseX / 40;
		this.fon.y = - stage.mouseY / 40;
			
		this.girl.x = - stage.mouseX / 40;
		this.girl.y = - stage.mouseY / 40;
		}
		
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 6
	this.pri = new lib.Символ51();
	this.pri.setTransform(-118.4,129.6,1,1,0,0,0,14.2,14.2);

	this.timeline.addTween(cjs.Tween.get(this.pri).wait(1));

	// Слой 4
	this.instance = new lib.Символ44();
	this.instance.setTransform(-25.6,131.9,1,1,0,0,0,19.7,24.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 3
	this.txt = new lib.Символ19();
	this.txt.setTransform(147.4,79.4,1.23,1.23,0,0,0,99,18.4);

	this.timeline.addTween(cjs.Tween.get(this.txt).wait(1));

	// Слой 2
	this.girl = new lib.Символ1_1();
	this.girl.setTransform(-0.6,-0.6,1,1,0,0,0,-262.1,-124.6);

	this.timeline.addTween(cjs.Tween.get(this.girl).wait(1));

	// Слой 1
	this.fon = new lib.Символ8();
	this.fon.setTransform(-0.7,-0.6,1.095,1.095,0,0,0,39,12.7);

	this.timeline.addTween(cjs.Tween.get(this.fon).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(186.4,138,826.3,422.3);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;