(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 580,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	manifest: [
		{src:"images/btn1.png", id:"btn1"},
		{src:"images/btn2.png", id:"btn2"},
		{src:"images/btn3.png", id:"btn3"},
		{src:"images/krug.png", id:"krug"},
		{src:"images/logo.png", id:"logo"},
		{src:"images/orel.png", id:"orel"}
	]
};



// symbols:



(lib.btn1 = function() {
	this.initialize(img.btn1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,114,47);


(lib.btn2 = function() {
	this.initialize(img.btn2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,115,47);


(lib.btn3 = function() {
	this.initialize(img.btn3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,115,47);


(lib.krug = function() {
	this.initialize(img.krug);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,45,35);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,148,40);


(lib.orel = function() {
	this.initialize(img.orel);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,43,36);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aq7FoIAArPIV3AAIAALPg");
	this.shape.setTransform(70,36);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ44 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.btn1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,114,47);


(lib.Символ43 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F68800").s().p("AgGBZIAAgVQgUgDgKgEQgQgHgIgFIgDgBIATgcQALAHAJAEQAKAEAJACIAAgZQgNgDgJgEQgKgEgGgDQgGgGgDgHQgEgHAAgKQAAgJAEgIQADgIAGgGQAHgGAJgDQAKgEAMAAIAAgMIATAAIAAAMQANACALAEQALAEAKAHIgRAcIgOgIQgHgDgIgCIAAAYQANADAJAEQAKAEAGAGQAGADADAHQAEAIAAAKQAAAJgEAIQgDAIgHAFQgGAGgKADQgJAEgLABIAAAUgAANAmQAHgBAEgCQADgDAAgFQAAgEgDgDQgDgDgIgCgAgPgqQgEADAAAEQAAAEADADQADADAJACIAAgXQgIABgDADg");
	this.shape.setTransform(6.4,9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,12.9,18);


(lib.Символ42 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F68800").s().p("AgNBKQgIgBgGgDIgMgHIgJgJQgFgFgDgHQgEgGgBgHIgEgOIgCgPIACgOQABgHADgHIAFgNIAIgMIAKgIQAFgFAGgDQAHgDAHgBQAHgCAGAAIAPACIANAEQAHADAFAEIAJAJQAFAFADAHIAGANQACAHACAHIAAAOIAAAPIgEAOIgGANIgIAMIgJAIQgGAFgGADQgGADgIABIgOACQgHAAgGgCgAgKgkQgFADgDAGQgDAEgCAIQgCAHAAAIQAAAIACAIQACAHADAFQADAGAFADQAGADAEAAQAGAAAFgDQAFgDAEgGQADgFACgHQACgHAAgJQAAgHgDgIQgBgHgEgFQgEgGgEgDQgGgDgFAAQgEAAgGADg");
	this.shape.setTransform(6.8,7.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,13.6,15.3);


(lib.Символ41 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F68800").s().p("AgNBKQgIgBgGgDIgMgHIgJgJQgFgFgDgHQgEgGgBgHIgEgOIgCgPIACgOQABgHADgHIAFgNIAIgMIAKgIQAFgFAGgDQAHgDAHgBQAHgCAGAAIAPACIANAEQAHADAFAEIAJAJQAFAFADAHIAGANQACAHACAHIAAAOIAAAPIgEAOIgGANIgIAMIgJAIQgGAFgGADQgGADgIABIgOACQgHAAgGgCgAgKgkQgFADgDAGQgDAEgCAIQgCAHAAAIQAAAIACAIQACAHADAFQADAGAFADQAGADAEAAQAGAAAFgDQAFgDAEgGQADgFACgHQACgHAAgJQAAgHgDgIQgBgHgEgFQgEgGgEgDQgGgDgFAAQgEAAgGADg");
	this.shape.setTransform(6.8,7.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,13.6,15.3);


(lib.Символ40 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F68800").s().p("AgQBIQgIgBgIgDQgIgEgGgFIgMgKIAZgaQAJAIAIAEQAIAEAIABQAJAAAFgFQAGgEgBgHQABgHgHgEQgGgEgJAAIgSAAIgGgTIAggeIg2AAIAAgiIBoAAIAAAdIgjAfQAJACAGACQAHAEAFAFQAFADADAHQADAIAAAIQAAALgEAKQgFAJgHAGQgHAHgLADQgKAEgNAAQgIAAgKgDg");
	this.shape.setTransform(6,7.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,11.9,15);


(lib.Символ39 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AL5C9QgHgBgGgDIgLgIIgJgIQgEgFgDgHIgGgNIgDgOIgBgPIABgQIADgOIAGgNIAHgMIAKgJIALgHQAGgDAGgBQAHgBAHAAQAHAAAHABQAGABAGADQAGADAFAEIAJAJIAIAMQADAGACAHQAFATAAALIgBAPIgEAOIgFANIgIALIgJAJIgLAIQgGADgHABQgGABgHAAQgIAAgGgBgAL3BCQgHAEgFAHQgEAHgDAKQgDAJAAAMQAAALADAJQADAJAFAHQAFAIAGAEQAIAEAIAAQAIAAAHgEQAHgEAFgHQAFgIADgJQACgJAAgLQAAgMgDgJQgCgJgFgHQgFgIgHgEQgHgEgIAAQgJAAgHAEgAJhC9QgHgBgGgDIgLgIIgJgIQgEgFgDgHIgGgNIgDgOIgBgPIABgQIADgOIAGgNIAHgMIAKgJIALgHQAGgDAGgBQAHgBAHAAQAHAAAHABQAGABAGADQAGADAFAEIAJAJIAIAMQADAGACAHQAFATAAALIgBAPIgEAOIgFANIgIALIgJAJIgLAIQgGADgHABQgGABgHAAQgIAAgGgBgAJfBCQgHAEgFAHQgEAHgDAKQgDAJAAAMQAAALADAJQADAJAFAHQAFAIAGAEQAIAEAIAAQAIAAAHgEQAHgEAFgHQAFgIADgJQACgJAAgLQAAgMgDgJQgCgJgFgHQgFgIgHgEQgHgEgIAAQgJAAgHAEgAkRC9QgHgBgHgDQgHgDgGgFIgLgJIAQgSQAJAIAJAEQAKAFAKAAQAGAAAGgCQAFgBAEgEQAEgEACgEQACgFAAgGQAAgFgCgFQgCgFgEgDQgFgDgFgCQgGgBgGAAIgPABIgMAFIgQgKIAEhIIBYAAIAAAXIhCAAIgCAiIALgCQAGgCAGAAQALAAAKADQAJADAHAFQAHAGADAJQAEAJAAAMQAAALgDAJQgEAJgHAHQgIAGgKAEQgKADgMAAQgIAAgIgBgAmaC9QgGgBgGgCQgKgEgKgJIAOgUQAIAHAIADQAIAEAJAAQAIAAAHgEQAGgDAFgGQAEgGADgIQACgJABgKQgGAHgIAEQgNAFgIgBQgLAAgKgDQgKgDgHgHQgGgFgEgKQgEgIAAgLQAAgKAEgJQAEgKAHgHQAIgHAKgEQAKgDAMAAQAJAAAOADQAKAEAIAIIAHAJIAGANQACAGABAJQACAJAAALQgCAWgDAKIgFAOIgHALQgEAGgFADQgFAFgGADQgGADgGABIgOABQgIAAgHgBgAmTA/QgFACgEAEQgEAEgCAFQgCAFAAAFQAAAGACAFQACAFAEADQAEAEAGACQAFABAHABQAHgBAGgBQAFgCAEgEQAEgEACgFQACgEAAgGQAAgGgCgFQgDgFgEgDQgEgEgFgCQgGgCgHgBQgHABgFACgAocC8QgIgBgIgDQgGgEgGgFIgLgKIASgRQAJAJAIAFIAKAEIAMABQAFAAAFgBQAFgCADgDQAEgDABgEQACgEAAgGQAAgFgCgEQgCgFgFgDIgKgEQgHgBgHAAIgMAAIgFgRIAogqIhAAAIAAgWIBiAAIAAATIgpArQAJABAHACQAIAEAGAFQAGAFAEAHQADAHAAAKQAAAKgEAJQgDAJgHAFQgHAGgKAEQgJADgLAAQgKAAgIgCgAqmC9QgGgBgGgDIgLgIIgJgIQgFgFgDgHIgFgNIgEgOIgBgPIABgQIAEgOIAFgNIAIgMIAJgJIALgHQAGgDAHgBQAGgBAHAAQAIAAAGABQAHABAGADQAFADAGAEIAJAJIAHAMQAEAGACAHQAEATAAALIgBAPIgDAOIgGANIgHALIgKAJIgLAIQgGADgGABQgHABgHAAQgHAAgHgBgAqnBCQgHAEgFAHQgFAHgDAKQgCAJAAAMQAAALADAJQACAJAFAHQAFAIAHAEQAHAEAIAAQAJAAAHgEQAHgEAFgHQAFgIACgJQADgJAAgLQAAgMgDgJQgDgJgFgHQgFgIgGgEQgIgEgIAAQgIAAgHAEgAuMC6IgLgFIgJgHIgHgJIgFgLIgEgNIgBhkIAaAAIAABTQAAALADAHQACAJAFAFQAFAFAHADQAHACAIABQAJgBAHgCQAHgCAEgGQAFgFADgIQACgHAAgLIAAhUIAaAAIAABTIgBAQIgDANQgCAGgEAGIgHAJIgJAHIgLAFQgQAFgKgBQgSgBgIgDgAHZC9IgthwIAbAAIAeBSIAehSIAbAAIguBwgAFMC9Ig9iUIAdAAIAsBxIAshxIAcAAIg9CUgAPdC8IAAgUIAygsQAKgIALgMQAEgFABgEQACgFAAgFQAAgGgCgEQgCgEgDgDQgDgDgFgCQgEgBgFAAQgFAAgEABQgFACgEADQgHAEgJAMIgSgOIAKgNQAGgHAGgDQAHgEAHgCQAIgCAKAAQAKAAAJADQAJADAHAGQAGAGAEAIQADAJAAAJQAAAJgCAHQgCAGgFAIQgFAGgHAGIgvApIBGAAIAAAWgANpC8IBCh9IhKAAIAAgWIBnAAIAAATIhCCAgACpC8IgPgkIhGAAIgPAkIgaAAIBAiUIAYAAIBBCUgACQCCIgZg7IgZA7IAyAAgAADC8IgNgkIhFAAIgQAkIgaAAIBBiUIAYAAIA+CUgAgTCCIgag7IgZA7IAzAAgAvoC8Igkg0IggAAIAAA0IgaAAIAAiTIBCAAQAMAAALADQAKADAHAHQAHAGAEAJQADAJAAAKQAAAJgCAHQgDAHgFAGQgEAFgHAEQgGAEgIACIAoA4gAwsByIAmAAQAHAAAFgCQAGgCAEgDQAEgDACgFQACgFAAgFQAAgGgCgFQgCgEgEgDQgEgEgGgBQgFgCgHAAIgmAAgAvUgGIAAgfIhyAAIAAiTIAaAAIAAB7IBFAAIAAh7IAZAAIAAB7IATAAIgEA3gAolgfIAAgQIgRgBQgHgBgHgDQgHgDgGgDQgGgDgEgEQgFgFgEgFIgGgLIgEgMIgBgOIABgNIAEgMIAGgLQAEgGAFgDQAEgFAGgDQAGgEAHgCQAHgCAHgBQAIgBAJAAIAAgPIAZAAIAAAPQAJAAAIABQAHABAHACQAHACAGAEQAFADAFAFQAFADAEAGIAGALQACAFABAHQACAGAAAIQAAAGgCAHQgBAGgCAHIgGAKQgEAFgFAFQgEAEgGADQgGADgHADQgHADgHABIgRABIAAAQgAoMhGQALAAAJgDQAJgDAGgFQAGgFADgIQADgIAAgJQAAgKgDgHQgDgIgGgGQgGgEgJgEQgJgDgLAAgAo5iWQgJAEgGAEQgGAGgDAIQgDAHAAAKQAAAJADAIQADAIAGAFQAGAFAJADQAJADALAAIAAhTQgLAAgJADgArigkQgIgCgHgCIgNgHIgMgKIgJgLQgEgGgCgHIgEgOQgCgIAAgHIACgQIAEgOIAHgNIAJgLQAFgFAGgEIANgIQAHgCAIgCQAIgCAIAAQAJAAAHACQAIACAHACIANAIQAGAEAFAFQAGAFAEAGIAGANIAEAOQACAHAAAJIgCAOIgEAPIgHAMQgEAHgFAFIgLAKIgNAHQgHACgIACQgIACgIgBQgJABgHgCgArmifQgJAFgHAHQgHAGgDAKQgEAKAAALQAAAKAEAJQAEAKAGAIQAHAGAJAEQAKAFAKAAQALAAAJgFQAJgDAHgHQAHgIADgJQAEgKAAgKQAAgLgEgJQgEgKgGgHQgHgHgJgFQgJgEgLAAQgLAAgJAEgAmlglIAAiTIA6AAQAMAAALADQAKAEAHAGQAIAHAEAJQADAJAAALIgBAMQgBAFgCAGQgFAIgIAHQgIAGgKADQgLAEgMAAIgeAAIAAAvgAmMhsIAfAAQAHAAAGgBQAFgCAFgEQAEgDACgGQACgFAAgFQAAgHgCgEQgCgFgEgEIgKgFQgGgBgHgBIgfAAgAukglIAAiTIA6AAQAMAAALADQAKAEAHAGQAIAHAEAJQADAJAAALIgBAMQgBAFgCAGQgFAIgIAHQgIAGgKADQgLAEgMAAIgeAAIAAAvgAuLhsIAfAAQAHAAAGgBQAFgCAFgEQAEgDACgGQACgFAAgFQAAgHgCgEQgCgFgEgEIgKgFQgGgBgHgBIgfAAg");
	this.shape.setTransform(109.5,19.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,219.1,38.2);


(lib.Символ38 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AG2C3IgLgFIgJgHIgHgJIgFgLIgEgNIgBhkIAaAAIAABUQABAKACAIQACAIAFAFQAFAFAHADQAHADAIAAQAJAAAHgDQAHgCAEgGQAFgFADgHQACgIAAgKIAAhVIAaAAIAABUIgBAPIgDANQgCAHgEAFIgHAJIgJAHIgLAFQgQAFgKAAQgSgCgIgDgAjvC6QgIgBgHgDIgNgHIgLgKIgJgLQgEgGgDgHIgEgOQgBgHgBgIIACgPIAEgPIAHgNIAJgLQAFgFAGgEIANgHQAIgDAHgCQAIgBAJAAQAIAAAIABQAIACAGADIAOAHQAGAEAFAFQAFAFAEAGIAHANIADAOQACAIAAAIIgCAPIgDAOIgHANQgEAGgFAFIgLAKIgOAHQgHADgHABQgIACgJAAQgIAAgIgCgAjzBAQgJAEgGAHQgIAHgDAJQgDAKgBALQABAKADAKQAEAJAHAIQAGAHAKAEQAJAEALAAQAKAAAJgEQAKgEAGgHQAHgHAEgKQADgKAAgKQAAgLgDgJQgEgKgHgHQgHgHgJgEQgJgFgLAAQgLAAgJAFgAreC6QgIgBgHgDIgMgHIgMgKIgJgLQgEgGgCgHIgFgOQgBgHAAgIIABgPIAFgPIAHgNIAJgLQAEgFAHgEIANgHQAHgDAHgCQAJgBAIAAQAJAAAHABQAIACAHADIANAHQAGAEAFAFQAGAFADAGIAHANIAEAOQABAIAAAIIgBAPIgEAOIgHANQgEAGgFAFIgLAKIgOAHQgGADgIABQgIACgIAAQgJAAgIgCgArhBAQgJAEgHAHQgHAHgDAJQgEAKAAALQAAAKAEAKQAEAJAGAIQAHAHAJAEQAKAEAKAAQAKAAAKgEQAJgEAHgHQAGgHAEgKQAEgKgBgKQABgLgEgJQgEgKgGgHQgIgHgJgEQgJgFgKAAQgLAAgJAFgAQBC6QgIgCgHgDQgIgCgIgFQgHgEgGgGIAPgTQAHAGAPAJIALADIAOABIALgBIAIgEQADgCABgEQACgDAAgEQAAgFgBgDQgCgDgDgCIgKgFIgQgFIgWgGQgJgEgGgFQgGgFgDgHQgEgHAAgKQAAgKAEgIQAEgHAHgGQAGgGAKgDQAIgDAMAAIAPABIANAEQAKADAPALIgOATQgKgHgKgEQgKgEgKAAIgKABQgEACgDACQgHAFAAAIQAAAEABADQACAEAEACIAKAFIASAFQAMADAIAEQAKADAGAFQAFAFADAHQADAHAAAJQAAALgDAIQgEAIgHAGQgIAFgJADQgJADgMAAIgRgBgAmIC6QgJgCgHgDQgIgCgHgFQgIgEgGgGIAQgTQAGAGAPAJIAMADIANABIALgBIAIgEQAEgCABgEQACgDAAgEQAAgFgBgDQgCgDgEgCIgJgFIgRgFIgVgGQgJgEgHgFQgGgFgDgHQgDgHAAgKQAAgKADgIQAEgHAHgGQAHgGAJgDQAJgDALAAIAQABIANAEQAJADAPALIgNATQgKgHgLgEQgJgEgLAAIgKABQgEACgDACQgHAFAAAIQAAAEACADQACAEADACIALAFIARAFQAMADAJAEQAJADAGAFQAGAFADAHQADAHAAAJQAAALgEAIQgEAIgHAGQgHAFgKADQgJADgLAAIgRgBgAOlC5IglgzIgfAAIAAAzIgaAAIAAiTIBBAAQANAAALAEQAKADAHAGQAHAGAEAJQADAJAAAKQAAAJgDAHQgCAIgFAFQgFAGgGAEQgGADgIADIAoA3gANhBvIAmAAQAGAAAGgCQAFgBAEgEQAFgDABgEQADgFAAgGQAAgGgDgEQgBgFgFgDQgDgDgGgCQgGgBgGAAIgmAAgAK6C5IAAiTIBtAAIAAAXIhTAAIAAAnIBKAAIAAAXIhKAAIAAAnIBVAAIAAAXgAJWC5IAAh7IguAAIAAgYIB3AAIAAAYIgvAAIAAB7gAEHC5IAAiTIBtAAIAAAXIhTAAIAAAnIBKAAIAAAXIhKAAIAAAnIBUAAIAAAXgADOC5IgkgzIghAAIAAAzIgZAAIAAiTIBBAAQANAAAKAEQAKADAIAGQAGAGAEAJQAEAJAAAKQAAAJgDAHQgCAIgFAFQgEAGgHAEQgGADgIADIAnA3gACJBvIAmAAQAIAAAFgCQAGgBAEgEQADgDACgEQADgFAAgGQAAgGgDgEQgCgFgDgDQgEgDgGgCQgFgBgIAAIgmAAgAgIC5IhRhoIAABoIgZAAIAAiTIAXAAIBPBmIAAhmIAXAAIAACTgAnrC5IAAhpIguBFIAAAAIguhFIAABpIgaAAIAAiTIAcAAIAsBGIAthGIAcAAIAACTgAtTC5IAAg+IhHAAIAAA+IgZAAIAAiTIAZAAIAAA9IBHAAIAAg9IAaAAIAACTgAwXC5IAAh7IgvAAIAAgYIB3AAIAAAYIguAAIAAB7gAovgGIAAiRIAaAAIAAATQAGgKAJgFQAFgDAFgBQAGgCAGAAQAKAAAKAEQAJAEAHAHQAHAIAFAKQAEAQAAAJIgBANIgDALQgFALgHAIQgHAHgJAEQgKAEgKAAQgGAAgGgCQgGgBgEgDQgJgFgGgJIAAAzgAoCiAQgGACgEAFQgFAFgCAGQgDAHAAAIQAAAIADAHQACAGAFAFQAEAEAGADQAGACAHAAQAGAAAGgCQAFgCAFgFQAEgFADgGQACgHAAgIQAAgIgDgHQgCgGgEgFQgFgFgFgCQgGgDgGAAQgHAAgGADgAl5gmIgMgEQgKgEgJgIQgHgIgEgKIgEgLIgBgMQAAgIAFgOQADgLAJgIQAIgIAKgEIAMgEIAMgBQAIAAAQAFQAKAEAJAIQAHAIAEAKQAFAPAAAIIgBAMIgEAKQgEALgHAIQgJAIgKAEQgQAFgIAAgAl7iAQgGADgFAFQgEAFgDAGQgCAHAAAHQABAHACAHQACAGAFAFQAEAFAGADQAHADAHAAQAIAAAGgDQAGgDAFgFQAEgFACgGQADgHAAgHQAAgHgDgHQgDgGgEgFQgEgFgHgDQgGgDgHAAQgIAAgGADgAt+gmIgLgEQgLgEgHgIQgJgIgDgKIgEgLIgBgMQAAgIAFgOQAEgLAIgIQAIgIAKgEIAMgEIAMgBQAJAAAOAFQAMAEAHAIQAIAIAFAKQAEAPAAAIIgBAMIgDAKQgFALgIAIQgIAIgLAEQgPAFgIAAgAt/iAQgGADgEAFQgFAFgDAGQgBAHAAAHQgBAHADAHQADAGAEAFQAFAFAFADQAHADAHAAQAIAAAGgDQAGgDAEgFQAFgFACgGQACgHAAgHQAAgHgCgHQgDgGgEgFQgFgFgGgDQgGgDgHAAQgIAAgGADgAAqgoIAAhKIgyBKIgYAAIAAhvIAYAAIAABLIAyhLIAYAAIAABvgAhQgoIghgtIgTATIAAAaIgZAAIAAhvIAZAAIAAA2IAwg2IAfAAIgsAvIAvBAgAkZgoIAAhvIA6AAQAHAAAHACQAHACAFAEQAFADACAGQADAFAAAGQAAAFgBAEIgFAHQgEAGgIAEIAKADIAHAGIAEAIQACAEAAAGQAAAHgDAGQgDAFgFAEQgFAEgIACQgHACgKAAgAkAg8IAdAAQAJAAAGgEQAEgEAAgGQAAgGgFgEQgFgEgKAAIgcAAgAkAhpIAbAAQAIAAAEgEQAEgDAAgGQAAgGgEgEQgEgDgIAAIgbAAgApngoIAAhKIg1BKIgXAAIAAhvIAYAAIAABLIA0hLIAZAAIAABvgAsFgoIAAhZIgjAAIAAgWIBgAAIAAAWIgjAAIAABZgAvYgoIgyhCIgYAYIAAAqIgZAAIAAiTIAZAAIAABKIBHhKIAfAAIg9A/IBABUg");
	this.shape.setTransform(109.5,18.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,219,37.7);


(lib.Символ37 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.krug();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,45,35);


(lib.Символ35 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.orel();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,43,36);


(lib.Символ33 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhFDBIAAgmQgNAHgJAAQgLAAgIgEQgIgEgHgIQgGgIgDgLQgDgLAAgOQAAgNADgLQADgLAHgHQAGgIAIgEQAJgEAKAAQAJAAANAIIAAgnIAnAAIAAAnIAKgFQAGgDAGAAQAIAAAJAEQAIAEAHAIQAGAHADALQAEALAAAOQAAANgEAMQgDAKgGAIQgHAIgIAEQgIAEgIAAQgHAAgGgDIgKgEIAAAmgAgeBPIAAAwQAFADAFAAQAFAAAEgCQADgCADgEIADgIIABgLIgBgLIgDgIQgDgEgDgCQgEgCgFAAQgFAAgFADgAhYBOQgDACgDAEIgDAIQgBAFAAAGQAAAGABAFIADAIQADAEADACQAEACAFAAQAFAAAFgDIAAgwQgFgDgFAAQgFAAgEACgAoHDBIAAiTIAoAAIAAAPQAHgIAHgEQAEgDAFgBQAFgBAGAAQALAAAJAEQAJAEAHAHQAHAIAEALQAEAQAAAJQgCARgCAIQgEALgHAHQgHAIgJAEQgJAEgLAAQgGAAgFgBQgFgBgFgDQgHgEgGgHIAAAvgAnSBPQgEACgDADIgFAIQgCAFAAAGQAAAGACAFIAFAIQADADAEACQAEACAFAAIAJgCQAEgCAEgDQADgEACgFQABgFAAgFQAAgGgBgFIgFgIQgEgDgEgCIgJgCQgFAAgEACgApmCeIgLgFIgJgHIgHgJIgFgKIgDgLIgCgNQAAgIAFgPQAEgLAHgIQAIgIALgFIALgDIAMgBIANABIAMAEIAKAFIAIAIQAHAJAEALQADALAAANIAAAIIhMAAQACAJAHAFQAGAFAJAAQAHAAAGgDQAGgDAHgGIAWASIgJAKQgGAEgGADQgGADgHACQgHACgJAAQgRgCgHgDgAo9BeQgCgKgFgFQgFgGgIAAQgIAAgFAGQgFAFgCAKIAoAAIAAAAgArTChIgLgDQgNgIgGgFQgIgIgEgLIgDgLIgCgMQAAgIAFgPQAEgKAIgJIAJgHIALgFIALgEIANgBQAJAAAHACQAHABAHAEIAKAIQAFAEAEAGIgbAUQgEgGgFgDQgFgDgGAAQgGAAgEACQgFACgDAEQgDADgBAFQgCAFAAAFIACAKQABAFAEAEQACADAFACQAEACAFAAQAGAAAGgDQAEgDAFgGIAbATQgEAHgEAEIgLAIQgHAEgHACQgIACgJAAQgHAAgGgCgAFMCgQgHgCgFgFQgFgEgDgHQgDgHAAgIQAAgJADgHQADgGAGgFQAGgEAIgDQAIgCAKAAQALAAARAEIAAgBQAAgJgGgFIgHgEIgKgBQgJAAgHACIgPAEIgJgcIAVgGQAMgDANAAQALAAAPAEQALADAHAHQAGAGADAKQADAIAAAMIAABCIgoAAIAAgMQgGAHgIADQgIAEgLAAQgIAAgHgCgAFgByQgFAEAAAHQAAAGAEADQAEADAGAAQAJAAAGgFQAFgFAAgIIAAgGQgHgDgJAAQgIAAgFAEgALZCgIAAgpIAqAAIAAApgAKdCgIAAhyIAoAAIAABygAImCgIAAhyIAoAAIAAAkIATAAQAKAAAJACQAIADAHAFQAGAEADAIQAEAHAAAJQAAAKgDAHQgDAHgGAFQgGAFgJADQgIADgKAAgAJOCEIAMAAQAIAAADgEQAFgDAAgGQAAgFgFgDQgEgEgHAAIgMAAgAHRCgIAAhSIgiAAIAAggIBrAAIAAAgIgiAAIAABSgAEFCgIgWglIgLAOIAAAXIgoAAIAAhyIAoAAIAAAqIAfgqIAtAAIgnAvIAoBDgACACgIAAg5IgmA5IglAAIAAhyIAnAAIAAA5IAmg5IAlAAIAABygAjBCgIAAg5IgmA5IglAAIAAhyIAnAAIAAA5IAmg5IAlAAIAABygAlhCgIAAhSIghAAIAAggIBqAAIAAAgIghAAIAABSgALZBXIAAgpIAqAAIAAApgApMgtQgHgCgFgFQgFgEgDgHQgDgHAAgIQAAgJADgHQADgGAGgFQAGgEAIgDQAIgCAKAAQALAAARAEIAAgBQAAgJgGgFIgHgEIgKgBQgJAAgHACIgPAEIgJgcIAVgGQAMgDANAAQALAAAPAEQALADAHAHQAGAGADAKQADAIAAAMIAABCIgoAAIAAgMQgGAHgIADQgIAEgLAAQgIAAgHgCgAo4hbQgFAEAAAHQAAAGAEADQAEADAGAAQAJAAAGgFQAFgFAAgIIAAgGQgHgDgJAAQgIAAgFAEgAjRgtIAAg5IgmA5IglAAIAAhyIAnAAIAAA5IAmg5IAlAAIAABygAnggtIAAhyIAoAAIAABSIAcAAIAAhSIAoAAIAABSIAcAAIAAhSIAoAAIAABygAqegtIAAg4Ig0AAIAAA4IgpAAIAAiTIApAAIAAA3IA0AAIAAg3IApAAIAACTg");
	this.shape.setTransform(77.1,19.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,154.3,38.8);


(lib.Символ31 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F68800").s().p("AAQBKIgPgEIgMgHIgLgJQgGgFgEgGIgHgOQgDgGgBgIQgCgHAAgIQAAgHACgHQABgIADgGIAHgOIAKgLQAFgFAHgEQAGgEAFgDQAHgDAIgBQAIgCAJAAQAIAAAIACIAPAEIAOAHIALAJIAKALIAHAOIAEAOQACAHAAAHQAAAIgCAHIgEAOQgDAHgFAGQgEAHgFAFIgMAJIgNAHIgPAEQgIACgJAAQgIAAgIgCgAARgjQgHADgFAGQgFAFAAAHQgDAHAAAHQAAAIADAHQABAHAEAFQAGAGAGADQAIADAIAAQAIAAAHgDQAHgDAFgGQAFgFACgHQADgHAAgIQAAgHgDgHQgCgHgGgFQgFgGgGgDQgIgDgIAAQgIAAgHADgAEmBJIAAgkIAqAAIAAAkgADkBJIAAhRIg5BRIgmAAIAAiRIAoAAIAABRIA5hRIAmAAIAACRgAi+BJIAAiRIBMAAQANAAAKADQAKADAHAHQAEAFADAFQACAHAAAHQAAAGgBAGIgFAJIgHAHIgJAFIAMADQAFADAEAFQAEAEACAGQACAGAAAIQAAAJgEAIQgEAHgHAFQgHAGgKACQgLADgNAAgAiWApIAfAAQAKgBAFgEQAFgDAAgHQAAgGgFgDQgFgEgKAAIgfAAgAiWgOIAaAAQAJAAAFgDQAFgDAAgGQAAgGgFgEQgFgDgJAAIgaAAgAkkBJIAAhtIgsAAIAAgkICBAAIAAAkIgtAAIAABtgAEwAZIgMhPIAAgSIAtAAIAAASIgMBPg");
	this.shape.setTransform(33.8,7.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,67.6,15.3);


(lib.Символ29 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F68800").s().p("AARA4IAAg4IgjA4IglAAIAAhvIAnAAIAAA3IAjg3IAlAAIAABvg");
	this.shape.setTransform(5.7,5.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,11.4,11.4);


(lib.Символ28 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAqDBIAAiTIAoAAIAAAPQAHgIAHgEQAEgDAFgBQAGgBAGAAQAKAAAJAEQAJAEAHAHQAHAIAEALQAEAQAAAJQgBARgDAIQgEALgHAHQgHAIgJAEQgJAEgKAAQgGAAgGgBQgFgBgEgDQgIgEgGgHIAAAvgABgBPQgFACgDADIgFAIQgCAFAAAGQAAAGACAFIAFAIQADADAFACQADACAGAAIAJgCQAEgCADgDQADgEACgFQACgFgBgFQABgGgCgFIgFgIQgDgDgEgCIgJgCQgGAAgDACgAquDBIAAiTIAoAAIAAAPQAHgIAHgEQAEgDAFgBQAFgBAHAAQAKAAAJAEQAJAEAHAHQAHAIAEALQAEAQAAAJQgBARgDAIQgEALgHAHQgHAIgJAEQgJAEgKAAQgHAAgFgBQgFgBgFgDQgGgEgHgHIAAAvgAp5BPQgEACgDADIgFAIQgCAFAAAGQAAAGACAFIAFAIQADADAEACQAFACAEAAIAJgCQAFgCADgDQADgEACgFQABgFABgFQgBgGgBgFIgFgIQgDgDgFgCIgJgCQgEAAgFACgAGMC3IAAgXIhXAAIAAhyIAoAAIAABSIAfAAIAAhSIAoAAIAABSIANAAIgDA3gAiOChIgLgDQgOgIgFgFQgJgIgEgLIgDgLIgBgMQgBgIAFgPQAEgKAJgJIAJgHIAKgFIAMgEIAMgBQAJAAAHACQAIABAGAEIALAIQAEAEAEAGIgaAUQgFgGgFgDQgFgDgGAAQgFAAgFACQgEACgDAEQgEADgBAFQgBAFgBAFIACAKQACAFADAEQACADAFACQAEACAFAAQAGAAAGgDQAFgDAFgGIAbATQgEAHgFAEIgLAIQgGAEgIACQgIACgJAAQgHAAgFgCgAoACeIgLgFIgJgHIgHgJIgGgKIgCgLIgCgNQAAgIAEgPQAFgLAHgIQAIgIALgFIALgDIALgBIAOABIAMAEIAKAFIAIAIQAHAJADALQAEALAAANIgBAIIhMAAQADAJAGAFQAHAFAJAAQAHAAAGgDQAGgDAHgGIAVASIgIAKQgGAEgGADQgGADgIACQgGACgJAAQgRgCgHgDgAnYBeQgBgKgFgFQgFgGgJAAQgHAAgFAGQgFAFgCAKIAnAAIAAAAgADJCgQgHgCgFgFQgFgEgDgHQgDgHAAgIQAAgJADgHQAEgGAFgFQAGgEAJgDQAHgCALAAQAKAAARAEIAAgBQAAgJgGgFIgHgEIgKgBQgJAAgHACIgPAEIgIgcIAUgGQAMgDAOAAQAKAAAQAEQAKADAHAHQAHAGADAKQACAIAAAMIAABCIgnAAIAAgMQgHAHgIADQgIAEgLAAQgIAAgHgCgADeByQgGAEAAAHQAAAGAEADQAFADAGAAQAIAAAGgFQAFgFABgIIAAgGQgIgDgIAAQgJAAgEAEgAKHCgIAAghIgJAAIgWAhIguAAIAbgoIgJgFIgGgIQgEgEgBgFQgBgGAAgGQAAgJACgHQADgGAFgFQAHgHAJgDQAJgDAMAAIBAAAIAABygAJsBPQgEADAAAGQAAAFAEADQAEADAHAAIAQAAIAAgXIgQAAQgHAAgEADgAIGCgIAAg5IgmA5IglAAIAAhyIAoAAIAAA5IAlg5IAlAAIAABygAgpCgIAAhSIgiAAIAAggIBpAAIAAAgIgfAAIAABSgAj1CgIAAg5IgmA5IglAAIAAhyIAoAAIAAA5IAlg5IAlAAIAABygAmiCgIAAhyIBXAAIAAAgIguAAIAABSgAiCgMIAAiTIAoAAIAAAPQAHgIAHgEQAEgDAFgBQAFgBAHAAQAKAAAJAEQAJAEAHAHQAHAIAEALQAEAQAAAJQgCARgCAIQgEALgHAHQgHAIgJAEQgJAEgKAAQgHAAgFgBQgFgBgFgDQgGgEgHgHIAAAvgAhNh+QgEACgDADIgFAIQgCAFAAAGQAAAGACAFIAFAIQADADAEACQAFACAEAAIAJgCQAFgCADgDQADgEACgFQABgFABgFQgBgGgBgFIgFgIQgDgDgFgCIgJgCQgEAAgFACgAk8gsIgMgDQgNgIgGgFQgHgIgFgLIgDgLIgCgMQAAgIAFgPQAFgKAHgJIAJgHIALgFIAMgEIAMgBQAJAAAIACQAGABAHAEIALAIQAFAEADAGIgaAUQgFgGgFgDQgFgDgGAAQgGAAgEACQgEACgEAEQgDADgBAFQgBAFAAAFIABAKQABAFAEAEQACADAFACQAEACAFAAQAHAAAFgDQAEgDAGgGIAbATQgFAHgEAEIgLAIQgHAEgHACQgIACgJAAQgGAAgGgCgAAbgtQgHgCgFgFQgFgEgDgHQgDgHAAgIQAAgJADgHQADgGAHgFQAFgEAIgDQAJgCAJAAQALAAARAEIAAgBQAAgJgFgFIgIgEIgKgBQgIAAgIACIgPAEIgJgcIAVgGQAMgDAOAAQAKAAAPAEQALADAHAHQAGAGADAKQADAIAAAMIAABCIgoAAIAAgMQgGAHgHADQgJAEgKAAQgJAAgHgCgAAvhbQgEAEAAAHQAAAGADADQAEADAGAAQAJAAAGgFQAGgFgBgIIAAgGQgHgDgIAAQgJAAgFAEgADMgtIAAghIgJAAIgWAhIguAAIAbgoIgJgFIgHgIQgDgEAAgFQgCgGAAgGQAAgJACgHQADgGAGgFQAFgHAKgDQAJgDAMAAIBAAAIAABygACxh+QgEADAAAGQAAAFAEADQAEADAHAAIAQAAIAAgXIgQAAQgHAAgEADgAjXgtIAAhSIgiAAIAAggIBrAAIAAAgIgiAAIAABSgAmkgtIAAhyIAoAAIAABygAobgtIAAhyIAoAAIAAAkIATAAQAKAAAJACQAJADAGAFQAGAEADAIQAFAHAAAJQAAAKgEAHQgDAHgGAFQgGAFgIADQgJADgKAAgAnzhJIANAAQAHAAAEgEQAEgDAAgGQAAgFgEgDQgEgEgHAAIgNAAgAqrgtIAAiTIB2AAIAAAiIhOAAIAAARIAcAAQANAAALADQALADAIAGQAIAGAEAJQAEANABAIQgBALgDAJQgFAJgHAGQgIAGgKADQgKAEgNAAgAqDhPIAbAAQAKAAAFgEQAFgEAAgIQAAgHgFgEQgFgEgJAAIgcAAg");
	this.shape.setTransform(68.8,19.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,137.5,38.8);


(lib.Символ24 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A43808").s().p("AN4BKIgQgEIgNgHIgMgJQgFgFgEgGIgHgOQgDgGgBgIQgCgHAAgIQAAgHACgHQABgIADgGIAHgOIAJgLQAGgFAHgEQAFgEAIgDQAHgDAIgBQAIgCAJAAQAIAAAIACIAPAEIAOAHIALAJIAKALIAHAOIAEAOQABAHAAAHQAAAIgBAHIgEAOQgEAHgEAGQgEAHgFAFIgMAJIgOAHIgPAEQgHACgJAAQgJAAgHgCgAN5gjQgHADgFAGQgFAFgCAHQgEAHAAAHQAAAIAEAHQADAHAEAFQAFAGAHADQAIADAIAAQAIAAAGgDQAHgDAGgGQAFgFACgHQADgHAAgIQAAgHgDgHQgDgHgFgFQgFgGgHgDQgHgDgIAAQgIAAgHADgAJOBKIgPgEIgOgHIgLgJQgGgFgEgGIgHgOQgDgGgBgIQgBgHAAgIQAAgHABgHQABgIADgGIAHgOIAKgLQAGgFAGgEQAGgEAHgDQAIgDAIgBQAHgCAJAAQAJAAAHACIAQAEIANAHIAMAJIAJALIAHAOIAEAOQACAHAAAHQAAAIgCAHIgEAOQgDAHgEAGQgFAHgFAFIgMAJIgNAHIgPAEQgIACgJAAQgIAAgIgCgAJQgjQgHADgGAGQgFAFgCAHQgDAHAAAHQAAAIADAHQADAHAEAFQAGAGAHADQAHADAIAAQAIAAAHgDQAHgDAFgGQAFgFACgHQADgHAAgIQAAgHgDgHQgCgHgGgFQgFgGgGgDQgIgDgIAAQgIAAgGADgAquBIIADgfIAJABQAFAAADgDQAEgDAEgJQACgKACgRIACg0IAAgUIBxAAIAACRIgpAAIAAhtIgiAAIAAAFQgBAmgDAPIgDATIgGAOIgIAJQgDAFgFACIgJADIgKABQgLAAgNgDgAPtBJIAAgkIApAAIAAAkgALDBJIAAiRIBqAAIAAAkIhCAAIAABtgAHSBJIAAg4Ig0AAIAAA4IgpAAIAAiRIApAAIAAA3IA0AAIAAg3IApAAIAACRgAEyBJIAAhSIglA3IAAAAIgmg3IAABSIgoAAIAAiRIArAAIAjA5IAjg5IAsAAIAACRgABCBJIAAhSIglA3IgBAAIgjg3IAABSIgoAAIAAiRIArAAIAhA5IAjg5IAsAAIAACRgAhxBJIAAhRIg5BRIgmAAIAAiRIAoAAIAABRIA5hRIAnAAIAACRgAk3BJIAAhtIgsAAIAAgkICCAAIAAAkIgtAAIAABtgAmUBJIgKgaIg6AAIgKAaIgrAAIA/iSIAnAAIA/CSgAmrAPIgQgoIgQAoIAgAAgArhBJIAAhtIgzAAIAABtIgoAAIAAiRICDAAIAACRgAu4BJIAAhRIg5BRIgmAAIAAiRIAoAAIAABRIA5hRIAnAAIAACRgAP3AZIgMhPIAAgSIAtAAIAAASIgMBPg");
	this.shape.setTransform(104.9,7.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,209.7,15.3);


(lib.Символ23 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKlBMQALgCAFgFQAFgEAAgIIAAgBIgQAAIAAgpIAqAAIAAAhQAAAMgDAIQgDAIgGAFQgFAFgJACQgHADgKAAgAiFA3IADgfIAJABQAFAAADgDQAFgDADgIQADgLACgQIABg0IAAgVIBvAAIAACRIgmAAIAAhtIgjAAIAAAGQgBAogCAMIgEATIgGAOIgHAKQgEAEgEACIgKADIgKABQgLAAgNgDgAJsA4IAAhSIgmA3IAAAAIgmg3IAABSIgoAAIAAiRIArAAIAjA5IAjg5IAsAAIAACRgAG2A4IAAhQIg5BQIgmAAIAAiRIApAAIAABTIA4hTIAnAAIAACRgADxA4IAAhtIgsAAIAAgkICBAAIAAAkIgtAAIAABtgACTA4IgKgaIg5AAIgLAaIgrAAIA/iSIAnAAIA/CSgAB9AAIgRgqIgQAqIAhAAgAi4A4IAAhtIgyAAIAABtIgpAAIAAiRICEAAIAACRgAmPA4IAAiRIAoAAIAACRgAodA4IAAiRIApAAIAAAuIAWAAQAOAAALAEQALADAIAGQAIAGAFAKQACAEABAGIABAJQAAAMgEAKQgEAJgIAHQgHAGgLAEQgLADgOAAgAn0AWIAVAAQAKAAAGgFQAGgEAAgJQAAgFgGgFQgGgFgKAAIgVAAgApfA4IAAhSIgmA3IAAAAIgmg3IAABSIgoAAIAAiRIArAAIAjA5IAjg5IAsAAIAACRg");
	this.shape.setTransform(72.4,9.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,144.9,18.3);


(lib.Символ21 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFD01").s().p("AgLCaIAAgkQgjgGgRgGQgggOgNgKIAggwQASAMAQAIQARAHAQADIAAgsQgWgFgQgGQgRgHgKgHQgLgJgGgNQgFgMAAgRQAAgQAFgNQAGgOALgKQALgKAQgGQAQgGAVgBIAAgVIAjAAIAAAWQAWACATAIQASAHARALIgeAwQgKgHgNgGQgMgFgNgDIAAApQAWAGAQAGQAQAHALAJQALAHAFANQAFANAAARQAAAQgGANQgGANgLAKQgLAKgQAGQgPAFgUACIAAAkgAAXBCQAMgCAGgEQAGgFAAgIQAAgIgFgEQgFgFgOgEgAgbhJQgGAEAAAIQAAAHAFAFQAFAEAOAEIAAgnQgMABgGAGg");
	this.shape.setTransform(11,15.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,22,30.9);


(lib.Символ20 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFD01").s().p("AgYCAQgMgCgMgGQgKgEgJgIQgKgHgHgJQgHgJgHgKQgGgLgDgMQgEgMgCgMIgCgaQAAgLACgNQACgNAEgMQAEgMAGgLQAGgKAHgJQAIgJAKgHQAJgHAKgFQALgFAMgDQANgCALgBIANABIAMACQANADAKAFQALAFAJAHQAJAHAIAJQAHAJAGAKQAGALAEAMQAEAMACANIACAYQAAANgCAMQgCANgEAMQgEAMgGAKQgGALgHAJQgIAJgKAHQgJAHgKAFQgLAFgMADIgMACIgNAAQgMABgMgDgAgSg/QgJAFgFAJQgHAJgDANQgDANAAAOQAAAPADAMQADANAHAJQAGAJAIAGQAJAEAJAAQAGAAAHgCIAGgCQAJgGAFgJQAHgJACgMQAEgNAAgPQAAgOgEgMQgDgNgGgJQgGgJgJgGIgFgCQgHgDgGABQgJAAgJAEg");
	this.shape.setTransform(11.7,13.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,23.3,26.2);


(lib.Символ19 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFD01").s().p("AgYCAQgMgCgMgGQgKgEgJgIQgKgHgHgJQgHgJgHgKQgGgLgDgMQgEgMgCgMIgCgaQAAgLACgNQACgNAEgMQAEgMAGgLQAGgKAHgJQAIgJAKgHQAJgHAKgFQALgFAMgDQANgCALgBQANABAMACQANADAKAFQALAFAJAHQAJAHAIAJQAHAJAGAKQAGALAEAMQAEAMACANIACAYQAAANgCAMQgCANgEAMQgEAMgGAKQgGALgHAJQgIAJgKAHQgJAHgKAFQgLAFgMADQgMADgNgBQgMABgMgDgAgSg/QgJAFgFAJQgHAJgDANQgDANAAAOQAAAPADAMQADANAHAJQAGAJAIAGQAJAEAJAAQAKAAAJgEQAJgGAFgJQAHgJACgMQAEgNAAgPQAAgOgEgMQgDgNgGgJQgGgJgJgGQgJgEgJAAQgJAAgJAEg");
	this.shape.setTransform(11.7,13.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,23.3,26.2);


(lib.Символ18 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFD01").s().p("AgbB9QgQgDgNgGQgNgGgMgJQgKgHgKgLIAsgsQAOAPAOAHQAPAIAPgBQAPAAAJgGQAJgIAAgMQAAgMgLgHQgLgHgRAAIgeAAIgKgiIA4g0IhfAAIAAg5IC1AAIAAAyIg9A0QAPADALAFQAMAGAJAIQAJAHAFAMQAFAMAAAQQAAATgIAQQgHAPgNALQgNALgSAGQgSAGgVAAQgPAAgQgDg");
	this.shape.setTransform(10.2,12.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,20.5,25.7);


(lib.Символ16 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AooB6IAAhiIAbAAIAAAKQAEgGAFgDIAGgCIAHgBQAIAAAFADQAGACAGAFQAEAGACAHQAEAKAAAGQgBAMgDAFQgCAHgEAFQgGAFgGADQgGADgGAAIgIgBIgGgCQgFgDgEgFIAAAggAoFAtIgEAEIgDAFIgCAHQAAAEACADIADAGIAEADIAGACQAEAAADgCQACgBACgCIAEgGIABgHIgBgHIgEgFIgEgEIgHgBIgGABgABEBkIgIgCQgJgFgEgEQgFgFgDgHIgCgIIgBgIQAAgFADgKQADgHAFgFIAGgFIAHgEIAIgCIAJgBIALABIAJAEIAHAFIAFAHIgSANQgDgEgDgCQgDgCgEAAQgEAAgDACQgDABgCACIgDAGIgBAGIABAHIADAGQACACADABIAGACQAEAAAEgDQADgBADgEIASANIgFAHQgEADgEACQgEADgFABQgFABgHAAIgHgBgAj8BkIgIgCIgIgEIgGgFQgDgDgGgJIgCgIIgBgIQAAgFADgKQADgFAGgHIAGgFIAIgEIAIgCIAJgBQAFAAAMADQAFACAHAGQAHAIACAFQADAKAAAFIgBAIIgCAIQgFAJgEADQgIAHgFACIgIACIgIABIgJgBgAj7AuIgFADIgDAGIgBAGIABAHIAEAFIAFAEQADACAEAAQADAAADgCIAFgEIADgFIACgHIgCgGIgDgGIgGgDIgFgCQgFAAgDACgAlXBkIgIgCIgHgEIgGgFIgEgGIgEgJQgCgFgBgPQABgJABgIQABgJAEgGIAEgHIAGgGIAIgEQAEgCAFAAIAngFIAEATIgpAHQgEABgEACIgFAEQgDAEgBAEQACgDAGgDIAIgEIAKgBQAIAAAHADQAGACAFAFQAFAEADAGQADAJAAAGIgBAHIgCAIQgDAGgGAGQgIAGgEACQgLADgGAAgAlUAwIgEAEIgDAFIgCAGQABADABADIADAFQACACACABIAHACIAFgCQADgBACgCIADgFIABgGIgBgGIgDgFIgFgEIgGgBIgGABgAECBjQgFgBgDgDQgEgDgCgFQgCgEABgGQgBgGACgEQADgEAEgEIAJgEQAFgCAHAAQAHAAALADIAAgBQAAgGgDgDQgCgCgDAAIgHgBIgLABIgKADIgFgTIANgEQAIgCAJAAQAHAAAKADQAIACAEAFQAFAEABAGQACAGAAAIIAAArIgaAAIAAgIQgEAFgFACQgGADgHAAQgFAAgFgCgAEPBFQgDADAAAEQAAAEACACQADACAFAAQAFAAAEgDQAEgEgBgFIAAgEQgEgCgGAAQgGAAgDADgAm+BjQgFgBgDgDQgEgDgBgFQgCgEAAgGQAAgGACgEQACgEAEgEIAKgEQAFgCAHAAQAHAAALADIAAgBQAAgGgEgDQgCgCgCAAIgIgBIgLABIgJADIgGgTIAOgEQAIgCAJAAQAHAAAKADQAHACAFAFQAEAEACAGQACAGAAAIIAAArIgaAAIAAgIQgEAFgFACQgHADgHAAQgFAAgFgCgAmwBFQgDADgBAEQAAAEADACQACACAFAAQAFAAAFgDQADgEAAgFIAAgEQgFgCgFAAQgGAAgDADgAIMBjIAAgYIAbAAIAAAYgAHjBjIAAgmIgaAmIgZAAIAAhLIAbAAIAAAlIAZglIAYAAIAABLgAGIBjIAAglIgSAaIgSgaIAAAlIgaAAIAAhLIAbAAIARAaIASgaIAbAAIAABLgADOBjIAAgbIgWAAIAAAbIgbAAIAAhLIAbAAIAAAaIAWAAIAAgaIAaAAIAABLgAgmBjIAAhLIAbAAIAABLgAh1BjIAAhLIAbAAIAAAXIAMAAQAHAAAGACQAFACAFADQAEADACAFQADAFAAAGQAAAGgDAFQgCAFgEADQgEAEgFABQgGACgHAAgAhaBRIAIAAQAFAAACgDQACgCABgEQgBgDgCgCQgCgDgFAAIgIAAgAivBjIAAg2IgWAAIAAgVIBIAAIAAAVIgXAAIAAA2gAISBDIgIg2IAAgMIAfAAIAAAMIgIA2gAEegqIgHgDQgKgFgDgDQgFgGgDgHIgDgHIgBgIQAAgFAEgKQADgHAFgGIAGgFIAHgDIAIgDIAIAAIALABIAJADIAHAFIAFAHIgSANQgCgEgDgBQgDgCgFAAQgEAAgDABQgCABgCADIgEAFIgBAHIABAHIAEAFQACADACABIAHABQAEAAAEgCQADgCADgEIASANIgGAHQgEAEgEACQgEACgFABQgEACgHAAIgIgBgAhjgsIgIgDIgHgFIAKgQQAFADAHACQAHACAFAAQAFAAADgBQACgCAAgDQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQgDgCgFAAIgKAAIAAgRIAKAAQAFAAACgCQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQgDgBgDAAQgGAAgFACQgHACgDADIgLgOIAHgFIAIgEIAJgDIAKgBQAIAAAHACQAFABAFADQADADADAEQACAEAAAEQgBAGgDAFQgDAEgGACQAHACAEAEIADAFIAAAHQAAAFgBAEQgCAFgFADQgFADgGACQgIACgJAAQgOgBgFgCgAjPgqIgIgDIgIgDIgGgFQgDgEgGgJIgCgHIgBgIQAAgFADgKQADgFAGgIIAGgFIAIgDIAIgDIAJgBQAFAAAMADQAFACAHAHQAHAIACAFQADAJAAAGIgBAIIgCAHQgFAJgEAEQgIAGgFACIgIADIgIABIgJgBgAjOhhIgFAEIgDAFIgBAHIABAHIAEAFIAFAEQADABAEAAQADAAADgBIAFgEIADgFIACgHIgCgHIgDgFIgGgEIgFgBQgFAAgDABgAlugsIgHgEIgGgEIgFgGIgDgHIgCgIIgCgIQABgGADgKQACgHAGgFQAEgGAHgDIAIgCIAIgBIAJABIAIADIAGAEIAGAFQAFAFACAIQACAHAAAJIAAAFIgzAAQACAGAEAEQAFADAFAAQAFAAAEgCQAEgCAEgEIAPAMIgGAHIgIAEIgJADQgEACgGAAQgLgBgFgCgAlThXQgBgHgDgDQgDgEgGAAQgFAAgDAEQgEADgBAHIAaAAIAAAAgAm3gqIgHgDQgJgFgDgDQgGgGgDgHIgCgHIgBgIQAAgFADgKQADgHAGgGIAGgFIAGgDIAIgDIAIAAIALABIAJADIAHAFIAGAHIgSANQgCgEgEgBQgDgCgFAAQgDAAgDABQgDABgCADIgDAFIgBAHIABAHIADAFQACADADABIAGABQAEAAAEgCQADgCAEgEIASANIgHAHQgDAEgEACQgEACgFABQgFACgHAAIgIgBgAC6grQgFgCgDgDQgEgDgCgEQgBgFgBgFQABgGABgFQADgEAEgDIAJgFQAFgBAHAAQAHAAALADIAAgBQAAgGgDgDQgCgCgDgBIgHgBIgLABIgKAEIgFgTIANgFQAIgBAJAAQAHAAAKACQAIADAEAEQAFAEACAGQABAGAAAIIAAAsIgaAAIAAgIQgEAEgFADQgGACgHAAQgFAAgFgBgADHhKQgDADAAAFQAAADACADQADACAFAAQAFAAAEgEQAEgDgBgGIAAgDQgEgCgGAAQgGAAgDACgAgTgrQgGgCgDgDQgDgDgCgEQgCgFAAgFQAAgGACgFQACgEAEgDIAKgFQAFgBAGAAQAGAAALADIAAgBQAAgGgEgDQgCgCgDgBIgEgBIgMABIgKAEIgEgTIANgFQAIgBAHAAQAHAAAKACQAHADAFAEQAEAEACAGQACAGAAAIIAAAsIgbAAIAAgIQgDAEgGADQgEACgGAAQgGAAgEgBgAgHhKQgCADAAAFQgBADADADQADACAEAAQAEAAAEgEQADgDAAgGIAAgDQgFgCgGAAQgDAAgEACgACGgrIAAgZIgJADIgKABQgGAAgFgCQgFgCgDgDQgEgDgCgFQgCgFAAgGIAAgdIAbAAIAAAVQAAAGABADQACADAFAAIAFgBIAGgCIAAgeIAaAAIAABMgAkvgrIAAhMIA6AAIAAAVIgfAAIAAA3gAoogrIAAhMIAtAAQAHAAAGACQAEABAEAEIADAFIABAHQAAAGgDAFQgCAEgGACIAGADIAEAEIAEAFIABAHQAAAFgDAEIgFAGIgJAEQgFACgIAAgAoOg8IALAAQAEAAADgCQADgCAAgEQAAgDgDgCQgDgCgEAAIgLAAgAoOhZIAJAAQAEAAADgCQACgCAAgDQAAgCgCgCQgCgCgFAAIgJAAg");
	this.shape.setTransform(55.4,12.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,110.7,24.5);


(lib.Символ14 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AClA8IgMgEQgGgCgFgDIgJgHIgIgJQgDgGgCgFIgEgMIgBgMIABgLIAEgMQACgFADgFIAIgKIAKgHIAKgFQAGgDAHgBIANgCQAHABAGABQAHABAFADIALAFIAKAHIAHAKIAGAKIAEAMIABALIgBAMIgEAMQgCAFgEAFIgHAJIgKAIIgLAFQgGADgGABIgNACQgHgBgHgBgACmgcQgFADgEAEQgEAFgCAFQgCAGAAAFQAAAGACAGQACAGAEAEQAEAEAGADQAFACAHAAQAHAAAFgCQAGgDAEgEQAEgEACgGQACgGAAgGQAAgFgCgGQgCgFgEgFQgEgEgGgDQgGgDgGAAQgHAAgGADgAnPA8QgIgCgGgDIgMgGIgKgHIARgXQAGAHAIADIAJAEIAKABQAJAAAFgEQAEgDAAgGQAAgFgEgCQgFgCgKgBIgMAAIAAgWIAMAAQAJAAAEgEQAEgCAAgFQAAgFgEgDQgEgDgHAAQgIABgIADQgJADgGAFIgQgTIAKgIQAFgEAGgCQAGgEAHgBQAIgBAIgBQAKABAIACQAIACAGAFQAGAEADAGQADAGAAAHIgBAJQgBAEgDADQgCAEgDACIgHAFIAIABIAHAHIAEAIQABAEAAAGQAAAHgDAHQgDAHgGAFQgGAFgJACQgJADgLAAQgKAAgIgBgALcA7IAAh1IBgAAIAAAcIhAAAIAAASIA6AAIAAAYIg6AAIAAATIBAAAIAAAcgAKJA7IAAhYIgkAAIAAgdIBpAAIAAAdIgkAAIAABYgAH7A7IAAh1IBgAAIAAAcIhAAAIAAASIA6AAIAAAYIg6AAIAAATIBAAAIAAAcgAHMA7IgJgVIguAAIgIAVIgjAAIAzh2IAgAAIAyB2gAG6AMIgNggIgOAgIAbAAgAEhA7IAAhYIgkAAIAAgdIBpAAIAAAdIgkAAIAABYgAAAA7IAAh1IBgAAIAAAcIg/AAIAAAOIAXAAQAKAAAJACQAJADAGAFQAGAEAEAFQADAKAAAHQAAAJgDAHQgDAHgGAGQgGAFgJACQgIADgLAAgAAhAfIAWAAQAHAAAEgDQAFgDAAgHQAAgFgFgDQgEgEgHABIgWAAgAgtA7IgJgVIguAAIgIAVIgjAAIAzh2IAgAAIAyB2gAg/AMIgNggIgOAgIAbAAgAj3A7IAAh1IAzAAQALAAAJADQAJADAHAFQAGAFAEAJQADALAAAGIgBAKIgDAGQgBAEgDAEIgGAGQgHAFgJADQgKADgLAAIgQAAIAAAigAjWAAIAPAAIAIAAIAGgDQADgCABgDQABgDAAgEQAAgDgBgEQgBgCgDgCIgGgEIgIgBIgPAAgAkmA7IgJgVIguAAIgIAVIgjAAIAzh2IAgAAIAyB2gAk4AMIgNggIgOAgIAbAAgApPA7IAAh1IAhAAIAAB1gArCA7IAAh1IAhAAIAAAlIASAAQALAAAJADQAJACAHAGQAHAFADAFIADAJIABAJQAAAKgEAHQgDAHgGAGQgHAFgIADQgJADgLAAgAqhAfIARAAQAJAAAEgDQAFgEAAgHQAAgHgFgDQgEgEgIAAIgSAAgAs7A7IAAh1IA9AAQALAAAIADQAIADAFAEQAEAFACAEQACAFAAAHIgBAJIgEAHIgGAFIgHAFIAJACQAFADADADQADADACAGQABAEAAAGQAAAIgDAGQgDAGgGAFQgFAEgJACQgIACgLAAgAsbAhIAZAAQAIgBAEgDQAEgDAAgFQAAgFgEgDQgEgDgIAAIgZAAgAsbgKIAVAAQAHAAAEgDQAEgDAAgGQAAgEgDgDQgEgCgIgBIgVAAg");
	this.shape.setTransform(82.9,6.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,165.8,12.4);


(lib.Символ11 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0F9EE8","#09629E"],[0,1],-200,0,200,0).s().p("A/PHCIAAuDMA+eAAAIAAODg");
	this.shape.setTransform(200,45);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,400,90);


(lib.Символ10 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FEFB00","#FCE701"],[0,1],-200,0,200,0).s().p("A/PHCIAAuDMA+eAAAIAAODg");
	this.shape.setTransform(200,45);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,400,90);


(lib.Символ9 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FFC429","#FF530D"],[0,1],-200,0,200,0).s().p("A/PHCIAAuDMA+eAAAIAAODg");
	this.shape.setTransform(200,45);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,400,90);


(lib.Символ8 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0F9EE8","#09629E"],[0,1],-200,0,200,0).s().p("A/PHCIAAuDMA+eAAAIAAODg");
	this.shape.setTransform(200,45);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,400,90);


(lib.Символ7 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A79BC").s().p("AlHBqIAAgjIhdAAIgDAjIgrAAIAAhNIAPAAIAIgYIAGgZIADgiIABgwICFAAIAACDIAUAAIgGBNgAmCg5QgCAjgCAOQgDARgHAUIA0AAIAAhYIgmAAgAMNBJIgPgEQgSgIgIgGQgLgKgIgMQgFgJgGgTIgUAAIAABCIgwAAIAAitIAwAAIAABCIAVAAQADgPAIgNQAIgMALgKQAIgGASgIIAPgEIAQgBQAJAAAKACQAIABAJAEQAIADAHAFIANALQAGAGAEAIIAIAPIAFARQACAJAAAKQAAAJgCAHQgCAJgDAIQgDAIgFAIIgKANIgNALQgIAFgIAEQgIADgJACQgJACgKAAgAMNg6QgHADgFAHQgFAGgDAJQgDAJAAAKQAAAJADAHQADAJAFAGQAFAHAIAEQAHADAJAAQAIAAAIgDQAHgEAFgGQAGgHACgJQADgGAAgKQAAgKgDgJQgDgIgFgHQgFgGgHgEQgIgEgJAAQgIAAgIAEgAjABJQgKgCgIgDQgJgEgHgFQgIgEgGgHQgGgGgFgHQgFgHgEgJQgDgIgCgJQgCgHAAgJQAAgKACgJQACgIADgJQAEgIAFgHIALgOIAOgLQAIgFAIgDQAJgEAJgBQAKgCAKAAQAKAAAJACQAKABAIAEQAJADAHAFIAOALQAGAGAFAIQAFAHAEAIQADAIACAJQACAJAAAKQAAAJgCAHQgCAJgDAIQgEAIgFAIIgLANIgOALQgIAFgIAEQgJADgJACQgKACgKAAQgKAAgJgCgAi/g6QgIAEgGAHQgGAGgDAJQgDAIAAAKQAAAJADAHQAEAIAFAHQAHAHAIADQAIAEAKAAQAKAAAIgEQAIgDAGgHQAGgGADgJQADgHAAgJQAAgKgDgIQgDgJgGgGQgGgHgIgEQgJgEgKAAQgJAAgJAEgAQ1BHIAAgqIAyAAIAAAqgAO6BHIAAiCIg0AAIAAgrICaAAIAAArIg1AAIAACCgAIyBHIAAg1IgVAAIgjA1Ig4AAIApg9QgIgDgGgFQgHgDgFgHQgEgHgDgIQgCgJAAgKQAAgIABgGQABgHADgGQAGgLAKgHQAKgHANgEQANgEAPAAIBTAAIAACtgAH/g3QgDADgCAEQgCAEAAAGQAAAJAHAGQADADAFABQAFACAGAAIAgAAIAAgsIgfAAQgNAAgHAGgAEiBHIAAitIBLAAQAQAAAOAEQANAFAKAIQAJAIAFALQAFAQAAAKQAAAIgBAHQgBAHgDAGQgDAFgEAFIgJAHQgKAIgOAEQgNAEgRAAIgYAAIAAAygAFSgPIAXAAQAHAAAFgBQAFgCAEgDQADgDACgEQACgFAAgFQAAgGgCgEQgCgEgDgDIgJgFQgFgBgHAAIgXAAgAB7BHIAAitICNAAIAAApIhdAAIAAAbIBUAAIAAAkIhUAAIAAAcIBeAAIAAApgAg1BHIAAitIBXAAQARAAAMAEQALAEAIAIQAGAFADAHQADAIAAAJQAAAHgDAGQgBAGgEAFIgJAJIgLAGIAPAGQAGAEAFAFQAEADADAHQACAHAAAJQAAALgEAJQgFAJgIAGQgJAHgMADQgNADgPAAgAgGAgIAjAAQAMAAAGgEQAGgEAAgIQAAgIgGgEQgGgEgMAAIgjAAgAgGggIAdAAQALAAAFgEQAGgEAAgIQAAgHgFgEQgGgEgLAAIgdAAgApaBHIAAhiIgsBCIgBAAIgthCIAABiIgvAAIAAitIAzAAIAqBEIAqhEIAzAAIAACtgAsoBHIgNgfIhDAAIgNAfIgzAAIBLiuIAvAAIBKCugAtDACIgTgwIgUAwIAnAAgAv5BHIAAhCIg+AAIAABCIgxAAIAAitIAxAAIAABCIA+AAIAAhCIAxAAIAACtgARBAOIgOhfIAAgVIA2AAIAAAVIgPBfg");
	this.shape.setTransform(112.9,10.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,225.9,21.4);


(lib.Символ4 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.logo();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,148,40);


(lib.Символ2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#F3F3F3","#D6D6D6"],[0,1],0,0,0,0,0,293.5).s().p("EgtTAHCIAAuDMBamAAAIAAODg");
	this.shape.setTransform(290,45);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,580,90);


(lib.Анимация8 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.btn3();
	this.instance.setTransform(-57.5,-23.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57.5,-23.5,115,47);


(lib.Анимация7 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.btn3();
	this.instance.setTransform(-57.5,-23.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57.5,-23.5,115,47);


(lib.Анимация6 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.btn3();
	this.instance.setTransform(-57.5,-23.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57.5,-23.5,115,47);


(lib.Анимация4 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.btn2();
	this.instance.setTransform(-57.5,-23.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57.5,-23.5,115,47);


(lib.Анимация2 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.btn2();
	this.instance.setTransform(-57.5,-23.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57.5,-23.5,115,47);


(lib.Анимация1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.btn2();
	this.instance.setTransform(-57.5,-23.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57.5,-23.5,115,47);


(lib.Символ36 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ38();
	this.instance.setTransform(98.8,17.8,0.5,0.5,0,0,0,109.5,18.8);

	// Слой 1
	this.instance_1 = new lib.Символ37();
	this.instance_1.setTransform(22.5,17.5,1,1,0,0,0,22.5,17.5);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,153.5,35);


(lib.Символ34 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ39();
	this.instance.setTransform(94.8,17.5,0.5,0.5,0,0,0,109.5,19.1);

	// Слой 1
	this.instance_1 = new lib.Символ35();
	this.instance_1.setTransform(18.5,18,1,1,0,0,0,21.5,18);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3,0,152.6,36);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_19 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(19).call(this.frame_19).wait(1));

	// 3
	this.instance = new lib.Символ36();
	this.instance.setTransform(38.5,-135,0.85,0.85,0,0,0,22.4,17.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).to({x:-55,alpha:1},9,cjs.Ease.get(1)).to({x:-46.5},5,cjs.Ease.get(1)).wait(2));

	// 2
	this.instance_1 = new lib.Символ34();
	this.instance_1.setTransform(23.2,-164.4,0.85,0.85,0,0,0,21.4,18);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(2).to({_off:false},0).to({x:-53.3,alpha:1},9,cjs.Ease.get(1)).to({x:-44.8},5,cjs.Ease.get(1)).wait(4));

	// 1
	this.instance_2 = new lib.Символ33();
	this.instance_2.setTransform(-126.8,-235.5,0.61,0.61,0,0,0,77.2,19.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-135.5},9,cjs.Ease.get(1)).to({y:-145.5},5,cjs.Ease.get(1)).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-173.9,-247.4,94.1,23.7);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 43
	this.instance = new lib.Символ43();
	this.instance.setTransform(50.1,9,1,1,0,0,0,6.4,9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(7).to({y:6.2},4,cjs.Ease.get(1)).to({y:9},5,cjs.Ease.get(1)).wait(1));

	// Символ 42
	this.instance_1 = new lib.Символ42();
	this.instance_1.setTransform(35.6,8.6,1,1,0,0,0,6.8,7.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({y:5.8},4,cjs.Ease.get(1)).to({y:8.6},5,cjs.Ease.get(1)).wait(3));

	// Символ 41
	this.instance_2 = new lib.Символ41();
	this.instance_2.setTransform(20.3,8.6,1,1,0,0,0,6.8,7.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(3).to({y:5.8},4,cjs.Ease.get(1)).to({y:8.6},5,cjs.Ease.get(1)).wait(5));

	// Символ 40
	this.instance_3 = new lib.Символ40();
	this.instance_3.setTransform(6,8.7,1,1,0,0,0,6,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1).to({y:5.9},4,cjs.Ease.get(1)).to({y:8.7},5,cjs.Ease.get(1)).wait(7));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,56.6,18);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_19 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(19).call(this.frame_19).wait(1));

	// 4
	this.instance = new lib.Символ31();
	this.instance.setTransform(150.4,104.7,1,1,0,0,0,33.8,7.7);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({_off:false},0).to({y:32.7},9,cjs.Ease.get(1)).to({y:34.7},5,cjs.Ease.get(1)).wait(1));

	// 3
	this.instance_1 = new lib.Символ30();
	this.instance_1.setTransform(156.6,-49.2,1.42,1.42,0,0,0,28.2,9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({y:16.8},9,cjs.Ease.get(1)).to({y:10.8},5,cjs.Ease.get(1)).wait(2));

	// 2
	this.instance_2 = new lib.Символ29();
	this.instance_2.setTransform(37.8,6.7,1,1,0,0,0,5.7,5.7);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(2).to({_off:false},0).to({x:117.8,alpha:1},9,cjs.Ease.get(1)).to({x:107.8},5,cjs.Ease.get(1)).wait(4));

	// 1
	this.instance_3 = new lib.Символ28();
	this.instance_3.setTransform(58.9,107.4,0.74,0.74,0,0,0,68.8,19.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:23.4},9,cjs.Ease.get(1)).to({y:27.4},5,cjs.Ease.get(1)).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(8,93.1,101.8,28.7);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 1
	this.instance = new lib.btn3();

	this.instance_1 = new lib.Анимация7("synched",0);
	this.instance_1.setTransform(57.5,23.5);
	this.instance_1._off = true;

	this.instance_2 = new lib.Анимация8("synched",0);
	this.instance_2.setTransform(57.5,23.5,1.06,1.06);
	this.instance_2._off = true;

	this.instance_3 = new lib.Анимация6("synched",0);
	this.instance_3.setTransform(57.5,23.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},3).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},4).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).to({_off:true,scaleX:1.06,scaleY:1.06},3,cjs.Ease.get(1)).wait(6));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},3,cjs.Ease.get(1)).wait(1).to({startPosition:0},0).to({_off:true,scaleX:1,scaleY:1},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,115,47);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 1
	this.instance = new lib.btn2();

	this.instance_1 = new lib.Анимация1("synched",0);
	this.instance_1.setTransform(57.5,23.5);
	this.instance_1._off = true;

	this.instance_2 = new lib.Анимация2("synched",0);
	this.instance_2.setTransform(57.5,23.5,1.06,1.06);
	this.instance_2._off = true;

	this.instance_3 = new lib.Анимация4("synched",0);
	this.instance_3.setTransform(57.5,23.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},3).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},4).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).to({_off:true,scaleX:1.06,scaleY:1.06},3,cjs.Ease.get(1)).wait(6));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},3,cjs.Ease.get(1)).wait(1).to({startPosition:0},0).to({_off:true,scaleX:1,scaleY:1},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,115,47);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_38 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(38).call(this.frame_38).wait(1));

	// 2
	this.instance = new lib.Символ24();
	this.instance.setTransform(175.2,39.7,1,1,0,0,0,104.9,7.7);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(23).to({_off:false},0).to({x:105.2,alpha:1},9,cjs.Ease.get(1)).to({x:115.2},6,cjs.Ease.get(1)).wait(1));

	// 1
	this.instance_1 = new lib.Символ23();
	this.instance_1.setTransform(102.7,-52.3,1,1,0,0,0,72.4,9.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.49,scaleY:1.49,x:119.7,y:40.8},9,cjs.Ease.get(1)).to({scaleX:1.46,scaleY:1.46,y:30.8},5,cjs.Ease.get(1)).wait(9).to({scaleX:1,scaleY:1,x:82.8,y:15.8},8,cjs.Ease.get(1)).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(30.3,-61.4,144.9,18.3);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 21
	this.instance = new lib.Символ21();
	this.instance.setTransform(86.1,15.4,1,1,0,0,0,11,15.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({y:11.9},4,cjs.Ease.get(1)).to({y:15.4},5,cjs.Ease.get(1)).wait(1));

	// Символ 20
	this.instance_1 = new lib.Символ20();
	this.instance_1.setTransform(61.2,14.7,1,1,0,0,0,11.7,13.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(8).to({y:11.2},4,cjs.Ease.get(1)).to({y:14.7},5,cjs.Ease.get(1)).wait(5));

	// Символ 19
	this.instance_2 = new lib.Символ19();
	this.instance_2.setTransform(34.9,14.7,1,1,0,0,0,11.7,13.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(4).to({y:11.2},4,cjs.Ease.get(1)).to({y:14.7},5,cjs.Ease.get(1)).wait(9));

	// Символ 18
	this.instance_3 = new lib.Символ18();
	this.instance_3.setTransform(10.2,14.9,1,1,0,0,0,10.2,12.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:11.4},4,cjs.Ease.get(1)).to({y:14.9},5,cjs.Ease.get(1)).wait(13));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,97.1,30.9);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_24 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(24).call(this.frame_24).wait(1));

	// 3
	this.instance = new lib.Символ16();
	this.instance.setTransform(161.1,135.3,1,1,0,0,0,55.4,12.2);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).to({y:28.3},10,cjs.Ease.get(1)).to({y:35.3},5,cjs.Ease.get(1)).wait(1));

	// 2
	this.instance_1 = new lib.Символ15();
	this.instance_1.setTransform(49.6,94,1,1,0,0,0,48.5,15.4);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({y:30},10,cjs.Ease.get(1)).to({y:34},5,cjs.Ease.get(1)).wait(6));

	// 1
	this.instance_2 = new lib.Символ14();
	this.instance_2.setTransform(86,-43.5,1,1,0,0,0,82.9,6.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:16.5},9,cjs.Ease.get(1)).to({y:6.5},5,cjs.Ease.get(1)).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3.1,-49.7,165.8,12.4);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 1
	this.instance = new lib.Символ44();
	this.instance.setTransform(57,23.5,1,1,0,0,0,57,23.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.06,scaleY:1.06},3,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,114,47);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text5
	this.instance = new lib.Символ32();
	this.instance.setTransform(413.7,186.7,1,1,0,0,0,77.1,19.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(279).to({_off:false},0).to({x:423.7},10,cjs.Ease.get(1)).wait(60).to({y:166.7},5,cjs.Ease.get(1)).to({x:413.7,y:366.7,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// text4
	this.instance_1 = new lib.Символ27();
	this.instance_1.setTransform(252.9,19.1,1,1,0,0,0,68.8,19.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(209).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(50).to({y:9.1},5,cjs.Ease.get(1)).to({y:129.1},5,cjs.Ease.get(1)).wait(81));

	// text3
	this.instance_2 = new lib.Символ22();
	this.instance_2.setTransform(267,10,1,1,0,0,0,87,18);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(139).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(50).to({y:0},5,cjs.Ease.get(1)).to({y:180,alpha:0},5,cjs.Ease.get(1)).wait(151));

	// text2
	this.instance_3 = new lib.Символ12();
	this.instance_3.setTransform(336.5,21.6,1,1,0,0,0,155.5,22.6);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(69).to({_off:false},0).wait(60).to({y:11.6,alpha:0.25},5,cjs.Ease.get(1)).to({y:151.6,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(220));

	// text1
	this.instance_4 = new lib.Символ7();
	this.instance_4.setTransform(243.5,23.2,3.51,3.51,0,0,0,112.9,10.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(4).to({_off:false},0).to({scaleX:0.91,scaleY:0.91,x:283.5,y:23.1,alpha:1},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(35).to({regX:113,scaleX:0.72,scaleY:0.72,rotation:-4},5,cjs.Ease.get(1)).to({regY:10.6,scaleX:2.67,scaleY:2.67,rotation:37,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(290));

	// logo
	this.instance_5 = new lib.Символ4();
	this.instance_5.setTransform(-117,20,1,1,0,0,0,74,20);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({x:83},9,cjs.Ease.get(1)).to({x:73},10,cjs.Ease.get(1)).wait(330).to({x:63},5,cjs.Ease.get(1)).to({x:103,alpha:0},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-191,0,148,40);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 5
	this.instance = new lib.Символ11();
	this.instance.setTransform(380,45,1,1,0,0,0,200,45);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(279).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(60).to({alpha:0},10,cjs.Ease.get(1)).wait(1));

	// 4
	this.instance_1 = new lib.Символ10();
	this.instance_1.setTransform(380,45,1,1,0,0,0,200,45);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(209).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(60).to({alpha:0},10,cjs.Ease.get(1)).wait(71));

	// 3
	this.instance_2 = new lib.Символ9();
	this.instance_2.setTransform(380,45,1,1,0,0,0,200,45);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(139).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(60).to({alpha:0},10,cjs.Ease.get(1)).wait(141));

	// 2
	this.instance_3 = new lib.Символ8();
	this.instance_3.setTransform(380,45,1,1,0,0,0,200,45);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(69).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(60).to({alpha:0},10,cjs.Ease.get(1)).wait(211));

	// 1
	this.instance_4 = new lib.Символ2();
	this.instance_4.setTransform(290,45,1,1,0,0,0,290,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(360));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,580,90);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// btn_3
	this.btn3 = new lib.Символ26();
	this.btn3.setTransform(636,20.5,1,1,0,0,0,57.5,23.5);
	this.btn3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.btn3).wait(279).to({_off:false},0).to({x:476},5,cjs.Ease.get(1)).to({x:486},5,cjs.Ease.get(1)).wait(60).to({x:476},5,cjs.Ease.get(1)).to({x:656},5,cjs.Ease.get(1)).wait(1));

	// btn_2
	this.btn2 = new lib.Символ25();
	this.btn2.setTransform(646,20.5,1,1,0,0,0,57.5,23.5);
	this.btn2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.btn2).wait(209).to({_off:false},0).to({x:476},5,cjs.Ease.get(1)).to({x:486},5,cjs.Ease.get(1)).wait(50).to({x:476},5,cjs.Ease.get(1)).to({x:646},5,cjs.Ease.get(1)).wait(81));

	// btn_1
	this.btn1 = new lib.Символ5();
	this.btn1.setTransform(645,20.5,1,1,0,0,0,57,23.5);
	this.btn1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.btn1).wait(9).to({_off:false},0).to({x:475},10,cjs.Ease.get(1)).to({x:485},10,cjs.Ease.get(1)).wait(170).to({x:475},5,cjs.Ease.get(1)).to({x:635},5,cjs.Ease.get(1)).to({_off:true},1).wait(150));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


// stage content:



(lib.binarium_slider_580x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//btn1
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.knopka.addEventListener("mouseover", fl_MouseOverHandler);
		
		function fl_MouseOverHandler()
		{
		 _this.btn.btn1.gotoAndPlay(1);
		}
		
		
		
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.knopka.addEventListener("mouseout", fl_MouseOutHandler);
		
		function fl_MouseOutHandler()
		{
		 _this.btn.btn1.gotoAndPlay(5);
		}
		
		
		//btn2
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.knopka.addEventListener("mouseover", fl_MouseOverHandler_2);
		
		function fl_MouseOverHandler_2()
		{
		 _this.btn.btn2.gotoAndPlay(1);
		}
		
		
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.knopka.addEventListener("mouseout", fl_MouseOutHandler_2);
		
		function fl_MouseOutHandler_2()
		{
		 _this.btn.btn2.gotoAndPlay(5);
		}
		
		
		
		
		//btn3
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.knopka.addEventListener("mouseover", fl_MouseOverHandler_3);
		
		function fl_MouseOverHandler_3()
		{
		 _this.btn.btn3.gotoAndPlay(1);
		}
		
		
		
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.knopka.addEventListener("mouseout", fl_MouseOutHandler_3);
		
		function fl_MouseOutHandler_3()
		{
		 _this.btn.btn3.gotoAndPlay(5);
		}
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		var _this = this;
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(link1, "_blank");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// ramka
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(1,1,1).p("EgtTgHBMBanAAAIAAODMhanAAAg");
	this.shape.setTransform(290,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// knopka
	this.knopka = new lib.Символ46();
	this.knopka.setTransform(505,46,1,1,0,0,0,70,36);
	new cjs.ButtonHelper(this.knopka, 0, 1, 2, false, new lib.Символ46(), 3);

	this.timeline.addTween(cjs.Tween.get(this.knopka).wait(1));

	// m (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgsgAGPIAAsdMBZCAAAIAAMdg");
	mask.setTransform(290,45);

	// BTN
	this.btn = new lib.Символ45();
	this.btn.setTransform(94.1,70,1,1,0,0,0,76,45);

	this.btn.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

	// text
	this.instance = new lib.Символ3();
	this.instance.setTransform(93,45,1,1,0,0,0,74,20);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// bg
	this.instance_1 = new lib.Символ1();
	this.instance_1.setTransform(290,45,1,1,0,0,0,290,45);

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(289,44,582,92);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;