(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/siege.jpg?1464261958157", id:"siege"},
		{src:"images/tre.png?1464261958157", id:"tre"},
		{src:"images/tre2.png?1464261958157", id:"tre2"}
	]
};



// symbols:



(lib.siege = function() {
	this.initialize(img.siege);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,767,350);


(lib.tre = function() {
	this.initialize(img.tre);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,273,99);


(lib.tre2 = function() {
	this.initialize(img.tre2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,163,121);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAkSMIgJgSIg1AAIgIASIgpAAIAAgFIBEiQIAQAAIBDCQIAAAFgAAPRZIgPgjIgNAjIAcAAgAAdOyIgfg5IgSABIAAA4IgnAAIAAiUIAnAAIAAA6IALAAQAHAAACgCQAEgDADgHIAGgUQABgHAEgGQAEgGAGgDQAHgEAJgBQAKgBAMADIAAAaQgHgBgFACQgEADgCAGQgEAOgEAJQgEAKgGAGIAqBCIAAAGgAgJLYIgNgDIgNgGIgMgIIgJgLQgFgGgDgHQgDgHgBgIQgCgIAAgKQAAgJACgIQABgJADgHQADgHAFgGIAJgKIAMgJQAGgDAHgCQAJgEAQgBQAMAAALADQAMADAJAHQAMAKAFAHQADAGACAGQADAHABAHIglAAQgCgGgDgEQgDgEgEgCIgKgEIgLgBQgGAAgHADQgGACgGAGQgEAFgDAIQgCAHAAAJQAAAIACAIQADAHAEAFQAGAGAGADQAHADAGAAQAGAAAGgBQAFgCAEgCQAFgDACgFQAEgEABgGIAlAAQgBAIgCAGQgCAHgEAGIgHAKIgJAIQgJAHgMADQgLADgNAAgAgNIAIgNgEQgHgCgGgEIgMgIIgJgLQgFgGgDgHQgDgIgBgIQgCgIAAgKQAAgJACgJQABgIAEgHQADgHAEgGQAEgGAGgFIALgJIANgGQAHgCAHgBIAMgCIAOACQAHABAHACIANAGIALAJIAKALQAEAGADAHQADAHACAIQACAJAAAJQAAAJgCAHQgBAIgDAHQgDAHgEAGIgJALQgFAGgGAEIgNAGIgOAEQgIACgIAAgAgMGPQgHACgFAFQgFAFgDAIQgDAHAAAKQAAAKADAIQADAHAFAFQAFAFAHADQAHACAFAAQAHAAAHgCQAGgDAFgFQAGgFADgHQADgIAAgKQAAgJgDgIQgDgHgGgGQgEgFgHgCQgHgDgHAAQgFAAgHADgAg0EkIAAiUIBAAAQAGAAAGACQAGABAFACQAKAEAHAJQAGAHAEAKQADAKgBALQAAAKgDAKQgDAJgHAIQgHAIgJAEQgPAFgIAAIgZAAIAAAmgAgODcIAaAAQAHAAAEgHQAFgGAAgIQAAgJgEgGQgFgGgHAAIgaAAgAg1BKIAAiRIBoAAIAAAhIhCAAIAAATIAZAAQANAAALAEQAJADAHAHQAHAFADAIQADAIAAAKQAAAKgDAIQgEAJgGAHQgHAHgKADQgKAEgNAAgAgPAoIAZAAQAIAAAEgEQAEgEAAgGQAAgGgEgEQgFgEgHAAIgZAAgAAkloIgJgSIg1AAIgIASIgpAAIAAgFIBEiQIAQAAIBDCQIAAAFgAAPmaIgPgkIgNAkIAcAAgAhJpDIABgbIAKAAQAEgBACgCQAEgDABgNIAKhkIBnAAIAACTIgnAAIAAhxIgeAAIgGBEQgBAQgEAKQgDAKgHAEQgHAFgLABIgEAAQgJAAgOgCgAg+sbIAAiUIAnAAIAABIIBLhJIAMAAIAACUIgnAAIAAhMIhMBNgAgJv1IgNgEIgNgGIgMgIIgJgLQgFgFgDgIQgDgHgBgIQgCgIAAgJQAAgKACgIQABgIADgHQADgHAFgGIAJgLQAGgFAGgDIANgGQAJgDAQgCQAMAAALAEQAMADAJAHQAMAKAFAHQADAFACAHQADAGABAHIglAAQgCgFgDgEIgHgHQgFgDgFgBIgLgBQgGAAgHADQgGADgGAFQgEAGgDAHQgCAHAAAKQAAAIACAHQADAHAEAGQAGAFAGAEQAHADAGAAQAGAAAGgCQAFgBAEgDQAFgDACgEQAEgFABgGIAlAAQgBAIgCAHQgCAGgEAGIgHAKIgJAIQgJAHgMAEQgLADgNAAg");
	this.shape.setTransform(-0.1,12.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(30));

	// Слой 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AiVWpMAAAgtRIErAAMAAAAtRg");
	var mask_graphics_1 = new cjs.Graphics().p("AiVWlMAAAgtJIErAAMAAAAtJg");
	var mask_graphics_2 = new cjs.Graphics().p("AiVWYMAAAgsvIErAAMAAAAsvg");
	var mask_graphics_3 = new cjs.Graphics().p("AiVWCMAAAgsDIErAAMAAAAsDg");
	var mask_graphics_4 = new cjs.Graphics().p("AiVVkMAAAgrHIErAAMAAAArHg");
	var mask_graphics_5 = new cjs.Graphics().p("AiVU9MAAAgp5IErAAMAAAAp5g");
	var mask_graphics_6 = new cjs.Graphics().p("AiVUNMAAAgoZIErAAMAAAAoZg");
	var mask_graphics_7 = new cjs.Graphics().p("AiVTVMAAAgmpIErAAMAAAAmpg");
	var mask_graphics_8 = new cjs.Graphics().p("AiVSdMAAAgk5IErAAMAAAAk5g");
	var mask_graphics_9 = new cjs.Graphics().p("AiVRtMAAAgjZIErAAMAAAAjZg");
	var mask_graphics_10 = new cjs.Graphics().p("AiVRGMAAAgiLIErAAMAAAAiLg");
	var mask_graphics_11 = new cjs.Graphics().p("AiVQoMAAAghPIErAAMAAAAhPg");
	var mask_graphics_12 = new cjs.Graphics().p("AiVQSMAAAggjIErAAMAAAAgjg");
	var mask_graphics_13 = new cjs.Graphics().p("AiVQFMAAAggJIErAAMAAAAgJg");
	var mask_graphics_14 = new cjs.Graphics().p("AiVQAIAA//IErAAIAAf/g");
	var mask_graphics_15 = new cjs.Graphics().p("AiVQEMAAAggHIErAAMAAAAgHg");
	var mask_graphics_16 = new cjs.Graphics().p("AiVQPMAAAggdIErAAMAAAAgdg");
	var mask_graphics_17 = new cjs.Graphics().p("AiVQgMAAAgg/IErAAMAAAAg/g");
	var mask_graphics_18 = new cjs.Graphics().p("AiVQ5MAAAghxIErAAMAAAAhxg");
	var mask_graphics_19 = new cjs.Graphics().p("AiVRZMAAAgixIErAAMAAAAixg");
	var mask_graphics_20 = new cjs.Graphics().p("AiVSAMAAAgj/IErAAMAAAAj/g");
	var mask_graphics_21 = new cjs.Graphics().p("AiVSuMAAAglbIErAAMAAAAlbg");
	var mask_graphics_22 = new cjs.Graphics().p("AiVTjMAAAgnFIErAAMAAAAnFg");
	var mask_graphics_23 = new cjs.Graphics().p("AiVUYMAAAgovIErAAMAAAAovg");
	var mask_graphics_24 = new cjs.Graphics().p("AiVVEMAAAgqHIErAAMAAAAqHg");
	var mask_graphics_25 = new cjs.Graphics().p("AiVVoMAAAgrPIErAAMAAAArPg");
	var mask_graphics_26 = new cjs.Graphics().p("AiVWFMAAAgsJIErAAMAAAAsJg");
	var mask_graphics_27 = new cjs.Graphics().p("AiVWZMAAAgsxIErAAMAAAAsxg");
	var mask_graphics_28 = new cjs.Graphics().p("AiVWlMAAAgtJIErAAMAAAAtJg");
	var mask_graphics_29 = new cjs.Graphics().p("AiVWpMAAAgtRIErAAMAAAAtRg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:0,y:0}).wait(1).to({graphics:mask_graphics_1,x:0,y:0.4}).wait(1).to({graphics:mask_graphics_2,x:0,y:1.7}).wait(1).to({graphics:mask_graphics_3,x:0,y:3.9}).wait(1).to({graphics:mask_graphics_4,x:0,y:6.9}).wait(1).to({graphics:mask_graphics_5,x:0,y:10.8}).wait(1).to({graphics:mask_graphics_6,x:0,y:15.6}).wait(1).to({graphics:mask_graphics_7,x:0,y:21.3}).wait(1).to({graphics:mask_graphics_8,x:0,y:26.9}).wait(1).to({graphics:mask_graphics_9,x:0,y:31.6}).wait(1).to({graphics:mask_graphics_10,x:0,y:35.5}).wait(1).to({graphics:mask_graphics_11,x:0,y:38.5}).wait(1).to({graphics:mask_graphics_12,x:0,y:40.7}).wait(1).to({graphics:mask_graphics_13,x:0,y:42}).wait(1).to({graphics:mask_graphics_14,x:0,y:42.5}).wait(1).to({graphics:mask_graphics_15,x:0,y:42.1}).wait(1).to({graphics:mask_graphics_16,x:0,y:41.1}).wait(1).to({graphics:mask_graphics_17,x:0,y:39.3}).wait(1).to({graphics:mask_graphics_18,x:0,y:36.8}).wait(1).to({graphics:mask_graphics_19,x:0,y:33.7}).wait(1).to({graphics:mask_graphics_20,x:0,y:29.8}).wait(1).to({graphics:mask_graphics_21,x:0,y:25.2}).wait(1).to({graphics:mask_graphics_22,x:0,y:19.9}).wait(1).to({graphics:mask_graphics_23,x:0,y:14.6}).wait(1).to({graphics:mask_graphics_24,x:0,y:10.2}).wait(1).to({graphics:mask_graphics_25,x:0,y:6.5}).wait(1).to({graphics:mask_graphics_26,x:0,y:3.7}).wait(1).to({graphics:mask_graphics_27,x:0,y:1.7}).wait(1).to({graphics:mask_graphics_28,x:0,y:0.4}).wait(1).to({graphics:mask_graphics_29,x:0,y:0}).wait(1));

	// Слой 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FF0000","#FFA600","#307F00"],[0,0.553,1],0,-145,0,145).s().p("AiVWpMAAAgtRIErAAMAAAAtRg");

	this.shape_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(30));

	// Слой 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(1,1,1).p("AiV2pIErAAMAAAAtTIkrAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16,-146,32,292);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AtFNFQlclbAAnqQAAnoFclcQFcldHpAAQHpAAFcFdQFdFcAAHoQAAHqldFbQlcFdnpAAQnpAAlcldg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-118.6,-118.6,237.3,237.3);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgwaADHIAAmNMBg1AAAIAAGNg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-310,-20,620,40);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF00").s().p("AdMFZQgagFgXgIQgZgJgVgMQgWgOgUgRQgTgRgPgVQgPgWgLgaQgLgagFgeQgHgeAAgiQAAgiAHgeQAFgcAMgaQALgaAQgWQAPgWATgRQATgQAXgOQAVgNAZgJQAYgIAagEIAzgFIAyAFQAaAEAXAIQAYAJAXANQAVAOATAQQATARAQAWQAQAWALAaQALAaAGAcQAGAegBAiQAAAfgEAbQgFAcgLAZQgJAagOAWQgOAVgTASQgRASgWAPQgWAOgZAKQgYAKgcAFQgcAFgfABgAdQg7QgZAJgTARQgTATgKAZQgMAcAAAjQAAAiAMAdQAJAaAUATQATARAYAKQAYAJAZAAQAaAAAYgJQAXgKATgRQATgTALgaQALgdABgiQAAgigLgdQgLgXgUgUQgRgRgZgKQgWgJgaAAQgaAAgYAJgA3vFdQg7gJgkgOIARhhQApAPAWgHQAOgDAKgKQALgMAKgVIARglIi2lFIAAgSICZAAIBkDKIAEAAIBajKICUAAIAAAOIjBGFQgVAxgVAbQgZAfgdAPQgPAIgSADQgNACgPAAIgKAAgEAmnAFVIgxgOQgXgIgWgMQgXgOgTgQQgTgSgQgUQgPgWgLgZQgMgagFgcQgHgfABghQgBghAHgeQAFgcAMgZQALgaAPgVQAQgVATgSQATgQAXgNQAUgMAZgJQAggLBEgGQAqAAAnAMQArAMAiAYQArAkAQAaQAMATAIAYQAIAWAEAYIiFAAQgHgRgLgPQgLgOgPgKQgPgJgSgFQgRgDgWAAQgeAAgZAKQgYAKgSATQgRAUgKAYQgIAbgBAhQABAdAIAaQAKAaARATQASAWAYALQAZALAeAAQAWAAATgFQASgFAPgKQARgLAJgPQAMgRAFgVICGAAQgEAcgIAYQgJAYgMAUQgMAVgOAPIggAeQghAZgsAMQgnALgsAAgAxUFVIAAoSICKAAIAAEBIEWkEIAqAAIAAIUIiLAAIAAkSIkWETgEAzNAFUIAAoRICHAAIAACeIBhAAQAgAAAzAQQAjAPAZAaQAXAZANAiQALAgABAkQgBAjgLAhQgNAhgXAaQgZAbgjAQQgzAPggACgEA1UADZIBhAAQAbAAARgUQAOgSgBgaQgBgagOgSQgQgUgaAAIhhAAgEAt+AFUIAAmYIiDAAIAAh5IGKAAIAAB5IiBAAIAAGYgAWQFUIAAmUIikAAIAAGUIiKAAIAAoRIG6AAIAAIRgAKwFUIAAoRIFMAAIAAB4IjBAAIAABKICyAAIAAB6IiyAAIAABWIDIAAIAAB/gAgiFUIh0jNQgQABgzABIAADLIiLAAIAAoRICLAAIAADOIAogBQAZgCAMgFQARgJALgYQAHgSANg3QAGgaAOgTQAOgWAWgNQAXgOAfgEQAjgDAtAKIAABdQgbgCgPAIQgQAIgGAYQgOAzgOAdQgOAjgWAYICWDtIAAAVgA8jFUIh1jNQgPABgzABIAADLIiKAAIAAoRICKAAIAADOIAogBQAZgCANgFQAQgJALgYQAHgSANg3QAGgaANgTQAPgWAVgNQAYgOAhgEQAjgDAtAKIAABdQgbgCgPAIQgRAIgGAYQgOAzgOAdQgPAjgWAYICYDtIAAAVgEgkkAFUIgghDIjGAAIgeBDIiRAAIAAgUID0oDIA/AAIDxIDIAAAUgEgneACdIBuAAIg3iAgEgvGAFUIAAmYIiCAAIAAh5IGKAAIAAB5IiBAAIAAGYgEgzdAFUIgghDIjGAAIgeBDIiRAAIAAgUID0oDIA/AAIDxIDIAAAUgEg2XACdIBuAAIg3iAgAC/FSIAAoQIDqAAQAXAAAWAEQAVAFASAIQAjAQAZAdQAXAcAMAkQAMAjgBAkQABAlgMAjQgNAjgXAaQgaAdgiAPQgzARggAAIhfAAIAACJgAFHBRIBiAAQAaAAARgZQAOgWAAgeQAAgdgOgVQgQgXgbAAIhiAAgAuNjhQgXgIgQgQQgQgPgIgYQgJgXgCgeIBMgHQABATAMAKQANALAXAAQAYAAAMgJQAOgKADgVIBMAHQgCAegJAXQgIAYgQAPQgQAQgXAIQgYAIgdAAQgeAAgXgIg");
	this.shape.setTransform(-2.9,-2.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-372.9,-37.9,740,70);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADtFAIgBAAQgqACgsAAQilAAiIghQguAHg0AAQh8AAhXgpQhZgoABg6QAAgvA6gjQgFgQgCgRQhEAThTAAQh8AAhZgpQhXgmgBg6QABg5BXgpQBZgoB8AAQBFAAA6ANQgCgKAAgKQAAg6BXgoQBZgpB7AAQB8AABZApQArAVAWAZQAugDAyAAQENAAC+BYQCvBQAPBuQAhAJAeANQBXApABA5QgBA6hXAoQg1AZhDAKQgSAlg+AcQhZAph7AAQh8AAhZgpg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-95,-36.1,190,72.3);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("ArBL9IgHgDIgDgEIAAgDIAAgEIADgEIACgBIAAgDQABgHgDgFIgDgFQgBgDACgDIADgHIAAgDQgMg7gCg/IgBgpQgBgZgCgRQgDgTgIgeIgMgxQgJgogDhKQgGiWgDjqQgBgmgCgPQgCgdgIgWIgLgcIgNgcQgTgxgGhMQgGhhANhjQAEgZANgBIAGgBIAAAHIABgBQAGgCAPgBQAPgFACgSQACgGgDgYQgDgWAKgJQAEgDANgDIAwgLQgIgjATgeIAEAFQAcgCAOAEQAKADAIAIQAIAIABAKIAAAMQAAAHACAFQAFAIARACQAfAFAdgMQgBgFgFgFIgHgKQgKgMAGgJQAFgHANgBQAfgGAQAGQAMADAIAKQAIAKgBAMIgDAQQgCAJAFAFQAFADAMgCIAugIQgLgvAWgNQALgHAYADQAWACAJAHQAMAKAFAdQAMBEASBFQAJAkANANQARAUAkAHQAjAIARgQQAKgKACgTQACgMgBgSIgCggQgBgnATgTIAcgSQAQgLACgNQAAgEgCgOQgBgLAEgGQAEgGAKgBQAJABAHAGQAJAJACAWQAFAEAGgDQAHgEABgGIABgNQAAgJABgEQACgNAQgBQAPgBAFALQADAGABALQABALADAGQAJAOATgDQAKgBATgLQgIgjATgJQAHgCAJADQAIAFAFAIQAFAJAAAZIgBAIIAOgBIAFgBQAHgCAAgOIgBgTQAAgHACgEQADgGAMgDIATgGIgBgBIAKAAQAGAAADACQAIADAAAJQgBAGgFAJIgBAMQgBAIAEAEQADAEAGACIALABQAKACAGAHQABgDgCgLQgDgKABgXQAAgFABgCQADgEAGAAIALACIASACQAKABAGAFQAFAHAAAOIAAAUIAAADIAngDIABghIgBgFIgEgFIgBgGIABgGQABgDADgCQAFgBABgBQAIgBAFAHIACACIAFACQAFABADAEQABACAAAHIABAlIAogDIgBgEIgCgDIgBgFIgBgDIgBgEIgDgEIgBgDIAAgEIACgEIADgEIAAgDIAAgEIACgEIADgDIAAgFIAAgDIACgEIADgDIAFAAIAAgBIAGADIADAEIABADIAAADIAAABIAKACIAGACIAYACIAGADIADAEIABADIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIACADIACAEIABAEIAAADIAAADIAEAAIABgCIAFgBIATgCIAGgCIAJgDIABgEIAAgDIAAgFIAAgDIAAgEIAAgEIAAgDIAAgEIAAgEIABgEIADgCIABgBIAFgBIAYgDIAGgDIAFAAIAGADIADAEIABADIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAAEIACACIAlgBIAGgEIAAgEIgDgDIgCgEIAAgEIAAgDIAAgFIAAgDIAAgEIAAgDIAAgFIAAgDIACgEIADgDIAFgBIAeAAIAGADIADAEIABADIAAAEIAAAEIAAAEIACADIADAEIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAACIATgBIAGgCIAYgDIAGgEIAAgDIAAgFIAAgDIAAgEIAAgEIAAgDIAAgEIAAgEIABgEIADgCIABgBIAGgDIAEgDIAFgBIAFAAIAGADIAEAEIACADIADAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIACADIACAEIABAEIAAADIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIACAFIADADIABAEIADAEIABADIACAEIACAEIABAEIACACIADABIAGADIADAEIABADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIgBAEIgCAEIgCAEIAAADIAAAEIAAAEIAAADIgBAFIgCADIgBAEIgBADIAAAEIAAAEIAAAEIAAAEIgBADIgDAEIgBAEIAAADIAAAFIAAADIAAAEIgDADIgBAEIgBAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIgBADIgCAEIgCADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIgBADIgCAEIgCADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIgBADIgCAFIgBADIgBAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIgBAEIgCADIgCAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAACIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIgDADIgCAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIgBAEIgCAEIgCAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIgBADIgCAEIgBAEIgBADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIgBAEIgCADIgBAFIgBADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIgBADIgCAEIgCAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIACADIACAEIABAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIgBADIgDAEIgGADIgGACIgCAEIgCADIgFABI2yAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.8,-76.5,167.6,153);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EE0000").s().p("AGRL+IgEgDIgBgFIgCgCIgHACIstAAIAAAAIgCAAQgFAAgCgEIgBgBIAAgDIAAgGQAAgTADgjQADgmAAgRQAAgXgEgeIgHg1QgNhfAEhvQAEhYAPh1QAGgqgBgUQAAgSgEgXIgHgoQgShkgChmQgEgFADgOQASg5gSgxQgCgIgMgaQgMgYgEgQQgFgXAFgSQACgJALgUQAKgTACgMIADgVQACgLAIgEIAJgBQAHAAADgCQAIgEABgMIAAgUQgBgMAEgPIAIgZQAHgegCglQgCgZALgFQAGgBAGADQAGADACAHQAEAIgDAQQgDAMAFAEQAEACAHgBIA4gEQgIgQAFgTQAEgSAOgLIABABQAHABAUgBQAQgBAJADQAPAIADAUQACAJgCAZIAtgBQACgHgBgJIgCgPQgCgVANgGQAFgBAHABIABAAQADgDAEABIAAgBIAAAAIATAAIAHABIAMAAQAQgBADABQAHAEAAAIQAAAEgCADIABAHIAJAmIABADIABgCIAEgEIACgCIAFAAIAAgBIA3AAIAAgSIgCgGIgBgKIAAgPIABgHQADgGAFACIAAgBQAEAAADADIAGADIANgBIAYgEIACgBIAAAAIAKAAQAGAAAEABQAGAEgBAHIgEAJQgBAFAAAIIAAAbIAjAAQABgEgBgCIgCgFIgBgFIABgcQAAgGABgCIACgBQACgEAEgBIADAAIAAgBIBKADQAFAAADACQAHADgBAIQAAAEgDAIIAAALIgBAOIgBAGIA3AAIgBgGQgCgLAAgGIAAgIIgCgFIgBgMIABgEQADgHAGABIABgBIABAAQACgDAFgBIACAAQAVACAaAAIAJAAQAFABACAEQABACAAAGIAAAOIgCAJIAAAZIBMAAIADgEIABgFQAAgJgBgEIgEgHQgCgGAGgEQAEgCAFAAIAVgDIABgBIAdgBQAIAAAFAEIACAAQAGANAAAUQAAALgDAWQgWDDgEETQgCCdgBE5QgCBwgLA8IgJAnIgHAoQgFAiABBDIgBB7QgBAJgEAIIgEAFIAAABIgBAFIgCADIgHACIgGgCg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49.2,-76.9,98.5,153.8);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgXHDQgIgBgQgEIgYgGIgSgDQgJgCgGgEQgNgKgBgYIgCgoQgCgKgTgjQgPgaAFgSIAGgOQADgIgDgGQgBgDgLgJQgJgHgCgLQgDgLADgKQgHgEgMACIgUAGQgLAEgKgCQgMgDgCgJQgDgKAKgJQAGgFAPgIQAbgQAVgnQAagyAJhAQAGg0gDhHIhGgCQgOAAgBgIQgBgGALgFQAbgOAegZQASgPAgggQAXgWALgNQAtg2AJhGIACgWIAEgVIAEAAQANASANAjQAQAqAGAMQAOAbAiAqQAaAfANAOQAXAZAVAQQAKAHACAGQACAJgJAHQgHAGgLABIgVABQgLAAgGAGQABBGAGBFQABAWAIAMIAIAJQAFAFACAEQAFAIAAARQAAATABAGQAFASAYAPIApAaQAJAHgDAGQgBAFgJACQgmAKgoADQgDAJABAMIADAWQACAMgDAKQgEALgJAEQgJADgPgEQgTgFgHgFQgGgFgDgGIgBgEQgBATgMAQQgQAWgXAFIAFBMQABAUgCALQgCASgKAKQgNAMgVAAIgLAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.4,-45.1,48.8,90.4);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AE1U7QgFgBgCgEIpbACIgHADIgFAAIgGgDIgEgEIgEgDIgBgEIAAgEIAAgEIAAgDIAAgEIAAgEIABgBIgBgFQAAgNAFgRQAJgdgGgwQgJhAAAgPQABgeAOgsIAWhKQAJgnACgyQABgbgCg+QgChfAAi8QAAhJADgkQAEg9APguIALgfIAKggQAHgcABg1IAGipQABgkgLgOQgFgGgMgJQgNgJgFgFQgLgNgCgWQgBgMADgdQAEg7gLg4QgtAMgvgDQgTAAgFgKQgHgMATgSIAsgpQAegcANgOQAXgZAOgWQAgg0AIhNQAFgxgGhaQgCgkgIgQQgHgNgLgHQgMgJgNACIgNAEIgOAFQgIABgGgDQgFgDgCgDIgCgBIgEgDIgFAAQgDgBgBgEQgCgDABgEQACgFAHgGIAGgFIAAgDIABgEIADgCIABgBIAFAAIAAgCIABABICZiRQAxgtASgcQAKgOAVgsQAWgxAJgcQAOgtgCglQgBgYABgIQACgSAMgIIABgBQAQAFgCAkQgDBJAcBGQANAdAXAkQA1BSBIBKQAZAZAVATQAXAUANAGIARAIQAKAFAFAGIAIANQAFAHAEAEIAKAGQAFAEABAEQACAGgFAEIgEADQgEAFgMACQhAAIg/gYIgCC4QAAAUAGAIIALAMQAIALgCAXQgDAbADAJQAEANAQAUQAHAMAKAaQALAYAYAXQAPAQAfAXIBKA3QAPALgFAJQgDAIgRgCIibgSIAHD4QACBCAHAhIAJAnQAGAXABAPQAEAhgIBFQgIBCAFAjQAEAOgHAFQAHBDgBAlQAAAOgCAfQgDAeAAAPQABAZACAaIAHBNQAEAvAEAXIAKAsQAEAggJBAQgDAbABAPQABAYAKAQQAFAHAAAEIAAAEQAGAGADAFQAFAKgBASIgBAdIAFAbIABAZIAAAzQAAAKgDAFQgFAJgIgDQACAIgBAMIgBATQAAAZAKAMIAJAIQAFAFADAEQAEAGAAAQIAAAaQAAAJgDAEQgEAGgGAAIgDAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.9,-133.9,81.8,267.9);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AE3UxQgFgBgCgEIAAAAIp0AAIgHgDIgDgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIACgCIAAgIQANg5AFgdQACgNAAgJIgCgMQgCgOACgZQACgcgBgMIgEgdQgDgRACgLQACgLANgYQAIgQADgMIAAgHIADgzIADgzQABgTgCgyQgCgrABgZQAAgGACgEIABgBQALiugEizQAAgJABgEIABgBIgBhLIAEg6QADgigCgYQgBgJACgEQABgEACgCIgDhIQgCg8ABgfIAEgvIAFgwQADgiAAgiQAAgIABgDIABgBIgHhWIgUAAQgUACgoABIgNAAQgIAAgCgDQgDgBgGABIgGABIgEABIgLACQgIAAgEgDQgHgGADgFQACgEAKgDQAQgEAMgIIAAgBIADgDIAUgOIAAgBIAEgDIAnglQAXgYANgKIAIgHIAEgGIgBgLIgBgKQAAgGACgDQAEgJAMgEQACgGAHgIIAKgNQAFgLAAgYIAAgrQAAgHABgDQACgEADAAIABgFQADgKAAgWIABi8QgggBguADIgiABQgIABgEgDQgDgDAAgEQAAgFADgDQAEgEAIgCIAugiQAagSAOgMQAKgIAYgaIAxg0QAggiAQgYQAJgNAQghIBAiFIgCgCIgBgDIAAgJIABgCIAAgBIgBgOIADg/QAAgGABgDQADgFAGAAQAFAAABAFIACALIADAcIAFAxQABAEgBAEIgCAHIgBAMIgBAHIA3BiQAhA4AgAnQAgAnBDBAQAUAVAPAKIAeARQATALAKAJQANAMgGAIQgCACgDABIgBABIgIACIgfABQgTAAgLACIgRAEQgKABgHgBIgDgBIgBAEQgGAmADBFQAEBMgEAgQAEgBADACQADACABAEQABAFgDAJIgHAPIAAAcQAAARAFALQAGgDAHADQAHADADAGQAFAKgBASQAEgCAFADQAEACACAFQADAHgEALQgFAKABAEQACAFAFADQAfAcA6AqQAYASASAIIAOAGQAIAFAAAHQABAEgDADQgCADgEABIgBAAQgEABgEgCIgJgCIgHAAQguAAhCgCIgFgBIgBADIABAPIgBAGIgDAEIAAABIgCAeIgFBCQgBAYAEA7QAHAEAAALQAAANgKAGQgNAJgegDQgJCcACBQQABAeADASQAEAaAMASIALAQQAIAKADAHQAJARACAlIATHbQACAzACAUQADAoAHAeIAMAwQAHAdACATQADAVAAAmQgBAqACASIAHA2QAFAhgCAVQgBAIgDAFQgDAGgFAAIgCgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-41.6,-133,83.2,266);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AksTuIgDABIgGgDIgEgEIAAgDIAAgDQgCgFACgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAEgEIAGgBIAAgBIABAAIABgDQADgFAAgIIAAhoQAAgMgCgGIgDgGIgBgJIABgYIAAgFIAAgEIgBhJQAAgKACgFQADgLALgJIAGgHIAEhOQAGiQAKikQAKilABjoQAAjnAHh8QABgbgJgJQgLgLgdAFIhUANQgJACgIgDQgIgEACgHIAFgCQgEgEgBgDQAAgEAEgEQADgEAGgCIAJgEQAGgCAHgIIALgMIAZgSIAOgGIAOgIIAYgRIAXgQIADgCIAQgWIAAgEQAAgOAEgEQADgFAKgBIAEgGQgDgKAHgOIAIgOQADgIAAgGIgEgOIgFgUQgCgGAAgHQAAgIADgJQAEgHADgDIAPgMIgDgfQgGhNAJhRQg4ALg6gCIgEABIgFgBIgHgBIAEgCQgEgDABgFQAAgDAHgGIAOgPQAJgKAHgEQAKgGAVgJQAMgHARgUIAVgbIAdgiIAagbQAPgQAJgNIAyhPIARgdIAPgWQAIgMAEgKIAFgLQgBgGAAgLIAAhjQAAgSAKABIAAgBQAGABACAMIAJAzQAHAFADAJQAEAIgDAJIgFARQAAAFAEAKQABAHgBAQQABAPALAVQANAXAjAsIA4BGQAOAQAJAOIAPAYQAJAPAIAIQARAUAxAaQAdAPASAPIAIAAQAHAAADACQADACAAAEQABAEgCADIgDACIABAAQADAGAAADQAAAEgFADQgEACgFgBQgEgBgGgFIgGADIgHADIgKABIgiACQgKAAgFADIgEADQgEACgJgEIgFgCIgLCnQgBATACAJIACAGIACgBIABAHIAEALIAAALQALA4AZA1QAFALAFAIIALAOQAKAKAYAQQAoAbAhAjIACABQAOAGAJAJQAFAGABAIQAAAKgIABQgFABgJgIIgFgEIgFABIhmAGQgCBVgYBWQgDALgFADQgDACgGAAIgJABQgRAEgBAhQgBA2ABAdQACAvAIAkIAOA1QAJAhACAUQAEAZgCAkIgCA9QgBAjAIBiQAODGgTDCQACAEABAHIADAQIABAZIAABQQAAAXABALIADASIABAYIABAYIADAYQACARAAARQAAAegDAPQgDAMgGAGIABACIgBADIgDAEIgGADIoKACIgGADIgCgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.1,-126.3,80.2,252.7);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.tre();
	this.instance.setTransform(-136.5,-49.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-136.5,-49.5,273,99);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.tre2();
	this.instance.setTransform(-81.5,-60.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.5,-60.5,163,121);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.siege();
	this.instance.setTransform(-383.5,-175);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-383.5,-175,767,350);


(lib.shape161 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AF6KaQgbgNgeAAIg4AEIhxAKIgPABIiwgLIgzgIQhGAAgcAJIguAJIgegFIgDABQgSAIgSAAIgcgHIghgJIgOgCIgOADIgkAJIgYgDQgFAEgGAAQgLAAgHgQIgKgFIAAgEIAIgBIgEgTQAAg1AUhJQgEguAEhRIAIAAIABAFIADgBIAXAdQAXAaAWAAQAoAAAPgmIAKg0IAIgtQAHgcAKgTQAhg7ANggQATgxAAgrQAAgSgJgdQgKgcgMgSIgKgYQgHgTgDgFIgTgVQgNgOgCgKIACgEIAIgCQAGAAAMAJQALAJALAAQAIAAAAgRIgCgTQADgQAJAIQAHAFAGANIAYApQABAEAfAOIALAFIANADIAtgBIANgCIAUArQAWApAQAAQAfAAAJgeIAGgZQAEgNAFgFQALAIADAYQADAZANAJIASAPQAJAIAPAGIATAEQAMADAAAKQAAAVgIAyQgIAyAAAVQAAA6AhA3QAqBKAQA8QAThBAEgyQAGhGADgOQAMguAkgoIAggpQAYgdAPgNQAQgNAMgdQAMgcAKgKQAMAKAKAYQANAkAGAKIApAmQAdAZAAATQAAANgVATQgaAYgFAIQgLASgDARQgCAJAAAYQAAAiAJAaIAVApQAeA3AABMQAAAUgNA+IgNA9IAAACIgCAJIgBADIgHADIgMACQgqAAgdgMgAn2iMQgFgoAPglIAaAaIARAXIgDAFIgEABQgUAHgMAQgABamAIgFgKIAIgKIApgrIAageQAFgHAHgEQAEgBgBAFIgLA4QgDAOACAOQAEAagQAGgAjrmXIAAgvQAMgOALASIASAZIgPAOQgNAIgGAAgAG0paIAKhGIAFgFIAdA/IgKAFIgdAJg");
	this.shape.setTransform(-14,68.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64.4,0.3,101,135.8);


(lib.shape160 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AGGIlIgOABIg+gGIhQgIIhlAJIhBAIIhggGIhCgHIhbgFIglADIgiAFIg/gFIhBgDIhMAFIgXAFIgcADIgBAAIgBgFQAAgHAIgJIAGgHIgCgDQAAgKAhgbQAggbAAghQAAglgdgoQghgvgJgwIABAAIgHgKIADgEIAKAPQAFADABAFQALAHAjAAQAjAAAwgtQApgmAFgTIAPhAQAFgZAAgcIgFg1IgGhQQgCg/hFhDQAagSALgcQAKgcgHgdQAMACAIAXIALAqQAIAyAUAdIAdAqQATAYAdALIA1AcQAyAbAKAAQAkAAAnhgIAIgZIAIgXIACgZQABgNAJgKQALAKADAXQAEAZAGAKIAKASQAHAJAOAJIAgAJQAYAHAAALIgGAXIgJAZIgGAUIgDAXQgCAfgFAVQgFARAAAUQAAAUAKAfIASAyQAEgJAHgIQAOgNAmgTIBAgnQAlgaAVgnIAthZIAGgxQADgcAXAAQAAAbAVApIAnBFQAKgBADgOQADgLgCgMIADgEQATANAGAYQAGAcAGAIQAKAOAHAWQAHAVAAARQAAAgg4BXQg5BXAAAxQAAAjAfA+QAYAxAVAYIAIAAIABACIABAGIAHAAIAAACIABAIQABATgnAAQgsAAgXgNgAAPmvIgGgHIgHgmQgEgZABgaIADgEQARAOATACQAQgBARgIIAigVIAcgQIgDARIgGAUQgJAUgRAOIhKBAg");
	this.shape.setTransform(-10.3,80.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.8,24.2,102.9,112.5);


(lib.shape159 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AAaGqIhPgLIiJAKIhKAKQgjAAgYgLQgZgLgPAAIhCALIg5ALIgVgCQgCABAAgKIAAgFQgGgIAAgKQAAghAbhAQAbhCAAgkQAAgRgIgqIAoACQAzAAAXgSQATgQAUgwQAEgKAHgjQAFgZAKgKIACACIABAGIgBAMIABAAIABgTQAAgigEgYQgEgbgNglIAAgUQANgFAMAVIASAmQAJAMAIATQAJAVAEAQQAOBEAcAbQAYAYAtAAQBBAAAxhXQAUgnAWhHIADgQIAGAAIADAbIABALIAAADIADAaQAAATAZAsQAUAlAhArQAlAwAOAAQAWAAAcggIAZgiIAkhFQALgWAkgyQAeguAAgaQAAgGAEgCIAEgBQATAcAPBTQAYBFBMAEIABABIABAHQAAAIgaApQgZAyAAAuQAAAxAYBOQAUBAADAVQAIADACAMQAAAKgTAJIAAABIgFAFIgCgCQgYAKgpAAIiIgKIhqAFIhSAFgAAlgrIgBgFIgBAFIACAAgAlVkHQgRgUgGgYIgBgPQAIgvgCgtIAIgWQARAdAFAfQAGAfADAfIAEA5QgFACgEAAQgIAAgIgIg");
	this.shape.setTransform(-9.2,91.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.8,48.2,103.3,87.5);


(lib.shape158 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AGtGeIh3gJIhHAEIhTgHIheAGIhIgEQhugGhvAEIhDgCIh2gIIhagHIgJgeQgDgNAAgMQACgeAPgaQATghAagaQAMgNADgRIAOhdIgKgMIAPAAIAEgDIADAJIAWgCQAJgBAGgGQAVgSAIgcQADgLAAgLIgEhIIAIgBIAHAKIAVAdIAXAZQAGAFAJACIAwADIAwApIAfATQAdANAhgCQAfgFAWgXQAigkAYgqIALApIAGAjQAEAkAbAWQAOANATAEQA+AMA4ggQAugbAdgtQAPgWAJgXIAchSQAOgoAbggIALBaIAeBnIAighIAGAIIARAdQAUAqAGAsQAKBMgQBKQgQBJgJBIIgWAEgAAHh5IACgZIAEgnQAEgngMgmQgFgPgIgOIgHgOIgIgcQgFgaAQgUIAOgRIgCARQAHAXAAAXQAAANAHAMIAxBOQAKAQgBASQgBAYgLATIgKASIgMAKQgKAHgJAAQgGAAgGgDgAlVjJQgJgdgNgNQgIgHgIggQgIgeAAgNIACgXIAOgZQAEgGABgUQACgQAIgBQALAKAPA0QAQA0AAAVIgCAvIgCBFQgCADgEABQgHgKgKgegAlzlHQAHgCgHgCg");
	this.shape.setTransform(-8.3,94.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.2,52.5,103.9,83.5);


(lib.shape157 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AHDG9IiIgCIhMgOIgbgHIiFAHQhOAMhPgKIhagKIhZgBIhMAGQhRAKhPgVIgBAIIgIAEIgPgPIAZlhIAJAAIBfBvIAEgNQADgNAAgNIABhaQACgiAFgfIAFgVQAIBbA8BGQAPARAUAHIArAMIAsAGQAaAAAZgKQAJgDAHgFQAZgSAQgcQAHgLADgNQAMgoAIgpIAIgCQAJAEACAJQAHAsAXAmQAMASASAMIAWANIAfALIB7AEQAdgGAagSIAUgRQAmgjAJg1QAFgagFgaQgPhFAahDIAGgIIAQAiQAQAiAAApIgBBQQgBA2AVAxIBKhFIAQBAQALAvAIAuQAJA6gOA4IgGAcQgEAegBAfQgBAVgIAUQgOAHgOAAIgKgBgAhJkpIgBgbQAEgdAMgaIAehCIAWBUQAGAYgCAXIgHAwIgGAwIACAaQADATgBAUIgIABQgxhAgFhRgAlpijQgVgmgQgoIgNgrQgKg8Afg1IAiBAQAGAKADALQAFATAAATQgCA4gHA3g");
	this.shape.setTransform(-3.5,90.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,46.3,103.6,89.3);


(lib.shape156 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AmSJrQgIgIgNgCIhJgBIgIAJQgUgQABgaQAChYAYhUIAIglQAFgggGghQArAAAhgbQAdgXAJgkIAIgaIAHgRIADAXIALAqQAHASAMAPIAiAmIASAPQAiAQAlAHIA4AHQAtAAAogXQA7giAMhEIACgTQAAgjgDgjIAOgCQAKAHAAAMIADBEQAEA0AnAiIAjAbQAvAjA5gHQBAgFAvgsQAcgaALgkQAOgugOguIgPg2QgIghgCgiQgCgdAEgbQABgHAEgHIAOAEIANAQQAVAWACAgIAEBQIgBBAQgEA4AZAwQAFguAgghIALBZQACAMAEALQAMAgAQAfQAUAnABAtIgCAtQgDASgIASIgYAvIABAQIguACIgoAIIgzACIhVgFQhSgDhRAEIidgFIgUgEIgdgIIibAFQgugCgrAPIgPAFIgGAAQgTAAgPgMgAgvhAQgSgkAAg4QAAgeAEgPIASg1QAGgSgBgfIABgwQALAFASAaQATAeALAKQAQATAHAWQAFAQAAAWQAAAagJAhIgPA9QgOA5ACA+QgCAEgEAAgAlKAeIgGgRQgDgogNgoIgQgwQgQgxABg1IALAAIAKAVQAJAPARANQALAHAHAJQAPAVAHAYIADASQACAbgLAZQgOAhgEAjgADnoGQgFgzARguIAEgPIAIADQAUAegEAjIgEAPQgMAYgHAXIgIACg");
	this.shape.setTransform(-5.7,72.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.2,9.8,105,126.3);


(lib.shape155 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("Al6IYIgzgUIgzgWQgJgFgFgJQgTghgHgnIgFglQgDghACgiQAEg2ANgzQARANANATQALARASAKQAiASAkgNQAKgCAIgHIAOgNIAJgQIAKgpIAKAAIAvAvQAPAPASAJQAeAPAiAAQAvgDAngaQAngaAUgsIAMggQAOgyAVgsIAMAtQAKAhAOAhQAVAxAxAXIBeAvQA1AcApAvQAHglAKgjQALgpAPgnQAQgqgBguIgBhmIAHAAIBFDLIAZgWQAIgHAJgEIAXgMQACgBADAAQgEAkgDAlQgCAkAFAiIAQBiIACAfQgBApgQAmIAFAKQgHAMgOgBIgggHIhEgEIg4AIIhrgDIjsgFIhrgLIhOAHIhTAIIhDAEIgOAEgAgCixQgEgagPgYQgYgpggghQgagbgUgiQgvBigdBoQgLACgHgLQgSgigOgmIgzCtIgLgBQgWgrgHguQgKhFgShEIAGgBIASAQQAVAWANAcIAGAAQACgeAMgaIAXgxIAbhAQAJgVAGgYQAIgggCgkIAJAAIAmAtIAKABIAQgGQAKgCAIgKIAHg1IAKABIAQAxQAOAbAaAMIAbgDIAZAEQADACACAFIAFAJIAGAUQANAhAUAjQALARACAWQADAugFAtIgGAbIgLAqIgSBGQgDAOgNAJQgBg/gHg/g");
	this.shape.setTransform(-6.3,82.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59.1,28.9,105.7,107.6);


(lib.shape154 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AHvHzQgNAHgOgBIhLgEIh9gBIg8gGIicAIIg2gFIgsgHQgegJgigBIgEgDIh5AJIh4AKIgRABIgigLQgrgSgxAAIgBgFIgBgLIADgbQACgWgDgUQgMhMgXhKIAFgFQAJgCAKAGIARAGIAxALQAXADAXgDQAugKAVgsIAHgUIAMg4IADAGIgHgpIAEgDQATAqAfAjQAUAXAaANQAfAOAgAAQAkAAAhgQQAbgMAUgWQAagdANgkQAQgmgBgpQgBgjgEglQgDgcgHgaQgFgZgMgXQgOgcgPgcQgWgmgJgsQgkApgYAyIgFAQQgCALABAOQABALgIAHIg0gNIgQgBQgKACgIADQgLAEgJAGQgJAHgFAJQgUAkgHArIgJAAIgNgVQgTgogKgtQgJgjAJgjIAIgCIAjAWQANAHANgEQAVgFALgSIAIgPQAPgdAEgfQALhIAEhKIAHgCIATANIAPAJIASAEQAUACAQgNIAIgJQAIgKAEgLIAGgVQAEgOALgJIAJAjIAQAqQALAUAWAAIAxgGIAHAEIgCANIgGBCQgDA2AQA1QAQA1gFA4QgHBKgVBFIAQAqQAJAUANASQALARAQANQAPANASAKIBAAkQAOAHAMALQAlAcAdAmQABgrARglQAthfAphjIAbAxQAVA0ACA3QADBFgBBFIA6gtIAJAQQAIARAEATQAGAZACAaQAFA5gNA3QgGAagRATg");
	this.shape.setTransform(-6.8,85.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.2,34.3,106.9,102.3);


(lib.shape153 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AmWHLQgTgMgLgFIghgIIgWgEIgCgJIAIgaQAIgYgBgHIgDgeIgEgeQAAgHgOgvIgMgrQgHgJgBgJIAEgCIANARIATAVIAiANIAoAMQBAAAAihFQAZgyAAgzQAAgdgQg3QgRhBgCgTIACgDIAJgBIAOARQAOARAZAAQA4AAAShEQAGgVACgaIAAgYIgIi5QABgOADgCIAXgCQAdAAASggIAXghQAAAWARAxQAWA9AYAAQAVAAAMgPQAPgRAFgCIAHA/IADBNQABA/gZBDIgBACIgBAEQgHAnAAAaIACAdIAAABIAJAAIAMAAQA5AAAdA5QASAngCAkQgBAfAOAlQAOAoAZAYQAOgYADgaIACg0IACgCQACgDAGAAQAGAAAJAPIAVAlQAlA9A3AgQABhDACgkQAGhAAZglIATAjQALAYAUASQAMALASAXQASAYAGAPQAVArAHAiQAJAiAAAnIgBAXQAFAFAAAKQAAAJgHAFIgHACIgCADQAEADgKAAQgGAAgDgFIgDAAQgZAAgXgIQgWgJgIAAQgJAAgeAMQgfAMgeAAIg5gIQgdgIgwAAIhlAKIhngNIhWgNQghAAhsARIh6ARQgRAAgKgHg");
	this.shape.setTransform(-6.6,89.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.6,43.2,104.1,93.3);


(lib.shape152 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AGJHBIglgGIgGABIhcAKQgZAAgugMIgsgNIgmALQglAKgZAAQg1AAhJgRQhIgSgqAAQgXAAhVASIhTAPIgBABIgBACIgHABIgIgCIgIAAQgPAAgUgSIgPgQIgCAAIgjABIgCgJQABgHAGgMQAHgMAAgNQADgOAAgfIAAgoQgDgQgUggIAAgSIABgBIAHgCQACAAATANQAZAMAkAAQA8AAARgkQAEgMAAgOIgBgMQABgagThIQgOg+gJgVIACgEQABgEAHAAIAPAJQAMAJAKAAQBeAAAciGQAKgtAAgzQgBgqgEgLIABgEQACgDAGAAQAFAAABAEQAAADAEAAQAUAAAQg8QAPg4ANgYIgBgGQABgFgEgDIgEgEQASgJAGAWQADAJACAaQAAAOAEAUIAIAfQALAbAXAnIAnBEQAXgXAKggQAIgYABglIAJgFQALAMACAeIAAAsQABAKgIA4IgHA8IgCA+QgDAlgRAYQBJAWAlBPQAbA6AABAIAFgCIALgCIAnALIAuAPIAXATIAYAbIACAAQAJgwAHgYQALgqAdgXQAjBJBFBSQAZAdAJASQANAZgBAiIAAAAIAEAKQgBAHgGAEIgPAFIgQADgAh2mWIAAAAIAAAAg");
	this.shape.setTransform(-4.9,90.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.8,45.3,101.8,91);


(lib.shape151 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("Al4IxQgogTgsgFIgFADIgNgFIAGgpIANgpIANguQAFgTgCgUQgDgkgQghQgEgJAAgKIATABQAZAUAhAEQAqADAegbQAUgSAHgaQARg/gWg/IALgCIAbAJIASgBQASgHAJgSQAlhLgChSIgCgSIgYhpIAYgFQANgHAJgOQAXgoAEgvIAFgeIAFgFQgDAkASAdQAiA3AqAuQAQASAKAUIAigrQAIgKACgNIAJgBQAHAEABAIQAGAagBAaIgCAvIgCBwIAEAmIAOAiQAiA+AqA6QAgAJAUAcQAiAxAJA7QATgLAOgTQAagkAcgiQAPAQAKAVIAIANIAtA4QAVAYAPAdIAyB6IgEANIiHANIgegHQhdgWhdAQIhMAMIgqgCIhVgOQhOgShPAJQgfACggAIIguAOQgJADgJAAQgRAAgQgIgAmqFHIABgBIgCgCgAFAjCIAAgQQAAggACgHQAGgTAcgVQAIAOAAAQQAAAIgNAgQgPAjgJAIQgFgHgCgLgAnxoDIANgnQADgJALgFIAFAMQAMAYAYAKIAEAGQgiAOglACQgEgGADgJg");
	this.shape.setTransform(-7.3,78.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.3,21.6,99.9,113.8);


(lib.shape150 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AmEIYIhQgRIgHAEQgKgCABgKQACgYAQgWQANgTAJgUQAOgeAEggIAEgaQAFgtgOgqQgMgigHgiIAIAAQANgIAQgBIArgBQALgDAKgHIAXgSIANgOQAMgRACgTIABgVIACgtIAMAAQAKAJAPACIAMACQAlgGAVgiIAQgbQANgagEgdIgNh7QgDggADghIAEgPIAFgGQAdAjAoAZQARALAUgFIBAgCIAiAEQAQAGAPAIQAiAUAWAiQAQAZACAeIABA1QgCAugMAvQgDAMAAALIACAZQAMA6AoAsIATARIAJAEQAeADAdgKIATgIQASgIAJgSQAJgSARgHIgBASIAFACQgIBdAxBPQARAZAcAKIAaAJIAkAIQAQAhABAnQABAegNAZIgsAJIkBgPIhfAHIhPAEIhHgEQhbgNhdAJQgoAEgkAKIgaAGgAFOjDQgEg0AOgzQAKgnAZgfQAMAHABANIABAJQACAcgKAbIgRArQgKAZgRAVgAn5n0QABggAegIIAHAkQADAUARAPIgBAKIg3ALQgDgZABgbg");
	this.shape.setTransform(-8.9,82.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59.6,28.2,101.4,108.4);


(lib.shape149 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AHRHlIhUgMIg+gDIhKgHIhGAJIhAAHQgTAEgSgEIhvgIQg5gGg4AGIhRALIgvgDIgxgLQgogKgoACIgEADIgQgCIALgmIAHgXQAWg3gQg6QgHgdgRgXIAggFIAvgFQAIAAAGgFIAagXIAXgeQAmg3gLhEIgPhRIAMgOIALgOQAUgiAPgmIAIgYQAIgcgLgWIAEgIIARALIAiAQIAtgCQAegQALgfIAJgfQAFgQAAgQQAAgjgBgiIABgyIADgNIAXA8IAaA6IAcAtQAQAUAVARQANAKAPAIQApASAtAIIBaAOIAqgBQAOgCANgJIANgOQAbgoARgqQAIAGgBAJQgLA7gHA7QgDAcAEAcQACATAKAPQAJAPASADQAVAAATgIIAJAEIABAJQgVAdgTAbQgSAcgHAgIgJA0QgHArAIAqQAFAbATAVIAtAGIAJAPIgQAcQgKARgHATQgIAVAPASIAZAcQAQARAFAWIAHADIADAJQgEAJgIAFQgLAHgOAAIgEAAgAG/EcIAAADIAFgEgAgtl3IABAAIgCgCgAn5mFQAAgRANghIARgtIAGAAQgBAVAKAZQAMAcAVAVIgaAFIgeAFQgMAJgHABg");
	this.shape.setTransform(-14.6,86.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.2,38.3,101.3,97.1);


(lib.shape148 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AFYHWIgpADIhHgEIg/AEIg/AEIhtgYIghgKIg2gCIhjAJIh0AJIhWgEQgGgIgQgGIADgHQgEgIgCgPIgBgqQAAgWAFgWIANguIAAgBIAHgBIAgAYQAiAaAQADIgCgzIgCglQAAhsAkhjIAahBQALghAAgaQAAgigUgqIgVgqIAAgGIAEAAIABACQAJgBAhAcQAnAgAcAAQAQAAAGgFQAEgEAAgLQAAgIgNgyIgPg0IACgEIAIgCQABAAAXAgQAWAfANAAQASAAAMgbQAIgUAAgOQAJgsgBgVQgBgdAQgmQAPgiAVgaIADAEIABAIQAAASgHAgQgHAgAAAPQAAA9AoA4QA/BXCHAAQBhAAA6hKQAmgvAGgqIACgEIAHgBIAHACIACARQAAALgJAmIgMAsIAAAGIAIgBIAMgBIADACIABAGIgOAvQgPApAAAqQAAAtAEALQAMAcAwATQg0AugNAxQgGAXAABDQAAASA3BrIAtBXQAJACAFAIIADAMQAAAOgRAIQgZAOg7AAgAGtjJIABACIABgCgAnukzIAEgJIgDAAIgBgHIABgDIgEgUQgDgZgCgIQgCgJgLgUQgJgQAAgOIACggIACAAQADAOAfAgIAfAeIgBALQAEgKALAEQgFAHgBARQgBAIgDACIACATQAAAEgNAKIgNAIIAAACQgEAIgFACIgIAAIgBABQgBAAAAgGg");
	this.shape.setTransform(-14.4,89.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.9,41.2,105.1,95.9);


(lib.shape147 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("Ak4HQQgPgNgEgBIgggEIgbgFIACgFIAAgDQAAgYAUhCQAXhKACgLIAAgCIAIgCQAIAAAHANQAFAJACAJIAThCQALgqANgYQAkhIAAg6QAAgTgJgYIgPgvQgEgTgYgZIgvgtIACgCQAKACALAHIABgCIgSgNIABgCIADgEQAZALATAMIA0AFQAhAAALgNQAGgHAAgIIgEgUIgEgUIAAgIIACgDIgBgBIAHgBQAEAAAaAsQAfArAeAAQAkAAAPhIQAMg1gEgtQgDgfAHg2IAFgtQAEgbAOgNQAGALACAUIABAkQAAAUgEAtQAAAXAJArQAKAsAJARQAaAyA2AmQA1AlAnAAQA6AAAlgcQATgOAKgRQAlgigOgmIAAgdIAAgCQACgCAGAAQAEAAAQAVQAMAMAFAAIAYgCIAVACIAAAUQgQAfgKAqQgJAoAAAfQAAANARBIQAIAcAPASQAMANAYAJQATAHAAAGIgZBBQgaBCAAAfQAAAyAhAvQAfAqAJAgIAKACQAFADAAAJIAAAGIgCADIgJABIgOgBIgmAEIgnAEIghACIgUACIg6gKQgrgKgsAAIhfAIIg6AGQghAAgugOQgsgPgmAAQgQAAhcATIhdASQgSAAgSgNgAoZjbQgDgbAEgbQAEgkACgiIAHAAQAMAbAFAeQAJAyAqAdIAAAHIgDABIgfgFQgGgCgGACIgOAFIgKABQgKgHgCgOg");
	this.shape.setTransform(-14.7,88.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68.7,41,108,95.6);


(lib.shape146 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AlBJfIgigNIgCACIgGgBIgBgFIgKgEQAFgGAHgDIALgbIAfgzQAthLAAg5QAAhHgkhEQgihBhOhTIAEgEIAKAJIACAAQAIABAYAOQAYAOAWgBIA4gEQALgHABgmIAAgBIgBgCQgIgRgHgmIgEgVQgLgigBgMIAAgQIgCgUIABgGIABgBIAFAAQAHAMAGATIASAhIAhA4QALAQA2AaQAHADASAPIAbAVIAAgEIgEgeIgEgfQABgjAOgiIAmhPQALgWAKg3QAKgvAQgSQALATABAdQABAmACAMQAEAUAAAdIgEAwQgBAYAIAaQAJATASAcQAEAHARAPQATAOALAEIAsATQAfAMAMAAQBcABAWg+QAGgUgBgXIgDgUQAAgaARgiQAPgfAUgZIACgPQADgOAHgFIA7A5QASATAAAhQAAAVgcA2QgdA4gBAnQAAAiAYAoQAkA+BIAAQAYAAATgLIAQgLQAEABABADIACAKQAAAIgKARIgNAWQgJATgEAaQgHA8AAAgIAAAvQAAAbgEATQgDANgCAgQgDAQgIAMIAAACQAAAPgPABIgqgCIiIAKIiAgKIhxAKQgWgBgxgMQgvgLgMAAIiUAGQgPACgcALIgaAMgAo1AZIgDgWQAAglAOg2QAKAUAQAuQAWAmAxAWIAAAEQAAACgGAAIgVgHQgQgHgNAAQgZAAgFAHQgLALgGACgAHsoDQgJgDgBgKIgBgMQgBgLACgLIAKg6IAFAAQAGAYgBAYIABAGIALAmQgEAJgKAEIgFABIgDgBg");
	this.shape.setTransform(-13.4,74.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70.3,12.2,113.9,124.3);


(lib.shape145 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AgbJNIgZgFIgagJIgWgBQiZAJiZgEQgagBgZgKIgGADIgHgNQALgSAPgNIAUgSQAWgXgCggIgDgrIAAgoQAEhXgPhVQgHgqgVgkQgVgjgjgYIAAgGIARgCIAaANQAQAJATAFQAYADAWgJQAZgKAJgaIADgTQABgLgCgJQgFgiANgeIAAAHIAFAAIAGATQAHARALAPQAmAvA2AjIAQhnQACgOAHgNQAVgrAggjQAOgQAJgTIAZgyIAEgCQAMANAHARQAWAyARA0QAJAZAGAaQAFAWADAVIAIA6IAIAWQAFAIAIAEQAOAHAQAEIAZgFQA5gNApgsQAWgYARgYQAjg1Aeg7QAYA/gIBCQgEAlgLAkQgKAfAEAkQAEAsAaAkQApA4BFAFQAYACAVgKIAKgIIARgYIALAEIAAAfQABALgHALIgeAqQgjAwAAA+QAAApAOAnIAMAgIgHADIhrgEQgtAFgtgGQhigGhiAIIgyAKQgIACgKAAIgQgCgAlKgLIADgBIgDgGgAHqniQgIgIgNACIgHAHQgNgVgDgcIAAgMIAEgwIAGAAQARAtAXApIAHASIAAAGIgHACg");
	this.shape.setTransform(-7.3,76.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.7,17.7,100.8,118.2);


(lib.shape144 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("ACdJwIhYAFIhQAGIgDAAIiTgJIhTAHQg6AAgTgIIgKgEIhCgDIhbgDQgCAFAAgKIAEgGIAAgDQAAgKAng7QAng8AAglQAAgXgag5QgVgugKgOIg7hDQgjgpgCgiIADAAIADgCIABACIAAAAIABABIAnAfQAoAbANAAQBHAAAXg0QAJgUAAgkIABgCIAHgBQAIAAAVAeIAcAoIBIA7IABAAQgPgpAXgqQATghA3g2QALgLAPgaIAZgqQAHgOAFgeQAEgcAFgHQAXAbALAsIAQBLIAIAWQAJAYAOAUQArA9BBAAQA3AAArgpQAWgVARgaQAQgOAIggQAJgjAKgMQAMAiACAPIABAqIgIB1QAAA1AgBNQANAgAOAaIAOAMQARAQAnAAQAhAAAXgbQAVgaAGABQAJAMACAWIABAhQAAAsggBKQghBMgZAAIgEAAIgCAAQgSAIgoAAIg6gBIgHACIhDADgAimkqQAIgqAAgbIgEgnIgEgoIACgGIAFAAIAJAkQAFAaAHAPIAXAsQAEAGAAAbIgBAoQgDAYgOALQglgmAAglgAIgklIAAgJQgBgOgnAEIgBgBIgCgIIAMgmIgGgTIgGgTIgDgTQgDgNAAgEIAAgGIACgBIAGAAIArA/QAQAcAAAcQAAAVgEAKQAEACgKAAQgHAAgBgFgAnrpFQABglAfgUIAPAyQgVACgRAMg");
	this.shape.setTransform(-7.7,71.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.9,8,112.6,127.9);


(lib.shape143 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AgyJoIgugMQg/gMhAgFIg5gDIgmAHQgxAPg1AAQgcAAgYgQIAHgMQgXgygEg3QgDgrgFgrQgFgngHgnQgKgwgHg0IANAEIAGAKIAkAlQAYgYARggIANgeQANguAZgoQATAwAYAsQANAVAXAJIAyAEQBKgQAxg6QASgVAOgZQA7hiAehxIAJABIAAAFIgEAsQgCAoAAAmQABAZAFAZQAGAcAPAbIAQAYQATAcAeAOQARAHASAAIATAAQAbgEAUgUIBAhAQAOgOAJgVIAZg7IAHAMQAEANABANQACApgGAnIgSBpQgLBEAhA7IAXAhIAPAQIAlAkIAZgxIAPARIASAiIAIAoQAHAdgBAdIgFAnIgGAZIhQACIAPgGIggAGIhCgGQhSgOhOANIhIAJIgjAHQgRAEgOAAQgSAAgSgFgAiNjRIgIgcQgHgagUgVIgOgTQgZgoALguIARhoIAHAAQAXA4AUA7QAMAjACAlQADA5gDA2IgMABgAAgjRIgBgDIAAgPQABgVAHgmIAKg5QAHAAAIAMQAHAKAAAGQAABtgeAHgAHekXIgBgBIAAgIQgBgGAJgTIAKgaQAGgSAEgdQAUAIABAjIAEA8QgDAGgYAAgAnCn5IgBgMQgDgOgoAEIgBAAIgCgHIALgVIAMgVQAFgeABgNIAHgBIAMAuIAMAxIAAAaQgCAEgEAAQgHgDAAgHgAnOofIgBgEIgDAEIAEAAg");
	this.shape.setTransform(-8.3,74.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.3,12.5,106.1,124.3);


(lib.shape142 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AEOJZIhTgEIhTAGIgaACIiegTIgpgCIjLAHIgkgFIg0gNQgXgJgYgCIgEgGQgEgHAAgIQAAgZAEgZIALg6QAHgigEghQgCgSgJgNIgbgrQgLgTgBgTIAIgCIAHAHIAmAkQAjAcArAUQAQgbAEgeQAEgggEgjQgGgqAOgnIAGAKQAGAKADALQADAOAIANIAaAiQAPASAWAHQAoANAngMQAPgFAOgKQAggXAXgiQAbgmAPgtIAehQQAIgTANgOIgEAuIgBAhQgEAlAPAgQAZAwAzAXQAeANAiAGQAigDAcgSIAcgYQAcgbATggIAohGIgBALIgFAdIgGAlIgKBIQgPB9BEBqQATgzArgkQANgMATgEIgDAUQgOArAJAsIANA8QALAxgCAzIgIAFIgnAIIg/AFgAAUhcIgCgIQAAgeAUhMIAZhfIACAEIACADIADgJIAHgKIACACIAAgGIAGgWQAGAbAAAgQAAAcgGAZIACAIQAAAbgYAuIgmBAgAHHiwQAAgUALguQAPg9AWgSQAJAPADAmQADAiAQATIgUALIgaAPIgLAOQgHAKgHACgAiVkXQgdgfgUglIgcgzQgLgUAAgYIgIgEIAWgGIAGgQIAEgSQAIg/Amg3QAFgGAJgDQgGAcgCAdQgBAMADAMIAUBNQAJAfgFAgQgIA+AOA7IgEAAQgIAAgIgIgAoVl0IACgKIAJgUIAuhFIAKgSQADgIAAgIQgBgggEgfIAHgEIgHgLIAGgEIgBgFIAPAVQAHALAEAMQAIAggGAgQgJArgRAnQgkAGgZAZgAncmhIAFgBIABgFg");
	this.shape.setTransform(-11,75.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64.5,14.2,107,123);


(lib.shape141 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AFmI9Qh3gXh5ACIhpgGIhiAAIhXgDIhKAIQhLAJhIgTIAAgFIAJAAQgvhEgHhSIgJhYIgMhTIAOAEQAgASAgAVQAQALAGATQAXgiATgmQAIgRAFgSQAMgtgEgwQgDgrAIgpIAAAMIAHgCIAAAiIAGArQAHAiAUAdQAQAXAXAUQAOAMASAEIAtACIAqgCQAOgCAMgLQASgSAOgXQASgbAMgbQAGgSAFgUIAjhyIgLBbQgGAnAFAmIAHAkQAIAcAYATIAYARQASAKAUgBQAdgEAXgNIANgJQBCgzAwhGQATgbAOgdQAPgeAdgQIABAPIgEAfQgKBgADBiIACA6QACAtAVAlQAHALANAFQATAIASgLIAUgPIAIAFIgDAjIgDAtQAAAQAEAQQAJAqAZAkIgHALIgcACIgggKIgXAHIgtAKgAFrAUIAEABIAAgGgAA5iOIAAgJIACgVQACgfALgbIAjhZQANgkAKgkIAPgsIgEA/IAMBOQADAYgIAWQgbBDg3AtgAiRlYQgsheAAg8IABgDIAJgCIAVARIAUARQAFgFAGgUIALgdIAIgdQAGgUAGgCQADAJAHAoQAIAqAAAPQAAAWgIA1QgIA2AAAVQAAAcAJAZQALAiAFAfQgCAEgHAAQgFgPg+iFgAoBlLQARgZAUgWIAaghQASgbALgfIALgiIACAyIgDAwQgDAhAEAfIgEAFIgEADIgHABQgNgPgTgBIgUAFQgXAKgQAVQgDgLAGgIgAmvloIACgEIgEAAgAm+lzIgEgEIgEADIAIABg");
	this.shape.setTransform(-15.1,79);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.9,21.5,103.7,115);


(lib.shape140 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AAdI4QgdgSgjgEQg7gEg6ADQggABgdAKIgfAGIgfgBQgWgDgTgIQgcgOghAHIgpAJIgaABIABgHIANgMIgBgLIAHgoIAMgwQAPg+gNg/IAHgCQANAJAQADQAnAAATgkQAOgbACgeQAEg6gBg5IAKgEQAEAtAOAqQAHAVALAUQAHAMAMAJQAjAdAtgGQAggDAagTQAWgRANgYQAWgrAKgyIAWhjIAMACQgEAqAHAoQAIAxAfAqQANARARALQAdATAlgDQAwgCAhgkIAbgfQAngxAWg5QATgzAmgiIABAZIgCBRQgBAjAAAjQAAAgAHAgQAUBYAmBQIAkgpIAHACQAEBgAnBVIAMAEIAAAPIgDAGIhFAIIgwACIijgQQgtgEgsALIhDATQgJACgKAAQgYAAgVgNgAAvh5QgChEAjg6IAYglQAXgiANgoQAGAiACAjQACAWgCAYQgCAYgNAUIgMAPIhEBFgAhcj7IgFgVQgDgYgKgXIgehFQgVg5ADg8IAIABIAcAqIAfh2IAUApQAEAKABAMQAFAygLAxQgSBaAMBbIgFADgAoTkbQARg5AhgxQAMgSAJgUIAHgVIAMAOQAMArgIAuQgFAhgRAbIgCABIgSgRIgdAKIgLAJgAnCmqIAAAAIAAAAg");
	this.shape.setTransform(-15.8,79.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69.1,21.7,106.6,116.3);


(lib.shape139 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AAOLlIhXgQIhoAEIgZAHIgaAEQgkgEgegRIg4APIgGgDIAAgIQAng7AVhFQAJgcAGgcQAFgWAAgWQADhUgGhSIAJgCIAIAOQAHANAEAPQAHAUAMAQQALAPAQALQALAHAPABIASgBQAagFASgUQBDhMAQhkIAKhEQADgUgFgVQgKgkAGggIAKASIAnBnQAJAVATANIASABQAMgFABgPIAGgBIAFBAIAEAXQAHAdAMAcQAIASATALIAYAKIAlACQAagFAVgMQAjgVATgkQAVgnAMgsQAMgyAZguIAMABQACAOgFAOIgFAVQgDAKAAALQAAAPAEAPQAOA0AvAYQALAGALAHQgRAvgPAwQgHATACAUIAGAiQAFAZAUAMQAPAKASgIIgSA2QgMArAEAsQABAUAOAPIAPABIAGAIQAEAHgCAJIgCAFQgSAIgWADIhKADIgoABIg/gIIgtgCIhGACIhIAJgAhJhRQgLgmgKgNQgdgpgUg8IACAAIAGgDIAFAIQADAHAQAAQAQAAABgGQACgIAMgEQACAKgBARIgBAXQAAAaAQA0QARA5ABARQAAADgEACQgMgOgLgjgAnxgwIgBgNQAFhGAYhAIAHAsQAFAbAWASIghAdQgOANgFASgAkBqNIgcgTIgGAKIgOAAQgCgTAJgNQARgbAVgYIAJAAIAHBDQACAKgHAIIgGAHg");
	this.shape.setTransform(-17.5,61.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.4,-13,99.9,149.3);


(lib.shape138 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("Al1KeIAEgBIgYgDIAIgJIAXgYIAKgKQAWggAEgmQAGgrAAgsIgBhIQAAgUgFgSQgMg2gQg2IAHgBQALAPAQAKQAVANAYgEQAZgDAUgQIAQgNQAhgdANgqQAKgeADghQACgdgHgdIgIglIAJAAIA5AqQAJAGAKADIASgCQANgHAHgNQAEgIABgNQADgdAAgeQAAgJAFgKQAcA4ATA7QAMAfAVAZQAXAbAhAJQAUA3AZA1QAPAhAHAmIAaiVIAGgQQANgdAXgVQAtgpA6gWIABAPQABAjAFAkQAEAhAVAZIAcAgIAyAwQAMALAIAOQAJAQABAPIADA6IgBALIgGAiQgHAkgEAlQgJBZAlBTIgJAQIhYAHIhVgEQh0gKh1AIIiQgHIhEgDIg3AEIhLAPIgfAFQgzgEgdgrgAkjErIAAAAIgBAAgAoIgUQgBgHACgGQAVgwgFg1IgEgyIAGAAIAOAgQAQAoApARQgaADgTAUIgKAOQgLAWgPASgAHclHIAGghIgLg8QASABAJAQIAMAWIAMAfIgjAdgAk5p1IgKgFIgVgDIgGAEIgCgNIAAhGQAWAlAcAhQAIAHgDANIgHABg");
	this.shape.setTransform(-13.8,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.9,-6.2,104.4,143.5);


(lib.shape137 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AE7MkIgvgEIhJgHIgpADIgnADIgmAEQg0AAghgKQgagKgHAAIgqgJIgBAAIh1AKIgpALQgLAAgWgOQgWgNgIgBIguABQgKAAgUgMIgBABIgeAIIgIgBIgCgEIAGgIIAAgBIAXgiQAWggAAgeQAAgYgIgZQgKgagRgWIAAgGIgBgCIAHgCQAKAAANAQIARAVQATgaAMggQAOgiAAgZQAAgdgUglIghg3IAVAUIACgBQA3AgAXAWQAhAgAIAoQAZggAEgPQADgJAAggIgCgyQgDgagHgXIAAgeQAyANAVgkQAMgVAAgfQAAgYgSgwIgSgxQAAgGAEAAIAEgBQAIAIAdAyQAhAuAjAAQATAAAFgWQAGgbAHgEQAIAQAJAuQAJAnAOAVQAYgYAMgeQAKgZAFgjIABgCIAFgEQAoA9ATBjQAeCTAEAPQAkhVAZgsQAshPBGgxIAGgBIACABIACAAQAAAzApBPIAxBgIARgSIAhgmQAQAgADANIABAmQAAAogQBHQgQBHAAAuQAAAoAPA4IAEADQAFAEABAFIgDACIADAKIgBACIgIACIgHgBIgFgDIAAgIIgWgCQgaAAggAJIgmAJIgFAAQgJAFgPABQgegCgGABgAE5MkIACAAIAJABgAoNECQgDgXANgSIAdgmIANgTQAVgiABgoQAFAcgJAaQgFANgBAOQgDAoAMAnIgJAFQgegJgcATgAHSqyIgJgKIgRABQgKAAgGgMQgLgZAAgTIAEgxIAEAAQgDAVAaAnIApA7IgGAFQgGgBgHgJg");
	this.shape.setTransform(-15.3,55.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68,-24.6,105.4,161);


(lib.shape136 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("ADnMBIhugHIghAIIg5AFQgWgCgUgMQgLgFgMgCQgWgHgXAAIh4AIIgWAFIgVAJIgLAGIiigPIgdACIgJgEIAGgFQgBgRAJgQIAohFQAMgVAHgXQAIgXgEgZQgOhTg3g+QgfgkgSgsIgWg0QgKgYAMgWIAMAgIAIARIAbAiIAZAXIBmBRQAmAcARAsQAdgnAXgsIAUgpIAIgYQAJgogIgoIgFgEIgEgRIAIgCIANAJIALAFQAMgBAFgJIAFgKQAMgagJgcIgZhNIgDgPIAGgCIAWAjQAJANANAHQAkAWAngSIANgIIAIgKQAGgNADgOQAFgaAUgRIAEAOQACAOAAAPQABAZAHAYQAFASAOAKQAYASAeAHIA9AIIAAAIIgGAWQgEAQgBARQgEA3AQA1QAWBGAOBIIAAiRQABhaAshMQALgTANgRQAqg0A9gcIAFACIAAAJQAAAKgEAJQgLAYgEAaQgMBNAmBFIAjA+QAkA/AXBFQAWgoAigeIAHACIgBAVIgNA1QgIAhgDAiQgGBRACBOIAOAGIgGAFQgNAIgMAEIhxgJQgGAJgKACIgcAIgAG6iZIAzA1QgBAIgJAFIgbAPgAi3oAIgNgsQgFgOADgQIAGAAQASAZAQAbQAFAJADALIgGAvQgUgTgHgagAA3ncQgEgRAGgRQAKgZgGgaIAGgBIAOAVQAHANAMAKIAOAIIAAAJIgvAaIgFACQgEAAgDgDgAHKqaIgPgJQgUAAgMAIQgOAJgDABQgIgGgDgNIgBgTIAEgnQAFgnALgLIAJAfQAEARAJAPQAFAKAVAWIAZAeQAAAEgGAAg");
	this.shape.setTransform(-13,59);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.2,-19.5,104.4,157.1);


(lib.shape135 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AkOJ7IgPgWQgMgRgUgEQgogCgnAPIghAGIgeADIgCgHQAYgsgCgxQgCgwgWgoQgZgvgVgxQgOgggFglIAAgeIACgtQABgaAMgSIAJAvQAIApAXAkIAZAiQAnAtAvAkQASAPAMARIAIgpQALgtARgqQAWg4APg6IAGgiQADgZgDgXQgFgdgJgbIAOgDIATgIIAIgIQAEgLAAgJQABgPgDgOQgFgWgIgVQgMgcgPgZQghg2glg1QALgFAIAHQAPALALAQIBFBcIAKALIAOgSIgWh5IAFgDQAJACAGAKQAJAPAEARIAVBFQAKAeASAZIATAVIANAIIAiAFQAuAAAOgtQAKgoAEgqIABAEIABgBIAEAkQAEAzAHAzQAFAgANAeQANAhAYAbIAaAUQAQAKAQgGIACAEIgEAHQgRAWgKAWQgEAKAAALQgBAaANAXQAkBAArA8IgEgxQgDgmACgmQACgaAGgZQAGgZALgXQAKgUAOgRQAyg8Azg3IABgHIAAgHQACgKAFgJQAHgKALgFIABAGIgCARIgKAtQgKApAEApQAGA3AVAzQALAZAPAXQAgAzAbA1QAYAvAAAzIARgZIAKgfIATgBQAGBdgUBcIgHAeIgKAcIgMgCIgIgDQgwgPguAOIg0ANIgVgGIgfAEIhngFIg5ABIgggBIgugGIhJgTIgzgCQg8AEg6ANQgfAIgbAQgAH+G6QAGAEgFgGgAGNhbQgBgEABgFIAEgZQAGgfgJgbIAGgCIA/BHQgNARgUgFIgLABIgVAKgAnpk5QgBgdALgZIAPgiIgBARQAIAAACANIAGAcIAGAZQgEAPgOAFIgLADIgFACQgLgGgBgOgAnak+IAAAAIgBgCIABACgAjWn9IgOgLQgJgMgDgPQgEgWACgWQABgPAKgMIANAwQANAFAEALIABANIgFAigAATolIgBgbIABgdIAFgnQAKAEAEAQQAGAWAFAGQAEAGAPAIIAXANQAGAEAFAIIAKAOQAAAJgGADIgLgNQgGgGgIAAQgpAAgDAJIgBAKQgCAGgGAEQgHgJgCgTgAAfpaIABAAIgBAAg");
	this.shape.setTransform(-12.4,73.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.4,8.6,106,129);


(lib.shape134 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AkXLEIAAgNIgwgFQhPAFgcAJIgXAIIgRAEIgNgCIgBgCIgBgHIAAgDQgLgPgIgvQgJgvAAgiQAAgLALgqIANgvIANgzIALgwQAEAIAIAUIAOAZIAfApQAFggAcg4QAhhCAXgVQAiggAbg6QAbg5AAgnQgBgRgHgQQgMgYgZAAQgFAAgFAEIgRAIIgDgCIgBgHQAAgEAIgIQALgJAFgOQAFgQABgPQgBgXgIgYIgXgyIABgCIAFgEIAzAmQAnAdAHAOIACAAIgeh3IAAgjQAKABAFAOIAMAXIAXAcQAaAXAlAAQA0AAAXgXIAOgPQAGgGAIAAIgCAFQACAVgEAlQAAAtAZAmQAiA0BFgIIACABIABAHQgBAEgVAYQgXAZgDAYIgJBJQAAAlAbA4QAYAwAfAnQAbAiANA3QAEAQACAgIAAAlIgCBMIgEAXQAPgbAMgsQAPg6AAgxQAAgWgLgzQgLg0AAgUQAAgtAegqQANgRA0gzQAqgqARghQAYgxgIg6QAQgFABARIgBAZQACAJAQATQAPATALAGQAmAWATAgQAOAYADAjIgGAEIgLgJIgKgFQg3AAgIBAQgEAhAGAkIAAAFQAKAZAWAfIA2BNQAUAkANAsQAMArAAAlQAAAVgEAaQgFAegIAOIAAAGIAAAFIgCADIgWAAQgeAAgRgIIgSgIQhCAAgVANQgTANgcAAQgaAAgdgLQgcgLgcAAIhNALIhJALQgOAAgngQQgqgQhJAAIglAHIgnAJQgOADgVAKIgVAJQgMAAgDgUgAoMhdIgMgfQAAgdAGgcQAHgfAMgLQAJAtAXAdIAVAVQABAGgLALIgTASIgHAOIgLASQgGgFgNgbgAAJkkQADgOAIgNQAUgbAYgVIAbgWQAsgjAgguQAJgQACgSQACgZASgMIADADQADAUgFASQgOA4gZA3QgTAqgtAPQgUAIgUANQgVAQgYAJIgBABgAj7mEQAAgMgBgLQgCgMgEgLQgJgeALgeIAXAvIAkAqIgcAVIgOAQQgOgDACgRgAgandIgBgRQAAg3AQg0IAJABQAEAeAFAfQAGAlgIAmIgMBLIgIAAgAHYoQIgCgNIAFgkIADglIgJgbIgMghQgFgKgNgrIADAAQAHANAWAiQATAdAHAVQAKAaAABEQABAGgHADIgSABg");
	this.shape.setTransform(-13.9,65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.7,-7.8,107.5,145.7);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ31();
	this.instance.setTransform(1.2,1.3,0.415,0.415);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.46},9,cjs.Ease.get(-1)).to({scaleX:0.51},10,cjs.Ease.get(1)).to({scaleX:0.47},10,cjs.Ease.get(-1)).to({scaleX:0.42},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-153.5,-14.5,307.1,29.1);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF00").s().p("ABCIwIAAjSIntAAIAAh+IHCsPIEzAAIAAKhIBiAAIAADsIhiAAIAADSgAhsB/IDBAAIAAizIAPi/IgDAAg");
	this.shape.setTransform(117.3,56.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFF00").s().p("AlGI5QhRgjg/g/Qg+g/gjhRQgkhVAAhcQAAhbAkhSQAjhSA+g/QA/g+BRgjQBVgjBbgBQBWABBOAfIAIgKIAmglQAWgXAfABQAggBAWAXIAwAxIBihiQALgLAQAAQAPAAAMALQALALgBAQQABAPgLAMIhjBhIAyAxQAVAWABAgQgBAegVAXIgnAlIgJAIQAgBOAABVQAABcgkBVQgiBRg/A/Qg/A/hRAjQhSAjhdAAQhbAAhVgjgAkLh+Qg3AXgpAqQgqAqgXA0QgYA4AAA9QAAARALAKQALAMAQAAQAQAAALgMQALgKAAgRQAAgtARgqQASgpAggdQAfggApgRQAqgSAtAAQAQAAALgLQALgLAAgQQAAgPgLgMQgLgLgQABQg9AAg4AXgAHQigIgmgmQgMgLAAgQQAAgPAMgLQAKgLARAAQAPAAALALIAmAmQALAKAAARQAAAPgLALQgMALgPAAQgPAAgLgLgAHrksQgQABgLgLQgLgLAAgQQAAgQALgLQALgLAQAAIBLAAQAQAAALALQALALAAAQQAAAQgLALQgLALgQgBgAGrmpQgLgLAAgPQAAgQALgLIBLhLQALgLAQAAQAQAAALALQALALAAAQQAAAPgLALIhLBLQgLALgQAAQgQAAgLgLgADHmpIgmglQgLgLAAgQQAAgQALgLQALgLAQABQAPgBALALIAmAmQAMALAAAQQAAAPgMALQgLALgQAAQgPAAgLgLgAE5nPQgLgLAAgQIAAhLQAAgPALgMQALgLAQAAQAPAAAMALQALAMgBAPIAABLQABAQgLALQgMALgPAAQgQAAgLgLg");
	this.shape_1.setTransform(17.8,52.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Слой 3
	this.instance = new lib.Символ34();
	this.instance.setTransform(62.5,61.8);
	this.instance.alpha = 0.262;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.2,-56.9,237.3,237.3);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ28();
	this.instance.filters = [new cjs.BlurFilter(24, 24, 1)];
	this.instance.cache(-97,-38,194,76);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-107,-48.1,218,100);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ25();
	this.instance.alpha = 0.449;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.367},4,cjs.Ease.get(-1)).to({alpha:0.262},5,cjs.Ease.get(1)).to({alpha:0.355},5,cjs.Ease.get(-1)).to({alpha:0.449},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.8,-76.5,167.6,153);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ23();
	this.instance.alpha = 0.27;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.348},4,cjs.Ease.get(-1)).to({alpha:0.449},5,cjs.Ease.get(1)).to({alpha:0.359},5,cjs.Ease.get(-1)).to({alpha:0.27},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49.2,-76.9,98.5,153.8);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ21();
	this.instance.alpha = 0.449;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.371},4,cjs.Ease.get(-1)).to({alpha:0.27},5,cjs.Ease.get(1)).to({alpha:0.359},5,cjs.Ease.get(-1)).to({alpha:0.449},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.4,-45.1,48.8,90.4);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ19();
	this.instance.alpha = 0.27;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.348},4,cjs.Ease.get(-1)).to({alpha:0.449},5,cjs.Ease.get(1)).to({alpha:0.359},5,cjs.Ease.get(-1)).to({alpha:0.27},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.9,-133.9,81.8,267.9);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ17();
	this.instance.alpha = 0.449;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.371},4,cjs.Ease.get(-1)).to({alpha:0.27},5,cjs.Ease.get(0.88)).to({alpha:0.359},5,cjs.Ease.get(-1)).to({alpha:0.449},5,cjs.Ease.get(0.88)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-41.6,-133,83.2,266);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ15();
	this.instance.alpha = 0.27;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.348},4,cjs.Ease.get(-1)).to({alpha:0.449},5,cjs.Ease.get(1)).to({alpha:0.359},5,cjs.Ease.get(-1)).to({alpha:0.27},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.1,-126.3,80.2,252.7);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ26();

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("ArBL9IgHgDIgDgEIAAgDIAAgEIADgEIACgBIAAgDQABgHgDgFIgDgFQgBgDACgDIADgHIAAgDQgMg7gCg/IgBgpQgBgZgCgRQgDgTgIgeIgMgxQgJgogDhKQgGiWgDjqQgBgmgCgPQgCgdgIgWIgLgcIgNgcQgTgxgGhMQgGhhANhjQAEgZANgBIAGgBIAAAHIABgBQAGgCAPgBQAPgFACgSQACgGgDgYQgDgWAKgJQAEgDANgDIAwgLQgIgjATgeIAEAFQAcgCAOAEQAKADAIAIQAIAIABAKIAAAMQAAAHACAFQAFAIARACQAfAFAdgMQgBgFgFgFIgHgKQgKgMAGgJQAFgHANgBQAfgGAQAGQAMADAIAKQAIAKgBAMIgDAQQgCAJAFAFQAFADAMgCIAugIQgLgvAWgNQALgHAYADQAWACAJAHQAMAKAFAdQAMBEASBFQAJAkANANQARAUAkAHQAjAIARgQQAKgKACgTQACgMgBgSIgCggQgBgnATgTIAcgSQAQgLACgNQAAgEgCgOQgBgLAEgGQAEgGAKgBQAJABAHAGQAJAJACAWQAFAEAGgDQAHgEABgGIABgNQAAgJABgEQACgNAQgBQAPgBAFALQADAGABALQABALADAGQAJAOATgDQAKgBATgLQgIgjATgJQAHgCAJADQAIAFAFAIQAFAJAAAZIgBAIIAOgBIAFgBQAHgCAAgOIgBgTQAAgHACgEQADgGAMgDIATgGIgBgBIAKAAQAGAAADACQAIADAAAJQgBAGgFAJIgBAMQgBAIAEAEQADAEAGACIALABQAKACAGAHQABgDgCgLQgDgKABgXQAAgFABgCQADgEAGAAIALACIASACQAKABAGAFQAFAHAAAOIAAAUIAAADIAngDIABghIgBgFIgEgFIgBgGIABgGQABgDADgCQAFgBABgBQAIgBAFAHIACACIAFACQAFABADAEQABACAAAHIABAlIAogDIgBgEIgCgDIgBgFIgBgDIgBgEIgDgEIgBgDIAAgEIACgEIADgEIAAgDIAAgEIACgEIADgDIAAgFIAAgDIACgEIADgDIAFAAIAAgBIAGADIADAEIABADIAAADIAAABIAKACIAGACIAYACIAGADIADAEIABADIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIACADIACAEIABAEIAAADIAAADIAEAAIABgCIAFgBIATgCIAGgCIAJgDIABgEIAAgDIAAgFIAAgDIAAgEIAAgEIAAgDIAAgEIAAgEIABgEIADgCIABgBIAFgBIAYgDIAGgDIAFAAIAGADIADAEIABADIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAAEIACACIAlgBIAGgEIAAgEIgDgDIgCgEIAAgEIAAgDIAAgFIAAgDIAAgEIAAgDIAAgFIAAgDIACgEIADgDIAFgBIAeAAIAGADIADAEIABADIAAAEIAAAEIAAAEIACADIADAEIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAACIATgBIAGgCIAYgDIAGgEIAAgDIAAgFIAAgDIAAgEIAAgEIAAgDIAAgEIAAgEIABgEIADgCIABgBIAGgDIAEgDIAFgBIAFAAIAGADIAEAEIACADIADAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIACADIACAEIABAEIAAADIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIACAFIADADIABAEIADAEIABADIACAEIACAEIABAEIACACIADABIAGADIADAEIABADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIgBAEIgCAEIgCAEIAAADIAAAEIAAAEIAAADIgBAFIgCADIgBAEIgBADIAAAEIAAAEIAAAEIAAAEIgBADIgDAEIgBAEIAAADIAAAFIAAADIAAAEIgDADIgBAEIgBAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIgBADIgCAEIgCADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIgBADIgCAEIgCADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIgBADIgCAFIgBADIgBAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIgBAEIgCADIgCAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAACIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIgDADIgCAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAEIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIgBAEIgCAEIgCAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIgBADIgCAEIgBAEIgBADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIgBAEIgCADIgBAFIgBADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIgBADIgCAEIgCAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIACADIACAEIABAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIAAADIAAAEIAAAEIAAADIAAAFIAAADIAAAEIAAADIAAAFIAAADIAAAEIAAAEIgBADIgDAEIgGADIgGACIgCAEIgCADIgFABI2yAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.shape}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ24();

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("AGRL+IgEgDIgBgFIgCgCIgHACIstAAIAAAAIgCAAQgFAAgCgEIgBgBIAAgDIAAgGQAAgTADgjQADgmAAgRQAAgXgEgeIgHg1QgNhfAEhvQAEhYAPh1QAGgqgBgUQAAgSgEgXIgHgoQgShkgChmQgEgFADgOQASg5gSgxQgCgIgMgaQgMgYgEgQQgFgXAFgSQACgJALgUQAKgTACgMIADgVQACgLAIgEIAJgBQAHAAADgCQAIgEABgMIAAgUQgBgMAEgPIAIgZQAHgegCglQgCgZALgFQAGgBAGADQAGADACAHQAEAIgDAQQgDAMAFAEQAEACAHgBIA4gEQgIgQAFgTQAEgSAOgLIABABQAHABAUgBQAQgBAJADQAPAIADAUQACAJgCAZIAtgBQACgHgBgJIgCgPQgCgVANgGQAFgBAHABIABAAQADgDAEABIAAgBIAAAAIATAAIAHABIAMAAQAQgBADABQAHAEAAAIQAAAEgCADIABAHIAJAmIABADIABgCIAEgEIACgCIAFAAIAAgBIA3AAIAAgSIgCgGIgBgKIAAgPIABgHQADgGAFACIAAgBQAEAAADADIAGADIANgBIAYgEIACgBIAAAAIAKAAQAGAAAEABQAGAEgBAHIgEAJQgBAFAAAIIAAAbIAjAAQABgEgBgCIgCgFIgBgFIABgcQAAgGABgCIACgBQACgEAEgBIADAAIAAgBIBKADQAFAAADACQAHADgBAIQAAAEgDAIIAAALIgBAOIgBAGIA3AAIgBgGQgCgLAAgGIAAgIIgCgFIgBgMIABgEQADgHAGABIABgBIABAAQACgDAFgBIACAAQAVACAaAAIAJAAQAFABACAEQABACAAAGIAAAOIgCAJIAAAZIBMAAIADgEIABgFQAAgJgBgEIgEgHQgCgGAGgEQAEgCAFAAIAVgDIABgBIAdgBQAIAAAFAEIACAAQAGANAAAUQAAALgDAWQgWDDgEETQgCCdgBE5QgCBwgLA8IgJAnIgHAoQgFAiABBDIgBB7QgBAJgEAIIgEAFIAAABIgBAFIgCADIgHACIgGgCg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.shape}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ16();

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF00FF").s().p("AksTuIgDABIgGgDIgEgEIAAgDIAAgDQgCgFACgEIAAgDIAAgEIAAgEIAAgEIAAgDIAAgEIAEgEIAGgBIAAgBIABAAIABgDQADgFAAgIIAAhoQAAgMgCgGIgDgGIgBgJIABgYIAAgFIAAgEIgBhJQAAgKACgFQADgLALgJIAGgHIAEhOQAGiQAKikQAKilABjoQAAjnAHh8QABgbgJgJQgLgLgdAFIhUANQgJACgIgDQgIgEACgHIAFgCQgEgEgBgDQAAgEAEgEQADgEAGgCIAJgEQAGgCAHgIIALgMIAZgSIAOgGIAOgIIAYgRIAXgQIADgCIAQgWIAAgEQAAgOAEgEQADgFAKgBIAEgGQgDgKAHgOIAIgOQADgIAAgGIgEgOIgFgUQgCgGAAgHQAAgIADgJQAEgHADgDIAPgMIgDgfQgGhNAJhRQg4ALg6gCIgEABIgFgBIgHgBIAEgCQgEgDABgFQAAgDAHgGIAOgPQAJgKAHgEQAKgGAVgJQAMgHARgUIAVgbIAdgiIAagbQAPgQAJgNIAyhPIARgdIAPgWQAIgMAEgKIAFgLQgBgGAAgLIAAhjQAAgSAKABIAAgBQAGABACAMIAJAzQAHAFADAJQAEAIgDAJIgFARQAAAFAEAKQABAHgBAQQABAPALAVQANAXAjAsIA4BGQAOAQAJAOIAPAYQAJAPAIAIQARAUAxAaQAdAPASAPIAIAAQAHAAADACQADACAAAEQABAEgCADIgDACIABAAQADAGAAADQAAAEgFADQgEACgFgBQgEgBgGgFIgGADIgHADIgKABIgiACQgKAAgFADIgEADQgEACgJgEIgFgCIgLCnQgBATACAJIACAGIACgBIABAHIAEALIAAALQALA4AZA1QAFALAFAIIALAOQAKAKAYAQQAoAbAhAjIACABQAOAGAJAJQAFAGABAIQAAAKgIABQgFABgJgIIgFgEIgFABIhmAGQgCBVgYBWQgDALgFADQgDACgGAAIgJABQgRAEgBAhQgBA2ABAdQACAvAIAkIAOA1QAJAhACAUQAEAZgCAkIgCA9QgBAjAIBiQAODGgTDCQACAEABAHIADAQIABAZIAABQQAAAXABALIADASIABAYIABAYIADAYQACARAAARQAAAegDAPQgDAMgGAGIABACIgBADIgDAEIgGADIoKACIgGADIgCgBg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.shape}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ18();

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF00FF").s().p("AE3UxQgFgBgCgEIAAAAIp0AAIgHgDIgDgDIAAgEIAAgEIAAgEIAAgDIAAgEIAAgEIACgCIAAgIQANg5AFgdQACgNAAgJIgCgMQgCgOACgZQACgcgBgMIgEgdQgDgRACgLQACgLANgYQAIgQADgMIAAgHIADgzIADgzQABgTgCgyQgCgrABgZQAAgGACgEIABgBQALiugEizQAAgJABgEIABgBIgBhLIAEg6QADgigCgYQgBgJACgEQABgEACgCIgDhIQgCg8ABgfIAEgvIAFgwQADgiAAgiQAAgIABgDIABgBIgHhWIgUAAQgUACgoABIgNAAQgIAAgCgDQgDgBgGABIgGABIgEABIgLACQgIAAgEgDQgHgGADgFQACgEAKgDQAQgEAMgIIAAgBIADgDIAUgOIAAgBIAEgDIAnglQAXgYANgKIAIgHIAEgGIgBgLIgBgKQAAgGACgDQAEgJAMgEQACgGAHgIIAKgNQAFgLAAgYIAAgrQAAgHABgDQACgEADAAIABgFQADgKAAgWIABi8QgggBguADIgiABQgIABgEgDQgDgDAAgEQAAgFADgDQAEgEAIgCIAugiQAagSAOgMQAKgIAYgaIAxg0QAggiAQgYQAJgNAQghIBAiFIgCgCIgBgDIAAgJIABgCIAAgBIgBgOIADg/QAAgGABgDQADgFAGAAQAFAAABAFIACALIADAcIAFAxQABAEgBAEIgCAHIgBAMIgBAHIA3BiQAhA4AgAnQAgAnBDBAQAUAVAPAKIAeARQATALAKAJQANAMgGAIQgCACgDABIgBABIgIACIgfABQgTAAgLACIgRAEQgKABgHgBIgDgBIgBAEQgGAmADBFQAEBMgEAgQAEgBADACQADACABAEQABAFgDAJIgHAPIAAAcQAAARAFALQAGgDAHADQAHADADAGQAFAKgBASQAEgCAFADQAEACACAFQADAHgEALQgFAKABAEQACAFAFADQAfAcA6AqQAYASASAIIAOAGQAIAFAAAHQABAEgDADQgCADgEABIgBAAQgEABgEgCIgJgCIgHAAQguAAhCgCIgFgBIgBADIABAPIgBAGIgDAEIAAABIgCAeIgFBCQgBAYAEA7QAHAEAAALQAAANgKAGQgNAJgegDQgJCcACBQQABAeADASQAEAaAMASIALAQQAIAKADAHQAJARACAlIATHbQACAzACAUQADAoAHAeIAMAwQAHAdACATQADAVAAAmQgBAqACASIAHA2QAFAhgCAVQgBAIgDAFQgDAGgFAAIgCgBg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.shape}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ22();

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF00FF").s().p("AgXHDQgIgBgQgEIgYgGIgSgDQgJgCgGgEQgNgKgBgYIgCgoQgCgKgTgjQgPgaAFgSIAGgOQADgIgDgGQgBgDgLgJQgJgHgCgLQgDgLADgKQgHgEgMACIgUAGQgLAEgKgCQgMgDgCgJQgDgKAKgJQAGgFAPgIQAbgQAVgnQAagyAJhAQAGg0gDhHIhGgCQgOAAgBgIQgBgGALgFQAbgOAegZQASgPAgggQAXgWALgNQAtg2AJhGIACgWIAEgVIAEAAQANASANAjQAQAqAGAMQAOAbAiAqQAaAfANAOQAXAZAVAQQAKAHACAGQACAJgJAHQgHAGgLABIgVABQgLAAgGAGQABBGAGBFQABAWAIAMIAIAJQAFAFACAEQAFAIAAARQAAATABAGQAFASAYAPIApAaQAJAHgDAGQgBAFgJACQgmAKgoADQgDAJABAMIADAWQACAMgDAKQgEALgJAEQgJADgPgEQgTgFgHgFQgGgFgDgGIgBgEQgBATgMAQQgQAWgXAFIAFBMQABAUgCALQgCASgKAKQgNAMgVAAIgLAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.shape}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ20();

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF00FF").s().p("AE1U7QgFgBgCgEIpbACIgHADIgFAAIgGgDIgEgEIgEgDIgBgEIAAgEIAAgEIAAgDIAAgEIAAgEIABgBIgBgFQAAgNAFgRQAJgdgGgwQgJhAAAgPQABgeAOgsIAWhKQAJgnACgyQABgbgCg+QgChfAAi8QAAhJADgkQAEg9APguIALgfIAKggQAHgcABg1IAGipQABgkgLgOQgFgGgMgJQgNgJgFgFQgLgNgCgWQgBgMADgdQAEg7gLg4QgtAMgvgDQgTAAgFgKQgHgMATgSIAsgpQAegcANgOQAXgZAOgWQAgg0AIhNQAFgxgGhaQgCgkgIgQQgHgNgLgHQgMgJgNACIgNAEIgOAFQgIABgGgDQgFgDgCgDIgCgBIgEgDIgFAAQgDgBgBgEQgCgDABgEQACgFAHgGIAGgFIAAgDIABgEIADgCIABgBIAFAAIAAgCIABABICZiRQAxgtASgcQAKgOAVgsQAWgxAJgcQAOgtgCglQgBgYABgIQACgSAMgIIABgBQAQAFgCAkQgDBJAcBGQANAdAXAkQA1BSBIBKQAZAZAVATQAXAUANAGIARAIQAKAFAFAGIAIANQAFAHAEAEIAKAGQAFAEABAEQACAGgFAEIgEADQgEAFgMACQhAAIg/gYIgCC4QAAAUAGAIIALAMQAIALgCAXQgDAbADAJQAEANAQAUQAHAMAKAaQALAYAYAXQAPAQAfAXIBKA3QAPALgFAJQgDAIgRgCIibgSIAHD4QACBCAHAhIAJAnQAGAXABAPQAEAhgIBFQgIBCAFAjQAEAOgHAFQAHBDgBAlQAAAOgCAfQgDAeAAAPQABAZACAaIAHBNQAEAvAEAXIAKAsQAEAggJBAQgDAbABAPQABAYAKAQQAFAHAAAEIAAAEQAGAGADAFQAFAKgBASIgBAdIAFAbIABAZIAAAzQAAAKgDAFQgFAJgIgDQACAIgBAMIgBATQAAAZAKAMIAJAIQAFAFADAEQAEAGAAAQIAAAaQAAAJgDAEQgEAGgGAAIgDAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.shape}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ6();
	this.instance.setTransform(320,110);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30));

	// Слой 3
	this.instance_1 = new lib.Символ5();
	this.instance_1.setTransform(322,27.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleY:0.94,y:39.5},7,cjs.Ease.get(-1)).to({scaleY:0.88,y:51.5},7,cjs.Ease.get(1)).to({scaleY:0.94,y:40.3},7,cjs.Ease.get(-1)).to({scaleY:1,y:27.5},8,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(183.5,-33,273,192.5);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.setTransform(0,-70);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-383.5,-245,767,350);


(lib.sprite162копия = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shape147("synched",0);

	this.instance_1 = new lib.shape148("synched",0);

	this.instance_2 = new lib.shape149("synched",0);

	this.instance_3 = new lib.shape150("synched",0);

	this.instance_4 = new lib.shape151("synched",0);

	this.instance_5 = new lib.shape152("synched",0);

	this.instance_6 = new lib.shape153("synched",0);

	this.instance_7 = new lib.shape154("synched",0);

	this.instance_8 = new lib.shape155("synched",0);

	this.instance_9 = new lib.shape156("synched",0);

	this.instance_10 = new lib.shape157("synched",0);

	this.instance_11 = new lib.shape158("synched",0);

	this.instance_12 = new lib.shape159("synched",0);

	this.instance_13 = new lib.shape160("synched",0);

	this.instance_14 = new lib.shape161("synched",0);

	this.instance_15 = new lib.shape134("synched",0);

	this.instance_16 = new lib.shape135("synched",0);

	this.instance_17 = new lib.shape136("synched",0);

	this.instance_18 = new lib.shape137("synched",0);

	this.instance_19 = new lib.shape138("synched",0);

	this.instance_20 = new lib.shape139("synched",0);

	this.instance_21 = new lib.shape140("synched",0);

	this.instance_22 = new lib.shape141("synched",0);

	this.instance_23 = new lib.shape142("synched",0);

	this.instance_24 = new lib.shape143("synched",0);

	this.instance_25 = new lib.shape144("synched",0);

	this.instance_26 = new lib.shape145("synched",0);

	this.instance_27 = new lib.shape146("synched",0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},2).to({state:[{t:this.instance_2}]},2).to({state:[{t:this.instance_3}]},2).to({state:[{t:this.instance_4}]},2).to({state:[{t:this.instance_5}]},2).to({state:[{t:this.instance_6}]},2).to({state:[{t:this.instance_7}]},2).to({state:[{t:this.instance_8}]},2).to({state:[{t:this.instance_9}]},2).to({state:[{t:this.instance_10}]},2).to({state:[{t:this.instance_11}]},2).to({state:[{t:this.instance_12}]},2).to({state:[{t:this.instance_13}]},2).to({state:[{t:this.instance_14}]},2).to({state:[{t:this.instance_15}]},2).to({state:[{t:this.instance_16}]},2).to({state:[{t:this.instance_17}]},2).to({state:[{t:this.instance_18}]},2).to({state:[{t:this.instance_19}]},2).to({state:[{t:this.instance_20}]},2).to({state:[{t:this.instance_21}]},2).to({state:[{t:this.instance_22}]},2).to({state:[{t:this.instance_23}]},2).to({state:[{t:this.instance_24}]},2).to({state:[{t:this.instance_25}]},2).to({state:[{t:this.instance_26}]},2).to({state:[{t:this.instance_27}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68.7,41,108,95.6);


(lib.sprite162 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shape134("synched",0);

	this.instance_1 = new lib.shape135("synched",0);

	this.instance_2 = new lib.shape136("synched",0);

	this.instance_3 = new lib.shape137("synched",0);

	this.instance_4 = new lib.shape138("synched",0);

	this.instance_5 = new lib.shape139("synched",0);

	this.instance_6 = new lib.shape140("synched",0);

	this.instance_7 = new lib.shape141("synched",0);

	this.instance_8 = new lib.shape142("synched",0);

	this.instance_9 = new lib.shape143("synched",0);

	this.instance_10 = new lib.shape144("synched",0);

	this.instance_11 = new lib.shape145("synched",0);

	this.instance_12 = new lib.shape146("synched",0);

	this.instance_13 = new lib.shape147("synched",0);

	this.instance_14 = new lib.shape148("synched",0);

	this.instance_15 = new lib.shape149("synched",0);

	this.instance_16 = new lib.shape150("synched",0);

	this.instance_17 = new lib.shape151("synched",0);

	this.instance_18 = new lib.shape152("synched",0);

	this.instance_19 = new lib.shape153("synched",0);

	this.instance_20 = new lib.shape154("synched",0);

	this.instance_21 = new lib.shape155("synched",0);

	this.instance_22 = new lib.shape156("synched",0);

	this.instance_23 = new lib.shape157("synched",0);

	this.instance_24 = new lib.shape158("synched",0);

	this.instance_25 = new lib.shape159("synched",0);

	this.instance_26 = new lib.shape160("synched",0);

	this.instance_27 = new lib.shape161("synched",0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},2).to({state:[{t:this.instance_2}]},2).to({state:[{t:this.instance_3}]},2).to({state:[{t:this.instance_4}]},2).to({state:[{t:this.instance_5}]},2).to({state:[{t:this.instance_6}]},2).to({state:[{t:this.instance_7}]},2).to({state:[{t:this.instance_8}]},2).to({state:[{t:this.instance_9}]},2).to({state:[{t:this.instance_10}]},2).to({state:[{t:this.instance_11}]},2).to({state:[{t:this.instance_12}]},2).to({state:[{t:this.instance_13}]},2).to({state:[{t:this.instance_14}]},2).to({state:[{t:this.instance_15}]},2).to({state:[{t:this.instance_16}]},2).to({state:[{t:this.instance_17}]},2).to({state:[{t:this.instance_18}]},2).to({state:[{t:this.instance_19}]},2).to({state:[{t:this.instance_20}]},2).to({state:[{t:this.instance_21}]},2).to({state:[{t:this.instance_22}]},2).to({state:[{t:this.instance_23}]},2).to({state:[{t:this.instance_24}]},2).to({state:[{t:this.instance_25}]},2).to({state:[{t:this.instance_26}]},2).to({state:[{t:this.instance_27}]},2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.7,-7.8,107.5,145.7);


(lib.Символ30копия3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.setTransform(105,13);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(52).to({_off:false},0).to({x:1115},117).wait(40));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ30копия2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.setTransform(105,13);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(38).to({x:111},0).to({x:1545,y:10.1},238).wait(40));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-35.1,218,100);


(lib.Символ30копия = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.setTransform(105,13);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:1545,y:10.1},239).wait(40));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-35.1,218,100);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.setTransform(105,13);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:1115},169).wait(40));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-35.1,218,100);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ4();
	this.instance.setTransform(-130,-63.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(53.5,-96.2,273,192.5);


(lib.sprite235копия = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.sprite162копия();
	this.instance.setTransform(12.5,-31.4);
	this.instance.shadow = new cjs.Shadow("#FFCC00",0,0,23);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.2,-15.4,161,150);


(lib.sprite235 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.sprite162();
	this.instance.setTransform(12.5,-31.4);
	this.instance.shadow = new cjs.Shadow("#FFCC00",0,0,23);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.2,-64.2,161,199);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 8
	this.instance = new lib.Символ13();
	this.instance.setTransform(375.3,202.1);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.Символ13(), 3);

	this.instance_1 = new lib.Символ12();
	this.instance_1.setTransform(197.3,203.2);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2, false, new lib.Символ12(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 7
	this.instance_2 = new lib.Символ11();
	this.instance_2.setTransform(130,153.3);
	new cjs.ButtonHelper(this.instance_2, 0, 1, 2, false, new lib.Символ11(), 3);

	this.instance_3 = new lib.Символ9();
	this.instance_3.setTransform(360.5,106.9);
	new cjs.ButtonHelper(this.instance_3, 0, 1, 2, false, new lib.Символ9(), 3);

	this.instance_4 = new lib.Символ8();
	this.instance_4.setTransform(481.6,146.7);
	new cjs.ButtonHelper(this.instance_4, 0, 1, 2, false, new lib.Символ8(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4},{t:this.instance_3},{t:this.instance_2}]}).wait(1));

	// Слой 6
	this.instance_5 = new lib.Символ10();
	this.instance_5.setTransform(271.7,146.6);
	new cjs.ButtonHelper(this.instance_5, 0, 1, 2, false, new lib.Символ10(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

	// Слой 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AT4bEIgWgJQgWh8AFggIgLlXQgGjHgDjVQgMkHAEhlQCaAAALgIQi3hfgljGIAAjZICIAAQkEjSg7jQQgLh5gHAHQgIA0AIA9QhwETjaCCIB1AGQAJCUgEBIQgOAHAFALQAFAUgDAvQgTAGgBAaQgVAiAHAKIiUCHQAUALB9gHIAABkIgjAAIAAA6IgxAAIAAg6Ig5AAIAAA3IgtAAIAAg3Ig2AAIAAA0IgvAAIAAg0IhMgFIAAA6IgjAAIAAg1IgnAAIAAA3IgkAAIAAg3Ig8AAIAAA5IgqAAIAAg5IgoAAIgDA6IgeAAQgCgnACgVQgigEgVA/IgrADQgIhAgPABQgHgOAEgIQBYAAACgDIhehRQADgJABgXQgKgCgUgSIgJjCQBRAAAAgGQjXiyAKhxQgTAtAIAiQh0CrhTAnIBJAKQAJBmgPBmIgdAvIhdBLIBaAAIAAAcIhPAAIAAA7IhKAAIAAg7IhAAAIAAA5IhPAAIAAg5IhPAAIAAAzIhMAAIAPg0IgXAAIAAheICiAAIiLhjQgJgYgVgYQARgSgmgQQALgZgagRIAAg6QAHgFABgQQgOAIgEgLQAEiGgDhOQBAgQBBAKQkUjMgxjHQAGgVAAgHQgBgHgIgSIgKhTQgOA4gCAuQgHAOAHANQh9EZjLCAICFgFIAADhIgKAAIAABUIgUAiIgTAOIAAAdIgUAeIiHBrICcAAIAABgIhSA6IhKAAIAAg6IhGAAIAAA+IhHAAIAAg+IhQAAIAAA1IgqAAIAAg1IhKAAIAAAzIhRAAIAAgzIhTAAIAAA8Ig/AAIAAg8IgkAAIifiLQAAgagTgYQAAgfgWABQAAgeAAgWQASgKgSgLQgEgpAEinIB4gCQh7hag3hNQgWgLhoi9QAHg8gYAFQARg3gRggQgMFEkgCeQhBAxClgVQAIBvgIATQAVBxg8B2QhzBmguAjQA0gcBuAhIghSiMghQAAAMAAAg2BMCaqAAAMAAAA2Hg");
	mask.setTransform(385,73.2);

	// Слой 4
	this.instance_6 = new lib.sprite235копия();
	this.instance_6.setTransform(429.5,32.4,1.083,1.175,0,22.8,0);
	this.instance_6.compositeOperation = "lighter";

	this.instance_6.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1));

	// Слой 2
	this.instance_7 = new lib.sprite235();
	this.instance_7.setTransform(235.9,32.4,1.083,1.175,0,22.8,0);
	this.instance_7.compositeOperation = "lighter";

	this.instance_7.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1));

	// Слой 10 - копия
	this.instance_8 = new lib.Символ30копия2();
	this.instance_8.setTransform(-271.8,134.3,0.684,0.684);

	this.instance_8.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(1));

	// Слой 9 - копия
	this.instance_9 = new lib.Символ30копия3();
	this.instance_9.setTransform(-315,-36.4);

	this.instance_9.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(1));

	// Слой 10
	this.instance_10 = new lib.Символ30копия();
	this.instance_10.setTransform(-246.8,21.2,0.684,0.684);

	this.instance_10.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(1));

	// Слой 9
	this.instance_11 = new lib.Символ30();
	this.instance_11.setTransform(-305,94);

	this.instance_11.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(1));

	// Слой 1
	this.instance_12 = new lib.Символ3();
	this.instance_12.setTransform(306,229);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-110,-35,799.5,369.1);


// stage content:
(lib.siege_600x300 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
		
		 this.fon.x = - stage.mouseX / 10;
		 this.fon.y = - stage.mouseY / 10;
			 this.tre.x = stage.mouseX / 10;
			
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 6
	this.instance = new lib.Символ35();
	this.instance.setTransform(579.5,132.9,0.849,0.849);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// FlashAICB
	this.instance_1 = new lib.Символ33();
	this.instance_1.setTransform(16,14.9,0.198,0.198);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 3
	this.instance_2 = new lib.Символ37();
	this.instance_2.setTransform(298.8,278.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 4
	this.instance_3 = new lib.Символ32();
	this.instance_3.setTransform(300,280);
	this.instance_3.alpha = 0.262;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Слой 2
	this.tre = new lib.Символ7();
	this.tre.setTransform(541.2,232.8,1,1,0,0,0,-51.8,0);

	this.timeline.addTween(cjs.Tween.get(this.tre).wait(1));

	// Слой 1
	this.fon = new lib.Символ1();
	this.fon.setTransform(17.5,-0.3);

	this.timeline.addTween(cjs.Tween.get(this.fon).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.5,49.7,1217,434);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;