(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 30,
	color: "#FFFFFF",
	manifest: [
		{src:"images/ahahahh.png?1461594216825", id:"ahahahh"},
		{src:"images/dfdfdfd.png?1461594216825", id:"dfdfdfd"},
		{src:"images/fhgsdfgsdfg.png?1461594216825", id:"fhgsdfgsdfg"},
		{src:"images/flares__12_.png?1461594216825", id:"flares__12_"},
		{src:"images/ghghgh.png?1461594216825", id:"ghghgh"},
		{src:"images/Layer6.png?1461594216825", id:"Layer6"},
		{src:"images/Layer6copy2.png?1461594216825", id:"Layer6copy2"},
		{src:"images/Layer6copy3.png?1461594216825", id:"Layer6copy3"},
		{src:"images/Layer6copy4.png?1461594216825", id:"Layer6copy4"},
		{src:"images/Layer9.png?1461594216825", id:"Layer9"},
		{src:"images/safasfgasf.jpg?1461594216825", id:"safasfgasf"},
		{src:"images/sjsjsjs.png?1461594216825", id:"sjsjsjs"}
	]
};



// symbols:



(lib.ahahahh = function() {
	this.initialize(img.ahahahh);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,235,152);


(lib.dfdfdfd = function() {
	this.initialize(img.dfdfdfd);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,127,91);


(lib.fhgsdfgsdfg = function() {
	this.initialize(img.fhgsdfgsdfg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,159,66);


(lib.flares__12_ = function() {
	this.initialize(img.flares__12_);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1199,805);


(lib.ghghgh = function() {
	this.initialize(img.ghghgh);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,194,30);


(lib.Layer6 = function() {
	this.initialize(img.Layer6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,127,115);


(lib.Layer6copy2 = function() {
	this.initialize(img.Layer6copy2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,127,115);


(lib.Layer6copy3 = function() {
	this.initialize(img.Layer6copy3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,130,134);


(lib.Layer6copy4 = function() {
	this.initialize(img.Layer6copy4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,105,95);


(lib.Layer9 = function() {
	this.initialize(img.Layer9);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,581,170);


(lib.safasfgasf = function() {
	this.initialize(img.safasfgasf);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.sjsjsjs = function() {
	this.initialize(img.sjsjsjs);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,255,243);


(lib.Символ68 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AoQBEIgMgGQgGgDgFgFIgJgKQgEgGgDgGQgDgIgCgHQgCgIAAgJQAAgvBIgYQAJAAASAEIAMAGIALAIIAJAKQAEAHADAGQADAHABAHQACAJAAAHQAAAwhIAYQgSgBgIgDgAoDgiQgGADgFAFQgFAEgDAHQgDAHAAAIQAAAJADAIQADAGAFAFQAFAFAGACQAHADAGAAQAHAAAGgDQAHgCAFgFQAFgFACgGQADgIAAgJQAAgIgDgHQgCgHgFgEQgFgFgHgDQgGgCgHAAQgGAAgHACgAGxBGIgNgEIgMgFIgLgIIgJgKQgEgFgDgIQgDgGgCgHQgBgJAAgIQAAgHABgIQACgIADgHQADgGAEgGIAJgKIALgIQAGgEAGgBIANgEIANgBQAMAAAKADQALADAJAGQAMAKAEAHIAFALIADANIgjAAIgFgJIgGgHIgJgDIgLgBQgHAAgHACQgGADgFAGQgEAFgDAGQgCAIAAAHQAAAHACAHQADAIAEAFQAFAFAGADQAHAEAHgBQAGAAAFgBQAFgBAEgDQAEgDADgEQADgEACgGIAjAAIgDANIgFAMIgIAKQgDAEgFADQgJAGgLAEQgLADgMAAgAJhBGIAAgqIgTAAIgYAqIgoAAIAAgGIAcgsQgHgFgFgGQgEgGgCgFQgDgIAAgHQAAgIACgHQABgHAEgHQAFgHAFgFQAHgFAIgCQAIgEAKAAIA+AAIAACLgAI8gfQgEAFAAAHQAAAHAEAEQAEAGAHAAIAaAAIAAgiIgaAAQgHgBgEAGgAEkBGIAAhqIgjAAIAAghIBoAAIAAAhIgiAAIAABqgACXBGIAAiLIBXAAIAAAhIgzAAIAAATIAvAAIAAAeIgvAAIAAAYIA1AAIAAAhgABiBGIgIgSIg3AAIgJASIghAAIAAgGIA9iHIAQAAIA/CHIAAAGgABOAVIgQgjIgQAjIAgAAgAg9BGIAAgyIgHAAIgRgBQgHAAgHgDIgLgGQgFgDgEgFIgHgIQgDgGgBgHQgDgJgBgYIAAgRIAlAAIAAARQAAAXAEAGQADAGAGADQAGADAKAAIAHAAIAAg6IAlAAIAACLgAj8BGIAAgFIAWgtIgwhTIAAgGIAoAAIAbA0IABAAIAYg0IAnAAIAAAGIhDCFgAk6BGIgkhQIgkBQIgjAAIAAgGIA/iHIAQAAIA/CHIAAAGgAp9BGIAAhpIgrAAIAABpIglAAIAAiLIB1AAIAACLgAKsA/QgGgFAAgHQAAgFACgDIAEgGQAGgFAIAAQAIAAAGAFIAEAGQACADAAAFQAAAHgGAFQgGAFgIABQgIgBgGgFgAKpAbIgDhiIAoAAIgDBig");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.8,-7.3,143.6,14.6);


(lib.Символ67 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGVBEIgMgGQgHgDgFgFIgJgKQgEgGgCgHQgEgHgBgHQgCgJAAgIQAAgvBIgYQAJAAASAEIALAGIALAIIAJAKQAFAGACAHQADAHACAHQACAJAAAHQAAAwhIAYQgSgBgIgDgAGigiQgGACgFAFQgFAFgDAHQgDAHAAAIQAAAJADAHQADAHAFAFQAFAFAGACQAGADAHAAQAHAAAGgDQAGgCAGgFQAFgFACgHQADgHAAgJQAAgIgDgHQgCgHgFgFQgGgFgGgCQgGgCgHAAQgHAAgGACgAnJBEIgLgGQgHgDgEgFIgJgKQgFgGgCgHQgDgHgCgHQgCgJAAgIQAAgvBIgYQAJAAARAEIAMAGIAMAIIAJAKQAEAGACAHQAEAHABAHQACAJAAAHQAAAwhIAYQgSgBgJgDgAm7giQgGACgFAFQgFAFgDAHQgDAHAAAIQAAAJADAHQADAHAFAFQAFAFAGACQAHADAGAAQAHAAAGgDQAGgCAGgFQAEgFADgHQADgHAAgJQAAgIgDgHQgDgHgEgFQgGgFgGgCQgGgCgHAAQgGAAgHACgAEoBFIAAg4IgsAAIAAA4IgkAAIAAiKIAkAAIAAAzIAsAAIAAgzIAkAAIAACKgACQBFIAAgxIgHAAIgRgBQgIgBgGgCIgLgGQgGgDgDgFIgHgIQgDgGgCgHQgCgJgBgYIAAgRIAlAAIAAARQAAAWAEAHQADAGAGADQAGACAKAAIAHAAIAAg5IAkAAIAACKgAAFBFIAAhFIhFBFIgNAAIAAiKIAkAAIAABFIBFhFIAOAAIAACKgAiCBFIgkhQIgkBQIgjAAIAAgFIA/iHIAPAAIBACHIAAAFgAk3BFIAAhqIgiAAIAAggIBoAAIAAAgIgiAAIAABqg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.3,-7.2,100.7,14.6);


(lib.Символ66 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADQBGIAAgqIgTAAIgYAqIgoAAIAAgGIAcgsQgHgFgEgGQgFgGgCgFQgDgIAAgHQAAgIACgHQACgHAEgHQAEgHAGgFQAGgFAIgCQAJgEAJAAIA+AAIAACLgACrgfQgEAFABAHQAAAHADAEQAEAGAHAAIAaAAIAAgiIgaAAQgGgBgFAGgAABBGIAAiLIBkAAIAAAhIhBAAIAAARIAaAAQAJAAANADQAJAEAHAGQAGAGADAHQADAIABAJQgBAJgDAIQgDAIgGAGQgHAHgJADQgNAFgJAAgAAkAlIAaAAQAHABAEgFQAEgDAAgGQAAgGgEgDQgEgFgHAAIgaAAgAh1BGIAAiLIBXAAIAAAhIgzAAIAAATIAvAAIAAAeIgvAAIAAAYIA1AAIAAAhgAjQBGIAAhqIgjAAIAAghIBoAAIAAAhIgiAAIAABqg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.4,-7,48.9,14);


(lib.Символ65 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgmBGIAAgFIAWgtIgwhTIAAgGIAoAAIAZA0IABAAIAYg0IAnAAIAAAGIhBCFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.5,-7,13.1,14);


(lib.Символ60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.fhgsdfgsdfg();
	this.instance.setTransform(11.3,-85.3,1,1,75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.4,-85.3,104.9,170.7);


(lib.Символ58 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AkvAjIAAiCIJfAAIAACCg");
	var mask_graphics_1 = new cjs.Graphics().p("AkwA2IAAiDIJhAAIAACDg");
	var mask_graphics_2 = new cjs.Graphics().p("AkwBCIAAiDIJgAAIAACDg");
	var mask_graphics_3 = new cjs.Graphics().p("AkvBCIAAiDIJgAAIAACDg");
	var mask_graphics_4 = new cjs.Graphics().p("AkwBCIAAiDIJgAAIAACDg");
	var mask_graphics_5 = new cjs.Graphics().p("AkwA2IAAiDIJhAAIAACDg");
	var mask_graphics_6 = new cjs.Graphics().p("AkvAjIAAiCIJfAAIAACCg");
	var mask_graphics_7 = new cjs.Graphics().p("AkwA2IAAiDIJhAAIAACDg");
	var mask_graphics_8 = new cjs.Graphics().p("AkwBCIAAiDIJgAAIAACDg");
	var mask_graphics_9 = new cjs.Graphics().p("AkvBCIAAiDIJgAAIAACDg");
	var mask_graphics_10 = new cjs.Graphics().p("AkwBCIAAiDIJgAAIAACDg");
	var mask_graphics_11 = new cjs.Graphics().p("AkwA2IAAiDIJhAAIAACDg");
	var mask_graphics_12 = new cjs.Graphics().p("AkvAjIAAiCIJfAAIAACCg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:1,y:-9.7}).wait(1).to({graphics:mask_graphics_1,x:0.8,y:-7.8}).wait(1).to({graphics:mask_graphics_2,x:0.7,y:-5.3}).wait(1).to({graphics:mask_graphics_3,x:0.6,y:-1.6}).wait(1).to({graphics:mask_graphics_4,x:0.7,y:-5.3}).wait(1).to({graphics:mask_graphics_5,x:0.8,y:-7.8}).wait(1).to({graphics:mask_graphics_6,x:1,y:-9.7}).wait(1).to({graphics:mask_graphics_7,x:0.8,y:-7.8}).wait(1).to({graphics:mask_graphics_8,x:0.7,y:-5.3}).wait(1).to({graphics:mask_graphics_9,x:0.6,y:-1.6}).wait(1).to({graphics:mask_graphics_10,x:0.7,y:-5.3}).wait(1).to({graphics:mask_graphics_11,x:0.8,y:-7.8}).wait(1).to({graphics:mask_graphics_12,x:1,y:-9.7}).wait(39));

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E68119").s().p("ABGAOQgSgGAAgIQAAgHASgGQASgFAaAAQAaAAASAFQATAGAAAHQAAAIgTAGQgSAGgagBQgaABgSgGgAieAOQgSgGAAgIQAAgHASgGQATgFAaAAQAaAAASAFQASAGAAAHQAAAIgSAGQgSAGgagBQgaABgTgGg");

	this.shape.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(51));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ghghgh();
	this.instance.setTransform(-97,-15);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-97,-15,194,30);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#612800","#630000","#FF0000","#610000"],[0,0.008,0.518,1],0,-24.8,0,24.8).s().p("AuqDwIAAnfIdVAAIAAHfg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-94,-24,188,48);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aj8BUIAAgMQgRAAgVgIIAAgRQAWAKAQAAIAAg0QgTgKgIgJQgHgJAAgNQAAgPAKgJQAJgKAPgBIAAgMIAKAAIAAAMQAOAAARAHIAAAPQgSgIgNgBIAAA0IAIAFQAPAHAFAHQAGAHAAALQAAAQgJALQgJAKgQAEIAAAMgAjyA4QARgGAAgQQAAgHgDgEQgEgFgKgHgAkNglQAAAIAEAFQADAFAKAHIAAgtQgRAFAAAPgADLBJIAegyQgLAAgJgDQgJgDgGgGQgHgGgDgHQgEgIAAgKQAAgIAEgOQAEgJAHgGQAHgFAKgDQAKgDALAAQAMAAAKADQAKADAHAFQAHAGAEAJQAEAOAAAIQAAAIgBAGQgCAGgEAFIgpBEgADhghQgFAFAAAIQAAAIAFAEQAFAFAHAAQAJAAAFgEQAEgFAAgIQAAgIgFgFQgEgFgJAAQgHAAgFAFgABSBJIAegyQgLAAgKgDQgIgDgHgGQgGgGgEgHQgDgIAAgKQAAgIAEgOQADgJAIgGQAHgFAKgDQAJgDAMAAQAMAAAJADQAKADAHAFQAIAGAEAJQAEAOAAAIQAAAIgCAGQgCAGgEAFIgoBEgABnghQgFAFAAAIQAAAIAFAEQAFAFAIAAQAJAAAEgEQAFgFAAgIQAAgIgFgFQgFgFgIAAQgIAAgFAFgAgmBJIAegyQgLAAgJgDQgJgDgGgGQgHgGgDgHQgEgIAAgKQAAgIAEgOQAEgJAHgGQAHgFAKgDQAKgDALAAQAKAAAKADQAKADAHAFQAHAGAEAJQAEAOAAAIQAAAIgBAGQgCAGgEAFIgpBEgAgQghQgFAFAAAIQAAAIAFAEQAFAFAHAAQAHAAAFgEQAEgFAAgIQAAgIgFgFQgEgFgHAAQgHAAgFAFgAifBJIAegyQgLAAgKgDQgIgDgHgGQgGgGgEgHQgDgIAAgKQAAgIAEgOQADgJAIgGQAHgFAKgDQAJgDAMAAQAMAAAJADQAKADAHAFQAIAGAEAJQAEAOAAAIQAAAIgCAGQgCAGgEAFIgoBEgAiKghQgFAFAAAIQAAAIAFAEQAFAFAIAAQAJAAAEgEQAFgFAAgIQAAgIgFgFQgFgFgIAAQgIAAgFAFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.2,-8.4,58.4,16.9);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgAhBCpIAegzQgLABgKgDQgIgDgHgGQgGgHgEgIQgDgIAAgLQAAgIAEgNQADgJAIgGQAHgGAKgDQAKgCAKAAQALAAAJACQAKADAHAGQAIAGAEAJQAEANAAAIQAAAJgBAGQgDAIgDAFIgpBEgEgAMBA9QgEAFAAAHQAAAJAEAEQAGAFAGAAQAIAAAEgFQAFgEAAgJQAAgHgFgFQgFgFgHAAQgGAAgGAFgEgARA/LQgIgCgHgFQgGgEgFgGQgFgFgCgHQgCgGAAgIQAAgHACgGQACgHAEgGQAFgGAGgFIgHgJIgCgKQgBgEABgGQAAgFACgFQADgFAEgEQADgEAGgDQAEgEAHgBQAHgCAGAAQAIAAAHACQAGABAGAEIAJAHQAEAFABAFQADAEABAGQABAEgBAGQgBAFgDAFIgFAJQAFAFAFAFQAEAGACAHQACAHAAAGQgBAIgBAGQgDAHgEAFQgEAHgHADQgGAFgJACQgIADgLAAQgIAAgJgDgEgAGA+OQgDABgDAEQgEAEAAAHQAAAIAEAEQADADADABIAGACQAFgBADgBQADgBACgDQAFgEAAgIQAAgHgFgEQgCgEgDgBQgDgBgFAAIgGABgEgAHA9dQgEADAAAFQAAAEAEADQADADAEABQAGgBAEgDQADgDAAgEQAAgFgDgDQgEgEgGAAQgEAAgDAEgEgAnA7wIAshsIg1AAIAAghIBlAAIAAAGIg3CHgEgATA4TQgJgDgIgGQgHgGgFgJIgDgKIAAgMQgBgHACgHQACgHAEgGIAohEIAmAAIgeAyQALAAAKACQAIADAHAGQAGAHAEAIQADAJABAKIgBAMIgEAKQgEAJgHAGQgHAGgKADQgJACgLAAQgKAAgKgCgEgAGA3VQgDABgCADQgEAFAAAHQAAAIAEAFQAFAFAHABQAHgBAFgFQAEgEABgJQAAgHgFgFQgFgFgHAAQgDAAgEABgEgAQA03QgJgDgHgGQgFgGgFgIQgDgJAAgKIAeAAQAAAGAEAEQAFADAGAAQAHAAAEgDQAEgFAAgIQAAgGgEgFQgCgDgHgBIgJgCIgkABIAAhPIBVAAIAAAfIg4AAIAAARQAOgBAJACQAMABAIAFIAIAGQAEAEADAFIADAKQACAHAAAIQAAAIgDAKQgEAIgFAHQgHAHgJAEQgNAEgIABQgIgBgIgDgEAAIAxbIAAgaIg7AAIAAgPIA1hiIAnAAIAABTIAMAAIAAAeIgMAAIAAAagEgAMAwjIAVAAIACgqgEgANAuBQgFgBgGgEIgJgGIgIgJQgDgGgBgGQgCgFAAgHIAgAAQAAAGAEAEQAEAEAHAAQAGgBAEgFQADgEABgHQgBgIgCgEQgEgDgGgCQgCgCgGAAIgNAAIAAgFIATgmIgpAAIAAghIBYAAIAAAGIgaAvQAIACAGAFQAFADAEAGQACAGACAGQACAGgBAIQAAAIgCAJQgEAJgGAHQgGAHgKAEQgMAEgIAAQgGABgHgCgEgAwAqjIAAgFIAyhNQADgEACgEIADgKQAAgEgDgDQgEgDgDAAQgHAAgEADQgEAEAAAHIgeAAQAAgLADgJQAEgIAGgGQAGgFAJgDQAHgDAKAAQAGgBAGACQAGABAFADQAGADAEAFQAEAEACAFQADAFABAGQABAGAAAHQgBAGgCAGQgCAGgEAGIgcAoIApAAIAAAfgEgAkAnIIAAgdIAUAAIAAhSIgTAAIAAgeIA0AAIAABwIAVAAIAAAdgEgAVAjoQgJgDgIgGQgHgGgEgKIgDgJIgBgLIAAgxQAAgHAEgOQAEgIAHgGQAIgHAJgDQAJgDALAAQAJAAAKADQAJADAIAHQAHAGAEAIQADAOAAAHIAAAxIgBALIgCAJQgEAKgHAGQgIAGgJADQgKADgJAAQgLAAgJgDgEgAOAh+QgFAFAAAIIAAAvQAAAJAFAEQAFAEAIABQAHgBAFgEQAFgEAAgJIAAgvQAAgIgFgFQgFgEgHAAQgIAAgFAEgEgAhAgFIAegzQgLABgKgDQgIgDgHgHQgGgGgEgJQgDgIAAgKQAAgIAEgNQADgJAIgHQAHgFAKgDQAKgDAKAAQALAAAJADQAKADAHAFQAIAHAEAJQAEANAAAIQAAAIgBAHQgDAHgDAFIgpBFgAgMeZQgEAEAAAIQAAAIAEAFQAGAEAGAAQAIAAAEgEQAFgFAAgIQAAgIgFgEQgFgGgHAAQgGAAgGAGgAgRcnQgIgDgHgEQgGgEgFgHQgFgFgCgGQgCgHAAgIQAAgGACgHQACgGAEgHQAFgGAGgEIgHgJIgCgKQgBgFABgGQAAgEACgFQADgFAEgEQADgEAGgEQAEgDAHgBQAHgDAGAAQAIAAAHADQAGABAGADIAJAIQAEAEABAFQADAFABAFQABAFgBAFQgBAGgDAEIgFAJQAFAFAFAGQAEAFACAIQACAGAAAHQgBAHgBAHQgDAGgEAGQgEAGgHAEQgGAEgJADQgIACgLAAQgIAAgJgCgAgGbqQgDABgDADQgEAFAAAHQAAAHAEAFQADACADACIAGABQAFAAADgBQADgCACgCQAFgFAAgHQAAgHgFgFQgCgDgDgBQgDgBgFgBIgGACgAgHa5QgEADAAAEQAAAFAEADQADADAEAAQAGAAAEgDQADgDAAgFQAAgEgDgDQgEgEgGAAQgEAAgDAEgAgnZLIAshsIg1AAIAAggIBlAAIAAAGIg3CGgAgTVuQgJgCgIgHQgHgGgFgIIgDgLIAAgLQgBgIACgGQACgHAEgHIAohDIAmAAIgeAyQALAAAKACQAIADAHAGQAGAGAEAJQADAJABAKIgBALIgEALQgEAIgHAGQgHAHgKACQgJADgLAAQgKAAgKgDgAgGUxQgDABgCADQgEAEAAAIQAAAHAEAGQAFAFAHAAQAHAAAFgFQAEgFABgIQAAgIgFgEQgFgGgHAAQgDABgEABgAgQSTQgJgDgHgGQgFgHgFgIQgDgIAAgLIAeAAQAAAHAEADQAFAEAGAAQAHAAAEgEQAEgFAAgIQAAgGgEgEQgCgDgHgCIgJgCIgkABIAAhOIBVAAIAAAfIg4AAIAAARQAOgBAJACQAMABAIAEIAIAGQAEAEADAFIADALQACAHAAAHQAAAJgDAJQgEAJgFAGQgHAHgJAFQgNAEgIAAQgIAAgIgDgAAIO3IAAgbIg7AAIAAgPIA1hiIAnAAIAABUIAMAAIAAAdIgMAAIAAAbgAgMN/IAVAAIACgqgAgNLcQgFgBgGgDIgJgHIgIgJQgDgFgBgGQgCgGAAgHIAgAAQAAAHAEADQAEAEAHAAQAGAAAEgFQADgFABgHQgBgHgCgEQgEgEgGgCQgCgCgGABIgNAAIAAgGIATgmIgpAAIAAggIBYAAIAAAFIgaAvQAIACAGAFQAFAEAEAGQACAFACAGQACAHgBAHQAAAJgCAJQgEAIgGAIQgGAGgKAFQgMAEgIAAQgGAAgHgCgAgwH/IAAgFIAyhOQADgDACgFIADgJQAAgEgDgDQgEgDgDAAQgHAAgEADQgEADAAAIIgeAAQAAgMADgIQAEgJAGgGQAGgFAJgDQAHgDAKAAQAGAAAGACQAGABAFADQAGADAEAEQAEAFACAFQADAFABAGQABAGAAAGQgBAHgCAFQgCAHgEAGIgcAnIApAAIAAAggAgkEjIAAgdIAUAAIAAhSIgTAAIAAgdIA0AAIAABvIAVAAIAAAdgAgVBDQgJgDgIgGQgHgGgEgJIgDgKIgBgLIAAguQAAgIAEgNQAEgJAHgGQAIgGAJgDQAJgDALgBQAJABAKADQAJADAIAGQAHAGAEAJQADANAAAIIAAAuIgBALIgCAKQgEAJgHAGQgIAGgJADQgKAEgJAAQgLAAgJgEgAgOglQgFAFAAAJIAAAtQAAAIAFAFQAFAEAIAAQAHAAAFgEQAFgFAAgIIAAgtQAAgJgFgFQgFgEgHAAQgIAAgFAEgAghiWIAegzQgLABgKgDQgIgDgHgGQgGgHgEgIQgDgJAAgKQAAgHAEgOQADgJAIgGQAHgGAKgDQAKgCAKAAQALAAAJACQAKADAHAGQAIAGAEAJQAEAOAAAHQAAAJgBAGQgDAHgDAGIgpBEgAgMkCQgEAFAAAHQAAAJAEAEQAGAFAGAAQAIAAAEgEQAFgFAAgJQAAgHgFgFQgFgFgHAAQgGAAgGAFgAgRl0QgIgCgHgFQgGgEgFgGQgFgGgCgGQgCgHAAgHQAAgHACgGQACgHAEgGQAFgGAGgFIgHgJIgCgKQgBgEABgGQAAgFACgFQADgFAEgEQADgEAGgDQAEgEAHgBQAHgCAGAAQAIAAAHACQAGABAGAEIAJAHQAEAFABAEQADAFABAFQABAFgBAGQgBAFgDAFIgFAJQAFAEAFAHQAEAFACAHQACAHAAAGQgBAIgBAGQgDAHgEAFQgEAHgHADQgGAFgJACQgIADgLAAQgIAAgJgDgAgGmxQgDACgDADQgEAFAAAGQAAAHAEAGQADACADABIAGABQAFABADgCQADgBACgCQAFgGAAgHQAAgGgFgFQgCgDgDgCQgDgBgFAAIgGABgAgHniQgEADAAAFQAAAEAEADQADADAEAAQAGAAAEgDQADgDAAgEQAAgFgDgDQgEgDgGAAQgEAAgDADgAgnpPIAshsIg1AAIAAghIBlAAIAAAGIg3CHgAgTssQgJgDgIgGQgHgGgFgJIgDgKIAAgMQgBgHACgHQACgHAEgGIAohDIAmAAIgeAxQALAAAKACQAIAEAHAFQAGAHAEAIQADAJABAKIgBAMIgEAKQgEAJgHAGQgHAGgKADQgJADgLAAQgKAAgKgDgAgGtqQgDACgCACQgEAFAAAHQAAAIAEAFQAFAGAHgBQAHABAFgGQAEgEABgJQAAgHgFgFQgFgFgHAAQgDAAgEABgAgQwIQgJgDgHgGQgFgGgFgIQgDgJAAgLIAeAAQAAAIAEADQAFAEAGAAQAHAAAEgFQAEgEAAgIQAAgHgEgDQgCgEgHgCIgJgBIgkAAIAAhOIBVAAIAAAfIg4AAIAAASQAOgBAJABQAMACAIAEIAIAGQAEAEADAEIADALQACAHAAAIQAAAIgDAKQgEAIgFAHQgHAHgJAEQgNAFgIgBQgIABgIgEgAAIzkIAAgaIg7AAIAAgPIA1hiIAnAAIAABTIAMAAIAAAeIgMAAIAAAagAgM0cIAVAAIACgpgAgN2+QgFgBgGgDIgJgHIgIgJQgDgFgBgGQgCgHAAgHIAgAAQAAAIAEADQAEADAHABQAGAAAEgGQADgEABgHQgBgIgCgEQgEgDgGgDQgCgBgGAAIgNAAIAAgFIATgnIgpAAIAAggIBYAAIAAAFIgaAwQAIACAGAEQAFAEAEAGQACAFACAHQACAGgBAIQAAAJgCAIQgEAJgGAHQgGAHgKAEQgMAFgIgBQgGAAgHgBgAgw6bIAAgGIAyhNQADgEACgEIADgKQAAgEgDgCQgEgEgDAAQgHAAgEAEQgEADAAAHIgeAAQAAgLADgJQAEgIAGgGQAGgGAJgDQAHgCAKAAQAGgBAGACQAGACAFACQAGADAEAFQAEAEACAFQADAGABAGQABAFAAAHQgBAGgCAGQgCAGgEAHIgcAmIApAAIAAAhgAgk94IAAgcIAUAAIAAhSIgTAAIAAgdIA0AAIAABvIAVAAIAAAcgEgAVghXQgJgDgIgHQgHgGgEgIIgDgKIgBgLIAAgxQAAgHAEgNQAEgJAHgGQAIgGAJgEQAJgDALAAQAJAAAKADQAJAEAIAGQAHAGAEAJQADANAAAHIAAAxIgBALIgCAKQgEAIgHAGQgIAHgJADQgKAEgJAAQgLAAgJgEgEgAOgjBQgFAEAAAJIAAAvQAAAJAFAEQAFAEAIAAQAHAAAFgEQAFgEAAgJIAAgvQAAgJgFgEQgFgEgHAAQgIAAgFAEgEgAhgk7IAegyQgLAAgKgDQgIgDgHgGQgGgGgEgJQgDgIAAgKQAAgIAEgOQADgJAIgGQAHgFAKgDQAKgDAKAAQALAAAJADQAKADAHAFQAIAGAEAJQAEAOAAAIQAAAIgBAGQgDAIgDAFIgpBEgEgAMgmnQgEAFAAAIQAAAIAEAFQAGAEAGAAQAIABAEgFQAFgEAAgJQAAgIgFgFQgFgEgHgBQgGABgGAEgEgARgoYQgIgDgHgEQgGgEgFgHQgFgFgCgHQgCgGAAgHQAAgHACgHQACgHAEgFQAFgHAGgEIgHgJIgCgKQgBgFABgGQAAgFACgFQADgFAEgEQADgDAGgEQAEgDAHgBQAHgCAGAAQAIAAAHACQAGABAGADIAJAHQAEAFABAFQADAEABAGQABAFgBAFQgBAFgDAGIgFAJQAFAEAFAGQAEAGACAGQACAHAAAHQgBAHgBAGQgDAHgEAGQgEAGgHAEQgGAEgJADQgIADgLAAQgIAAgJgDgEgAGgpVQgDABgDADQgEAFAAAHQAAAHAEAFQADACADABIAGACQAFAAADgCQADgBACgCQAFgFAAgHQAAgHgFgFQgCgDgDgBQgDgCgFAAIgGACgEgAHgqHQgEADAAAFQAAAFAEADQADADAEAAQAGAAAEgDQADgDAAgFQAAgFgDgDQgEgDgGAAQgEAAgDADgEgAngr0IAshsIg1AAIAAggIBlAAIAAAFIg3CHgEgATgvRQgJgCgIgHQgHgGgFgIIgDgKIAAgMQgBgIACgGQACgIAEgGIAohDIAmAAIgeAyQALAAAKACQAIADAHAGQAGAGAEAIQADAJABALIgBAMIgEAKQgEAIgHAGQgHAHgKACQgJADgLAAQgKAAgKgDgEgAGgwOQgDABgCACQgEAFAAAIQAAAHAEAGQAFAFAHAAQAHAAAFgFQAEgFABgIQAAgIgFgFQgFgEgHgBQgDAAgEACgEgAQgytQgJgDgHgGQgFgFgFgJQgDgIAAgLIAeAAQAAAHAEADQAFAEAGAAQAHAAAEgEQAEgEAAgJQAAgGgEgEQgCgDgHgCIgJgCIgkABIAAhOIBVAAIAAAfIg4AAIAAARQAOgBAJACQAMABAIAFIAIAFQAEAEADAFIADALQACAGAAAIQAAAJgDAJQgEAIgFAIQgHAHgJAEQgNAEgIAAQgIAAgIgEgEAAIg2IIAAgaIg7AAIAAgQIA1hiIAnAAIAABUIAMAAIAAAeIgMAAIAAAagEgAMg3AIAVAAIACgqgEgANg5jQgFgBgGgDIgJgHIgIgJQgDgFgBgGQgCgGAAgHIAgAAQAAAHAEAEQAEADAHAAQAGAAAEgFQADgEABgIQgBgHgCgEQgEgEgGgCQgCgBgGgBIgNAAIAAgFIATgmIgpAAIAAggIBYAAIAAAFIgaAvQAIADAGAEQAFAEAEAFQACAGACAHQACAGgBAHQAAAJgCAIQgEAJgGAIQgGAGgKAEQgMAFgIAAQgGAAgHgCgEgAwg9AIAAgGIAyhMQADgEACgEIADgKQAAgEgDgDQgEgDgDAAQgHAAgEADQgEADAAAHIgeAAQAAgLADgIQAEgIAGgHQAGgFAJgDQAHgDAKAAQAGgBAGACQAGACAFADQAGADAEAEQAEAFACAFQADAFABAGQABAGAAAGQgBAGgCAGQgCAHgEAGIgcAnIApAAIAAAggEgAkhAcIAAgdIAUAAIAAhSIgTAAIAAgdIA0AAIAABvIAVAAIAAAdg");
	this.shape.setTransform(0.3,0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.2,-426.4,10.9,853.1);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#0000FF").ss(4.2,1,1).p("Egu3gXbMBdvAAAMAAAAu3MhdvAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-302.1,-152.1,604.2,304.2);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgAiAzGIAfgyQgLAAgKgDQgIgDgHgGQgHgGgDgIQgDgJgBgKQAAgIAFgOQADgJAIgGQAGgFALgDQAJgDALAAQAKAAAKADIAIADIAJAFQAHAGAFAJQADAOAAAIQABAIgCAGQgCAIgEAGIgoBDgEgAMAxaQgFAFAAAIQAAAIAFAFQAFAEAHAAQAIABAEgFQAEgEAAgJQAAgIgEgFQgFgEgHAAQgHAAgFAEgEgASAvpQgIgCgHgFQgGgEgFgGQgEgGgCgHQgCgGgBgHQAAgHACgHQADgHADgFQAFgHAGgEIgGgJIgDgKQgBgFABgGQABgEACgGQACgEAEgFQADgDAGgEQAFgDAHgBQAHgCAGAAQAHAAAIACQAGABAFADIACACIAHAFQAEAFACAFQADAEAAAGQABAFgBAGQAAAEgDAGIgGAJQAGAEAEAGQAFAGACAGQABAHAAAHQAAAHgCAGQgCAHgFAGQgEAGgHAEIgFADIgKAEQgIACgKABQgJgBgJgCgEgAHAusQgDABgCADQgEAFgBAHQABAHAEAFQACACADABIAHACQAEAAADgCQAEgBACgCQAFgFgBgHQABgHgFgFQgCgDgEgBQgDgBgEAAIgHABgEgAIAt6QgEADABAFQgBAFAEADQAEADAEAAQAGAAADgDQAEgDAAgFQAAgFgEgDQgDgDgGAAQgEAAgEADgEgAnAsNIAshsIg1AAIAAggIBkAAIAAAFIg2CHgEgATAoxQgKgEgIgFQgHgGgEgJIgDgKIgBgMQAAgIABgGQADgIADgGIAphDIAlAAIgdAyQALAAAJACIAEACQAHADAFAEQAGAGAEAIQADAJAAALIgBAMIgDAKQgEAJgIAGIgJAFIgHAEQgKACgLAAQgJAAgKgCgEgAGAnzQgDABgCACQgFAFAAAIQAAAIAFAFQAFAFAGAAQAIAAAFgFQAEgFAAgIQAAgIgEgFQgFgEgIAAQgDAAgDABgEgARAlUQgJgCgGgHQgGgFgEgIQgEgJAAgLIAfAAQAAAHAEAEQAFADAGAAQAGAAAEgEQAEgFABgIQgBgGgDgEQgDgEgGgBIgKgCIgkABIAAhOIBWAAIAAAfIg4AAIAAARQAOgBAIABQAMACAIAFIAIAFQAEAEADAFIAEALQACAGAAAIQAAAJgEAJQgDAIgGAIQgHAGgIAEQgNAFgIAAQgJAAgIgEgEAAHAh5IAAgaIg7AAIAAgQIA2hiIAnAAIAABUIALAAIAAAeIgLAAIAAAagEgAMAhBIAUAAIADgqgAgNeeQgGgBgGgDIgJgHIgHgJQgDgFgCgGQgBgGAAgHIAfAAQAAAHAFAEQADADAIAAQAFAAAEgFQAEgFABgHQgBgHgDgEQgDgEgGgCQgCgBgHgBIgMAAIAAgEIATgnIgpAAIAAggIBXAAIAAAFIgaAwQAJABAFAFQAGAEADAFQADAGABAHQACAGAAAHQAAAJgDAIQgDAJgHAIQgGAGgJAEQgNAFgHAAQgHAAgGgCgAgwbBIAAgGIAyhMQADgEABgEIADgKQAAgEgDgDQgDgDgEAAQgGAAgEADQgEAEAAAGIgfAAQABgKADgJQADgJAGgGQAHgFAIgDQAIgDAKAAQAFAAAHABQAGACAFADQAGADAEAFQADAEADAFQACAFACAGQABAGgBAGQAAAGgCAHQgDAGgEAGIgcAnIAqAAIAAAggAglXlIAAgdIAUAAIAAhSIgTAAIAAgdIA0AAIAABvIAVAAIAAAdgAgUUGQgKgEgHgGQgHgGgEgJIgEgJIgBgLIAAgyQAAgHAFgNQAEgIAHgHQAHgGAKgEQAJgCALAAQAJAAAJACQAJAEAIAGQAHAHAEAIQAEANAAAHIAAAyIgBALIgDAJQgEAJgHAGQgIAGgJAEQgJADgJAAQgLAAgJgDgAgNScQgGAEAAAIIAAAwQAAAIAGAFQAEAEAJAAQAGAAAFgEQAFgFAAgIIAAgwQAAgIgFgEQgFgFgGAAQgJAAgEAFgAgiQiIAfgyQgLAAgKgDQgIgDgHgHQgHgFgDgJQgDgJgBgJQAAgJAFgNQADgJAIgGQAGgFALgDQAJgEALAAQAKAAAKAEQAKADAHAFQAHAGAFAJQADANAAAJQABAHgCAHQgCAHgEAGIgoBEgAgMO2QgFAFAAAIQAAAHAFAFQAFAFAHAAQAIAAAEgFQAEgEAAgIQAAgIgEgFQgFgFgHAAQgHAAgFAFgAgSNFQgIgDgHgEQgGgFgFgGQgEgGgCgGQgCgHgBgHQAAgGACgIQADgGADgGQAFgGAGgEIgGgJIgDgKQgBgGABgFQABgFACgFQACgFAEgEQADgEAGgDQAFgDAHgCQAHgCAGAAQAHAAAIACQAGACAFADIAJAHQAEAEACAFQADAFAAAGQABAFgBAFQAAAFgDAFIgGAJQAGAFAEAFQAFAGACAHQABAGAAAIQAAAGgCAHQgCAGgFAHQgEAGgHAEQgGAEgJADQgIACgKAAQgJAAgJgCgAgHMIQgDAAgCADQgEAGgBAHQABAHAEAFQACACADABIAHACQAEAAADgCQAEgBACgCQAFgFgBgHQABgHgFgGQgCgDgEAAQgDgCgEAAIgHACgAgILWQgEADABAEQgBAFAEADQAEADAEAAQAGAAADgDQAEgDAAgFQAAgEgEgDQgDgDgGgBQgEABgEADgAgnJoIAshsIg1AAIAAgfIBkAAIAAAFIg2CGgAgTGMQgKgDgIgGQgHgGgEgJIgDgKIgBgLQAAgIABgHQADgHADgGIAphEIAlAAIgdAzQALgBAJADQAJACAHAHQAGAFAEAJQADAJAAALIgBALIgDAKQgEAJgIAGQgHAGgJADQgKACgLABQgJgBgKgCgAgGFPQgDABgCACQgFAFAAAIQAAAHAFAFQAFAGAGAAQAIAAAFgGQAEgFAAgHQAAgIgEgFQgFgFgIAAQgDAAgDACgAgRCwQgJgDgGgGQgGgGgEgIQgEgJAAgKIAfAAQAAAGAEAEQAFADAGAAQAGAAAEgDQAEgFABgJQgBgGgDgEQgDgDgGgBIgKgDIgkABIAAhNIBWAAIAAAeIg4AAIAAARQAOAAAIABQAMACAIAEIAIAGQAEADADAFIAEAMQACAGAAAHQAAAKgEAIQgDAJgGAHQgHAHgIAEQgNAFgIAAQgJAAgIgEgAAHgpIAAgbIg7AAIAAgQIA2hiIAnAAIAABVIALAAIAAAdIgLAAIAAAbgAgMhhIAUAAIADgqgAgNkEQgGgCgGgDIgJgHIgHgJQgDgEgCgHQgBgFAAgHIAfAAQAAAGAFAEQADAEAIgBQAFAAAEgEQAEgFABgIQgBgGgDgFQgDgDgGgDQgCgBgHAAIgMAAIAAgFIATgnIgpAAIAAgfIBXAAIAAAEIgaAwQAJACAFAEQAGAEADAGQADAFABAHQACAHAAAGQAAAJgDAJQgDAJgHAHQgGAHgJAEQgNAEgHABQgHgBgGgBgAgwniIAAgFIAyhNQADgDABgFIADgJQAAgFgDgDQgDgCgEAAQgGAAgEACQgEAEAAAHIgfAAQABgLADgJQADgIAGgGQAHgFAIgDQAIgEAKAAQAFAAAHACQAGACAFADQAGADAEAEQADAEADAGQACAFACAFQABAGgBAGQAAAHgCAGQgDAHgEAFIgcAnIAqAAIAAAggAglq9IAAgeIAUAAIAAhSIgTAAIAAgcIA0AAIAABuIAVAAIAAAegAgUudQgKgDgHgGQgHgHgEgJIgEgJIgBgLIAAgxQAAgIAFgNQAEgIAHgHQAHgFAKgEQAJgDALAAQAJAAAJADQAJAEAIAFQAHAHAEAIQAEANAAAIIAAAxIgBALIgDAJQgEAJgHAHQgIAGgJADQgJADgJAAQgLAAgJgDgAgNwHQgGAFAAAIIAAAwQAAAHAGAFQAEAFAJAAQAGAAAFgFQAFgFAAgHIAAgwQAAgIgFgFQgFgEgGAAQgJAAgEAEgAgix2IAfgzQgLAAgKgCQgIgEgHgGQgHgGgDgJQgDgIgBgKQAAgIAFgNQADgKAIgFQAGgGALgDQAJgDALAAQAKAAAKADIAIADIAJAGQAHAFAFAKQADANAAAIQABAIgCAHQgCAHgEAFIgoBFgAgMziQgFAFAAAHQAAAIAFAEQAFAGAHAAQAIgBAEgEQAEgEAAgJQAAgHgEgFQgFgGgHAAQgHAAgFAGgAgS1UQgIgDgHgEQgGgFgFgGQgEgFgCgGQgCgHgBgIQAAgGACgHQADgGADgHQAFgFAGgFIgGgJIgDgKQgBgFABgFQABgGACgEQACgGAEgDQADgFAGgCQAFgEAHgCQAHgCAGAAQAHAAAIACQAGACAFAEIACABIAHAGQAEAEACAFQADAFAAAFQABAFgBAFQAAAFgDAFIgGAJQAGAFAEAGQAFAFACAIQABAGAAAHQAAAHgCAHQgCAGgFAGQgEAGgHAEIgFADIgKAEQgIADgKgBQgJABgJgDgAgH2RQgDABgCADQgEAFgBAHQABAHAEAFQACADADABIAHABQAEAAADgBQAEgBACgDQAFgFgBgHQABgHgFgFQgCgDgEgBQgDgBgEgBIgHACgAgI3CQgEADABAEQgBAEAEADQAEAEAEAAQAGAAADgEQAEgDAAgEQAAgEgEgDQgDgEgGAAQgEAAgEAEgAgn4wIAshsIg1AAIAAggIBkAAIAAAGIg2CGgAgT8NQgKgDgIgGQgHgFgEgKIgDgKIgBgLQAAgHABgIQADgHADgFIAphEIAlAAIgdAyQALgBAJADIAEACQAGACAGAFQAGAGAEAJQADAIAAALIgBALIgDAKQgEAKgIAFIgJAHIgHACQgKADgLAAQgJAAgKgDgAgG9KQgDABgCADQgFAFAAAHQAAAIAFAEQAFAGAGAAQAIAAAFgGQAEgEAAgIQAAgHgEgFQgFgGgIAAQgDABgDABgAgR/oQgJgEgGgFQgGgGgEgJQgEgJAAgKIAfAAQAAAHAEADQAFAEAGAAQAGAAAEgEQAEgEABgJQgBgGgDgEQgDgEgGgBIgKgCIgkABIAAhOIBWAAIAAAeIg4AAIAAASQAOgBAIABQAMACAIAEIAIAHQAEADADAFIAEALQACAGAAAIQAAAJgEAJQgDAJgGAGQgHAIgIADQgNAFgIAAQgJAAgIgDgEAAHgjEIAAgbIg7AAIAAgPIA2hiIAnAAIAABUIALAAIAAAdIgLAAIAAAbgEgAMgj8IAUAAIADgqgEgANgmeQgGgCgGgDIgJgHIgHgJQgDgFgCgGQgBgGAAgHIAfAAQAAAHAFADQADAEAIAAQAFAAAEgFQAEgEABgIQgBgHgDgFQgDgDgGgCQgCgBgHAAIgMAAIAAgGIATgmIgpAAIAAggIBXAAIAAAFIgaAvQAJADAFAEQAGADADAHQADAFABAGQACAHAAAHQAAAJgDAJQgDAIgHAHQgGAHgJAFQgNAEgHAAQgHAAgGgBgEgAwgp8IAAgFIAyhOQADgDABgFIADgJQAAgFgDgCQgDgDgEAAQgGAAgEADQgEADAAAIIgfAAQABgLADgKQADgHAGgGQAHgGAIgDQAIgDAKAAQAFAAAHACQAGABAFADQAGADAEAEQADAEADAGQACAFACAGQABAGgBAGQAAAHgCAFQgDAHgEAGIgcAnIAqAAIAAAggEgAlgtYIAAgdIAUAAIAAhSIgTAAIAAgdIA0AAIAABvIAVAAIAAAdgEgAUgw4QgKgCgHgHQgHgGgEgJIgEgKIgBgLIAAgwQAAgIAFgNQAEgIAHgHQAHgGAKgDQAJgEALAAQAJAAAJAEQAJADAIAGQAHAHAEAIQAEANAAAIIAAAwIgBALIgDAKQgEAJgHAGQgIAHgJACQgJAEgJAAQgLAAgJgEgEgANgyiQgGAFAAAJIAAAvQAAAIAGAEQAEAFAJAAQAGAAAFgFQAFgEAAgIIAAgvQAAgJgFgFQgFgDgGAAQgJAAgEADg");
	this.shape.setTransform(0.2,99.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.2,-227.5,10.8,654.2);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.529,1],-40.7,-31.5,40.8,31.5).s().p("AwdIJIUM6HIMvJ2I0MaHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-105.5,-115.2,211,230.4);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11.7,0,11.7).s().p("AgnBuIAAgWIh0AAIAAAWIgpAAIAAhCIAUAAIBDiZIAVAAIBFCZIATAAIAAAkIBXi9IAWAAIBYC9IAAAHIgxAAIgyhwIgyBwIgwAAIAAAXgAh9ArIA3AAIgdhEg");
	this.shape.setTransform(-146.9,15.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11.2,0,11.2).s().p("AAgBhIAAg5IgaAAIgfA5Ig4AAIAAgHIAmg+QgJgGgHgJQgFgJgEgIQgDgKgBgKQAAgLADgKQACgLAGgJQAGgJAHgHQAKgHALgEQALgEAOAAIBUAAIAADBgAgSgsQgEAHAAAKQAAAKAFAGQAGAIAJAAIAiAAIAAgwIgiAAQgJAAgHAHg");
	this.shape_1.setTransform(-118.3,14.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.9,0,11).s().p("AhKBhIAAjBIBRAAQAMAAALAFQALAEAJAIQAIAJAFAKQAEALAAANQAAAJgEAJQgFAKgGAFQAMAFAGAKQAGAKAAAOQAAAMgFALQgDALgIAJQgJAJgKAEQgMAFgOAAgAgbA0IAmAAQAHAAAFgEQADgFAAgHQAAgHgDgEQgFgFgHAAIgmAAgAgbgUIAeAAQAHAAAEgFQADgEAAgGQAAgHgDgFQgEgEgHAAIgeAAg");
	this.shape_2.setTransform(-89.9,14.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11.6,0,11.7).s().p("AgfBgQgNgEgIgJQgJgIgFgNQgEgMAAgQIArAAQAAALAHAHQAHAHALAAQAKAAAHgHQAGgHAAgJQAAgJgGgGQgHgHgKAAIgOAAIAAgmIANAAQAHAAAEgGQAFgFAAgHQAAgHgEgEQgFgFgGAAQgIAAgFACQgEAEAAAFIgtAAQgBgNAFgKQAFgKAIgHQAJgGAMgEQALgCANAAQANAAANAEQAMAFAIAIQAIAIAEAKQAEAKAAALQAAAKgEAJQgFALgIAGQAHAEAFADQAGAFADAGQAEAGABAHQACAHAAAIQAAANgFAMQgFALgJAIQgJAIgOAFQgPAEgQAAQgQAAgNgEg");
	this.shape_3.setTransform(-72.6,14.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-9.9,0,10).s().p("AhMBhIAAjBIBUAAQAXAAAdAXQAIAKAFANQAEANAAANQAAAOgEAMQgFAMgIALQgJAKgNAGQgHADgHABIgQACIgjAAIAAAygAgbACIAiAAQAKAAAGgGQAFgIAAgMQAAgLgFgHQgCgFgEgCQgFgCgFAAIgiAAg");
	this.shape_4.setTransform(-54,14.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10,0,10.1).s().p("AgjBeQgKgDgHgFQgJgEgGgGIgNgPQgGgIgEgJQgEgKgCgLQgDgLAAgMQAAhCBjgiQAMAAAYAGQAJAEAIAFIAPALQAHAGAGAIQAGAIAEAJQAEAKACAKQADAMAAALQAABChkAjQgYgCgLgFgAgRgwQgIADgHAHQgHAHgEAJQgEAKAAAMQAAAMAEALQAEAJAHAHQAHAHAIADQAJAEAIAAQAJAAAJgEQAJgDAHgHQAGgHAEgJQAEgLAAgMQAAgMgEgKQgEgJgGgHQgHgHgJgDQgJgDgJAAQgIAAgJADg");
	this.shape_5.setTransform(-33.7,14.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-9.6,0,9.6).s().p("AgNBiIgSgFIgRgIQgIgFgHgGQgHgGgGgIQgGgIgEgJQgEgJgDgLQgCgLAAgMQAAgKACgLQADgMAEgJQAEgJAGgIQAGgIAHgGQAHgGAIgFQAIgFAJgDIASgFIAQgBQAQAAAPAEQAPAEANAJQAQAOAFAJQAFAHADAJIAEASIgwAAQgEgHgEgGIgJgJQgFgDgHgCQgHgCgIAAQgIAAgJAEQgJAEgHAIQgGAGgEAKQgDALAAAKQAAAKADAKQAEAKAGAHQAHAIAJAEQAJAFAIAAQAIAAAIgCQAGgCAGgFQAFgDAEgGQAFgGACgIIAwAAQgBAKgCAJQgDAJgFAHIgKANQgFAHgGAEQgNAJgPAFQgPAEgRAAg");
	this.shape_6.setTransform(-11.5,14.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.5,0,10.5).s().p("Ag9BhIAAjBIB4AAIAAAtIhGAAIAAAcIBAAAIAAAqIhAAAIAAAhIBIAAIAAAtg");
	this.shape_7.setTransform(-69.6,-16.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.5,0,10.5).s().p("AgnBtIAAgVIh0AAIAAAVIgpAAIAAhBIAUAAIBCiYIAWAAIBFCYIATAAIAAAkIBXi8IAVAAIBZC8IAAAHIgxAAIgMgYIhMAAIgMAYIgwAAIAAAWgAh+ArIA3AAIgchEgABMAUIAsAAIgWgxg");
	this.shape_8.setTransform(-34.2,-15.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.5,0,10.5).s().p("Ag8BhIAAjBIB3AAIAAAtIhGAAIAAAcIBAAAIAAAqIhAAAIAAAhIBIAAIAAAtg");
	this.shape_9.setTransform(-105.6,-16.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.5,0,10.5).s().p("AhMBhIAAjBICJAAIAAAtIhYAAIAAAXIAiAAQANABASAFQAMAFAJAJQAJAIAFAKQAEALAAAMQAAAMgEAMQgFAMgJAIQgJAJgMAGQgSAFgNAAgAgbA0IAiAAQAJABAHgHQAFgEAAgJQAAgHgGgFQgGgHgJAAIgiAAg");
	this.shape_10.setTransform(-87.3,-16.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.2,0,10.3).s().p("AgXBhIAAjBIAvAAIAADBg");
	this.shape_11.setTransform(-142.5,-16.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.2,0,10.3).s().p("AgXBhIAAiUIgwAAIAAgtICPAAIAAAtIgvAAIAACUg");
	this.shape_12.setTransform(-122.1,-16.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.5,0,10.5).s().p("AhMBhIAAjBIAxAAIAAA6IAjAAQALABATAFQANAGAIAJQAJAKAFALQAEAMAAANQAAANgEAMQgFAMgJAKQgIAKgNAFQgTAGgLAAgAgbA0IAhAAQALABAFgIQAHgGAAgKQgBgKgGgGQgFgIgLAAIghAAg");
	this.shape_13.setTransform(-156.4,-16.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0.1,-9.5,0.1,9.5).s().p("AAsBhIAAhXIgpAsIgDAAIgrgsIAABXIgzAAIAAjBIATAAIBLBVIBOhVIAQAAIAADBg");
	this.shape_14.setTransform(-178.7,-16.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-9.8,0,9.9).s().p("AAyBiIgyhwIgxBwIgwAAIAAgHIBXi8IAUAAIBYC8IAAAHg");
	this.shape_15.setTransform(9.3,14.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0.1,-10,0.1,10.1).s().p("AgjBeQgJgDgIgFQgIgEgHgGQgHgHgGgIQgFgIgFgJQgEgKgCgLQgDgLAAgMQAAhCBjgiQAMAAAYAGQAJAEAIAFQAJAFAGAGQAHAGAGAIQAGAIAEAJQAEAKACAKQADAMAAALQAABChkAjQgXgCgMgFgAgRgwQgIADgHAHQgHAHgEAJQgEAKAAAMQAAAMAEALQAEAJAHAHQAHAHAIADQAKAEAHAAQAJAAAJgEQAJgDAHgHQAHgHADgJQAEgLAAgMQAAgMgEgKQgDgJgHgHQgHgHgJgDQgJgDgJAAQgHAAgKADg");
	this.shape_16.setTransform(30.4,14.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.4,0,10.5).s().p("AAgBhIAAhgIhgBgIgSAAIAAjAIAzAAIAABfIBghgIASAAIAADBg");
	this.shape_17.setTransform(52.7,14.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.7,0,10.7).s().p("AAgBhIAAhgIhgBgIgSAAIAAjAIAyAAIAABfIBhhgIASAAIAADBg");
	this.shape_18.setTransform(82,14.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.4,0,10.5).s().p("Ag7BhIAAjBIB3AAIAAAtIhFAAIAACUg");
	this.shape_19.setTransform(101.4,14.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.4,0,10.5).s().p("AhMBhIAAjBIBTAAQAYAAAdAXQAIAKAFANQAEANAAANQAAAOgEAMQgFAMgIALQgKAKgMAGQgHADgIABQgHACgJAAIgiAAIAAAygAgbACIAhAAQAKAAAHgGQAEgIACgMQgBgLgFgHQgCgFgFgCQgDgCgHAAIghAAg");
	this.shape_20.setTransform(118.7,14.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-9.4,0,9.5).s().p("AgYBhIAAjBIAxAAIAADBg");
	this.shape_21.setTransform(151.9,14.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11.2,0,11.2).s().p("AhMBhIAAjBIAxAAIAAA7IAiAAQAMAAATAFQANAGAJAJQAIAKAFALQAEAMAAANQAAANgEAMQgFAMgIAJQgJALgNAFQgTAGgMAAgAgbA0IAiAAQAKAAAGgHQAFgHAAgJQAAgKgFgGQgHgIgJAAIgiAAg");
	this.shape_22.setTransform(137.9,14.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0.1,-7.7,0.1,7.8).s().p("AgWBFIgFiJIA2AAIgDCJg");
	this.shape_23.setTransform(161.8,11.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-2.7,0,2.8).s().p("AgSASQgIgHAAgLQAAgFACgFQACgDAEgEQAIgHAKAAQALAAAIAHIAGAHQACAFAAAFQAAALgIAHQgIAHgLAAQgKAAgIgHg");
	this.shape_24.setTransform(161.8,21.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11,0,11).s().p("AhMBhIAAjBIAxAAIAAA6IAiAAQAMABATAFQAMAGAKAJQAIAKAFALQAEAMAAANQAAANgEAMQgFAMgIAKQgKAKgMAFQgTAGgMAAgAgbA0IAhAAQALABAGgIQAFgGABgKQgCgKgEgGQgHgIgKAAIghAAg");
	this.shape_25.setTransform(171.8,-16.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11.5,0,11.5).s().p("AgXBhIAAjBIAvAAIAADBg");
	this.shape_26.setTransform(185.7,-16.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11.2,0,11.3).s().p("AgNBhIgSgEQgKgDgHgFQgIgEgHgHIgNgOQgGgIgEgKQgFgIgCgLQgCgLAAgMQAAgKACgLQACgMAFgJQAEgJAGgIIANgOQAHgGAIgFQAHgFAKgDIASgEIAQgCQAQAAAPAEQAPAFANAIQAPAOAGAKIAIAPQADAIABAKIgxAAQgDgHgEgGQgEgFgFgEQgGgEgGgBIgPgCQgIABgKAEQgJADgGAHQgGAIgEAJQgDALAAAKQAAAKADAKQAEAKAGAHQAGAIAJAEQAKAFAIAAQAIAAAIgDQAGgCAGgDQAFgEAEgHQAEgFADgIIAwAAIgEATIgHARIgKAMQgFAHgHAEQgNAJgOAFQgPAEgRAAg");
	this.shape_27.setTransform(150.6,-16.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11,0,11).s().p("Ag2BhIAAgFIAfg/IhCh1IAAgIIA3AAIAjBIIACAAIAhhIIA2AAIAAAIIhaC5g");
	this.shape_28.setTransform(130.3,-16.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11.2,0,11.3).s().p("AAeBhIAAhOIg7AAIAABOIgzAAIAAjBIAzAAIAABHIA7AAIAAhHIAzAAIAADBg");
	this.shape_29.setTransform(110.6,-16.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11.7,0,11.8).s().p("AgjBfQgJgEgIgFQgIgEgHgGIgNgPQgFgHgFgKQgEgKgCgKQgDgMAAgMQAAhCBjgiQAMAAAYAHIARAIQAIAFAHAGQAHAGAGAIQAGAIAEAJQAEAKACALQADALAAALQAABDhkAiQgXgCgMgEgAgRgwQgIADgHAHQgHAHgEAJQgEALAAALQAAANAEAKQAEAKAHAHQAHAGAIADQAKAEAHAAQAJAAAJgEQAJgDAHgGQAHgHADgKQAEgKAAgNQAAgLgEgLQgDgJgHgHQgHgHgJgDQgJgDgJAAQgHAAgKADg");
	this.shape_30.setTransform(88.7,-16.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11.2,0,11.3).s().p("AhMBhIAAjBICKAAIAAAtIhYAAIAAAXIAiAAQALABATAFQANAFAJAJQAIAIAFAKQAEALAAAMQAAAMgEAMQgFAMgIAIQgJAJgNAGQgTAFgLAAgAgaA0IAhAAQAKABAGgHQAEgEAAgJQAAgHgFgFQgFgHgKAAIghAAg");
	this.shape_31.setTransform(68.4,-16.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-3,0,3).s().p("AgTAVQgJgDgGgFQgGgGgEgIQgDgIAAgMIAcgDQABAHAFAFQAFAEAIAAQAIgBAFgDQAFgDACgJIAcADQgBAMgDAIQgDAIgGAGQgGAFgJADQgJAEgLAAQgKAAgJgEg");
	this.shape_32.setTransform(53.5,1.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-11,0,11).s().p("AhMBhIAAjBIBTAAQAXAAAeAXQAIAKAFANQAEANAAAOQAAAOgEALQgFAMgIAKQgKALgMAGIgPAFQgHABgJAAIgiAAIAAAygAgbADIAiAAQAJAAAHgHQAFgJABgKQAAgMgGgHQgCgFgFgBQgEgDgFAAIgiAAg");
	this.shape_33.setTransform(-4.2,-16.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0.1,-10.5,0.1,10.5).s().p("AAsBhIAAhXIgpAsIgEAAIgqgsIAABXIgyAAIAAjBIATAAIBKBVIBOhVIARAAIAADBg");
	this.shape_34.setTransform(38.5,-16.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.lf(["#C19600","#FDE08D","#C19600"],[0,0.529,1],0,-10.7,0,10.8).s().p("AAgBhIAAhgIhgBgIgSAAIAAjBIAyAAIAABgIBhhgIASAAIAADBg");
	this.shape_35.setTransform(15.7,-16.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-188.2,-26.3,376.5,52.7);


(lib.Слой3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dfdfdfd();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,127,91);


(lib.Слой2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sjsjsjs();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,255,243);


(lib.Прямоугольник1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Egu3AXbMAAAgu2MBdvAAAMAAAAu2g");
	mask.setTransform(300,150);

	// Слой 1
	this.instance = new lib.safasfgasf();

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.Layer9_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 9
	this.instance = new lib.Layer9();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,581,170);


(lib.Layer6copy4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Layer6copy4();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,105,95);


(lib.Layer6copy3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Layer6copy3();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,130,134);


(lib.Layer6copy2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Layer6copy2();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,127,115);


(lib.Layer6_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Layer6();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,127,115);


(lib.flares__12__1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.flares__12_();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1199,805);


(lib.Символ64 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 68
	this.instance = new lib.Символ68();
	this.instance.setTransform(92.5,-104.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(7).to({y:-43.9},7).to({scaleY:0.64,y:-41.3},2).to({scaleY:1,y:-56.9},7,cjs.Ease.get(1)).to({y:-43.9},9,cjs.Ease.get(-1)).to({y:-50.4},9,cjs.Ease.get(1)).to({y:-41.3},11,cjs.Ease.get(-1)).wait(47).to({scaleX:0.69,scaleY:0.79,x:99.4},6).to({scaleX:0.97,x:-303.9},11).wait(1));

	// Символ 67
	this.instance_1 = new lib.Символ67();
	this.instance_1.setTransform(-37.8,-104.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({y:-43.9},7).to({scaleY:0.64,y:-41.3},2).to({scaleY:1,y:-56.9},7,cjs.Ease.get(1)).to({y:-43.9},9,cjs.Ease.get(-1)).to({y:-50.4},9,cjs.Ease.get(1)).to({y:-41.3},11,cjs.Ease.get(-1)).wait(49).to({scaleX:0.84,scaleY:1.16,x:7.6},6).to({scaleX:1.19,x:-433.5},11).wait(1));

	// Символ 66
	this.instance_2 = new lib.Символ66();
	this.instance_2.setTransform(-120.8,-104.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(3).to({y:-43.9},7).to({scaleY:0.64,y:-41.3},2).to({scaleY:1,y:-56.9},7,cjs.Ease.get(1)).to({y:-43.9},9,cjs.Ease.get(-1)).to({y:-50.4},9,cjs.Ease.get(1)).to({y:-41.3},11,cjs.Ease.get(-1)).wait(51).to({regX:0.1,scaleX:0.59,scaleY:0.85,x:-49.1,y:-41.1},6).to({regX:0,scaleX:0.83,x:-513.4},11).wait(1));

	// Символ 65
	this.instance_3 = new lib.Символ65();
	this.instance_3.setTransform(-157.8,-104.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1).to({y:-43.9},7).to({scaleY:0.64,y:-41.3},2).to({scaleY:1,y:-56.9},7,cjs.Ease.get(1)).to({y:-43.9},9,cjs.Ease.get(-1)).to({y:-50.4},9,cjs.Ease.get(1)).to({y:-41.3},11,cjs.Ease.get(-1)).wait(53).to({scaleX:1.18,scaleY:1.66,x:-69.2},6).to({scaleX:1.67,x:-541.7},11).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-164.3,-112.2,328.7,14.6);


(lib.Символ61 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ60();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.4,-85.3,104.9,170.7);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADlAxIgJgEIgIgGIgHgIIgFgJIgDgKQgBgGAAgGQAAgiA0gSQAGABANADIAJAFIAIAFIAGAHQAEAFABAEQADAGABAFQABAGAAAFQAAAig0ATQgNgCgGgCgADugZIgIAGQgDADgCAGQgDAFAAAFQAAAGADAFQACAGADADIAIAGQAFACAFgBQAFABAEgCQAFgDAEgDQADgDACgGQACgFAAgGQAAgFgCgFQgCgGgDgDQgEgDgFgDQgEgBgFAAIgKABgApXAyQgHgCgEgFQgFgFgCgGQgDgGAAgJIAXAAQAAAGAEAEQADADAGAAQAGAAAEgDQADgEAAgEQAAgFgDgEQgEgDgGAAIgHAAIAAgTIAHAAQAEAAADgDQACgDAAgDQAAgEgCgCQgDgDgEAAQgEAAgDACQgCABAAADIgXAAQgBgGADgGQACgFAFgEQAEgDAGgCQAGgBAHgBQAIABAHACQAGACAEAFQAEAEACAFQACAFAAAGQAAAFgCAFQgCAGgFADIAHADIAFAFIACAHIABAIQAAAHgCAGQgDAGgFAEQgFAEgHACQgIADgJAAQgIAAgHgCgAIzAzIgJgDIgJgEIgIgGIgHgHIgFgJIgDgLIgBgLIABgKIADgMIAFgJIAHgGIAIgGIAJgFIAJgCIAJgBQAJAAAHACQAIADAHAEQAIAIADAEIAEAIIACAKIgZAAIgEgGIgEgGIgHgCIgIgBQgFAAgFACQgEACgEAEQgDADgCAGQgCAFAAAFQAAAFACAFQACAFADAEQAEAEAEACQAFACAFAAIAIAAQAEgBADgCIAFgGQACgDABgEIAaAAIgCAKIgEAIIgGAIIgGAFQgGAEgIADQgIACgJAAgAG0AyIAAgDIAQggIgig8IAAgFIAdAAIATAmIABAAIARgmIAdAAIAAAFIgxBfgAF6AyIAAgpIggAAIAAApIgaAAIAAhkIAaAAIAAAlIAgAAIAAglIAaAAIAABkgABmAyIAAhkIBJAAIAAAYIgwAAIAAAMIATAAQAGAAAKADQAHACAEAFQAFAEACAFQADAFAAAHQAAAGgDAGQgCAGgFAEQgEAFgHADQgKADgGAAgAB/AbIATAAQAFAAADgDQADgDAAgEQAAgEgDgDQgDgDgFAAIgTAAgAglAyIAAhkIAaAAIAAAfIARAAQAGAAAKADQAGADAFAFQAEAFADAEQACAHAAAHQAAAHgCAFQgDAHgEAFQgFAFgGADQgKADgGAAgAgLAbIAQAAQAGAAADgEQADgDAAgFQgBgGgCgDQgEgEgFAAIgQAAgAhnAyIAAhMIgZAAIAAgYIBLAAIAAAYIgZAAIAABMgAidAyIgGgNIgoAAIgGANIgZAAIAAgEIAthhIAMAAIAuBhIAAAEgAirAQIgMgZIgLAZIAXAAgAlCAyIAAhkIAtAAQAMABAPAMQAEAEADAIQACAGAAAHQAAAHgCAFQgDAHgEAFQgFAGgGADIgIADIgIAAIgTAAIAAAagAkoABIASAAQAGAAADgCQACgFABgGQAAgFgDgFIgDgDQgDgCgDABIgSAAgAmmAyIAAhkIBJAAIAAAYIgwAAIAAAMIATAAQAGAAAKADQAHACAEAFQAFAEACAFQADAFAAAHQAAAGgDAGQgCAGgFAEQgEAFgHADQgKADgGAAgAmNAbIATAAQAFAAADgDQADgDAAgEQAAgEgDgDQgDgDgFAAIgTAAgAnNAyIgGgNIgoAAIgGANIgaAAIAAgEIAuhhIALAAIAvBhIAAAEgAnbAQIgMgZIgMAZIAYAAg");
	this.shape.setTransform(1.6,0.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.instance = new lib.Символ40();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ42();
	this.instance_1.setTransform(1.2,24.8,0.959,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-94,-24,188.2,63.8);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ30();
	this.instance.filters = [new cjs.BlurFilter(4, 4, 1)];
	this.instance.cache(-304,-154,608,308);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-304.1,-154.1,612,312);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Прямоугольник1();
	this.instance.setTransform(0,0,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-300,-150,600,300);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 32
	this.instance = new lib.Символ32();
	this.instance.setTransform(-12.9,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(250));

	// Символ 31
	this.instance_1 = new lib.Символ31();
	this.instance_1.setTransform(23.8,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(19).to({y:-21.4},5).wait(20).to({y:-44.3},5).wait(20).to({y:-66.1},5).wait(20).to({y:-88.1},5).wait(20).to({y:-110.2},5).wait(20).to({y:-132},5).wait(20).to({y:-154},5).wait(20).to({y:-176.1},5).wait(19).to({y:-198.1},6).wait(26));

	// Символ 25
	this.instance_2 = new lib.Символ25();
	this.instance_2.setTransform(37.4,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-220.9},24).wait(1).to({y:0.2},0).to({y:-220.9},24).wait(1).to({y:0.2},0).to({y:-220.9},24).wait(1).to({y:0.2},0).to({y:-220.9},24).wait(1).to({y:0.2},0).to({y:-220.9},24).wait(1).to({y:0.2},0).to({y:-220.9},24).wait(1).to({y:0.2},0).to({y:-220.9},24).wait(1).to({y:0.2},0).to({y:-220.9},24).wait(1).to({y:0.2},0).to({y:-220.9},24).wait(1).to({y:0.2},0).to({y:-198.3},24).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-42.1,-426.2,85.1,853.1);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.flares__12__1();
	this.instance.setTransform(0,0,1,1,0,0,0,599.5,402.5);
	this.instance.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-599.5,-402.5,1199,805);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Layer9_1();
	this.instance.setTransform(0,0,1,1,0,0,0,290.5,85);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-290.5,-85,581,170);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Layer6_1();
	this.instance.setTransform(0,0,1,1,0,0,0,63.5,57.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:100.2,y:-239.3},64,cjs.Ease.get(-1)).to({x:201.9,y:-482.3},65,cjs.Ease.get(0.86)).to({x:104.1,y:-248.5},63,cjs.Ease.get(-1)).to({x:0,y:0},67,cjs.Ease.get(0.86)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.5,-57.5,127,115);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Layer6copy2_1();
	this.instance.setTransform(295.6,57.5,1,1,0,0,0,63.5,57.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-8.7,y:-95.3},49,cjs.Ease.get(-1)).to({x:-319.1,y:-251.2},50,cjs.Ease.get(1)).to({x:-5.6,y:-93.7},51,cjs.Ease.get(-1)).to({x:295.6,y:57.5},49,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(232.1,0,127,115);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Layer6copy3_1();
	this.instance.setTransform(0,0,1,1,0,0,0,65,67);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:482.2,y:25.7},24,cjs.Ease.get(-1)).to({x:984.4,y:52.5},25,cjs.Ease.get(1)).to({x:405.3,y:21.6},25,cjs.Ease.get(-1)).to({x:0,y:0},26,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65,-67,130,134);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Layer6copy4_1();
	this.instance.setTransform(0,0,1,1,0,0,0,52.5,47.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.5,-47.5,105,95);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A3kEHIAAgVIhzAAIAAAVIgpAAIAAhBIATAAIBDibIAWAAIBFCbIAUAAIAAAjIBYi+IAVAAIBYC+IAAAIIgwAAIgyhzIgyBzIgxAAIAAAWgA46DFIA3AAIgchHgAELDvQgJgEgIgFIAAAAQgIgEgHgGIAAAAQgHgHgFgIIAAAAQgGgHgEgKIAAAAQgEgKgCgKIAAAAQgDgMAAgNIAAAAQAAhDBkghIAAAAQANgBAYAHIAAAAQAJADAIAFIAAAAQAIAFAHAGIAAAAQAHAHAFAHIAAAAQAHAJADAIIAAAAQAEAKACAKIAAAAQADANAAALIAAAAQAABEhkAiIAAAAQgZgCgMgEgAEeBeQgIADgHAIIAAAAQgHAGgEAKIAAAAQgFAJAAANIAAAAQAAAOAFAKIAAAAQAEAKAHAHIAAAAQAHAGAIAEIAAAAQAJADAJAAIAAAAQAKAAAIgDIAAAAQAJgEAHgGIAAAAQAHgHAEgKIAAAAQAEgKAAgOIAAAAQAAgNgEgJIAAAAQgEgKgHgGIAAAAQgHgIgJgDIAAAAQgIgDgKAAIAAAAQgJAAgJADgAl0DvQgKgEgHgFIAAAAQgJgEgGgGIAAAAIgNgPIAAAAQgGgHgEgKIAAAAQgEgKgCgKIAAAAQgDgMAAgNIAAAAQAAhDBkghIAAAAQANgBAYAHIAAAAQAJADAIAFIAAAAIAPALIAAAAQAHAHAGAHIAAAAQAGAJAEAIIAAAAQAEAKACAKIAAAAQADANAAALIAAAAQAABEhlAiIAAAAQgZgCgLgEgAliBeQgIADgHAIIAAAAQgHAGgEAKIAAAAQgEAJAAANIAAAAQAAAOAEAKIAAAAQAEAKAHAHIAAAAQAHAGAIAEIAAAAQAJADAJAAIAAAAQAKAAAJgDIAAAAQAJgEAHgGIAAAAQAGgHAEgKIAAAAQAEgKAAgOIAAAAQAAgNgEgJIAAAAQgEgKgGgGIAAAAQgHgIgJgDIAAAAQgJgDgKAAIAAAAQgJAAgJADgAr1DwQgNgEgIgJIAAAAQgJgJgFgMIAAAAQgEgMAAgQIAAAAIArAAQAAALAHAHIAAAAQAHAGALABIAAAAQAMgBAHgGIAAAAQAGgHAAgJIAAAAQAAgJgGgGIAAAAQgHgHgMAAIAAAAIgOAAIAAgpIANAAQAJABAEgGIAAAAQAFgFAAgHIAAAAQAAgHgEgEIAAAAQgFgGgIAAIAAAAQgIAAgFADIAAAAQgEADAAAGIAAAAIgtAAQgBgNAFgLIAAAAQAFgJAIgHIAAAAQAJgHAMgDIAAAAQALgDANABIAAAAQAPAAANAEIAAAAQAMAEAIAJIAAAAQAIAIAEAKIAAAAQAEAJAAALIAAAAQAAALgEAJIAAAAQgFALgIAGIAAAAQAHAEAFAFIAAAAQAGAFADAFIAAAAQAEAHABAHIAAAAQACAGAAAJIAAAAQAAANgFALIAAAAQgFALgJAJIAAAAQgJAIgOAFIAAAAQgPAEgSAAIAAAAQgQAAgNgEgAiADyIgSgGIAAAAIgRgHIAAAAQgIgFgHgHIAAAAQgHgFgGgIIAAAAQgGgIgEgJIAAAAQgEgKgDgKIAAAAQgCgLAAgNIAAAAQAAgMACgKIAAAAQADgMAEgKIAAAAQAEgIAGgJIAAAAQAGgHAHgGIAAAAQAHgGAIgFIAAAAQAIgFAJgDIAAAAIASgFIASgBQAQAAAPAEIAAAAQAPAEAMAJIAAAAQAQAOAGAJIAAAAQAEAHAEAIIAAAAIAEASIAAAAIgxAAQgDgGgEgGIAAAAIgJgJIAAAAQgGgEgGgCIAAAAQgHgBgIAAIAAAAQgLAAgJAEIAAAAQgJADgGAJIAAAAQgGAGgEAKIAAAAQgDALAAALIAAAAQAAALADAJIAAAAQAEALAGAHIAAAAQAGAHAJAFIAAAAQAJAFALAAIAAAAQAIAAAHgCIAAAAQAHgCAGgFIAAAAQAFgDAEgGIAAAAQAFgGACgIIAAAAIAwAAQgBAKgDAJIAAAAQgCAIgFAIIAAAAIgKANIAAAAQgFAHgHAEIAAAAQgMAJgQAFIAAAAQgOAEgRAAIAAAAgAXVDxIAAjDIAzAAIAADDgAUVDxIAAjDIAyAAIAAA7IAkAAQAMgBATAGIAAAAQAMAFAJAKIAAAAQAIAKAFANIAAAAQAFALAAANIAAAAQAAANgFANIAAAAQgFAMgIAJIAAAAQgJALgMAEIAAAAQgTAHgMAAIAAAAgAVHDEIAjAAQALAAAFgIIAAAAQAGgGAAgKIAAAAQgBgJgFgGIAAAAQgGgIgKAAIAAAAIgjAAgARVDxIAAjDIBVAAQAXAAAdAXIAAAAQAJAJAFANIAAAAQAEAOAAANIAAAAQAAAOgEANIAAAAQgFANgJALIAAAAQgJAKgMAGIAAAAQgHADgIABIAAAAQgHACgJgBIAAAAIgkAAIAAAzgASGCSIAjAAQAKAAAGgJIAAAAQAFgHABgMIAAAAQAAgLgGgIIAAAAQgCgEgEgCIAAAAQgEgCgGgBIAAAAIgjAAgAO5DxIAAjDIB5AAIAAAsIhHAAIAACXgANUDxIAAhhIhiBhIgSAAIAAjDIAyAAIAABfIBjhgIASAAIAADEgAIvDxIAAhhIhiBhIgSAAIAAjDIAzAAIAABfIBjhgIASAAIAADEgACPDxIgyhzIgzBzIguAAIAAgIIBVi+IAWAAIBYC+IAAAIgApoDxIAAjDIBWAAQAXAAAdAXIAAAAQAIAJAFANIAAAAQAEAOAAANIAAAAQAAAOgEANIAAAAQgFANgIALIAAAAQgJAKgNAGIAAAAQgHADgHABIAAAAIgQABIAAAAIglAAIAAAzgAo3CSIAkAAQAKAAAGgJIAAAAQAFgHAAgMIAAAAQAAgLgFgIIAAAAQgCgEgEgCIAAAAQgFgCgFgBIAAAAIgkAAgAvNDxIAAjDIBTAAQAMAAALAFIAAAAQAMAEAIAIIAAAAQAIAIAFALIAAAAQAEALAAANIAAAAQAAAJgDAJIAAAAQgFAKgHAFIAAAAQAMAHAGAKIAAAAQAGAKAAAOIAAAAQAAAMgFALIAAAAQgDALgIAJIAAAAQgIAJgLAEIAAAAQgLAEgPABIAAAAgAudDEIAoAAQAHAAAEgFIAAAAQADgFAAgGIAAAAQAAgHgDgEIAAAAQgEgFgHgBIAAAAIgoAAgAudB6IAfAAQAHAAAEgFIAAAAQAEgFAAgFIAAAAQAAgHgEgFIAAAAQgEgEgHgBIAAAAIgfAAgAx9DxIAAg5IgaAAIghA5Ig4AAIAAgIIAmg9QgJgHgHgIIAAAAQgFgJgEgLIAAAAQgDgJgBgLIAAAAQAAgKADgKIAAAAQACgLAGgJIAAAAQAGgJAHgHIAAAAQAKgHALgEIAAAAQALgEAOAAIAAAAIBWAAIAADDgAyxBiQgEAHAAAKIAAAAQAAAKAFAGIAAAAQAGAIAJAAIAAAAIAkAAIAAgxIgkAAQgJAAgHAIgAY+DpQgIgIAAgLIAAAAQAAgGACgFIAAAAQACgEAEgDIAAAAQAIgIAMAAIAAAAQALAAAIAIIAAAAIAGAHIAAAAQACAFAAAGIAAAAQAAALgIAIIAAAAQgIAHgLAAIAAAAQgMAAgIgHgAY6C1IgFiLIA4AAIgDCLgAICAgQgJgDgGgFIAAAAQgGgHgEgJIAAAAQgDgIAAgKIAAAAIAcgEQABAIAFAFIAAAAQAFABAJAAIAAAAQAJAAAFgBIAAAAQAFgEACgJIAAAAIAcAEQgBAKgDAIIAAAAQgDAJgGAHIAAAAQgGAFgJADIAAAAQgJADgMABIAAAAQgLgBgJgDgAl9gqIAAgVIhzAAIAAAVIgpAAIAAhBIATAAIBDiaIAVAAIBFCaIAVAAIAAAkIBXi+IAWAAIBYC+IAAAIIgxAAIgLgZIhNAAIgMAZIgwAAIAAAVgAnThrIA3AAIgdhHgAkIiDIAtAAIgXgzgANShBQgJgEgIgFIAAAAQgIgEgHgGIAAAAIgNgPIAAAAQgFgHgFgKIAAAAQgEgKgCgKIAAAAQgDgNAAgMIAAAAQAAhDBlgiIAAAAQAMAAAYAHIAAAAIARAHIAAAAQAIAGAHAGIAAAAQAHAGAGAIIAAAAQAGAIAEAJIAAAAQAEAKACAKIAAAAQADAMAAAMIAAAAQAABEhkAhIAAAAQgZgCgMgDgANkjSQgIADgHAHIAAAAQgHAHgEAJIAAAAQgEALAAAMIAAAAQAAAOAEAKIAAAAQAEAJAHAIIAAAAQAHAGAIADIAAAAQAKADAJABIAAAAQAJgBAJgDIAAAAQAJgDAHgGIAAAAQAHgIADgJIAAAAQAEgKAAgOIAAAAQAAgMgEgLIAAAAQgDgJgHgHIAAAAQgHgHgJgDIAAAAQgJgDgJAAIAAAAQgJAAgKADgAXTg/IgSgFIAAAAQgKgDgHgEIAAAAQgJgFgGgHIAAAAIgNgNIAAAAQgGgIgEgKIAAAAQgFgJgCgKIAAAAQgCgMAAgMIAAAAQAAgMACgLIAAAAQACgLAFgKIAAAAQAEgJAGgIIAAAAIANgNIAAAAQAGgHAJgEIAAAAQAHgGAKgCIAAAAIASgFIASgBQAQAAAOADIAAAAQAQAFAMAJIAAAAQAQAOAGAJIAAAAIAHAPIAAAAQADAIACAKIAAAAIgxAAQgDgGgEgGIAAAAQgEgGgFgDIAAAAQgGgEgHgCIAAAAIgOgBIAAAAQgLAAgJAEIAAAAQgJAEgGAHIAAAAQgGAHgEAKIAAAAQgDAKAAAMIAAAAQAAAKADAKIAAAAQAEALAGAGIAAAAQAGAJAJAEIAAAAQAJAEALAAIAAAAQAIABAHgDIAAAAQAHgCAGgEIAAAAQAFgEAEgGIAAAAQAEgGADgHIAAAAIAwAAIgEATIAAAAIgHAQIAAAAIgKANIAAAAQgFAHgHADIAAAAQgNAKgPAFIAAAAQgPADgQAAIAAAAgAcog/IAAjEIAyAAIAADEgAZog/IAAjEIAxAAIAAA7IAkAAQAMAAATAFIAAAAQAMAGAJAKIAAAAQAJAJAFANIAAAAQAEAMAAANIAAAAQAAANgEAMIAAAAQgFANgJAJIAAAAQgJAKgMAFIAAAAQgTAGgMABIAAAAgAaZhsIAjAAQALAAAFgIIAAAAQAGgGAAgKIAAAAQgBgJgFgGIAAAAQgGgIgKAAIAAAAIgjAAgATgg/IAAgGIAeg/IhCh3IAAgIIA4AAIAlBIIABAAIAihIIA2AAIAAAIIhdC8gARwg/IAAhPIg9AAIAABPIgzAAIAAjEIAzAAIAABIIA9AAIAAhIIAzAAIAADEgAJeg/IAAjEICMAAIAAAtIhaAAIAAAYIAkAAQAMAAASAFIAAAAQANAFAJAKIAAAAQAIAJAFAKIAAAAQAEALAAANIAAAAQAAAMgEALIAAAAQgFAMgIAJIAAAAQgJAJgNAFIAAAAQgSAFgMABIAAAAgAKQhsIAjAAQAKAAAGgHIAAAAQAFgEAAgIIAAAAQAAgIgGgFIAAAAQgFgHgKABIAAAAIgjAAgAGtg/IAAhYIgpAsIgGAAIgqgsIAABYIgzAAIAAjEIATAAIBMBVIBOhVIARAAIAADEgAC9g/IAAhhIhiBhIgSAAIAAjEIAzAAIAABgIBjhgIASAAIAADEgAh2g/IAAjEIBWAAQAXAAAbAYIAAAAQAIAKAFAMIAAAAQAEANAAAOIAAAAQAAAOgEANIAAAAQgFANgIAKIAAAAQgJALgLAGIAAAAIgOAEIAAAAQgIACgIgBIAAAAIgkAAIAAAzgAhEieIAjAAQAKAAAGgJIAAAAQAFgIABgLIAAAAQAAgLgGgIIAAAAQgCgEgEgCIAAAAQgEgDgGAAIAAAAIgjAAgAr1g/IAAjEIB5AAIAAAtIhHAAIAAAcIBCAAIAAAsIhCAAIAAAiIBKAAIAAAtgAu1g/IAAjEICLAAIAAAtIhaAAIAAAYIAkAAQAMAAATAFIAAAAQAMAFAJAKIAAAAQAJAJAFAKIAAAAQAEALAAANIAAAAQAAAMgEALIAAAAQgFAMgJAJIAAAAQgJAJgMAFIAAAAQgTAFgMABIAAAAgAuEhsIAkAAQAJAAAHgHIAAAAQAEgEAAgIIAAAAQAAgIgFgFIAAAAQgGgHgJABIAAAAIgkAAgAxcg/IAAjEIB5AAIAAAtIhIAAIAAAcIBCAAIAAAsIhCAAIAAAiIBKAAIAAAtgAzcg/IAAiXIgwAAIAAgtICRAAIAAAtIgvAAIAACXgA2og/IAAjEIAyAAIAADEgA5og/IAAjEIAxAAIAAA7IAkAAQAMAAATAFIAAAAQAMAGAJAKIAAAAQAJAJAFANIAAAAQAEAMAAANIAAAAQAAANgEAMIAAAAQgFANgJAJIAAAAQgJAKgMAFIAAAAQgTAGgMABIAAAAgA43hsIAjAAQALAAAFgIIAAAAQAGgGAAgKIAAAAQgBgJgFgGIAAAAQgGgIgKAAIAAAAIgjAAgA7Ng/IAAhYIgpAsIgGAAIgqgsIAABYIgzAAIAAjEIATAAIBMBVIBOhVIARAAIAADEg");
	var mask_graphics_39 = new cjs.Graphics().p("A3kEHIAAgVIhzAAIAAAVIgpAAIAAhBIATAAIBDibIAWAAIBFCbIAUAAIAAAjIBYi+IAVAAIBYC+IAAAIIgwAAIgyhzIgyBzIgxAAIAAAWgA46DFIA3AAIgchHgAELDvQgJgEgIgFIAAAAQgIgEgHgGIAAAAQgHgHgFgIIAAAAQgGgHgEgKIAAAAQgEgKgCgKIAAAAQgDgMAAgNIAAAAQAAhDBkghIAAAAQANgBAYAHIAAAAQAJADAIAFIAAAAQAIAFAHAGIAAAAQAHAHAFAHIAAAAQAHAJADAIIAAAAQAEAKACAKIAAAAQADANAAALIAAAAQAABEhkAiIAAAAQgZgCgMgEgAEeBeQgIADgHAIIAAAAQgHAGgEAKIAAAAQgFAJAAANIAAAAQAAAOAFAKIAAAAQAEAKAHAHIAAAAQAHAGAIAEIAAAAQAJADAJAAIAAAAQAKAAAIgDIAAAAQAJgEAHgGIAAAAQAHgHAEgKIAAAAQAEgKAAgOIAAAAQAAgNgEgJIAAAAQgEgKgHgGIAAAAQgHgIgJgDIAAAAQgIgDgKAAIAAAAQgJAAgJADgAl0DvQgKgEgHgFIAAAAQgJgEgGgGIAAAAIgNgPIAAAAQgGgHgEgKIAAAAQgEgKgCgKIAAAAQgDgMAAgNIAAAAQAAhDBkghIAAAAQANgBAYAHIAAAAQAJADAIAFIAAAAIAPALIAAAAQAHAHAGAHIAAAAQAGAJAEAIIAAAAQAEAKACAKIAAAAQADANAAALIAAAAQAABEhlAiIAAAAQgZgCgLgEgAliBeQgIADgHAIIAAAAQgHAGgEAKIAAAAQgEAJAAANIAAAAQAAAOAEAKIAAAAQAEAKAHAHIAAAAQAHAGAIAEIAAAAQAJADAJAAIAAAAQAKAAAJgDIAAAAQAJgEAHgGIAAAAQAGgHAEgKIAAAAQAEgKAAgOIAAAAQAAgNgEgJIAAAAQgEgKgGgGIAAAAQgHgIgJgDIAAAAQgJgDgKAAIAAAAQgJAAgJADgAr1DwQgNgEgIgJIAAAAQgJgJgFgMIAAAAQgEgMAAgQIAAAAIArAAQAAALAHAHIAAAAQAHAGALABIAAAAQAMgBAHgGIAAAAQAGgHAAgJIAAAAQAAgJgGgGIAAAAQgHgHgMAAIAAAAIgOAAIAAgpIANAAQAJABAEgGIAAAAQAFgFAAgHIAAAAQAAgHgEgEIAAAAQgFgGgIAAIAAAAQgIAAgFADIAAAAQgEADAAAGIAAAAIgtAAQgBgNAFgLIAAAAQAFgJAIgHIAAAAQAJgHAMgDIAAAAQALgDANABIAAAAQAPAAANAEIAAAAQAMAEAIAJIAAAAQAIAIAEAKIAAAAQAEAJAAALIAAAAQAAALgEAJIAAAAQgFALgIAGIAAAAQAHAEAFAFIAAAAQAGAFADAFIAAAAQAEAHABAHIAAAAQACAGAAAJIAAAAQAAANgFALIAAAAQgFALgJAJIAAAAQgJAIgOAFIAAAAQgPAEgSAAIAAAAQgQAAgNgEgAiADyIgSgGIAAAAIgRgHIAAAAQgIgFgHgHIAAAAQgHgFgGgIIAAAAQgGgIgEgJIAAAAQgEgKgDgKIAAAAQgCgLAAgNIAAAAQAAgMACgKIAAAAQADgMAEgKIAAAAQAEgIAGgJIAAAAQAGgHAHgGIAAAAQAHgGAIgFIAAAAQAIgFAJgDIAAAAIASgFIASgBQAQAAAPAEIAAAAQAPAEAMAJIAAAAQAQAOAGAJIAAAAQAEAHAEAIIAAAAIAEASIAAAAIgxAAQgDgGgEgGIAAAAIgJgJIAAAAQgGgEgGgCIAAAAQgHgBgIAAIAAAAQgLAAgJAEIAAAAQgJADgGAJIAAAAQgGAGgEAKIAAAAQgDALAAALIAAAAQAAALADAJIAAAAQAEALAGAHIAAAAQAGAHAJAFIAAAAQAJAFALAAIAAAAQAIAAAHgCIAAAAQAHgCAGgFIAAAAQAFgDAEgGIAAAAQAFgGACgIIAAAAIAwAAQgBAKgDAJIAAAAQgCAIgFAIIAAAAIgKANIAAAAQgFAHgHAEIAAAAQgMAJgQAFIAAAAQgOAEgRAAIAAAAgAXVDxIAAjDIAzAAIAADDgAUVDxIAAjDIAyAAIAAA7IAkAAQAMgBATAGIAAAAQAMAFAJAKIAAAAQAIAKAFANIAAAAQAFALAAANIAAAAQAAANgFANIAAAAQgFAMgIAJIAAAAQgJALgMAEIAAAAQgTAHgMAAIAAAAgAVHDEIAjAAQALAAAFgIIAAAAQAGgGAAgKIAAAAQgBgJgFgGIAAAAQgGgIgKAAIAAAAIgjAAgARVDxIAAjDIBVAAQAXAAAdAXIAAAAQAJAJAFANIAAAAQAEAOAAANIAAAAQAAAOgEANIAAAAQgFANgJALIAAAAQgJAKgMAGIAAAAQgHADgIABIAAAAQgHACgJgBIAAAAIgkAAIAAAzgASGCSIAjAAQAKAAAGgJIAAAAQAFgHABgMIAAAAQAAgLgGgIIAAAAQgCgEgEgCIAAAAQgEgCgGgBIAAAAIgjAAgAO5DxIAAjDIB5AAIAAAsIhHAAIAACXgANUDxIAAhhIhiBhIgSAAIAAjDIAyAAIAABfIBjhgIASAAIAADEgAIvDxIAAhhIhiBhIgSAAIAAjDIAzAAIAABfIBjhgIASAAIAADEgACPDxIgyhzIgzBzIguAAIAAgIIBVi+IAWAAIBYC+IAAAIgApoDxIAAjDIBWAAQAXAAAdAXIAAAAQAIAJAFANIAAAAQAEAOAAANIAAAAQAAAOgEANIAAAAQgFANgIALIAAAAQgJAKgNAGIAAAAQgHADgHABIAAAAIgQABIAAAAIglAAIAAAzgAo3CSIAkAAQAKAAAGgJIAAAAQAFgHAAgMIAAAAQAAgLgFgIIAAAAQgCgEgEgCIAAAAQgFgCgFgBIAAAAIgkAAgAvNDxIAAjDIBTAAQAMAAALAFIAAAAQAMAEAIAIIAAAAQAIAIAFALIAAAAQAEALAAANIAAAAQAAAJgDAJIAAAAQgFAKgHAFIAAAAQAMAHAGAKIAAAAQAGAKAAAOIAAAAQAAAMgFALIAAAAQgDALgIAJIAAAAQgIAJgLAEIAAAAQgLAEgPABIAAAAgAudDEIAoAAQAHAAAEgFIAAAAQADgFAAgGIAAAAQAAgHgDgEIAAAAQgEgFgHgBIAAAAIgoAAgAudB6IAfAAQAHAAAEgFIAAAAQAEgFAAgFIAAAAQAAgHgEgFIAAAAQgEgEgHgBIAAAAIgfAAgAx9DxIAAg5IgaAAIghA5Ig4AAIAAgIIAmg9QgJgHgHgIIAAAAQgFgJgEgLIAAAAQgDgJgBgLIAAAAQAAgKADgKIAAAAQACgLAGgJIAAAAQAGgJAHgHIAAAAQAKgHALgEIAAAAQALgEAOAAIAAAAIBWAAIAADDgAyxBiQgEAHAAAKIAAAAQAAAKAFAGIAAAAQAGAIAJAAIAAAAIAkAAIAAgxIgkAAQgJAAgHAIgAY+DpQgIgIAAgLIAAAAQAAgGACgFIAAAAQACgEAEgDIAAAAQAIgIAMAAIAAAAQALAAAIAIIAAAAIAGAHIAAAAQACAFAAAGIAAAAQAAALgIAIIAAAAQgIAHgLAAIAAAAQgMAAgIgHgAY6C1IgFiLIA4AAIgDCLgAICAgQgJgDgGgFIAAAAQgGgHgEgJIAAAAQgDgIAAgKIAAAAIAcgEQABAIAFAFIAAAAQAFABAJAAIAAAAQAJAAAFgBIAAAAQAFgEACgJIAAAAIAcAEQgBAKgDAIIAAAAQgDAJgGAHIAAAAQgGAFgJADIAAAAQgJADgMABIAAAAQgLgBgJgDgAl9gqIAAgVIhzAAIAAAVIgpAAIAAhBIATAAIBDiaIAVAAIBFCaIAVAAIAAAkIBXi+IAWAAIBYC+IAAAIIgxAAIgLgZIhNAAIgMAZIgwAAIAAAVgAnThrIA3AAIgdhHgAkIiDIAtAAIgXgzgANShBQgJgEgIgFIAAAAQgIgEgHgGIAAAAIgNgPIAAAAQgFgHgFgKIAAAAQgEgKgCgKIAAAAQgDgNAAgMIAAAAQAAhDBlgiIAAAAQAMAAAYAHIAAAAIARAHIAAAAQAIAGAHAGIAAAAQAHAGAGAIIAAAAQAGAIAEAJIAAAAQAEAKACAKIAAAAQADAMAAAMIAAAAQAABEhkAhIAAAAQgZgCgMgDgANkjSQgIADgHAHIAAAAQgHAHgEAJIAAAAQgEALAAAMIAAAAQAAAOAEAKIAAAAQAEAJAHAIIAAAAQAHAGAIADIAAAAQAKADAJABIAAAAQAJgBAJgDIAAAAQAJgDAHgGIAAAAQAHgIADgJIAAAAQAEgKAAgOIAAAAQAAgMgEgLIAAAAQgDgJgHgHIAAAAQgHgHgJgDIAAAAQgJgDgJAAIAAAAQgJAAgKADgAXTg/IgSgFIAAAAQgKgDgHgEIAAAAQgJgFgGgHIAAAAIgNgNIAAAAQgGgIgEgKIAAAAQgFgJgCgKIAAAAQgCgMAAgMIAAAAQAAgMACgLIAAAAQACgLAFgKIAAAAQAEgJAGgIIAAAAIANgNIAAAAQAGgHAJgEIAAAAQAHgGAKgCIAAAAIASgFIASgBQAQAAAOADIAAAAQAQAFAMAJIAAAAQAQAOAGAJIAAAAIAHAPIAAAAQADAIACAKIAAAAIgxAAQgDgGgEgGIAAAAQgEgGgFgDIAAAAQgGgEgHgCIAAAAIgOgBIAAAAQgLAAgJAEIAAAAQgJAEgGAHIAAAAQgGAHgEAKIAAAAQgDAKAAAMIAAAAQAAAKADAKIAAAAQAEALAGAGIAAAAQAGAJAJAEIAAAAQAJAEALAAIAAAAQAIABAHgDIAAAAQAHgCAGgEIAAAAQAFgEAEgGIAAAAQAEgGADgHIAAAAIAwAAIgEATIAAAAIgHAQIAAAAIgKANIAAAAQgFAHgHADIAAAAQgNAKgPAFIAAAAQgPADgQAAIAAAAgAcog/IAAjEIAyAAIAADEgAZog/IAAjEIAxAAIAAA7IAkAAQAMAAATAFIAAAAQAMAGAJAKIAAAAQAJAJAFANIAAAAQAEAMAAANIAAAAQAAANgEAMIAAAAQgFANgJAJIAAAAQgJAKgMAFIAAAAQgTAGgMABIAAAAgAaZhsIAjAAQALAAAFgIIAAAAQAGgGAAgKIAAAAQgBgJgFgGIAAAAQgGgIgKAAIAAAAIgjAAgATgg/IAAgGIAeg/IhCh3IAAgIIA4AAIAlBIIABAAIAihIIA2AAIAAAIIhdC8gARwg/IAAhPIg9AAIAABPIgzAAIAAjEIAzAAIAABIIA9AAIAAhIIAzAAIAADEgAJeg/IAAjEICMAAIAAAtIhaAAIAAAYIAkAAQAMAAASAFIAAAAQANAFAJAKIAAAAQAIAJAFAKIAAAAQAEALAAANIAAAAQAAAMgEALIAAAAQgFAMgIAJIAAAAQgJAJgNAFIAAAAQgSAFgMABIAAAAgAKQhsIAjAAQAKAAAGgHIAAAAQAFgEAAgIIAAAAQAAgIgGgFIAAAAQgFgHgKABIAAAAIgjAAgAGtg/IAAhYIgpAsIgGAAIgqgsIAABYIgzAAIAAjEIATAAIBMBVIBOhVIARAAIAADEgAC9g/IAAhhIhiBhIgSAAIAAjEIAzAAIAABgIBjhgIASAAIAADEgAh2g/IAAjEIBWAAQAXAAAbAYIAAAAQAIAKAFAMIAAAAQAEANAAAOIAAAAQAAAOgEANIAAAAQgFANgIAKIAAAAQgJALgLAGIAAAAIgOAEIAAAAQgIACgIgBIAAAAIgkAAIAAAzgAhEieIAjAAQAKAAAGgJIAAAAQAFgIABgLIAAAAQAAgLgGgIIAAAAQgCgEgEgCIAAAAQgEgDgGAAIAAAAIgjAAgAr1g/IAAjEIB5AAIAAAtIhHAAIAAAcIBCAAIAAAsIhCAAIAAAiIBKAAIAAAtgAu1g/IAAjEICLAAIAAAtIhaAAIAAAYIAkAAQAMAAATAFIAAAAQAMAFAJAKIAAAAQAJAJAFAKIAAAAQAEALAAANIAAAAQAAAMgEALIAAAAQgFAMgJAJIAAAAQgJAJgMAFIAAAAQgTAFgMABIAAAAgAuEhsIAkAAQAJAAAHgHIAAAAQAEgEAAgIIAAAAQAAgIgFgFIAAAAQgGgHgJABIAAAAIgkAAgAxcg/IAAjEIB5AAIAAAtIhIAAIAAAcIBCAAIAAAsIhCAAIAAAiIBKAAIAAAtgAzcg/IAAiXIgwAAIAAgtICRAAIAAAtIgvAAIAACXgA2og/IAAjEIAyAAIAADEgA5og/IAAjEIAxAAIAAA7IAkAAQAMAAATAFIAAAAQAMAGAJAKIAAAAQAJAJAFANIAAAAQAEAMAAANIAAAAQAAANgEAMIAAAAQgFANgJAJIAAAAQgJAKgMAFIAAAAQgTAGgMABIAAAAgA43hsIAjAAQALAAAFgIIAAAAQAGgGAAgKIAAAAQgBgJgFgGIAAAAQgGgIgKAAIAAAAIgjAAgA7Ng/IAAhYIgpAsIgGAAIgqgsIAABYIgzAAIAAjEIATAAIBMBVIBOhVIARAAIAADEg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-41,y:-77.3}).wait(39).to({graphics:mask_graphics_39,x:-41,y:-77.3}).wait(51));

	// Слой 2
	this.instance = new lib.Символ16();
	this.instance.setTransform(-305.7,-100.1);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:247.8},39).wait(51));

	// Слой 1
	this.instance_1 = new lib.Символ5();
	this.instance_1.setTransform(-40.9,-77.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(90));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-229.2,-103.6,376.5,52.7);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Слой3();
	this.instance.setTransform(0,0,1,1,0,0,0,63.5,45.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.5,-45.5,127,91);


(lib.Символ62 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_119 = function() {
		this.gotoAndPlay(0);
	}
	this.frame_139 = function() {
		this.gotoAndPlay(120);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(119).call(this.frame_119).wait(20).call(this.frame_139).wait(6));

	// Слой 1
	this.instance = new lib.Символ61();
	this.instance.setTransform(23.7,57.6,1,1,0,0,0,23.7,57.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-7.3},29,cjs.Ease.get(-1)).to({rotation:-15},30,cjs.Ease.get(1)).to({rotation:-7.3},30,cjs.Ease.get(-1)).to({rotation:0},30,cjs.Ease.get(1)).wait(1).to({rotation:-25.7},0).to({scaleX:1,scaleY:1,rotation:-25.6,x:3.1,y:49.9},4,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:-25.7,x:-22.8,y:40.2},5,cjs.Ease.get(0.92)).to({scaleX:1,scaleY:1,rotation:-25.6,x:0.5,y:49},5,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:-25.7,x:23.7,y:57.6},5,cjs.Ease.get(0.92)).to({rotation:0},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.4,-85.3,104.9,170.7);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_115 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_140 = function() {
		this.gotoAndPlay(117);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(115).call(this.frame_115).wait(25).call(this.frame_140).wait(1));

	// Слой 1
	this.instance = new lib.Символ38();
	this.instance.setTransform(-1.1,-7.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.07,scaleY:1.07},3).to({scaleX:1,scaleY:1},3).wait(1).to({scaleX:1.07,scaleY:1.07},3).to({scaleX:1,scaleY:1},3).wait(43).to({rotation:-2.5},3,cjs.Ease.get(1)).to({rotation:3.9},4,cjs.Ease.get(-1)).to({rotation:-2.5},4,cjs.Ease.get(1)).to({rotation:3.9},4,cjs.Ease.get(-1)).to({rotation:0},3,cjs.Ease.get(1)).wait(42).to({scaleX:1.07,scaleY:1.07},6,cjs.Ease.get(-1)).to({scaleX:1.13,scaleY:1.13},6,cjs.Ease.get(0.96)).to({scaleX:1.07,scaleY:1.07,x:-1.2},6,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,x:-1.1},6,cjs.Ease.get(0.96)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-95.1,-31.9,188.2,63.8);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#010717","#010717","rgba(1,7,23,0)"],[0,0.678,1],0,62.3,0,-62.3).s().p("AnPKUIAA0nIOeAAIAAUng");
	this.shape.setTransform(62.6,75.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#010717","#010717","rgba(1,7,23,0)"],[0,0.678,1],0,-62.3,0,62.3).s().p("AnPKUIAA0nIOeAAIAAUng");
	this.shape_1.setTransform(62.6,-75.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AyWr3MAktAAAIAAXvMgktAAAg");
	mask.setTransform(4.2,1.6);

	// Слой 1
	this.bablo = new lib.Символ24();
	this.bablo.setTransform(-0.8,-0.6,1.942,1.942);

	this.bablo.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.bablo).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-82.5,-141.1,191.6,282.4);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ28();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},19).to({alpha:1},20).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-304.1,-154.1,612,312);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ26();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-300,-150,600,300);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ22();
	this.instance.setTransform(-66,28,1,1,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},49).to({alpha:1},50).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ22();
	this.instance_1.setTransform(-196,28);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},49).to({alpha:0},50).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-795.5,-374.5,1329,805);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ20();
	this.instance.setTransform(4.6,0,0.061,0.061);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.09,scaleY:1.09},44).to({scaleX:1.52,scaleY:1.52,alpha:0},18).wait(55));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-13.1,-5.2,35.6,10.4);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ4();
	this.instance.setTransform(41,35.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:42.4,y:48.4},34,cjs.Ease.get(-1)).to({x:43.7,y:61.8},35,cjs.Ease.get(1)).to({x:42.3,y:48.2},36,cjs.Ease.get(-1)).to({x:41,y:35.3},34,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-370.2,-180,558.5,230.4);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.ruka = new lib.Символ62();
	this.ruka.setTransform(-110.3,78.2,0.881,0.881,-20.5);

	this.timeline.addTween(cjs.Tween.get(this.ruka).wait(1));

	// Слой 2
	this.instance = new lib.Символ58();
	this.instance.setTransform(24.1,8.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Слой2();
	this.instance_1.setTransform(26.6,51.5,1,1,0,0,0,127.5,121.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-180,-70,334.1,243);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.setTransform(-309.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-85.6,y:-208.5},24,cjs.Ease.get(-1)).to({x:194.1,y:-469.2},30,cjs.Ease.get(1)).to({x:-62.2,y:-230.3},28,cjs.Ease.get(-1)).to({x:-309.3,y:0},27,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-372.8,-57.5,127,115);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ10();
	this.instance.setTransform(122,-101);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-285.6,y:-139.5},44,cjs.Ease.get(-1)).to({x:-584.5,y:22.2},45,cjs.Ease.get(1)).to({x:-282.4,y:-141.2},46,cjs.Ease.get(-1)).to({x:6.6,y:-297.6},44,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(354,-101,127,115);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ8();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:148.8},19,cjs.Ease.get(-1)).to({y:305.4},20,cjs.Ease.get(1)).to({y:152.7},20,cjs.Ease.get(-1)).to({y:0},20,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65,-67,130,134);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ6();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-76.5,y:380.2},49,cjs.Ease.get(-1)).to({x:-154.6,y:768.1},50,cjs.Ease.get(1)).to({x:-77.3,y:384.1},50,cjs.Ease.get(-1)).to({x:0,y:0},50,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.5,-47.5,105,95);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63.5,-45.5,127,91);


(lib.Символ57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ7();
	this.instance.setTransform(242.5,47.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-172.7,y:83.2},49,cjs.Ease.get(-1)).to({x:-596.3,y:119.6},50,cjs.Ease.get(0.98)).to({x:-176.9,y:83.6},50,cjs.Ease.get(-1)).to({x:242.5,y:47.5},50,cjs.Ease.get(0.98)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(190,0,105,95);


(lib.Символ56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 11
	this.instance = new lib.Символ11();
	this.instance.setTransform(71.9,93.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Символ 7
	this.instance_1 = new lib.Символ57();
	this.instance_1.setTransform(201.8,-357.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Символ 9
	this.instance_2 = new lib.Символ9();
	this.instance_2.setTransform(-355.5,-179.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Символ 13
	this.instance_3 = new lib.Символ13();
	this.instance_3.setTransform(-40.1,292.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-420.5,-357.8,973.4,707.5);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ17();
	this.instance.setTransform(0,-42,1,1,-4.5,0,0,0,-42);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:1.8},74,cjs.Ease.get(-1)).to({regX:-0.1,rotation:8.5},75,cjs.Ease.get(1)).to({regY:-42.1,rotation:2,y:-42.1},74,cjs.Ease.get(-1)).to({regX:0,regY:-42,rotation:-4.5,y:-42},76,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-379.8,-167.2,569.6,246.2);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.mujik1 = new lib.Символ14();

	this.timeline.addTween(cjs.Tween.get(this.mujik1).to({y:-3.1},19,cjs.Ease.get(-1)).to({y:-6.5},20,cjs.Ease.get(1)).to({y:-3.2},20,cjs.Ease.get(-1)).to({y:0},20,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-180,-70,334.1,243);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ18();
	this.instance.setTransform(0,0,1,1,0,0,0,0,-42);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.89,scaleY:0.89},49,cjs.Ease.get(-1)).to({scaleX:0.77,scaleY:0.77},50,cjs.Ease.get(1)).to({regY:-42.1,scaleX:0.89,scaleY:0.89},50,cjs.Ease.get(-1)).to({regY:-42,scaleX:1,scaleY:1},50,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-379.8,-125.2,569.6,246.2);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 6
	this.btn = new lib.Символ41();
	this.btn.setTransform(80.9,69.2,1.198,1.198);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

	// Слой 3
	this.instance = new lib.Символ3();
	this.instance.setTransform(148.2,-153.5,0.549,0.549);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.mujik = new lib.Символ15();
	this.mujik.setTransform(-230.8,19,0.846,0.846,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.mujik).wait(1));

	// Layer 9 - копия: 2
	this.instance_1 = new lib.Символ21();
	this.instance_1.setTransform(-236.4,72.7,1,1,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer 9 - копия: 2
	this.instance_2 = new lib.Символ21();
	this.instance_2.setTransform(-235.4,79.2,1,1,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Layer 9 - копия
	this.instance_3 = new lib.Символ21();
	this.instance_3.setTransform(-233.3,70.9,1,1,90);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Layer 9
	this.instance_4 = new lib.Символ21();
	this.instance_4.setTransform(-237.3,76.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// Слой 4
	this.instance_5 = new lib.Символ64();
	this.instance_5.setTransform(-144.4,-241.3,1.317,1.317,0,0,0,-0.1,-104.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

	// flares__12_
	this.instance_6 = new lib.Символ19();
	this.instance_6.setTransform(-156.9,-117.2,0.836,0.836,0,0,0,-91,-22.9);

	this.instance_7 = new lib.Символ23();
	this.instance_7.setTransform(-176.2,76,0.718,0.718,0,0,0,-129.1,15.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6}]}).wait(1));

	// Layer 6 copy 2
	this.instance_8 = new lib.Символ56();
	this.instance_8.setTransform(-161.7,-46.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(1));

	// Layer 6 copy 2 - копия
	this.instance_9 = new lib.Символ56();
	this.instance_9.setTransform(-83.7,-46.9,1,1,-133);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(1));

	// Слой 5
	this.text1 = new lib.Символ33();
	this.text1.setTransform(73.6,-10.6,0.836,0.836);

	this.timeline.addTween(cjs.Tween.get(this.text1).wait(1));

	// Прямоугольник 1
	this.instance_10 = new lib.Символ27();
	this.instance_10.setTransform(-89.5,-42.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-684.1,-702.9,1137.6,1384.7);


// stage content:
(lib.resident600x300 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		var _this = this;
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		function fl_MouseOverHandler_5()
		{
		    _this.main.text1.bablo.gotoAndStop(249);
			_this.main.btn.gotoAndPlay(117);
			_this.main.mujik.mujik1.ruka.gotoAndPlay(120);
		}
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		
		
		function fl_MouseOutHandler_2()
		{
		    _this.main.text1.bablo.gotoAndPlay(0);
			_this.main.btn.gotoAndPlay(0);
			_this.main.mujik.mujik1.ruka.gotoAndPlay(140);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 15
	this.instance = new lib.Символ29();
	this.instance.setTransform(300.1,150.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 3
	this.main = new lib.Символ1();
	this.main.setTransform(389.5,192.5);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(5.4,-360.4,1137.6,1384.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;