(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/afag.png?1473860617371", id:"afag"},
		{src:"images/agahhah.png?1473860617371", id:"agahhah"},
		{src:"images/ajajaj.png?1473860617371", id:"ajajaj"},
		{src:"images/dkdkdk.png?1473860617371", id:"dkdkdk"},
		{src:"images/dym.png?1473860617371", id:"dym"},
		{src:"images/fff.png?1473860617371", id:"fff"},
		{src:"images/glklyl.png?1473860617372", id:"glklyl"},
		{src:"images/logo1.png?1473860617372", id:"logo1"},
		{src:"images/qwre.jpg?1473860617372", id:"qwre"},
		{src:"images/sdfghfhserfhwqar.png?1473860617372", id:"sdfghfhserfhwqar"},
		{src:"images/w256h2561380453915MouseOptions256x256321.png?1473860617372", id:"w256h2561380453915MouseOptions256x256321"},
		{src:"images/wert.png?1473860617372", id:"wert"},
		{src:"images/yertyerty.jpg?1473860617372", id:"yertyerty"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.afag = function() {
	this.initialize(img.afag);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,73,166);


(lib.agahhah = function() {
	this.initialize(img.agahhah);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,69,90);


(lib.ajajaj = function() {
	this.initialize(img.ajajaj);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,20,32);


(lib.dkdkdk = function() {
	this.initialize(img.dkdkdk);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,44,24);


(lib.dym = function() {
	this.initialize(img.dym);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,331,997);


(lib.fff = function() {
	this.initialize(img.fff);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,456,161);


(lib.glklyl = function() {
	this.initialize(img.glklyl);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,141,256);


(lib.logo1 = function() {
	this.initialize(img.logo1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,370,206);


(lib.qwre = function() {
	this.initialize(img.qwre);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,138,256);


(lib.sdfghfhserfhwqar = function() {
	this.initialize(img.sdfghfhserfhwqar);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,101,27);


(lib.w256h2561380453915MouseOptions256x256321 = function() {
	this.initialize(img.w256h2561380453915MouseOptions256x256321);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,256);


(lib.wert = function() {
	this.initialize(img.wert);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,141,256);


(lib.yertyerty = function() {
	this.initialize(img.yertyerty);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,136,256);


(lib.Символ73 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FF00").s().p("AgYAYQgKgKAAgOQAAgNAKgLQALgKANAAQAOAAAKAKQALALAAANQAAAOgLAKQgKALgOAAQgNAAgLgLg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.5,-3.5,7,7);


(lib.Символ71 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sdfghfhserfhwqar();
	this.instance.parent = this;
	this.instance.setTransform(-50.5,-54);

	this.instance_1 = new lib.sdfghfhserfhwqar();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-50.5,-27);

	this.instance_2 = new lib.sdfghfhserfhwqar();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-50.5,0);

	this.instance_3 = new lib.sdfghfhserfhwqar();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-50.5,27);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.5,-54,101,108);


(lib.Символ66 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.fff();
	this.instance.parent = this;
	this.instance.setTransform(-228,-91);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-228,-91,456,161);


(lib.Символ65 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALOCxQgDgEAAgFIAAg0QAAgFADgDQAEgEAGAAIAGAAIAFgCIAEgEIAFgIIAAABIAEgMIg+iaIABABIgCgEIgBgDQAAgFAEgDQAEgDAIAAIAuAAQAHAAAFADQAEADACAFIARA4IACAIIADAGIAVhGQACgGAEgCQAFgDAHAAIAtAAQAKAAADADQAEADAAAGIAAADIhCCoIAAgBIgBADIgIAUIAAAAIgFALQgFAMgIAKQgHAKgLAHQgKAIgNAEQgNAEgPABQgHgBgEgCgAItCrIgBAAIgCAAQgUgCgRgGQgQgGgPgJIgGgFQgDgCAAgEIACgFIAbgnIAFgEIAHgCIAGABIAUAKIAJADIAMABIAHgBIAGgDIAEgHIABgKQAAgXgZABIgBAAQgHAAgEgDQgFgDAAgGIAAgmQAAgFAFgEQAEAAAHAAIAIgBIAHgDIAEgEQACgDAAgFQAAgHgFgEQgFgDgIgBQgHABgHACQgGACgGAFQgEACgFABIgHgCIgEgEIgagkIgBgCIAAgCQAAgEACgCIAGgEIAAAAQAOgKARgFQAQgFATAAIAVAAIAVAEQAKADAKAEQAJAEAHAIQAGAIAEALQAEANAAAPQAAAKgCAIQgDAGgDAFIgJAKIgKAGIAPAMQAGAHAGAHQAFAJADAJQADAKAAAMQAAAVgIARQgIAQgOAKQgOAKgSAFQgSAFgTAAgAj8ClQgRgEgOgJQgPgJgMgMQgNgNgIgOQgJgPgFgRQgFgRAAgTQAAgSAFgSQAFgOAJgPQAIgQANgLQAMgMAPgKQAOgIARgFQASgEASgBQASABASAEQARAFAPAIQAOAKANAMQAMALAJAQQAIAPAFAOQAFASAAASQAAATgFARQgFARgIAPQgJAOgMANQgNAMgOAJQgPAJgRAEQgSAFgSAAQgSAAgSgFgAjsgLQgJAEgHAHQgHAFgEAKQgDAKAAALQAAALADAKQAEAKAHAGQAHAIAJAEQAJAEALAAQAMAAAJgEQAJgEAHgIQAHgGAEgKQAEgKAAgLQAAgLgEgKQgEgKgHgFQgHgHgJgEQgJgFgMAAQgLAAgJAFgAsCClQgSgEgPgIQgPgJgMgLQgNgMgJgPQgJgPgFgSQgFgRAAgUQAAgRAFgRQAEgOAJgPQAIgPAMgMQAMgNAPgJQAOgKARgEQASgGASAAQARAAAOAEQANADAMAEQALAFAJAIIATAOIADAFQABADgCAEIgyAuIgEAAIgEAAIgHgGIgIgFIgKgDIgNgCQgKABgKAEQgJAEgHAHQgGAGgEAKQgEAJAAAKQAAALAEAJQADAJAHAIQAGAHAKAFQAJAFALAAQALAAAKgFQAKgEAIgIIAEgBIADABIAyAwQADAEgBACIgEAGQgUATgXAKQgXAJgZAAQgSAAgRgFgAg6ClQgEgDAAgHIAAgtQAAgMAPAAQAEAAAEgEQADgEAAgGIAAijQAAgEAEgFQAEgEAIAAIC8AAIAHABIAFACIAEADIABAGIAADpQAAAGgEAEQgFADgHAAIgyAAQgHAAgFgDQgEgEAAgGIAAivIg7AAIAABqQAAASgHAPQgHAPgMAMQgMAMgPAGQgRAHgUAAQgIAAgEgEgAQ0CmQgIAAAAgHIAAh2Ig7B3QgDAGgFAAIhHAAIgFgCQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIAAj0QAAgEACgCQACgCAEAAIBEAAQAEAAACADQACACAAADIAABrIA9huIAEgDIAEgCIBEAAQAEAAACADQACACAAADIAADzIgCAEQgBADgFAAgAD5CmQgEAAgBgCQgCgCAAgDIAAjzQAAgIAHAAIBEAAQAIAAAAAIIAABMIAqAAQASAAAPAHQAPAGAKAMQAKANAGAPQAGAQAAAQQAAAQgGAQQgGAQgLAMQgKAOgPAHQgPAIgSAAgAFFBnIAWAAQAGAAAEgDIAGgFIAEgIIABgJIgBgKIgEgIIgGgGQgEgCgGAAIgWAAgAnCCmQgQAAAAgNIAAivIg9AAIAACwQAAAGgEADQgEADgIAAIgzAAQgIAAgEgDQgEgDAAgGIAAjpQAAgNAQAAIDDAAIAFABIAGACIADAEIACAFIAADpQAAANgQAAgAvRCmQgJAAgEgDQgDgEAAgGIAAh0IhJB5IgGAGQgEACgFAAIg2AAQgHAAgEgDQgFgCAAgHIAAjqQAAgFAFgEQAFgDAHAAIAwAAQAGAAAEADQAFADABAGIAABpIBFhuQADgEAEgBIAKgCIA2AAQAIAAAEAEQAFAEAAAEIAADpQgBAGgDADQgEAEgJAAgAQFh5IgNgGIgNgLIgQgRIAAgCIAAgBIgBgBQAAgDADgBIAUgOIABgBIADgBIACABIACABIAMAPIAGAEIAHACIAHgCIAGgEIALgPIAFgCIABABIADABIAUAOQADACAAACIgBABIAAABIAAACIgQARIgOALIgNAGIgMACg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115.2,-18,230.5,36);


(lib.Символ64 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgVAWQgKgJAAgNQAAgMAKgJQAJgKAMAAQANAAAJAKQAKAJAAAMQAAANgKAJQgJAKgNAAQgMAAgJgKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.2,-3.2,6.5,6.5);


(lib.Символ62 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#265468").s().p("EgwhAVRMAAAgqhMBhDAAAMAAAAqhg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-310.6,-136.1,621.3,272.4);


(lib.Символ60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.glklyl();
	this.instance.parent = this;
	this.instance.setTransform(-76.7,-139.3,1.088,1.088);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.7,-139.3,153.5,278.6);


(lib.Символ58 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.yertyerty();
	this.instance.parent = this;
	this.instance.setTransform(-74,-139.3,1.088,1.088);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74,-139.3,148,278.6);


(lib.Символ56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.qwre();
	this.instance.parent = this;
	this.instance.setTransform(-75.1,-139.3,1.088,1.088);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.1,-139.3,150.2,278.6);


(lib.Символ54 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.wert();
	this.instance.parent = this;
	this.instance.setTransform(-76.7,-139.3,1.088,1.088);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.7,-139.3,153.5,278.6);


(lib.Символ52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CC99").s().p("EgYwAxOMAAAhibMAxhAAAMAAABibg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-158.5,-315,317.1,630.2);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AOVC0QgYgHgUgMQgVgMgRgQQgRgSgMgUQgNgWgGgXQgHgYAAgaQAAgYAHgZQAGgXANgWQAMgUARgRQARgRAVgNQAUgMAYgGQAZgHAaAAQAZAAAYAHQAYAGAVAMQAVANARARQASARAMAUQALAWAHAXQAHAZAAAYQAAAagHAYQgHAXgLAWQgMAUgSASQgRAQgVAMQgVAMgYAHQgYAHgZAAQgaAAgZgHgAOshEQgOAGgKAKQgJAKgFAOQgFAOAAAOQAAAPAFANQAFAOAJAKQAKAKAOAGQAMAGAQgBQAQABANgGQANgGAKgKQAJgKAFgOQAGgNAAgPQAAgOgGgOQgFgOgJgKQgKgKgNgGQgNgGgQABQgQgBgMAGgAv4C0QgYgHgUgMQgVgMgRgQQgSgSgMgUQgMgWgHgXQgHgYAAgaQAAgYAHgZQAHgXAMgWQAMgUASgRQARgRAVgNQAUgMAYgGQAYgHAaAAQAZAAAZAHQAYAGAVAMQAUANASARQARARAMAUQAMAWAHAXQAGAZAAAYQAAAagGAYQgHAXgMAWQgMAUgRASQgSAQgUAMQgVAMgYAHQgZAHgZAAQgaAAgYgHgAvihEQgNAGgKAKQgJAKgGAOQgFAOAAAOQAAAPAFANQAGAOAJAKQAKAKANAGQANAGAPgBQAQABAOgGQAMgGAKgKQAKgKAFgOQAFgNAAgPQAAgOgFgOQgFgOgKgKQgKgKgMgGQgOgGgQABQgPgBgNAGgAmLC0QgFgEAAgJIAAg/QAAgSAVAAQAGAAAFgGQAFgFAAgIIAAjlQAAgGAFgHQAGgGALAAIEUABIAHADIAFAFIACAIIAAFIQAAAIgGAFQgGAFgLgBIhGAAQgKABgGgFQgGgFAAgIIAAj3IhSAAIAACWQAAAZgKAWQgKAUgRASQgRAPgYAKQgYAIgcABQgLgBgGgFgAKMC1QgIABgHgEQgGgEgEgEIABAAIhUhoIgJADIAABfQAAARgYAAIhFAAQgLABgGgFQgFgFAAgIIAAlHQAAgHAFgGQAGgFALAAIBFAAIAIACIAIADIAFAGIADAHIAABoIAMgUIACgDQAMgVAOgTQAOgSASgNQARgNAXgIQAWgIAeABQAJAAAFADQAGAFAAAHIAABAQgBAGgFAGQgFAEgKAAQgIABgIAFIgRASIgrA9ICGCiQAFAFAAAFQAAAFgEADQgEACgIAAgAEIC1QgMAAgEgKIgNgrIhpAAIgOArQgEAKgMAAIheAAQgGABAAgGIB5laIACgEIADgEIAEgCIAEgBIBhAAQADAAAEADIAFAIIB7FaQAAAGgIgBgADNAmIgXhHIgXBHIAuAAgAqzC1QgLAAgGgEQgGgGAAgIIAAlGQAAgJAHgFQAFgEALAAIDbAAQAKAAAGAFQAGAGAAAHIAAA5QAAAIgHAGQgGADgJAAIh/AAIAAAhIA8AAQAbAAAWALQAWAKAPARQAQAQAJAUQAIAWAAAWQAAAXgIAWQgJAVgQARQgQAQgWAKQgXALgagBgApXBcIAnAAIAKgCIAHgHIAFgKIACgLIgCgLIgFgKIgHgIQgEgDgGAAIgnAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115.5,-18.7,231.1,37.5);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("A0WGSQhdAAABhdIAAppQgBhdBdAAMAotAAAQBdAAgBBdIAAJpQABBdhdAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139.6,-40.2,279.2,80.5);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlMB3QgFAAgCgCQgDgCAAgDIAAghIhdAAIAAAhQAAADgDADQgDABgFAAIgiAAQgGAAgCgBQgCgDAAgDIAAhOQAAgEADgCQADgDAFAAIAPAAIANgbIAEgSIADgWIADhBQAAgJAKAAIBzAAIAEABIADACIADACIAAAEIAACEIAKAAQAFAAAEADQADACAAAEIAABOQAAADgDACQgDACgFAAgAmFg/IAGAAIgFAsIgMAsIAgAAIAAhYIgPAAIAAgDgAgBBPQgNgDgLgHQgMgHgJgJQgJgJgHgLQgHgMgDgNQgEgLAAgOQAAgOAEgNQADgNAHgLQAHgMAJgJQAJgIAMgHQALgHANgEQALgDAOAAQAOAAANADQANAEALAHQALAHAKAIQAJAJAHAMQAGALAEANQAEANAAAOQAAAOgEALQgEANgGAMQgHALgJAJQgKAJgLAHQgLAHgNADQgNAEgOAAQgOAAgLgEgAAJg3QgHAEgEAFQgFAGgDAIQgCAHAAAIQAAAIACAIQADAFAFAGQAEAFAHAEQAHADAIAAQAJAAAHgDQAHgEAFgFQAGgGACgFQADgIAAgIQAAgIgDgHQgCgIgGgGQgFgFgHgEQgHgCgJAAQgIAAgHACgAp/BPQgNgDgLgHQgLgHgKgJQgJgJgHgLQgGgMgEgNQgEgLAAgOQAAgOAEgNQAEgNAGgLQAHgMAJgJQAKgIALgHQALgHANgEQANgDAOAAQAOAAANADQANAEAMAHQALAHAJAIQAKAJAGAMQAHALADANQAEANAAAOQAAAOgEALQgDANgHAMQgGALgKAJQgJAJgLAHQgMAHgNADQgNAEgOAAQgOAAgNgEgApzg3QgHAEgFAFQgFAGgDAIQgDAHAAAIQAAAIADAIQADAFAFAGQAFAFAHAEQAHADAIAAQAJAAAHgDQAHgEAFgFQAGgGACgFQADgIAAgIQAAgIgDgHQgCgIgGgGQgFgFgHgEQgHgCgJAAQgIAAgHACgAMABQQgGAAAAgFIAAi5QAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAAAQABgBABAAICIAAIAEACQAAAAABABQAAAAAAABQAAAAABABQAAABAAAAIAAArIgCAEQgBABAAAAQgBABAAAAQAAAAgBAAQgBABAAAAIhOAAIAAAWIA8AAIAEABQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAhIgCABQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAIg8AAIAAAVIBRAAIAEACQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABIAAAtIgCACQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAgAJIBQQgGAAAAgFIAAi5QAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBABAAQAAAAABAAQABgBAAAAICIAAIAEACQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAIAAArIgCAEQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAIhOAAIAAAWIA9AAIAEABQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAhIgBABQgBAAAAABQAAAAgBAAQAAABgBAAQgBAAAAAAIg9AAIAAAVIBRAAIAEACQABABAAAAQAAABAAAAQABABAAAAQAAABAAABIAAArIgBACIgBACQgCACgDAAgAHdBQQgGAAAAgFIAAhHIg4AAIAABHQAAAFgGAAIg0AAQgFAAgBgEIAAi6IACgDQABgBAAAAQAAgBABAAQAAAAABAAQABgBAAAAIA0AAIAEADQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAAA6IA4AAIAAg6QAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAgBABAAQAAAAABAAQABgBAAAAIA0AAIAEACQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABIAAC5QAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAgACtBQQgGAAgDgDQgDgCAAgFIAAiwQAAgFADgCQADgCAGgBIB3AAQAFABAEADQADADAAADIAAAfQAAAFgEADQgDABgFAAIhFAAIAAASIAhAAQAOAAAMAGQAMAGAIAIQAJAKAFAMQAEAJAAAMQAAANgEAMQgFALgJAJQgIAJgNAGQgMAFgOAAgADfAgIAVAAIAFgBIAFgEIACgFIABgHIgBgGIgCgFIgEgEQgDAAgDAAIgVAAgAj4BQQgFAAAAgFIAAi5IABgDQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAIBZAAQAJAAAIADQAIADAHAFQAHAFAFAGQAGAGAEAIIAGAQQACAIAAAIQAAAMgFAMQgEAMgIAKQgIAHgLAGQgLAGgOAAIggAAIAAA6QAAAFgGAAgAi+gdIARAAQAEAAADgBIAFgFIADgFIABgIIgBgHIgDgGIgFgFQgDgCgEABIgRAAgAsWBQQgMAAAAgKIAAiFIguAAIAACGQAAAEgDADQgDACgGAAIgnAAQgGAAgDgCQgDgDAAgEIAAiwQAAgLAMAAICUAAIAEABIAEACIADADIABAEIAACwQAAAKgMAAg");
	this.shape.setTransform(-0.2,1.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-91.4,-10.2,182.6,23.9);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990000").s().p("AyLFoQhUgBAAhSIAAopQAAhTBUAAMAkXAAAQBUAAAABTIAAIpQAABShUABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.8,-36,249.6,72);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADvCAQgRgEgPgJQgPgJgMgMQgMgMgJgPQgJgPgEgRQgFgRAAgSQAAgRAFgRQAEgRAJgPQAJgPAMgMQAMgMAPgJQAPgJARgFQARgEATAAQASAAARAEQARAFAPAJQAPAJAMAMQANAMAIAPQAJAPAFARQAEARAAARQAAASgEARQgFARgJAPQgIAPgNAMQgMAMgPAJQgPAJgRAEQgRAFgSAAQgTAAgRgFgAD/gwQgKAEgHAHQgGAHgEAKQgEAKAAAKQAAAKAEAKQAEAKAGAHQAHAHAKAEQAJAEALAAQALAAAKgEQAJgEAHgHQAHgHADgKQAEgKAAgKQAAgKgEgKQgDgKgHgHQgHgHgJgEQgKgEgLAAQgLAAgJAEgAlkCAQgRgEgPgJQgPgJgMgMQgMgMgJgPQgJgPgEgRQgFgRAAgSQAAgRAFgRQAEgRAJgPQAJgPAMgMQAMgMAPgJQAPgJARgFQARgEATAAQASAAARAEQARAFAPAJQAPAJAMAMQANAMAIAPQAJAPAFARQAEARAAARQAAASgEARQgFARgJAPQgIAPgNAMQgMAMgPAJQgPAJgRAEQgRAFgSAAQgTAAgRgFgAlUgwQgKAEgHAHQgGAHgEAKQgEAKAAAKQAAAKAEAKQAEAKAGAHQAHAHAKAEQAJAEALAAQALAAAKgEQAJgEAHgHQAHgHADgKQAEgKAAgKQAAgKgEgKQgDgKgHgHQgHgHgJgEQgKgEgLAAQgLAAgJAEgAurB/QgTgGgRgLIABAAQgFgDgDgEQgDgEADgFIAegrQAFgGAEAAQAFgBAIAFQAHAGAJACQAIAEAKAAQAPAAANgJQAMgIAHgOIhIAAIgGgBIgFgDIgDgFIgBgEIAAgkQAAgGAEgDQAFgDAGAAIBIAAQgIgNgMgIQgMgIgPAAQgKAAgIADQgIACgIAGQgIAFgFgBQgFAAgEgGIgdgqQgDgGADgEQADgEAEgDIAAAAQAQgLATgFQATgGAWAAQATAAASAFQARAEAQAJQAPAJAMAMQANAMAJAPQAJAPAEARQAFARAAARQAAASgFARQgEARgJAPQgJAPgNAMQgMAMgPAJQgQAIgRAFQgSAFgTAAQgWAAgTgGgAMTCBQgEAAgCgCQgCgCAAgDIAAjzQAAgIAIAAIBDAAQAJAAAAAIIAABMIAqAAQASAAAOAHQAPAIALANQAKAMAGAOQAFAQAAAPQAAAQgGAQQgGAQgKANQgLANgPAHQgPAIgSAAgANfBCIAWAAQAFAAAEgCIAHgGIAEgIIABgJIgBgKIgEgIIgHgGQgEgCgFAAIgWAAgAKgCBQgIAAgBgHIgMhjIgUBjIgBADIgDADIgCABIgCAAIg+AAIgEgBQgEgCAAgEIgUhiIgMBiQAAAHgIAAIhEAAQgIAAABgHIAYjzIADgFQACgDAEAAIBIAAQAIAAADAIIAmB8IAnh8QACgIAIAAIBJAAQAEAAACADIADAFIAYDzQAAADgCACQgCACgEAAgAAYCBQgIAAAAgHIAAhdIhIAAIAABdQAAAHgIAAIhEAAQgHAAgBgGIAAj0IADgFQACgDADAAIBEAAIAFADQADACAAADIAABMIBIAAIAAhMQAAgDACgCQACgDAEAAIBEAAIAGACQACABAAAEIAAD0QAAADgCACQgCACgDAAgAoiCBQgFAAgFgCQgFgDgCgDIAAAAIg7hKIgHACIAABEQAAAMgRAAIgxAAQgIAAgEgDQgEgDAAgGIAAjpQAAgFAEgEQAEgEAIAAIAxAAIAGABIAFADIAEAEIACAFIAABLIAJgPIABgCQAJgPAKgNQAKgNAMgKQANgJAQgGQAQgFAVAAQAHAAADADQAEADAAAFIAAAuQAAAEgEAEQgEADgHAAQgFAAgGAFIgMAMIgfArIBgBzQADAFAAADQAAADgDACQgDACgFAAg");
	this.shape.setTransform(-0.9,-37.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-99.4,-51,197,26.7);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABuBRQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgYIhKAAIAAAZQAAABgBAAQAAABAAAAQgBAAAAAAQgBABgBAAIgXAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAg2QAAgDADAAIANAAIAKgVIAFgcIACgvQAAAAABgBQAAAAAAgBQABAAAAAAQABAAABAAIBQAAIACABIABABIAABgIAKAAIADAAIABADIAAA1QAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAgABDgMIgKAhIAhAAIAAhCIgTAAgAhZA5IAAgcIABgCIACgCIAFAAIADgBIAEgDIADgFIACgGIgihSIAAgBIAAgBQAAgEAFABIAYAAIADABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAAAIARAzIAPgzIACgCIADgBIAZAAIADABIAAACIAAABIgiBYIgBABIgGAQIgGALIgJAJQgFAEgGACQgGACgIAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAgADNA0QgJgCgIgEQgHgFgHgGQgGgGgEgIQgFgIgCgIQgCgHgBgJQABgKACgIQACgJAFgIQAEgHAGgGQAHgHAHgEQAIgEAJgDQAJgCAJAAQAKAAAIACQAIADAJAEQAHAEAGAHQAGAGAEAHQAFAIACAJQADAIAAAKQAAAJgDAHQgCAIgFAIQgEAIgGAGQgGAGgHAFQgJAEgIACQgIADgKAAQgJAAgJgDgADRgsQgGADgEAEQgFAGgDAGQgCAHAAAGQAAAIACAFQADAGAFAFQAEAEAGADQAGADAIAAQAIAAAFgDQAHgDAEgEQAEgFADgGQADgFAAgIQAAgGgDgHQgDgGgEgGQgEgEgHgDQgFgCgIgBQgIABgGACgAlDA0QgJgCgHgEQgIgFgGgGQgGgGgFgIQgEgIgCgIQgDgHAAgJQAAgKADgIQACgJAEgIQAFgHAGgGQAGgHAIgEQAHgEAJgDQAJgCAJAAQAKAAAIACQAJADAIAEQAHAEAGAHQAHAGAEAHQAEAIADAJQADAIAAAKQAAAJgDAHQgDAIgEAIQgEAIgHAGQgGAGgHAFQgIAEgJACQgIADgKAAQgJAAgJgDgAk/gsQgGADgEAEQgFAGgCAGQgCAHgBAGQABAIACAFQACAGAFAFQAEAEAGADQAHADAHAAQAIAAAFgDQAHgDAFgEQAEgFACgGQADgFAAgIQAAgGgDgHQgCgGgEgGQgFgEgHgDQgFgCgIgBQgHABgHACgApZA0QgIgCgIgEQgHgFgGgGQgHgGgEgIQgEgIgCgIQgDgHAAgJQAAgKADgIQACgJAEgIQAEgHAHgGQAGgHAHgEQAIgEAIgDQAKgCAJAAQAJAAAJACQAIADAIAEQAIAEAGAHQAGAGAFAHQAEAIACAJQADAIAAAKQAAAJgDAHQgCAIgEAIQgFAIgGAGQgGAGgIAFQgIAEgIACQgJADgJAAQgJAAgKgDgApUgsQgGADgEAEQgFAGgCAGQgDAHAAAGQAAAIADAFQACAGAFAFQAEAEAGADQAHADAHAAQAHAAAHgDQAFgDAFgEQAFgFACgGQACgFABgIQgBgGgCgHQgCgGgFgGQgFgEgFgDQgHgCgHgBQgHABgHACgAO2A1IgDgBIgBgDIAAhKIgvBLIgBACIgCABIgdAAIgDgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAh7IABgCIADgBIAZAAIADABIACACIAABHIAthIIACgBIACgBIAdAAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAIABACIAAB7IgBACQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAgAMlA1IgEgBIgBgDIAAhKIguBLIgCACIgCABIgdAAIgCgBIgBgDIAAh7QAAAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAIADgBIAZAAIACABIADACIAABHIAshIIADgBIACgBIAdAAQABAAAAAAQABAAAAAAQAAAAABAAQAAABAAAAIABACIAAB7IgBACQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAKSA1IgDgBIgBgDIAAgxIgsAAIAAAxIgBACQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgaAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBgBgBIAAh7IABgCQABAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAaAAIAEABIABACIAAArIAsAAIAAgrIABgCQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIAaAAIADABQAAAAABAAQAAAAAAABQAAAAAAABQABAAAAAAIAAB7IgCADIgDABgAIQA1IgEgBIgBgDIgHgSIgwAAIgGASQgBAEgEAAIgaAAIgCgBIgBgCIAAgBIAwh7IACgCIADgBIAWAAIADABIACABIAxB8IAAABQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAgAHeADIAcAAIgNgngAE8A1IgCgBIgBgDIAAh7IABgCIACgBIA5AAQAIAAAGACQAIADAFAGQAFAFADAHQADAHAAAIQAAAGgCAGQgCAGgEAFQAHAGADAHQAEAHAAAJQAAAIgDAHQgEAHgFAGQgFAFgHADQgHAEgIAAgAFbAbIAVAAQADAAADgCIADgDIADgFIABgFIgBgGIgDgEIgDgCQgDgBgDgBIgVAAgAFbgZIAQAAIAFgBQADgBACgCIADgEIABgGIgBgEIgDgFIgEgCIgGgBIgQAAgAjTA1IgDgBIgBgDIAAh7IABgCIADgBIA5AAQAGgBAFACIAKAFIAIAHQAEAEADAFIADAKIACALQAAAIgDAHQgCAIgGAGQgFAFgIADQgIAEgIgBIgbAAIAAArQAAAEgFAAgAi0gUIATAAIAGgBIADgDIADgFIABgFIgBgGIgDgFIgEgDIgFgBIgTAAgAnoA1QgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBIgBgCIAAh7IABgCIAEgBIBSAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIAAACIAAAXIAAACIgDABIg0AAIAAARIAbAAQAJABAIADQAHAEAFAGQAGAGACAHQADAHAAAIQAAAHgDAJQgDAHgFAGQgGAGgHADQgHAEgJAAgAnKAYIATAAIAGgBIAEgCIACgFIACgFIgCgGIgCgEIgEgCQgDgBgDgBIgTAAgArrA1IgDgBIgCgDIgGgSIgwAAIgGASQgCAEgDAAIgbAAIgCgBIgBgCIABgBIAvh7IACgCIAEgBIAWAAIADABIACABIAwB8IABABQAAADgEAAgAscADIAbAAIgNgngAuAA1IgDgBIAAgDIAAgxIgtAAIAAAxIgBACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgZAAQgEAAgBgEIAAh7IABgCQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIAaAAIADABIABACIAAArIAtAAIAAgrIAAgCQABAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIAaAAIAEABQAAAAAAAAQAAAAABABQAAAAAAABQAAAAAAAAIAAB7IgBADIgDABg");
	this.shape.setTransform(0,-20.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-98,-28.7,196,16.2);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],0,-10.8,0,4).s().p("A8iBHIAAiOMA5FAAAIAACOg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-182.8,-7.2,365.6,14.4);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EghjAI0IAAxnMBDHAAAIAARng");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-214.8,-56.4,429.6,112.8);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ASwL9QgogLgjgUQgjgVgdgdQgdgdgVgjQgUgkgMgpQgLgoAAgtQAAgqALgpQALgoAVgkQAVgiAcgdQAdgdAkgUQAjgWApgLQApgLAsAAQBAAAA6AZIAmATIAiAXQAIAFABAGQABAHgEAEIgLAOQgGAHgGABQgFABgMgJQgjgagpgOQgogPgrAAQgnAAgjAJQgjALgeARQgeATgYAYQgZAagRAdQgRAegKAiQgKAhAAAjQAAAlALAiQAKAiASAeQASAeAZAZQAZAaAdASQAeASAhAKQAhAKAjAAIAsgEIAsgMIArgUIAngaQAGgEAHABQAGABAGAJIAHAKIACAOQAAAHgIAFIhGApQg7AZhBAAQgrAAgpgMgEBEvAMFIgMgIIgJgMIgCgQIACgPIAJgMIAMgIIAPgDIAPADIAMAIIAIAMIADAPIgDAQIgIAMIgMAIIgPADgAzxMAIgCgCQgMgBAAgNIAApJQAAgQAQAAIARAAQAPAAAAAQIAADaICoAAQAoAAAjAPQAjAPAZAaQAaAbAPAiQAPAjAAAnQAAAngPAjQgPAjgaAaQgaAagjAQQgjAPgoAAgAzPLQICnAAQAeAAAbgLQAagLATgUQATgUALgaQAMgaAAgeQAAgegMgZQgLgbgTgTQgUgUgagMQgagKgegBIinAAgEA6kAL/QgPAAAAgOIAApKQAAgMALgDIADgBIDIAAQApAAAjAPQAjAQAZAaQAaAaAPAjQAPAiAAAoQAAAngPAiQgOAkgaAZQgaAbgjAPQgiAOgpAAIinAAIAADcQAAAOgQAAgEA7FAHmICmAAQAeABAbgLQAZgNAUgTQATgUAMgaQALgaAAgeQAAgdgLgaQgMgbgTgTQgTgUgagMQgagLgfAAIimAAgEAyRAL/QgSABAAgTIAApDQAAgIAEgFQAFgGAJAAIGTAAQAHAAAGAFQAFAEAAAKIAAAKQAAAHgFAGQgFAFgIAAIl2AAIAADqIEvAAQAIAAAFAEQAFAFAAAJIAAAKQAAAHgEAHQgFAFgJAAIkvAAIAADxIF/AAQAHAAAGAFQAFAEAAAJIAAAKQAAAIgFAGQgFAGgIgBgEApgAL/QgIABgGgGQgFgFAAgJIAApCQAAgIAFgFQAGgGAIAAIDxAAQAhAAAdAMQAdANAWAVQAWAWAMAeQAMAcAAAiQAAAogSAkQgSAkgfAZQAXAJATAOQATAPAOATQANATAIAYQAIAXAAAaQAAAigMAfQgNAfgWAYQgXAWgeAPQgeANgkAAgEAp7ALRID0AAQAYAAAVgJQAWgKAQgRQAQgRAKgWQAJgXAAgaQAAgYgJgWQgJgWgQgPQgQgPgWgIQgWgJgYAAIj0AAgEAp7AG0IDWAAQAZAAAUgLQAVgJAPgSQAPgRAHgXQAIgWAAgZQAAgZgIgUQgIgVgOgPQgPgQgVgIQgUgJgZAAIjWAAgEAhSAL/QgPAAAAgOIAApKQAAgMALgDIADgBIDIAAQApAAAjAPQAjAQAZAaQAaAaAPAjQAPAiAAAoQAAAngPAiQgOAkgaAZQgaAbgjAPQgiAOgpAAIinAAIAADcQAAAOgQAAgEAhzAHmICmAAQAeABAbgLQAZgNAUgTQATgUAMgaQALgaAAgeQAAgdgLgaQgMgbgTgTQgTgUgagMQgagLgfAAIimAAgAY/L/QgSABAAgTIAApDQAAgIAEgFQAFgGAJAAIGTAAQAHAAAGAFQAFAEAAAKIAAAKQAAAHgFAGQgFAFgIAAIl2AAIAADqIEvAAQAIAAAFAEQAFAFAAAJIAAAKQAAAHgEAHQgFAFgJAAIkvAAIAADxIF/AAQAHAAAGAFQAFAEAAAJIAAAKQAAAIgFAGQgFAGgIgBgAJpL/QgJABgGgGIgJgNIg4iFIlMAAIg2CCQgHAWgTgBIgKAAQgNAAAAgKIACgJIDxpCIAHgNQAEgGAIAAIAPAAIAIADIAGAGIAEAHIACAFIDxJBIABAGIgEAKIgJACgAIFI4IiSleIiSFeIEkAAgAgcL/QgPAAAAgOIAAkVImWAAIAAEVQAAAOgPAAIgRAAQgPAAAAgOIAApMIADgKQAEgFAIABIARAAQAHgBAEAFIAEAKIAAEIIGWAAIAAkIIAEgKQAEgFAHABIARAAIALADQACAFAAAGIAAJMQAAAOgNAAgA5IL/QgSABAAgTIAAonIjAAAQgSAAAAgSIAAgKQgBgTATAAIGtAAQAHAAAGAFQAFAEAAAKIAAAKQAAAHgFAGQgFAFgIAAIi+AAIAAInQAAATgUgBgA+aL/QgTABAAgUIAAoEImkISQgEAGgJgBIgRAAQgIABgFgGQgGgFAAgJIAApCQAAgJAGgFQAGgFAHAAIALAAQAIAAAFAGQAFAFAAAIIAAIHIGloUQADgGAJAAIAQAAQAHAAAGAGQAGAFAAAIIAAJCQAAAUgSgBgEgrMAL/QgSABAAgTIAAonIjAAAQgSAAAAgSIAAgKQgBgTATAAIGtAAQAHAAAGAFQAFAEAAAKIAAAKQAAAHgFAGQgFAFgIAAIi+AAIAAInQAAATgUgBgEgv+AL/QgJABgGgGIgKgNIg3iFIlNAAIg1CCQgIAWgSgBIgKAAQgOAAAAgKIACgJIDxpCIAHgNQAFgGAHAAIAQAAIAHADIAGAGIAFAHIACAFIDxJBIABAGIgEAKIgKACgEgxjAI4IiSleIiSFeIEkAAgEg/aAL/QgPAAAAgOIAApKQAAgMAMgDIACgBIDJAAQAoAAAjAPQAjAQAaAaQAaAaAPAjQAOAiAAAoQAAAngOAiQgPAkgaAZQgZAbgjAPQgjAOgoAAIioAAIAADcQAAAOgPAAgEg+5AHmICnAAQAeABAagLQAagNATgTQAUgUALgaQAMgaAAgeQAAgdgMgaQgLgbgTgTQgUgUgagMQgagLgeAAIinAAgEhEzAL/QgSABAAgTIAAonIjAAAQgSAAAAgSIAAgKQgBgTATAAIGtAAQAHAAAGAFQAFAEAAAKIAAAKQAAAHgFAGQgFAFgIAAIi+AAIAAInQAAATgUgBgEBE5AKEQgJAAgFgHQgGgGAAgIIAAhGQAAgYAIgTQAJgSANgQIAdgcIBFgyIAdgcQAOgPAIgTQAHgTAAgYQAAgggLgZQgNgZgUgRQgVgSgcgIQgcgJgfAAQggAAgcAKQgbAKgVASQgUATgLAaQgMAaAAAgQAAAHgGAHIgMAIIgMAAQgIAAgEgFIgHgKIAAgFQABgqARgjQAPgiAcgaQAbgaAkgOQAjgPApAAQAqAAAkANQAkAMAbAZQAbAXAQAhQAPAjAAAoQAAAogNAcQgOAcgUAVQgVAWgXAQIgsAhQgUAQgOARQgNARABAXIAABHQAAAJgGAGQgGAGgIAAgEhEIgAzQgvgNgpgYQgpgYghghQgigjgYgpQgYgpgNgwQgOguAAg1QAAgxAOgvQAMgwAZgpQAYgoAhgiQAighApgZQAqgYAvgNQAwgNAzAAQBLAABEAdIAsAVIAoAcQAIAGACAHQABAHgFAFIgNARQgHAIgGABQgGABgOgKQgpgegwgRQgvgSgyABQgtAAgpALQgoALgjAWQgjAUgcAdQgdAdgVAjQgUAjgLAoQgLAnAAAoQAAArAMAoQALAnAVAkQAVAiAeAeQAdAdAiAWQAjAVAmALQAmAMApAAIA0gFIAzgNIAzgXIAsgeQAIgGAIACQAHABAHALIAIALIADAQQgBAIgJAGIhRAwQhFAdhMAAQgzAAgvgOgEBBGgA0QgvgNgpgYQgpgYghghQgigjgYgoQgYgpgNguQgNgwAAgyQAAg0ANguQANgwAYgpQAYgoAigjQAhghApgZQApgYAvgNQAvgMAzAAQAzAAAvAMQAvANApAYQApAZAiAhQAhAiAYApQAYApAOAwQANAvAAAzQAAAygNAwQgOAugYApQgYApghAiQgiAhgpAYQgpAYgvANQgvAMgzAAQgzAAgvgMgEBBWgLEQgpAMgiAUQgjAVgdAbQgcAdgUAjQgUAigMAoQgLAoAAArQAABAAZA5QAYA5AqArQArApA5AZQA5AZBAgBQAsAAAogLQAngKAjgVQAigVAdgbQAcgdAVgiQAUgjALgoQALgoAAgrQAAhBgYg5QgZg4gqgqQgrgqg5gZQg4gZhBAAQgrAAgnALgAbCg0QgvgNgogYQgqgYghghQgigjgYgoQgYgpgNguQgNgwAAgyQAAg0ANguQANgwAYgpQAYgoAigjQAhghAqgZQAogYAwgNQAugMA0AAQAyAAAvAMQAwANApAYQAoAZAiAhQAhAiAYApQAYApAOAwQANAvAAAzQAAAygNAwQgOAugYApQgYApghAiQgiAhgoAYQgpAYgwANQgvAMgzAAQgzAAgvgMgAbSrEQgoAMgjAUQgjAVgcAbQgcAdgVAjQgUAigLAoQgLAoAAArQAABAAYA5QAZA5AqArQAqApA5AZQA5AZBBgBQArAAAogLQAngKAjgVQAigVAdgbQAcgdAVgiQAUgjALgoQALgoAAgrQAAhBgYg5QgZg4gqgqQgrgqg5gZQg4gZhAAAQgsAAgnALgAj4g0QgwgNgogYQgpgYgighQghgjgYgoQgZgpgNguQgMgwAAgyQAAg0AMguQANgwAZgpQAYgoAhgjQAighApgZQApgYAvgNQAvgMAzAAQAzAAAvAMQAvANAnAYQApAZAiAhQAhAiAYApQAYApAOAwQANAvAAAzQAAAygNAwQgOAugYApQgYApghAiQgiAhgpAYQgnAYgvANQgvAMgzAAQgzAAgvgMgAjprEQgoAMgiAUQgjAVgdAbQgcAdgUAjQgVAigLAoQgLAoAAArQAABAAZA5QAYA5AqArQArApA5AZQA4AZBBgBQAsAAAngLQAogKAhgVQAigVAcgbQAdgdAUgiQAVgjAKgoQAMgoAAgrQAAhBgYg5Qgag4gqgqQgqgqg3gZQg5gZhAAAQgrAAgoALgEgvXgA0QgvgNgpgYQgpgYghghQgigjgYgoQgYgpgNguQgNgwAAgyQAAg0ANguQANgwAYgpQAYgoAigjQAhghApgZQApgYAvgNQAvgMAzAAQAzAAAvAMQAwANAoAYQApAZAiAhQAhAiAYApQAYApAOAwQANAvAAAzQAAAygNAwQgOAugYApQgYApghAiQgiAhgpAYQgoAYgwANQgvAMgzAAQgzAAgvgMgEgvHgLEQgpAMgiAUQgjAVgdAbQgcAdgUAjQgUAigLAoQgLAoAAArQAABAAYA5QAYA5AqArQArApA5AZQA5AZBAgBQAsAAAogLQAngKAjgVQAigVAdgbQAcgdAVgiQAUgjALgoQALgoAAgrQAAhBgYg5QgZg4gqgqQgrgqg5gZQg4gZhBAAQgrAAgnALgEgm8gA0QgGgFAAgMIAAgKQAAgKAGgGQAGgFAJgBQASgCAQgJQAPgIAMgNQAMgOAGgRQAGgRAAgRIAAokQAAgIAGgGQAFgHAKAAIHSAAQAJAAAGAGQAIAGAAAJIAAKlQAAAVgXAAIgMAAQgVAAAAgVIAAqBImOAAIAAIAQAAAfgLAZQgLAcgTAUQgTAUgZAMQgaANgeADQgIgBgHgFgA6+gvIgDgCQgNgBAAgQIAAqrQAAgSASAAIAUAAQARAAAAASIAAD/IDEAAQAvAAApASQAoASAeAeQAfAeARAoQARApAAAuQAAAtgRApQgRAogfAfQgeAfgpASQgpARgvABgA6XhnIDDAAQAkAAAegNQAfgNAXgXQAWgXANgfQANgfAAgiQAAgkgNgdQgNgfgXgWQgXgYgegNQgfgNgjAAIjDAAgEA6ZgAwQgRAAAAgRIAAlDInZAAIAAFDQAAARgSAAIgUAAQgRAAAAgRIAAqtIAEgNQAEgEAJAAIAUAAQAIAAAFAEIAFANIAAEzIHZAAIAAkzIAEgNQAFgEAIAAIAUAAIANAEQAFAFAAAIIAAKtQAAARgSAAgEApogAwQgTAAAAgRIAAksIgBgBIgegEIgagKIjyE5IgKAJIgLAGIgLADIgiAAQgMAAAAgGIACgJIEQlZIgWgaIh5jJIgpg0IgZgRQgMgGgRAAIgcAAQgJAAgFgEQgFgGAAgIIAAgUQAAgJAFgFIAOgEIAUAAQAiAAAaANQAaANAVAWQAUAVARAbIBpC0IAWAeQAPAWAUAJQATAKAYAAIAAlJQAAgTASABIAVAAQAIAAAFAEIAEAOIAAFJQAWAAATgLQATgJAPgVIB+jSQARgbAVgVQAVgWAZgNQAbgNAjAAIATAAIAOAEQAFAFAAAJIAAAUIgFANIgMAFIgeAAQgRAAgNAGIgZARIgVAYIh3DGIgrA5IEPFZIACAHQAAACgCAEQgFACgEAAIgnAAIgKgDIgRgPIjzk5IgZAKIgcAEIAAEtQAAARgRAAgAUxgwQgWAAAAgWIgupCIj5ImQgHATgPAAIgLAAQgOAAgIgTIj7omIguJCQAAAWgWAAIgMAAQgVAAAAgWIAzqkQAAgIAFgGQAGgHALAAIASAAQAKAAAEAGIETJPIENpPQAGgGAJAAIATAAQAJAAAHAGQAHAGAAAJIA0KkQAAAWgXAAgAp7gwQgJAAgIgGIgPgOIkglZIg4AjIgeAKIgjAFIAAEqQAAARgRAAIgVAAQgSAAAAgRIAAqsQAAgTASABIAVAAQAHAAAGAEIAEAOIAAFNQAZAAAZgLQAZgKAXgXIAcghICIi2QAUgaAXgTQAXgUAbgNQAcgMAjABQAJAAAEAEIADAKIAAAWIgDAKIgKAFQgfAAgZARQgbARgYAcIiaDFIFKGIIACAFIgDAGIgHADgEg1agAwQgJAAgIgGIgPgOIkglZIg4AjIgeAKIgiAFIAAEqQAAARgSAAIgUAAQgTAAAAgRIAAqsQAAgTATABIAUAAQAIAAAFAEIAFAOIAAFNQAZAAAZgLQAZgKAWgXICkjXQAVgaAWgTQAXgUAcgNQAcgMAiABQAKAAADAEIADAKIAAAWIgDAKIgKAFQgeAAgaARQgbARgYAcIiaDFIFKGIIACAFIgCAGIgHADg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-463.3,-77.7,926.6,155.5);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AwnF8Ii2AAQhgAAAAhgIAAqwIAAAAQAHhSBZAAMAm8AAAQBYAAAHBSIAAAAIAAKwQAABghfAAMgihAAAIhlBrg");
	this.shape.setTransform(0,23.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-134.3,-24.9,268.6,97.4);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5F6063").s().p("AMmLZQgogLgjgVQgjgUgdgdQgdgdgUgjQgVgjgLgoQgLgpAAgrQAAgrALgpQALgoAVgkQAUgiAdgeQAdgcAjgWQAjgUApgLQAogMAsAAQArAAApAMQAoALAjAUQAjAWAdAcQAdAdAUAjQAVAkAMAoQALApAAAsQAAArgLAoQgMApgVAiQgUAkgdAcQgdAdgjAUQgjAVgoALQgpALgsAAQgrAAgpgLgAM0CnQgjAKgdARQgeASgZAXQgYAagRAdQgSAegJAiQgKAiAAAkQAAA4AVAxQAVAxAkAkQAlAkAxAVQAwAVA4AAQAlAAAigKQAigJAegSQAdgRAZgYQAYgZASgdQARgeAJgiQAKgjAAglQAAg2gVgxQgVgxgkgkQglgkgxgWQgwgUg3AAQglgBgiAKgAnzLZQgogLgjgVQgjgUgdgdQgdgdgUgjQgVgjgLgoQgLgpAAgrQAAgrALgpQALgoAVgkQAUgiAdgeQAdgcAjgWQAjgUApgLQAogMAsAAQArAAApAMQAoALAjAUQAjAWAdAcQAdAdAUAjQAVAkAMAoQALApAAAsQAAArgLAoQgMApgVAiQgUAkgdAcQgdAdgjAUQgjAVgoALQgpALgsAAQgrAAgpgLgAnlCnQgjAKgdARQgeASgZAXQgYAagRAdQgSAegJAiQgKAiAAAkQAAA4AVAxQAVAxAkAkQAlAkAxAVQAwAVA4AAQAlAAAigKQAigJAegSQAdgRAZgYQAYgZASgdQARgeAJgiQAKgjAAglQAAg2gVgxQgVgxgkgkQglgkgxgWQgwgUg3AAQglgBgiAKgAgkLZQgGgEAAgKIAAgJQAAgJAFgFQAGgEAIgBQAPgCALgHQAOgHAKgLQAKgMAFgPQAGgOAAgPIAAnWQAAgHAFgFQAEgGAJAAIGPAAQAHAAAGAGQAHAEAAAIIAAJFQAAASgUAAIgKAAQgSAAAAgSIAAomIlWAAIAAG3QAAAagJAXQgKAXgQARQgQARgWAKQgWALgXADQgIAAgFgFgA22LdQgPAAgIgNIivkAIiuEAQgIANgPAAIgWAAQgRAAAMgRIDFkkIjCkdQgJgNABgFQABgEANgBIAPAAIARAEIAOAOICpD7ICpj7IAOgOIARgEIAPAAQAOABABAEQAAAFgIANIjDEdIDFEkQAMARgQAAgEAthALdQgTAAAAgTIAAoGImkITQgEAGgJAAIgRAAQgIAAgFgGQgGgGAAgHIAApEQAAgIAGgEQAGgGAHAAIALAAQAIAAAFAGQAFAFAAAHIAAIIIGloUQADgGAJAAIAQAAQAHAAAGAGQAGAFAAAIIAAJDQAAATgSAAgEAjiALdQgTAAAAgTIAAoGImkITQgEAGgJAAIgRAAQgIAAgFgGQgGgGAAgHIAApEQAAgIAGgEQAGgGAHAAIALAAQAIAAAFAGQAFAFAAAHIAAIIIGloUQADgGAJAAIAQAAQAHAAAGAGQAGAFAAAIIAAJDQAAATgSAAgAUyLdQgJAAgEgGQgFgGAAgGIAApFQAAgSASAAIFjAAQAIAAAFAGQAFAGAAAHIAAAKQAAAKgFAEQgGAFgHgBIlFAAIAAIoQAAAHgHAFQgFAFgIABgAtiLdQgPAAAAgQIAAkVImWAAIAAEVQAAAQgPAAIgRAAQgPAAAAgQIAApKIADgLQAEgEAIgBIARAAQAHABAEAEIAEALIAAEHIGWAAIAAkHIAEgLQAEgEAHgBIARAAIALAFQAEAEAAAHIAAJKQAAAQgPAAgEgk8ALdQgSAAAAgSIAApFQAAgHAEgFQAFgGAJAAIGTAAQAHAAAGAFQAFAFAAAIIAAAKQAAAIgFAGQgFAGgIgBIl2AAIAADpIEvAAQAIAAAFAFQAFAFAAAJIAAAKQAAAIgEAGQgGAFgIAAIkvAAIAADxIF/AAQAHAAAGAFQAFAFAAAIIAAALQAAAGgFAHQgFAGgIAAgEgqYALdQgSAAAAgSIAAooIjAAAQgSABAAgUIAAgKQAAgSASAAIGtAAQAIAAAFAFQAFAFAAAIIAAAKQAAAIgFAGQgEAGgJgBIi+AAIAAIoQAAASgTAAgA4lh2QgogLgjgWQgjgTgdgdQgdgegUgiQgVgkgLgoQgLgoAAgsQAAgrALgoQALgpAVgkQAUgiAdgeQAdgcAjgVQAjgUApgMQAogLAsAAQArAAApALQAoAMAjAUQAjAVAdAcQAdAeAUAiQAVAkAMApQALAoAAAsQAAArgLAoQgMApgVAjQgUAjgdAdQgdAdgjATQgjAWgoALQgpAKgsAAQgrAAgpgKgA4XqpQgjAKgdARQgeASgZAYQgYAZgRAdQgSAegJAiQgKAjAAAkQAAA4AVAwQAVAxAkAkQAlAlAxAUQAwAWA4AAQAlgBAigJQAigJAegSQAdgRAZgZQAYgYASgeQARgdAJgjQAKgiAAglQAAg3gVgxQgVgxgkgkQglgkgxgVQgwgVg3AAQglAAgiAJgAo6h2QgGgEAAgLIAAgJQAAgIAFgFQAGgFAIgBQAPgBANgIQAOgGAKgMQAKgMAFgPQAGgOAAgPIAAnVQAAgHAFgGQAEgFAJAAIGPAAQAIgBAFAGQAHAFAAAIIAAJEQAAASgUAAIgKAAQgSAAAAgSIAAomIlWAAIAAG3QAAAagJAXQgKAYgQARQgQARgWAKQgWALgZACQgIABgFgFgAclhzIgDgBQgLgBAAgNIAApKQAAgPAPAAIASAAQAPAAAAAPIAADbICoAAQAogBAjAPQAjAQAZAaQAaAaAPAjQAPAiAAAnQAAAngPAkQgPAigaAbQgZAagkAQQgjAOgoAAgAdHiiICnAAQAeAAAagLQAbgLATgVQATgTALgbQALgaAAgeQAAgdgLgaQgLgagTgUQgUgTgagMQgagLgeAAIinAAgAP4hzQgIABgEgFQgEgEAAgHIAAjZQgKAPgRANIgmAVIgsAPQgWAEgVAAQglABghgOQgggOgYgZQgZgZgNggQgOggAAgmIAAkDQAAgGAEgFIAMgDIARAAIALADQAEAEAAAHIAAENQACAYALAWQALAXASAQQASARAXAKQAXAKAaAAQAZAAAagJQAagKAWgQQAVgQAOgVQAOgXACgYIAAkQQAAgPAPABIASAAQAPgBAAAPIAAJLIgEALQgEAFgHgBgEAnPgBzQgSAAAAgSIAApEQAAgHAEgGQAFgFAJAAIGTAAQAHAAAGAEQAFAFAAAJIAAAKQAAAHgFAGQgFAGgIAAIl2AAIAADpIEvAAQAIAAAFAEQAFAFAAAJIAAAKQAAAIgEAGQgFAGgJgBIkvAAIAADyIF/AAQAHgBAGAGQAFAEAAAJIAAAKQAAAHgFAHQgFAFgIAAgEAkTgBzQgPAAAAgPIAApLQAAgPAPAAIARAAIALAEIAEALIAAJLQAAAPgPAAgAZzhzQgPAAAAgPIAAkVImVAAIAAEVQAAAPgQAAIgRAAQgPAAAAgPIAApLIAEgLQADgEAIAAIARAAQAHAAAEAEIAFALIAAEHIGVAAIAAkHIAEgLQAEgEAHAAIARAAIALAEQAFAEAAAHIAAJLQAAAPgQAAgAIohzQgJAAgGgFIgJgNIg4iGIlMAAIg2CDQgHAVgTAAIgKAAQgNAAAAgLIACgIIDxpDIAHgNQAEgFAIAAIAPAAIAIACIAGAGIAEAIIACAFIDxJBIABAGIgEAJIgJADgAHEk7IiSleIiSFeIEkAAgAwXhzQgIAAgFgFQgGgGAAgIIAApCQAAgUATABIFeAAQAJAAAFAFQAEAGAAAIIAAAKQAAAJgFAFQgFAEgIAAIlBAAIAAC6IDFAAQAnAAAjAOQAjAQAaAaQAaAaAPAjQAPAiAAAoQAAAogPAjQgPAigaAaQgaAbgjAPQgjAPgoAAgAv6ihIDEAAQAfAAAagLQAagLAUgVQAUgTALgbQALgbAAgeQAAgegLgaQgLgbgUgUQgUgUgagLQgagMgfAAIjEAAg");
	this.shape.setTransform(-366.1,42.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-660.2,-31.5,588.3,148.1);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EhYPAYmMAAAgxLMCwfAAAMAAAAxLg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-564.8,-157.4,1129.7,314.9);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#000000","rgba(0,0,0,0)"],[0,1],0,0,0,0,0,30.5).s().p("AlOFPQiMiKAAjFQAAjECMiKQCKiMDEAAQDFAACKCMQCMCKAADEQAADFiMCKQiKCMjFAAQjEAAiKiMg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-47.5,-47.5,95,95);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dkdkdk();
	this.instance.parent = this;
	this.instance.setTransform(-22,-12);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22,-12,44,24);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.agahhah();
	this.instance.parent = this;
	this.instance.setTransform(-34.5,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.5,-45,69,90);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ajajaj();
	this.instance.parent = this;
	this.instance.setTransform(-10,-16);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10,-16,20,32);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.afag();
	this.instance.parent = this;
	this.instance.setTransform(-36.5,-83);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36.5,-83,73,166);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ArLE0QgRgEgPgJQgPgHgNgMQgNgNgJgPQgIgOgFgSQgGgRAAgUQABgRAEgQQAFgRAIgPQAIgPAMgMQAMgNAPgJQAPgKARgFQARgEATgBQAQABAOADQAOACALAGQALAEAJAHIATAPIAEAFQAAADgCAEIgyAuIgDACIgFgCIgHgGIgIgFIgKgDIgNgCQgKAAgJAFQgJAFgIAGQgGAIgEAJQgEAKAAAKQAAAKAEAKQAEAKAGAHQAHAHAJAGQAJAEALAAQAMAAAJgEQALgFAHgIIAEgCIADACIAzAxQACADgBACIgEAGQgTATgYAJQgXAKgZAAQgSAAgRgFgALTE1QgIgDgFgFQgGgGgDgIQgCgHAAgIQAAgJACgHQADgHAGgGQAFgGAIgDQAIgDAHAAQAKAAAHADQAHADAGAGQAFAGADAHQAEAHAAAJQAAAIgEAHQgDAIgFAGQgGAFgHADQgHADgKAAQgHAAgIgDgAGsE1QgIAAAAgHIAAj1QAAgEACgCQABgCAFAAIB0AAQAMAAALADQALAEAIAGQAJAHAHAIQAIAJAEAKQAGAKACAKQADALAAALQAAAQgFAPQgHAQgKAMQgKANgPAIQgOAIgSAAIgrAAIAABMQAAAHgIAAgAH3CjIAWAAQAGAAAEgCIAGgFIAFgIIABgKIgBgJIgFgIIgGgHQgEgBgGAAIgWAAgADCE1QgIAAAAgHIAAj1QAAgEACgCQACgCAEAAICyAAQADAAADACQACACAAAEIAAA4IgCAGQgCADgEAAIhmAAIAAAdIBQAAIAFACQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABIAAAsIgCAEQgCACgDAAIhQAAIAAAdIBrAAQADAAACACQACADAAADIAAA4IAAADIgDADQgBADgFAAgAg2E1QgIAAAAgHIAAj1QAAgEACgCQACgCAEAAIB0AAQAQAAANAHQAOAFALALQAKALAGANQAFAPAAAPQAAANgDAMQgEALgIAJQANAMAHAPQAHARAAARQAAAQgGAOQgGAOgLAKQgKALgOAGQgOAGgPAAgAAUD9IARAAQAGAAAEgDIAIgFIAGgIIABgJIgBgJIgGgJIgIgGQgEgCgGAAIgRAAgAAUCcIAKAAQAGAAAFgDQAEgCADgDIAGgIIABgKIgBgJIgGgIIgHgGQgFgCgGAAIgKAAgAkwE1QgIAAAAgHIAAj1QABgEABgCQACgCAEAAIB0AAQANAAALADQAKAEAJAGQAJAHAHAIQAHAJAFAKQAFAKADAKQACALAAALQAAAQgFAPQgGAQgKAMQgKANgPAIQgPAIgSAAIgqAAIAABMQAAAHgIAAgAjkCjIAWAAQAGAAADgCIAHgFIAEgIIABgKIgBgJIgEgIIgHgHQgDgBgGAAIgWAAgAoaE1QgHAAgBgHIAAj1QABgEACgCQACgCADAAICzAAQADAAADACQACACAAAEIAAA4IgCAGQgDADgDAAIhmAAIAAAdIBPAAIAFACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAsIgCAEQgCACgDAAIhPAAIAAAdIBqAAQADAAACACQACADAAADIAAA4IAAADIgCADQgCADgFAAgALGDbQgEAAgCgEQgCgCAAgDQAAgQAFgKQAEgLAHgHQAGgHAIgFIAagUQAEgGABgHIgCgHIgFgHIgHgEIgIgCIgHACIgHAEIgFAHIgCAIIAAACIAAAEIgEABIg5AAQgFAAgBgDIgCgEIAAgGQAAgTAIgPQAHgPANgLQAMgLARgGQAQgHARAAQASAAAQAIQAPAGAMAMQAMAMAGAQQAIAQgBASQAAAQgDAMQgEAKgFAIQgGAHgHAEIgLAJIgJAKQgEAFgBAJQAAAEgCACQgCADgDAAgAC1gpQgDgDAAgGIAAgzQAAgFADgEQAEgDAGAAIAGAAIAFgCIAEgEIAGgIIAAAAIAEgLIg/idIABACIgCgEIAAgDQAAgGADgCQAEgDAIAAIAvAAQAGAAAFADQAEACACAGIASA3IACAJIACAFIAVhFQACgGAEgDQAFgCAIAAIAtAAQAJAAADADQAEADAAAGIAAACIhCCqIAAAAIgBACIgIAVIAAgBIgEAMQgFALgJAKQgHAKgLAIQgJAHgNAEQgNAFgQAAQgGAAgFgDgAS2g0QgHABAAgIIAAhdIhKAAIAABdQAAAIgJgBIhDAAQgIAAAAgFIAAj3IADgFQABgCAEAAIBDAAIAGACQADACAAADIAABMIBKAAIAAhMQAAgDACgCQACgCADAAIBFAAIAFABQADABAAAEIAAD2QAAADgDACQgCACgCAAgAMng0QgIABAAgIIAAj1QAAgDACgCQACgCAEAAICzAAQACAAADACQACABAAAEIAAA5IgCAFQgCADgDAAIhnAAIAAAeIBPAAIAGABQAAABABAAQAAABAAAAQABABAAAAQAAABAAABIAAArIgCAFQgCACgEAAIhPAAIAAAcIBrAAQACAAADADQACACAAADIAAA4IAAAEIgCADQgDACgEAAgAKsg0QgGAAgEgCQgFgDgDgDIABABIg4hLIgEABIgDAAIAABFQAAAGgEADQgEADgIAAIgxAAQgRAAAAgMIAAhEIgDgBIgEgBIg4BLIAAgBQgCADgFADQgEACgGAAIhCAAQgNABAAgIIACgEIBfh4IgfgsIgMgMQgGgEgGgBQgGAAgEgDQgEgDgBgFIAAgtQABgGAEgDQADgDAHAAQAVAAAQAFQAQAGAMAKQANAJAKANIATAcIAGAPQAAAAAAABQABAAAAAAQABAAABAAQAAAAABAAIAAhKIABgFIAFgEIAFgCIAGgBIAxAAQAIAAAEADQAEAEAAAFIAABLIAJgOIABgDQAJgPAKgNQAKgNANgJQAMgKAQgGQAQgFAVAAQAHAAAEADQADADABAGIAAAtQgBAFgEADQgDADgIAAQgFABgGAEIgMAMIgaAlIgFAHIBgB4IABAEQgBADgDACQgDACgGAAgAhBg0QgIABAAgIIAAj1QAAgDACgCQABgCAFAAIByAAQAMAAALADQALAEAIAGQAJAHAIAIQAHAJAEAKQAGAKACAKQADALAAAKQAAARgFAPQgHAQgKAMQgKAMgPAIQgOAJgSgBIgrAAIAABMQAAAIgIgBgAAIjGIAWAAQAGAAAEgCIAGgFIAFgIIABgKIgBgJIgFgIIgGgGQgEgCgGAAIgWAAgAkSg0QgDAAgCgCQgCgCAAgDIAAj1QAAgHAHAAICnAAIADABIADACIABACIABADIAAA8QAAAEgCACQgDACgDAAIhaAAIAACwIgBADIgCACIgDACIgDAAgAoCg0QgJABABgIIAAj1QgBgDADgCQABgCAFAAICyAAQADAAACACQADABAAAEIAAA5IgDAFQgCADgDAAIhnAAIAAAeIBQAAIAGABQAAABAAAAQABABAAAAQAAABAAAAQABABAAABIAAArIgCAFQgDACgDAAIhQAAIAAAcIBrAAQADAAADADQACACAAADIAAA4IgBAEIgCADQgCACgEAAgAr8g0QgIABAAgIIAAj1QAAgDABgCQADgCAEAAIB0AAQAMAAALADQALAEAJAGQAIAHAHAIQAHAJAGAKQAEAKAEAKQACALAAAKQAAARgGAPQgFAQgLAMQgKAMgPAIQgPAJgSgBIgqAAIAABMQABAIgJgBgAqxjGIAXAAQAFAAAEgCIAHgFIADgIIABgKIgBgJIgDgIIgHgGQgEgCgFAAIgXAAgAvmg0QgIABAAgIIAAj1QAAgDACgCQACgCAEAAICzAAQADAAACACQADABAAAEIAAA5IgDAFQgCADgDAAIhnAAIAAAeIBPAAIAGABQAAABABAAQAAABAAAAQABABAAAAQAAABAAABIAAArIgCAFQgCACgEAAIhPAAIAAAcIBqAAQADAAADADQACACAAADIAAA4IgBAEIgBADQgCACgFAAgAxjg0QgQAAAAgMIAAiyIg8AAIAACyQAAAHgEACQgEADgIAAIg0AAQgHAAgEgDQgEgCAAgHIAAjrQAAgMAPAAIDEAAIAFABIAFACIAEAEIACAFIAADrQAAAMgQAAg");
	this.shape.setTransform(0,-6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.3,-37.3,256.7,62.7);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dym();
	this.instance.parent = this;
	this.instance.setTransform(-166,-43);

	this.instance_1 = new lib.dym();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-166,-955);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-166,-955,331,1909);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#999999").s().p("EgaAA0hMAAAhpBMA0BAAAMAAABpBg");
	this.shape.setTransform(0,66.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-166.5,-269.5,333.1,672.2);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("ArLE0QgRgEgPgJQgPgHgNgMQgNgNgJgPQgIgOgFgSQgGgRAAgUQABgRAEgQQAFgRAIgPQAIgPAMgMQAMgNAPgJQAPgKARgFQARgEATgBQAQABAOADQAOACALAGQALAEAJAHIATAPIAEAFQAAADgCAEIgyAuIgDACIgFgCIgHgGIgIgFIgKgDIgNgCQgKAAgJAFQgJAFgIAGQgGAIgEAJQgEAKAAAKQAAAKAEAKQAEAKAGAHQAHAHAJAGQAJAEALAAQAMAAAJgEQALgFAHgIIAEgCIADACIAzAxQACADgBACIgEAGQgTATgYAJQgXAKgZAAQgSAAgRgFgALTE1QgIgDgFgFQgGgGgDgIQgCgHAAgIQAAgJACgHQADgHAGgGQAFgGAIgDQAIgDAHAAQAKAAAHADQAHADAGAGQAFAGADAHQAEAHAAAJQAAAIgEAHQgDAIgFAGQgGAFgHADQgHADgKAAQgHAAgIgDgAGsE1QgIAAAAgHIAAj1QAAgEACgCQABgCAFAAIB0AAQAMAAALADQALAEAIAGQAJAHAHAIQAIAJAEAKQAGAKACAKQADALAAALQAAAQgFAPQgHAQgKAMQgKANgPAIQgOAIgSAAIgrAAIAABMQAAAHgIAAgAH3CjIAWAAQAGAAAEgCIAGgFIAFgIIABgKIgBgJIgFgIIgGgHQgEgBgGAAIgWAAgADCE1QgIAAAAgHIAAj1QAAgEACgCQACgCAEAAICyAAQADAAADACQACACAAAEIAAA4IgCAGQgCADgEAAIhmAAIAAAdIBQAAIAFACQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABIAAAsIgCAEQgCACgDAAIhQAAIAAAdIBrAAQADAAACACQACADAAADIAAA4IAAADIgDADQgBADgFAAgAg2E1QgIAAAAgHIAAj1QAAgEACgCQACgCAEAAIB0AAQAQAAANAHQAOAFALALQAKALAGANQAFAPAAAPQAAANgDAMQgEALgIAJQANAMAHAPQAHARAAARQAAAQgGAOQgGAOgLAKQgKALgOAGQgOAGgPAAgAAUD9IARAAQAGAAAEgDIAIgFIAGgIIABgJIgBgJIgGgJIgIgGQgEgCgGAAIgRAAgAAUCcIAKAAQAGAAAFgDQAEgCADgDIAGgIIABgKIgBgJIgGgIIgHgGQgFgCgGAAIgKAAgAkwE1QgIAAAAgHIAAj1QABgEABgCQACgCAEAAIB0AAQANAAALADQAKAEAJAGQAJAHAHAIQAHAJAFAKQAFAKADAKQACALAAALQAAAQgFAPQgGAQgKAMQgKANgPAIQgPAIgSAAIgqAAIAABMQAAAHgIAAgAjkCjIAWAAQAGAAADgCIAHgFIAEgIIABgKIgBgJIgEgIIgHgHQgDgBgGAAIgWAAgAoaE1QgHAAgBgHIAAj1QABgEACgCQACgCADAAICzAAQADAAADACQACACAAAEIAAA4IgCAGQgDADgDAAIhmAAIAAAdIBPAAIAFACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAsIgCAEQgCACgDAAIhPAAIAAAdIBqAAQADAAACACQACADAAADIAAA4IAAADIgCADQgCADgFAAgALGDbQgEAAgCgEQgCgCAAgDQAAgQAFgKQAEgLAHgHQAGgHAIgFIAagUQAEgGABgHIgCgHIgFgHIgHgEIgIgCIgHACIgHAEIgFAHIgCAIIAAACIAAAEIgEABIg5AAQgFAAgBgDIgCgEIAAgGQAAgTAIgPQAHgPANgLQAMgLARgGQAQgHARAAQASAAAQAIQAPAGAMAMQAMAMAGAQQAIAQgBASQAAAQgDAMQgEAKgFAIQgGAHgHAEIgLAJIgJAKQgEAFgBAJQAAAEgCACQgCADgDAAgAC1gpQgDgDAAgGIAAgzQAAgFADgEQAEgDAGAAIAGAAIAFgCIAEgEIAGgIIAAAAIAEgLIg/idIABACIgCgEIAAgDQAAgGADgCQAEgDAIAAIAvAAQAGAAAFADQAEACACAGIASA3IACAJIACAFIAVhFQACgGAEgDQAFgCAIAAIAtAAQAJAAADADQAEADAAAGIAAACIhCCqIAAAAIgBACIgIAVIAAgBIgEAMQgFALgJAKQgHAKgLAIQgJAHgNAEQgNAFgQAAQgGAAgFgDgAS2g0QgHABAAgIIAAhdIhKAAIAABdQAAAIgJgBIhDAAQgIAAAAgFIAAj3IADgFQABgCAEAAIBDAAIAGACQADACAAADIAABMIBKAAIAAhMQAAgDACgCQACgCADAAIBFAAIAFABQADABAAAEIAAD2QAAADgDACQgCACgCAAgAMng0QgIABAAgIIAAj1QAAgDACgCQACgCAEAAICzAAQACAAADACQACABAAAEIAAA5IgCAFQgCADgDAAIhnAAIAAAeIBPAAIAGABQAAABABAAQAAABAAAAQABABAAAAQAAABAAABIAAArIgCAFQgCACgEAAIhPAAIAAAcIBrAAQACAAADADQACACAAADIAAA4IAAAEIgCADQgDACgEAAgAKsg0QgGAAgEgCQgFgDgDgDIABABIg4hLIgEABIgDAAIAABFQAAAGgEADQgEADgIAAIgxAAQgRAAAAgMIAAhEIgDgBIgEgBIg4BLIAAgBQgCADgFADQgEACgGAAIhCAAQgNABAAgIIACgEIBfh4IgfgsIgMgMQgGgEgGgBQgGAAgEgDQgEgDgBgFIAAgtQABgGAEgDQADgDAHAAQAVAAAQAFQAQAGAMAKQANAJAKANIATAcIAGAPQAAAAAAABQABAAAAAAQABAAABAAQAAAAABAAIAAhKIABgFIAFgEIAFgCIAGgBIAxAAQAIAAAEADQAEAEAAAFIAABLIAJgOIABgDQAJgPAKgNQAKgNANgJQAMgKAQgGQAQgFAVAAQAHAAAEADQADADABAGIAAAtQgBAFgEADQgDADgIAAQgFABgGAEIgMAMIgaAlIgFAHIBgB4IABAEQgBADgDACQgDACgGAAgAhBg0QgIABAAgIIAAj1QAAgDACgCQABgCAFAAIByAAQAMAAALADQALAEAIAGQAJAHAIAIQAHAJAEAKQAGAKACAKQADALAAAKQAAARgFAPQgHAQgKAMQgKAMgPAIQgOAJgSgBIgrAAIAABMQAAAIgIgBgAAIjGIAWAAQAGAAAEgCIAGgFIAFgIIABgKIgBgJIgFgIIgGgGQgEgCgGAAIgWAAgAkSg0QgDAAgCgCQgCgCAAgDIAAj1QAAgHAHAAICnAAIADABIADACIABACIABADIAAA8QAAAEgCACQgDACgDAAIhaAAIAACwIgBADIgCACIgDACIgDAAgAoCg0QgJABABgIIAAj1QgBgDADgCQABgCAFAAICyAAQADAAACACQADABAAAEIAAA5IgDAFQgCADgDAAIhnAAIAAAeIBQAAIAGABQAAABAAAAQABABAAAAQAAABAAAAQABABAAABIAAArIgCAFQgDACgDAAIhQAAIAAAcIBrAAQADAAADADQACACAAADIAAA4IgBAEIgCADQgCACgEAAgAr8g0QgIABAAgIIAAj1QAAgDABgCQADgCAEAAIB0AAQAMAAALADQALAEAJAGQAIAHAHAIQAHAJAGAKQAEAKAEAKQACALAAAKQAAARgGAPQgFAQgLAMQgKAMgPAIQgPAJgSgBIgqAAIAABMQABAIgJgBgAqxjGIAXAAQAFAAAEgCIAHgFIADgIIABgKIgBgJIgDgIIgHgGQgEgCgFAAIgXAAgAvmg0QgIABAAgIIAAj1QAAgDACgCQACgCAEAAICzAAQADAAACACQADABAAAEIAAA5IgDAFQgCADgDAAIhnAAIAAAeIBPAAIAGABQAAABABAAQAAABAAAAQABABAAAAQAAABAAABIAAArIgCAFQgCACgEAAIhPAAIAAAcIBqAAQADAAADADQACACAAADIAAA4IgBAEIgBADQgCACgFAAgAxjg0QgQAAAAgMIAAiyIg8AAIAACyQAAAHgEACQgEADgIAAIg0AAQgHAAgEgDQgEgCAAgHIAAjrQAAgMAPAAIDEAAIAFABIAFACIAEAEIACAFIAADrQAAAMgQAAg");
	this.shape.setTransform(0,-6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.3,-37.3,256.7,62.7);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.w256h2561380453915MouseOptions256x256321();
	this.instance.parent = this;
	this.instance.setTransform(-14.4,-14.4,0.112,0.112);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.4,-14.4,28.8,28.8);


(lib.Символ33_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ah9BfQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBgBAAAAIAAgWIhjAAIAAAWIgBADQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgMAAIgDgBIgBgDIAAgkQAAgEAEAAIAHAAIAliAQAEgRASAAQASAAAEAQIAmCBIAGAAQAEAAAAAEIAAAkIgBADQgBAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAgAiMAzIgjh8QgBgEgDAAQgDAAgBAEIgiB8IBNAAgAK0BFQgMgBgCgCQgCgCAAgEIAAiVQAAgEAEAAIAMAAQAEAAAAAEIAABBIAYgBQBAAAgBAtIAAAEQABAuhAAAgAK4gHIAAA7IAYABQAYAAAKgHQAKgHAAgPIAAgEQAAgQgKgFQgKgHgYAAgAEpBFQgMgBgBgCQgDgCAAgEIAAiVQAAgEAFAAIALAAQAEAAABAEIAABBIAXgBQBAAAAAAtIAAAEQAAAuhAAAgAEugHIAAA7IAXABQAYAAAKgHQAKgHAAgPIAAgEQAAgQgKgFQgKgHgYAAgAlbA8QgMgKAAgVIAAhSQAAgWAMgJQAMgKAXAAIAlABIAHAAIABACIAAAMQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgrAAQgNAAgHAEQgGADgBAQIAAAeIBEAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABIABADIAAAIIgBADIgDABIhEAAIAAAjQABAOAFAEQAFAFAQAAIArAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAALIgBADQAAABgNAAIgfAAQgYAAgLgKgAneBFQgMgBgCgCQgCgCAAgEIAAiQIABgFQABgBAAAAQAAgBABAAQAAAAABAAQAAgBAAAAIAmgCQBBAAAAAqIAAAEQAAAMgHAJQgFAJgMAEQAMAEAGAKQAGAHABANIAAAEQAAAuhAAAgAnaA0IAYABQAYAAAKgHQAJgHABgPIAAgEQgBgaghAAIgiAAgAnahNIAAA3IAiAAQAgAAABgaIAAgEQAAgNgKgGQgKgGgZAAgAH1BFQgeAAAAgcIAAiBQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIADgCIALAAIADACIABADIAACBQAAAGACACQACACAGAAIAuAAIAAiLQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIAMAAIADACIABADIAACLIAtAAQAGAAACgCQACgCAAgGIAAiBQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAIALAAQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAABIABADIAACBQAAAcgeAAgAGlBFQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAiZQAAgEAEAAIAMAAQAEAAAAAEIAACZIgBADQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAgBAAgADpBFQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAAAAAgBIgCgDIAAiAIAAgBIgBABIggBBIgDADIgFABIgLAAQgDAAgCgBQgCgBgCgDIgYgwIgIgRIgBABIAACAIgBADIgDACIgLAAIgDgCQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIAAiWQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAABgBQAAAAABAAQAAAAABgBQAAAAABAAIAOAAQAFAAADAEIAkBMQAAAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQABAAAAAAQABgBAAAAQAAAAAAAAQABgBAAAAIAlhMQABgEAFAAIAPAAQAAAAABAAQAAABABAAQAAAAABAAQABABAAAAQABABAAAAQAAABAAAAQABABAAABQAAAAAAABIAACWQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAALBFIgDgBIgBgDIAAh/IAAgBIgBABIhCB/QgCAEgFAAIgNAAQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBQAAAAAAgBIAAiXQAAgEAEAAIAMAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABACIAAB/IABABIBDh/IACgEIAGgBIAMAAQABAAAAAAQABABAAAAQABAAAAAAQABABABAAQAAABAAAAQABABAAAAQAAAAAAABQABABAAAAIAACZQAAABgBAAQAAABAAAAQgBAAgBABQAAAAgBAAgAoWBFIgCgBIgDgIIgNgtIg5AAIgOAzIgCACIgCABIgNAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAgBIAqiNQAEgRARAAQASAAAFAQIAoCOIABABQAAAEgEAAgAosgBIgQg3IgEgSIgBgBIgBgBIgDgBIgCABIgBABIgUBKIAwAAgAqrBFQAAAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAhHIhMAAIAABHIgBADIgCACIgMAAIgDgCQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIAAiYQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAIADgCIAMAAIACACIABADIAAA/IBMAAIAAg/QAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIALAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAACYQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78.4,-9.5,156.8,19.2);


(lib.Символ72 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ73();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({x:7.5},0).wait(4).to({regX:0.1,scaleX:1.57,scaleY:1.57,x:18.8,y:0.5},0).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.5,-3.5,7,7);


(lib.Символ70 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ72();
	this.instance.parent = this;
	this.instance.setTransform(22.4,40.6);

	this.instance_1 = new lib.Символ72();
	this.instance_1.parent = this;
	this.instance_1.setTransform(22.4,13.7);

	this.instance_2 = new lib.Символ72();
	this.instance_2.parent = this;
	this.instance_2.setTransform(22.4,-13.5);

	this.instance_3 = new lib.Символ72();
	this.instance_3.parent = this;
	this.instance_3.setTransform(22.4,-40.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 1
	this.instance_4 = new lib.Символ71();
	this.instance_4.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.5,-54,101,108);


(lib.Символ69 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ70();
	this.instance.parent = this;
	this.instance.setTransform(-0.5,-46);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-41},14,cjs.Ease.get(1)).to({y:-46},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51,-100,101,108);


(lib.Символ67 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ66();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.535,0.535,0,0,0,0,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:9},14,cjs.Ease.get(1)).to({y:0},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-121.9,-48.6,243.8,86.1);


(lib.Символ63 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 64
	this.instance = new lib.Символ64();
	this.instance.parent = this;
	this.instance.setTransform(0,70.2);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3).to({_off:false},0).to({alpha:0.621},2).to({alpha:1},2).wait(1));

	// Символ 64
	this.instance_1 = new lib.Символ64();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,46.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).to({alpha:0.621},2).to({alpha:1},2).to({_off:true},1).wait(2));

	// Символ 64
	this.instance_2 = new lib.Символ64();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,22.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(2).to({_off:false},0).to({alpha:0.621},2).to({alpha:1},2).to({_off:true},1).wait(1));

	// Символ 64
	this.instance_3 = new lib.Символ64();
	this.instance_3.parent = this;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(2).to({_off:false},0).to({alpha:0.621},1).to({alpha:1},1).to({_off:true},1).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ61 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ60();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.7,-139.3,153.5,278.6);


(lib.Символ57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ63();
	this.instance.parent = this;
	this.instance.setTransform(-32.7,-112.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ56();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.1,-139.3,150.2,278.6);


(lib.Символ55 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ54();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.7,-139.3,153.5,278.6);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 48
	this.instance = new lib.Символ48();
	this.instance.parent = this;
	this.instance.setTransform(0,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.12,scaleY:1.12},0).wait(1));

	// Символ 47
	this.instance_1 = new lib.Символ47();
	this.instance_1.parent = this;

	this.instance_2 = new lib.Символ50();
	this.instance_2.parent = this;
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.8,-36,249.6,72);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ49();
	this.instance.parent = this;
	this.instance.setTransform(-1.3,0);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-140.9,-40.2,279.2,80.5);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ31();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.196,0.196);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(100).to({_off:false},0).wait(100));

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhZC/QAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIAAgDIAAgiIhxAAIAAAjQAAABAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIgFAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAgqQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBABAAIAIAAIAKgQQAEgJADgMQAEgMACgOQACgPAAgSIAAgiQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAAAIBMAAIACABIABACIAACCIANAAIACABIABACIAAAqIgBADIgCABgAioAuQAAASgDAOQgBAPgDALIgIAUIgJASIBTAAIAAh6Ig7AAgANFCbIgDgDIgCgDIgBgDIABgDIACgDIADgCIADAAIAEAAIADACIABADIABADIgBADIgBADIgDADIgEAAgAgICYQgJgDgIgEQgJgFgGgHQgHgHgFgHQgFgJgCgJQgDgJAAgLQAAgKADgKQACgJAFgIQAFgIAHgHQAGgGAJgGQAIgFAJgCQAIgDAKAAQAKAAAKADQAJACAIAFQAIAGAHAGQAHAHAEAIQAFAIADAJQADAKAAAKQAAALgDAJQgDAJgFAJQgEAHgHAHQgHAHgIAFQgIAEgJADQgKADgKAAQgKAAgIgDgAgFAVQgIACgHAEIgMAKIgKAMQgEAIgCAIQgDAHAAAJQAAANAFALQAFAMAJAIQAIAJALAFQAMAEALAAQAJAAAIgCQAIgCAGgEQAIgDAFgHQAGgFAEgIQAEgGACgIQACgIAAgJQAAgNgFgLQgFgMgIgIQgJgJgLgFQgLgEgNAAQgJAAgGACgAoeCYQgKgDgIgEQgIgFgHgHQgGgHgFgHQgFgJgDgJQgDgJAAgLQAAgKADgKQADgJAFgIQAFgIAGgHQAHgGAIgGQAIgFAKgCQAJgDAKAAQALAAAJADQAJACAJAFQAIAGAGAGQAHAHAFAIQAFAIADAJQACAKAAAKQAAALgCAJQgDAJgFAJQgFAHgHAHQgGAHgIAFQgJAEgJADQgJADgLAAQgKAAgJgDgAobAVQgIACgHAEIgNAKIgKAMQgEAIgCAIQgCAHAAAJQAAANAFALQAFAMAIAIQAJAJALAFQAMAEAMAAQAJAAAIgCQAIgCAHgEQAHgDAGgHQAGgFADgIQAEgGADgIQACgIAAgJQAAgNgFgLQgFgMgIgIQgJgJgLgFQgLgEgOAAQgIAAgIACgAtCCYQgJgDgIgEQgJgFgGgHQgHgHgFgHQgFgJgCgJQgDgJAAgLQAAgKADgKQACgJAFgIQAFgIAHgHQAGgGAJgGQAIgFAJgCQAKgDAKAAQAKAAAKADQAJACAIAFQAIAGAHAGQAHAHAEAIQAFAIADAJQADAKAAAKQAAALgDAJQgDAJgFAJQgEAHgHAHQgHAHgIAFQgIAEgJADQgKADgKAAQgKAAgKgDgAs/AVQgHACgIAEIgMAKIgKAMQgEAIgCAIQgDAHAAAJQAAANAFALQAFAMAJAIQAIAJAMAFQALAEANAAQAJAAAIgCQAIgCAGgEQAIgDAFgHQAGgFAEgIQAEgGACgIQACgIAAgJQAAgNgFgLQgEgMgJgIQgIgJgMgFQgLgEgNAAQgJAAgIACgAKqCZQgEAAAAgEIAAiIIABgDQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAIBeAAIADABIABADIAAACIgBAEQAAAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIhXAAIAAA3IBHAAIADABIABACIAAADQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIhHAAIAAA4IBaAAIADABQAAABAAAAQAAAAAAAAQABABAAAAQAAABAAABIAAACIgBADIgDABgAKCCZQgEAAAAgEIAAh5IhiB8IgDABIgEAAIgDgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAiIIACgDIADgBIADAAIADABIABADIAAB6IBih9QAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAEAAIADABIABADIAACIQAAAEgEAAgAHqCZQgEAAAAgEIAAhAIhfAAIAABAQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgDAAQgEAAAAgEIAAiIIABgDIADgBIADAAIADABIABADIAAA9IBfAAIAAg9IABgDIADgBIADAAIADABIABADIAACIQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAgAFhCZIgEgBIgCgDIgNgfIhOAAIgMAfQgCAEgEAAIgDAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIAAgCIA4iIIACgDIADgBIAEAAIACABIABABIABACIABABIA4CHIAAABIgBACIgCABgAEFBqIBEAAIgihSgABxCZIgDgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAiIIACgDIADgBIA5AAQAHAAAHADQAHADAFAFQAFAFADAHQADAGAAAJQAAAJgFAIQgEAJgHAFQAFACAFAEQAEADADAFQAEAEABAGQACAFAAAGQAAAIgCAIQgDAGgGAGQgFAFgHAEQgHADgJAAgAB3COIA5AAQAGAAAFgCQAFgCAEgEQADgEADgGQACgFAAgGQAAgFgCgFQgCgFgEgEQgDgEgGgCQgFgCgGAAIg5AAgAB3BMIAzAAQAFgBAFgCQAFgCADgEQAEgEACgFQACgGAAgFQAAgHgCgFQgCgEgEgEIgIgFQgFgCgFAAIgzAAgAkxCYIAAgBIAAgHIAAgDIADAAQAHABAEgEQAFgEAEgJIAIgVIgmhbIAAAAIAAgBIAAgBIAAgCIACgBIAIAAIACACIAgBSIAhhRIABgDIAJABQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAABIg0B9IgHAJQgDADgFACQgFACgHAAgAmkCZQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiIQAAgBAAgBQABAAAAgBQAAAAABgBQABAAAAAAIAvAAQAKAAAIAEQAIAEAGAFQAHAGADAJQADAHAAAKQAAAJgDAIQgDAJgHAFQgGAGgIAEQgIADgKAAIgmAAIAAAzQAAAEgEAAgAmcBYIAmAAQAIAAAGgDQAGgDAEgFQAFgEACgGQADgGAAgHQAAgHgDgGQgCgGgFgFQgEgEgGgDQgGgDgIAAIgmAAgArHCZIgDgBIgBgDIAAiIQAAgEAEAAIBSAAIADABIACADIAAACQAAABAAABQAAAAgBABQAAAAAAABQAAAAgBABIgDAAIhLAAIAAAsIAuAAQAJAAAIADQAJAEAGAGQAGAGADAIQADAJAAAJQAAAIgDAJQgDAIgGAGQgGAGgJADQgIAEgJAAgArACOIAuAAQAHAAAGgCQAGgDAFgFQAFgEACgGQADgGAAgHQAAgIgDgGQgCgGgFgFQgFgEgGgDQgGgDgHABIguAAgANHB8IgDgBIgCgDIAAgRQAAgFACgFIAFgIIAHgHIAQgLIAHgHQADgDACgFQACgEAAgGQAAgHgDgGQgCgGgFgDQgFgFgHgCQgGgCgIAAQgHAAgHACQgGADgFAEQgEAEgDAGQgDAGAAAIQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgDACIgDAAIgDgBIgBgCIAAgCQAAgKAEgIQADgIAHgGQAGgFAJgEQAIgDAJAAQAKAAAIADQAJADAHAFQAGAGADAHQAEAIAAAJQAAAKgDAHQgDAGgFAFQgFAFgFAEIgLAIIgHAHQgDAFAAAFIAAARQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAIgDABgAsOhHIgBgDIAAgBIABgDIADgCQADAAACgBIAFgDIADgGIABgFIAAhbIABgDIACgBIBNAAIADABQAAABAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABwQAAADgEAAIgCAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAhqIhCAAIAABVQAAAFgCAEIgFAIQgDADgEACQgEADgFAAIgDgBgAMthHQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhwQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBABAAIADAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAABIAAApIAgAAQAIAAAHAEQAGADAFAEQAFAFADAIQADAGAAAHQAAAIgDAHQgDAHgFAEQgFAGgGACQgHADgIAAgAM0hQIAgAAQAGAAAFgCQAFgCAEgEQADgDADgFQACgGAAgGQAAgFgCgFQgDgGgDgDQgEgEgFgCQgFgCgGAAIggAAgALrhHQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhrIglAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgCQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAIBTAAIADABIABADIAAACIgBACIgDABIglAAIAABrQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAgAKmhHQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAgpIgqAAIgEgBIgTAsQAAAAgBABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgGAAIgBAAIgBgCIAAgBIAVgsQgFgCgEgDIgHgIQgDgFgCgFQgBgGAAgFQAAgIACgGQADgIAFgFQAFgEAHgDQAHgEAIAAIAuAAIACABIABACIAABxQAAABAAABQgBAAAAABQAAAAgBAAQgBAAAAAAgAJxiyQgFACgEAEIgGAJQgCAFAAAGQAAAFABAEIAEAHIAGAHIAIADIAAABIAHABIApAAIAAg5IgnAAQgGABgFACgAI9hHQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAg1IhOAAIAAA1QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgDAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAhwIAAgDIADgBIADAAIACABIABADIAAAyIBOAAIAAgyIABgDIACgBIADAAIADABIAAADIAABwQAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAgAF/hHQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAhwIABgDIACgBIBOAAIACABIABADIAAACIgBACIgCABIhIAAIAAAtIA6AAIADABIABADIAAACIgBACQgBABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIg6AAIAAAuIBKAAIACACIABACIAAACIgBACIgCABgAFghHQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIgIhgIgpBcQAAAAgBABQAAAAgBABQAAAAgBAAQAAABgBAAIgCAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAIgqhcIgHBgQAAADgEAAIgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAJhwIABgDIACgBIAEAAIACABIABADIAsBfIAthiIACgBIADAAIADABIABADIAJBwQAAABAAABQgBAAAAABQgBAAAAAAQgBAAgBAAgABZhHQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAhwIABgDIACgBIBOAAIACABIABADIAAACIgBACIgCABIhIAAIAAAtIA6AAIADABIABADIAAACIgBACQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIg6AAIAAAuIBKAAIACACIABACIAAACIgBACIgCABgAAWhHQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhrIgjAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgCQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAIBRAAIADABIABADIAAACIgBACIgDABIglAAIAABrQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAgAhvhHQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhwIABgDIADgBIBNAAIADABIABADIAAACIgBACIgDABIhIAAIAAAtIA7AAIACABIABADIAAACIgBACQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIg7AAIAAAuIBKAAIADACIABACIAAACIgBACIgDABgAjGhHIAAgCIAAgFIAAgCIACAAQAGAAAEgDQAEgEADgGIAHgSIgghLIAAAAIAAgBIAAgBIAAgCIACAAIAGAAIACABIAbBEIAahDIACgCIADAAIAEAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIgBAEIgqBkIgFAHIgHAFQgEABgGAAgAklhHQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAhwQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAgBIAnAAQAIAAAHAEQAHADAFAEQAFAGACAGQADAHAAAHQAAAIgDAHQgCAHgFAEQgFAGgHACQgHADgIAAIggAAIAAAqQAAABAAABQAAAAAAABQgBAAAAAAQgBAAgBAAgAkfh9IAgAAQAGAAAFgCQAFgCAEgEQAEgDACgFQACgGAAgGQAAgFgCgFQgCgGgEgDQgEgEgFgCQgFgCgGgBIggAAgAlFhHQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhkIhRBmIgCABIgDAAIgDgBIgBgCIAAhwIABgDIADgBIACAAIACABIABADIAABlIBRhoIADgBIADAAIACABIABADIAABwQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAgAnDhHQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAg1IhPAAIAAA1QAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAIgDAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhwIABgDIACgBIADAAIADABIAAADIAAAyIBPAAIAAgyIAAgDIADgBIADAAIACABIABADIAABwQAAABAAABQgBAAAAABQAAAAgBAAQgBAAAAAAgAo1hHIgDgBIgCgCIgKgaIhAAAIgLAZQgBAEgEAAIgCAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgBIAuhwIACgDIACgBIADAAIACABIABABIABACIAAABIAvBvIAAABIgBACIgCAAgAqBhtIA5AAIgchDgAsmhHQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAhqIhCAAIAABqQAAABAAABQgBAAAAABQgBAAAAAAQgBAAgBAAIgCAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAhwIABgDIACgBIBNAAIADABIABADIAABwQAAABAAABQgBAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape.setTransform(-0.2,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},100).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-89.1,-18.3,178,38.3);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.parent = this;
	this.instance.setTransform(-1,-27.3,1.163,1.163);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ28();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-2,-44.2,0.893,0.893,0,0,0,-0.1,-0.1);
	this.instance_1.alpha = 0.41;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-121.8,-66.4,239.8,87);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ21();
	this.instance.parent = this;
	this.instance.setTransform(-17.2,2.8,1,1,0,0,0,-17.2,2.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:15},29,cjs.Ease.get(1)).to({rotation:0},30,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22,-12,44,24);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ19();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:2.2,y:1.4},34,cjs.Ease.get(1)).to({rotation:0,y:0},35,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.5,-45,69,90);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ25();
	this.instance.parent = this;
	this.instance.setTransform(462.6,-37.2,0.731,0.731);

	this.instance_1 = new lib.logo1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-431,-130);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 2
	this.instance_2 = new lib.Символ24();
	this.instance_2.parent = this;
	this.instance_2.setTransform(7.9,-101.2,1,1.116);
	this.instance_2.alpha = 0.57;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-556.9,-276.8,1129.7,352.9);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A6AZKMAAAgyTMA0BAAAMAAAAyTg");

	// Слой 2
	this.instance = new lib.Символ9();
	this.instance.parent = this;
	this.instance.setTransform(19.5,88.4);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-804.8},39).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-146.5,-161,313.1,322.1);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ4();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},4).to({alpha:1},4).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ10();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.3,-37.3,256.7,62.7);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 64
	this.instance = new lib.Символ64();
	this.instance.parent = this;
	this.instance.setTransform(0,35);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).to({alpha:0.73},1).to({alpha:1},2).wait(1));

	// Символ 64 - копия: 2 - копия
	this.instance_1 = new lib.Символ64();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,151.4);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(3).to({_off:false},0).to({y:150.7,alpha:0.73},2).to({y:151.4,alpha:1},1).to({_off:true},1).wait(1));

	// Символ 64 - копия: 2
	this.instance_2 = new lib.Символ64();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,127.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(3).to({_off:false},0).to({y:127.8,alpha:0.73},2).to({y:127.2,alpha:1},1).to({_off:true},1).wait(1));

	// Символ 64
	this.instance_3 = new lib.Символ64();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,103.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1).to({_off:false},0).to({y:104,alpha:0.73},2).to({y:103.4,alpha:1},2).to({_off:true},1).wait(2));

	// Символ 64
	this.instance_4 = new lib.Символ64();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,-11.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(2).to({_off:false},0).to({alpha:0.73},2).to({alpha:1},2).to({_off:true},1).wait(1));

	// Символ 64 - копия
	this.instance_5 = new lib.Символ64();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,-34.9);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({_off:false},0).to({alpha:0.73},2).to({alpha:1},2).to({_off:true},1).wait(2));

	// Символ 64
	this.instance_6 = new lib.Символ64();
	this.instance_6.parent = this;
	this.instance_6.setTransform(0,-34.9);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(2).to({_off:false},0).to({alpha:0.73},1).to({alpha:1},2).to({_off:true},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ34();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-6.8},14,cjs.Ease.get(0.98)).to({y:0},7,cjs.Ease.get(0.98)).wait(1).to({y:-6.8},14,cjs.Ease.get(0.98)).to({y:0},7,cjs.Ease.get(0.98)).wait(32));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.4,-14.4,28.8,28.8);


(lib.Символ27_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance_2 = new lib.Символ35();
	this.instance_2.parent = this;
	this.instance_2.setTransform(257.6,268.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 1
	this.instance_3 = new lib.Символ33_1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(161.2,268.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(82.8,253.8,189.2,28.8);


(lib.Символ68 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ67();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-121.9,-48.6,243.8,86.1);


(lib.Символ59 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ2();
	this.instance.parent = this;
	this.instance.setTransform(-32.8,-78.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ58();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74,-139.3,148,278.6);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Растровое изображение 14
	this.instance = new lib.Символ55();
	this.instance.parent = this;
	this.instance.setTransform(-224.2,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({skewX:-0.1,x:-221.9},2).to({skewX:0,x:-224.2},2).wait(1));

	// Растровое изображение 13
	this.instance_1 = new lib.Символ57();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-73.9,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleY:0.98,skewX:0.1,x:-73.6,y:3},2).to({scaleY:1,skewX:0,x:-73.9,y:0.3},2).wait(1));

	// Растровое изображение 12
	this.instance_2 = new lib.Символ59();
	this.instance_2.parent = this;
	this.instance_2.setTransform(75.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regY:-0.1,scaleY:1.01,skewX:-0.7,x:73.6,y:-1.5},2).to({regY:0,scaleY:1,skewX:0,x:75.3,y:0},2).wait(1));

	// Растровое изображение 11
	this.instance_3 = new lib.Символ61();
	this.instance_3.parent = this;
	this.instance_3.setTransform(224.7,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({scaleY:0.99,skewX:0.6,x:220.5,y:1.8},2).to({scaleY:1,skewX:0,x:224.7,y:0.3},2).wait(1));

	// Слой 6
	this.instance_4 = new lib.Символ62();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-9.8,1.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-320.5,-139.3,622,278.9);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_31 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(31).call(this.frame_31).wait(5));

	// Символ 65
	this.instance = new lib.Символ65();
	this.instance.parent = this;
	this.instance.setTransform(14.6,-17.8,1.174,1.174);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(23).to({_off:false},0).to({y:22,alpha:1},4,cjs.Ease.get(1)).wait(9));

	// Символ 51
	this.instance_1 = new lib.Символ51();
	this.instance_1.parent = this;
	this.instance_1.setTransform(14.4,32,1.174,1.174);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(21).to({_off:false},0).to({y:71.8,alpha:1},4,cjs.Ease.get(1)).wait(11));

	// Слой 5
	this.instance_2 = new lib.Символ46();
	this.instance_2.parent = this;
	this.instance_2.setTransform(15.3,307.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(18).to({_off:false},0).to({y:168.7,alpha:1},7,cjs.Ease.get(1)).wait(7).to({y:307.1,alpha:0},3).wait(1));

	// Слой 2
	this.instance_3 = new lib.Символ68();
	this.instance_3.parent = this;
	this.instance_3.setTransform(15,-13.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(10).to({_off:false},0).to({y:-51.5,alpha:1},4,cjs.Ease.get(1)).wait(22));

	// Слой 3
	this.instance_4 = new lib.Символ69();
	this.instance_4.parent = this;
	this.instance_4.setTransform(14.5,-20.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(12).to({_off:false},0).to({y:-45.4,alpha:0.641},2,cjs.Ease.get(1)).to({y:-59.5,alpha:1},3).wait(19));

	// Символ 42
	this.instance_5 = new lib.Символ42();
	this.instance_5.parent = this;
	this.instance_5.setTransform(16.4,-212.9,1.39,1.39);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(4).to({_off:false},0).to({y:-179.3,alpha:1},4,cjs.Ease.get(1)).wait(28));

	// Символ 41
	this.instance_6 = new lib.Символ41();
	this.instance_6.parent = this;
	this.instance_6.setTransform(13.9,-182.1,1.39,1.39);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(6).to({_off:false},0).to({y:-164.5,alpha:1},4,cjs.Ease.get(1)).wait(26));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ3();
	this.instance.parent = this;
	this.instance.setTransform(-10.2,-33.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ33();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,-14.4,1,1.255);
	this.instance_1.alpha = 0.66;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-214.8,-85.2,429.6,141.6);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ27();
	this.instance.parent = this;
	this.instance.setTransform(-94.1,46.9,0.28,0.28,0,0,0,-96.1,23.9);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:-96,regY:24,scaleX:1.12,scaleY:1.12,alpha:1},9).to({scaleX:1,scaleY:1},5).wait(45).to({scaleX:1.12,scaleY:1.12},5).to({regX:-96.1,regY:23.9,scaleX:0.28,scaleY:0.28,alpha:0},9).wait(27));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-101.3,21.6,67.1,24.3);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.text1 = new lib.Символ40();
	this.text1.parent = this;
	this.text1.setTransform(-15.4,73.1);

	this.timeline.addTween(cjs.Tween.get(this.text1).wait(1));

	// Слой 1
	this.instance = new lib.Символ52();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-158.5,-315,317.1,630.2);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 16
	this.instance = new lib.Символ16();
	this.instance.parent = this;
	this.instance.setTransform(-18.9,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Символ 17
	this.instance_1 = new lib.Символ17();
	this.instance_1.parent = this;
	this.instance_1.setTransform(6.9,4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.9,-16,57.9,32);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ53();
	this.instance.parent = this;
	this.instance.setTransform(-1.6,0,1.018,1.018);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-327.8,-141.8,633,283.9);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ11();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.667,0.667);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-218.5,-94.5,422,189.2);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ20();
	this.instance.parent = this;
	this.instance.setTransform(-26.6,2.5,1,1,0,0,0,-26.6,2.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-15,y:2.6},29,cjs.Ease.get(1)).to({rotation:0,y:2.5},30,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.9,-16,57.9,32);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 15
	this.instance = new lib.Символ15();
	this.instance.parent = this;
	this.instance.setTransform(-68.8,-85);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Символ 14
	this.instance_1 = new lib.Символ14();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-66.2,37.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Символ 16
	this.instance_2 = new lib.Символ22();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-28.5,-18.3,1,1,0,0,0,-3.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-103.3,-130,106.9,250.3);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 17
	this.instance = new lib.Символ18();
	this.instance.parent = this;
	this.instance.setTransform(51.8,-178.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 6
	this.instance_1 = new lib.Символ23();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-16.4,-65.2,1.884,0.3,-2.3,0,0,0,-0.1);
	this.instance_1.alpha = 0.289;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-106.4,-308.3,180,260.9);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ39();
	this.instance.parent = this;
	this.instance.setTransform(0,-40);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 3
	this.instance_1 = new lib.Символ38();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-1,59);
	this.instance_1.alpha = 0.441;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-218.5,-134.5,422,200.7);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_10 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(10));

	// Слой 4
	this.instance = new lib.Символ12();
	this.instance.parent = this;
	this.instance.setTransform(0,-210.1,0.33,0.33,0,0,0,0,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(20));

	// Слой 8
	this.instance_1 = new lib.Символ27_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-174.3,48.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:55,alpha:0},9,cjs.Ease.get(1)).wait(1).to({y:48.8,alpha:1},9,cjs.Ease.get(1)).wait(1));

	// Слой 6
	this.text11 = new lib.Символ26();
	this.text11.parent = this;
	this.text11.setTransform(-0.4,30.5);
	this.text11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.text11).to({alpha:1},9).wait(1).to({alpha:0},9).wait(1));

	// Слой 8
	this.instance_2 = new lib.Символ32();
	this.instance_2.parent = this;
	this.instance_2.setTransform(7.8,299.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:415.9,alpha:0},9,cjs.Ease.get(1)).wait(1).to({y:299.1,alpha:1},9).wait(1));

	// Слой 7
	this.instance_3 = new lib.Символ30();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-0.7,-102.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({alpha:0},9).wait(1).to({alpha:1},9).wait(1));

	// Слой 5
	this.instance_4 = new lib.Символ13();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-90.5,269.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:-71.5},3,cjs.Ease.get(1)).to({x:-243.5,alpha:0},6,cjs.Ease.get(1)).wait(1).to({x:-71.5,alpha:1},6).to({x:-90.5},3).wait(1));

	// Символ 5
	this.instance_5 = new lib.Символ5();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,132.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({regY:0.1,scaleX:1.18,scaleY:1.18,y:112.8},3,cjs.Ease.get(1)).to({scaleX:0.59,scaleY:0.59,y:-54.3,alpha:0},6,cjs.Ease.get(1)).wait(1).to({scaleX:1.18,scaleY:1.18,y:112.8,alpha:1},6,cjs.Ease.get(1)).to({regY:0,scaleX:1,scaleY:1,y:132.5},3,cjs.Ease.get(1)).wait(1));

	// Символ 7
	this.instance_6 = new lib.Символ7();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-1.4,-112.4);
	this.instance_6.alpha = 0.75;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({regX:-0.1,regY:-0.1,scaleX:1.18,scaleY:1.18,x:-1.7,y:-175.3},3,cjs.Ease.get(1)).to({scaleX:0.59,scaleY:0.59,x:-0.8,y:-199.9,alpha:0},6,cjs.Ease.get(1)).wait(1).to({scaleX:1.18,scaleY:1.18,x:-1.7,y:-175.3,alpha:0.75},6,cjs.Ease.get(1)).to({regX:0,regY:0,scaleX:1,scaleY:1,x:-1.4,y:-112.4},3,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-218.5,-979.1,441.1,1909);


// stage content:



(lib.server300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		stage.scaleX = stage.scaleY = 2;
		stage.canvas.width = 300 * 2;
		stage.canvas.height = 600 * 2;
		stage.canvas.style.width = "300px";
		stage.canvas.style.height = "600px";
		
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		var _this = this;
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		  function fl_MouseOverHandler_5()
		{
		    _this.main.gotoAndPlay(1);
			_this.main.text11.text1.gotoAndPlay(1);
		}
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		  function fl_MouseOutHandler_2()
		{
		    _this.main.gotoAndPlay(11);
			_this.main.text11.text1.gotoAndPlay(32);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 1
	this.main = new lib.Символ1();
	this.main.parent = this;
	this.main.setTransform(151,235.9,1,1,0,0,0,0,-24.6);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

	// Слой 2
	this.instance = new lib.Символ6();
	this.instance.parent = this;
	this.instance.setTransform(149.6,256.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(82.4,-418.6,441.2,1909);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;