(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 305,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/cannon.png", id:"cannon"},
		{src:"images/fon.jpg", id:"fon"},
		{src:"images/Pirate_Ship_SU.png", id:"Pirate_Ship_SU"}
	]
};



// symbols:



(lib.cannon = function() {
	this.initialize(img.cannon);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,185,122);


(lib.fon = function() {
	this.initialize(img.fon);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.Pirate_Ship_SU = function() {
	this.initialize(img.Pirate_Ship_SU);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,99,100);


(lib.Символ37 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0D4375","#000F1C"],[0,1],-175,-3881.2,175,-3881.2).s().p("A7UEiIAgpEMA2JAAAIAAJEg");
	this.shape.setTransform(0,240.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#0D4375","#000F1C"],[0,1],-175,4530.8,175,4530.8).s().p("A6aJbIg6y1MA2pAAAIAAS1g");
	this.shape_1.setTransform(0,-269.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#0D4375","#000F1C"],[0,1],-176.6,-1.2,173.4,-1.2).s().p("EgbEAg5IAAAAUAhfghbghFggWIAAAAMA1vAAAMAAABBxg");
	this.shape_2.setTransform(1.6,1.2);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-175,-330,350,600);


(lib.Символ35 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(20,20,20,0.498)").s().p("Eg5BAD6IAAnzMByDAAAIAAHzg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-365,-25,730,50);


(lib.Символ34 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#141414").s().p("AltBbQgHgCgFgEQgFgDgEgFQgDgFgDgHIgDgPQgCgMADgeQACgOAHgYQADgIAEgHQAEgGAFgFIAFgGIgEAHQgEAHgDAIQgHAYgCAQQgDAcABAMIAEAPQADAHADAFQAEAFAFADQAFAEAHACQAJADAXABQANAAATgEQAHgCAGgDIAFgDIgFAFQgEAFgGADQgGADgHACQgUAEgMAAQgXgBgJgDgAA+BcIADgUIgLAAIgYiPQAAgEgDgDQgEgDgFAAIggAAIgEAAIABgBQACgFADgCQAEgCAEAAIAgAAQAFAAADADQAEADABAEIAYCXIAViNIAJAAIgXCZQAmACAgAAQAPAAAKgCQAJgCAGgEIgIAIQgHAGgLACQgJACgPAAQggAAgmgCgADGBdIgBgdIAKgDIABAWQAKABAIgBQAIgCAIgEIAGgDIgDACQgGAHgHAEQgIAEgIACIgIABIgKgBgAHaBcIANhdIACgIIg6BRIgDAAIA+hXIAMgWIABAAQgEANgCANIgNBdIAbAAIgCAKgAF0BcIAYijIAJAAIgWCZIAiAAIgGAKgAEuBcIAUiJIgTAAIgMAuQgIAbgFAKQgGALgGAHIgIAIIAKgQQAFgKAIgbIANgzQACgIAEgEQAEgDAJAAIATAAIgUCJIAcAAIgBAKgAAJBcIgFgrIgrAAIgKAXIgFAAIANghIA3AAIAFArIAaAAIABAKgAhrBcIBGiaQACgFADgCIAEgCIhFCZIAhAAIgFAKgAjtBcIAXijIAJgBIgWCaIAcAAIgBAKgAnKBcIgGgjQgCgPgDgHQgEgJgFgDQgEgDgFAAIgIA0IgIAAIAGguQABgJAAgIIAMAAQAKAAAGAEQAFADAEAJQADAHACAPIAGAjIAaAAIABAKgAonBcIAXijIAIAAIgVCZIAcAAIgCAKgAIJBIIAViZIgiAAIAHgKIAlAAIgXCjgAFeBIIAWiZIhGAAQgKAAgGACIgJAEQACgFAFgDQAEgEAIgCQAGgCAKAAIBGAAIgXCjgAi9BIIAIgzQANACARAAQAQAAAKgCQAJgCAHgEIgHAIQgIAFgLADQgKACgQAAIgOAAIgFAngAmdBIIgFgdQgDgQgEgJQgFgKgHgEQgGgEgMgBIAAgBQAMgCAJgFIACgBIgBACIAGAEQAHAEAFAIQAEAJADAQIAHAngADEA7QADgJACgPQADgOgDgKQgCgKgGgEQgGgGgMgCQgLgDgRAAIgYAAIAFgnIBCAAIgDAKIg3AAIgDATIAYAAQARAAALADQAMACAGAGQAGAGADAIQACAKgCAOQgDAPgDAJQgFAKgHAFIgDACIAFgHgAkDA4IAHgOQAEgLAFgeIACgVIgBgTQgBgIgCgHIgGgMQgEgFgFgDQgFgEgHgCIgPgDIgRgBQgXABgKADQgGACgGADIgEADIADgEQAFgFAGgEQAFgDAIgCQAIgDAYgBIARABIAPADQAHACAEAEQAFADAEAFIAHAMQACAHABAIIABATIgCAXQgGAcgDALIgHAOIgJAMIgFAFIAEgHgAB3AJIAmABQAEABACACQADADAAAEIgBALQgBAIgCAFQgBAFgDADQgDACgGABIgkABgAB7AuIAggBIAAgEIABgLQAAgEgDgDQgCgCgEgBIgVgBgAlRA1QgGgCgDgGQgCgHAAgKQAAgKACgRQADgQADgLQADgLAFgGQAEgHAHgCQAGgDAKAAQAKAAAFACQAGADADAGQACAGAAALQAAAKgCARQgDAQgDAKQgDAMgFAGQgFAGgGADQgHADgJAAQgKAAgFgDgAlIgrIgCAHQgDALgCASQgDAPAAAKQAAAKADAHQACAGAGACQAFADAKAAIANgBIACgJQADgKACgSQADgPAAgKQAAgLgDgGQgDgGgFgDQgFgCgKAAQgHAAgGACgADZAsIAJgCIALgcQAFgOAIgnQABgIAEgGQADgGAFgEIAEgCIgCACQgDAGgCAIQgJAngEAOQgIAXgFAJQgFAJgIAFIgEABgAGmAmQAEgQACgLIANhcIgaAAIABgKIAjAAIgNBcIgBAKIA6hSIADAAIg+BWQgIALgFAMgAgdAKIAbhAIAEAAIAIBAgAgTAAIATAAIgEgigAhfgCQAEgKACgQQACgQgCgKQgCgLgGgGQgHgHgLgDQgLgDgRAAQggABgUABIABgJQAUgCApgBQARAAALADQAMADAGAHQAGAGACALQACAKgCAQQgCAQgEAKQgEALgIAEIgCACIAEgHgAiygDIAHg0IAbAAIAKABQAFABACADQACACABAFQABAFgCAHQgBAJgCAFQgBAGgEACQgDADgFACIgMABgAiogNIAZAAIAHAAIABgIQABgHAAgFQgBgFgCgCQgCgDgEgBIgLgBIgJAAgAntgPQADgHACgMIAGgvIgbAAIABgKIAkAAIgGAvQgCAMgDAHIALAAQAHAAAGgCQAGgNANgfIAHAAQgOAfgHAJQgGAIgGAEQgHAEgJAAgAmkgXQAJgNATgtIgfAAIADgKIAmAAQgTAtgJANQgGAIgGAFIACgDgADMg/IAEgSIg3gCIgwABIABgJQAagCAfAAIA3ACIgGAcg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AljBRQgHgCgFgEQgFgDgEgFQgDgFgDgHIgEgPQgBgMADgcQACgQAHgYQADgIAEgHIAEgHIAFgEIAGgGIAEgDQAGgDAGgCQAKgDAXgBIARABIAPADQAHACAFAEQAFADAEAFIAGAMQACAHABAIIABATIgCAVQgFAegEALIgHAOIgEAHIgFAFIgFAFIgFADQgGADgHACQgTAEgNAAQgXgBgJgDgAlBg0QgHACgEAHQgFAGgDALQgDALgDAQQgCARAAAKQAAAKACAHQADAGAGACQAFADAKAAQAJAAAHgDQAGgDAFgGQAFgGADgMQADgKADgQQACgRAAgKQAAgLgCgGQgDgGgGgDQgFgCgKAAQgKAAgGADgABIBSIAXiZIABgKIAJgBIAwgBIA3ACIgEASIgDAKIgHAAIhCAAIgFAnIAYAAQARAAALADQAMACAGAGQAGAEACAKQADAKgDAOQgCAPgDAJIgFAHIgHAIIgCACQgGAEgJACQgKACgPAAQggAAgmgCgABxA4IAkgBQAGgBADgCQADgDABgFQACgFABgIIABgLQAAgEgDgDQgCgCgEgBIgmgBgADQBTIgBgWIAAgHIAKgDIAEgBQAIgFAFgJQAFgJAIgXQAEgOAJgnQACgIADgGIACgCQACgFAEgDIAEgCIAJgEQAGgCAKAAIBGAAIgWCZIgBAKIgJAAIgcAAIAUiJIgTAAQgJAAgEADQgEAEgCAIIgNAzQgIAbgFAKIgKAQIgDACIgHAIIgGADQgIAEgIACIgIABIgKgBgAH/BSIgbAAIANhdQACgNAEgNIgBAAIgMAWIg+BXIgHAKIgEAAIgiAAIAWiZIABgKIAJAAIAaAAIgNBcQgCALgEAQIABAAQAFgMAIgLIA+hWIAHgKIADAAIAiAAIgVCZIgCAKgAAtBSIgaAAIgFgrIg3AAIgNAhIgFAKIgFAAIghAAIBFiZIABgBQACgFADgCIAEgCIAEAAIAgAAQAFAAAEADQADADAAAEIAYCPIACAKgAgdAKIAnAAIgIhAIgEAAgAjHBSIgcAAIAWiaIABgJIAJgBQAUgBAggBQARAAALADQALADAHAHQAGAGACALQACAKgCAQQgCAQgEAKIgEAHIgIAIIgCACQgHAEgJACQgKACgQAAQgRAAgNgCIgIAzIgBAKgAiygDIAZAAIAMgBQAFgCADgDQAEgCABgGQACgFABgJQACgHgBgFQgBgFgCgCQgCgDgFgBIgKgBIgbAAgAmmBSIgaAAIgGgjQgCgPgDgHQgEgJgFgDQgGgEgKAAIgMAAQAAAIgBAJIgGAuIgCAKIgIAAIgcAAIAViZIACgKIAJAAIAbAAIgGAvQgCAMgDAHIALAAQAJAAAHgEQAGgEAGgIQAHgJAOgfIADgKIAHAAIAfAAQgTAtgJANIgCADQgEAGgGAEIgCABQgJAFgMACIAAABQAMABAGAEQAHAEAFAKQAEAJADAQIAFAdIACAKg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-55.3,-9.5,110.6,19.2);


(lib.Символ33 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#141414").s().p("ADiBbQgGgCgFgEQgFgDgEgFQgEgFgDgHIgDgPQgBgMACgeQACgOAHgYQADgIAFgHQADgGAFgFIAGgGIgEAHQgEAHgEAIQgGAYgDAQQgCAcABAMIADAPQADAHAEAFQADAFAGADQAFAEAGACQAJADAYABQAMAAATgEQAIgCAFgDIAFgDIgEAFQgFAFgGADQgFADgIACQgTAEgMAAQgXgBgKgDgAFiBcIAYijIAJgBIgWCaQAmACAhAAQAPAAAKgCQALgCAGgEQgEAGgFAEQgHAEgLACQgKACgPAAQghAAgngCgAILBcQgHAAgDgDQgDgDABgHIACgLQABgHADgCQACgCAEAAIAAABIgCALQgBAHADADQADADAHAAIAHAAIAEAAQgBAFgDACQgDADgHAAgABVBcIATiGIgxAAIAEgdIAJAAIgDATIAxAAIgTCGIAcAAIgBAKgAgCBcIgGgrIgtAAIgJAXIgGAAIAOghIA2AAIAGArIAZAAIACAKgAh5BcIBGiaQACgFAEgCIADgCIhECZIAgAAIgEAKgAj7BcIAYijIAJgBIgXCaIAcAAIgBAKgAk/BcIAOhdIABgIIg6BRIgEAAIA/hXIAMgWIACAAQgFANgCANIgNBdIAaAAIgBAKgAmlBcIAYijIAJAAIgXCZIAjAAIgHAKgAnrBcIATiJIgoAAIgRB1IgIAAIASh/IA6AAIgUCJIAdAAIgCAKgApJBcIAXijIAIAAIgVCZIAcAAIgBAKgAIqBHIACgMQABgGgDgEQgEgDgGAAIgIAAIgDABQABgFACgCIgQAAIALhxIAJAAIgKBnIATAAIgBAGIAGAAQAGAAAEADQACAEAAAGIgCAMQgBAGgDACQgCACgEABIAAgBgACFBIIASh8IAoAAIgBAKIggAAIgQBygAApBIIgYiPQgBgEgDgDQgEgDgEAAIggAAIgFAAIABgBQACgFADgCQAEgCAFAAIAgAAQAFAAADADQADADABAEIAaCZgAjLBIIAIgzQAOACARAAQAQAAAJgCQAJgCAHgEIgHAIQgIAFgLADQgJACgRAAIgNAAIgGAngAkQBIIAViZIgiAAIAHgKIAlAAIgXCjgAm6BIIAViZIh6AAIABgKICDAAIgXCjgAHqA/QAEgIACgNIABgSQgBgIgDgFQgEgGgFgEQgHgBgJgBIAAgBQAIgBAGgCIAGgEIAGACQAFAEAEAEQADAFABAIIgBASQgCANgEAIQgEAIgHAFIABgDgAFMA4IAHgOQAEgLAGgeIABgVIAAgTQgCgIgCgHIgGgMQgEgFgFgDQgFgEgHgCIgOgDIgSgBQgXABgJADQgHACgGADIgEADIAEgEQAFgFAFgEQAGgDAHgCQAJgDAXgBIASABIAOADQAHACAFAEQAFADAEAFIAGAMQACAHACAIIAAATIgBAXQgGAcgEALIgHAOIgIAMIgFAFIADgHgAGbAJIAnABQAFABADADQACACAAAFIAAAMQgBAHgCAEQgCAFgEADQgDACgFABIgnABgAGeAuIAkgBIAAgCIAAgMQAAgFgCgCQgDgDgFgBIgWgBgAD+A1QgFgCgDgGQgCgHgBgKQABgKACgRQADgQACgLQADgLAFgGQAFgHAGgCQAHgDAKAAQAJAAAGACQAFADADAGQACAGABALQgBAKgCARQgCAQgDAKQgEAMgFAGQgEAGgGADQgHADgJAAQgKAAgGgDgAEIgrIgDAHQgDALgCASQgCAPgBAKQABAKACAHQACAGAGACQAGADAJAAIANgBIADgJQADgKACgSQADgPAAgKQAAgLgDgGQgDgGgGgDQgFgCgJAAQgIAAgFACgAlzAmQAFgQABgLIANhcIgaAAIABgKIAjAAIgNBcIgCAKIA7hSIADAAIg+BWQgIALgEAMgAIvAUIARhnIgaAAIABgKIAjAAIgTBxgAgrAKIAbhAIAHAAIAIBAgAghAAIATAAIgDgigAhsgCQAEgKACgQQACgQgCgKQgCgLgGgGQgHgHgLgDQgLgDgRAAQghABgTABIABgJQAUgCApgBQARAAALADQALADAHAHQAGAGACALQACAKgCAQQgDAQgDAKQgFALgHAEIgDACIAFgHgAi/gDIAGg0IAbAAIALABQAEABACADQADACABAFQAAAFgCAHQgBAJgCAFQgBAGgDACQgEADgEACIgNABgAi1gNIAYAAIAHAAIABgIQACgHgBgFQAAgFgDgCQgCgDgEgBIgLgBIgJAAgAGkg3IAbAAQANAAAEADQAEAEgBAMIgDALQgCAEgEADQgCACgFABIglABgAGogYIAhAAIAAgCQABgMgEgEQgEgDgNAAIgKAAgAHygXIAEgQQABgNgCgIQgCgJgHgFQgGgFgLgCQgLgCgQAAIgzABIABgJQASgCAqAAQAQAAALACQALACAGAFQAHAFACAJQADAIgCANIgEAQQgCAGgEAFIgHAFIADgGgADJg+IADgTIh+AAIABgKICHAAIgEAdg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ADsBRQgGgCgFgEQgGgDgDgFQgEgFgDgHIgDgPQgBgMACgcQADgQAGgYQAEgIAEgHIAEgHIAEgEIAGgGIAEgDQAGgDAHgCQAJgDAXgBIASABIAOADQAHACAFAEQAFADAEAFIAGAMQACAHACAIIAAATIgBAVQgGAegEALIgHAOIgDAHIgFAFIgGAFIgFADQgFADgIACQgTAEgMAAQgYgBgJgDgAEOg0QgGACgFAHQgFAGgDALQgCALgDAQQgCARgBAKQABAKACAHQADAGAFACQAGADAKAAQAJAAAHgDQAGgDAEgGQAFgGAEgMQADgKACgQQACgRABgKQgBgLgCgGQgDgGgFgDQgGgCgJAAQgKAAgHADgAFtBSIAWiaIABgJIAJgBIAzgBQAQAAALACQALACAGAFQAHAFACAJQACAIgBANIgEAQIgDAGIgDAFIgEADIgGAEQgGACgIABIAAABQAJABAHABQAFAEAEAGQADAFABAIIgBASQgCANgEAIIgBADIgBAAQgEAGgFAEIgBAAQgGAEgLACQgKACgPAAQghAAgmgCgAGUA4IAngBQAFgBADgCQAEgDACgFQACgEABgHIAAgMQAAgFgCgCQgDgDgFgBIgngBgAGegOIAlgBQAFgBACgCQAEgDACgEIADgLQABgMgEgEQgEgDgNAAIgbAAgAIcBSIgHAAQgHAAgDgDQgDgDABgHIACgLIAAgBQABgGADgCQACgCAEAAIADgBIAIAAQAGAAAEADQADAEgBAGIgCAMIAAABQgBAFgDACQgCACgEABIgEAAgAB7BSIgcAAIATiGIgxAAIADgTIABgKIAJAAIB+AAIgDATIgBAKIgJAAIgoAAIgSB8IgBAKgAAfBSIgZAAIgGgrIg2AAIgOAhIgEAKIgGAAIggAAIBEiZIABgBQACgFAEgCIADgCIAFAAIAgAAQAEAAAEADQADADABAEIAYCPIACAKgAgrAKIAqAAIgIhAIgHAAgAjVBSIgcAAIAXiaIABgJIAJgBQATgBAhgBQARAAALADQALADAHAHQAGAGACALQACAKgCAQQgCAQgEAKIgFAHIgHAIIgDACQgHAEgJACQgJACgQAAQgRAAgOgCIgIAzIgBAKgAi/gDIAYAAIANgBQAEgCAEgDQADgCABgGQACgFABgJQACgHAAgFQgBgFgDgCQgCgDgEgBIgLgBIgbAAgAkbBSIgaAAIANhdQACgNAFgNIgCAAIgMAWIg/BXIgHAKIgDAAIgjAAIAXiZIABgKIAJAAIAaAAIgNBcQgBALgFAQIACAAQAEgMAIgLIA+hWIAHgKIADAAIAiAAIgVCZIgCAKgAnEBSIgdAAIAUiJIg6AAIgSB/IgCAKIgIAAIgcAAIAViZIACgKIAJAAIB6AAIgVCZIgCAKgAIlAeIgTAAIAKhnIABgKIAJAAIAaAAIgRBnIgCAKg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-58.7,-9.5,117.4,19.2);


(lib.Символ32 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAaBRQgHgCgFgEQgFgDgEgFQgEgFgBgHIgDgPQgBgMADgcQABgQAGgYQADgIAEgHIAEgHIAEgEIAGgGIAFgDQAFgDAHgCQAJgDAYgBIARABIAOADQAHACAFAEQAFADAEAFIAGAMQADAHABAIIABATIgCAVQgGAegEALIgGAOIgEAHIgFAFIgFAFIgGADQgFADgHACQgUAEgMAAQgXgBgJgDgAA8g0QgHACgFAHQgEAGgDALQgDALgDAQQgCARAAAKQAAAKACAHQADAGAGACQAFADAKAAQAJAAAHgDQAGgDAFgGQAFgGADgMQADgKACgQQADgRAAgKQAAgLgDgGQgDgGgFgDQgGgCgJAAQgKAAgGADgAkWBRQgGgCgFgEQgGgDgDgFQgEgFgDgHIgDgPQgBgMACgcQACgQAHgYQADgIAEgHIAFgHIAEgEIAGgGIAEgDQAGgDAHgCQAJgDAXgBIASABIAOADQAHACAFAEQAFADAEAFIAGAMQACAHABAIIABATIgCAVQgFAegEALIgHAOIgEAHIgEAFIgGAFIgFADQgGADgHACQgTAEgNAAQgXgBgJgDgAj0g0QgHACgEAHQgFAGgDALQgDALgCAQQgDARAAAKQAAAKADAHQACAGAGACQAGADAJAAQAKAAAGgDQAHgDAEgGQAFgGADgMQADgKADgQQACgRAAgKQAAgLgCgGQgDgGgGgDQgFgCgKAAQgKAAgGADgAG/BSIgbAAIAOhdQACgNAEgNIgCAAIgMAWIg+BXIgHAKIgDAAIgjAAIAWiZIABgKIAJAAIAaAAIgNBcQgBALgFAQIACAAQAFgMAHgLIA+hWIAHgKIADAAIAjAAIgWCZIgCAKgAEVBSIgdAAIAUiJIg6AAIgSB/IgBAKIgJAAIgcAAIAWiZIABgKIAJAAIB6AAIgVCZIgCAKgAhWBSIgcAAIATiGIgxAAIADgTIABgKIAJAAIB+AAIgCATIgCAKIgIAAIgpAAIgSB8IgBAKgAljBSIgcAAIATiJIg5AAIgSB/IgCAKIgIAAIgdAAIAWiZIACgKIAJAAIB6AAIgWCZIgBAKg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#141414").s().p("AAQBbQgHgCgFgEQgEgDgDgFQgEgFgCgHIgEgPQgBgMADgeQACgOAHgYQACgIADgHQADgGAFgFIAGgGIgEAHQgEAHgDAIQgGAYgBAQQgDAcABAMIADAPQABAHAEAFQAEAFAFADQAFAEAHACQAJADAXABQAMAAAUgEQAHgCAFgDIAGgDIgFAFQgFAFgGADQgFADgHACQgUAEgMAAQgXgBgJgDgAkgBbQgGgCgFgEQgGgDgDgFQgEgFgDgHIgDgPQgBgMACgeQACgOAHgYQADgIAEgHQAEgGAFgFIAGgGIgFAHQgEAHgDAIQgHAYgCAQQgCAcABAMIADAPQADAHAEAFQADAFAGADQAFAEAGACQAJADAXABQANAAATgEQAHgCAGgDIAFgDIgEAFQgFAFgGADQgGADgHACQgTAEgNAAQgXgBgJgDgAGaBcIAOhdIABgIIg6BRIgDAAIA+hXIAMgWIACAAQgEANgCANIgOBdIAbAAIgCAKgAE1BcIAXijIAJAAIgWCZIAjAAIgHAKgADuBcIAUiJIgoAAIgRB1IgJAAIASh/IA6AAIgUCJIAdAAIgCAKgACQBcIAXijIAJAAIgWCZIAcAAIgBAKgAh8BcIATiGIgxAAIAEgdIAJAAIgDATIAxAAIgTCGIAcAAIgBAKgAmJBcIATiJIgoAAIgRB1IgIAAIASh/IA5AAIgTCJIAcAAIgBAKgAnoBcIAYijIAIAAIgWCZIAdAAIgCAKgAHJBIIAWiZIgjAAIAHgKIAmAAIgYCjgAEfBIIAViZIh6AAIABgKICDAAIgXCjgAhMBIIASh8IApAAIgCAKIggAAIgQBygAlZBIIAWiZIh6AAIABgKICDAAIgXCjgAB6A4IAGgOQAEgLAGgeIACgVIgBgTQgBgIgDgHIgGgMQgEgFgFgDQgFgEgHgCIgOgDIgRgBQgYABgJADQgHACgFADIgFADIAEgEQAFgFAGgEQAFgDAHgCQAJgDAYgBIARABIAOADQAHACAFAEQAFADAEAFIAGAMQADAHABAIIABATIgCAXQgGAcgEALIgGAOIgJAMIgFAFIAEgHgAi2A4IAHgOQAEgLAFgeIACgVIgBgTQgBgIgCgHIgGgMQgEgFgFgDQgFgEgHgCIgOgDIgSgBQgXABgJADQgHACgGADIgEADIAEgEQAEgFAGgEQAGgDAHgCQAJgDAXgBIASABIAOADQAHACAFAEQAFADAEAFIAGAMQACAHABAIIABATIgCAXQgFAcgEALIgHAOIgIAMIgGAFIAEgHgAAsA1QgGgCgDgGQgCgHAAgKQAAgKACgRQADgQADgLQADgLAEgGQAFgHAHgCQAGgDAKAAQAJAAAGACQAFADADAGQADAGAAALQAAAKgDARQgCAQgDAKQgDAMgFAGQgFAGgGADQgHADgJAAQgKAAgFgDgAA1grIgCAHQgDALgDASQgCAPAAAKQAAAKACAHQADAGAGACQAFADAKAAIAMgBIADgJQADgKACgSQADgPAAgKQAAgLgDgGQgDgGgFgDQgGgCgJAAQgIAAgFACgAkEA1QgGgCgCgGQgDgHAAgKQAAgKADgRQACgQADgLQADgLAFgGQAEgHAHgCQAGgDAKAAQAKAAAFACQAGADADAGQACAGAAALQAAAKgCARQgDAQgDAKQgDAMgFAGQgEAGgHADQgGADgKAAQgJAAgGgDgAj6grIgDAHQgDALgCASQgDAPAAAKQAAAKADAHQACAGAGACQAGADAJAAIANgBIACgJQADgKADgSQACgPAAgKQAAgLgCgGQgDgGgGgDQgFgCgKAAQgHAAgFACgAFmAmQAFgQABgLIANhcIgaAAIABgKIAjAAIgNBcIgBAKIA6hSIADAAIg+BWQgHALgFAMgAgHg+IACgTIh+AAIABgKICFAAIgDAdg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-48.9,-9.5,97.9,19.2);


(lib.Символ29 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag2BlIACgkIhsAAIgHAkIgcAAIAJg+IAQAAQAKgRANghQAGgSAJgjQABgJAEgGQADgGAGgEQAFgEAHgDQAHgCAIAAIBHAAIgUCJIAWAAIgJA+gAhchEQgEADgCAJIgNAyQgLAegIAPIA2AAIAQhuIgUAAQgIAAgEADgAEzBBQgHABgDgEQgDgDABgGIABgMQABgGAEgDQADgDAGAAIAJAAQAGAAADAEQAEADgBAGIgCAMQgBAGgDACQgDADgGAAgAD2BBIgFgqIg5AAIgSAqIgmAAIBFiaQACgEAEgDQADgCAFAAIAiAAQAFAAADADQAEADAAAEIAaCZgADtgFIgIhCIgHAAIgaBCIApAAgAAABBIAVijQAUgCApAAQARAAALACQALADAHAHQAGAHACAKQACAKgCAQQgCARgEAKQgFAKgHAGQgHAEgLACQgKACgQAAQgRAAgOgCIgJA9gAAvgUIAYAAIANgBQAFgCADgDQADgCACgGQACgFABgIQABgIAAgFQgBgEgCgDQgCgDgFgBIgKgBIgbAAgAj4BBIAJg/IgWAAQgIAAgFAEQgFADgDAIIgTAwIgnAAIAVgzQADgJAKgHQAHgGAJAAIAAgBQgIgBgGgFQgGgEgDgHQgDgGgBgIQgBgIACgIQABgNAFgJQAFgIAIgFQAIgFALgCQALgCAPAAQAfAAAhACIgXCjgAkQhEQgDACgCAFQgCAEgBAGIAAAMQAAAFACADQACAEAEABQAFACAGAAIAaAAIAHgwIgZAAQgNAAgGAEgAE9gFQgHAAgDgDQgDgDABgGIABgMQABgGAEgDQADgDAGAAIAJAAQAGAAAEAEQADADgBAHIgCAKQgBAHgDACQgDADgGAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-34.1,-10.2,68.3,20.4);


(lib.Символ25 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AiBBoQg6g6AAhQQAAhJAug2QgSAmAAAvQAABPA5A6QA7A6BPAAQBSAAA5g6IANgOQgPAfgaAaQg4A6hSAAQhQAAg6g6g");
	this.shape.setTransform(-7.4,7.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.698)").s().p("AhGDwQg7gSgvguQhIhJgBhnQABhmBIhKQBKhIBmgBQA/ABA0AbIAAADIACAKQAEAGAGADIAAABQgcgPgjAAQg6AAgnApQgpApAAA6QAAA5ApAoQAnApA6AAQA6AAApgpQApgoAAg5QAAgkgQgeIACAAQAIAAAHgDQAtA/AABPQgBBnhJBJQguAug6ASQgiAJgmABQglgBghgJgAjOAQQAABRA6A6QA6A7BSAAQBQAAA4g7QAagZAPgfIgNAOQg5A6hSAAQhPAAg7g6Qg5g6AAhQQAAguASgmQguA2AABHgACjisIgKgJQAGAAAIgDQAAAIAEAIIABACIgBADIgIgJg");
	this.shape_1.setTransform(-5.5,2.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#141414").s().p("Ah4B7QgpgqAAg5QAAg4ApgpQApgpA6AAQAhAAAcAPIAAgCQgHgCgDgGIgDgKIABgDQADgLAdgRQAigVAQAOQADAFAIAIIAWAVIAHAHQAMANAAALQAAAKgUAVQgNANgLAFQgIADgHAAIgCAAQAQAeAAAiQAAA5gpAqQgpApg4AAQg6AAgpgpgABChSIAKAJIAIAIIABgCIgBgCQgEgIAAgIQgIADgGAAg");
	this.shape_2.setTransform(3.2,-7.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#999999").s().p("Ag0AjIgWgVIANgHQAsgVAdgLQAegKAXgHIAKAnQgqADg1AdIgZAOIgHgIg");
	this.shape_3.setTransform(22.9,-23.3);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-30.5,-27.6,61,55.3);


(lib.Символ23 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AReJKIgWgCQgWgCAAgEQAfgBAVgDIATgDIEIAAIEPAFIACAIIgDACgEgmUAIAQA2gQAegIQAygNB4gJIDWgCQBMgFAEAFQgFAChkAHIjPABQhWAKgwANQgdAHg7AUQgKgGgEgGgEAjHAFQQg7gNi8gYQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAAAAAIACgCQDNAbAmAIQBJAPCFA0QiQgug+gNgAU9FSIjjgRQAAAAAAgBQABgBAAAAQAAgBAAAAQABAAAAgBIACgBQAzAABaAGQBcAHApAHIgDACgAyTEXQBogMAvAgIgxgHQgqgFgLAAQhbAAgkAKQgTAGgcALQAjgYBagLgAL2DnQALAAAngSQAogTAVADQgLAHggAKQgcAJgJAIgAi/CmQg4gIgwgCQAageA+AQQAiAJA9AUIgEABIgRABIg6gHgA/bBsQAVgBBBAMQgKAGhBAIIhdAIQAxgeAhgDgAbHiIQgvgJgMgGIAAgDIAxAJQA6ALBMAHQgTACgTAAQgfAAg3gLgAZYiVQgJgCAAgDIATAAIABAFIgEAAIgHAAgEgjQgCsQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAAAgBIACgBIBgABQBfABABADIgDACgARokkQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAAAgBIACgBQECABACAEIgDACgA2QkrQAngQAagGQAugJBwAKQiBACgeAGQgUADgbAMgAhwk6QAWgQBHAHQA1AGAhALQiAgSgzAKgAm5mfQhDACgsAKQASgHAbgGQAqgJAaADIAUAWIgBAFIgVgUgAQQn8QAAgEAEgBQDFABADAEIgEACgAjAohQgWgCAAgEIBbgEQBAgCBkAAQAOAGAEAGQgSgFjGAHQgSAAgRgCgAZoo/QgTgCAAgEIA2gDQATgBACACIglAKIgTgCg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-245.3,-58.6,490.7,117.3);


(lib.Символ22 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjQHuQgKgDgOgIQgQgGgkgCIAAgDQApACAJADQAEAFAHACQAdAKDtAFIACAIIg4ACQihAAgkgPgEAgwAG9QhrgRg7gTQAAAAAAgBQAAgBABAAQAAgBAAAAQAAAAABgBIABgBQAoARFkApQAIACgTAAQhiAAh8gTgA0fHIICEgHICNgHIBagBIACAGQhHACiDAHIh/AIQgkAAAAgIgAYlHNQgKgBgGgDIj0AAQgeAIgxgJQAigBAcgDIAdgDIDfAAQATACASALIgEAAIgIgBgEAjkAEEQgqgDAAgDQBEgBA/gEIBkgGIAPgGQgHgFhDgHIlbgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIABgCIFFAAIA3AJQAlAGALAGQgKAFhIAKQhBAJgKAAIg4gBgAhmCzQB5gDBcgLQBVgLApgEIAAgBIAPABQAOABABADIhtARQhuAPhwAAQgmAAAAgHgAvlBEQgwgZgbgGQgogJgpAOQgDALAAgTQAAguCiA+QCsBNATADIAJAEQAJADABACQhbgIh6g/gA7/BeQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAAAgBIACgBQCGABAMABQBDADAbAPQg1gEi+gLgAhaBmQgZgCAAgEQBogFBLgLQBmgOBBgGIAAgBIARABQASABABADQgLABiaATIiZAUQgUAAgTgCgAOGgJQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBIABgBQBeAFCAADQBWAEAbAOgARLiBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAAAgBIABgBQEYABABAEgArNkJQAAgXBXAHQBKAGAjANIABABQgCABgMAAQgJAAgggHQgfgHgKAAQgPAAgjAFQglAFgDAEIgFAEIgCABQgEAAAAgKgEglEgGKIg4gSQgjgLgZgEQACgEAMgEQALgEAHAAQADAGgLABIBdAJQAzAFA2ADQAAABAHADQAHAEABACQgjASgmAAQgYAAgYgHgAWxmNQAAgFADgBQA4ABACAFQgCABgQAAIgrgBgA41n2QAAgFADgBIC4ABQC4ACABADIgDACg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-248.9,-50.9,497.9,101.9);


(lib.Символ21 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A9tIcQgjgHiSgDQgPgFgDgEIAAgDQCpAIATAEIFnAAIApgDQAfgCApAAIACAFQgDACiIAIgApkHUQiMgWhHgGQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBIABgBQDtAPB9AjIgCABIgQABQgIAAiAgTgAUPHXQidgLgVgKQgDgEAAgDQDaAAB/AjQAIACgSAAQhMgDhOgGgApsDmQAAAAAAgBQAAgBABAAQAAgBAAAAQAAAAABgBIABgBIAjABQAjABABADIgDACgAICC7ICLgdQgpAUhaASQgvAJhAAKQAMgIBbgUgAVNCeIgvgDQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAAAgBIACgBIAZABQAZACABAEIgCAGQgFAAAAgFgA9QBWQg/gEhwgCQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBIABgBQC+gBANADQgLAGApAFIACABQAAABgMAAIgzgEgAqpA6QAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAIABgCIBxABQBxACABADIgEACgAx/AXIi6gDQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAABgBIACgBQC+gBAQADQADABAAAEQAAADARADQgCABgFAAQgKAAgbgGgAAGAUQAFgEACABQAHAEAlgOIAEABQAFACABADQgOAJgQAAQgTAAgMgCgAAOABQAHgGAEAAIACAQIgHACgAQ2AGQhqgDAAgDIDgAAQAmgFA2gBIABAGQgBAAgrACIg9AFIhqgBgABbg6IALABQAMABAAADQgWAAgJAIIgQAPQAOgTAKgJgA9qg8QhmgQgoAIQAZgNBmANQBgANAiAQIhzgVgAeBiDQgngEgbgFIjDgDQgGgCgOACIgTADQAFgPAFAAIAlACQA/AEBtABQANAAArAGQA1AHAQAHQgKAAgigDgAuWjLQAAAAAAgBQAAgBAAAAQABgBAAAAQAAAAABgBIACgBIBLABQBMABABADIgDACgARTjvQgYgIhbgHQAAgEAEgBQBTAFAYAHIAzAOQgdAAgSgGgA1oj7IBYABQBWABABADIgCACQixACgKADQAHgKAHgCgAYJkMQhBgDAAgDQBagDBkgGQBegFAtgBIABAFQg8ADhAAHIg+AHIhPgBgA1+mlIhygNQAAgEAEgBQC8ANBkAPIgEABIgRABQgnAAh2gMgAmsmuQhZgGgdgFQAAgFADgBQA4AABYAHQBiAHAFAHIgKABIgYABQgTAAhPgGgAbUneQgagDAAgDQBvgHBngYQBdgWBIgCQguAOiBAZQh7AXgQAAQgUAAgTgBg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-210.2,-54,420.4,108.1);


(lib.Символ20 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AhMgWICeAWIieAXQgKgXAKgWg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.2,-2.3,16.5,4.7);


(lib.Символ18 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(3,1,1).p("AAxjzQBIAOA3A2QA0A1APBEAD1AtQgNBKg4A5Qg3A2hIAOAjyg2QAPhEA0g1QA3g2BIgOAgwD0QhIgOg3g2Qg4g5gNhK");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-26,-25.9,52.1,51.9);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ai1AhIAgAAIAAABIgggBgAjtAVQgBgBAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAIABgCIAlABIAcACIAAACgAlgARIAAgDIBHABIAAACgAhdAKIAAgBICbgGIAAABIgRABIAAABQgvABgzAEgAEvAGQgNgCgCgEIAXABQASACAcABIAdABIALAAIAAABIgwABIgugBgAlFAEIhOgDQgQgBABgFIAZAFIBMAAIAAAEgACcABIAiAAIAAACIgiAAgAjTABQgZgBAAAAIAaAAIAEABIAAAAgAj6gHIgDgCIATgBIAnAAIAAADgAgLgPIgMgBIAXgBIBVAAQAsABAAABIiBAAIgLAAgAEKgSQgFgBgTAAIAAgBIAWAAIA5ACIAAABgAGZgaIgdgBIgHAAQACgGANABIAcADIADABIAAACg");
	this.shape.setTransform(2.7,-2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ah1AgIC4gUIAAABIi1AUQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAgAjqAcQBOgIBRgEIAMAAIAAgBQB7gNCygFIAAABIiqAJIhnAJIAEAAIAAABIgNACIgjAAQg9ADhaAHQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAAAgAlLAGIAAgCQAWAAB0gFIAkAAIAggBIAAACIhDAAIhuAGgAlPgCQAGgDA0gFIAAABIg0AHgABbgGIAAgCQANAAAwgFIAZAAIATgBIAFABIAAABQhMACgdAEgAAdgWIAUgGQAQgCBFgCIBwAAIAZAAIAAABIiUACQg+ADgbAEgAFXgaIAqAAIAKgDQABAAABABQABAAAAAAQABAAAAAAQAAABAAAAIgKACQgDABgrABgAmOgeIAigBIBBABIAAACIhjABg");
	this.shape_1.setTransform(0.6,-0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AjFAeIAxgFIALgBQgQAAgogEIiDAAIgFABIgKAAIAAgCIALgBIAAAAICIAAIAcACIAaADIADABIAAAAQAjgDA3gBIAAgBIBRgBIiBAIIhkAGQgBAAgBgBQgBAAAAAAQgBAAAAAAQAAgBAAAAgAghANIACgDICLgLIAqAAQARAAgBABIgSAAIAAAAIgoAAIhOAGQgwAEgJAEgADYACIAAgCIAYAAIAAgBIArgBIAsgCIAkAAQAWAAAAACIg9ABIg6ABIgtACgAgCgBIAAgCQB1gNA5gEIAAACIiqARgAmAgEIAAgCIAmgDIA2gDIA2ABIAAADIhAAAIgoACIgUACgAhggWIADgEIARgBIAhAAIAngBIBtAAIAAAAIAKABIAAABIi7ACIgQACgAENgdIAAgBQARgBBeAGIAAABIgJABQhAAAgmgGg");
	this.shape_2.setTransform(2.3,-1.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ACGAqIAAgBIArAAIAQACIAAAAIgFABgAhQAUQgkgEgVgFIAiADIAaAEIACACIAAAAgAB1APIhdgKIAAgCQAiACAbADIAnAFIADAAIAAACgAloAJIADABIAAABIgGAAIgFgBIAAgEIAiACIARACIAAABgAhYAGQg6gFg/gJIAAgCIBBAHIBJAIIAAABgADkACIAAgCQAMAAAMAAIAaAAQAQACAgABIAAACgAFEgSIALAAQACABAeAEIAAABgAmpgTIAAgDIAOAAIAAgBIA6ABIAAACIg1AAIgDABgAF3giIgngIQAQgBAbAGIAvAJIAAABQgdgDgWgEg");
	this.shape_3.setTransform(3.5,-1.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_2}]},2).to({state:[{t:this.shape_3}]},2).wait(2));

	// Слой 1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1F73AC").s().p("AlbAnQgOgDgQgHIAEgBIADABQAIgDAxgDIAygEIArAAIAFAAQAOAAAIgDIAegEQApgDAOAAIACgBIAngFIAcADIgBABQAHAHAGACQAKAEARgBQArAABngLIAAABQAYABA8gKIBaAAIAHgOIAUgCIgGAQIARAAQAQAFAEAOIgHAUgAkDghIgJgFIBCAAQgiACgUAFIgDgCgAhugmIAUAAIgOADIgGgDg");
	this.shape_4.setTransform(3.7,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0B3F72").s().p("AlHArIgEABIgCAAQghAAgHgMIgEgLIgRgQQgKgHABgDQgBgPADgCIACABIAOAAIALAAQABgKACgBIADABIAMAAIARABIAGgEQBKgHAlASIAJAFIAEACQAUgFAhgCIAbAAQAbgEAnAEIAFADIAPgDQAYgEAigCQAAgCAVgBQAjgCBxAAIAJAFQAngCAzgBQAvgKBDgCQAAAFAIAQIgIAWIgDAAIgVABIgGAPIhaAAQg9AKgYgBIAAgBQhmALgtAAQgRABgKgEQgHgCgHgHIACgBIgagDIgoAFIgBABQgOAAgpADIgfAEQgIADgOAAIgEAAIgrAAIgzAEQgxADgHADIgEgBg");
	this.shape_5.setTransform(-1,-1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-41.5,-6,86.1,10);


(lib.Символ8 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FF0000","rgba(255,0,0,0.012)"],[0,1],0,0,0,0,0,10.2).s().p("AhpBqQgsgsAAg+QAAg9AsgsQAsgsA9AAQA+AAAsAsQAsAsAAA9QAAA+gsAsQgsAsg+AAQg9AAgsgsg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-15,-15,30,30);


(lib.Символ6 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.cannon();
	this.instance.setTransform(-92.5,-61);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-92.5,-61,185,122);


(lib.Символ38 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ37();
	this.instance.setTransform(0,10,1,0.779);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-175,-247.1,350,467.5);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 33
	this.instance = new lib.Символ33();
	this.instance.setTransform(108.5,-40);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).to({y:0},4).wait(52).to({x:97.5},0).wait(1).to({x:107.5},0).wait(1).to({x:108.5},0).wait(1).to({x:98.5},0).to({x:266.8},5).to({_off:true},1).wait(7));

	// Символ 34
	this.instance_1 = new lib.Символ34();
	this.instance_1.setTransform(-9.7,-40);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(2).to({_off:false},0).to({y:0},4).wait(58).to({x:-19.7},0).wait(1).to({x:-10.7},0).wait(1).to({x:-9.7},0).wait(1).to({x:-19.7},0).to({x:263.4},5).to({_off:true},1).wait(3));

	// Символ 32
	this.instance_2 = new lib.Символ32();
	this.instance_2.setTransform(-118.1,-40);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:0},4).wait(63).to({x:-128.1},0).wait(1).to({x:-119.1},0).wait(1).to({x:-118.1},0).wait(1).to({x:-128.1},0).to({x:263.4},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-167.1,-49.5,97.9,19.2);


(lib.Символ28 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ29();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#141414").s().p("Ag2BvIABgUIgBAAIABgQIhrAAIgHAkIgcAAIADgUIgDAAIAJg+IAQAAQAKgRANghQAGgSAJgjQABgJAEgGQADgGAGgEQAFgFAHgCQAHgCAIAAIBHAAIgDAUIADAAIgRB1IATAAIgDAUIADAAIgJA+gAhcg6QgEAEgCAIIgNAwIgKAbIAtAAIANhbIgRAAQgIABgEADgAEzBLQgHAAgDgDQgDgDABgHIABgKQgCgEABgFIABgMQABgGAEgDQADgDAGAAIAJAAQAGAAADAEQAEADgBAGIgCALQADADgBAGIgCAMQgBAGgDACQgDADgGAAgAD2BLIgFgqIg5AAIgSAqIgmAAIAJgUIgJAAIBFiaQACgEAEgDQADgCAFAAIAiAAQAFAAADADQAEADAAAEIAaCZIgDAAIADAUgADrgPIgGguIgHAAIgSAuIAfAAgAAABLIABgUIgBAAIAVijQAUgCApAAQARAAALADQALADAHAGQAGAHACAKQACAJgBANQABAKgCAOQgCARgEAKQgFAIgHAGQgHAGgLACQgKACgQAAQgRAAgOgCIgJA9gAAygeIAVAAIANgBQAFgBADgDQADgDACgGIADgLIgCgCQgCgDgFgBIgKgBIgbAAgAj4BLIADgUIgDAAIAHgrIgUAAQgIAAgFAEQgFACgDAJIgTAwIgnAAIAIgUIgIAAIAVgzQADgGAHgHIgEgHQgDgGgBgIQgBgHACgJIAAAAIgBgEQgBgHACgJQABgNAFgJQAFgIAIgFQAIgFALgCQALgCAPAAQAfAAAhACIgCAUIACAAIgXCjgAkQg6QgDADgCAEIgCAHIABADQACAEAEABQAFACAGAAIAaAAIAEgcIgWAAQgNAAgGAEgAE9ADQgHAAgDgDQgDgBABgHIABgKQgCgEABgFIABgMQABgGAEgDQADgDAGAAIAJAAQAGAAAEAEQADADgBAHIgCAKQADAEgBAGIgCAKQgBAHgDAAQgDADgGAAg");
	this.shape.setTransform(-1,0);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-35.1,-11.2,69.3,22.4);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ20();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-3.6},9).to({x:0},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8.2,-2.3,16.5,4.7);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ18();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.92,scaleY:0.92},4,cjs.Ease.get(-1)).to({scaleX:0.82,scaleY:0.82},5,cjs.Ease.get(1)).to({scaleX:0.91,scaleY:0.91},5,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26,-25.9,52.1,51.9);


(lib.Символ16 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ19();
	this.instance.setTransform(0.4,24.2,1,1,0,90,-90);

	this.instance_1 = new lib.Символ19();
	this.instance_1.setTransform(0.4,-25.4,1,1,90);

	this.instance_2 = new lib.Символ19();
	this.instance_2.setTransform(25.3,-0.5,1,1,0,0,180);

	this.instance_3 = new lib.Символ19();
	this.instance_3.setTransform(-24.3,-0.5);

	this.instance_4 = new lib.Символ17();

	this.addChild(this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-32.6,-33.6,66.1,66.1);


(lib.Символ10 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ11();
	this.instance.setTransform(10.5,48);

	// Слой 1
	this.instance_1 = new lib.Pirate_Ship_SU();
	this.instance_1.setTransform(-49.5,-50);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-49.5,-50,104.6,102);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ23();
	this.instance.setTransform(2.3,31.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3).to({alpha:0},0).to({alpha:1},4).wait(7));

	// Слой 3
	this.instance_1 = new lib.Символ22();
	this.instance_1.setTransform(-23.7,16.9);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},4).to({alpha:0},4).wait(6));

	// Слой 1
	this.instance_2 = new lib.Символ21();
	this.instance_2.setTransform(-28,23.6);
	this.instance_2.alpha = 0.75;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({alpha:1},1).wait(4).to({alpha:0},4).wait(2).to({alpha:0.75},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-272.7,-34,520.4,124.4);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF00").s().p("AgZAxQAGgSAAgGIgCgFQAMgGAAAOQgCAagKAAQgEAAAAgFgAAiAlQgGgNAAgFIABgCQAIAAAEALQAEAJAAAKQAAABAAABQAAAAgBABQAAAAAAABQAAAAgBAAQgDgCgGgMgAA0gGIABgCQAGABAEAIQADAIAAAGIgBAFIgCAAQgLgXAAgDgAhBgOQAEgKAXgDIADADQgMADgRAIgAAWguIgBgDQAAgHAdAEQAHABAEAFIAFAIQAAABgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgYgLgRABg");
	this.shape.setTransform(-0.7,1.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhEA0QAAgKAOgQQAPgQAAAOIgWAjQgIAAABgHgAA5AdIgHgHQAAgLAUAVQgBABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAQgDABgHgHgAgqg3IABgCQAGAAAGALQAGALAAAEQAAAEgEAAQgGAAgJgcg");
	this.shape_1.setTransform(1.2,-1.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFF00").s().p("AgrAgQAAgHAHgPQAHgMAAAKIgDAQIgFAVQgGgCAAgLgAAmAIIACAAQAEAGAAADIgBADIAAABQgFgDAAgKgAgngsQAMgBAJAFIAAACIgBABQgFAAgPgHg");
	this.shape_2.setTransform(-0.3,1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AACAjQABgJAIAHQAJAHAAAFIgBAEQAAABgBAAQAAAAgBABQgBAAAAAAQgBAAAAAAQgFAAgIgQgAhFADQABgEAKgCQAMgBAAAFQAAAHgPAAQgIAAAAgFgAA0gLIgJgIQAAgHANAFQAOAFAAAHQAAAGgGAAQgDAAgJgIgAAIgmQAAgIAIgDQAGgDABAIQgFARgEAAQgHAAABgLg");
	this.shape_3.setTransform(-0.4,-0.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFF00").s().p("AAAAiIAAgFIgFgVQAAgIAFALQAEALAAADIgCANIgCABQgBgCABgDgAg+AXIgCgNQAAgHAEgSQABgHAJgKQAIgMAAALIgEANIgDAJIgBAEQgGASAAAMIgDABgAAzAAQgJgTAAgDIABgBQABAAAAgBQAAAAAAAAQABAAAAgBQAAAAAAgBQATAfABAPIgCACIgMgWg");
	this.shape_4.setTransform(2,6.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSApIABgEIADgJIAFgFQAJgIAAANQgEASgIAAQgFAAgBgFgAAsATQAAgIAHAHQAFAGAAAGQAAAEgDABQgJgNAAgDgAhIAJIAAgDQASgmAIAQQgFAJgSARgAAzgWQAAgHALgJQALgJAAAMQgPARgDAAQgFAAABgEgAgLglQAAgGAFgBQAGgBAAAHIgBAJQgCAIgCABQgGgCAAgPg");
	this.shape_5.setTransform(-1.2,1.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF00").s().p("AAxAvQABgHgDgMIgEgUQAFAAAEAKQADAJAAAGIgCAOQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAABgBAAgAAAAiIgBgLQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAIABAKIgBAFgAg2gPQAAgPAFgLQAFgLAAANQgDAngDAAQgFAAABgPg");
	this.shape_6.setTransform(0.1,6.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABLBIQAAgLADgOIABAAQACADAAAFQAAAJgDALQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBgAgmBAQAJhPAAAyIAAAOIgFASIgEgDgAAJA+IgBgFQgBgDAEgKQADgLAAgEQAGgOACAJQACAFAAAKQAAADgEAKQgFAKgEAAIgCAAgAAzASQgHgQAAgCQAAgLAMARQALATAAAIQAAAEgCADQgGgFgIgRgAApAdIACgBQAAABAAAAQABAAAAAAQAAABAAAAQABAAAAABIgBACIgBACgAhQAJQAHgMAIgIQAJgIAAAKQABABgKAIIgOAKgAA3gmQgIgHgJAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIAAgCQAAgKARAHQARAIAAAJIgCADIgDACIgJgIgAgUhJQAOgEAAALIAAACIgQAAQgGAAgGACIgJAEQAKgLANgEg");
	this.shape_7.setTransform(0.3,2.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFF00").s().p("AAwA8IACgJQgDgTAAgHQAHAAACAGIAAAJQAAAMgGALQgBgBAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBgAgZAVQAAgTAKgOQAJgQAAAOQAAAHgPAfIgBAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBgAg3gkIAGgOQAFgJAIgCIABACQAAABgHAJIgKAOg");
	this.shape_8.setTransform(-2.7,4.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbA0QgBgMABgMQABgWALgBIAAACIgCAPIgCASQgBAYgCAHQgFgGAAgNgABEAqQgFgPgIgJQAKACAHALQAGAJAAAJQAAAMgEADIgGgWgAAnAsIgEgLIABgCQAIACAEAUIgBAEIAAABQgDgEgFgKgAAAAdQAAgEAAgBQABABAAAFQAAAHgBABgAhNAgQACgRACgJQADgNAKgBIAAACQAAAGgQAggAAngnQAAgIAMALQANANAGAWIAAABIgEAAIgbgngAgbg+QgJgCgCgDQAEgEAJACQAIABADAEIgBACIgCABIgKgBg");
	this.shape_9.setTransform(0,2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFF00").s().p("AAHBJIgBgMQAAgIACgDQACAEAAAHQAAAIgCAEgAgoAuIgBgEQAAgIABgIQADgOAFAAIABAHIgCAOQgCANgCADQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAgAAKgxQAAgKAQgJQAQgJAAALQAAAEgEgBIgFgBQgIAAgMASQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAg");
	this.shape_10.setTransform(0,2.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAQBKQACgPgCgPIgDgaIAAgBIACgBQAFAJABAIIABAOQAAAMgFAPgAggA/QgBgMABgKQADgWALABIABADIgDAWQgCATgDAHIgCABQgBABgEgKgAAkAQQAFACAEANIAFAVIgBABQgEgRgJgUgAhIAcIAAgCQAAgDAFgPQAFgPADgDQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIgNAjIgBABgABJAPQgBgWgEgLQgJgUgYgOQAWgCANAZQAJARAAAPIgBAMIgCABgAhOggQAAgDAOgIQAOgHADABIABACQgIAGgWAMQgBgBAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBgAgehHIgBgCIAEAAQADAAAGACIAAADIgCAAQgDAAgHgDg");
	this.shape_11.setTransform(0.4,2.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFF00").s().p("AAAA+QAAgKAFgHQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAQgFAEQgCgCAAgFgAgZg0IAAgCQAAgEALACQALABAAAFQAAAAAAABQAAABgBAAQAAAAAAABQgBAAgBAAgAALhDIAAgBIAPAIQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgIAAgEgKg");
	this.shape_12.setTransform(-2.6,2.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAAA9IAAgPIgDgPIgCgOQAAgFADACQACADABADIAEANQACAHAAASIgEARIgBABQgCgFAAgKgAgyA9QAAgTAFgUQAGgWAJgLQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIgGAPQgHARgCAIIgDAUQgCAOAAAIIgCABQgBgDAAgKgAATAAQAKACAGAOQADAKAAANIgDAGQgJgWgHgXgAApggIAAgDQATAIAJARQAIAMgBAQIAAADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAQgSgrgOgLgAhMgRQABgFAJgMQALgNAHABIAAADQAAACgKAMQgLAMgGAEgAAehIQAIgHAKAIQAIAHACAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_13.setTransform(-0.2,4.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFF00").s().p("AAqAJQAAgJAKAHQALAIAAAKQAAAIgEAAgAg6AJQAHgKAOgGIABACIgMAMQgNAOgGAJIgBABIAKgWgAAygbQAAgJAKAJQAJAKAAAHIgBAFQAAAAABAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgRgWg");
	this.shape_14.setTransform(-0.4,2.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAJA/IABgVQAAgHADgBQAEAHAAAWIgBAUIgBABIgBAAQgFgHAAgOgAAhAhQAAgJAJAOQAIAPAAANQAAAEgDAAQgBAAgNglgAgyAvQAZgzAAASIgHAQQgJAPgGAGIgDgEgAgMgaQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABQAAACgLAGQAIgJACgBgAATgjQgCgFgEAAQgBACgDACQgEgCAAgEQAAgIALAEQAKADAAAKQAAADgEACgAgZg3QgNgLgMgDQAMgHAPAMQANAKAAAHQAAABgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgMgKgAAPhBQAAgIASgIQASgHAAAKQAAADgEAAIgHgCQgFAAgIAHIgJAHQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAg");
	this.shape_15.setTransform(-0.1,3.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFF00").s().p("AgkA3QAEgaAKABIAAACQAAACgFANIgIANQgBgCAAgDgAAdALIAAgCIACAAQAGALAAARQAAAGgCADQgGgLAAgYgAgZgsQgHgCgEgEQAAAAAAgBQAAgBAAAAQABAAAAAAQAAgBABAAIAFAAQALAAAEAHQAAAEgEAAIgHgCgAAIgyQAAgDAIgDQAJgEAGABIAAACQAAAEgVAFQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAg");
	this.shape_16.setTransform(-0.3,1.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AABA4QAAggAGgJQACAEAAAMIAAAOQgBAHgGAJQgBgCAAgDgAhQAQQAOgWARgEIABACQAAAEgfAUgAAwgIIAAgBIABAAQADABABAEIABAFIgBABIgFgKgAhOgQIAMgPQAJgKAOgCQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBACQgLADgIAJIgOAMgABHgfIgKgKIgQgHQgLgFAAgCQAAgJAYALQAYAKgBAIQAAAMgDAAQgCAAgFgIg");
	this.shape_17.setTransform(-0.1,2.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFF00").s().p("AgDA2IAAgOIABgHQAAgFACgBQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgBAYIgBABgAg2AGQALglAagEQgMARgWAZgAAcgoIgBgCQAAgGAbgGIABACIgMAEQgKADAAAFIAAABIgCABQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAg");
	this.shape_18.setTransform(-2.9,1.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AArApIgBgSQgDgPgPgOQAAgFAHADQAEACAFAFQADABABADIAEAHIADANIACAOQABAOgGAFQgEgEgBgLgAgHA0QAAgJgKggQAHAAAGALQADAIAAAGQAAAJgFALIgBgEgAhDAhIAAgJQAAgHADgJIAEgOIAHgQQACgGAFgEQAEgFAAAIQAAADgJAaQgIAYgFAKgAA8gTQgGgXgXgLQAQgJANAZQAJAUAAAQIgBABQAAAAAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAIgFgUg");
	this.shape_19.setTransform(0.7,3.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFF00").s().p("AhAAjQAAgLAPgSQAOgPAAAJQAAAAgIAMIgQAaIgBAAQgBAAgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBgAAFAbIgCgGQADgCACANIgCABIgBgGgAAsgRQAAgBAAAAQABAAAAgBQAAAAAAAAQABgBAAAAIALANQAIAKAAACIgBAGIgBAAQgIgSgLgKgAANgkIAAgBQAGADAEAHIAHALIAAAFIgBAAQgGgMgKgNg");
	this.shape_20.setTransform(2.6,0.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgUA9QAAgSABgPQAEgcAIAJIAAACQABAMgHAuIgEABQgEAAABgJgAA1AgIgDgJQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAABAAIAAgBQAEAEAHANIAAACQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBAAgBAAQgCAAgFgIgAAOAFIABgCQAIADAFALIAGARIAAACQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgEAAgOgggAhTAUQABgTAPgVQAOgWAAAQIgKARQgLARgDAWIgDABQgDgFAAgGgABHgDQgIgQgBAFQABgIAKALQALALAAAJIgBACQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAgBAAIgJgPgAhDgrIgBgCQAAgJAagKQAagLAAANIgBADIgDABIgJgDQgJAAgIAGQgMAKgHADg");
	this.shape_21.setTransform(-0.6,3.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_10}]},1).to({state:[{t:this.shape_13},{t:this.shape_12}]},1).to({state:[{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_17},{t:this.shape_16}]},1).to({state:[{t:this.shape_19},{t:this.shape_18}]},1).to({state:[{t:this.shape_21},{t:this.shape_20}]},1).wait(1));

	// Слой 1
	this.instance = new lib.Символ8();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.828},4).to({alpha:1},6).wait(1));

	// Слой 3
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.rf(["#FFC900","rgba(255,201,0,0.008)"],[0,1],0,0,0,0,0,10.2).s().p("AhpBqQgsgsAAg+QAAg9AsgsQAsgsA9AAQA+AAAsAsQAsAsAAA9QAAA+gsAsQgsAsg+AAQg9AAgsgsg");

	this.timeline.addTween(cjs.Tween.get(this.shape_22).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15,-15,30,30);


(lib.Символ5 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ7();
	this.instance.setTransform(-2,26.6);

	// Слой 1
	this.instance_1 = new lib.Символ6();

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-92.5,-61,185,122);


(lib.Символ4 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ5();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-92.5,-61,185,122);


(lib.Символ3 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ9();
	this.instance.setTransform(8.2,33.7);

	// Слой 1
	this.instance_1 = new lib.fon();
	this.instance_1.setTransform(-300,-150);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-300,-150,600,300);


(lib.Символ1копия2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ10();
	this.instance.setTransform(240,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(102).to({x:-1440},0).wait(1).to({x:240},0).to({x:-1440},102).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(190.5,-50,104.6,102);


(lib.Символ1копия = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ10();
	this.instance.setTransform(240,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-1440},102).to({_off:true},1).wait(104));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(190.5,-50,104.6,102);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ10();
	this.instance.setTransform(240,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:108.8},19,cjs.Ease.get(-1)).to({x:-36.9},20,cjs.Ease.get(1)).to({x:-197.3},20,cjs.Ease.get(-1)).to({x:-343},20,cjs.Ease.get(1)).to({x:-488.8},21,cjs.Ease.get(-1)).to({x:-620},19,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(190.5,-50,104.6,102);


(lib.Символ24 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ7();
	this.instance.setTransform(29.5,-26.6);

	// Слой 1
	this.instance_1 = new lib.Символ25();

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-30.5,-41.6,75,69.3);


(lib.Символ14 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ1();
	this.instance.setTransform(150.2,-30);

	this.instance_1 = new lib.Символ1копия2();
	this.instance_1.setTransform(231.8,-45.4,0.488,0.488);

	this.instance_2 = new lib.Символ1копия();
	this.instance_2.setTransform(-301.3,-35.4,0.488,0.488,0,0,180);

	// Слой 1
	this.instance_3 = new lib.Символ3();
	this.instance_3.setTransform(-34.8,0,1.183,1.067);

	this.addChild(this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-445.2,-160,890.6,320);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ4();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:7.6},14,cjs.Ease.get(-1)).to({y:16},15,cjs.Ease.get(1)).to({y:8},15,cjs.Ease.get(-1)).to({y:0},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.5,-61,185,122);


(lib.Символ36 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.setTransform(0,45.7);

	this.instance_1 = new lib.Символ16();
	this.instance_1.setTransform(4.1,-73);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-92.5,-106.6,185,213.4);


(lib.Символ30 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ28();
	this.instance.setTransform(-87.1,4.8);

	this.instance_1 = new lib.Символ24();
	this.instance_1.setTransform(102.3,2.8,0.449,0.449);

	this.instance_2 = new lib.Символ24();
	this.instance_2.setTransform(69.7,2.8,0.449,0.449);

	this.instance_3 = new lib.Символ24();
	this.instance_3.setTransform(37.1,2.8,0.449,0.449);

	this.instance_4 = new lib.Символ24();
	this.instance_4.setTransform(4.6,2.8,0.449,0.449);

	this.instance_5 = new lib.Символ24();
	this.instance_5.setTransform(-28,2.8,0.449,0.449);

	this.addChild(this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-122.3,-15.9,244.6,31.9);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.dvij = new lib.Символ14();
	this.dvij.setTransform(0,8);

	this.timeline.addTween(cjs.Tween.get(this.dvij).to({y:6.2},14,cjs.Ease.get(-1)).to({y:0},15,cjs.Ease.get(0.95)).to({y:4.3},16).to({y:8},14,cjs.Ease.get(0.95)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-445.2,-152,890.6,320);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Символ 38
	this.instance = new lib.Символ38();
	this.instance.setTransform(-600,-7,1,1,180);
	this.instance.filters = [new cjs.BlurFilter(34, 34, 1)];
	this.instance.cache(-177,-249,354,472);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-320,y:5},4).to({x:-600,y:-7},5).wait(1));

	// Символ 38
	this.instance_1 = new lib.Символ38();
	this.instance_1.setTransform(524.3,-7);
	this.instance_1.filters = [new cjs.BlurFilter(34, 34, 1)];
	this.instance_1.cache(-177,-249,354,472);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:250.3,y:5},4).to({x:524.3,y:-7},5).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ15();
	this.instance_2.setTransform(0,-8);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({scaleX:1.26,scaleY:1.26},4).to({scaleX:1,scaleY:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-809,-288.1,1550.3,568.8);


// stage content:



(lib.pirate = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.pus.visible = true;
		this.movieClip_1.visible = false;
		this.movieClip_2.visible = false;
		
		/* Пользовательский курсор мыши
		Заменяет курсор мыши по умолчанию на указанный экземпляр символа.
		*/
		stage.canvas.style.cursor = "none";
		this.movieClip_1.mouseEnabled = false;
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
			this.movieClip_1.x = stage.mouseX;
		}
		//Чтобы восстановить курсор мыши по умолчанию, раскомментируйте следующие строки:
		//this.removeEventListener("tick", fl_CustomMouseCursor.bind(this));
		//stage.removeChild(movieClip_1);
		//stage.canvas.style.cursor = "default";
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		/* Пользовательский курсор мыши
		Заменяет курсор мыши по умолчанию на указанный экземпляр символа.
		*/
		stage.canvas.style.cursor = "none";
		this.movieClip_2.mouseEnabled = false;
		this.addEventListener("tick", fl_CustomMouseCursor_2.bind(this));
		
		function fl_CustomMouseCursor_2() {
			this.movieClip_2.x = stage.mouseX;
			this.movieClip_2.y = stage.mouseY;
		}
		
		/* Показать объект
		Показывает указанный экземпляр символа.
		
		Инструкции:
		1. Используйте этот код для объектов, которые в настоящий момент скрыты.
		*/
		document.addEventListener("mouseover", fl_mouseover.bind(this));
		function fl_mouseover() {
			this.pus.visible = false;
			this.movieClip_1.visible = true;
			this.movieClip_2.visible = true;
			this.krug.play(1);
		}
		
		
		document.addEventListener("mouseout", fl_mouseout.bind(this));
		
		function fl_mouseout() {
			this.pus.visible = true;
			this.movieClip_1.visible = false;
			this.movieClip_2.visible = false;
			this.krug.play(5);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 7
	this.pus = new lib.Символ36();
	this.pus.setTransform(320,202.3);

	this.timeline.addTween(cjs.Tween.get(this.pus).wait(1));

	// Слой 3
	this.movieClip_1 = new lib.Символ12();
	this.movieClip_1.setTransform(320,248);

	this.timeline.addTween(cjs.Tween.get(this.movieClip_1).wait(1));

	// Слой 6
	this.movieClip_2 = new lib.Символ16();
	this.movieClip_2.setTransform(324.1,129.3);

	this.timeline.addTween(cjs.Tween.get(this.movieClip_2).wait(1));

	// Слой 2
	this.instance = new lib.Символ30();
	this.instance.setTransform(138,17.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 4
	this.instance_1 = new lib.Символ31();
	this.instance_1.setTransform(458.8,22);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 5
	this.instance_2 = new lib.Символ35();
	this.instance_2.setTransform(315,15);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 1
	this.krug = new lib.Символ39();
	this.krug.setTransform(349.8,158);

	this.timeline.addTween(cjs.Tween.get(this.krug).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-122.2,39.4,1512.3,531.8);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;