(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/back.jpg", id:"back"},
		{src:"images/for_03.png", id:"for_03"},
		{src:"images/for_09.png", id:"for_09"},
		{src:"images/for_14.png", id:"for_14"},
		{src:"images/w256h2561380453915MouseOptions256x25632.png", id:"w256h2561380453915MouseOptions256x25632"}
	]
};



// symbols:



(lib.back = function() {
	this.initialize(img.back);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,661,313);


(lib.for_03 = function() {
	this.initialize(img.for_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,141,128);


(lib.for_09 = function() {
	this.initialize(img.for_09);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,117,116);


(lib.for_14 = function() {
	this.initialize(img.for_14);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,418,275);


(lib.w256h2561380453915MouseOptions256x25632 = function() {
	this.initialize(img.w256h2561380453915MouseOptions256x25632);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,256);


(lib.Символ28 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhoDIIAAmPIAFgFIDMDMIjMDNg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.5,-20.5,21.1,41.2);


(lib.Символ26 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,0,0,0.498)").s().p("AgoAjIAAhFIBRAAIAABFg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.2,-3.5,8.4,7.1);


(lib.Символ25 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(1,1,1).p("Ai/giIF/AAIAABFIl/AAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-20.2,-4.5,40.5,9.1);


(lib.Символ21 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,0,0,0.498)").s().p("Ag3AVQgXgIAAgNQAAgMAXgIQAYgJAfAAQAhAAAWAJQAYAIAAAMQAAANgYAIQgWAJghAAQgfAAgYgJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.9,-3.1,15.9,6.2);


(lib.Символ20 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(2,1,1).p("AA4AAQAAAXgRAQQgQARgXAAQgWAAgQgRQgRgQAAgXQAAgWARgQQAQgRAWAAQAXAAAQARQARAQAAAWg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.6,-6.6,13.2,13.2);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.498)").s().p("ABDA4QgFgCgFgEQgDgEgDgGQgCgFAAgHIAAg3QAAgIACgFQADgGADgEIAKgGQAHgCAHAAQAOABAIAHQAJAJAAAOIAAA3QAAAOgJAIQgIAIgOAAQgHAAgHgCgABIglQgDACAAAFIAAA8QAAAFADADQADADAGAAQAEAAADgDQADgEABgFIAAg7QgBgEgDgEQgDgCgEAAQgGAAgDADgAgMA4QgFgCgFgEQgDgEgDgGQgCgFgBgHIAAg3QABgIACgFQADgGADgEIAKgGQAHgCAFAAQAOABAIAHQAJAJAAAOIAAA3QAAAOgJAIQgIAIgOAAQgFAAgHgCgAgHglQgDACAAAFIAAA8QAAAFADADQADADAEAAQAEAAADgDQADgEABgFIAAg7QgBgEgDgEQgDgCgEAAQgEAAgDADgAhVA4IAAhOIgaAAIAAgQIADAAQAGAAAGgBQAEgBAEgDIAFgHQADgDABgFIAOAAIAAByg");
	this.shape.setTransform(-2.2,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.498)").s().p("AA4AyQgJgHAAgQIAAgGIAVAAIAAAKIACAGQACADACAAIAFABIAFAAIAEgDIACgGIABgWQAAgIgDgCQgDgEgGAAQgEAAgDACIgEAEIgTAAIACg6IA3AAIAAARIglAAIgBAZQADgEAEgCQAEgBAFAAQAHAAAFACQAFACAEAEQADAFACAGQABAEAAAIIAAALQAAAUgHAIQgEAFgGACQgGACgIAAQgPAAgJgIgAAEA4IAAgXIgiAAIAAgVIAehGIAZAAIAABKIAKAAIAAARIgKAAIAAAXgAgPAQIATAAIAAgwgAhuA4IAAgGQAAgLAEgKQADgJAGgGQAFgHAGgFIAPgNIAEgEIABgGIABgEQAAgJgDgCQgDgEgGAAQgFAAgDAEQgDADAAAKIAAAHIgVAAIAAgHQAAgJADgGQADgHAEgEQAFgEAGgDQAFgCAGAAQAHAAAGACQAGADAEADQAEAEADAGQACAGAAAHQAAAJgEAJQgEAIgHAFIgRAQQgEAEgDAFQgCAEgBAFIAoAAIAAASg");
	this.shape_1.setTransform(-2,-0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.498)").s().p("AA4AyQgJgHAAgQIAAgGIAVAAIAAAKIACAGQAAABABABQAAAAABAAQAAABABAAQAAAAABAAIAFABIAFAAIAEgDIACgGIAAgWQAAgIgCgCQgEgEgGAAQgDAAgDACIgEAEIgTAAIACg6IA3AAIAAARIglAAIgBAZQADgEAEgCQAEgBAFAAQAHAAAFACQAFACAEAEQACAFACAGQACAEAAAIIAAALQAAAUgHAIQgEAFgGACQgGACgIAAQgPAAgJgIgAgWAyQgJgHAAgQIAAgGIAVAAIAAAKIACAGQAAABABABQAAAAABAAQAAABABAAQAAAAABAAIAEABIAEAAIAEgDIACgGIAAgWQAAgIgDgCQgCgEgFAAQgDAAgDACIgEAEIgTAAIACg6IA1AAIAAARIgkAAIAAAZQADgEAEgCQADgBAEAAQAHAAAEACQAGACADAEQADAFADAGQABAEAAAIIAAALQAAAUgHAIQgEAFgGACQgGACgIAAQgNAAgJgIgAhKA4IAAgXIgkAAIAAgVIAghGIAYAAIAABKIAKAAIAAARIgKAAIAAAXgAhfAQIAVAAIAAgwg");
	this.shape_2.setTransform(-2,-0.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,255,255,0.498)").s().p("AgXAyQgJgHAAgQIAAgGIAVAAIAAAKIACAGQACADACAAIAFABIADAAIAEgDIACgGIABgWQAAgIgDgCQgDgEgEAAQgEAAgDACIgEAEIgTAAIACg6IA1AAIAAARIgjAAIgBAZQADgEAEgCQAEgBADAAQAHAAAFACQAFACAEAEQADAFACAGQABAEAAAIIAAALQAAAUgHAIQgEAFgGACQgGACgHAAQgOAAgJgIgAhaA5QgFgCgFgDQgEgDgCgFQgDgGAAgHIAAg5QAAgGACgHQACgFAEgFQAEgEAFgCQAGgCAHgBQAIAAAFACQAGACAEADQAEAEADAFQACAFAAAGIgVAAQAAgEgCgDQgDgCgFgBQgFABgDADQgCAEAAAIIAAANQACgDAGgCQAFgCAEgBQALAAAGAHQAEADABAFQACAFAAAEIAAAbQAAAHgDAGQgCAFgEADQgEADgGACQgGABgHAAQgGAAgFgBgAhVAAQgDABAAAHIAAAWQAAAMAJgBQAFAAADgDQADgCAAgGIAAgXQAAgGgDgBQgDgCgEAAQgEAAgDACgAA8A4IAEgbIAHgbIAIgWIAKgUIgsAAIAAgSIBBAAIAAARIgJATIgIAWIgHAaQgCAOgBAQg");
	this.shape_3.setTransform(-1.9,-0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(255,255,255,0.498)").s().p("AgLA5QgGgCgEgDQgEgEgCgFQgCgFAAgGIAUAAQAAAEADADQACACAEAAQAFAAACgDQADgDAAgJIAAgNQgDADgFADQgDACgFAAQgFAAgEgCQgEgCgEgDQgGgHAAgKIAAgbQAAgHACgFQACgFAFgEQAEgEAGgBQAFgBAFgBQAGABAFABQAGABAEAEQAEAEADAFQACAFAAAHIAAA5QAAAHgCAFQgCAHgEADQgDAEgGADQgGACgHAAQgFAAgGgBgAgGgmQgDAEAAAFIAAAXQAAAGADABQAEACACAAQAEAAADgCQADgBAAgGIAAgXQAAgGgDgDQgCgDgFAAQgDAAgDADgAhaA5QgGgCgEgDQgEgEgCgFQgCgFAAgGIAUAAQAAAEADADQACACAFAAQAGAAACgDQADgDAAgJIAAgNQgDADgFADQgFACgFAAQgFAAgEgCQgEgCgEgDQgGgHAAgKIAAgbQAAgHACgFQACgFAFgEQAEgEAGgBQAFgBAHgBQAGABAFABQAGABAEAEQAEAEADAFQACAFAAAHIAAA5QAAAHgCAFQgCAHgEADQgDAEgGADQgGACgHAAQgHAAgGgBgAhVgmQgDAEAAAFIAAAXQAAAGADABQAEACADAAQAFAAADgCQADgBAAgGIAAgXQAAgGgDgDQgCgDgFAAQgFAAgDADgAA7A4IAFgbIAGgbIAJgWIAKgUIgtAAIAAgSIBBAAIAAARIgIATIgJAWIgGAaQgDAOgBAQg");
	this.shape_4.setTransform(-2,-0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-13.4,-6.5,22.5,11.8);


(lib.Символ16 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(2,1,1).p("ADlAZIAAg2AGjAZIAAg2AAdAZIAAg2AijAZIAAg2AlnAZIAAg2Ao5AeIRzAA");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-58,-4.1,116.2,8.1);


(lib.Символ15 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(51,51,255,0.498)").s().p("Ak8AAIE8k8IE9E8Ik9E9g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-31.8,-31.8,63.6,63.6);


(lib.Символ11 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMTA5QgHgBgFgFQgFgFgDgHQgDgIAAgLIAAgRIgUAAIAAA2IgWAAIAAhxIAWAAIAAAsIAUAAIAAgIQAAgLADgHQADgIAFgFQAFgDAHgCQAHgDAIAAQAJAAAHADQAGACAFADQAFAFADAIQADALAAAHIAAAoQgBAOgCAFQgDAHgFAFQgFAFgGABQgHADgJAAQgIAAgHgDgAMbgoQgDACgCACQgEAFAAAJIAAAtQAAAIAEAGQAEAFAIAAQAHAAAFgFQAEgGAAgIIAAgtQAAgJgEgFQgCgCgDgCQgDgBgEAAQgEAAgDABgAl4A5QgHgBgFgFQgFgFgDgHQgCgFgBgNIAAgoQAAgLADgHQADgIAFgFQAFgEAHgCQAHgDAIAAQAIAAAHADQAHABAFAFQAFAFADAIQACAHAAALIAAAoQAAALgCAHQgDAIgFAFQgFAEgHACQgHACgIAAQgIAAgHgDgAl0gkIgDAGIgBAIIAAAuIABAIIADAFQADAFAIAAQAHAAAEgFIADgFIABgIIAAguIgBgHIgDgHQgCgCgDgCQgCgBgEAAQgIAAgDAFgAsxA7IgHgCIAAgQIAGABQAEAAACgCIAEgHIgfhZIAYAAIASA7IASg7IAYAAIggBbIgEALIgGAIQgDADgDACIgHABgAF4A7IgGgCIAAgPIAHABQABAAAAgBQABAAAAAAQABAAAAAAQABgBAAAAQACgBABgFIACgOIABhNIBCAAIAABxIgWAAIAAhgIgXAAIAAAqQAAAPgBAKQgCALgCAHQgDAHgFADQgFADgHAAgAEaA7IgGgCIAAgPIAHABQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQACgBABgFIABgOIABhNIBDAAIAABxIgWAAIAAhgIgXAAIAAAqQAAAPgCAKQgBALgDAHQgDAHgFADQgEADgHAAgAivA6IAAhxIAWAAIAAAsIATAAQAGAAAGADQAFADAEAFQAEADACAGQACAGAAAGQAAAJgCAGQgCAHgDAFQgEAEgFADQgFADgHAAgAiZAqIANAAQAGAAADgFQAEgEAAgJQAAgJgEgFQgBgDgDgBQgCgBgDAAIgNAAgAKuA5IAAhBQABgJACgIIgBAAIggBSIgXAAIAAhxIAUAAIAAA/IgCATIAghSIAXAAIAABxgAIiA5IAAhxIApAAQAHAAAGACQAFADAEAFQAEAEACAGQADAGAAAHQAAAHgDAHQgCAGgEADQgEAEgFADQgGADgHAAIgTAAIAAAvgAI4gFIALAAQAEAAADgCQADgBACgBQAEgFAAgJIgBgGQgBgEgCgCIgFgDIgHgCIgLAAgAHWA5IAAhxIA+AAIAAARIgoAAIAAAbIAlAAIAAAPIglAAIAAAkIAoAAIAAASgAD1A5IAAhBQABgJACgIIgBAAIggBSIgXAAIAAhxIAUAAIAAA/IgCATIAghSIAXAAIAABxgACEA5IAAhgIgbAAIAAgRIBMAAIAAARIgbAAIAABggAAXA5IAAhxIApAAQAHAAAGACQAFADAEAFQAEAEACAGQADAGAAAHQAAAHgDAHQgCAGgEADQgEAEgFADQgGADgHAAIgTAAIAAAvgAAtgFIALAAQAEAAADgCQADgBACgBQAEgFAAgJIgBgGQgBgEgCgCIgFgDIgHgCIgLAAgAgIA5IgEgXIgcAAIgFAXIgXAAIAdhxIAdAAIAYBxgAgPAQIgKg6IgMA6IAWAAgAjVA5IgTguIgJAMIAAAiIgWAAIAAgiIgIgMIgUAuIgYAAIAehAIgdgxIAZAAIAaAxIAAgxIAWAAIAAAxIAbgxIAYAAIgdAxIAeBAgAnKA5IAAhgIgbAAIAAgRIBMAAIAAARIgbAAIAABggAoHA5IAAgyIgSABQgHAAgGgCQgGgCgEgEQgEgDgCgGQgCgGAAgHIAAgiIAWAAIAAAfQAAAIAEAFQAEAEAIAAIALgBIAAgvIAWAAIAABxgApdA5IABhBQAAgJACgIIAAAAIggBSIgYAAIAAhxIAVAAIgBA/IgCATIAghSIAYAAIAABxgAq3A5IAAg2IgdAAIAAA2IgWAAIAAhxIAWAAIAAAsIAdAAIAAgsIAWAAIAABxg");
	this.shape.setTransform(-3.9,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-88,-6,168.2,12);


(lib.Символ9 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,0,0,0.4)").s().p("Eg4eAbEMAAAg2HMBw9AAAMAAAA2Hg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-361.5,-173.2,723.1,346.5);


(lib.Символ3 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.for_03();
	this.instance.setTransform(-70.5,-64);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-70.5,-64,141,128);


(lib.Tween22 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.w256h2561380453915MouseOptions256x25632();
	this.instance.setTransform(-30,-30,0.234,0.234);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-30,-30,60,60);


(lib.Symbol36 = function() {
	this.initialize();

	// Layer 1
	this.text = new cjs.Text("НАВЕДИ МЫШЬ", "bold 22px 'Arial Black'", "#FFFFFF");
	this.text.textAlign = "center";
	this.text.lineHeight = 24;
	this.text.setTransform(65.5,0,0.66,0.66);
	this.text.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,5);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.9,-3,142,33);


(lib.shape109 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(3,1,1).p("AETAAQAABxhRBRQhRBRhxAAQhwAAhRhRQhRhRAAhxQAAhwBRhRQBRhRBwAAQBxAABRBRQBRBRAABwg");
	this.shape.setTransform(27.5,27.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,58,58);


(lib.shape260 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AAwDbIgBgQQAAgVASgBQASgBAAAUIgCARIgEACIgMACgAEsAkIgHgEIgCgIIAFgHQAEgEAEgBIANALIgNAPgACLi0IgEgFIgCgIIAJgJQAIgEALAEQAAABAAAAQABAAAAAAQAAAAAAAAQABABAAAAIACAHIgBAKIgBAAIgDACIgLACgAk0jEIgIgFIAAABIAAgIQAAgIAEgCIAIgCIANALQgCAHgLAIg");
	this.shape.setTransform(-2.5,-34.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-34.3,-56.2,63.6,44.4);


(lib.shape259 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AAsDPIgFgIQABgbASAFQASAEABARIgCAOQgBACgKAAQgNAAgHgHgAEmANIAAgGIACgBIAUAAIABAHIgBAKIgJABQgNgJAAgCgACIi9IAAAAIgBgCIgBgHQAAgEAKgFIAVgCIACAFQAAAHgIAFIgQAEgAk7jKIgBgFIAFgHIAUABIABABIABAGIgBAIIgBACIgHABQgJABgIgIg");
	this.shape.setTransform(-2.2,-35);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-34,-56.5,63.5,43);


(lib.shape258 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AAQGyQgEgDAAgIQAAgNAXAFIACABIABAHQAAANgCgGQgDAFgIACgACHELIgBgNQAAgVASgVQASgVAAAtIAAAUQgDAOgPAAgAGDBCQgEgEAAgIQAAgJAEgEIAIgFQAMAMACAQQgHAFgHADgAjfh8IgBgGIAAgbIAYABQABADAAALQAAAKgBAIIgMAEQgIgBgDgDgADciNQAAgFAJgFQAJgFAAgFIAIACQAFACAAAIQAAAHgIAHIgKAKQgNgNAAgDgAFqlKQABgHAFgEIASAAIABACIABAJIgBALQgHAFgEABQgOgNAAgEgAmYmkIANgQQAIADAEAIIgDAHIgJAIQgKgDgDgHg");
	this.shape.setTransform(-11.7,-41.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-52.6,-85.2,81.9,87.5);


(lib.shape257 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AAMG6IgCgHIADgGIAGgBIAIAHIgBAGIgHADgACGEAIgCgQQABgKASgRQASgRABArQgBASgUAAgAGAA0IgBgLQAAgMAIADQAHACAJAPQgDAEgJAAgAjmh4IAAgJQABgOARAAQAQgBAAAPQAAARgPAAQgQAAgDgIgADciMQADgDAFgBIARAAIABALIAAAMIgIACQgPgKgDgLgAFpk8IgBgBIgDgCIgBgGQABgFAJgGIATgBIABABIABAFQAAAGgHAFQgHAEgEAAgAmOmgIgFgDIgDgJIADgLQAFgFARADIABAKQABAEgCAEQgDAHgMAAIgCAAg");
	this.shape.setTransform(-11.5,-43.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-52.3,-88,81.5,88.8);


(lib.shape256 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ag7HdIgEgFIgBgGQAAgHAIgDIAUABIABABIABAIQAAAMgBgDIgDACIgLACgAGbEeQAAgJAFgEIASABIABACIABAJIgBAMIgLAFQgNgNAAgDgAA+EBQgCgFAAgQQAAgoAXABQAXABAAAtIgDAfIgNACQgWgFgGgOgAE1AmIABgTQALAAANAKQALAJAAAGQAAAIgHAHQgFAGgGADQgSgRAAgNgAkrhZQAAgWASgFQASgFAAAYQAAANgBAEQgEAKgSAHQgNgNAAgNgACThsIgBgMQAAgKAGgJQAJgNASAAIADATIgBARQgEAKgSAHQgJgDgDgGgAAtifIAFgKQAEgFAEgBIAMALIgDAHIgJAIQgJgDgEgHgAhCjPIgCgFIgBABIgBgIQAAgIAFgCIAIgCIANALIgBALIgCACIgKACgAEdk2QgGgMAAgIQAAgbASADQARACAAAUQAAANgKAUIgIACQgFgCgGgLgAnamjIgDgIIAHgFQAGgDAAgJQANANAAAQIgNAGgAHHnIIgCgFIgBgPIAKgCIANAEQADgGAAAMIgBAJIgBAAIgCACIgKACg");
	this.shape.setTransform(-4.8,-47.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-52.6,-95.2,95.7,96);


(lib.shape255 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AgeHTIgBgIQAGgIAJgBQAJAAAGAIIgFAIQgCADgJAAgAG1ERQAAgIAEgCIAKgCIALACQACgDAAAJQAAAIgKANIgFABQgMgLAAgHgABXD3QgDgFACgGQAAgyAYgFQAIgCAHAHQAIAHAAAMQAAA1gWAAQgUAAgEgLgAFOAgQgBgIABgGQAAgbAUADQAUADAAAXIgBATQgDAIgQAAQgRAAgDgPgAkXhhIgDgMQAAgVAUgNQAUgMAAAqIAAARQgCALgNAAQgPAAgHgMgACnh8QgCgHABgHQAAgSADgFQAGgPAXAGIACASIgEAWQgFATgKAAQgMAAgCgNgABEiZIgBgOQAAgPAHAAQAHAAATAOIgGAJQgGAHgJAAgAgtjjIgDgBIgBgHQAAgFAIgFIASgCQACABAAAJQAAAGgCACQgCAEgKAAgAEzlQIgDgBIgBgNQAAgMALgFQANgGASAJIACAKQAAAGgIAGQgJAHgNAAgAnOm/IgBgKQAAgJACgBIAegBQACgBAAAJQAAAKgFAFQgEAGgGAAQgOAAgEgIg");
	this.shape.setTransform(-7.2,-47.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-53.6,-94.6,92.9,93.9);


(lib.shape254 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AqPIGIgBgNQAAgbAbgBQAaAAAAAbQAAALgJAIQgIAGgKAAQgTAAgGgLgAJeHcIgCgNQAAgcAbABQAaAAAAAaQAAALgJAHQgIAHgKAAQgSAAgGgLgAiwG1QAAgZAUAEQAUAEAAASQAAAKgCADQgFAKgVAAQgLgKgBgOgAEzECIgDgJQAAgWANAAQAMAAAAAVIgBAUIgLAFQgHgHgDgIgAgxDmIgBgvQAAg6AXgLQAXgLAAA+QACAagCAOQgEAbgYAAgAAmBOIgHgFIgCgIIAFgGIAIgGIANALIgNAPgADNADQgDgJAAgJQAAgXACgPQAagDAGANQACAEAAAXIgBARQgFAOgRAIQgGgGgEgOgAmahkIgBgeIAGgyQAWgIAGAUQACAGAAAXQACATgCAIQgDAPgRAAgAATifQgBgNABgOQAAgzAaADQAZADAAAkQAAASgFARQgIAcgSAAQgRAAgDgbgAhLi3IACgNQALgCAZACIACAPQAAASgRAAQgXAAAAgUgAi5kJIgCgDQAAgIAJgCIAOABIACABIABAIIgBAIIAAgCQgEAGgIABgACil/QgCgKACgJQAAgiAUABQAUACAAAjIgBAhIgDACIgLACQgVAAgEgWgAFantIgBgNQAAgOAMgFQAKAEADAHIABAJIgCAMIgDAGQgDACgGACQgJgEgCgGgApInpIgIgCIgCgUQAAgQAKgBQANgCAXAVIgIAOQgGAGgMAAg");
	this.shape.setTransform(6.4,-46.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-59.4,-99.8,131.6,106);


(lib.shape253 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AqSH6QgCgGACgIQAAgcAbgEQAbgCAAAgIgBAUQgEAJgXAAQgWAAgEgNgAJkHoIgCgJQAAgeAZADQAZADAAAWQAAAMgEAFQgIAGgdAEQgFgFgCgLgAi3HRIgEgKQAAgKAJgLQANgPAYAGIABABIABAFQAAANgHAOQgHAPgKAAQgOAAgGgIgAEaEUQgBgFABgEQAAgMAagGQAZgHAAARQAAAKgJAHQgJAHgNgBQgRAAgDgGgAg8DWQgCgNACgMQAAhAAdgGQAcgHAAA9QAABCgZgBQgaAAgGgYgAAdBkIgBgFIAAgRIAdgBIABALIAAALIgPADgADBAAQgEgNAAgNQAAgvAYAQQAXARAAAwIgBAOQgCAHgMgBQgUAAgIgcgAmdhqQgCgEACgFQAAgfAXgNQAXgMAAAmQACAOgCAIQgDAOgWAAQgSABgDgKgAASiWIAAgTQAAgoAYgCQAXgCAAAZQAAAOgKAVQgLAWgOAAQgKABgCgUgAhOiOIgBgPQAAgQASgFQASgDAAAWIgBAOQgDAFgPAAgAi5jyIgCgNIADgKIALgCIAMABQACABAAAJQAAAGgEAEQgEAFgHAAgACbl4QgCgFACgHQAAgeAWgCQAWgCAAAdIgBARQgCAMgNAAQgXAAgFgMgAFWnYIgCgBIAAgJIAEgIQAFgFAFgDIAGACIADAHQAAAIgEAFQgEAFgFAAgApKnoQgIgIAAgHQAAgLADgDIANgBQAQAAAGAIIACAKQAAAJgIADg");
	this.shape.setTransform(6.6,-50.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-59.4,-102.4,132.1,103.9);


(lib.shape252 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AJdH9IgEgQQAAgbAcAGQAbAFAFAYIgDATIgHAEQgGAFgLAAQgVAAgIgUgAqTIAQgCgJACgKQAAgoAbAAQAaABAAAmQAAAlgbAAQgWAAgEgRgAi1HwIgCgbQAAgdAXABQAXABAAAdQAAAbgZAAgAEzFOIgCgBQgCgIAAgXQAAgeAUgIQAVgIAAAhQAAAJgKASQgJATgHAAgAg3EFIgBgzQAAh0AfAdQALALAJAbQAIAbAAAUIgBAhQgFAXgcAAgAAgCHIgCgBIgBgCIgBgLQAAgUASgGQASgHAAAXQAAAOgHAGQgGAFgIAAgAC/AkIAAgXQAAhEAagDQAZgEAAA7QAAASgGAkIgCADIgJACQgdAAgFgUgAmWgWIgBg7QAAg/AXAEQAXADAAAnIgFAhIgFAhIAAAJIgBAAIgFACIgMACgAhFh0IgHgUQAAgVAUAAQAUAAAAAaIgBARQgEAJgRAKQgFgGgGgPgAASiEQgDgNADgPIADgZIAEgeQAhgHAIAXIADAhQAAA9gXAAQgYAAgEgbgAi1jXIgBgGIgBgNQAAgXAPAGQAQAFAAASIgBAMIgDACIgLACgACbleQgCgKACgMQAAgxAagJQAZgKAAA9IABAeQgEAUgUAAQgXAAgFgVgAFWmvIgDgJQAAgOAKgYIASgiIAKAQIADAJQAAAIgJAbQgLAfgJAFQgGgGgDgJgApSnQIgBgfIABgeIATgDQATAAAKANQAHAKAAAJQAAAOgHAJQgKALgVAAg");
	this.shape.setTransform(6,-55.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60.2,-108.1,132.4,105.9);


(lib.shape251 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AJpIDQgCgEAAgFQAAgXAVgBQAWgCAAAYIgDAOQgEAGgPAAQgOAAgFgJgAi2HzQgCgLACgMIAAgUQADgJAOAAQATAAAIAYQADAMAAAPQAAAWgXAAQgUAAgEgVgAqPHrIgCgRQAAgeAbgJQAbgIAAAhQAAAPgGAMQgJAUgUAAQgNAAgEgQgAElFXQgBgFABgGQAAgkAhgRQAggRAAAlQAAANgLARQgOAYgXAAQgOAAgDgKgAgpEYQgJgJgEgYQgEgTAAgVQAAhzAhAdQAMALALAcQAIAdAAAZIgCAeIgVAkgAAnB9QAAgNADgCIAdgDIACAQIgCAMQgFAKgSABQgJgFAAgQgADEAxQgFgLgBgLQAAhGAcgJQAdgIAABEIgBAjQgFAagVAAQgPAAgJgUgAmZg6IgHgyQAAgjAeASQAeASAAAjQAABCgaAAQgRAAgKg0gAhFhuIgDgOIACgOQAHgKAaAFQAIAJAAAHQAAAKgDAIQgFANgMAAQgOAAgGgOgAATiIQgCgPACgQQAAgzAZAGQAZAGAAAxQACARgCALQgDAXgRAAQgYAAgGgegAi2jNIAAgJQAAgOAGgHQAIgMASAFQACAIAAANIgBAWIgFABIgKABQgPAAgDgIgACglxQgEgVAAgSQAAgyAbASQAbASAAAvIAAAaQgEAWgUAAQgTAAgHgqgAFOmgIgBgPQAAgtAVgJQAUgJAAAtQAAAMgFAKQgHANgOAAgApRnVQgCgHACgIIACgXQAKgVAhAHQALAFADAJIABAOQAAAJgJAOQgLAQgOAAQgWAAgEgPg");
	this.shape.setTransform(5.5,-58.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60.3,-110.6,131.7,104.9);


(lib.shape250 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AJgIEIAAgOQAAgoAeAHQAeAIAAAgQAAAOgNAHQgJAFgJAAQgYAAgFgTgAi7HtIgFgpQAAgQAQgKQAQgKAJAcIAGAjIAFAeIgBAPQgDAKgRAAQgRAAgJgpgAqZHdIgBgEIgBgRQAAgWAPgFQARgFAWAgIgEAVIgIADIgPAFgAEmF0QgCgIACgMQAAgdANgaQASgkAhAQIABADIABAJQgaBigMAAQgXAAgFgPgAhAD/QgCgWACgZQAAhlAhAAQANAAAJAYQAJAaAAAqQACAcgCAZQgEAwgeAAQgZAAgFgtgAAeCPQgCgHACgJQAAgkAXgJQAWgJAAAiIgDAWIgEAYIgEADIgMACQgTAAgDgPgAC7A/QgCgJACgLQAAiCAdAUQAKAHAJAcQAJAcAAAZQAAA9gfAAQgWAAgEgTgAmagvQgFgbAAgdIACgaIAEgiQAcAKAPAnQAMAgAAAmIAAAeQgEATgTAAQgYAAgJg0gAhJhdIgBgkQAAgsAWAGQAXAGAAAoIgCAXQgDAIgSAAgAAOiOQgCgSACgSQAAhHAcAAQAcAAAABOIABAkQgEAegUAAQgbAAgGglgAjAjdQAAgYAXAFQAXAEAAAXQAAAWgcAAQgKAAgIgegACflUQgCgGAAgXQAAhCAeghQANgOAIAJQAKALAAAmIgBAvIgUBCIgHADQgZgQgGgQgAFLmOIgBgXQAAgjACgIQAEgVAWgRQAKAGADASIAAAYIgBAmQgFARgWAZQgKgFgCgTgApRnEQgEgKAEgMQAAglAcgTQAcgTAABCIgDAWQgBAPACAMIgCACIgJACQgkAAgHgWg");
	this.shape.setTransform(5.3,-60.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-61.5,-114.3,133.7,107.1);


(lib.shape249 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AJcH7IgBgMQAAgjAggJQAfgJAAAfQAAANgEAMQgIATgTABQgZgBgGgKgAi8ICQgPgPgRhHQAAgYAOgPQATgVAcAnQAEAJADAhIADAlIgBAOQgCAJgGAFgAqZHPIAAgWQAAgbADgJQAKgcAkAEQAMAJAAAYQAAATgHAUQgJAcgQAAQgYgBgFgRgAqJGwIABAIIAAgDIABgQgAEdGCQgDgNAAgOQAAgpApgnQAQgPALADQANAFAAAfQAAARgSApQgWAygWgBQgMABgEgZgAhTDvQgFgmABgkQAAgdAWgbQAagfAZAyQACAFADAoIACAuIAAA2QgFArgbABQghAAgLhOgAAlCpQgJgKAAgeQAAg0AWAJQAWAIAAA1IgBAMQgBAGgHAEgACzBlIgFg1IgCglQAAgaAZgiQAZghAAAqQABAmAGAUQAGAUAAAYQAAApgmAAgADFgdIADAAIAAgCgAmegyQgHgkgDgjQAAg6ApA0QAoA1AAAhQAAAUgGARQgKAXgVAAQgUAAgOhFgAAUhWQgKgFgHgUQgDgOAAgJQAAgvAJggQAJgdAOgCQAhgFAACJIgBAOQgEAGgRAGgAhThvIgEgTQAAgjAdAFQAcAHAAAlQAAALgGAHQgIAJgNAAQgTAAgHgWgAjIi6IAAgLQAAgNAGgJQAJgPAVAJQABAGAAAMQAAALgEAJQgFALgKAAQgPAAgDgKgACRljQgCgaACgaQAAgwALgYQAKgVAOAFQAjANAABdQAAAYgFAVQgJApgYAAQgaAAgGg0gAE8maQgEgRAAgRQAAgrAYADQAXAEAAAuIAAAfQgDAagQAAQgRAAgHghgApSm+IgEgoQAAgWAKgIIAVAAQAeATAAAzIAAAWQgEARgXAAQgWAAgIgng");
	this.shape.setTransform(5.9,-64.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60.7,-116.7,133.4,103.6);


(lib.shape248 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ai5JQQgCgZgNg/QgMg7AAgcQAAgsAcgvQAbgvABBlIAFCmIAAAgQgDARgQAAgAJgHHQgCgOACgQQgBg/AbAAQAaAAABA+IAAAjQgEAXgXAAQgXAAgDgbgAqSHSIgCg1QAAgwA0gqQAVgRAPABQAPACAAAbQABAFgVAXQgWAcgHAQIAAAjQgBAZgaAHgAEYGyIgCgXQAAgoA0hdQAzheAABWQAAAhgiBDQgfA7gYAdQgKgGgCgSgAhKE+QAAghgJg9QgHg7AAgdQAAggAZgVQAdgYARAzQALASADAeIABAxIgBBAQgHAxglAAgAAiCxIgDgCIgEghIgDgdQAAgtAcABQAcAAAAAqQAAAOgFAPIgLAhQgFAFgMAAgACsA/QgCgXACgXQAAhpAdAIQAcAHAABrQAAAjgCAJQgHAhgaAAQgSAAgEgwgAmXg1QgIgmgBgjQAAh2ApBfQAOAhAOAvQAMArAAAKIAAAVQgDAPgTAAQgiAAgQhJgAAEh+QgDgXADgVQAAgwAJghQAJgeAMgCQAfgGAACDQADAXgDATQgFAkgcAAQgXAAgFgugAhVhtQgDgPADgQQAAgzAcgDQAbgCAAAuIgDAcIgGAkIgDADQgCADgIAAQgbAAgGgdgAjPjDQgCgGACgIQAAgaAhgEQAhgEABAbQgBAighAAQgcAAgFgNgACNmcQgHhAgDg8QAAgwAMgIQAMgIARAZQAoA9AABhIAAAPIAAAFQgEAyAAAbIgFADIgJADQgDAfgRAAQgTAAgOiBgAE1l8QgDgLADgKQAAgoAfhRQAfhRAABmIgKBJQgNBEgLAAQgXAAgFgUgApAmLQgXgMABgoQgBgoAMgXQALgVAPABQAQAAALAWQAMAZgBArIgBAXQgCAMgJAKg");
	this.shape.setTransform(5.4,-66.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60.8,-126.4,132.3,119.1);


(lib.shape247 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AjPHkIgNiJQAAhUAfAHQAdAGAABHQAAAOgEAbQgGAbAAANIAIAyQAJAzAAAbIAAAnQgEAcgUAAQgOAAgQiLgAD9HbIgBgUQAAg/A+hxQAZguARgMQAUgOAAAoQAAAZgiBdQgoBvgjAAgAqMGQIgEgQQAAgvA2gVQAWgIAPAEQARAEAAARQAAAKgZAhQgcAngWAAQgVAAgIgPgAJYFiIgKgaQAAgHAIgTIALgUIAgAAQALACADATIAAAbQACASgCALQgDAUgTAAQgUAAgNgZgAhnCuQgKhFgDhEQAAg4AvAzQAxA1gDAXIAKBJQAFAnAAAeQABA+gpAAQgkAAgTiKgAHrDkQAAgUAYAIIACACIABAKIAAALIgBABIgNAGQgNgOAAgEgAA1CUIgbAAQgTgOgFgRQgBgHAAgWQAAgVADgFQAJgRAhADQASAYADAMIABAeIgBAWQgDAMgJAAIgCAAgAA0CCIAAAAIAAAAgACmBhIgLhIQgHgoABgcQAAgoAKgQQAIgOANALQAgAZAABVQACAagCAWQgFAqgaAAgAmlg7QgLgtgCguQAAhEARgBQAPgBAXArQAUAlASAyQARAyAAASQAAARgFALQgHAWgSAAQgsAAgXhXgAABiYQgBgkAAgjQAAgkAbgfQAegfABAyQAAAWADAtIADAtQAAARgKAbQgMAjgSAAQgRAAgGhIgAhHhoQgXgVgMhgQAAgVAWgIQAYgJAQAnIALAmIADAkQAAAjgMAHgAjVjLQgDgLAAgLQAAgiAfABQAgABAAApQAAAfgmAAQgQAAgGgSgABymxQgMhFgHhHQAAgvARgCQAOgCAVAiQA0BRAABdQgGB2gcAAQgbAAgYiHgAEgmRQgCgNACgOQABgqAkhLQAlhLAABnQgRCOgiAAQgTAAgEgagApkm/QgFgcADgaQAAgfAPgNQAOgNAVAIQAyASAABOQAAAPgMAVQgQAbgXAAQgmAAgJg4g");
	this.shape.setTransform(6,-68.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-59.7,-130.5,131.4,124.7);


(lib.shape246 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AjZH4IgPi+IAEgeIAGgpQAPgKANAPIAXAhIAAD8QAFAaAAA0QAAA0gCAaIgEACIgNACQgOAAgSi9gADvI6IgFgCIgBgyQAAgaAWhFQAVhFAag2QAdg+ASgGQAWgGAABQQAAAOgzB7Qg2B/gNABgAp0GZIABgSQAAgiAzgIQAzgHAAAjQAAAGgbAUQgeAWgTAAQgXAAgEgQgAI5E+IgPgeQAAgUAMgHIAaACQAlATAAArQAAANgJAIQgIAHgKAAQgPAAgSgjgAhwEVQgGgmgCg9IgNhgIgIhPQAAg5AWASQASAPAdA+QAZA6AVBCQAWBCAAAXQAAAXgOAfQgRAngZAAQgpAAgLhGgAHtD/IgBgIIAEgHQAFgFAEAAIAOALIgDAIQgEAFgHADgAgECPQAAgZAFgUQALgfAZAAQAVAAAOAcQAJAVAAAOQAAAOgLARQgPAXgaAAQghAAAAgpgACSA7IgKhbQAAgyALgXQAKgUAPAIQAjASAABeQgPCZgUAAQgNAAgNhZgAmNAWIgZg6QgQgVgDgfIAAgyQAAjOB6FYQAABDgfAAQgcAAgTgtgAgEhaQgCgaACgbIAAgvQACgpAEgYQAQg2AWAOQAUAMAAAkQAAAmgKBKQgMBhgRAAQgVAAgEg0gAhuiXQgIgigCgjQAAgoAMgHQALgFARAVQAoAyAABIIgCAcQgGARgWAAQgZAAgPhDgAjiiKIgBgpQAAgnAjgOQAkgOAAAtQAAAPgRAZQgRAagPAAgABWmzQgOhYgHhYQAAhRAQAAQANAAARAoIAFAGQAoAxAABZIAAALQAQBPAABQQACAcgCASQgEAjgWAAQghAAgbiygAEblOIgDgCIgBgqQAAgoAmhpQAmhpAABvQAAA0gIAtQgOBXglAAgApZlYQgOgSgEghIgBg4QAAhDAPgTQANgRAVATQATAQAPAlQAPAkAAAeQAAAcgCAIQgFAagVAKg");
	this.shape.setTransform(6.4,-73.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-56.5,-142.4,125.9,138.7);


(lib.shape245 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AjCLDQgFgzgViVIgTiOQAAhGANgxQALgsARgKQAQgKALAeQANAiAABHIgICWIAIC8QACASgCANQgDAXgSAAgADmJBQgCgOACgPQAAgVAShHQAShFAIgOIASgrIATgtQATgmASgLQATgNAAAhQgPBbgWBWQgtCsglAAQgPAAgDgcgAFbD5IgDAHIAAACIAEgFIgBgFgApNG2QgOgJgDgIIgBgPQAAgNAGgEQASgOBEAGIATARQADAFAAALQAAAMgEADQgEAEgUAFgAiBCkQgQhegHhfQAAghAbAHQAbAJANAwIAMAvQAIAfAIARQASAjARA5QAUBAAAAgQAAA+gxAAQguAAggi7gAI1E2IgOghQAAggAhAYQAiAXAAAdQAAAXgWAAQgNAAgSgigAHiDzQgBgEAAgJQAAgYAWgJQAWgJAAAgQAAALgFALQgGALgJAAQgSAAgFgKgAACCEQgCgeAAgfQAAggANgIQAMgIASANQArAgAABCQAAA7gvAAQgcAAgJg9gACLBTQgGgnAAgmQAAgwAOg6QAShLAXAyQAJARABAbQAAAjADALQAJAgAAA2QAAAUgHAcIgNA5IgCADIgHACQgdAAgNhOgAmdgwQgNhAgHg+QAAg+AcAFQAdAEAYBWIAXBRQANAxAAAdQAAA7gjAAQgjAAgbh9gAgGhXQgDgcAAgdQAAiIAmglQARgPALAYQAMAaAABAQAAAzgGAtQgNBbgfAAQgTAAgGg4gAh0iiIgahXQAAiVBxEiQAAAMgIALQgKANgPAAQgYAAgehagAjlilQgHgXgDgYQAAgOAGgJQALgRAcAGQAQAIAPAeQAPAcAAAQQAAAugwAAQgTAAgOgvgABJnPQgRhegNheQAAglASgQQAWgTAdBHIAmBpQAEAPALBPQALBTAAAeQAAAPgKAWQgPAbgUAAQgXAAgji7gApQk8QgTgQgEgnIgCg+QAAg6ADgRQAKg3AmATQAWAyAZAhQAJAMAAAqQAAAjgGAKQgGAIguAmgAESl1QgDgTADgUQAAgZALg2QAQhIAWAAQAUAAAIA1IADA3QAAAPgRAxQgTA3gNAAQgaAAgFglg");
	this.shape.setTransform(5.8,-76.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-56,-147,123.7,141.9);


(lib.shape244 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AjBLhIgFgjQgDgUgJgPIAAjVIgYhbIgBhCQAAg5ANgqQAMgmASgMQASgLAMAXQANAZAAA6QAAAtgBAJIgOBLIAAETQAGAigCA2IgFACIgMACgADeKQQgCgKAAgJQAAgxAOg8IAgh0QAbhcAshGQAuhKAABFQhKFdhMBUQgHgHgEgPgAo9HTQgHgFAAgPQAAgiA7AEQA6AFAAAdQAAASgOAFIgsADQgoAAgMgKgAiBC6Igpi6IADgZIAEgfQBCAJASA2QAFARAEAgIAIAtQACAIAmBNQAhBIAAAaIgBAiQgFAdgUAAQgRAAgDgFIgHgMQACAIgFAPQgHATgSAAQgOAAgti6gAIuFHIgbgZQAAgNANgJQAMgIAQABQApABAAArQAAARgDAIQgGAOgSAAgAHkDPQgCgEAAgVQAAghAcgHQAbgIAAAoQAAAzgTAAQgcAAgGgSgAgCCPQgHgngDgoIADgaQAJgWAiALQAwApAIAQQADAHAAApQAAAegKAXQgRAjglAAQgTAAgMhNgAAgCzIACAAIgCgEgACACDQgDgeADgeQAAhZANhFQAMg/AQgQQARgQALAuQANA0AABwIAABYQgHBKggAAQgkAAgHg7gAmNgSIgghxQAAgQARg3QASg8AOgPQASAvAXBTQAbBmAAAuIAAAzQgFAogXAAQgWAAgjhugAAPgSIgIgCIgJiBQAAhaAMgzIABgJQAIhKAYAXIADACQAKgDAJAQQAMAZAAA+QAAA6gGA+IgJA4IAAAgIgBAIIgMAFIgCgCQgHAMgJAAgAhVg+QgbgZgBgOIgCgjQgCgUgGgOIgbhIQgUg5AAgHQAAiNCKFwQAAALgGAMQgGAOgLAFQgOgKgQgPgAjuigQgKgfgCghQAAgeAQgCQAOgCAVAUQAyAwAAA+QAAAOgCAFQgGALgUAAQgoAAgVg+gAB+kVQgVgYgniPQgoiQAAg2QAAg0AEgOQANgrAwASQAJA3AXBKQAzDTAAAtIAAAlQgDAYgKAKgApYkaQgHgHgDgPIgCgRIAHhwQAIhfAEgQQAShBAnBgQAkBXAAAkQAAANgOAmQgTAwgUAJgAEKlKQgCgRACgRQAAgTAOg5QAPg9ARgrQATg1AMABQAOABAABQQAAAjgPBNQgVBqgeAAQgVAAgEghg");
	this.shape.setTransform(5.1,-79.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-56.2,-153.8,122.8,148);


(lib.shape243 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AgQAKIgCgKQAAgSASABQATAAAAARQAAAIgHAFQgGAFgGAAQgMAAgEgIg");
	this.shape.setTransform(-63.1,-154.6);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AjDK8QgGgYgBgbIAHhIQAAg7gPhLIgPhJQAAgWAJhNQAKhVAIgQQAXgvAXiVQAAgTgNgTIgdgjQgqg0AAhLIAAgXQAEgPATAAQACAAAeAjQAgAmAUAJIABABIAAgFQAAgGgTgrQgTgqAAgiQAAgtARADQAOADAYAnQA1BaAXB0QARAvAKAXQAEAMAmAUQArATAEAFQAOAQAIA8IAHBBQAAAZgmAWQgmAWgBAhQgCBDgfAqIgYAAQgFgGgCgEIgFgJIgDATQgDAQgPAAQgXAAgWhSIggh+QgDAKgBAjQgCAegJASIAACyQAEAPAAAhQAAAagFAoIgFAxIADA3QAHAtAAAJIAAAOQgDAJgLAAQgYAAgMgvgADjJtQgCgQACgRQAAhIAuiQQAwiTAmgkIAFABIAFgBQAOALADATIABAiQAABDgrCGQgmBzggA0IAAACQAAAIgKALQgLAMgKAAQgOAAgCghgAogHZQgJgHAAgOQAAgfA+AEQA+AEAAAkQAAAMgEAEQgIAJgbAAQg5AAgTgRgAIQE+QgNgOAAgLQAAgFANgIQAPgHAPgCQAbgEAKARQAIgDADAIIACAVIgCAVIgLACQgGADgNAAQgeAAgSgSgACPB9QgGgeAAgeQAAgVAFgjIAEgvQAAgUgHgoQgHgpAAgUQAAgNADgFQAHgPAaAAIAegCIAVAlIACAeQAAAQgFAYQgGAZAAAOIAHB/QADAhgDAZQgFAwgdAAQgdAAgLg8gAHkCgIgHgBIgBgVQAAgZAng/QAmg+AABFQAAAngGAVQgMAsgjAAgAl4gjQgQhCgKhDQAAhJAdgvQAggyAMB/QALAdAOBhQAMBVAAAQIgBAsQgFAjgTAAQgcAAgfiCgAAJhvQgEgiABgjIAHg4IgHhDQgGgtAAgWQAAgSACgGQAJgTAeAJQANALAUA7QATA2AAAOIgHBKIAHBCQAAATgLAcQgNAkgUAAQgeAAgKhEgABImnQgYhngThoQAAgtAcgvQAdgzAUA7IARBIIARBMIAkCxIAYB2QAAASgGANQgMAXgdAAQgfAAgyjOgAo4kjQgegRgGgYIgDgpQAAgmAJhBIAOhnQAXgsAVAgIAcA7QARAbAEAbQACAJAAApQAAA5gDAPQgJAsglAVgAEIlkQgCgYACgZQAAhNAPg0QAWhMAzACQAMAKADAmIABApQAAA7gKAzQgVBmg3AAQgPAAgDgxg");
	this.shape_1.setTransform(4.1,-80.6);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-65,-156.5,130,150.7);


(lib.shape242 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AgXgIQAAggAXAKQAYAJAAAfQAAAIgEAHQgFAJgKAAQgOAAgOgqg");
	this.shape.setTransform(-62.6,-153.7);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AioLlQgIgJgGgNIgCgHIgBAAIgIhWIAAiIIgYhrQgHgjAAgzQAAhDAchwQAchwAAgFQAAgxgmg0Qgmg0AAg3IAAgmQADgbAWAAQAVAAAPAkQATAvAFAFIABgUIgFgxIgFgyIABgsQADgcAOgJQANATAZA/IAxB2QBACYAsAAQAqAAAUBlIANBrIAAATQgCAKgNAAQgIAAgHgGIgIgHIgiB3QgdBcgWAAQgRAAgEgNIgHgUIgJASQgKAPgLAAQgYAAgRhSQgVhngJgQIgKCLQgKCFAAAkIAKCVQAAA9gCAiIgLAFQgMgFgBgNgADZKpIgBgdQAAi9BcjYQAkhVAbgaQAdgcAAA7QAAAlhMDoQhFDRgaBAQgJgMgDgQgAoGHfQgOgLAAgLQAAggA6AEQA6AFAAAgQAAAJgEAHQgGAOgQAAQg1AAgXgRgAH9E6QgCgDAAgLQAAgcAtgCQAtgDAAAgQAAARgPAGIgeAEQgiAAgJgMgACXCeIgLgWIAAj+QgCgYg9jrQg7jkAAgkQAAgcAMggQAMgfAQgPQAqgnAKBhQAAAkAJA0IASBcQASBWAnBuQAWBAAABeQAAAfgHAsQgIAsAAAvQAHA1ABAkQAABFgkAAQgSAAgEgLgAHCBUQgGgXABgZQAAgLASgcQATggAUgWQA6g+AABWQAAAmgLAzQgRBLgeAAQgmAAgOgvgAH2BlQAWAAABg+IgEhIQgNAYgWAKQAWgKANgYIAEBIQgBA+gWAAQgQAAgIgdQgGgUAAgRQAAgaAOgIQgOAIAAAaQAAARAGAUQAIAdAQAAIAAAAgAlkghIgpifQAAgyAMgrQALgnAPgQQAQgPAKAUQAMAYAABAQAABhAaA7QAaA6AAAeQAAAOgIAqQgIAqAAAWIgEADQgEADgIAAQgLAAgsicgAAahAIgHgCQgIhMgFiZQgHiHgjhdIAAgjQA7A5AlB/QAiBxAABtIAAAyQgIAngrAAgApBkuQgOgIgEgVIgBghIADh3IAChyQAAh2A5BkIA4B8QgZCagnAjgAD8llQgCgaACgaQAAhJACgJQADgQAehZIATg9QAPggAYAiQAMASAGAeQAGAZAAAVQAAAKgFACIgBAAIgHAeQgIAfAAAWIgCABIgFA9QgPBhgpAAQgbAAgGgyg");
	this.shape_1.setTransform(4,-80.3);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-65,-157,128.7,152.8);


(lib.shape241 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("ANUIHIgIgFIgBgPQAAgVAVAAQAWAAAAATQAAAFgGAIQgIAKgKAAgAtzG+IgCgJQAAgVAUAAQASAAABATQAAAJgHAFQgFAFgHAAQgOAAgEgIgAKQi3IgBgKQgBgTAUAAQATAAAAATQAAAHgHAGQgGAFgHAAQgOAAgDgIgABlk5IgCgQQAAgVAUAAQATAAAAAVQAAASgTADgArknVIgRgeQAAgiAfAWQAhAXAAAZQAAAYgUAAQgIAAgTgeg");
	this.shape.setTransform(10.9,-104.1);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("Ai+KSIgJhYQgFgygGgWIABAAQgJgjgJhFQgNhcAAgWQAAgvARhHQAQhHAAgKQAAhSgchMQgdhMAAgeQAAgjAKgeQANgpAbABIAMgDQAPAAAIAeIAJAqQAPgHgBgXQAAgMgFgXIgChEIAAghQADgdAPAAQAXAAAnBoIA7CaQAKgJACgRIABgfIgDg5QgDg5AAgcQAAgagHgvQgGgvAAgXIAAgcQADgSANAAQAUAAAPAjIASA2IAFABIAEgqIgiiVQAAgOAMgfQANgiAPgUQArg4AOBsQADAfATBAQAVBEAEAeQAMBNAhCCQAXBZAABcQAAATgJA0QgKAzAAAhQAAAuAGAUQAEASABAWIAbAjIAxBHIBFhzQAxhDAABaQAAAPgXBLIgXBDIAAABIgVBMQgYBQgHAeQgIBDgJAnQgSBJglAAQgXAAgGgaQgDgNACgOIAHg/QAAgYgFgdQgGgcAAgkQAAgfAMgsIAMgrQAAgjgJgfQgNgrgcgKIgWABIhDCLQgyBjgqAAQgOAAgIgJIgJgOQgGAEgIAYQgHATgPAAQgOAAgOgdIgSgoQgJAlADA4QAFA/AAAfQAAATgKBFQgMBOgIAAQgiAAgNhqgABvgnIAKgfQgBgFgJAAIgDAQIgDANIAAAFIAAgBgAnvHdQgQgOAAgNIACgOQAEgHAWgJQA8ABAVAVQALALAAAWQAAANgFAGQgHAGgVAAQgvAAgYgXgAHrE2QgEgFACgGIABgPQADgJAIgCIAhgGIAlgEIASANIABALQAAAMgOAJQgRAMgjAAQgbAAgGgKgAlRBCIgQhwIgShTQgThWAAgSQAAiYAhgfIAAADQAAADAGAAIAAAAIgIAKIAIgHIAFgDIgBAAIAEgCIACgBIABAAIALgEQAaAAAFAhIAAAhQAAAbgIA5QgJA6AAAZQAAAsAZA5QAYA5AABlQAAA/gTAAQgjAAgRhIgAHTBhQgfgXgHgXQgDgJAAghQAAgQAVg1QAVg2AYgsQAcgzARgJQAVgLAAA3QAAAVgIAzIgMBEIAABHQgDArgeARgAHdBFQAegTADgiIADg+IAMg6QAEgWAAgOQAAgKgCgGQACAGAAAKQAAAOgEAWIgMA6IgDA+QgDAigeATQgSgUgEgNQgBgFAAgTQAAghAbg0IAuhSIAAgBIAAABIguBSQgbA0AAAhQAAATABAFQAEANASAUIAAAAgAD9k6QgVgVgFgoQgBgOAAg0QAAhCAVhHQAUhCAbgkQAcgmATAUQAVAXAABeQAAAYgaBiQgeBygaAfgApLl5QgFgpALg0IAAilQgIgcAAgNIABgcQBAAJAnBZQAeBEAAA7QAAAmgOAuQgYBLgyAAQgmAAgGg5g");
	this.shape_1.setTransform(3.6,-79.6);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-77.7,-156.1,177.3,153);


(lib.shape240 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AMbIOIgBgLQABgUAqgaQAqgaAAAmQAAAMgNAKQgNAKgoATgAtrG7IgDgOQAAgZAXAFQAVAGAAAWQAAAGgDAGQgGAHgKAAQgQAAgGgNgAjWhKIgBgKQgBgUAUABQASAAAAATQABAIgHAGQgFAEgHAAQgOAAgEgIgAJ5iZIgCgSQAAgbAbgQQAbgPAAAcQAAAKgKATQgMAWgNADgABck9QgBgGABgIQAAgcATAAQAUAAgBAcQAAAagTAAQgPAAgEgMgArhnNIgSguQAAgwAlAvQAlAvAAAZQAAAGgEAFQgFAIgKAAQgRAAgUgsg");
	this.shape.setTransform(11.2,-102.8);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AiZMJQgFgxgrjTQgojHAAgRQAAgnANg4QANg4AAgsQAAg+gchGQgchHAAgsQAAgeAJg5QANhQATAAQAUAAAVAtQAIASAPAtIABgBIAAjSIAIgIQAGgFAHgBQATABAgBnQAlB5AUAdQASgSAEgaIACguQAAgxgNg4QgMg4AAgnIAAgkQADgYATAAQAdgBAQA+QAOBIAJASIADACIABgGIgQiHQgKhUAAg1QAAgwARgnQAUgvAXBJQALBRAQBaQAMBBAuCMIArCHQgKCSAAAlQgDAnACAkQAEBFAeARQAsAZAKAyQAEA5AGAbIABAAQAhioA3gBQAUAAADAOIAAAPQAAAbhVEPQhZEcgZAAIgLgBIgCgBQgBgFACgJIACgRQAAgVgKglIAAktQgJgQgEglQgFgogHgSIhCCWQg7CGgIAAQgFAAgUgeIgZgpQgFAIAAA6QAAAugaAAQgSAAgRghIgSgpIgXCKQgLBQACA8IgDACIgLACgAnVHuQgSgOgJgLQAAglBCAMQBBANAAAjQAAAJgDAHQgHAOgQAAQgqAAgkgcgAH7FRIgTgNQgIgGAAgGQAAgQANgGQAUgJA6ADQAOAEAHAKQAGAHAAAGQAAAKgLAJQgJAGgHABgAleACQgWhPgQhSQAAgwASiFQAUiTAPgJQALANgDALQAoANALAeQAFAOAAAlQAAAmgSA4QgSA4AAA0QAAA3AXA+QAXA8AABSIAAAuQgEAjgTgBQgYABgqiigAHCBRQgSgOgFgeQgBgLAAggQAAgOAZhLQAahQAchCQBQi7AACOQAAAtgQApQgYA7gIAnIgIBfQgFA7gZAdgAHMA1IAkgDQAFjEAzhwIgGABIAGgBQgzBwgFDEIgkADIgEgiIgDgbQAAgtAkhQIA5h8Ig5B8QgkBQAAAtIADAbIAEAigADkk+QgGgVgDgVQAAg5AUhdQAThaAZhAQAbhGARAEQAUAFAABsQAAAxgXB/QgeCkgkAAQgSAAgMgpgAoumUQgEgvABhXQgFgtgRhQQgOhEAAgdIABgTQAlALAUApIAdBPQAKAMAjA/QAkBCAAAKQAAAfgUBBQgbBTggAAQgqABgIhXg");
	this.shape_1.setTransform(3.1,-80.7);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-76.7,-158.7,175.8,156);


(lib.shape239 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("ALvIXIgCgJQAAgKA+grQA+grAAApQAAAKgmAeQgpAggVAAQgRAAgFgIgAtaG5IgOgUQAAghAgARQAgARAAAYQAAAKgHAGQgFAFgHAAQgNAAgSgagAjHg+IgBgXQAAgXATgEQATgEAAAgIgBAMQgEALgOAFgAJnhxIgHgFIgBgEIgBgLQAAgVAog3QAog2AAA0QAAAFgZAuQgaAxgJAAgABdkvQgCgJABgLQAAgfAWgKQAWgKAAAbQAAAPgFAUQgHAcgNAAQgPAAgDgTgArPm6IgfhFQAAhjBfDTQAAALgFAIQgFAJgKAAQgLAAghhHg");
	this.shape.setTransform(10.6,-101.3);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AjFKcQgWhmgfjCQgJg1hHi2Qg/ihAAhRQAAgeAYieQAWidAAgfIAEgBIAJgCQAeAAAwB6IBHCzQADglADhBIAFhrIACgDIALgDQAVAAAgBNIAoBvQAGgRAAgrIgKhrQAAgcAUhJQAWhLAchDQBIizAhBRQAiBMASB+IAdDJIBBjkQAribAUAAQANAAAHCwQAABVgjBxQgjByAAA2IAJA/QALA2gBATQAAAZgHAfQgIAeABATQgBAhBPAdIBPAeQAAAIgaBhQgfB0ghBlQhjE4g3AAIgMgBIgDgBQgBgbAAg1IAKjTQAAgTgJgiIgCgCIgkCLQgYBcgXAAQgQAAgQgdIgQgiIgFAhQgEAUgXAAQgSAAgEgEIgPgUIgfABQg1BaAHBgIgCACIgJACQghAAgni3gAmzIVQhDgiAAADQAAgzBiAkQAjANAfATQAfASAAAHQAAAagmAAQgRAAhJglgAGxF2QgBgDAAgKQgBgJAVgOQAUgNAZgIQBCgVAAAqQAAASgiAPQggAOggAAQgZAAgHgLgAGDAvQgHgZACgZQABgXAihcQAkheAqhUQAwhiAegcQAigiAABNQAAAJglBrQglBtgBATQgTDohMAAQgnAAgLgygAGagDQAAAQAFANQAGAQATAWQArhOAfiKQAoiwAVg4IgCAAIACAAQgVA4goCwQgfCKgrBOQgTgWgGgQQgFgNAAgQQAAgcBEieQBAiWAcgvIADACIgDgCQgcAvhACWQhECeAAAcIAAAAgAnej4QgGgngVhmIgZiNQgGgwgkhzIgjh0QAAioDWINQABAagWBSQgaBjgYAAQgNAAgBgDg");
	this.shape_1.setTransform(3.1,-83.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-76.7,-168.5,174.8,170.3);


(lib.shape238 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AK5InQgBgCAAgHIAbgXIA8gsQBYg5AAApQAAAQg/AqQhAAqgZAAQgRAAgFgIgAtmGdQAAgnAoAeQAoAfAAAiQAAAFgFAGQgFAIgKAAgAjEgZIgBguQAAgyATgEQASgEAAA6IgBAbQgDAXgOACgAJJhGIAFgXIArhhQAyhhAABJQAAAJgkBIQglBJgIAAQgOAAgDgKgABVkJQgCgOACgPQAAgpAYgiQAKgOAHACQAHACAAAXQgRB2gMAAQgQAAgDgbgAqymLQgvh9AAgJQAAhTBBCYIBBCpQAAAcgTAAQgOAAgyiEg");
	this.shape.setTransform(10.4,-99.8);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AjTKcQgWhmgfjCQgIg1hHi2Qg/ihAAhRQAAgeAXieQAXidAAgfIADgBIAJgCQAeAAAwB6IBHCzQAEglAChBIAFhrIACgDIALgDQAWAAAfBNIAoBvQAGgRAAgrIgKhrQAAgcAVhJQAVhLAchDQBIizAhBRQAiBMASB+IAeDJIBAjkQAribAUAAQANAAAHCwQAABVgjBxQgjByAAA2IAKA/QAKA2AAATQAAAZgIAfQgHAeAAATQAAAhBPAdIBOAeQAAAIgaBhQgfB0ggBlQhkE4g3AAIgMgBIgCgBQgCgbAAg1IALjTQAAgTgJgiIgDgCIgjCLQgYBcgYAAQgQAAgQgdIgQgiIgEAhQgFAUgWAAQgTAAgEgEIgPgUIgfABQg1BaAHBgIgCACIgJACQggAAgoi3gAnBIVQhDgiAAADQAAgzBiAkQAjANAgATQAeASAAAHQAAAaglAAQgSAAhJglgAGkF2QgCgDAAgKQAAgJAUgOQAUgNAagIQBBgVAAAqQAAASgiAPQggAOggAAQgZAAgGgLgAFmAbQgJgZgCgXQAAg0AshrQA2iAAGgZIAShMQANgsAaglIBAhbQAxg4AABMQAAAegnCMQgeBrgQAwQgbB0gVBFQgmB+grAAQggAAgRgwgAGXAtQAig0AYhhQAdhzARgnQBFieAIiSQhRBwgnCfIgxB8IAxh8QAnifBRhwQgICShFCeQgRAngdBzQgYBhgiA0IgVglQgMgPAAgOQAAgfAthzQgtBzAAAfQAAAOAMAPIAVAlgAnsj4QgGgngVhmIgZiNQgGgwgkhzIgih0QAAioDWINQAAAagWBSQgZBjgZAAQgMAAgCgDg");
	this.shape_1.setTransform(4.4,-83.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-76.7,-168.5,174.3,170.3);


(lib.shape237 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AJtI/QgCgDAAgHQAAgGAoggQApgjAtgdQB+hTAAA0QAAARhzBFQhsBBgHAAQgQAAgEgIgAtDG7IgjguQAAg2A3A4QA3A3AAASQAAAMgKAFIgLACQgPAAgngwgAjFglIgKhIQAAgbAHgEQAHgDAKAQQAXApAAA/QACAVgCAKQgCAZgQAAQgIAAgLhGgAImAFQgCgDAAgFQAAgqA/iJQA+iJAABQQAAAMguB2QgwB6gMAAQgNAAgEgIgApbhiQgFhIhEirQhCinAAgnQAAigCwI5QAAAjgTAKgABOiGIgHgFQgCgjAAhDQAAhLAbhBQALgbAIABQAIABAAAlQAAARgHAnQgIAoAAAXIAEBHQgBAugWAAg");
	this.shape.setTransform(10.9,-97.1);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("Aj8IRQhak1gojZQgQhUgnh+IhDjTQgThAggixQgaiLgEgiIgBgDIAAgDIAAgCQAAgOAHAEIAAAAQAGAAAKAJQAWAVAhA5QBSCQAzDAIADAAIAAhYIADgCIAKgCQARAAA/CEQA1BvAnBnIADACQAKg1AHhaIAOiaIACgDIAKgCQASAAAOBeQASB5AJAaQAShFAcjmQAhjEAwAAQAbAAArCZQArCZACBpIADACQAWguAzjBQAqifATAAQARAAAICGIAFCHIgMBJQgNBJAAAmQAABNAPAyQAPAyAAAzIgHAvIgIAzQAAAYAGAJQAPAWAygBIABgCIACgCIAKgCQAJAAACAFIABAGIACABIAEAFIgEANIgDAAQgNAzhcEgQhsFSgMAAQgtAAgXgcIAAjHIgCgEIgbCAQgSBYgZAAQgSAAgJgdQgLgmgEgEQgOAkgKAAQgVAAgQgaIgRghQgNA4gJAbQgTA4gRAAQgcAAhdlDgAmIIlQhMgsAAgBQAAgxBbAiQAkAOAaATQAdAVAAAPQAAAigcAAQgCAAhMgrgAFqGTIgCgOQAAgVAdgYQAbgWAmgQQAmgQAaACQAeABAAAYQAAAMiiBVQgTAAgFgLgAFlhUQgOg7gJg+QAAgIAxhhIBIiUIAcg8QARgkAJgcQAVg/AdgLQAcgKAAAyQAAAXhQE2QhSE8gOAAQgbAAgbh1gAGVgDQAQhiA9jPQA7jJAPhjQgPBjg7DJQg9DPgQBiQgWgfgLhTQgHg2AAgfQAAgUC/mCQi/GCAAAUQAAAfAHA2QALBTAWAfIAAAAg");
	this.shape_1.setTransform(4.6,-82);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-76.2,-167.2,174.3,170.5);


(lib.shape236 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AIJJjIAAgBIgBgKQAAgXCxh1QCwh1AAAqQAAALiGBXQihBognAfgAsqGmQg+hKAAgHQAAgsBOBNQBBBAAcArIgDANIgEADQgFADgHAAQgXAAhDhOgAH/ByIgBgMQAAgFAehZQAihgAHgdQAWhdAkhEQAlhFAAA7QAAAPhBDDQhDDKgPAAQgPAAgDgKgAjDgZQgFhMAAhHQAAgTAHgEQAGgEAJAMQAVAiAABUQAAAeAIA1QAIA3AAAYQAAAfgTAAQgZAAgKiVgAA0BSQgCgGACgGQAAgoAIhtIAMiGQAAg4AFhVQADgeAWgrQAYgtAAA8IgJBvIgLCTQADBdgBA3QgCBjgjAAQgQAAgDgLgAp4jnQhxkyAAgIIgDgCIgCgfQAAgnAUAAQATAAAAAnQABAKgBAJIgCAIQAHAKAHARQAIAKAIAfIAMArIAZBRQAQA0AXAjQAMATA0CMQA4CSAAAbQAAAHgHAGQgGAFgGAAQgMAAhyk1g");
	this.shape.setTransform(10.6,-92.9);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AimNWIgJgDIgGADQgkhcgjhoIgEAAIhbhCQhZhBAAAHQAAgbAgAAQAeAAArAUQAYALAUAOIgWhJQgpiIhBjzQghh3g6kvIgojfIgGABQgNgggDgtIgBhOQAAiEAFgPQANgnA5CoQAEA4AyBfIBRCaIAEAAQADgVAAgwIAEgDIANgEQANAAA+CaQAiBRAVA+QABhmAQhkQAZiXAqBFIAgDKIAJBGIAbhwQA0jOAdh1QAhh6AhAxQAeArgCBUQAEA6AUBUIAUBUQAYheAziGQAohpAcgsQAegyAAA0QAABlgZEVIgRDOIBIipQB4kRBAhkIALAEQAGACAAALIgBAHIABAZQAABshHEVQhXFMgDAQQgSBrhADXQAeghAkgcQAugjAdgGQAhgGAAAlQAAAOhCA5QhGA8g2AdIgKgEQg6DDgVBtIABAAQAJADgBAPQAAAPgIAFIgQAEIgeAAIgKADIjiAEIgJADg");
	this.shape_1.setTransform(4.9,-83);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-76.7,-168.5,174.8,171);


(lib.shape235 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AF6KcIgBgSQAAgWBPhHQBJhBBlhJQBphMBGglQBPgrAAAaQAAAfiDBKIiZBYIhnBcQg4AygtAygAsBGFIhyh2QAAhKCECJICDCZQAAATgVAAQgNAAhzh1gAF/ExQgBgDAAgHQAAgMA/iOIBgjTQAlhOAehoIAZhcQAMgjAQgSQATgXABA2QAAAZh2E/Qh9FPglAAQgOAAgEgIgAAnEVQgDgFAAgGQAAhoAPihIAakIIAAjVQAIgiAUgCQAVgCgBAZQABAIgEAJIgHAMIAADOQgKDZgJByQgPDTgZAAQgNAAgEgLgAi+gCQgIhngChnQAAgfATgqQASgqAABHQAABgAGAtIAUCLQALBTgBA6IgBATQgDANgPAAQgcAAgQjLgAoUAXIhBj+QgQg/hCi2Ig9itQAAg1AiBAQAQAgAzB6IAoBtQAYBCALArIBDDwQAyCvgBASQAAAHgBACIgCAGIgGACIgMACQgRAAguijg");
	this.shape.setTransform(10.7,-85.4);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AimNWIgJgDIgGADIgOgnQgPgPgQggIgihMQgLgRhAgyQgzgoAAgdQAAgmAnASQAdAPAtAsIgkh0QgpiIhBjzQghh3g6kvIgojfIgGABQgNgggDgtIgBhOQAAiEAFgPQANgnA5CoQAEA4AyBfIBRCaIAEAAQADgVAAgwIAEgDIANgEQANAAA+CaQAiBRAVA+QABhmAQhkQAZiXAqBFIAgDKIAJBGIAbhwQA0jOAdh1QAhh6AhAxQAeArgCBUQAEA6AUBUIAUBUQAYheAziGQAohpAcgsQAegyAAA0QAABlgZEVIgRDOIBIipQB4kRBAhkIALAEQAGACAAALIgBAHIABAZQAABshHEVQhXFMgDAQQgSBuhEDhQA0hAApgYQAqgZAAAkQABAJhCBLQhLBVgdBDQgMAbgeBwQgPA4gKAWIABAAQAJADgBAPQAAAPgIAFIgQAEIgeAAIgKADIjiAEIgJADg");
	this.shape_1.setTransform(4.9,-83);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-77.7,-168.5,176.8,171);


(lib.shape234 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AEnLCQgCgCAAgIQCXiDCWh3QEujuAAA3QAAALh4BbQhWBChbBBIiXB8QhxBegSAAQgSAAgEgIgApeISQhIhEghgpQgYgdhWhPQhKhFAAgHQAAhNDIDLQBjBmBlB3QAAASgXAAQgMAAhMhIgAEsHWQgCgFAAgGQAAgNBPi2IBykHQAvhzAphwQAhhcAjg/QAphLAAA7QAAAUhKC5QhECpghBEIhrEGQhFCtgUAAQgNAAgEgKgAAsGcQgDggADgiQAAhGAKiMQAKiLAAhIIAKhpQAHhBAIgsQAAhZAWg5IgCgHQgBgMABgNQAAg3AUAAQATABAAA2IAAAcQgCAOgIAFQgBBygbEHQgcETAAByQAAANAFAvIAFAzQAAAHgGAGQgHAFgGAAQgZAAgEg/gAihE9QgDg+ACh7IgKkmIACgqIACg2QAAgeAMgXQANgcAOAxIgDB2IgCBOIAMD8IALB/QAIBOgBAvQAAAGgDAGQgGAHgKAAQggAAgGhwgAn3BvQgOgrgThVQgVhagMgrQgUhBhMi7QhEiwAAhdQAAhAAWAiQAOAZAXBFQgBAeALAnIAVBFQAMAwAmBYQAoBhANApQAsCPAcCCQAHAmAuB3QApBvAAAHQABAJgHAGQgFAFgIAAQgeAAhQkGg");
	this.shape.setTransform(9.9,-83.3);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF3300").s().p("AiMFUIgHgBIgEABQg4hDg1hTQgig2g3hgQgbgvgxh4IgjhZIgEABQgLgNgDgSIgBgfQAAg1AEgGQAMgPAwBDQADAWArAmIBDA9IADAAQADgIAAgTIADgCIAMgBQAKAAA1A9IAuA5QABgpANgnQAVg9AjAcIAbBQIAIAcIAXgsIBDiBQAcgwAdATQAZARgCAiQAEAXAPAhIARAiQAUgmAsg1QAigqAXgSQAZgUAAAVQAAApgUBuIgPBSIA9hDQBlhtA1goIAKACQAFAAAAAFIgCADIACAKQAAArg9BuIhLCJQgQAvhABjQg5BZgUAwIABAAQAHABAAAGQAAAGgHACIgOACIgYAAIgJABIi/ABIgHACg");
	this.shape_1.setTransform(3.7,-31.6);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-79.7,-154.7,179.3,157.1);


(lib.shape233 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AC3LvIgCgKQAAgkC+h/QBghABig7QCjidBAg1QB3hhAAA6QAAAVhOA1IhfBBIhFBIQgtAsgrAdIl6ENQgQAAgEgIgAAgKKIgIgFQgBgaAAg2QAAg9ABgHIAYhnIAAjWQgPhRAMhwQAGhBASiCQALgigBg/QAAhFAFgcIAPhgQAAg2AbgUQALgIAHAGQAJAHAAAWQAAAbgVCkIgeDnQgVCQABBSQAFBgAABaQAABEgQB1IgFBxQgEBBgTAAgAoQIjIh9iJQgVgVh9hnQhvhbAAgGQAAhFEADsQBeBXBRBVQBQBTAAAMQAAAJgJAGQgGAEgHAAQgSAAhZhfgADGJYIgBgBIgBgKIA5hpQA+htASg9QArigAyhzIA8iHIA+iKQCWlCAABiQAAALhmDXQh1D0gaA/Qg9CvgjBaQg8ChhSBpgAmNGJQhij8gxjMQgOg7hZk8QhMkPAAgZQAAgfATAJQATAJAHAlQAUA6AFAeQAGAkAQAzIAbBVIA0CtQAcBnAJBHQADAWBzEvQBuElAABJQAAAIgGAFQgGAFgHAAQgIAAhTjVgAh9I6QAAhogOiJIgdjwIAAjzIgHhRIgDg4QAAgkATgbQATgbABBRQAAApAKBdIAADxQAnGDAAAzQAAA0gSAKg");
	this.shape.setTransform(9.9,-78.1);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC00").s().p("Ai/DeIgFABQhJgshEg2IhzhjQgkgeg/hPIgtg6IgFAAQgOgIgEgMQgCgEAAgQQAAgjAGgEQAPgKA+AsQAEAPA3AYIBXApIAEAAQAEgGAAgMIAEgBIAPgBQAOAABEAoIA8AmQABgbARgaQAbgoAuASIAjA1IAKASIAegdIBYhUQAkggAlANQAgALgCAWQAEAPAVAWIAWAWQAagZA5gjQArgbAegMQAhgNAAAOQAAAagbBJIgTA1IBPgsQCDhHBFgaIAMABQAHAAAAADIgCACIACAHQAAAchOBIIhiBaQgVAehTBBQhKA7gaAfIACAAQAJABAAAEQAAAEgJABIgSABIggAAIgLABIlsACg");
	this.shape_1.setTransform(7.7,-19.9);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-81.2,-154,182.4,156.5);


(lib.shape232 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AjWMFIgBAAQgFAFgHAAQjxjRhihiQglgmieiNQiDh1AAgJQAAg2CLB+QCiCdAtAoIC0CcIBcBWQgjhGgqhwQhPjPhRkWQgyitgvjbQgKgxguixQgpifAAgHQAAgRAQgCQAQgBAMAWQABAQAJAiIA1DGQAPA8AFAnQALBLAlB9QArCTAMA2QASBVAmByIBIDIQAYBABVCuIBRCiQAAAJgKAGIgMAEQgPAAgUgVgAAtMOIgIgFQgBgeAAhEQAAhJAFgmIAAjlQApjdAFkCIAPjxQgCgTAGgmIALhAQAAghAWgkQAWglAAA4QAAA9geFdQggF6gUBvIAADlQgEARABBsQAABSgVAAgAhvIsIgDjCQgDhxgIg3IAAjQQgEgPgCghQgCgbgHgRIAAi+IgPg9QAAgSAPAAQAQgBAIARIAIAZQAFASABAHQACAfgBBAQgCBrARBUIAADUQALA4ABBXIACCPQAEAwARBkQAPBXAAAzQAAAJgEAGQgFAHgKAAQgxAAgHjjgACQMCIgBgJQAAgTB3kCID7odQArhgAZhJQAmhvA5hrQA8hyAAA2QAAAQhsD8IijF8QhNC7hZDEQhzD7gUAAQgQAAgEgIgADgL1QgBgGABgHQAAglCKhzICdh9QBZhTB9hYQCghxAAA2IiPBoQieBzg9A2QgYAVhJAzQhFAvgOAOIhsB9QgPAAgEgLg");
	this.shape.setTransform(7.6,-76);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC00").s().p("AlRB9IhzhjQgkgeg/hPIgtg6IgFAAQgOgIgEgMQgCgEAAgQQAAgjAGgEQAPgKA+AsQAEAPA3AYIBXApIAEAAQAEgGAAgMIAEgBIAPgBQAOAABEAoIA8AmQABgbARgaQAbgoAuASIAtBHIB2hxQAkggAlANQAgALgCAWQAEAPAVAWIAWAWQAagZA5gjQArgbAegMQAhgNAAAOQAAAagbBJIgTA1IBPgsQCDhHBFgaIAMABQAHAAAAADIgCACIACAHQAAAchOBIIhiBaQgVAehTBBQhKA7gaAfIACAAQAJABAAAEQAAAEgJABImzADIgFABQhJgshEg2g");
	this.shape_1.setTransform(7.7,-19.9);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-81.7,-155.4,178.8,158.9);


(lib.shape5 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF33").s().p("AgjGqIgFgLQAAgDAEgCQAJAGACANIgCAIgACnGUQgLgFAAgFIAFgFQANAEAKAMIgCAEIAAAAQgFAAgKgFgAhSFdIADgBQAFgBAMAVIALAZIgBAIIACgCIABADIgCABQgWgOgJgogAgzF3IgEgIIABgEIALAQIgBADgABXFwIgJgOIADgFQAEAAAJAMQAJALAAAFIgDAEQgFgBgIgMgABfFjQgYgVAAgGIACgFQAUAOAjAhQgDAGgCAAIAAAAQgGAAgWgVgAhqEzIgFgMIAAgFIADAAIAFAKIgBAHgAi4EmQAAgFAEgBIACAAIABABIABAIIgBAFIgBAAQgFAAgBgIgAA3EjQAAgBAAgBQAAAAAAgBQAAAAAAAAQABAAAAABQAKAAAAAJIgBADQgKgCAAgIgAhXEfIAAgDIAIAFIADAFQAAAAAAABQAAAAAAABQgBAAAAAAQgBABgBAAgADkD5IADgFIAMAIIgIACQgGAAgBgFgACADOIABgEIAHAAIAaALIAAgCIgCgGQAGACAQAIQARAJAAACIgBADIgIADgACTCsIADgCQAKABAFAHIgEAEQgJgBgFgJgAg8CIIADgEIACAAIACAEIgCADgAgNCDIAAgDIAGgBQAFgBACAHIgDAEQgKgBAAgFgAhhB8IAAgGQAIABABAGIAAADQgKgBABgDgADDBtIABgEQAEAAAHAGQgCACgGACQgEgBAAgFgABjBeQAAgEACACIANADIANADQAFACABAEIgFAEQgcgMgBgCgAAiBWIABgEQAJAHABAEIgBAEQgKgBAAgKgACjA+QAAgBAAgBQAAAAAAAAQABgBAAABQAAAAAAABIAIgBIAFADQAAAEgGABQgHgCgBgEgAABA8IgBgFIAAgDQAEACAAAEIgBACgABJA0QAAgHAGAAQAdADABAHIgBAEIgIABQgagBgBgHgABhhhQAGgIANgBQAFgBABADQgCAKgRACgACAhuIAHgGIACACQgDAEgDAAgAgwh6IAHgEIACACQAAAEgEAFQgEgCgBgFgAgfiIQAAgDAGgBIABADIAAABIgCADIgEAAgAg5iKIgBgMIAEgBQADgBAGAFIAEAFIgBAIIgCAAQgIAAgFgEgABxiHIAFgFIAFABIAAABQgEAEgCAAgAhwiPIgBgEQgBgHAGgBQABAAABAAQAAAAABAAQAAAAAAABQAAAAgBAAIABAIIgFADgAB1iaIgCgDIAFgFIAFACQABABgIAFgACJiyQACgJAPgCIADABQgBAEgGAGIgHAFIgBAAQgEAAgBgFgAABjFIAGgMQAHgKAHgBIAFADQAAAGgEAIQgGALgJABIgBAAQgEAAgBgGgAC5jNQALgNAJgBQAFgBAGAEIAIgDIgZARIgEABQgGAAgEgEgAg8jbIAAgIQACgGAFgBIAFADIgCAIQgBAEgGABgAATkEIAMgPQAJgKAHgBQACAAAAAAQABAAAAAAQAAAAAAAAQAAAAgBABIAAABQgVAagDABIgBAAQgDAAgCgDgAgQkYIABgDIACACIgBADIgCABgAB/kjQACgGAIgBQACAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgBACQgGAFgDABgAgaksQgBgFAFgMQAGgMAEgBIAGABQAAAEgHANIgIAMgAA8kxQADgJAGgBIACACQgDAKgFAAgAAkk5IgBgCQgBgIAGgCIADACQABAJgGABgACWlGIgCgBIAMgJIACABIAAACQgJAJgBAAgAiilPIABgcIABgYQADACABAMIgCAwQgDgCgBgIgAjxlSIAAgEIACAAIAEAHQABADgEAEQgDgDAAgHgABTlKQAVglAGgBIAEABIABADQAAAGgKANQgKAPgJABQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAgAAmlWIAOgLQgGAMgDACgAgZlpIAAgHQACgEAHgDIABAAIAAACQgDAMgDABgAgNmFQAAgHAIgSIAJgWIADACQgGAigJARQgFgCAAgEgAiYmJIAAgEIADABIABADIgBAGQgEgBABgFgAiXmkQgCgLAGgDIACAAIAAACQAAAKgDAIIgCABg");
	this.shape.setTransform(-140,-101.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-164.3,-144.8,48.6,87.4);


(lib.shape4 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,153,0,0.443)","rgba(255,204,0,0.412)","rgba(255,255,204,0.463)","rgba(255,250,184,0.431)","rgba(255,198,0,0.424)","rgba(255,158,0,0.471)"],[0,0.184,0.427,0.631,0.878,1],0,-43,0,43.1).s().p("AgGGuQgXgBgNh/QgOiAADiwQADiyASh9QASh+AUACQAXABAOB/QAOB/gDCwIAAAEQgDCwgSB8QgSB8gUAAIgBAAgAgIjUIgEAZIAAACIADADIAAACQgLBPgCBwQgCBxAJBQIAGAvIgCACQAIA4ALABQAPABAMhZQANhZACh/QACh9gJhaQgKhagPgBIAAAAQgQAAgKBYg");
	this.shape.setTransform(-173.4,-102.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-1.7,-1.6,-1.7,-1.6).s().p("AAIAdIgTgVIgNgYQgDgMAEgEQAFgEALAIQAJAHAKAOQAKALADANQAEAMgGAEIgDABQgFAAgHgFg");
	this.shape_1.setTransform(-128.5,-60.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-2,0.3,-2,0.3).s().p("AgXAJQgLgEABgFQAAgGAKgEIAXgDQAPAAAJAFQAKAEAAAFQAAAGgKAEIgYAEg");
	this.shape_2.setTransform(-100,-95.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-2,-0.4,-2,2.6).s().p("AgjAMQgCgGAJgGQAJgIAQgFIAZgFQAMABACAGQACAFgJAGQgJAIgPAFIgaAGQgMgBgCgGg");
	this.shape_3.setTransform(-114.9,-114.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-1,-2,-1,6.6).s().p("AgXAjQgFgDADgNQADgNALgNIATgXQALgIAFAEQAFADgDANQgEANgKANIgTAXQgIAFgEAAIgEgBg");
	this.shape_4.setTransform(-129.5,-142.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-13.9,1,-13.9,1).s().p("AisAaQhIgLABgPQgBgOBIgLICsgMICsAMQBHALABAOQgBAPhHALIisALg");
	this.shape_5.setTransform(121.9,-99.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF33").s().p("AguGGIgFgLIgBgEIAEgBIAHAKIAFALIgCAFgACCFjIAGgFQASALABAJQAAAEgGAAQgRgIgCgLgAhOFWIgGgOIAAgEQAFADAFALQAGAKAHABIgEAEQgGgCgHgJgABJE0IgPgLQgmgiAAgGIAAgDIACACIgSgcQgYgagBgGIAAgCIgCgEIABgBIBGBCQA1AzABAEIAAACQAUAWABAHIgCADIACAFIgCADgAB4FcIABAAIgCgFIgNgIgAA8EeIAVAWIABgBIgWgVgABeEwQgWgchLhDgAhIFJIgLgbIgYg1IABgCIACgCQAKAOAUArQASAoAAAHIgBACQgHgEgIgSgAhnEVIAAgBIABAAIAKASIgBACIAAAAQgIAAgCgTgAheDzIACgGQAHgBADAMIgDAEQgKgGABgDgAivDfQgCgQAEgHIAHAOQAAAcgDAAIAAABQgFAAgBgUgAiCDKQAAgCAAAAQAAgBAAAAQABAAAAAAQAAAAAAABIACgBIAKAOIAFAOIgCAEQgNgGgDgXgADQDZIgHgFIAAgDIAEgBIAQANIgDACgACiDIQgNAAgjgVIglgUIADgBIgOgIIABgBIgRgMQAAgBAAgBQAAAAAAgBQABAAAAAAQAAAAAAABIBOAkQAyAaAAAGIgEAFgACkDFIAAABIALAGIgDgGIgBACQgDAAgEgDgAgpCcQgcgOgBgFQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAABgBIAYAQQAUAKARgEIgBAAIgDgEQgBgCAHgBIAEADIAMgRIgCgMIADgBQAEgBAEAEQAEAEABAFQAAAHgFALQgHARgMABIgCABQgPAAgagOgAB7CRIAFgGQADgBAHAIIgEAEIgCAAQgJAAAAgFgAhKBxIgBgEIAAgGIAHgCIAEAGIAAAFIgHABgAhzBfQgBgHAJgBQAJgCAAAJQABAIgLACIAAAAQgGAAgBgJgAgjBhQAAgEAEgCIAEAGIgEAEIAAAAQgEAAAAgEgACmBVQAAgCAAAAQAAgBAAAAQAAgBAAAAQABABAAAAIAJADIAAACIgFACIgBAAQgEAAAAgEgAB+BXIgGgEIgTgDIgIgCIAAABIgDACIgggDQgVgDgFgJIAMgJIgGgJIAFgFIAAgBIgZgYQgUgSgBgIIADgEQARALBJAeIgaAOIgCAHIAEAIQAAAHAOAEIAJADIAEgEQAIgCATAIIAZALIAAABQgCACgFAAgAA7AlIANgFIgGgCgAAFA6IABgCQAOADABAEIAAADIgDABQgFgBgIgIgACPAlQAAgFAEgDQAKAEAAADIgBAFQgNgBAAgDgAgoAfIgBgJIAFgCQAKgBABAIQAAAGgGABgAAohdIAlgyIgPgBIAEgEIgBgBIgRAKIgCgBIABgEIgDABIgKAFIgDgDIAFgGQgTgBgBgHIgDgMQAAgFAHgKIgHAAIAAgBIgBgCQgBgHAEgEIAEgEQgGgCAEgGIAGgIIgKAFIgDgBIAAgBIALgLIgNAFIgBgDIALgMIAQgLIACACIgHAJIAJgBIAAABIgIAJQAEABABACQgEAIgEACIAMABQAAADAGAAIgBABIgLAIIABACIgGAIIgBABIACACIgCAIQAEgBACgGIAFACIgHALIALALIASADIAEgCIACABIAJgFIACABIAfgOIAFAEIA0gfIANAAIAAADQg8AkgZAMIgEAHIAQgKIAGACQgUAIABAFIgIAMQgLAMgHACIAGADIAXAAQgGANgFgGQgFgGgJAKIgZAJgAAYhlQAGgEAEgBIADAAIAAABQgIAGgDAAgAhmh1IABgEIAEgBIACADIAAAKQgGgCgBgGgAg/h8IAAgLQABgLAIgBQAMgCACASQAEANgPACIgDAAQgIAAgBgIgAhsiMIgCgFQgBgHAJgBIAGABIAAADIgBAJgAggiWQgBgKAkgmIADAEIgjAtIgCAAgAhDjGIAAgDQgBgGAPgRIAEABQAAAFgGALIgJAJgAiijNIAAgVIAFAAIABAHIgBAPgAghjdIAEgKIAGABIAAADIgIAIgAgFjqIACgJIgHAGIgCgFIACgFIAAAAIgEACIgEAAIgEgKIgCgJQgCADgEgBIACgNIAAAAIgIAOIgDAAIAEgXIABgDIgDAGIgEAEQgBAEgEAAIgDgCQASgrgBgJIABAAIABADQAQg1AMgUQADgBAAAEQgFAOgQA1IgKAdIAGgIIACABIgBALQADABAEAKIgDAKIAEAFIgCAMIAEAGIAHgEIACAFIAbgTQAPgJAHgJQAOgTAegaIACADQg1A7ABAFQgTAdgFABIgCAAIAOgXIgEAAIgaAYgABbkCIAKgPIAQgMQAEAAABAEIgHALQABADgGAFQgIAFgIABgAibkGIACgiQAEghAHgLIABACQADA1gGAWIgGgHIgEAMIgBAAgAjakfIgCgUIABgIIAFAAQAJAcACANQAAAHgCAEQgJgEgEgUgAg5khIgBgGIAIgUIAOgUIADAFIgJAZIgNARIgCAAgAB7ksIAHgJIAGABIAAACIgJAJgAAgk0IABgJIAGgGIAEAEIgEAIIgEADgAiSl4IgCgUIAEgCIAEABIAAAZg");
	this.shape_6.setTransform(-141.2,-99.3);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-178.9,-145.8,325.3,88.9);


(lib.shape3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,153,0,0.443)","rgba(255,204,0,0.412)","rgba(255,255,204,0.463)","rgba(255,250,184,0.431)","rgba(255,198,0,0.424)","rgba(255,158,0,0.471)"],[0,0.184,0.427,0.631,0.878,1],0,-43,0,43.1).s().p("AgGGuQgXgBgNh/QgOiAADiwQADiyASh9QASh+AUACQAXABAOB/QAOB/gDCwIAAAEQgDCwgSB8QgSB8gUAAIgBAAgAgIjUIgEAZIAAACIADADIAAACQgLBPgCBwQgCBxAJBQIAGAvIgCACQAIA4ALABQAPABAMhZQANhZACh/QACh9gJhaQgKhagPgBIAAAAQgQAAgKBYg");
	this.shape.setTransform(-173.4,-102.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-1.7,-1.6,-1.7,-1.6).s().p("AAIAdIgTgVIgNgYQgDgMAEgEQAFgEALAIQAJAHAKAOQAKALADANQAEAMgGAEIgDABQgFAAgHgFg");
	this.shape_1.setTransform(-128.5,-60.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-2,0.3,-2,0.3).s().p("AgXAJQgLgEABgFQAAgGAKgEIAXgDQAPAAAJAFQAKAEAAAFQAAAGgKAEIgYAEg");
	this.shape_2.setTransform(-100,-95.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-2,-0.4,-2,2.6).s().p("AgjAMQgCgGAJgGQAJgIAQgFIAZgFQAMABACAGQACAFgJAGQgJAIgPAFIgaAGQgMgBgCgGg");
	this.shape_3.setTransform(-114.9,-114.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-1,-2,-1,6.6).s().p("AgXAjQgFgDADgNQADgNALgNIATgXQALgIAFAEQAFADgDANQgEANgKANIgTAXQgIAFgEAAIgEgBg");
	this.shape_4.setTransform(-129.5,-142.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-32.6,1,-32.6,1).s().p("AmUAaQipgKACgQQgCgOCpgLQCngMDtAAQDrAACnAMQCnALADAOQgDAQinAKQinAMjrAAQjtAAingMg");
	this.shape_5.setTransform(-42.6,-98.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF33").s().p("AguGGIgFgLIgBgEIAEgBIAHAKIAFALIgCAFgACCFjIAGgFQASALABAJQAAAEgGAAQgRgIgCgLgAhOFWIgGgOIAAgEQAFADAFALQAGAKAHABIgEAEQgGgCgHgJgABJE0IgPgLQgmgiAAgGIAAgDIACACIgSgcQgYgagBgGIAAgCIgCgEIABgBIBGBCQA1AzABAEIAAACQAUAWABAHIgCADIACAFIgCADgAB4FcIABAAIgCgFIgNgIgAA8EeIAVAWIABgBIgWgVgABeEwQgWgchLhDgAhIFJIgLgbIgYg1IABgCIACgCQAKAOAUArQASAoAAAHIgBACQgHgEgIgSgAhnEVIAAgBIABAAIAKASIgBACIAAAAQgIAAgCgTgAheDzIACgGQAHgBADAMIgDAEQgKgGABgDgAivDfQgCgQAEgHIAHAOQAAAcgDAAIAAABQgFAAgBgUgAiCDKQAAgCAAAAQAAgBAAAAQABAAAAAAQAAAAAAABIACgBIAKAOIAFAOIgCAEQgNgGgDgXgADQDZIgHgFIAAgDIAEgBIAQANIgDACgACiDIQgNAAgjgVIglgUIADgBIgOgIIABgBIgRgMQAAgBAAgBQAAAAAAgBQABAAAAAAQAAAAAAABIBOAkQAyAaAAAGIgEAFgACkDFIAAABIALAGIgDgGIgBACQgDAAgEgDgAgpCcQgcgOgBgFQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAABgBIAYAQQAUAKARgEIgBAAIgDgEQgBgCAHgBIAEADIAMgRIgCgMIADgBQAEgBAEAEQAEAEABAFQAAAHgFALQgHARgMABIgCABQgPAAgagOgAB7CRIAFgGQADgBAHAIIgEAEIgCAAQgJAAAAgFgAhKBxIgBgEIAAgGIAHgCIAEAGIAAAFIgHABgAhzBfQgBgHAJgBQAJgCAAAJQABAIgLACIAAAAQgGAAgBgJgAgjBhQAAgEAEgCIAEAGIgEAEIAAAAQgEAAAAgEgACmBVQAAgCAAAAQAAgBAAAAQAAgBAAAAQABABAAAAIAJADIAAACIgFACIgBAAQgEAAAAgEgAB+BXIgGgEIgTgDIgIgCIAAABIgDACIgggDQgVgDgFgJIAMgJIgGgJIAFgFIAAgBIgZgYQgUgSgBgIIADgEQARALBJAeIgaAOIgCAHIAEAIQAAAHAOAEIAJADIAEgEQAIgCATAIIAZALIAAABQgCACgFAAgAA7AlIANgFIgGgCgAAFA6IABgCQAOADABAEIAAADIgDABQgFgBgIgIgACPAlQAAgFAEgDQAKAEAAADIgBAFQgNgBAAgDgAgoAfIgBgJIAFgCQAKgBABAIQAAAGgGABgAAohdIAlgyIgPgBIAEgEIgBgBIgRAKIgCgBIABgEIgDABIgKAFIgDgDIAFgGQgTgBgBgHIgDgMQAAgFAHgKIgHAAIAAgBIgBgCQgBgHAEgEIAEgEQgGgCAEgGIAGgIIgKAFIgDgBIAAgBIALgLIgNAFIgBgDIALgMIAQgLIACACIgHAJIAJgBIAAABIgIAJQAEABABACQgEAIgEACIAMABQAAADAGAAIgBABIgLAIIABACIgGAIIgBABIACACIgCAIQAEgBACgGIAFACIgHALIALALIASADIAEgCIACABIAJgFIACABIAfgOIAFAEIA0gfIANAAIAAADQg8AkgZAMIgEAHIAQgKIAGACQgUAIABAFIgIAMQgLAMgHACIAGADIAXAAQgGANgFgGQgFgGgJAKIgZAJgAAYhlQAGgEAEgBIADAAIAAABQgIAGgDAAgAhmh1IABgEIAEgBIACADIAAAKQgGgCgBgGgAg/h8IAAgLQABgLAIgBQAMgCACASQAEANgPACIgDAAQgIAAgBgIgAhsiMIgCgFQgBgHAJgBIAGABIAAADIgBAJgAggiWQgBgKAkgmIADAEIgjAtIgCAAgAhDjGIAAgDQgBgGAPgRIAEABQAAAFgGALIgJAJgAiijNIAAgVIAFAAIABAHIgBAPgAghjdIAEgKIAGABIAAADIgIAIgAgFjqIACgJIgHAGIgCgFIACgFIAAAAIgEACIgEAAIgEgKIgCgJQgCADgEgBIACgNIAAAAIgIAOIgDAAIAEgXIABgDIgDAGIgEAEQgBAEgEAAIgDgCQASgrgBgJIABAAIABADQAQg1AMgUQADgBAAAEQgFAOgQA1IgKAdIAGgIIACABIgBALQADABAEAKIgDAKIAEAFIgCAMIAEAGIAHgEIACAFIAbgTQAPgJAHgJQAOgTAegaIACADQg1A7ABAFQgTAdgFABIgCAAIAOgXIgEAAIgaAYgABbkCIAKgPIAQgMQAEAAABAEIgHALQABADgGAFQgIAFgIABgAibkGIACgiQAEghAHgLIABACQADA1gGAWIgGgHIgEAMIgBAAgAjakfIgCgUIABgIIAFAAQAJAcACANQAAAHgCAEQgJgEgEgUgAg5khIgBgGIAIgUIAOgUIADAFIgJAZIgNARIgCAAgAB7ksIAHgJIAGABIAAACIgJAJgAAgk0IABgJIAGgGIAEAEIgEAIIgEADgAiSl4IgCgUIAEgCIAEABIAAAZg");
	this.shape_6.setTransform(-141.2,-99.3);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-178.9,-145.8,193.5,88.9);


(lib.shape2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-6.7,-8.6,-6.7,-8.6).s().p("ABGBzQgkgrgthAIglgzIAgAgIBGBGQgbgmgXgnIAIALIA2BMIgBAGIAHAPQAHAIAGABIACADQAdAwgFAFIgBAAQgHAAghgogAhriLQADgCgBgDIgEgGIgCACIAAgGQAEgEAdAhIgVACg");
	this.shape.setTransform(-139.8,-76.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-7.2,0.2,-7.2,0.2).s().p("AAAAOIg8gFIgcgCQgmgGABgEQAAgHAlgCIBBgCIAXAAIBZAIQAkAFABAFQgBAGglADQgYACgdAAIgjgBg");
	this.shape_1.setTransform(-116.9,-96.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-9.7,1.9,-9.7,1.9).s().p("AAABBIAAgCIAAAAIAAgBIACAAIgFgQIAHgPIhHghIANAOIgBApIgBAMQgjgEgcgMQgygVAAgcQAAgcAygVQAWgIAZgFIAIAGIgEADIADAEIALgEQgXAMACAEIAmgCQAkgIAwgRIAFgCQAlAFAeAMQAyAVABAcQgBALgIALIhBACQgmADABAGQgBAGAlAGIAcACIgEACQguAThBACgAAzAoIgNADIAAADQAAAEAIAEIALgBIABgEQgBgJgFAAIgBAAgAh6AIQgGAAgCAJIgBAJQABANAMgCQAQgCAAgPQgCgMgNAAIgFAAgAgYhFIABAAIgIAFg");
	this.shape_2.setTransform(-135.4,-100.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-6.7,-2.2,-6.7,7.8).s().p("AhhAZIALgGIACgBIAKgEIAJgEQAbgKAjgNIAZgJIA6gQIAngCQACAGgiAQIgBABQggAPgsAOIgFACQgwARgkAIIgnACQgCgEAXgMg");
	this.shape_3.setTransform(-131.2,-108.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-5.5,-9.3,-5.5,26.9).s().p("AhlCWQgFgDAagvIAHgLIABgBIgGAKIAZADIgJALQgfAmgHAAIgBAAgAgRAPIAAgGIgHADIAAgBIANgSQAog+AigpQAigpAFACQAFAFgaAuIhFBqIgJAOIgHAIgAAcgXIACACIALgQIgBgCQgMAJAAAHg");
	this.shape_4.setTransform(-142.1,-124.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FF9900","#FFCC00","#FFFFCC","rgba(255,255,204,0)"],[0,0.345,0.792,1],-63.2,-1,60.8,-1).s().p("AnVCTIAOAAQAfALAdASIAQAJIg7g3IAFgBQgJgJABgMIAFgHQAIgFAJgCIAfgCIAFAAIgegRQBBgCAugTIAEgCIA9AGQA0ABAmgDQAkgDABgGQAAgGglgGIhYgIIgZAAQAIgLABgMQgBgbgygVQgegMglgFQAtgQAfgPIOJBDIlfA2IimANQhKABhOAQQhQAPhlABQg0AAgxAPQgTAGgDASQgIAxASAvQARAwAXAugAmFCTQAEgBABgCIABgBIgJgBgAnbDLQgGgNACgMIALAlgApjAAIAvhAIAJAAQATgBgEgSQAAgIgCgEIASgaQAOAOAIAWIAHAbIAAABQgZAFgWAIQgyAVAAAbQAAAdAyAVQAcAMAjAEQgDANgIAMQgMARgTAFIgMADgAm/hAIAegPIgcAAIAHgHIgLABIBUhCIhWAkIgNACIgGgRIgBgEIAFgKIAkgpQANgDAUgdIAAgEIgDAAIBFhTIgtDNIATACIgbAJQgjAMgbAMgAmHhoIgIADIAAAFIADABIAHgGIAAgCQABAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgCAAgAnaikIgJgFIADgQIAdgpIgWBGg");
	this.shape_5.setTransform(-93.1,-100.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF33").s().p("Ag7FoIgHgTQgBgGAFgBQAHAEABAJIABgEIAGAIIAFAXIgBAFIgDABQgFgDgIgRgAB+F0QgGgBgHgIIgHgPIABgGIAAgCQAZAHACAPQADAJgJABgAAXEEIgeggIhHhOIAUgCIAVgCIAMgCIAMgCQARgGAMgRQAIgLADgNIABgNIABgpIgNgQIBJAjIgJAQIAHAPIgCAAIAAABIAAABIAAABIAIAFIAeARIgFAAIgfACQgJACgIAFIgFAIQgBAMAJAIIgFABIA7A3IgQgJQgdgSgfgLIgOAAIgDAAIACAPIgDADIgGAOQgCALAGANIAHANIAHANQAXApAbAmgAiSCxIAHgWIAOAIQAPAGADAQIAfBxgAiXDqIgHhKIACgJIACAAIACAKIAEBJgACaDZQgBgHAHgBIADACIABAIIACAAQgCADgEAAQgGgBAAgEgAByCnIAJAAIgBABQgBACgEABgAhJCFIgBgEIAEgGIACgCIAEAGQABADgDACIgEABgAhwBxIABgIQADgIALgBQAIAAABAFQAEAVgRACIgBAAQgJAAgBgLgAB7BLIAAgDIANgCQAGgBABAJIgBAEIgLACQgIgFAAgEgAguA3IABgJQACgIAGgBQASgCACAOQAAAPgQACIgCAAQgKAAgBgLgAAPgYIAEgDIgIgGIAAgBIgHgbQgGgWgOgOIgTgNIAAgBIgZgCIAGgKIgBAAIgOAFIgCgKIgLABIABgQIgEgDIBli1IgkB9IAMgLIACANIAAABIAGgDIAAAFIAMAPIAJgIIAUgSIgRAqIADABIgBAEIgDARIAJAEIABAIIABAQIABAGIABAEIAGARIANgCIBWgjIhUBBIALgBIgHAHIAcABIgeAPIgHAEIgKAEIgDABIgKAGIgLAFgAg4goQgIgDgBgLIACgMQAEgNAMgCQAJgBAEALQACAEAAAIQAEASgTACgAhagrIAEgIIABABIACAGIgBADIgDABgAhghHIABgFIAFgFIAEABIADAHQAAAKgIABIAAAAQgEAAgBgJgABrhIIAAgFIAIgDQABAAABAAQABAAAAAAQAAAAAAABQAAAAgBAAIAAADIgHAFgAi0iCIABgFIACAAIAEARQgGgDgBgJgAiIiAIgHgLIAWhvQABAZAGAXQAIAlgPAdQgEAIgJAAIgCAAgAiriWIgEgQIgFghIgCgZIADAAIASBNIgBAJQgFgCgEgKgACiiOIAEgKQAEgHAHgBQABAAABAAQABAAAAAAQABAAAAAAQAAABgBAAIABAHQAHAIgYADgABKihIgGgEIANgQQAPgQAJgBIABABIADAAIAAAEQgUAdgNADgAAujsQAAgIAMgIIABABIgLAQgAh3kxQgBgGAEgCIACACIgDAYIAAAAgAAXlXIgBgCIAHgRIANgRIABABQgLAigGABg");
	this.shape_6.setTransform(-143.9,-103.4);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-162.2,-141.4,130.4,80.9);


(lib.shape1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-6.7,-8.6,-6.7,-8.6).s().p("ABGBzQgkgrgthAIglgzIAgAgIBGBGQgbgmgXgnIAIALIA2BMIgBAGIAHAPQAHAIAGABIACADQAdAwgFAFIgBAAQgHAAghgogAhriLQADgCgBgDIgEgGIgCACIAAgGQAEgEAdAhIgVACg");
	this.shape.setTransform(-139.8,-76.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-7.2,0.2,-7.2,0.2).s().p("AAAAOIg8gFIgcgCQgmgGABgEQAAgHAlgCIBBgCIAXAAIBZAIQAkAFABAFQgBAGglADQgYACgdAAIgjgBg");
	this.shape_1.setTransform(-116.9,-96.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-9.7,1.9,-9.7,1.9).s().p("AAABBIAAgCIAAAAIAAgBIACAAIgFgQIAHgPIhHghIANAOIgBApIgBAMQgjgEgcgMQgygVAAgcQAAgcAygVQAWgIAZgFIAIAGIgEADIADAEIAKgEQgWAMACAEIAmgCQAkgIAwgRIAFgCQAlAFAeAMQAyAVABAcQgBALgIALIhBACQgmADABAGQgBAGAlAGIAcACIgEACQguAThBACgAAzAoIgNADIAAADQAAAEAIAEIALgBIABgEQgBgJgFAAIgBAAgAh6AIQgGAAgCAJIgBAJQABANAMgCQAQgCAAgPQgCgMgNAAIgFAAgAgYhFIABAAIgIAFg");
	this.shape_2.setTransform(-135.4,-100.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-6.7,-2.2,-6.7,7.8).s().p("AhhAZIAAAAIALgGIACgBIAKgEIAJgEQAbgKAjgNIAZgJIA6gQIAngCQACAGgiAQIgBABQggAPgsAOIgFACQgwARgkAIIgnACQgCgEAXgMg");
	this.shape_3.setTransform(-131.2,-108.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FF9900","#FFCC00","#FFFFDF"],[0,0.345,0.945],-5.5,-9.3,-5.5,26.9).s().p("AhlCWQgFgDAagvIAHgLIABgBIgGAKIAZADIgJALQgfAmgHAAIgBAAgAgRAPIAAgGIgHADIAAgBIANgSQAog+AigpQAigpAFACQAFAFgaAuIhFBqIgJAOIgHAIgAAcgXIACACIALgQIgBgCQgMAJAAAHg");
	this.shape_4.setTransform(-142.1,-124.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FF9900","#FFCC00","#FFFFCC","rgba(255,255,204,0)"],[0,0.345,0.792,1],-63.2,-1,60.8,-1).s().p("AnVCTIAOAAQAfALAdASIAQAJIg7g3IAFgBQgJgJABgMIAFgHQAIgFAJgCIAfgCIAFAAIgegRQBBgCAugTIAEgCIA9AGQA0ABAmgDQAkgDABgGQAAgGglgGIhYgIIgZAAQAIgLABgMQgBgbgygVQgegMglgFQAtgQAfgPIOJBDIlfA2IimANQhKABhOAQQhQAPhlABQg0AAgxAPQgTAGgDASQgIAxASAvQARAwAXAugAmFCTQAEgBABgCIABgBIgJgBgAnbDLQgGgNACgMIALAlgApjAAIAvhAIAJAAQATgBgEgSQAAgIgCgEIASgaQAOAOAIAWIAHAbIAAABQgZAFgWAIQgyAVAAAbQAAAdAyAVQAcAMAjAEQgDANgIAMQgMARgTAFIgMADgAm/hAIAegPIgcAAIAHgHIgLABIBUhCIhWAkIgNACIgGgRIgBgEIAFgKIAkgpQANgDAUgdIAAgEIgDAAIBFhTIgtDNIATACIgbAJQgjAMgbAMgAmHhoIgIADIAAAFIADABIAHgGIAAgCQABAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgCAAgAnaikIgJgFIADgQIAdgpIgWBGg");
	this.shape_5.setTransform(-93.1,-100.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF33").s().p("Ag7FoIgHgTQgBgGAFgBQAHAEABAJIABgEIAGAIIAFAXIgBAFIgDABQgFgDgIgRgAB+F0QgGgBgHgIIgHgPIABgGIAAgCQAZAHACAPQADAJgJABgAAXEEIgeggIhHhOIAUgCIAVgCIAMgCIAMgCQARgGAMgRQAIgLADgNIABgNIABgpIgNgQIBJAjIgJAQIAHAPIgCAAIAAABIAAABIAAABIAIAFIAeARIgFAAIgfACQgJACgIAFIgFAIQgBAMAJAIIgFABIA7A3IgQgJQgdgSgfgLIgOAAIgDAAIACAPIgDADIgGAOQgCALAGANIAHANIAHANQAXApAbAmgAiSCxIAHgWIAOAIQAPAGADAQIAfBxgAiXDqIgHhKIACgJIACAAIACAKIAEBJgACaDZQgBgHAHgBIADACIABAIIACAAQgCADgEAAQgGgBAAgEgAByCnIAJAAIgBABQgBACgEABgAhJCFIgBgEIAEgGIACgCIAEAGQABADgDACIgEABgAhwBxIABgIQADgIALgBQAIAAABAFQAEAVgRACIgBAAQgJAAgBgLgAB7BLIAAgDIANgCQAGgBABAJIgBAEIgLACQgIgFAAgEgAguA3IABgJQACgIAGgBQASgCACAOQAAAPgQACIgCAAQgKAAgBgLgAAPgYIAEgDIgIgGIAAgBIgHgbQgGgWgOgOIgTgNIAAgBIgZgCIAGgKIgBAAIgOAFIgCgKIgLABIABgQIgEgDIBli1IgkB9IAMgLIACANIAAABIAGgDIAAAFIAMAPIAJgIIAUgSIgRAqIADABIgBAEIgDARIAJAEIABAIIABAQIABAGIABAEIAGARIANgCIBWgjIhUBBIALgBIgHAHIAcABIgeAPIgHAEIgKAEIgDABIgKAGIgBAAIgKAFgAg4goQgIgDgBgLIACgMQAEgNAMgCQAJgBAEALQACAEAAAIQAEASgTACgAhagrIAEgIIABABIACAGIgBADIgDABgAhghHIABgFIAFgFIAEABIADAHQAAAKgIABIAAAAQgEAAgBgJgABrhIIAAgFIAIgDQABAAABAAQABAAAAAAQAAAAAAABQAAAAgBAAIAAADIgHAFgAi0iCIABgFIACAAIAEARQgGgDgBgJgAiIiAIgHgLIAWhvQABAZAGAXQAIAlgPAdQgEAIgJAAIgCAAgAiriWIgEgQIgFghIgCgZIADAAIASBNIgBAJQgFgCgEgKgACiiOIAEgKQAEgHAHgBQABAAABAAQABAAAAAAQABAAAAAAQAAABgBAAIABAHQAHAIgYADgABKihIgGgEIANgQQAPgQAJgBIABABIADAAIAAAEQgUAdgNADgAAujsQAAgIAMgIIABABIgLAQgAh3kxQgBgGAEgCIACACIgDAYIAAAAgAAXlXIgBgCIAHgRIANgRIABABQgLAigGABg");
	this.shape_6.setTransform(-143.9,-103.4);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-162.2,-141.4,130.4,80.9);


(lib.Символ30 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ28();
	this.instance.setTransform(0.1,0,0.803,0.803,90);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-16.5,-8.4,33.1,16.9);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ30();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:20},4).to({y:0},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16.5,-8.4,33.1,16.9);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.setTransform(211.6,-339.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({x:101.6},0).wait(30).to({x:-113.4},0).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(195.1,-348.4,33,16.9);


(lib.Символ24 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ25();

	// Символ 26
	this.instance_1 = new lib.Символ26();
	this.instance_1.setTransform(-15,-0.6);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.7,-4.2,39.5,8.2);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ21();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:80},19).to({x:0},20).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-3.1,15.9,6.2);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ20();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-10},9).to({x:0},10).to({x:5,y:-5},10).to({x:0,y:0},10).to({x:4,y:5},10).to({x:0,y:0},10).to({x:-3.5,y:6.5},10).to({x:0,y:0},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.6,-6.6,13.2,13.2);


(lib.Символ18 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ17();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13.4,-6.5,22.5,11.8);


(lib.Символ13 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ15();

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(2,1,1).p("AiEi4ICEiFICACBACHC3IiHCHIh+iAAC7iCICDCCIh7B7Ai1CHIiIiHICAh/");

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-32.8,-32.8,65.6,65.6);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ11();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.13,scaleY:1.13},9).to({scaleX:1,scaleY:1},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-88,-6,168.2,12);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Dummy Layer
	this.instance = new lib.shape232("synched",0);
	this.instance.setTransform(256,161.3,1,1,0,0,0,7.6,-76);

	this.instance_1 = new lib.shape233("synched",0);
	this.instance_1.setTransform(258.3,161.5,1,1,0,0,0,9.9,-75.8);

	this.instance_2 = new lib.shape234("synched",0);
	this.instance_2.setTransform(258.3,161.1,1,1,0,0,0,9.9,-76.2);

	this.instance_3 = new lib.shape235("synched",0);
	this.instance_3.setTransform(259.1,154.3,1,1,0,0,0,10.7,-83);

	this.instance_4 = new lib.shape236("synched",0);
	this.instance_4.setTransform(259,154.3,1,1,0,0,0,10.6,-83);

	this.instance_5 = new lib.shape237("synched",0);
	this.instance_5.setTransform(259.2,155.3,1,1,0,0,0,10.8,-82);

	this.instance_6 = new lib.shape238("synched",0);
	this.instance_6.setTransform(258.7,153.9,1,1,0,0,0,10.3,-83.4);

	this.instance_7 = new lib.shape239("synched",0);
	this.instance_7.setTransform(259,153.9,1,1,0,0,0,10.6,-83.4);

	this.instance_8 = new lib.shape240("synched",0);
	this.instance_8.setTransform(259.6,156.5,1,1,0,0,0,11.2,-80.8);

	this.instance_9 = new lib.shape241("synched",0);
	this.instance_9.setTransform(259.3,157.6,1,1,0,0,0,10.9,-79.7);

	this.instance_10 = new lib.shape242("synched",0);
	this.instance_10.setTransform(247.7,156.6,1,1,0,0,0,-0.7,-80.7);

	this.instance_11 = new lib.shape243("synched",0);
	this.instance_11.setTransform(248.3,156.1,1,1,0,0,0,-0.1,-81.2);

	this.instance_12 = new lib.shape244("synched",0);
	this.instance_12.setTransform(253.5,157.5,1,1,0,0,0,5.1,-79.8);

	this.instance_13 = new lib.shape245("synched",0);
	this.instance_13.setTransform(254.2,161.2,1,1,0,0,0,5.8,-76.1);

	this.instance_14 = new lib.shape246("synched",0);
	this.instance_14.setTransform(254.8,164.2,1,1,0,0,0,6.4,-73.1);

	this.instance_15 = new lib.shape247("synched",0);
	this.instance_15.setTransform(254.4,169.1,1,1,0,0,0,6,-68.2);

	this.instance_16 = new lib.shape248("synched",0);
	this.instance_16.setTransform(253.8,170.4,1,1,0,0,0,5.4,-66.9);

	this.instance_17 = new lib.shape249("synched",0);
	this.instance_17.setTransform(254.3,172.3,1,1,0,0,0,5.9,-65);

	this.instance_18 = new lib.shape250("synched",0);
	this.instance_18.setTransform(253.7,176.5,1,1,0,0,0,5.3,-60.8);

	this.instance_19 = new lib.shape251("synched",0);
	this.instance_19.setTransform(253.9,179.1,1,1,0,0,0,5.5,-58.2);

	this.instance_20 = new lib.shape252("synched",0);
	this.instance_20.setTransform(254.4,182.1,1,1,0,0,0,6,-55.2);

	this.instance_21 = new lib.shape253("synched",0);
	this.instance_21.setTransform(254.9,186.8,1,1,0,0,0,6.5,-50.5);

	this.instance_22 = new lib.shape254("synched",0);
	this.instance_22.setTransform(254.8,190.4,1,1,0,0,0,6.4,-46.9);

	this.instance_23 = new lib.shape255("synched",0);
	this.instance_23.setTransform(241.2,189.6,1,1,0,0,0,-7.2,-47.7);

	this.instance_24 = new lib.shape256("synched",0);
	this.instance_24.setTransform(243.5,190.1,1,1,0,0,0,-4.9,-47.2);

	this.instance_25 = new lib.shape257("synched",0);
	this.instance_25.setTransform(236.8,193.7,1,1,0,0,0,-11.6,-43.6);

	this.instance_26 = new lib.shape258("synched",0);
	this.instance_26.setTransform(236.7,195.8,1,1,0,0,0,-11.7,-41.5);

	this.instance_27 = new lib.shape259("synched",0);
	this.instance_27.setTransform(246.2,202.3,1,1,0,0,0,-2.2,-35);

	this.instance_28 = new lib.shape260("synched",0);
	this.instance_28.setTransform(245.8,203.2,1,1,0,0,0,-2.6,-34.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_5}]},1).to({state:[{t:this.instance_6}]},1).to({state:[{t:this.instance_7}]},1).to({state:[{t:this.instance_8}]},1).to({state:[{t:this.instance_9}]},1).to({state:[{t:this.instance_10}]},1).to({state:[{t:this.instance_11}]},1).to({state:[{t:this.instance_12}]},1).to({state:[{t:this.instance_13}]},1).to({state:[{t:this.instance_14}]},1).to({state:[{t:this.instance_15}]},1).to({state:[{t:this.instance_16}]},1).to({state:[{t:this.instance_17}]},1).to({state:[{t:this.instance_18}]},1).to({state:[{t:this.instance_19}]},1).to({state:[{t:this.instance_20}]},1).to({state:[{t:this.instance_21}]},1).to({state:[{t:this.instance_22}]},1).to({state:[{t:this.instance_23}]},1).to({state:[{t:this.instance_24}]},1).to({state:[{t:this.instance_25}]},1).to({state:[{t:this.instance_26}]},1).to({state:[{t:this.instance_27}]},1).to({state:[{t:this.instance_28}]},1).to({state:[]},1).wait(21));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(166.6,81.8,178.8,158.9);


(lib.Symbol26 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Symbol36();
	this.instance.setTransform(66.8,11.6,1,1,0,0,0,66.8,11.6);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.9,-3,142,33);


(lib.sprite110 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape109("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,58,58);


(lib.sprite11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shape1("synched",0);

	this.instance_1 = new lib.shape2("synched",0);

	this.instance_2 = new lib.shape3("synched",0);

	this.instance_3 = new lib.shape4("synched",0);

	this.instance_4 = new lib.shape5("synched",0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_4}]},1).to({state:[]},1).wait(35));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-162.2,-141.4,130.4,80.9);


(lib.Symbol16 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Tween22("synched",0);
	this.instance.setTransform(30,30);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,60,60);


(lib.Символ14 = function() {
	this.initialize();

	// Слой 3
	this.instance = new lib.Символ18();
	this.instance.setTransform(105,11.6);

	// Слой 4
	this.instance_1 = new lib.Символ22();
	this.instance_1.setTransform(-136.5,7.4);

	// Слой 2
	this.instance_2 = new lib.Символ19();
	this.instance_2.setTransform(-0.2,-0.4);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(51,51,255,0.498)").s().p("AgmAnQgRgQAAgXQAAgWARgQQARgQAVAAQAXAAAQAQQAQAQAAAWQAAAXgQAQQgQAQgXAAQgVAAgRgQg");
	this.shape.setTransform(-0.2,-0.4);

	// Слой 1
	this.instance_3 = new lib.Символ16();
	this.instance_3.setTransform(-99.7,-2.9);

	this.instance_4 = new lib.Символ16();
	this.instance_4.setTransform(101.9,-3);

	this.instance_5 = new lib.Символ13();

	this.addChild(this.instance_5,this.instance_4,this.instance_3,this.shape,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-157.7,-32.8,317.7,65.6);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.setTransform(2.2,1.9,0.843,0.843,0,0,0,258.6,163.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},49).wait(11).to({_off:false,scaleX:0.4,scaleY:0.4,x:-357.3,y:-4.1},0).to({_off:true},49).wait(11).to({_off:false,regY:163.4,scaleX:0.2,scaleY:0.2,x:-127.5,y:-70.4},0).to({_off:true},49).wait(10).to({_off:false,regY:163.3,scaleX:0.14,scaleY:0.14,x:-359.5,y:-87.4},0).to({_off:true},50).wait(10).to({_off:false,regX:258.5,scaleX:0.12,scaleY:0.12,x:-72.2,y:-121.5},0).to({_off:true},50).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.4,-67,150.8,134);


(lib.Символ2 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.sprite11();
	this.instance.setTransform(413.6,243.7,1.026,1.026);
	this.instance.shadow = new cjs.Shadow("#FFB500",0,0,7);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(243.2,94.6,145,95);


(lib.sprite112 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol16();
	this.instance.setTransform(1.5,21.8,0.85,0.85,0,0,0,30,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({guide:{path:[1.5,21.7,1.5,21.3,1.5,20.9,1.5,15.3,5.6,11.2,9.7,7.1,15.3,7.1,21.1,7.1,25.2,11.2,29.3,15.3,29.3,20.9,29.3,26.7,25.2,30.8,21.1,34.9,15.3,34.9,9.7,34.9,5.6,30.8,3.3,28.5,2.3,25.7]}},29).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24,-3.7,51,51);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(2,1,1).p("AjhibIHDAAIAAE3InDAAg");
	this.shape.setTransform(472.1,-536.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,0,0,0.498)").s().p("AjhCcIAAk3IHDAAIAAE3g");
	this.shape_1.setTransform(472.1,-536.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(2));

	// Слой 1
	this.instance = new lib.Символ14();
	this.instance.setTransform(-1.1,0,0.803,0.803);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(448.4,-553.1,47.4,33.3);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ2();
	this.instance.setTransform(37.4,-51.9,0.148,0.148,-132,0,0,316,140.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},40).wait(15).to({_off:false,regX:315.9,regY:139.6,scaleX:0.12,scaleY:0.12,x:-6.4,y:-49.3},0).to({_off:true},41).wait(13).to({_off:false,regY:139.7,scaleX:0.13,scaleY:0.13,x:-100.4,y:-51.4},0).to({_off:true},41).wait(16));

	// Слой 5
	this.instance_1 = new lib.Символ3();
	this.instance_1.setTransform(-89.1,-39.5,0.087,0.087);
	this.instance_1.alpha = 0.699;

	this.instance_2 = new lib.Символ3();
	this.instance_2.setTransform(3.6,-38.4,0.072,0.072);
	this.instance_2.alpha = 0.641;

	this.instance_3 = new lib.Символ3();
	this.instance_3.setTransform(50.1,-38.4,0.109,0.109);
	this.instance_3.alpha = 0.699;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]},39).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]},1).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]},15).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]},40).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]},14).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]},56).wait(1));

	// Слой 1
	this.instance_4 = new lib.back();
	this.instance_4.setTransform(-330.5,-156.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(166));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-330.5,-156.5,661,313);


(lib.sprite113 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.sprite112();
	this.instance.setTransform(11.6,6.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30));

	// Layer 1
	this.instance_1 = new lib.sprite110();
	this.instance_1.setTransform(-8.7,-8.7,1.316,1.316);
	this.instance_1.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.5,-10.6,78.2,76.3);


(lib.Символ5копия = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ27();
	this.instance.setTransform(453.6,161.1);

	// Слой 4
	this.instance_1 = new lib.Символ24();
	this.instance_1.setTransform(340.1,-133.6,0.721,0.721);

	this.instance_2 = new lib.Символ24();
	this.instance_2.setTransform(557.8,-128.9,0.62,0.62,0,0,0,0,-0.1);

	this.instance_3 = new lib.Символ24();
	this.instance_3.setTransform(666,-137.6,0.855,0.855);

	// Слой 6
	this.instance_4 = new lib.for_09();
	this.instance_4.setTransform(235,-36.9);

	// expl
	this.instance_5 = new lib.Символ8();
	this.instance_5.setTransform(859.9,43);

	// Слой 3
	this.instance_6 = new lib.Символ4();
	this.instance_6.setTransform(551.7,-18.2,2.344,2.344);

	this.addChild(this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-222.9,-385,1549.2,733.6);


(lib.Символ5 = function() {
	this.initialize();

	// Слой 6
	this.instance = new lib.for_09();
	this.instance.setTransform(235,-36.9);

	// Слой 4
	this.instance_1 = new lib.for_14();
	this.instance_1.setTransform(218.5,-62.6);

	// expl
	this.instance_2 = new lib.Символ8();
	this.instance_2.setTransform(722.3,-33.4);

	// Слой 3
	this.instance_3 = new lib.Символ4();
	this.instance_3.setTransform(509.5,-84.5);

	this.addChild(this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(179,-241,661,453.4);


(lib.Символ9_1 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.Symbol26();
	this.instance.setTransform(-92.9,0.6,1,1,0,0,0,66.8,11.6);

	// Слой 1
	this.cir = new lib.sprite113();
	this.cir.setTransform(0.1,0.1,0.499,0.499,0,0,0,27.6,27.6);

	this.addChild(this.cir,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-162.7,-19,181.8,38.1);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ5копия();
	this.instance.setTransform(-551.7,18.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(10).to({y:12},0).wait(1).to({y:21.3},0).wait(1).to({x:-556.3,y:18.2},0).wait(1).to({x:-548.6,y:15.1},0).wait(1).to({x:-551.7,y:18.2},0).wait(48).to({y:12},0).wait(1).to({y:21.3},0).wait(1).to({x:-556.3,y:18.2},0).wait(1).to({x:-548.6,y:15.1},0).wait(1).to({x:-551.7,y:18.2},0).wait(40).to({y:12},0).wait(1).to({y:21.3},0).wait(1).to({x:-556.3,y:18.2},0).wait(1).to({x:-548.6,y:15.1},0).wait(1).to({x:-551.7,y:18.2},0).wait(77).to({y:12},0).wait(1).to({y:21.3},0).wait(1).to({x:-556.3,y:18.2},0).wait(1).to({x:-548.6,y:15.1},0).wait(1).to({x:-551.7,y:18.2},0).wait(51));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-774.6,-366.8,1549.2,733.6);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ9_1();
	this.instance.setTransform(173.3,-145.3,0.612,0.612);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(300));

	// Слой 3
	this.instance_1 = new lib.Символ10();
	this.instance_1.setTransform(136.4,-173.4,1.865,1.865);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(300));

	// Слой 2
	this.instance_2 = new lib.Символ9();
	this.instance_2.setTransform(107.5,-61.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(7).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false},0).to({_off:true},1).wait(108).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false},0).to({_off:true},1).wait(112).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false},0).to({_off:true},1).wait(58));

	// Слой 1
	this.instance_3 = new lib.Символ5();
	this.instance_3.setTransform(-400.1,25.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(8).to({y:21.9},0).wait(1).to({y:29.9},0).wait(1).to({x:-398.1,y:23.9},0).wait(1).to({x:-403.1,y:22.9},0).wait(1).to({x:-400.1,y:25.9},0).wait(49).to({y:21.9},0).wait(1).to({y:29.9},0).wait(1).to({x:-398.1,y:23.9},0).wait(1).to({x:-403.1,y:22.9},0).wait(1).to({x:-400.1,y:25.9},0).wait(56).to({y:21.9},0).wait(1).to({y:29.9},0).wait(1).to({x:-398.1,y:23.9},0).wait(1).to({x:-403.1,y:22.9},0).wait(1).to({x:-400.1,y:25.9},0).wait(55).to({y:21.9},0).wait(1).to({y:29.9},0).wait(1).to({x:-398.1,y:23.9},0).wait(1).to({x:-403.1,y:22.9},0).wait(1).to({x:-400.1,y:25.9},0).wait(54).to({y:21.9},0).wait(1).to({y:29.9},0).wait(1).to({x:-398.1,y:23.9},0).wait(1).to({x:-403.1,y:22.9},0).wait(1).to({x:-400.1,y:25.9},0).wait(58));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-221.1,-215.1,661,453.4);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 1
	this.instance = new lib.Символ7();
	this.instance.setTransform(-83.3,-40.9,1,1,0,0,0,-83.3,-40.9);

	this.instance_1 = new lib.Символ12();
	this.instance_1.setTransform(151.6,7.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-221.1,-215.1,661,453.4);


// stage content:



(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		stage.canvas.style.cursor = "none";
		this.pricel.mouseEnabled = false;
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
			this.pricel.x = stage.mouseX;
			this.pricel.y = stage.mouseY;
		}
		
		
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(link1, "_blank");
		}
		var _this = this;
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		function fl_MouseOverHandler_5()
		    {
			    _this.main.gotoAndStop(1);
				_this.pricel.gotoAndPlay(2);
			    
		    }
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		
		function fl_MouseOutHandler_2()
		    {
			    _this.main.gotoAndStop(0);
				_this.pricel.gotoAndPlay(0);
			  
		    }
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 8
	this.pricel = new lib.Символ23();
	this.pricel.setTransform(-288.4,128.5);

	this.timeline.addTween(cjs.Tween.get(this.pricel).wait(1));

	// Слой 7
	this.main = new lib.Символ6();
	this.main.setTransform(81.4,163.7,1,1,0,0,0,-83.3,-40.9);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(243.6,-274.7,661,867.6);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;