(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 685,
	fps: 24,
	color: "#000000",
	manifest: [
		{src:"images/aaa.png?1460727211194", id:"aaa"},
		{src:"images/aaa10.png?1460727211194", id:"aaa10"},
		{src:"images/aaa11.png?1460727211194", id:"aaa11"},
		{src:"images/aaa12.png?1460727211194", id:"aaa12"},
		{src:"images/aaa13.png?1460727211194", id:"aaa13"},
		{src:"images/aaa14.png?1460727211194", id:"aaa14"},
		{src:"images/aaa2.png?1460727211194", id:"aaa2"},
		{src:"images/aaa3.png?1460727211194", id:"aaa3"},
		{src:"images/aaa4.png?1460727211194", id:"aaa4"},
		{src:"images/aaa5.png?1460727211194", id:"aaa5"},
		{src:"images/aaa6.png?1460727211194", id:"aaa6"},
		{src:"images/aaa7.png?1460727211194", id:"aaa7"},
		{src:"images/aaa8.png?1460727211194", id:"aaa8"},
		{src:"images/aaa9.png?1460727211194", id:"aaa9"},
		{src:"images/bg1.jpg?1460727211194", id:"bg1"},
		{src:"images/big.png?1460727211194", id:"big"},
		{src:"images/btn.png?1460727211194", id:"btn"},
		{src:"images/bullet.png?1460727211194", id:"bullet"},
		{src:"images/circle1.png?1460727211194", id:"circle1"},
		{src:"images/circle2.png?1460727211194", id:"circle2"},
		{src:"images/frame.png?1460727211194", id:"frame"},
		{src:"images/gun.png?1460727211194", id:"gun"},
		{src:"images/health.png?1460727211194", id:"health"},
		{src:"images/hp.png?1460727211194", id:"hp"},
		{src:"images/title.png?1460727211194", id:"title"}
	]
};



// symbols:



(lib.aaa = function() {
	this.initialize(img.aaa);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,255,216);


(lib.aaa10 = function() {
	this.initialize(img.aaa10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,103,100);


(lib.aaa11 = function() {
	this.initialize(img.aaa11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,70,107);


(lib.aaa12 = function() {
	this.initialize(img.aaa12);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,22,22);


(lib.aaa13 = function() {
	this.initialize(img.aaa13);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,24,15);


(lib.aaa14 = function() {
	this.initialize(img.aaa14);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,27,17);


(lib.aaa2 = function() {
	this.initialize(img.aaa2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,34,63);


(lib.aaa3 = function() {
	this.initialize(img.aaa3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,55,70);


(lib.aaa4 = function() {
	this.initialize(img.aaa4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,53,76);


(lib.aaa5 = function() {
	this.initialize(img.aaa5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,73,56);


(lib.aaa6 = function() {
	this.initialize(img.aaa6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,133,48);


(lib.aaa7 = function() {
	this.initialize(img.aaa7);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,71,54);


(lib.aaa8 = function() {
	this.initialize(img.aaa8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,107,84);


(lib.aaa9 = function() {
	this.initialize(img.aaa9);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,117);


(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1178,814);


(lib.big = function() {
	this.initialize(img.big);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,403,148);


(lib.btn = function() {
	this.initialize(img.btn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,332,90);


(lib.bullet = function() {
	this.initialize(img.bullet);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,42,43);


(lib.circle1 = function() {
	this.initialize(img.circle1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,338,338);


(lib.circle2 = function() {
	this.initialize(img.circle2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,338,338);


(lib.frame = function() {
	this.initialize(img.frame);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,180,16);


(lib.gun = function() {
	this.initialize(img.gun);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,504,304);


(lib.health = function() {
	this.initialize(img.health);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,179,14);


(lib.hp = function() {
	this.initialize(img.hp);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,810,567);


(lib.title = function() {
	this.initialize(img.title);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,478,73);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("ApQBMIAAiXIEVAAIAACXg");
	var mask_graphics_1 = new cjs.Graphics().p("AoiBMIAAiXIEUAAIAACXg");
	var mask_graphics_2 = new cjs.Graphics().p("An0BMIAAiXIEUAAIAACXg");
	var mask_graphics_3 = new cjs.Graphics().p("AnHBMIAAiXIEUAAIAACXg");
	var mask_graphics_4 = new cjs.Graphics().p("AmZBMIAAiXIEUAAIAACXg");
	var mask_graphics_5 = new cjs.Graphics().p("AlsBMIAAiXIEUAAIAACXg");
	var mask_graphics_6 = new cjs.Graphics().p("Ak+BMIAAiXIEUAAIAACXg");
	var mask_graphics_7 = new cjs.Graphics().p("AkRBMIAAiXIESAAIAACXg");
	var mask_graphics_8 = new cjs.Graphics().p("AjjBMIAAiXIESAAIAACXg");
	var mask_graphics_9 = new cjs.Graphics().p("Ai2BMIAAiXIESAAIAACXg");
	var mask_graphics_10 = new cjs.Graphics().p("AiIBMIAAiXIERAAIAACXg");
	var mask_graphics_11 = new cjs.Graphics().p("AiIBMIAAiXIERAAIAACXg");
	var mask_graphics_12 = new cjs.Graphics().p("AiIBMIAAiXIERAAIAACXg");
	var mask_graphics_13 = new cjs.Graphics().p("AiJBMIAAiXIESAAIAACXg");
	var mask_graphics_14 = new cjs.Graphics().p("AhcBMIAAiXIESAAIAACXg");
	var mask_graphics_15 = new cjs.Graphics().p("AgvBMIAAiXIESAAIAACXg");
	var mask_graphics_16 = new cjs.Graphics().p("AgBBMIAAiXIESAAIAACXg");
	var mask_graphics_17 = new cjs.Graphics().p("AAqBMIAAiXIEUAAIAACXg");
	var mask_graphics_18 = new cjs.Graphics().p("ABYBMIAAiXIEUAAIAACXg");
	var mask_graphics_19 = new cjs.Graphics().p("ACFBMIAAiXIEUAAIAACXg");
	var mask_graphics_20 = new cjs.Graphics().p("ACzBMIAAiXIEUAAIAACXg");
	var mask_graphics_21 = new cjs.Graphics().p("ADgBMIAAiXIEUAAIAACXg");
	var mask_graphics_22 = new cjs.Graphics().p("AEOBMIAAiXIEUAAIAACXg");
	var mask_graphics_23 = new cjs.Graphics().p("AE8BMIAAiXIEUAAIAACXg");
	var mask_graphics_35 = new cjs.Graphics().p("AE8BMIAAiXIEUAAIAACXg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-59.3,y:0}).wait(1).to({graphics:mask_graphics_1,x:-54.7,y:0}).wait(1).to({graphics:mask_graphics_2,x:-50.2,y:0}).wait(1).to({graphics:mask_graphics_3,x:-45.6,y:0}).wait(1).to({graphics:mask_graphics_4,x:-41.1,y:0}).wait(1).to({graphics:mask_graphics_5,x:-36.5,y:0}).wait(1).to({graphics:mask_graphics_6,x:-32,y:0}).wait(1).to({graphics:mask_graphics_7,x:-27.4,y:0}).wait(1).to({graphics:mask_graphics_8,x:-22.9,y:0}).wait(1).to({graphics:mask_graphics_9,x:-18.3,y:0}).wait(1).to({graphics:mask_graphics_10,x:-13.8,y:0}).wait(1).to({graphics:mask_graphics_11,x:-4.7,y:0}).wait(1).to({graphics:mask_graphics_12,x:4.5,y:0}).wait(1).to({graphics:mask_graphics_13,x:13.6,y:0}).wait(1).to({graphics:mask_graphics_14,x:18.2,y:0}).wait(1).to({graphics:mask_graphics_15,x:22.8,y:0}).wait(1).to({graphics:mask_graphics_16,x:27.3,y:0}).wait(1).to({graphics:mask_graphics_17,x:31.9,y:0}).wait(1).to({graphics:mask_graphics_18,x:36.4,y:0}).wait(1).to({graphics:mask_graphics_19,x:41,y:0}).wait(1).to({graphics:mask_graphics_20,x:45.5,y:0}).wait(1).to({graphics:mask_graphics_21,x:50.1,y:0}).wait(1).to({graphics:mask_graphics_22,x:54.6,y:0}).wait(1).to({graphics:mask_graphics_23,x:59.2,y:0}).wait(12).to({graphics:mask_graphics_35,x:59.2,y:0}).wait(1));

	// Слой 1
	this.instance = new lib.health();
	this.instance.setTransform(-89.4,-6.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ANBBEIgFgDIgCgDIgdhzIggA1IgCAAIgBAAIjlAAIgwBEQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgCgBIgFgDIgCgDIgdhzIggA1IgCAAIgBAAIjqAAIgrBEIAAAAIgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgCgBIgFgDIgCgDIgdhzIggA1IgCAAIgBAAIjoAAIgrBEQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgCgBIgFgDIgCgDIgdhzIggA1IgCAAIgBAAIjqAAIgrBEIAAAAIgBAAQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgCgBIgFgDIgCgDIgdhzIggA1IgCAAIgBAAIjwAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAIgBgEIABgDIAEgBIDuAAIAhg5IAAgDIABAAIADAAIACABIAAABIADACIADABIAdB0IAkg4IAAgBIABgDIAEgBIDuAAIAhg5IAAgDIABAAIADAAIACABIAAABIADACIADABIAdB0IAkg4IAAgBIABgDIAEgBIDsAAIAhg5IAAgDIABAAIADAAIACABIAAABIADACIADABIAdB0IAkg4IAAgBIABgDIAEgBIDuAAIAhg5IAAgDIABAAIADAAIACABIAAABIADACIADABIAdB0IAkg4IAAgBIABgDIAEgBIDuAAIAhg5IAAgDIABAAIADAAIACABIAAABIADACIADABIAdB0IAkg4IAAgBIABgDIAEgBIATAAIAAAIIgNAAIgrBEIAAAAIgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgCgBg");

	this.instance.mask = this.shape.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape}]},35).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.btn();
	this.instance.setTransform(-166,-44);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-166,-44,332,90);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.bg1();
	this.instance.setTransform(-591.9,-340.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-591.9,-340.9,1178,814);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.hp();
	this.instance.setTransform(-415.3,-274.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-415.3,-274.3,810,567);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bullet();
	this.instance.setTransform(-21,-21.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21,-21.5,42,43);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.gun();
	this.instance.setTransform(-252,-152);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-252,-152,504,304);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AZfFmIgDgHIADgDIgBgEIAEAAIABAEIABAAIAAADIABAAIAAAEIgBADIgCAAIgDABgAZ0FYIgEAAIgFAAIgCgDIAAgEIADgDIAFACIAFAIgAabFWIAAgDIADABIAAABIgBAAIgBABgAaDFJIAAgDIADAAIAAADgAaRE1IgCAAIgDgEIgCgFIAKADIABADIgBAAIgCADIgBAAgAZXEvIgCgCIAAgDIAAgDIACgDIAFAAIACADIABAGIgDABIAAABgAZBEoIABgDIABgFIgEAAIAAAAIgDAAIABgFIABAAIAAgFIABAAIACgCIABgDIAJABIABACIAAABIACAAIAAADIACAGIgCAHIgMAEgAaNEgIgCgGIAEgCIAHACIgDAGIgDAAIgDAAgAYSEgIAAgCIABgCIABAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAABIgBABgAYXEcIgCgBIgBgBIgBAAIgEgDIAAgGIACgBIAAgBIAFgEIAGAAIABAEIABAAIAAACIABAAIAAAEIABABIAAABIgBAAIgBADIgCAAIAAABIAAABIgCABIgDAAgAX2EPIAAgCIAAgFIAAAAIgFADIABgEIABgFIAGgCIAFABIABABIAAABIACABIABACIABACIAAACIgBABIgBACIgCABIAAABIgBAAIgEABIgEgBgAYoEBIAAgBIgBAAIAAgEIAEgBIABAEIgBABIAAABgAX7D+IgFgCIgCgGIgBAAIAAgGIABAAIAAgDIACAAIAAgBIAFgEIAIABIADAHIACAJIgBAAIAAACIgDACIAAABIgDAAIAAABgAVyD9IgDgHQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIAAgEIADAAQAAAAAAABQAAABAAAAQABABAAAAQAAABAAAAIABAAIAAADIABAAIABAEIgCADIgCABIgCAAgAacD9IAAgHIABAAIAAgDIgDgBQgCABAAAAQgBAAgBAAQAAAAgBAAQAAgBAAAAIAAgHIABgBIAAgBIADgBIACgBIhUAAIAAgNIACABIABADIAEAAIAEgCIAAgEIgCgEIgGAAIgBACIgCACIAHmJIhYGLIACAAIABABIABAAIABADIAAADIgFAAIgBgCIgCAIIgyAAIgYhpIBggPIhkgEIgVhiIAsAAIgtgDIgni3IgDAAIAFC0IhSgDIAAjZICGAAIAtDRQAJArAHA6IAFg2IAWhuIA5gMIg2gCIAdiEICFAAIAAHAIABAAIABADIACAAIAAgBIgBgBIgBgBIABgBIAAAAIABAAIAAABIAEAAIAAABIABACQAAAAAAAAQAAABAAAAQAAAAAAABQABAAAAAAIABABIABAAIABABIABABIACAAIAAABIACACIABABIgCAAIAAADIgBAAIAAABIgCABIgDABIAAADIgDgCIgFAAIAAABIgBACgAakDzIABAAIAAgBIgBAAgAagDuIABABIABAAIgBgCIgBAAIAAABgAXmDYIAAACIABABIACABIAAgFIgCAAIAAABIgBAAIAAAAgAXSDQIgBADIgBADIACAAIAAACIABACIAHgBIABgBIABgCIgCAAIAAgEIgCgCgAXvDOIgBACIABACIABABIABABIABAAIAEgCIgCgDIgBgDIgEAAIAAACgAXdDHIAAACIAAAAIABABIABABIAAgCIABAAIAAgBIgBgBIgCgBIAAABgAXQDGIAEAAIABgBIAAgDIAAgDIgFAAgAXiC+IACAAIABADIACAAIACgCIAAgBIAAgBIgBgDIgEAAIgCAEgAWqiLIgBABIAAABIABACIAAABIAEgBIAAgBIABgBIgBgBIgCgBIgBAAgAWYjOIgCACIABABIABACIADAAIACgBIABgBIABgBIgCgCIgDgCIgCACgAY5D8IAAgCIAAgBIgOgCIAAgBIgDgCQAAgBAAAAQgBAAAAAAQgBgBgBAAQAAAAgBAAIgDAEIgCgBIgCAAIAAgCIgFAAIgEgBIgBgEIAEgBIAAABIADAAQgBgEgGABIgLABIgCgEIAAgFIABgBIAAgBIAFgBIAFgCIACAAIAAgBIABgCIAAAAIACgBIAAgCIAGgCIAAADIAAAAIAEACIAGAAIAAABIACAAIAAABIACAAIAAABIADABIADACIAAAAIAMAAIAFACIAEACIAEAGIABAKIAAAAIAAABIgGAFIgFABgAKHDqQgtgbgHg/IgDgfIAAAAIAAgBIACgCIAFAAIABADIBFgGIAAgFIAJAAIACADIAAADIgBABIgBABIgDABIABAOIACgCIACAAIAAAAIABACIgBABIAAAAIgBADIgBACQADAUAGALQANAVAXADIgBgCIAAgEQAEgCAAgHIAEAAIgBADIAAADIACACIABAEIgCAAIgBADIAKAAQAPgCALgGQAKgGAHgMQALgUgCgdQgDgkgUgTQgSgTggADIgqAEIgFhAIAngEQAPgBALgFQAKgFAIgJQAOgTgDgjQgDgYgNgQIAHABQgOgMgXACQgTACgMALIgQAAIgHAMQgGARACAdIhRAIIgCgcQgCgXAHgVIAOABQAFgOAKgLIDNgCIAXAHIAHANIAAAAIAFgBIADgBIAAACIgEAAIAAACIgCAAIAAACIAAABIACgBIAEAAIAAABIgCAAIgCADIABAEIADgBIADgCIAAAEIgFAAIAAACIgBAAIAAgBIgBAAIgCABIAAgBIgIAAIACAIIADgCIAAACIABAAIAAACIgBgCIAAAAIgBAAIgBABIgBAAIABAFIABgBIACAAIAAABIgBABIAAAAIgCABIAAAAIABAGQADAigLAYQgHAQgMAMQgNAMgRAIQATAEAQAJQAPAKAMAQQALAOAFARQAHASABAVQAGBHgqAnQghAeg7AGIgXABQgtAAgfgSgAJcCAIABADIABACIAGAAIAAgCIAAgCIAAgBIgCgBIAAgBIgBAAIgFACgAYPD2IAFAAIABAAIABAAIAAADIgCABIgDABgAaKDuIAAgDIAFABIACABIAAACIgCACIgEABIgBgEgAPWDXQgegYgKgyQgFgYgCgnIBRgCQACgEAFgCIAAAAIACgBIAIAAIAHADIAEAHIAAAAQACAFgCACIgDAFIABAAQABADAHAAIAAgBIAGACIAFgBIAAgBIAJACIAHAFIAAACIABACIABAAIABAAIAAADIABAAIABADQAAABABAAQAAABAAAAQAAABAAAAQABAAAAABIADAAQAFgJAIABQAIABAGAHIABAAIAAABIAAACIABAAIAAADIACAAIAAACIABAAIAAAGIADADIAAABIgBAAIgDACIgDACIAHAKIgDAMIADAAQAHgIAFgMQAHgUABgtIAngBIgngFIAAhPIBWAHIAAAnQgCBUgFAXQgLAygdAYQgQANgZAHQgaAHghAAQhCAAghgbgARwCzIAEABIAEAAIAAgBIACgBIAEgBIgBgGIgCAAIAAgDIgBAAQAAAAAAgBIgCgBIgEAAIgEABIAAAEIABAEIgDAAgAQ4CiIACADIAAAFIgDABIAAABIACAAIACgBIABgDIAAgEIgCgCIgCgBgARfCqIAAAAIAAABIAEAAIABAAIABgBIAAAAIgEgBIgCgCgARdCkIACAAIgBgBIgCAAIABABgARYCiIADAAIAAgBIgDgBIAAABIgBAAQAAAAAAABQAAAAAAAAQAAAAAAAAQABAAAAAAgARSCZIABAAIAAgBIgBgBIgBgBIABADgAQjCWIABAAQAAAAAAgBQABAAAAAAQAAAAAAAAQAAAAAAgBIgBAAIgBACgAQgCWIACAAIAAgCIgCAAgAQqCTIADAAIACgCQAAAAAAABQAAAAABAAQAAAAAAgBQAAAAAAAAIABgBIAAgCIADgBIAAgCIgCAAgAQMCKIAGAEIAGADIAAgBIgEgCIgCgDIgCAAIAAgBIgEgCgARJCKIAEAAIAAgCIgEAAgARWB4IACAGIgCAGIACAAIACAAIAAgLIgEgCgAQoBoIAGACIADAFIAAADIABAAIAAACIACAAIAAADIABAAIgBgIIgCgCIgBgCIgDgCIAAgBIgBgCIgBAAIAAgBIgEAAgAQLBNIABADIAAAEIgBADIABAAIAAgCIADgGIgBAAIAAgCIgFgEIACAEgAQCBJIAGAAIAAAAIgGAAgAx/CoQASAAAKgIQALgHAFgRQAEgMABgcIgCABIgDADIgBAAIAAgCIAAgBIgGAAIgEABIAAACIgCgBIgCgBIAAADIgFgBIAAACIgDAAIgBgDIgBgDIABAAIALgBIAAgBIADgBIACgBIAAgCIgBgEIgCgBIgCAAIgBABIAAACIgIABIgEAEIgIABIAAgBIgDAAIgBgBIgDgBIAAgDIAEABIAEAAIgCgHIgDgFIgCAAIgBgBIAAgCIgBgBIgBAAIAAgDIgCgCIAAgBIgCAAIgCgDIgDAAIAAgBIgCAAIgCgCIgBAAIgCgCIgCgCIgBAAIgCgBIgBgBIAAgBIgEAAIAAgBIgEAAIgBAEIgEABIgCABIAAABIgIgBIAAABIgEgBIAAgBIgKAAIgCgBIAAgDIACAAIACgBIAAgDIAAgBIAAgCIgCAAIgFgDIgEACIAAAEQgDgBgCgEQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBIAAgFIAAAAIAAgCIhtAAIAACKICXAAIAABDIjsAAIAAluIAAgBIgBABIgDgBIgDgCIABgBIABgCIAFAEIAAgtIAAABIgCAAIACgEIAAABIAAghIDsAAIAABCIiXAAIAABxICMAAIAAArIACgBIAIgCIACABIACABIAHAIIACAAIABADIACAAIADABIAAACIADAAIABABIADAEIADAAIABACIABABIACABIAAADIABAAIABABIAAADIADABIAAACIABAAIAAACIABABIABAFIACAAIAAACIACACIADABIAAACIACAAIABACIACAAIACADIAOAFIAEAEIACAEIACABIABAAIAAABIADACIABgrIAAidIBNgCIAAChQABBpgRAlQgNAdgbAPQgdAPgrAAgAxaBOIgCAAIAAADIAAADIABgBIACgBIABgCIABgDIgDABgAx0A7IACAEIACAEIACAAIABAHIACAFIgBgQIgDgCIgFgDgEgklADXQgegYgLgyQgFgegCg0IA7gSIAbAHIAAAXIABgBIACAAIAIAAIAHACIADAIIABAAQABAEgBADIgDAFIABAAQACADAFAAIAAgCIAHADIAFgBIAAgCIAIADIAIAFIAAABIAAACIACAAIABABIAAACIABAAIACAEIABADIADAAQAFgIAJABQAHAAAFAHIABABIABABIAAABIABAAIAAADIACAAIAAADIABAAIAAAGIADACIABgIIgDgDIADABIACgzIBWAAIgCAaQgBAigGAZQgIAagNATQggAqhCAAQhBAAgigbgEgiMAC0IACABIAFgBIAAAAIADgCIADgBIgCgFIAAAAIAAgDIgBgBIgBAAIgCgBIgFAAIgCABIAAAEIABAEIgEAAgEgieACrIABAAIAAABIADAAIABgBIABAAIAAgBIgEgBIgCgBgEgieAClIgBgBIgCAAIACABIABAAgEgilACjIADgBIAAAAIgDgCIAAACIAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAgEgirACaIABAAIAAgCIgBAAIgBgBIABADgEgjaACXIABgBIABgBIgBAAIgBACgEgjcACXIABAAIAAgCIgBAAgEgjTACUIADAAIACgCIACgBIAAgBIABgBIACgCIAAgBIgBAAgEgjwACKIAEAFIAIACIAAAAIgFgDIgCgCIgCAAIAAgCIgDgCgEgi0ACKIAEAAIAAgBIgEgBgEgiYACEIgBACIAFAAIAAgBIgBgCgEgimAB4IABAHIgBAGIABAAIABgBIAAgLIgCgBgEgjUABoIAEADIAFAFIAAACIABAAIAAACIABAAIAAAEIABAAIgBgJIgCgCIAAgBIgEgCIgBgCIAAgBIgCAAIAAgBIgCAAgEgjyABOIACADIAAAEIgCADIACAAIAAgCIACgGIgBAAIAAgCIgGgEIADAEgEgj7ABKIAFAAIAAgBIgFAAgAWGDvIgDAAIgGAAIgCgDIAAgEIADgCIAGABIABAEIADAEgEAkBADnIAIkAIgGAAIACgQIBKAFIAHgBIAAEMgEAg5ADnIAAjzIgGAAIAAgpIBQAEIgBAbIAHgBIgJCSIAviOIgDAAIAKgbIBBAEIgEANIAEgBIhmEFgAbrDnIAAhbIBUABIAAAYIAcAAQATAAANgEQAOgDAGgHIAHgIIBDABIhBgFQAHgPABgZQAAgngRgPQgQgQgdAAIgjAAIAABmIhUgIIAAhmIBjgWICkBBIAEAgIgDAgIhTBhQgUAGgYAAgAUYDnIAAjdIBSAAIACDdgAB4DnIAAkzIBUgqIAAARIgkAOIAkgLIAAA/IA0gCQAQgEAHgKQAFgHACgMIACgeQAAgPgCgLIBRgbIABAFQAFATAAAaQAAAjgKAUQgMAcggALQARADANAGQAMAIAIAOQAIANADATQAFASAAAXIgBAcIgGAbQgNArgZATQgaATguAAgADMClIA2gBIAOgEQAQgHAGgUIABgEQADgMAAgUQAAgngLgNQgGgIgNgEQgMgEgUAAIggAAgAjADnIAEjSIAwgBIgwgDIAJh7IgnB5IhEgEIBbjkIBYAAIAAA5Ig9AKIA9AHIAAF2gAmJDnIAAjSIBPAAIgIBmIAhhmIBFAAIhVDSgAouDnIAAjCIg0AAQgRABgTAFQgSAFgGAYQgDAOgBAfIgBBOQgCAUgGAQIhcAAIAAgJQALgGADgnQAEgoAAgpIAAgPIAmgEIgmgHQACgcALgQQAQgXAkgDQgngFgRgiQgNgaAAgsQAAgTAEgPIBgAEQgNAOAAAhQAAATAGAOIggADIAhABIAGAMQAOAQAXAAIBCAAIAAgYIBUAEIAACPIguAJIAuAJIAAAFIgbAEIAbAGIAAAaIgRAEIARACIAABGgA7UDnIAAnAICsAAIADAAQgRgCgUABIAAgBIAAgBIgHgGIgFgFIgCABIgCAAIAAACIgBACIgCgBIgCgBIgBABIgFABQgDAAgDgBIAAgBIgCgCIgBgBIABgBIABAAIABgBIADACIACACIABgCIACgCIAHAEIACgEIADgCIgDgCIACgDIAEAAIADAAIABgBIAGACIAGACIAAAAIABgBIABABIABAAIAEgCIARAIIABgCIgDgDIAAgBIAAAAIAAAAIgBgBIADgEIACgFIACABIABgDIAAgDIABABIAAgBIABACIAAACIAJAGIAAAFIADABIAAAIIACABIACgBIACADIgCAEIABABIAAgBIADABIAAgEQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAgBgBIAAAAIgBAAIACgEIgBAAIgCADIAAAAIgBAAIACgHIADgGIAHAFIgEAOIADABIACABIAGgIIACABIgCADIgCADIABABIAAABIgBACIADAAIAAADIAIAEIAAgCIgEgCIABgBIADABIACgCIgBAAIAAgBIgDgDIgEgDIACgBIABgBIgDgDIAAgBIACABIABAAIABgBIACABIABAAIACgDIADgFIgBgCIABgDIgEgCIABgCIADABIACgDIABgEIABABIACABIgCAJIAAAJIADACIgCACIgBACIAEABIAAAEIAEACIABABIAAABIAAgBIAAAAIADAAIADABIgCADIAGAGIAFgOIAEgBIADgCIAEgBIAFABIADAGQADAEAFABIABgBIACAAIACABIgBACIAEADIgBACIADAJQgBAEAHAFIAEgCIADABIAAABIgHABIgBACIAAABIgGAAIgBADIgIAAIgCADIgCAEIAFAHIgBACIABABIgBABIgBABIACABIgBABIACABIgBABIACACIAEACIgBABIgEAAIgDAEIAGAHIAAAAIgBABIgHgCIgBACIgFgMIgOgWQAJARAGAUQADALABAMQACANAAANQAAAhgJAaQgGAPgIANQgIAKgLAIQgSAPgZAGQgZAGgbAAIg4AAIAAC9gA6AgWIAtAAQAeAAAPgOQAHgHAEgMIAcgEIAAAAIAqgGIhCgEIACgjQAAgZgPgLQgHgFgNgDIhIgDgA3sglIADABIABgBIgCgBgA3lhOIACACIACABIABgBIgEgEIgBACgA5kidIACAFIAGgBIAAgDIAAgEIgDAAIgDAAIgCADgA4RjbIAAABIABAAIAAAAIAAABIAEABIABgBIgCgBIgDgCIgBABgA4cjgIAAADIADABIADgDIgDgCIABgBIgEAAIAAACgA/JDkIAFivIAHgCIAChOIgGgBIAFh+IhjgDIABgsIA2gUIDjAHIgCBCIhigDIgDCAIAFABIgCAvIgGACIgFC6IgWARgAI4DAIAAgCIABAAIABgCIADgCIAAAAIADAAIABAAIAAAAIAAADIgDACIgFADIgBgCgEgiKACwIADAAIAAAAIgBAAIgCAAgAIGCwIABgEIABAAIAAABIABAAIAAADgAR0CwIgBgBIADAAIAAABIgBAAIgBAAgALFCrIgCAAIgCABIAAgCIACgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBIADgBIAAgCIAFAAIABABIACABIAAADIAAAEIgJABgAI6CkIgCAAIABgFIACAAIADADIgBAAIgCADIgBgBgAIWCiIAAgCIAFAAIAAACIgBAAIAAAAgAKuCbIABgEIACABIABAAIgBADgAIbCYIAAgDIgBAAIAAACIgFAAIgDgEIgBAAIgCgCIgCgCIAAgCIABAAIAAgDIACAAIAGgIIAJAAIAAABIAEAAIADAEIABAAIAAAKIgCACIgDgCIgFgBIACAIgAWECOIABgCIAAgCIABAAIAAADIgBABgAx5CNIgDgBIgBgFIAEgCIAAgBIACABIACAAIAAgBIACgBIAEgCIABACIABAEIgBAAIgBADIgEAAIAAgCIgCABIgBABIgBADIgCAAgAWKCKIgCgBIgBgBIgCAAIgDgDIAAgHIABAAIAAgBIAFgEIAGAAIABAEIACAAIAAABIABAAIAAAFIABAAIAAACIgBAAIgBACIgDABIAAABIAAABIgCABIgCAAgARfCLIAAgBIAAgBIAAgBIAAgBIACAAIABABIABAAIAAADgAJJCIIAAgBIABgCIAGgBIAAAFIgBAAIAAABgARhCHIAAAAIAAAAgARkCFIABgCIADAAIAAABIABABgAxnCDIAAgCIgBgBIAEAAIAAADgAItB4IAFAAIACACIAAAEIgDABIgEABgARiB6IgDgCIAEAAIACABIAAABIgDAAgAx3B2IgBgHIABgBIABgBIAEAAIAEABIABACIACADIAAACIgBAAIABACIgBAAIgJACIgCgDgAxkBtIgBgEIADgBIAAACIABADgAI9BqIgBgCIgCgCIALgBIAAACIABACIgBAAIAAABgAIqBoIgCAAIgBAAIAAgDIADAAIACABIgBABIgBABIAAABgAKCBoIgCgCIgBgCIAAgDIADACIAAAFgAJ5BdIADAAIAAABIgBAAIgBAAIgBgBgAJJBYIgBgDIgDgCIAAgCIgCAAIAAgDIAAAAIgEgFIAEgJIADgDIACgCIACgDIABAAIACAAIACgCIABgCIACgBIADgBIAAgBIAMAAIABACIACAAIAAABIABAAIAAABIAEADIACAEIABAAIAAAGIABAFIAAgFIACAAIAAACIABADIABAAIgBABIAAABIAAAAIAAAFIgBAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIABADIABAAIAAABIgBAAIgDgEIgCAAIgCgBIgFAAIgBACIgBADIADACIAAABIACAAIAAABIACABIAAADIgRABQgIAAgHgGgAJcBKIAAAAIAAgEIAAAAgAJaA/IABAAIAAgDIgBAAgAILBVIAAgEIADAAIAAAEgAyABVIAAgBIgBgEIACADIAAACgAudiXIhiAAIAAAbIhNgHIAAhWIEDAAIAADjIhUBCgAIEBJIgCgCIgBgCIABgCIAFAAIABAEIgBABIAAABgAyOBGIgGgEIAIAAIADACIABADIACAAIAAACgAKKBFIgBgCIgCAAIgCgDIgBAAIgCgGIAFgCIAEgEIACAAIABgBIAAgCIABgBIAAgBIAEAAIgCAEIACAAIAAgBIABgBIAAgBIAGAAIACADIABAFIABAAIgBACIAAACIgKABIABAFIgBAEQAAgBgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgFADIAAgCgAKMA8IACAAIAAgCIgCAAgAKPA5IABAAIAAgBIgBAAgAy6BGIAAgEIABgBIABABIABAAIABAAIAAADIgBABgEgjhAA/IgDgHIACgCIAEgBIABAEIABAEIgCACIgCABIgBgBgAQcA+IgCgHIACgBIADgBIABAEIAAAEIgBABIgCABIgBgBgAKkA6IgBgBIAAgDIACgBIAFgBIAAAFIgCABIgEAAgAY7A1IgBgCIgBgEQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIACgDIAGAAIABAEIABAFIgCABIAAACgAdWgDIBagWQAPAGANALQAWAQAKAcIAFAPgAOmAnIAAhDIBWAGIAAAaIAIgEIADAAIAAgBIADAAIABgCIAHgBIAGAGIAGACIACAIQAEAFgDAHIgFALIgIADIAAABIgGAAIAAABIgEABIgOgKIAAAUgAPUAiQgBACAFABIADABIACgCIgBgEIgBgCIgEAAgAQbAYIABAAIAAgFIgBAAgAQUAEIADAEIAAACIABAAIABAEIABADIABAAIAAgFIgBAAIAAgGIgCAAIAAgBIgGgFgAYmAtIABgDIAAgEIgDgBIAAABIgEAAIABgFIABAAIAAgGIACAAIACgCIABgDIAJABIAAACIABABIABAAIAAADIABAGIAAAHIgMAEgAJDAtIAAgCIACAAIAAACgEglVAAbIAqALIgqAHgAIxAqIgBgCIABgCIADAAIABABIAAABIgBABIAAABgEgj/AAiIAAAIIgSgDIASgFIgDgEIgBAAIgdAGIAAAAIgDADIgBgBQgGgBABgDIgsgIIAAg2IBWgBIAAAgIADgCIAEgBIACAAIAAAAIACAAIACgDIAHgBIAHAGIAGADIABAHQAFAFgEAIIgFALIgIADIAAABIgGAAIAAABIgFABgEgjjAAZIACAAIAAgFIgCAAgEgjpAAEIAEAEIAAADIABAAIAAAEIAAADIABAAIAAgGIgBAAIAAgFIAAAAIAAgCIgHgFgAUHAoIgBAAIgCgEIgDgEIAKACIABAEIgBAAIgDADgAImAlIgBgDIgFAAIgCgDIgBgFIACgCIAFAAIABABIABABIAAACIABAAIAAADIABAAIAEACQAAABAAAAQAAAAAAABQAAAAAAABQABABAAABIgDAAIgDABIgBgCgAUDAOIADgDIAHADIgDAFIgGABgAbrgoIBYAjIhYAPgAmJAFIAAjeIBVAAIgGDigAbrgqIAAgjIBNAGIACADIABACIAEABIAAAeIABAAQAAABAKgBIBJADIAFACIADACIADgCIACABIABAAIAMADIhhATgAejgfIABgCIAEgBIAAACIABABgAOrh0QAEgTAFgPIgEAAIAAgBIAEAAIAAgBIAAgBIABAAIABgCQADgIADgHIAAgCIABAAIAAABIAHgLIAAgDIABAAIAAACIAGgHIgBAAIAAAAIABAAIAAgBIAAAAIACgBIgBgCIABAAIAAAAIACAAIAKgJIAAgBIgCAAIgDACIgQAIIAAABIACAAQAAAEgEAAIAAAFIgBADIgHABIgBgBIgBAAIABgEIACgEIABAAIAAgCIgCAAIgBgFIAAgFIgHAAIAAgCIgBgEIgBAAIAAgEIgBAAIAAACQgBAAAAABQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAgCIgDAAIAAAEIgCAAIgBABIgBgDIAAgCIgCAAIAAgBIABgBIABAAIAAgCIABAAIAAgDIgBAAIAAgCIACAAIAAgCIABAAIgBgBIAAgBIgEABIgFgBIgBgCIAAgDIABAAIABgEIgCgEIADgCIAEgCIABgFIgBAAIAAgBIACAAIABACIADABIACADIADAAIAAgBIAAgCIADAAIAAgBIACAAIAAgEIABAAQAAAAABABQAAAAAAAAQAAABABAAQAAAAABAAIACgDIAAADIAFAAIABgHIABAAIAAAGIACAAIAAACIACgBIACAAIAAgDIACABIABAEIAEABIAAgBIADAAIACgBIAAABIABAAIAAAEIABABIABACIAEAAIACgBIAAACIgBADIAAAEIAEAAIAAABIAAAAIAAAEIAFgBIADgBIAAABIABABIAIADIAAACIgBACIABAAIABAAIAAABQALgEAMgDIAAgBIgBgCIACAAIAAgDIgBgCIgFABIAAgBQgFgCAAgFIABAAIABgBIAAgCIgBgCIgCgCIgFACIgEAAIABgDIgBgFIgBAAIAAAGIgCAAIAAgCIgBAAIABgFIACgDIADgDIAAgBIAIAAIAAgEIACAAIABgCIACgBIAAgBIAFAAIAEACIAAADIABADIABAAIAAACIgBACIgBABIgCABIAAACIACABIABABIABgBIABgBIAAADIABAAIABACIABACIAAAFIAAAFIgCABIgCABIgBABIgBAAIAAAEIACAAIAAgCIABAAIAAAFIAAAAQASgDAWAAQAuAAAfAOQAeAOARAdQAWAoABBdIhWADIAAgJQAAgygHgWQgNgsgpAAQgTAAgMAIQgNAJgIARQgIAXgBApIAAAeIhWABQAAgyAFgjgAOxh/IABAAIAAgDIgBAAgAO6icIACAAIAAgDIgCAAgAPCitIABAAIAAgCIACAAIAAgDIgBAAIAAACIgCAAgAPXi5IgBABIAAABIABAAIABABIABAAIAAgBIABgBIABgBIgCgBIgCAAgAPVjAIABABIABABIAAgDIgCAAgAPCjLIACAAIAAgCIgCAAgAPpjMIAAAAIgBgBgAOwjXIABAAIAAgCIAAAAIAAgBIgBAAgAOrjcIAFAAIAAgCIgFAAgAPljfIABAAIgCgBgAQDjrIACAAIAAAAIgBAAIABgCIAAgCIgCAAgEglVgAoQABhdAWgmIANgTICAgmQAsAFAdAZQAQAPAIAVQAJAWAAAcIACAiIhTAAIgGg0QgFgPgJgIQgIgHgOAAQgTAAgNAIQgMAJgIARQgJAXAAApIAAAbgEAkKgAvIAFg7IgSA6IhAgEIABgBIBBikIBXAAIAACvgAehgqIgBgCIACAAIACABIAAABIgDAAgA42gyIABgFIAEAEIgCACIgBAAIgCgBgEAg5gA7IAAieIBUAAIgDCigAXdg9IADACIAAAAIgBACIgCAAgAouiFIAvACIgvgGIAAgOIg+AAQgQAAgLADIhpgMQAJgVASgNQASgNAagGQAWgEAZAAICgAAIAACOIhUAHgAXFhHIAAgDIACABIABACgAbrhbIAAh+IDsAAIAAACIgeBAIhYAAQADAFgDAHIgFAKIgIADIAAABIgGAAIAAABIgFABIgEgEIgGgDIAAAkIgBAAQgHAEgCAKgAcUiCQgBACAGABIABABIACgCIgBgEIgBgCIgDAAgAdaiMIABAAIAAgFIgBAAgAdYiZIAAgBIAAAAgA27hkIAAgBIAAgBIALAHIgBACgAdbhmIgCgHIACgCIAEgBIABAFIABAEIgCABIgCABIgCgBgA29hyIgEgCIABgBIABAAIABgBIADABIADABIgCAEIgDgCgANPh4IAAgBIACAAIgCABIAAABgAOjh5IgBgBIADABIAAABIgCgBgA27iCQABADAAACIABABIAAABgAWyh/IABgCIACgBIADADIgFACgA3EiIIAAgCIADgEIAGAMIgJgGgAW8iFIgCgBIABgCIACgCIAAAAIACgBIACACIABABIgBACIgBABIABABIgEABIgBgCgAEYiKQgGgHgLgEIBSgqIAGAHIAMAVIhQAfgA2liIIAFgCIAFAAIAAACIAFACIgBACgAOViHIgBgBIACAAIAAABIgBAAIAAABgAWziGIAAgCIAAgBIACAAIAAABIAAABIAAABgANeiHIAAgGIABAAIAAAGgA29iIIABgCIABgCIACABIgBACIgBACIgCgBgA2tiKIgBgBIAAgBIAAgBIAEACIABgBIABAAIgBACIgBAAIgBABIgBAAIgBgBgANZiKIAAgBIAEAAIAAABgA24iPIAAgCIACABIACgBIACABIgCACgAOuiPIAAgCIABAAIACABIAAABgAOfiPIAAgBIAEAAIAAABgA24iPgAOkiQIAAgBIADAAIAAABgANZiQIAAgCIABABIACAAIgBABIgCAAgAW6iRIAAAAIAAgDIAAAAIACAAIAAABIgBACgAWwiVIACgDIADABIAAABIgBABIAAACIgCABIgCgDgAOniXIgBAAIgBgBIACAAIAAABIAEAAIAAABIgCAAIgCACgAOYiXIAAgCIABACgA2hiZIABgCIACABIgBADIgCgCgAW5ibIgBgBIgBABIAAgCIgBAAIADgEIABADIAAACIAAABgAO0ibIAAgEIACAAIAAAEgAXEiiIgBACIgCgBIgEgCIgCgEIACgEIAGgEIAAAAIABAAIABAAIABAAIACACIACAHIgDADIAAABIgBABIgCABIAAgCgAOxigIAAgCIgCAAIAAgDIACACIAAADgAOhiiIgBgBIADAAIAAABIgCAAgAOeiiIAAgBIABAAIAAABIgBAAgAOjijIAAgDIABAAIAAADgAOjijgAO2ilIAAgCIACAAIAAACgAOsilIAAgFIACAAIAAAFgAOeilIAAgCIABAAIAAACgANPinIAEAAIAAABIgDAAIgBgBgAXLisIAAgBIABAAIAAgCIABgBIAAgCIABAAIACAAIACABIAAAAQADABAAAEIgBABIgDABIABAAIACACIgFACQgEgCAAgEgAM/imIAAgBIAHAAIAAABgAW1inIgCgDIgCgCIgBgBIgCABIgCgBIAAAAIgEgCIABAAIAAgBIABgBIgBgCIAAgDIAAgBIgBgBIAAgBIAAAAIABgBIgBgCIAAgDIgDgGIgBgDIgBgEIAHgIIACAAIAEACIACADIADACIgCACIAEAIIgCABIAAACIABADIADABIAAABIAAABIAAABIABACIAAAEIgBABIgCgDIgBgBQgBACACADIAEAGIgBACIgEACgAOfinIAAgCIADAAIAAACgAOfingAMziqIABgDIgBAAIAAABIAAAAIAAgDIgCAAIAAgFIABAAIAAgBIgBAAIAAgCIAEgGQACgEAEgBIAAgCIACABIADABIAAgDIgDAAIAAgBIADAAIACgDIACgCIADAAIAAABIABAAIAAgBIADAAIABABIAAABIgGAAIAAABIACAAIAAABQABABAAAAQABAAAAAAQAAAAABAAQAAAAABgBIACgBIAAABIABABIACAAIAAABIgKACIgHACIAAADIgEAAIgCADIgBAAIAAACIgBAAIAAAIIgCAAIAAgBIAAAAIAAgEIgDAAIAAAJIADAAIAAgDIAEgBIAAAFIgCAAIAAADIAEAAIAAACQgGAAgDgDgAM6i+IABgBIABAAIgBgBIgBgBgANTipIAAgBIABABIAAAAgAJgixQAWgWAhgKICJAnIjIABgAOqitIAAgCIAFAAIAAACgAW9i0IgBgBIAAgBIAAAAIABgBIAEACIgBACIgBAAIgCgBgA2Yi4IABAAIgBACIgBAAIABgCgAOmjBIgBAAIAAACIgBAAIAAgBIAAgCIACAAIAAgDIABAAIAAgBIABgCIACgBIAEAAIAAABIgBABIgBAAIgCABIgDABIAAAGQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAABgA2Pi8IgCgBIACgEIACADIAAADIgCgBgAXNi8IAAAAIgCgBIgCgBIgDgDIACgBIAAgBQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAAAAIABgBIABgBIAAgBIACAAIAAABIABgBIABACIABgBIAAAAIACACIAAADIAAAAIgEAGIgBgBgANVi9IAAgEIgCAAIAAgBIgCgBIAAgBIACAAIAAgBIABAAIAAABQADACAAAFgAMui/IgBgBIABgBQAAABAAAAQABABAAAAQAAAAAAgBQAAAAAAgBIAAgBIACAAIgCAEgAMqi/IAAgDIABAAIAAADgAXSjBIADgBIAAAAIgCABgANojBIAAgBIABABgAW5jDIABgDIABAAIABgBIAAACIAAAAIABABIgDADgANfjCIAAgCIAAABIABABgANjjCIAAgBIABgBIgBgCIABAAIABgBIAAgEIABAAIAAAEIAEAAIAAABIgBACIgBACgAMtjDIgBgBIACAAIAAACIgBgBgANsjFIAAgBIABABgANfjFIAAgCIAAABIABABgANgjHIAAgBIAEAAIAAABgANsjJIAAgDIABAAIAAADgAOcjKIAAgCIABACgANojMIACAAIAAABIgCgBgAOejMIAAgBIABAAIAAABIgBAAgAORjMIABgCIAFAAIAAABIgBAAIAAABgAOvjOIgBgBIACAAIAAABIgBAAgAOejQIABAAIAAgBIAEAAIAAgCIACAAIAAADIgEACIgDgCgAOwjPgANzjTIgBAAIAAgEIACgCIAEgBIABABIABAAIAAACIABACIgBAAIAAACIgEABIgDgBgAOljTgA2njWIgBAAIABgDIADAAIAEAAIgBACIgBAAIgCABIgDAAgAXCjYIgCAAIgDAAIgBgDIgCgCIACgCIAAgBIABgCIAHgDIAEACIADADIAAABIgCAAIgEACIABACIABgBIAAABIABABIAAAAIgDABIAAAAIgCABIgBABIAAgBgAP1jaIAAgDIABABIAAACgAV0jdIAAgHIABAAIAAgCIgEgCQgBABgBAAQgBAAAAAAQgBAAAAAAQAAAAgBgBIABgHIAAgBIAAgBIAEgBIADgBIABADIACAAIAAgBIgBgBIgBgBIABAAIAAgBIABAAIAAABIADAAIAAABIABACIABACIACABIABAAIABACIABAAIACAAIAAACIABABIABACIgBAAIAAACIgBAAIAAACIgCABIgDAAIAAADIgEgCIgEAAIgBABIAAACgAV7jmIABAAIAAgCIgBAAgAV4jsIAAABIACAAIgBgCIgCgBIABACgAP3jdIAAgDIACAAIgBACIAAABgAONjeIAAgCIABAAIAAACgAP7jgIAAgBIACAAIAAABIgCAAgAjfj6QgbgZAAgmIAnAAQADAVAPALQAQAKAZAAQAfAAAPgKQAPgKAEgWIAnAAQgGAqgaAXQgaAWgrAAQgvAAgbgYgAQWjlIgBgBIgBgCIACgBIABAAIAAgCIgBAAIAAgCIABAAIAAgBIAEAAIAAACIABABIgCAAIAAAGIgCAAIgCABgAVhjrIABgEIAEABIADABIAAACIgDACIgDABIgCgDgA5vjrIACgEIACABIgCAFIgCgCgAXBjrIgBgCIACgDIACgCIABABIABABIAAgBIACADIgDADQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgBgBgAPhjrIAAAAIAAAAIAEgDIAAABIgBACIAAAAgAPnjvIAAgBIABgBIACAAIAAABIgBAAIgBABIAAAAIgBAAgA49jvIgNgHIAAgCQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAgBAAAAIgCABIgCABIgCgBIAAgBIgBgBIACgEIAGACIgBACIACABIABABIAHgMIABAAIAAACIgBAGIgFAHIAKADIAAgBIgBgBIABgBIABABIACgDIABgDIADACIACgCIgDgBIABgBIACABIACgDIABABIgBABIACABIgIALIgBgBIACgEIgBAAIgCAFIgCgBIgBABIABAAIABABIgCACgA4XjxIACAAIACAAIgBABIgDgBgA5mj1IgBgBIAAgBIABgCIABgCIAGAAIAFACIgCAIgA3LjxIgBgBIAAABIgBAAIgEgBIgDgCIAAgBIABgBIgCgBIABAAQgEgDACgEIgCAAIABgCIABgBIAAAAIAAAAIAAABIAAAAIACgFIAEgDIAEgBIABgBIACABIABAAIABAAIADABIADAEIgBAAIABABIABAAIAAADIABAAIgBACIABABIgBABIABABIgEAHIgDADgA57j2IAFgCIAGADIgCAEgAOcjyIAAgBIgBAAIAAgBIACAAIAAACgA5vjzIAAgCIABABIgBABIgBABIABgBgA4RjyIgJgFIABgBIgCgBIAAABIgDgCIABgDIACACIADABIABgDIACgCIABABIAAACIABAAIgBAEIACACIACABIgBADgAQfj1IgDgEIAAgCIAAgBQACgFABABIAEgBIAAgDIgCgEIABgEIAEgDIAHAAIABAEIABAAQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAIgBAEIgHAEIAAACIABACIABAAIgBAFIgEACIgFABIgBgBgAWQj6IABAAIADACIgBACIgCABgAPdj3IAAgCIAAABIAAABgAPQj4IAAgFIABAAIAAAFgA34j5IAAgBIAAgCIAAgBIADADIgBABIgBgBIAAABgA58j8IACgCIACgCIgHgMIAHgJIACABIgGAKIADAAIACABIAAAHIgCAIIgDgCgAO+j7IgBgBIADAAIAAACgAWNj8QAAABgBgBIgCgBIgCgBIAAgBIAAABIgCgCIACAAIgCgBIABAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIABgBIgBgDIABgBIgBgBIABgBIACgBIgBAAIABgBIAAABIABgBIABACIAAgCIACADIACgCIAAADIACADIACAAIAAgBIABABIgFACIAAgBIgCACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAAAIABADIgEACgAWLkBIABgCIAAgBQAAAAgBABQAAAAAAAAQAAAAAAABQAAAAAAABgAWMkGIAAAAIABAAIAAAAIAAgBgA4ij8IgBgBIgBgBIACgCIADABIABACIgBAAIgBAAIAAABIgBAAgAPuj+IABAAIAAABIgBAAIAAAAIAAgBgAPGj9IAAgBIgBgBIAAgBIADAAIAAADgAO6j+IAAgCIgBAAIABgBIABAAIAAADgA51kBIAAgBIgBgBIABgCIACAAIABgBIAEACIADABIgCAFgAXckBIACgCIAAAAIABAAIAAgBIAAAAIACgCIADgBIABABIABACIgCACIgDACIgCgBIgCACgA4ekAIABgBIACABIgBABgAOfkAIAAgBIABAAIAAgCIABABIABACgAPMkBIAAgHIAAAAIAAAHgA34kDIABAAIACAAIgBACIgCgCgA5kkDIgCgCIABgDIAEABIAEgCIAAgBIADACIAAACIgEABIgDADIgDgBgAOnkEIACAAIAAABIgCgBgA5akIIABgBIABgBIABAAIABgBIADACIADADIAAgCIAEACIAAACIgBABgAXVkDIgCAAIAAgCIAAgDIABgCIABgCIABABIADAFIgBACIgDABgAO5kEIAAAAIgBAAIAAgFIABAAIAAADIABACgA3tkFIgCgBIgBABIgBABIgCgBIgCABIgRgJIACgEIgEgCIABgBIgGgJIAAgLIgCgBIgCgBIAEgHIABAAIABABIgCADIABABIAHgQIAKgGIALgDIACgBIACgCIAEABIADACIACgBIABgBIAJAEIADAFIAFAFIgCACIAFACIABAHIAAAAIABABIgBAGIABACIgBACIgBACIACACIgKATIgGADIgEAFIgMAAIgBgBgA3qkVIAAABIgCAEIgCADIACABIgBABIAAAAIABABIADgEIABABIABgDIABgCIgBgCIAAgBIgDgBIAAABgAOnkGIACAAIAAACgAOfkEIAAgCIgCAAIgBgBIAAgBIgFgFIgCgHIACgDIACgCIAAgCIAEACIgBgBIgBgBIAAgCIADgBIACgBIAAgBQAHgCAEADQAFADABADIgCAAIAAADIgBAAIAAgDIgCAAIgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAQgBAAAAgBIAAADIAEABQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAABIgBAAIAAABIgEAAQgDgEgIAAIgDABIgDAEIgBAAIAAAEIADAAIAAACIACAAIAAACIACABIAEABIAAACgAOWkQIABAAIAAgCIgBAAgA5KkGIABgDIADACIgCADIgCgCgAWpkGIgBgEIAEgBIADADIgDADgAOukHIAAgCIABACgA3CkIIAAgBIAAgBQABABgBgBIgBgBIAAAAIABAAIABgBIAAgBIADABIADACIgCADgA5akIIAAAAgAQ0kLIgCgDIACgBIAAgBIAFAAIABACIABADIgDABIgDABIgBgCgAW1kNIAAgEIABgBIAAAAIADAAIABADIgCACIgCADIgBgDgAO3kMIAAgEIABAAIAAAEgAXGkOIAAgBIABgCIABABIABABIgCABgAOxkVIAAgDIABAAIAAADgA6IkbIABgBIACAAIAAgFIACABIABgBIACADIgBADIgDADIgEgDgA5MkcIgDgCIAAgBIACABIABgCIADACIgBADIgCgBgA52kfIADgDIACgGIADACIACgEIABABIAAABIABABIgEADIgCAEIABABIACgCIACAAIgBADIgBAAIgBACIgDgCIAAABIgCACIgDgEgA56kbIABgDIABABIAAAAIgBACIgBAAgAO0kcIAAgDIACAAIAAABIABACgA5GkeIABgDIACgDIgDgCIgDgBIABgDIAEACIACABIABAEIgBAFgAXGkjIAAABIACABIgBAAIgBABIAAgDgA5RkhIABgBIgCAAIACgCIABgBIACAAIgCAEIgCABgARNkiIgCgBIAEAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgBABIgBgBgA6pkmIgBgDIADgBIADABIABACIgBABIgBABIgBAAIAAABgARAkmIgBAAIgBgBIgCAAIgDgFIgBgIIADgCIAEgDIAAgCIAFAAIADACIADACIABAFIAAAFIAAAAIgBAFIgCAAIgCABIgBABIgBABgAO0klIAAgBIAAABgA5NkoIgCAAIADgCIABgCIABABIgBAEIgCgBgA5/ksIABgDIACACIACABIACgBIgBgBIgBgBIABgBIACgBIABAAIgBADIgBAEIgBgBIgBAAIgBABIgEgCgAOyktIAAgDIgBgCIAAgBIADAAIAAAGgA6AkxIAAgBIABAAIABgBIABABIgBACgA53k2IABgGIACABIACABIgCACIgBADIgCgBgA5elBIABgBIAAAAIAAAAIABAAIABAAIACAAIgBACIgBABgA6nlLIgCgBIADgDIACgDIABABIABAEIgCABIgBACIgCgBgA55lRIABgDIABAEIABABIAAABIgDgDgAOglPIAAgCIABABIABABgAOklTIAAgCIABABIAAABgA58lZIABgBIgBgBIACgCIADACIgDADgA6mlmIABAAIgBACIgCAAIACgCg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-239,-35.9,478.1,72);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.aaa, null, new cjs.Matrix2D(1,0,0,1,-60.2,-108)).s().p("ApZQ4MAAAghvISzAAMAAAAhvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.2,-108,120.4,216);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.big();
	this.instance.setTransform(-201.6,-73.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-201.6,-73.9,403,148);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.circle1();
	this.instance.setTransform(-168.7,-168.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168.7,-168.7,338,338);


(lib.Слой18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa14();
	this.instance.setTransform(-13.5,-8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-13.5,-8.5,27,17);


(lib.Слой17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa13();
	this.instance.setTransform(-12,-7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12,-7.5,24,15);


(lib.Слой16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa12();
	this.instance.setTransform(-11,-11);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11,-11,22,22);


(lib.Слой15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa11();
	this.instance.setTransform(-35,-53.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35,-53.5,70,107);


(lib.Слой14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa10();
	this.instance.setTransform(-51.5,-50);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51.5,-50,103,100);


(lib.Слой13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa9();
	this.instance.setTransform(-48,-58.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48,-58.5,96,117);


(lib.Слой12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa8();
	this.instance.setTransform(-53.5,-42);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.5,-42,107,84);


(lib.Слой11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa7();
	this.instance.setTransform(-35.5,-27);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.5,-27,71,54);


(lib.Слой10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa6();
	this.instance.setTransform(-66.5,-24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.5,-24,133,48);


(lib.Слой9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa5();
	this.instance.setTransform(-36.5,-28);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36.5,-28,73,56);


(lib.Слой8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa4();
	this.instance.setTransform(-26.5,-38);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.5,-38,53,76);


(lib.Слой7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa3();
	this.instance.setTransform(-27.5,-35);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.5,-35,55,70);


(lib.Слой6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa2();
	this.instance.setTransform(-17,-31.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-17,-31.5,34,63);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_14 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(14).call(this.frame_14).wait(1));

	// Слой 1
	this.instance = new lib.Символ24();
	this.instance.setTransform(0,182.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:1,y:137.7},0).wait(1).to({y:105.8},0).wait(1).to({y:84.4},0).wait(1).to({y:68.5},0).wait(1).to({y:55.1},0).wait(1).to({y:43.2},0).wait(1).to({y:33},0).wait(1).to({y:24.8},0).wait(1).to({y:18.2},0).wait(1).to({y:13},0).wait(1).to({y:8.8},0).wait(1).to({y:5.3},0).wait(1).to({y:2.5},0).wait(1).to({regY:0,y:-1},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-166,138.1,332,90);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3 - копия
	this.instance = new lib.Символ42();
	this.instance.setTransform(0,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2 - копия
	this.instance_1 = new lib.frame();
	this.instance_1.setTransform(-89.9,-8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-118.6,-8,208.7,16);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Режим изоляции
	this.instance = new lib.Символ17();
	this.instance.setTransform(-435.4,-0.1,0.053,0.053);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ20();
	this.instance_1.setTransform(-289.6,-0.5,1.269,1.933,0,0,0,0,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ15();
	this.instance_2.setTransform(-62,0);

	this.instance_3 = new lib.Символ15();
	this.instance_3.setTransform(-31,0);

	this.instance_4 = new lib.Символ15();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4},{t:this.instance_3},{t:this.instance_2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-457.4,-21.5,478.4,43);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 11
	this.instance = new lib.Слой11();
	this.instance.setTransform(0.5,-29);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(40));

	// Слой 16
	this.instance_1 = new lib.Слой16();
	this.instance_1.setTransform(-2,12);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:2.8,x:-1.7,y:9.3},9,cjs.Ease.get(-1)).to({rotation:6,x:-1.3,y:6.3},10,cjs.Ease.get(1)).to({rotation:2.8,x:-1.6,y:9.2},10,cjs.Ease.get(-1)).to({rotation:0,x:-2,y:12},10,cjs.Ease.get(1)).wait(1));

	// Слой 17
	this.instance_2 = new lib.Слой17();
	this.instance_2.setTransform(-10,37.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({scaleX:1,scaleY:1,rotation:-17.3,x:-4.8,y:31.7},9,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:-36.7,x:1,y:25.2},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:-18.3,x:-4.5,y:31.4},10,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:0,x:-10,y:37.5},10,cjs.Ease.get(1)).wait(1));

	// Слой 6
	this.instance_3 = new lib.Слой6();
	this.instance_3.setTransform(-19,24.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({rotation:-8.3,x:-14.9,y:21.9},9,cjs.Ease.get(-1)).to({rotation:-17.5,x:-10.4,y:18.9},10,cjs.Ease.get(1)).to({rotation:-8.6,x:-14.7,y:21.7},10,cjs.Ease.get(-1)).to({rotation:0,x:-19,y:24.5},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36,-56,72,112);


(lib.Символ8_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance_1 = new lib.Слой18();
	this.instance_1.setTransform(16.9,-8.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1,scaleY:1,rotation:9.3,x:16.6,y:-8.1},7,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:18.7,x:16.3,y:-7.4},7,cjs.Ease.get(1)).to({rotation:8.6,x:16.6,y:-8.2},8,cjs.Ease.get(-1)).to({rotation:0,x:16.9,y:-8.7},7,cjs.Ease.get(1)).wait(1));

	// Слой 9
	this.instance_2 = new lib.Слой9();
	this.instance_2.setTransform(27,12.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({rotation:-2.8,x:27.1,y:10.3},7,cjs.Ease.get(-1)).to({rotation:-5.7,y:8},7,cjs.Ease.get(1)).to({rotation:-2.5,y:10.4},8,cjs.Ease.get(-1)).to({rotation:0,x:27,y:12.5},7,cjs.Ease.get(1)).wait(1));

	// Слой 10
	this.instance_3 = new lib.Слой10();
	this.instance_3.setTransform(0,-16.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.5,-40.5,133,81);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Слой7();
	this.instance.setTransform(43.5,-82.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(40));

	// Слой 16
	this.instance_1 = new lib.Символ9();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:-6.5,x:8.2},9,cjs.Ease.get(-1)).to({rotation:-14,x:17.2},10,cjs.Ease.get(1)).to({rotation:-6.8,x:8.6,y:0.1},10,cjs.Ease.get(-1)).to({rotation:0,x:0,y:0},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36,-117.9,107,174);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ10();
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14).to({alpha:0},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-239,-35.9,478.1,72);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия: 2
	this.instance = new lib.Символ4();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1 - копия
	this.instance_1 = new lib.title();
	this.instance_1.setTransform(-239,-35.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-239,-35.9,478.1,73);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:7.6},19,cjs.Ease.get(-1)).to({y:15.7},20,cjs.Ease.get(1)).to({y:7.5},21,cjs.Ease.get(-1)).to({y:0},19,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-252,-152,504,304);


(lib.Символ7_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ8();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:360},29).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-201.6,-73.9,403,148);


(lib.Символ6_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance_2 = new lib.Символ5();
	this.instance_2.setTransform(0,0,0.317,0.317);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({scaleX:0.42,scaleY:0.42},7,cjs.Ease.get(-1)).to({scaleX:0.51,scaleY:0.51},7,cjs.Ease.get(1)).to({scaleX:0.42,scaleY:0.42},7,cjs.Ease.get(-1)).to({scaleX:0.32,scaleY:0.32},8,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.5,-53.5,107.3,107.3);


(lib.Символ1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance_1 = new lib.Символ6_1();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 1 - копия: 2
	this.instance_2 = new lib.circle2();
	this.instance_2.setTransform(-168.7,-168.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 1 - копия: 2
	this.instance_3 = new lib.Символ7_1();
	this.instance_3.setTransform(0,4.6,0.687,0.687,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Слой 1
	this.instance_4 = new lib.Символ7_1();
	this.instance_4.setTransform(0,4.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-201.6,-168.7,403,338);


(lib.Слой5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.head_a = new lib.Слой8();
	this.head_a.setTransform(-65,-133.3);

	this.timeline.addTween(cjs.Tween.get(this.head_a).wait(1).to({x:-65.1},0).wait(1).to({rotation:-0.1},0).wait(1).to({rotation:-0.3},0).wait(1).to({rotation:-0.5},0).wait(1).to({rotation:-0.9,x:-65.2},0).wait(1).to({rotation:-1.2,y:-133.2},0).wait(1).to({rotation:-1.7,x:-65.3},0).wait(1).to({rotation:-2.2,x:-65.4},0).wait(1).to({rotation:-2.8,x:-65.5,y:-133.1},0).wait(1).to({rotation:-3.4,x:-65.6},0).wait(1).to({rotation:-3.9,x:-65.7},0).wait(1).to({rotation:-4.4},0).wait(1).to({rotation:-4.8,x:-65.8},0).wait(1).to({rotation:-5.2,y:-133},0).wait(1).to({rotation:-5.5,x:-65.9},0).wait(1).to({rotation:-5.7},0).wait(1).to({rotation:-5.8},0).wait(1).to({rotation:-5.9},0).wait(1).to({rotation:-6},0).wait(1).to({rotation:-5.9},0).wait(1).to({rotation:-5.8},0).wait(1).to({rotation:-5.7},0).wait(1).to({rotation:-5.5},0).wait(1).to({rotation:-5.2,x:-65.8},0).wait(1).to({rotation:-4.8,y:-133.1},0).wait(1).to({rotation:-4.4,x:-65.7},0).wait(1).to({rotation:-3.9},0).wait(1).to({rotation:-3.4,x:-65.6,y:-133.2},0).wait(1).to({rotation:-2.8,x:-65.5},0).wait(1).to({rotation:-2.3,x:-65.4},0).wait(1).to({rotation:-1.8,x:-65.3},0).wait(1).to({rotation:-1.4,y:-133.3},0).wait(1).to({rotation:-1,x:-65.2},0).wait(1).to({rotation:-0.7},0).wait(1).to({rotation:-0.4,x:-65.1},0).wait(1).to({rotation:-0.3},0).wait(1).to({rotation:-0.1},0).wait(1).to({rotation:0},0).wait(1).to({x:-65},0).wait(1));

	// Слой 1
	this.instance = new lib.Символ7();
	this.instance.setTransform(-67.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(40));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-127.5,-171.3,120.4,279.3);


(lib.Группа1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 16
	this.instance = new lib.Символ6();
	this.instance.setTransform(-118,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:17.3,regY:-27.4,rotation:0.5,x:-99.8,y:-60.6},0).wait(1).to({rotation:2.2,x:-97.3,y:-61.4},0).wait(1).to({rotation:4.9,x:-93.2,y:-62.6},0).wait(1).to({rotation:8.7,x:-87.5,y:-64.1},0).wait(1).to({regX:0,regY:0,scaleX:1,scaleY:1,rotation:13.6,x:-103.6,y:-43.5},0).wait(1).to({regX:17.3,regY:-27.4,rotation:18.1,x:-73.9,y:-67.5},0).wait(1).to({scaleX:1,scaleY:1,rotation:21.9,x:-68.7,y:-68.7},0).wait(1).to({rotation:24.8,x:-64.9,y:-69.5},0).wait(1).to({rotation:26.8,x:-62.1,y:-70.1},0).wait(1).to({rotation:28.1,x:-60.4,y:-70.4},0).wait(1).to({regX:0,regY:0,rotation:28.5,x:-88.2,y:-54.7},0).wait(1).to({regX:17.3,regY:-27.4,rotation:28.1,x:-60.4,y:-70.4},0).wait(1).to({rotation:26.9,x:-62,y:-70.1},0).wait(1).to({rotation:24.9,x:-64.7,y:-69.5},0).wait(1).to({rotation:22.1,x:-68.4,y:-68.7},0).wait(1).to({scaleX:1,scaleY:1,rotation:18.5,x:-73.4,y:-67.5},0).wait(1).to({regX:0,regY:0,rotation:14.1,x:-103.1,y:-43.8},0).wait(1).to({regX:17.3,regY:-27.4,rotation:9.8,x:-85.9,y:-64.5},0).wait(1).to({scaleX:1,scaleY:1,rotation:6.3,x:-91.1,y:-63.1},0).wait(1).to({rotation:3.5,x:-95.3,y:-62},0).wait(1).to({rotation:1.6,x:-98.2,y:-61.1},0).wait(1).to({rotation:0.4,x:-100,y:-60.6},0).wait(1).to({regX:0,regY:0,rotation:0,x:-118,y:-33},0).wait(1));

	// Слой 9
	this.instance_1 = new lib.Символ8_1();
	this.instance_1.setTransform(91.5,-4.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({rotation:-0.2,x:92.5,y:-4.1},0).wait(1).to({rotation:-0.8,x:95.3,y:-2.8},0).wait(1).to({rotation:-1.8,x:100.1,y:-0.7},0).wait(1).to({rotation:-3.2,x:106.7,y:2.2},0).wait(1).to({rotation:-5,x:115.3,y:6},0).wait(1).to({rotation:-6.7,x:123.1,y:9.4},0).wait(1).to({rotation:-8.1,x:129.4,y:12.3},0).wait(1).to({rotation:-9.1,x:134.4,y:14.4},0).wait(1).to({rotation:-9.9,x:137.9,y:16},0).wait(1).to({rotation:-10.3,x:140,y:16.9},0).wait(1).to({rotation:-10.5,x:140.8,y:17.3},0).wait(1).to({rotation:-10.3,x:140.1,y:16.9},0).wait(1).to({rotation:-9.9,x:138,y:16},0).wait(1).to({rotation:-9.1,x:134.6,y:14.5},0).wait(1).to({rotation:-8.1,x:129.8,y:12.4},0).wait(1).to({rotation:-6.7,x:123.7,y:9.7},0).wait(1).to({rotation:-5.1,x:116.2,y:6.4},0).wait(1).to({rotation:-3.5,x:108.6,y:3.1},0).wait(1).to({rotation:-2.3,x:102.5,y:0.3},0).wait(1).to({rotation:-1.3,x:97.7,y:-1.8},0).wait(1).to({rotation:-0.6,x:94.2,y:-3.3},0).wait(1).to({rotation:-0.1,x:92.2,y:-4.2},0).wait(1).to({rotation:0,x:91.5,y:-4.5},0).wait(1));

	// Слой 12
	this.instance_2 = new lib.Слой12();
	this.instance_2.setTransform(37.5,25);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({x:38.1,y:25.4},0).wait(1).to({x:40,y:26.5},0).wait(1).to({x:43.1,y:28.4},0).wait(1).to({x:47.4,y:31},0).wait(1).to({x:53,y:34.4},0).wait(1).to({x:58,y:37.5},0).wait(1).to({x:62.2,y:40},0).wait(1).to({x:65.4,y:42},0).wait(1).to({x:67.7,y:43.4},0).wait(1).to({x:69.1,y:44.2},0).wait(1).to({x:69.6,y:44.5},0).wait(1).to({x:69.1,y:44.2},0).wait(1).to({x:67.8,y:43.4},0).wait(1).to({x:65.6,y:42.1},0).wait(1).to({x:62.4,y:40.2},0).wait(1).to({x:58.4,y:37.7},0).wait(1).to({x:53.6,y:34.8},0).wait(1).to({x:48.6,y:31.8},0).wait(1).to({x:44.6,y:29.3},0).wait(1).to({x:41.5,y:27.4},0).wait(1).to({x:39.3,y:26.1},0).wait(1).to({x:37.9,y:25.3},0).wait(1).to({x:37.5,y:25},0).wait(1));

	// Слой 13
	this.instance_3 = new lib.Слой13();
	this.instance_3.setTransform(41,115.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1).to({rotation:0.4,x:41.2},0).wait(1).to({rotation:1.8,x:42},0).wait(1).to({rotation:4,x:43.2},0).wait(1).to({rotation:7.1,x:44.9},0).wait(1).to({scaleX:1,scaleY:1,rotation:11.1,x:47.1},0).wait(1).to({scaleX:1,scaleY:1,rotation:14.8,x:49.1},0).wait(1).to({rotation:17.8,x:50.7},0).wait(1).to({rotation:20.2,x:52},0).wait(1).to({rotation:21.9,x:52.9},0).wait(1).to({rotation:22.9,x:53.4},0).wait(1).to({rotation:23.2,x:53.6},0).wait(1).to({rotation:22.9,x:53.4},0).wait(1).to({rotation:21.9,x:52.9},0).wait(1).to({rotation:20.3,x:52},0).wait(1).to({rotation:18,x:50.8},0).wait(1).to({rotation:15.1,x:49.3},0).wait(1).to({scaleX:1,scaleY:1,rotation:11.5,x:47.4},0).wait(1).to({scaleX:1,scaleY:1,rotation:8,x:45.4},0).wait(1).to({rotation:5.1,x:43.8},0).wait(1).to({rotation:2.9,x:42.6},0).wait(1).to({rotation:1.3,x:41.7},0).wait(1).to({rotation:0.3,x:41.2},0).wait(1).to({rotation:0,x:41},0).wait(1));

	// Слой 14
	this.instance_4 = new lib.Слой14();
	this.instance_4.setTransform(-130.5,124);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1).to({x:-129.9,y:123.8},0).wait(1).to({rotation:-0.1,x:-127.9,y:123.2},0).wait(1).to({rotation:-0.3,x:-124.7,y:122.2},0).wait(1).to({rotation:-0.5,x:-120.2,y:120.8},0).wait(1).to({rotation:-0.8,x:-114.4,y:119.1},0).wait(1).to({rotation:-1.3,x:-109.2,y:117.4},0).wait(1).to({rotation:-1.8,x:-104.9,y:116.1},0).wait(1).to({rotation:-2.1,x:-101.6,y:115},0).wait(1).to({rotation:-2.3,x:-99.2,y:114.3},0).wait(1).to({rotation:-2.5,x:-97.8,y:113.8},0).wait(1).to({x:-97.3,y:113.7},0).wait(1).to({x:-97.8,y:113.8},0).wait(1).to({rotation:-2.6,x:-99.1,y:114.3},0).wait(1).to({rotation:-2.7,x:-101.4,y:115},0).wait(1).to({rotation:-2.9,x:-104.7,y:116},0).wait(1).to({rotation:-3,x:-108.8,y:117.3},0).wait(1).to({rotation:-3.3,x:-113.9,y:118.9},0).wait(1).to({rotation:-2.3,x:-119,y:120.5},0).wait(1).to({rotation:-1.5,x:-123.1,y:121.7},0).wait(1).to({rotation:-0.8,x:-126.3,y:122.7},0).wait(1).to({rotation:-0.4,x:-128.7,y:123.4},0).wait(1).to({rotation:-0.1,x:-130,y:123.9},0).wait(1).to({rotation:0,x:-130.5,y:124},0).wait(1));

	// Слой 5
	this.body = new lib.Слой5();
	this.body.setTransform(54.5,-40);

	this.timeline.addTween(cjs.Tween.get(this.body).wait(1).to({regX:-67.3,regY:-32.8,rotation:0.3,x:-11.8,y:-72.3},0).wait(1).to({rotation:1.1,x:-8.9,y:-70.9},0).wait(1).to({rotation:2.4,x:-4,y:-68.6},0).wait(1).to({rotation:4.3,x:2.9,y:-65.3},0).wait(1).to({regX:0,regY:0,rotation:6.8,x:75,y:-20.6},0).wait(1).to({regX:-67.3,regY:-32.8,rotation:9,x:20.3,y:-57.2},0).wait(1).to({rotation:10.8,x:27.2,y:-53.9},0).wait(1).to({rotation:12.2,x:32.5,y:-51.3},0).wait(1).to({rotation:13.2,x:36.4,y:-49.5},0).wait(1).to({rotation:13.8,x:38.7,y:-48.3},0).wait(1).to({regX:0,regY:0,rotation:14,x:96.9,y:0.1},0).wait(1).to({regX:-67.3,regY:-32.8,rotation:13.8,x:38.7,y:-48.3},0).wait(1).to({rotation:13.2,x:36.5,y:-49.4},0).wait(1).to({rotation:12.2,x:32.8,y:-51.1},0).wait(1).to({rotation:10.8,x:27.5,y:-53.6},0).wait(1).to({rotation:9,x:20.9,y:-56.7},0).wait(1).to({regX:0,regY:0,rotation:6.8,x:75.8,y:-19.9},0).wait(1).to({regX:-67.3,regY:-32.8,rotation:4.7,x:4.9,y:-64.3},0).wait(1).to({rotation:3,x:-1.5,y:-67.3},0).wait(1).to({rotation:1.7,x:-6.5,y:-69.7},0).wait(1).to({rotation:0.8,x:-10,y:-71.4},0).wait(1).to({rotation:0.2,x:-12.1,y:-72.4},0).wait(1).to({regX:0,regY:0,rotation:0,x:54.5,y:-40},0).wait(1));

	// Слой 15
	this.instance_5 = new lib.Слой15();
	this.instance_5.setTransform(-72,36.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({rotation:0.2,x:-71.4,y:36.6},0).wait(1).to({rotation:1,x:-69.6,y:37},0).wait(1).to({rotation:2.2,x:-66.6,y:37.6},0).wait(1).to({rotation:3.8,x:-62.4,y:38.4},0).wait(1).to({rotation:6,x:-57,y:39.5},0).wait(1).to({rotation:8,x:-52.1,y:40.3},0).wait(1).to({rotation:9.6,x:-48.1,y:41},0).wait(1).to({rotation:10.9,x:-45,y:41.6},0).wait(1).to({rotation:11.8,x:-42.8,y:41.9},0).wait(1).to({rotation:12.3,x:-41.5,y:42.2},0).wait(1).to({rotation:12.5,x:-41,y:42.3},0).wait(1).to({rotation:12.4,x:-41.4,y:42.1},0).wait(1).to({rotation:12.2,x:-42.4,y:41.6},0).wait(1).to({rotation:11.8,x:-44,y:40.7},0).wait(1).to({rotation:11.3,x:-46.4,y:39.5},0).wait(1).to({rotation:10.6,x:-49.4,y:37.9},0).wait(1).to({rotation:9.8,x:-53,y:36},0).wait(1).to({rotation:6.8,x:-58.8,y:36.1},0).wait(1).to({rotation:4.3,x:-63.6,y:36.3},0).wait(1).to({rotation:2.4,x:-67.3,y:36.4},0).wait(1).to({rotation:1.1,x:-69.9},0).wait(1).to({rotation:0.3,x:-71.5,y:36.5},0).wait(1).to({rotation:0,x:-72},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-182,-211.3,340,385.3);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 1
	this.instance = new lib.Символ1_1();
	this.instance.setTransform(0,0,0.522,0.522);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_14 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(14).call(this.frame_14).wait(1));

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.setTransform(0,0,0.799,0.799);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:7.8,rotation:6.4,x:-26.3,y:30.1},0).wait(1).to({rotation:9.8,x:-40.2,y:42.7},0).wait(1).to({rotation:12,x:-49.1,y:50.8},0).wait(1).to({rotation:13.5,x:-55.5,y:56.5},0).wait(1).to({rotation:14.2,x:-58.4,y:59.2},0).wait(1).to({rotation:14.7,x:-60.2,y:60.8},0).wait(1).to({regY:0,rotation:15,x:-60,y:56},0).to({rotation:0,x:-115,y:287.1},7,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-201.4,-121.5,402.9,243);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.zomb = new lib.Группа1();
	this.zomb.setTransform(-9.9,-0.7,0.83,0.83,0,0,180,0,-19.5);

	this.timeline.addTween(cjs.Tween.get(this.zomb).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141.1,-159.9,282.2,319.8);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.setTransform(0,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-239,-36.4,478.1,73);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_12 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(12).call(this.frame_12).wait(1));

	// Слой 1
	this.targ = new lib.Символ11();

	this.timeline.addTween(cjs.Tween.get(this.targ).to({scaleX:1.4,scaleY:1.4,x:5.5,y:71.1},12).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141.1,-159.9,282.2,319.8);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_27 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(27).call(this.frame_27).wait(1));

	// Слой 3
	this.instance = new lib.Символ16();
	this.instance.setTransform(219.1,-149.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(16).to({_off:false},0).wait(1).to({regX:-218.2,x:0.9,y:-107.8},0).wait(1).to({y:-78.8},0).wait(1).to({y:-58.2},0).wait(1).to({y:-42.5},0).wait(1).to({y:-29.4},0).wait(1).to({y:-19.4},0).wait(1).to({y:-12.9},0).wait(1).to({y:-8.5},0).wait(1).to({y:-5},0).wait(1).to({y:-1.9},0).wait(1).to({regX:0,x:219.1,y:0.9},0).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ3();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:19.3},8,cjs.Ease.get(-1)).to({y:40},8,cjs.Ease.get(1)).wait(1).to({y:33.2},0).wait(1).to({y:24.8},0).wait(1).to({y:14.2},0).wait(1).to({x:0.1,y:1.1},0).wait(1).to({y:-15.4},0).wait(1).to({y:-36.3},0).wait(1).to({x:0.2,y:-63.6},0).wait(1).to({y:-99.2},0).wait(1).to({x:0.3,y:-149.2},0).wait(1).to({x:0.5,y:-230.6},0).wait(1).to({x:0.7,y:-332.1},0).wait(1));

	// Слой 4
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],0,-83.4,0,83.5).s().p("Ehc5APtIAA/ZMC5zAAAIAAfZg");
	this.shape.setTransform(0.6,-9.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(28));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-594,-109.7,1189.3,201.1);


// stage content:
(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var _this = this;
		
		//Resize
		
		window._setCanvasSize = function() {
			
		    console.log(stage.canvas.width);
			
			stage.canvas.width = window.innerWidth;
			stage.canvas.height = window.innerHeight;
			
			_this.gun.x = stage.canvas.width/2;
			_this.gun.y = stage.canvas.height;
			
			_this.title.x = stage.canvas.width/2;
			_this.title.y = stage.canvas.height/10;
			
			_this.bg.x = stage.canvas.width/2;
			_this.bg.y = stage.canvas.height/2;
			
			_this.zombie.x = stage.canvas.width/2;
			_this.zombie.y = stage.canvas.height/2;
			
			_this.btn.x = stage.canvas.width/2;
			_this.btn.y = stage.canvas.height+60;
			
			
		}
		
		
			window.onresize=function(){
				_setCanvasSize();
			}
		
			
		
		//Scale
		
			_this.gun.scaleX = 0.7;
			_this.gun.scaleY = 0.7;
		
			_this.title.scaleX = 0.6;
			_this.title.scaleY = 0.6;
		
			_this.zombie.scaleX = 0.9;
			_this.zombie.scaleY = 0.9;
		
			_this.bg.scaleX = 0.9;
			_this.bg.scaleY = 0.9;
		
			_this.btn.scaleX = 0.7;
			_this.btn.scaleY = 0.7;	
			
		window.onresize();
		
		//Touch Actions
		var onClick = function(evt) {
			console.log('click');
			window.open("https://www.google.com.ua", "_blank");
		};
		
		var onTouchMove = function() {
			console.log('move');
			var touch = event.targetTouches[0];  
			_this.circle_mc.x = touch.pageX; 
			_this.circle_mc.y = touch.pageY;  
			event.preventDefault(); 
		};
		
		var onTouchStart = function() {
			console.log('start');
			var touch = event.targetTouches[0];
			_this.title.gotoAndPlay(1);
			_this.zombie.gotoAndPlay(1);
			_this.gun.gotoAndPlay(1);
			_this.circle_mc.gotoAndPlay(1);
			_this.circle_mc.x = touch.pageX; 
			_this.circle_mc.y = touch.pageY;  
			event.preventDefault(); 
		};
		
		var onTouchEnd = function() {
			console.log('end');
			var touch = event.targetTouches[0];
			_this.btn.gotoAndPlay(1);
			event.preventDefault();
			
			stage.canvas.removeEventListener('touchmove', onTouchMove);
			stage.canvas.removeEventListener('touchstart', onTouchStart);
			stage.canvas.removeEventListener('touchend', onTouchEnd);
			
			stage.canvas.addEventListener("click", onClick);
		};
			
		stage.canvas.addEventListener('touchmove', onTouchMove, false);
		stage.canvas.addEventListener('touchstart', onTouchStart, false);
		stage.canvas.addEventListener('touchend', onTouchEnd, false);
		
		
		window.onresize();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 8
	this.btn = new lib.Символ26();
	this.btn.setTransform(319.1,775,1,1,0,0,0,0,188.1);

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

	// Слой 4
	this.title = new lib.Символ14();
	this.title.setTransform(320,109.7);

	this.timeline.addTween(cjs.Tween.get(this.title).wait(1));

	// Слой 7
	this.circle_mc = new lib.Символ23();
	this.circle_mc.setTransform(320.6,407.1);

	this.timeline.addTween(cjs.Tween.get(this.circle_mc).wait(1));

	// Слой 1
	this.gun = new lib.Символ13();
	this.gun.setTransform(297.1,685.2,1,1,0,0,0,-201,121.7);

	this.timeline.addTween(cjs.Tween.get(this.gun).wait(1));

	// Слой 2
	this.zombie = new lib.Символ40();
	this.zombie.setTransform(319,326,1,1,0,0,0,-1,-76);

	this.timeline.addTween(cjs.Tween.get(this.zombie).wait(1));

	// Слой 3
	this.bg = new lib.Символ22();
	this.bg.setTransform(319,406.5,1,1,0,0,0,-1,64);

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(45.9,342.5,1189.3,815.6);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;