(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 305,
	fps: 35,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bg.jpg", id:"bg"},
		{src:"images/blik.png", id:"blik"},
		{src:"images/body.png", id:"body"},
		{src:"images/chest.png", id:"chest"},
		{src:"images/fog.png", id:"fog"},
		{src:"images/hand.png", id:"hand"},
		{src:"images/hand2.png", id:"hand2"},
		{src:"images/leg.png", id:"leg"},
		{src:"images/skull.png", id:"skull"}
	]
};



// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,305);


(lib.blik = function() {
	this.initialize(img.blik);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,40,32);


(lib.body = function() {
	this.initialize(img.body);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,198,355);


(lib.chest = function() {
	this.initialize(img.chest);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,70,65);


(lib.fog = function() {
	this.initialize(img.fog);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,155);


(lib.hand = function() {
	this.initialize(img.hand);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,51,153);


(lib.hand2 = function() {
	this.initialize(img.hand2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,155,415);


(lib.leg = function() {
	this.initialize(img.leg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,162,97);


(lib.skull = function() {
	this.initialize(img.skull);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,58,85);


(lib.Символ58 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(4,2,0,3).p("Egx/gX0MBj/AAAMAAAAvpMhj/AAAg");
	this.shape.setTransform(320,152.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2,-2,644,309);


(lib.Символ54 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhGDyQguAAgFgjIgfjZQgIg9BAAAIDBAAQBAAAgJA9IgeDZQgFAjgvAAgAADhPIAAgVIAAAAIAPAAIAAgHIAAhJIgPAAIAAg9IAAAAIA5AAQA0AAAFASIAiByQAEAKgHAIQgMANgvgBgAhZhPQguAAgMgNQgHgHADgKIAihyQAHgSA0AAIA4AAIAAA9IgQAAIAABJIAAAHIAQAAIAAAVgAADhpIgFAAIgKAAIAAgCIAAhEIAZAAIAABEIAAACg");
	this.shape.setTransform(16.5,26);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.408)").s().p("AhLEEQgygBgFglIghjqQgJhABFgBIDPAAQBFABgKBAIggDqQgGAlgxABgAiYgKIAfDZQAFAjAuAAICMAAQAvAAAFgjIAejZQAJg9hAAAIjBAAQhAAAAIA9gACXhtIgihyQgGgSg0AAIg4AAIAAgSIA9AAQA4ABAGASIAkB6QAGASgUAJQAHgIgEgKgAiih2IAlh6QAGgSA4gBIA9AAIAAASIg5AAQg0AAgGASIgiByQgDAKAHAHQgUgIAFgSgAADhkIAAgFIAKAAIAAgCIAFAAIAAAHgAgShkIAAgHIAFAAIAAACIALAAIAAAFg");
	this.shape_1.setTransform(16.5,26);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,33,52);


(lib.Символ51 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAGEVIgEgBIgCgBIgBgBIgDAAIgEABQgEABgFAAIgFgCIgCgBIgCgCIgDgEIgBgEIAAAAIAAgJIABgBIABgGIAAgBQACgDAEgCQAEgBAFAAIAGAGIAFAHIACAIIAAAIIAAABIAAAAQABgKgBgHQABgHAGgEIAFgCIAEAAQADgBADAFIAAABQADADABAFIACAEIABADIAAABIAAAGIABAAQABgHgDgKIAAgCIAEgJIAFgFIAEgDIABAAIACAAIACAAIABABIADADIAGAKIABAAIAAAAIgCgGIgCgDIADgFIADgFIAEgEIACgBIACgBQAEAGABAGIAAANIgBAFIgBACQgCAHgEABQgCgGgCgDIgCAAIgCABIgCAGIgDAFIgDADIgDADQgGADgJgCIgBAAIgCADIgCACIgCABIgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgFAAIgHgBgAgvEIIgLgGQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAABIgFAAIgEgBQgEgCgBgGIAAgGIACgIIACgHIAEgHQADABACAEIAEAGIABAAQgEAHABAKIACgIIADgHQACgEAEAAIAHgBQAFAHACAJIACASIgBAAIAAAAIgBAAIgGABIgHgBgAgJDuIgEgCIgBAAQgFgBgFADQgGADgBAFQgBgJgEgHIgBgCIgCgBIgBgBQgDgBgEACQgEABgDADQgCgGgFgEQgDgCgDAAIgCgCIgBgBIgDgEQgDgDgFgCQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBABQgFAFgBAHIAAgEQgCgTACgQQADgGABgHQABgHgBgHQAAgGgFgEIAGgBIABABQAFAFADAJQADAJgBAMQgBAKgEAJIAAABQAGgMABgLQACgMgEgLIgDgIIAFACQAEADAFAGIAIAKQAAABABAAQAAAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBgBAAQgCgIgFgGQgFgGgHgEIAGABQAGABAFADIAKAIIABAAIAAgBQgGgKgPgFIgIgBIgJAAIgIgCQgOgBgQAGIgOAGQgIADgGABIAAgBQgFgIgLgLIgQgRQgKgLgBgRQAAgLADgUQADgNAGgUIALgeQAEgPAAgPIgBgJIAEAGIAAAAQACADgBADQADgCgBgDIgCgEIAAAAIgBgDIgFgNQAAgEADgEIABgBIgBgBIgEgCQgBAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBIABgDIACgCIAGgEIAFgDIABgBIgBAAQgGgFgBgGQgCgFADgHIAEgKIAFgKIAKgYQAHgMAJgIQAHgGALgFIAUgHQALgDAIgEQAJgFAHgGQAEAHAHACQAGABAJgCIAQgFQAJgDAEAAIgDANQgFAQAFAFIgDAFIgDADIAAACIAAABQAGAHAIADQgIAEABAHIAFAJQADAFgBAFIABgGIgCgHIgCgDIgCgEQgBgDAEgDIAGgEIABgBIgBgBQgJgCgFgHIACgEIACgFIAAgBIgBgCQgBgCAAgHIACgLQACgHADgEQAIABAEAHIACAAQAJgDAGABQAIAAAGAGQAGAFADABIAGABIAFgBQADAAADACIAFAEIAEADIAEADIAEACQAAAAABABQAAAAABAAQABAAAAAAQABAAAAAAIAGgDQAEgCADAAIAGACIAGADIAHACIAHADQACAEACAFIABAKIACAKQAAAGgBAEIABABQAFAEABAIIABANIAAALIgBALIACANIABAOIgBAEIAAABIgBAHQgCAJgHAEIgBAAIgBACIAAAAIAAABQAAAIACAHQACAJAFAFIAAAAIAAAAQgFgOgBgNIACAAQAGgDAEgIQACgFABgJQAHgKAGgLIgDAMIgDALQgFAUADAPIAAAFIACALIAFAKIAIASQAHAPACAJQAEANgBAMQgBAWgNAUQgOAWgUAIIgFACQgNgFgPgDQgQgGgNgDQgMgCgKAFQgKAFgGALIAAAAIAAAAQAJgLALgDQAIgDANADIAJADIgKAAQgQABgKAIQgNAJADAPIABAAIAAAAQABgIADgFQADgGAGgDQAHgEAMAAIgEAFQgFAGgBAMQgBAIACAIQACAKAGACIABAAQgJgJABgSQABgJAEgHIAEgFIAGgDIAHAAQgEAEgCAFQgCAFgBAGQAAAGABAGQACAGADAEQgEABgCAFQgDAEAAAFIAAABIgBACIgBAAQgCABgEAEIgDAFIgCAAIgBABIgCAAQgEABgEAFQgEAEAAAGIgDgEIAAgBIgEgCIgFAAIAAAAIgBABQgFACgDAFQgEAFgBAFQgDgGgDgDIgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIgGABIgFADQgEAEgBAGQgDgGgFgFgAgGDSIAAABIADAMIACAMQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAIAAgBIABgLQABgDACgDIAEgFIAAgBIgCAAQgGADAAANIgCgJIgDgIIAAAAIgBAAgAATDUIgBAAIACAFIADAEQADAHAAAGIABAAQABgFgCgFIgHgMIAAgBIAAABgAgXDbQgCAEgBAGIABAAIAAAAQACgKAIgHIAAgBIgBAAQgEACgDAGgAgaCKQgGAHgDAMQgDAJAAALIgCAMIgEAMIgFAKIgDALIAAABIABAAIAFgNIAGgMIAEgJQACAGADADQADAEAFAAIAEACQAJABAFgIQgDACgFAAIACgBIAFgDIABAAIADgFIAAgBQACAHAEADQAFAEAHAAQAGAAAEgEQAEgDABgFIABAAIAAAAQABAFAFAGIAJAKIABAAIAAgBQgBgEgFgGQgGgHgBgEQgBgDABgFIADgHQACgHgDgGIAAAAIAAAAIgBAIIgCAIIgBgRQgDgNgKgLIgBAAQAIAKACALQgCgDgEgDIgDgCIgCgEQgFgGgBgKIgBAAIgBgGIgCAAIgCAEIgCAEIgEAGIAAgEIAAgOIAAgVIAFAAIAEAAIADADIABAAIAFAEIAFAGIAEAFQAFAGAGADQAGADAHABIABgBQAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAQgKgBgIgJQgIgMgFgEIADABIAGAEIAGAGQAEAEAFADQAFACAGAAIAQgCIARgCQAFAAANABQALABAGgBIABAAIADgBIADgDIADgCQAFgFAGgKQAJgPABgNIACgBIAGgFIAAAHIgBAHQgBAKgHAJQAIgJADgOIAFAGIAEAGIABAAQgBgGgEgHIgBgDIgBgEIABgGIACgFIABgBIABgDIAAgFQABgKgHgKIgHgIIgGgIQgGgHgEgKQgFgMAAgMQgBgNAGgLIgBgBIAAAAQgIANAAAQQABAPAHANIABADIAAABIgCADQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQABADAEADIAGAGIAGAGIAFAIQADAGgBAGQgCAGgFAEIgIACIgJAAIgJgBIgIAAQgRACgQAHIgOAJIgOAKQgQALgNABIgFgCIgBgBQgEgDgEgHQgGgLgEgPIAAgBIgBABQACAPAGAMIAFAIIgJgBIgCgLIgCgKQgDgUgEgNIAAAAIAAABIACAPIACAPIADAWQAAAAAAAAQgBAAAAAAQgBAAAAABQAAAAAAAAIgFAAIAAgCIAAgBIgBABIAAACIgJACIAFgIIAAgBIADgKQACgJgBgDIAAAAIgGAQQgDAJgFAFIgCAAIgCAAIAAAAQgMACgIgBQgKgCgIgGQgGgGgGgJIgIgQIgKgSQgFgKgGgHQgGgHgKgEIgKgDIgLgBQgFgEgEgEQgEgIgCgIQgCgJACgIIAFgGIAEgHQAGgKgCgPQgBgHgHgTIAAAAIAAAAIAEARQADAJAAAHQAAAHgDAGQgCAFgEAGIgLARQgEAKAFAKIABAAIgCgIIABgHQABgFAFgHQgDAIACAJQgBAGAEAHQAEAGAGADIgFADIgEAEQgDAFAAAHIgBAEIgBAFIgGALIgHAMQgFAMAGAKIAAABIABgBIgDgIQgBgDABgEIACgGIAEgEIAFgJQgCARAGAVQADAOAGAIQgIgCgDgFQgCgFgCgIIgDgNIAAAAIAAAOQAAAJACAFQACAGAHADIACACQAGADAJAAIAlAGIAlAGQABAAADgDIAFgFIANgIIALgFIgJAIIgHAIQgDAFAAAFIAAABIAAgBQACgFAFgFIAJgIIAIgHQAFgEABgFIAAAAIADgBIALAAIAAAVIAAANIgEgGIgEgDIgDAGIgLATIgIARIgBABQABgSAFgLIAAAAIAAgBIAAABgAA1CqQgCAQABAGQACALALAGIAAAAIAAAAIgHgJQgEgFgBgGIAAgJIABgKIAAAAIgBAAgAg3CwIAAAJQgBAFgCAEIgFAHIgEAHQAIgJADgGQAFgJgDgJIgBAAIAAABgABzCBIAGAAIAFgBQAEAAADgDIAIgGQAGgGAJgMIAAAAIAAAAIgMALIgNAKIgRABIgSgBQgJgBgHACIgJACIgJABIgBAAIABABQADABADAAIAHgBQALgCAKABIANABIAMAAIgGACgACtBhIgEANIgHAMQAFgEADgHQADgHABgHIAAAAIgBAAgAg0AjQADAJAEAGQAGAHAIAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAgBIgBgCQgHgBgFgGQgEgFgEgIIgBgBIgBACgAh6gbIABABIAVAMQANAHAIAGQALAHAFALQAFALABAOQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABgOgFgMQgGgLgKgHQgJgHgNgHIgZgLIAAAAIgBAAgAABhNIAAASIABABIAAgBIABgSIgCgTIgBAAIABATgAhND3QAAgBAAAAQAAgBgBAAQAAgBgBAAQAAgBgBAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAIgBACIgDgJIgEgJQABgLAGgHQAEACADADIABABIAAAAIACACIABACIABAFIAAABQgCADgCAFQgBAFABAFIgBADIAAABgABKDmQgBgGgEgFIADgFIADgCIADgCIACAEIACAEIABAGQAAAEgBAEIgDAGIAAABQgCADgDABQABgGgBgHgABTDTQAAAAAAgBQAAgBAAAAQgBgBAAAAQgBAAAAgBIAAgBIgBAAIADgIQACgEADgBIABABQACAFgBAJQAAAJgEAFQAAgFgDgGgACahYIAAgOIAAgPQgBgIgDgFIgDgEIgCgBIAAgCQABgMgFgTIgCgEIgCgFIgEgCIgFgCIgKgFQgHgDgEABIgFABIgEACQgDABgCgCIgEgDIgEgCIgDgCIgDgDQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAIgFAAIgFAAQgDABgDgCIgFgEIgJgFIgLgBIgKABIgDABIgDgDQgDgDgGgBQADgFAEgCIABgCQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQgHgBgEgDQgFgDgDgFQgEgGAGgEQACgDAGgEIACgCIgBgCIgHgKQgDgEACgEIAdADIASABIARABIAQABIAPAFQAHADAJAFIAEADIAJAIIANAPQAOATAPAdQAIAPADAQQACARgDAQQgCAMgGANIgLAYIgCgSgAiuhbQgGgbAGgZQAEgUAKgWQAKgTAOgSQANgRAQgMQARgNATgHQAPgFARgBQAOgBATACIgBAEQABAEADAEIAFAHIgJAIQgFAFACAGQAFALAPAFQgDADgDAEQgEAAgIACIgNAEQgLACgGAAQgJgBgEgHIgBgBIgBABQgHAHgMAGIgWAIQgOAFgHAEQgLAGgHAJQgHAIgGANIgLAYIgEAJQgDAFAAAEQgBAFACAFIAGAHIgHAEQgEADgCAEIAAAAIgEgMg");
	this.shape.setTransform(19,27.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,38,55.8);


(lib.Символ50 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],-189.8,0,189.8,0).s().p("A9pGkIAAtHMA7TAAAIAANHg");
	this.shape.setTransform(189.8,42);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,379.6,84.1);


(lib.Символ49 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FF0000","rgba(255,0,0,0)"],[0,1],-189.8,0,189.8,0).s().p("A9pGkIAAtHMA7TAAAIAANHg");
	this.shape.setTransform(189.8,42);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,379.6,84.1);


(lib.Символ42 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACZBnQgZgrgCgvIAAgJQAAghAIghQAJghAQggQAOgbAIAAIB1gBQATAAAAAMQAAAFgFAGQgFAGgJAHQgTAOgLACIgDgCQgFgOgSAAIg1ADIgFAIIgKAmQAAADAFACQAEABALAAIBEgEQAOAAAHADQAHADAAAFQAAAFgHAHIgJAIQgLAIgMAFIgDAAIgDgFIgCgCIgngDIgaACIgEACIgBAFIABASQACAXAIAXQANAnAZAOIAVAKIAVAAQAHAAAVgLIAVgMQAJAAABAGIAAACQgDAFgJAIQgLALgUARQglAggJAAQgxAAggg5gAkkBnQgZgrgDgvIAAgJQAAghAJghQAIghARggQAOgbAIAAIB1gBQASAAAAAMQAAAFgFAGQgEAGgJAHQgTAOgLACIgDgCQgGgOgSAAIg1ADIgEAIIgKAmQAAADAEABQAFACALAAIBDgEQAOAAAHADQAHADAAAFQAAAFgGAHIgKAIQgKAIgNAFIgCAAIgDgFIgCgCIgngDIgaACIgEACIgCAFIABASQACAXAIAXQANAnAZAOIAWAKIAVAAQAHAAAUgLIAWgMQAKAAgBAIQgDAFgIAIQgLALgVARQglAggJAAQgxAAgfg5gAhFCBIAAgFIABixIAAgUIgBgBIgEgCIgHgGIALgNIAQgRIgEgDIgWABIgMgBQgKgCAAgFIAAgEIATgTQANgJAKgDIAMAGIBxAAQAkAAAAAjIAAAQIAAAEIgBBrQAAASgZATQgNALgLAFQgLAFgIAAIgfgBQgOAAgDADQgFADAAAPIABAKQABAGADAEIAHAEIABACQAAAGgIAIIgMAKQgTAQgJAAQgNAAgBgagAgShxIgBAfIAACAIADACIAQgQIAhABQAWAAAAgJIAAhmIAAgTQAAgJgFgFQgEgFgJAAIgiAAQgMAAgJADgAHpCSQgDgGgBgNIAAg8IAAgUIABhBQAAgrACgGQACgHANgPIAFgHQAIgKACgGIgDgEIhjAAIgCAEIAAAUIACByIAAAMQgBAmgGAtQgRATgMAJQgKAHgHABIgEABQgEAAAAgEIAIgPIABgDQABgIABgNIAAgEIAAgUIgBgaIAAgTQABgCABgSIAAgzIAAgKIAAgKQAAgSgDgIQgDgGgEgBIgBgDQAAgCAHgIQAGgHALgLIAAgDIgUABQgKAAgGgCQgGgCAAgGQAAgJASgNQAQgMALAAQARAIAhAAIBogCQAcACAAAOQAAACgEAJIgHALIgMAZQgCAGAAAoIgBA7IAAAUIAAAmQABAaACAEQAIAGAAADQAAAGgGAHQgFAGgJAHQgTAQgKAAQgIAAgEgIgAmfCIIgCgVIgBhcQgIACgPAMIgXARQgUAJgVAAQgUAAgJgLQgKgLgDgRQgDgOgBgOIAAgIIAAgfIAAgJQAAgkgDgLIgCgCIgHgEIgBgDIAAgBQAgguAPAAQAJAAAEAIQAFAIAAAPIgBAMIgCBjIAAAHQADAVAPAFQAVAAAXgLQAZgMAAgTIABgwIAAgTIgDgKIgCgCIgEgCIgGgFIAWgdQAQgSANAAQAIAAAEAHQAEAIAAAPIAAAOIgCDHIABABIABAMIAKAJQAAAHgFAHIAAABQgFAHgKAHQgTAPgOAAQgIgDgCgPg");
	this.shape.setTransform(56.6,16.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ACZBkQgbgwAAg0IAAgJQACAtAZAsQAgA4AxAAQAJABAlggQAUgRALgLIACgBQAJAAABAFIAAADQgHALgkAeQglAggJAAQgxAAggg5gAkkBkQgcgwAAg0IAAgJQADAuAZArQAfA4AxAAQAJABAlggQAVgRALgLIACgBQAKAAgBAIQgHALgkAeQglAggJAAQgxAAgfg5gAhFB5IAAgPQABAZANABQAJAAATgQIAMgKIAHAEIABACQAAAJgUAPQgTAPgJABQgOAAAAgfgAHpCPQgEgHAAgOIAAgSQABANADAGQAEAIAIAAQAKAAATgQQAJgIAFgGQAGAFAAADQAAAJgUAQQgTAQgKABQgIgBgEgHgAFjCSIAIgOIAAgCQAHgCAKgGQAMgKARgSQAGgtABgmIAAAIQAAAqgHA1QgRATgMAJQgNAJgIAAQgEAAAAgFgAmfCFIgCgVIgBhcQgIABgPANIgXARQgUAJgVAAQgUAAgJgLQgKgLgDgSQgEgQAAgUIAAgLQABAQADALQADASAKALQAJALAUAAQAVAAAUgJIAXgRQAPgMAIgCIABBbIACAWQACAOAIAEQAOAAATgQQAKgHAFgGIAFAFQAAAHgFAHQgFAHgKAHQgTAPgOABQgIgDgCgPgAFtAnIAAgBIABAaIAAAUgAgUBBQAAgOAFgEQADgDAOAAIAfACQAIAAALgFQALgFANgLQAZgUAAgPIAAASQAAARgZAUQgNAKgLAGQgLAFgIAAIgfgCQgOAAgDAEQgDABgBAHIgBgLgAlsBAIACjGIAAAGIgBDCgAD4gbIgDgGIgCgBIgngDIgaACIgEACIAAADIgBgSIABgFIAEgCIAagCIAnADIACABIADAGIADAAQAMgFALgJIAJgHQAHADAAAEQAAAJgQALQgLAJgMAFgAjFgbIgDgGIgCgBIgngDIgaACIgEACIgBADIgBgSIACgFIAEgCIAagCIAnADIACABIADAGIACAAQANgFAKgJIAKgHQAGADAAAEQAAAJgQALQgKAJgNAFgAn2gkIAChjIABAIIgDBiIAAgHgAFlhVIgBgDQAAgDAIgHQADAIAAASIAAAKQgBgVgJgCgAoqhmIgJgGIgBgDIAAgCIAIgLIACABQADALAAAlIAAAIQAAgagDgJgAIehyIAMgYIAHgMQAEAEAAAFQAAAEgLATIgMAZQgCAEAAAVQAAgoACgGgAhJhQIgHgGIALgMIABABIAAAUgACuhdIAKgmIAFgIIA1gEQASABAFAOIADACQALgCATgPQAJgGAFgGQAFACAAAHQAAAJgTAOQgTAPgLACIgDgCQgFgPgSAAIg1AEIgFAIIgFAWQgFgCAAgCgAkPhdIAKgmIAEgIIA1gEQASABAGAOIADACQALgCATgPQAJgHAEgFQAFACAAAHQAAAJgSAOQgTAPgLACIgDgCQgGgPgSAAIg1AEIgEAIIgGAWQgEgBAAgDgAmhhmIgGgEIgGgFIAKgNIACABIADALIAAATgAAyhzQgEgEgJAAIgiAAQgMAAgJADIgBALIABgfQAJgDAMAAIAiAAQAJAAAEAEQAFAFAAAKIAAATQgBgJgEgFgAGeiHIACgEIBjAAIADAEQgCAGgIAKIhcAAIgCADgAhlh9IAAgEIAKgJIAMABIAWgBIAEADIgQARIgKABQgWgBAAgHgAFoh2QgWAAAAgKQAAgGAGgGQAGACAKAAIAUgBIAAADQgLALgGAHg");
	this.shape_1.setTransform(56.6,18.6);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0.2,113.2,34.1);


(lib.Символ41 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEJC9IABgEIAFgMIABgEIACi0IAAgPQAAgJgCgFIgCgCIgGgFQACgFAGgIIACgCIALgQIgCgBIghgBIABAAIgEAAQgIgCAAgHQADgIAOgLQAMgMALgDIAMAFIAaACIA8gCQAmAAAKADQAYAIAAAbIAAAPIgDCdIAAATIABAJQAEAQAKAHIABADQAAAEgHAHIgPAPQgVASgHAAQgIAAgFgHQgDgHgBgOIAAgCIAAgBIAAgBIABhBIABgqIAAgCIgBgqIgFgEIhAAAQgFAAAAAmIAAAHIACA9IAAALQgCAYgGAQQgIATgRAHIgUAGIgDABgAFEhQIgBACIAAATIABAYQAAAGA2ABIALAAQAHAAABgLIABgEIAAgKQAAgUgIgFQgFgCgWAAIghAAgAHwB7IAAgLIADh4IAAgGQAAgkgDgLIgCgCIgHgEIgCgDIAAgBQAhguAPAAQAJAAAEAIQAEAIAAAOIAAAPIgCC6IABAFQABAZAQAGQAWAAAWgMQAVgMADgRIAAgEIgChTIACgwIABgNIgDgWIgCgCIgLgIIAXgcQAQgSANAAQAIAAAEAHQAEAIAAAOIAAAPIgCDHIABABIABALIAKAKQAAAHgFAHIAAAAQgFAHgKAIQgTAOgOAAQgIgCgDgPIgBgWQgIACgPAMIgYARQgSAKgWgBQgtAAgEhFgAjmB7IAAgLIACh4IABgGQAAgkgEgLIgCgCIgGgEIgCgDIAAgBQAhguAOAAQAJAAAEAIQAFAIAAAOIgBAPIgBC6IAAAFQABAZARAGQAVAAAWgMQAWgMACgRIABgEIgChTIACgwIABgNIgDgWIgDgCIgKgIIAWgcQAQgSAOAAQAIAAAEAHQAEAIAAAOIgBAPIgBDHIAAABIACALIAKAKQAAAHgGAHIAAAAQgFAHgJAIQgUAOgOAAQgHgCgDgPIgCgWQgHACgPAMIgYARQgTAKgWgBQgtAAgDhFgAAQDAIgCAAQgGAAAAgGIAMgVQAMgRABgLIAAgCIgBiTIAAgUIgBgEIgBgBIgIgHQACgHAGgGQAGgIALgJIAAgEIgCAAIgfABQgMAAgEgCQgGgCAAgFQAAgJAPgNQARgOAJgBIAIAGIB7ABIgGAAQAZAAANAOQAMAOAAAbIAAAJQgCAKgEAKQgHAPgOAQIgKAJIAKAJIAGAGQAJAHAHAOIADAWIAAAUIAAAwIgCAKQAAAwhAAAgAB7CbQAUAAAGgLQAFgIAAgRIAAgCIAAgCQAAgxgDgKQgJgbgkAAIgRAAQgIAAAAAbIAAAJIACAdIgBANQAAAMgCAGQgDAKgNAQIABADIADABIAHAAIAfAAIACAAgABShJIAAATIAAABIABA4QAAAEAEAAQAOAAAMgEQANgDAKgGQALgHAGgMQADgGACgHIABgMQAAgLgIgJQgHgJgLAAIgpAAQgKABAAAFgAnSDAIgDAAQgGAAAAgGIANgVQAMgRABgLIAAgCIgBiTIAAgUIgBgEIgCgBIgHgHQACgHAFgGQAHgIALgJIAAgEIgCAAIgfABQgMAAgGgCQgGgCAAgFQAAgJAQgNQARgOAKgBIAIAGICTABQALAAAJAEQAJAFAAAIIAAADIAAAEIgEADIgOAOQgOANgFAAIgGgFQgBgEgFgEQgEgDgGgBIhDAAQgJABAAAFIAAATIAAABIAAA4QABAEADAAIA+gEQAMABAKAEIAQAPQAKAHAGAOIAEAWIAAAUIgBAwIgBAKQAAAwhAAAgAlnCbQAUAAAFgLQAFgIABgRIAAgCIAAgCQAAgxgEgKQgIgbgkAAIgSAAQgIAAAAAbIABAJIABAdIAAANQgBAMgCAGQgDAKgNAQIACADIACABIAHAAIAgAAIABAAgApxC1QgkgWgRgjQgPgegDgpIAAgPIAEgvIAVg8QATgwAJAAIALgBIBzABQAHAEAAAFIgGALIgRARQgNAKgHgBIgGgHQgIgFgIABIg3AAQgHAIgHAWIgCAJIgEAgIgBAQIAAAMQABAWAFASQAGAWAMAOQABAKASANQATANALAAQAPAAAUgJQAVgIAGgBQAHABAAAHQAAAJgFABIgDADQg9A7gWAAQgIAAgRgKgAIxiYIgEgFQgFgEAAgEIAHgRQAEgJAGAAIAQANQAPAMAHAAQAGAAARgMQAQgOAEAAQAIAAAAAIQAAAEgGAIIgIAMQgXAegSAAQgPAAgbgWg");
	this.shape.setTransform(69.8,19.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AEJC9IABgFIAFgLIAAgBIAUgHQARgGAIgUQAGgPACgYIAAAJQAAAfgIATQgIAUgRAGIgXAIgAHwBwIAAgKQAEBGAtAAQAWAAASgJIAYgRQAPgMAIgCIABAWQADAOAIADQAOAAATgPQAKgHAFgHIAFAGQAAAHgFAHQgFAHgKAHQgTAPgOAAQgIgDgDgOIgBgWQgIACgPAMIgYARQgSAJgWAAQgxAAAAhQgAjmBwIAAgKQADBGAtAAQAWAAATgJIAYgRQAPgMAHgCIACAWQADAOAHADQAOAAAUgPQAJgHAFgHIAGAGQAAAHgGAHQgEAHgKAHQgUAPgOAAQgHgDgDgOIgCgWQgHACgPAMIgYARQgTAJgWAAQgwAAAAhQgAAODAQgGAAAAgGIAIgOIB8AAQBAAAAAgwIACgKIAAgxIAAABIAABEIgCAKQAAAwhAAAgAnVDAQgGAAAAgGIAJgOIB8AAQBAAAAAgwIABgKIABgxIAAABIgBBEIgBAKQAAAwhAAAgApxC1QgkgWgRgjQgSgkAAgyIAAgFQADAoAPAfQARAjAkAWQARAKAIAAQAWAAA9g8IABAAQAHAAAAAIQAAAIgFACQg/A+gXAAQgIAAgRgKgAGPC3QgEgIAAgPIAAgSQABAOADAHQAFAHAIAAQAHAAAVgSIAPgPIAGAGIABADQgBAHgVATQgVASgHAAQgIAAgFgHgABECHIgDgBIgBgEQANgPADgLQACgGAAgLIABAHQAAAVgDAJIgFALgAmfCHIgCgBIgCgEQANgPADgLQACgGABgLIAAAHQAAAVgDAJIgFALgAKtBpIACjGIAAAFIgBDDgAgpBpIABjGIABAFIgCDDgAIkBeIACi6IAAAFIgBC6IgBgFgAiyBeIABi6IABAFIgCC6IAAgFgACXA4QgJgbgkAAIgRAAQgGAAgCAQIAAgJQAAgbAIAAIARAAQAkAAAJAbQADAKAAAwQgBgegCgIgAlMA4QgIgbgkAAIgSAAQgGAAgBAQIgBgJQAAgbAIAAIASAAQAkAAAIAbQAEAKAAAwQgBgegDgIgAG+BIIADieIAAAGIgDCrIAAgTgAJ4AHIAAgFIACBTIAAAEgAheAHIAAgFIACBTIgBAEgAGMAHIgFgEIhAAAQgEAAgBAZIAAgHQAAgkAFAAIBAAAIAFAEIABAoIAAACgACrgLIAKgKQAOgQAHgPQAEgKACgKIAAALQAAAOgGAPQgHAPgOAQIAAAAgAqLgNIABgTIAEgfIACgJQAHgXAHgHIA3gBQAIAAAIAFIAGAHQAHAAANgKIARgQQAGAEAAAEIgGAMIgRAQQgNAKgHAAIgGgHQgIgFgIAAIg3ABQgHAHgHAXIgCAJIgEAfIgBAKIAAgLgAHwg+IgJgFIgCgDIAAgCIAJgLIACABQADAMAAAkIAAAGQAAgYgDgKgAjng+IgIgFIgCgDIAAgCIAIgLIACABQAEAMAAAkIgBAGQAAgYgDgKgAEOgqIgGgFQACgFAGgIQACAEAAAKIAAAPQgBgJgDgCgAAfgkIgJgJQACgGAGgHIABACIABAEIAAAUgAnDgkIgJgJQACgGAFgHIACACIABAEIAAAUgAJ4g+IgNgJIALgNIACACIADAXIgBANgAheg+IgNgJIAKgNIADACIADAXIgBANgACXhGQgHgJgLAAIgpAAQgJAAgBAFIAAgTQAAgGAKAAIApAAQALAAAHAJQAIAJAAALIgBAMQgCgHgFgFgAGGhOQgFgDgWAAIghAAIgGABIgBABIAAgTIABgCIAGgBIAhAAQAWAAAFADQAIAFAAAUIAAAKIgBAEQAAgPgHgEgAk0hDQgBgFgFgDQgEgEgGAAIhDAAQgIAAgBAFIAAgTQAAgGAJAAIBDAAQAGAAAEAEQAFADABAFIAGAEQAFAAAOgMIAOgOQAEAEAAAFIAAAEIAAAEIgSARQgOAMgFAAgAgIhWQAAgGAGgHQAEACAMAAIAfgBIACAAIAAAEQgLAIgGAJIgQAAQgWAAAAgJgAnshWQAAgGAGgHQAGACAMAAIAfgBIACAAIAAAEQgLAIgHAJIgPAAQgYAAAAgJgAD6hRIABABQgMgBAAgIQACgFAGgHIAEABIgBgBIAhACIACABIgLAQIgCACgAIxiZQgJgHAAgFIAFgMIAEAEQAbAXAPAAQASAAAXgeIAIgMQAGABAAAHQAAAGgOASQgXAegSAAQgPAAgbgXg");
	this.shape_1.setTransform(69.8,21.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,139.6,40.7);


(lib.Символ39 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("EAA3AkeIgigLIgVgJQgLgGgIACQgLgEgQADIgbAIQgjAJgqgGIgPgDQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBIgXgJQgKgCgLgJIgRgRQgQgPgIgNQgJgRACgTIAAgCQADgnAAgiIACgJQABgZALgbIAAgCIAAgBIABgBIAAgBQAQgdAkgOQAfgMAnADIACACQAiAZAUAVQAZAcANAgQALAcAFAoIAFBGQAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAgBQABAAAAgBQALhNgOg+QAWg6AugfQAQgMAWgEQAHgCAhgEIABAAQAVgEAbArIABABQAVAdAOAnQAIAUADAOIAHAcIAAAFIAHA2QAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAgBQABAAAAgBQANg/gchTIgFgOQATguAVgiQAOgVAVgRQANgKAcgRIABAAQAKgHAOAEQAKABADAFQAGADADAHQAOAMAJAMQATAbAkA3QAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQABAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQgBgVgSghIgMgVIATgtQALgYAPgRQAOgQAZgNIASgHQALgEAGgFQAdAwAKA0QAHArgFA8IABADQgBAVgJAWIgIAUQgSA0ggAOQgQg1gYgZQgGgGgKACQgJADgDAJQgCAJgSAsIgaApIgXAaQgOAPgOAIQgvAbhKgPIgIAAQgGAKgLAKIgVAQQgKAIgKAGIAAAAQgRAKgWAEIAAAAQgNACgYAAQgZgBgmgHgEgGRAiyIhfgyQgMgHgKAIIgiABQgUACgOgGQgmgQgEgzIAAgEIAAgJIgCgLIABgZIAMhFQAGgdAPghIAfg6QAWALAWAdIAiAzIAEADQgeA2AJBaIABABIABgBQAFgrAGgZQAKgmARgYQATgdAfgHQAOgDAvAAQApA6AQBOQAFAcAMB4IgFgCQgDgCgDACIgJADQgZANgbAAQgYAAgagKgAhVfXQgSgLgUgFIAAAAQgrgLgvAZQgwAbgHAoQgLhMgig9IAAAAIgJgPQgGgIgHgEIgHgDQgggHghAKQghAKgUAYQgRgsgrgiQgagVgdAEIgMgUIgBgBIgGgIQgKgRgQgPQgagcgpgMQgRAAgJALIgBABQgoAtgKA2IgEgeQgRihAUiFQAZgzAJg9QAJg7gHg3QgGgxgjgiQAUgCAcgKIAIAJQAnArAaBOQAZBLgKBgQgJBXghBQQABAAAAABQAAAAAAAAQABAAAAAAQAAAAAAgBQAyhcANhhQAOhpgihcQgOgogOgbQAXAKAWAOQAkAXAnAzQA2BIALAMQAMAMAOgJQAPgJgEgQQgOg+gsg0Qgogwg8giQAZABAUAEQA0AJAtAbQAnAYApAqQAEAEAFgDQAFgEgDgFQgzhUiBgnQgfgJgkgEQgogFgjAFQgigKgegDQh5gOiCAyIh0AzQhGAegzAHIgEgIQgphGhXhYQh4h5gVgZQhPhfgHiOQgFheAeikQAUhsA3inQBGjRAQg8QAjiCAAh+QAAgmgDgjQARAcAPAVIADAFQANAagIASIgCABQAAAAAAABQAAAAAAAAQgBAAABAAQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAXgLgJgiQgDgPgJgOIgBgCIgLgZQgMgkgahIQgBgkAagdQADgDAAgFQgBgGgEgCQgcgNgJgGQgUgPgDgTQgBgLALgOQAGgHAPgNQARgPAZgPQANgIAigRQAEgCAAgFQABgFgDgCQgygpgOguQgPgvAWg6QAMgfAag1QAeg7AKgZQA9iPAcg1QA6hrBHg+QA7g0BfgoQAigNCJguQBZgeA/ggQBOgoA5gzQAkA6A9ANQAxALBKgSICGgnQBRgXAugBQgUAmgUBCQgqCGArAwIgXAkQgOAUgOAMQgEADAAAHQAAAGAEAFQA1A6BKAYQhGApAMA3QAEASApA7QAeAqgQAqIABAAQALgZgEgdQgDgWgOgfQgDgIgMgWQgKgSgDgMQgIgbAdgYQAMgKApgWQAGgDgBgIQgBgJgHgBQhMgMg2hBQAKgMAPgXQAOgaAJgKQAFgGgBgHQgBgHgGgEQgagTAIg/QAEgcATg7QAUg7AYgoQBAAKAmA6QAGAJAIgDQBIgYA1ADQA/AEA0AsQAxApAdAMQAVAIAZAAIAwgDQAZgDAYARIAnAjQALALAWAMQAaAOAJAHQAgAWADABQAQAJAWgGQAKgDApgUQAhgRASADQAVADAgANIAzAVQAPAGAvANQArAOAMAQQAUAaAMAvIAOBQQAKA6ACAaQAEAygMAiQgCAJAIAFQAqAbAOBEQAIAlABBMQAAAbgEBDQgEA7ABAiQABAYAJBRQAHBLABAtIgBABQABAJgCATIAAAFIAAABIAAAHQAAAigJAWQgUBPg7AhIgEADQgHADgIAGQgCADACACIAAABIgBAFQACBHAQA8QAVBMApAnIACAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAgBQgthygFhwQAGAAAEgDQA6gaAbg8QAWgxADhMQA8hNAyhdIgXBfQgRBBgHAfQgnCkATCGIADAkQAFAmAOA1QAQA7AUAqQAVA3AwBlQA6B6AWBKQAgBrgHBmQgNC6huCsQhyC0ilBKQgYAFgTAJQhuguiBgUQiCg5hxgSQhngRhUApQhTApg0BbQAAAAAAABQAAABAAAAQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAQABAAAAAAQABgBAAAAQBJheBagdQBFgWBwAaQAmAJAkANQgwAAghADQiGALhZA+QhsBNAbB7QABADAEAAQAEAAABgDQAJhAAUgpQAZgyAwgcQA7giBpgBQgRAQgUAbQgkA0gLBhQgHBKANA+QASBVA3ARQABABAAAAQABAAAAgBQAAAAAAAAQAAgBgBAAQhHhLAKiYQAFhKAfg8QAOgaAXgPQAIgGAogTIA8AEQgfAagTAwQgQAngGAwQgFAyANAyQANAzAfAnQgiAKgXAoQgUAigGArIAAACQAAALgIAGIgCABQgWAJggAmQgQATgIAWIgPACIgKABQgLACgIADQgfAHgiAmQgjAmgEAvQgJgRgOgRIgBgCQgOgNgQgDQgOgDgbACIgDABIgHACQgoARgeArQgcAogLAvQgYg4gegUIgGgCQgQgMgUADQgXgBgaAKQgXAJgTAPQgsAmgKAzQgWg3guglgAg4bpQgEACABADQAMArAMA5IASBmQACAHAHgBQAIgCAAgHQAFg8AJgkQAGgZAQgYQAIgNAYgeQAEgFgEgEQgDgFgFADQg5AfgNBpQgIgugHgaQgKgngQgcQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBgBAAAAIgCABgAChb3QgDACABADQADARAMAVIAVAkQAeA2ACAzQAAAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAgBQAAAAAAgBQAHgpgRgoQgghJgXgeIgDgBIgDABgAiPbxQgjAUgXAsQgTAmgGAuQAAAFAEABQAFABAAgEQAMhRBChAQADgCgCgDQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAAAAAIgCABgAjnSJQgyA/gZBfQgWBSAABeQgNBHgHAdQgNA2gUAsIgoBYQgVAzgEApQgBAFAEAAQAFAAABgDQARgwAbg3QAMgcAlhJQATglAMgnQAPAuAaAdQAeAfAoAEQAPAGAQADQBNANAqhBIgBgBIgBAAQgTASgrgBIANgIQAYgHAUgSIADgDQASgSAMgaIACgEQAUA2ApAgQAtAhA8gCQAzgCAigeQAegcALguIACAAIABAFQALAsArAxQAZAbAyA1QACADADgCQAEgCgBgDQgJgjgsg2Qgsg3gKghQgJgcAKgnIAVhBQAQg0gUg0QgBgBAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAAAABQAEAhgGAjQgFAcgPAlQgBhTgMhAQgShphahgIgCAAQAAAAAAABQAAAAAAAAQgBAAABAAQAAABAAAAQA8BUARBhQgRgdgfgVIgYgYQgOgPgIgLQgmg4gLhPIgCgEQgFgegJgWQgEgBgHAEQgJALgKAWIgRAjQgPAbgWAWIABghIAAhzQAAhrgDhNIAsABQAPgCATAIQAPAHANALIAFAEQAbAQAVAUQARARAWAbIAlAuQAoAyAtAaQAyAcA7ACQAJAAAAgJQAAgJgJgBQhPgLhEhOQhIhfgpgnIAZAKQAaAMAcAZIAwAuQAoAnAkARQAoAUA0ACQAzACBYgQQBjgSAogCQAqgBBrAJQBfAJA1gGIAHgBQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQALgGAJgHIACgBQAMgGAOgMIAXgVQArgoAxhUQBMiDANhtIALgHQAggWAUgPQABAmAAATQgBAfgEAbQgPBRg5BQQAAAAAAABQABAAAAAAQAAAAAAAAQAAAAABAAQBGhTAahzQAHALAiAnQAaAfAIAXIABABIABgBQgGg2gdg4IgOgdQgGgQgBgPQgCgVALgbIAVgtIABgFQAHgPACgQQACgZgBgRQAGhRg6hTQgSgZgkgqQgngsgPgVQgvhBgnhhQgphogBhiQgBhqAshfQACgEgEgDQgEgCgCAEQhCBnAECJQAEB7A7B7QAGARABAMQgCAEABAGQgGAQgGAJQgKgBgGALQgHALAFAJQANAaAdAdIAzAwQAgAgATAWQAaAfAPAeQAZAygMA1QgMAxgoAlIgDABQgnAOgfADQgiAEgngGIhIgLQgngEghAEQiPAQiCBAQgzAZhGAyIh2BTQiHBahqAIQgUgKgZgHIgEgDQgjgegkg8Qg2hbgdiAQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAgBAAQgBAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAOB+A0BqQASAkAXAfQgegFgqgCIgDgBQgFgmgKg1IgRhaQgfipghhmQAAAAgBgBQAAAAAAAAQgBgBAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAABAAAAIAUCBQAPBPAHAxQAKA9ANB5QgNgBgIALIgrACIAAgWQAAgJgIAAQgJAAAAAJIgBAXQgoAEggAGQANgQAXgwIADgGQAUg+AHgbQARhGgLgbIAAAAQgRAsgeBZQgdBLgoAtQgGACgKgBIgRgEIgCgBIgCABIgBAAQhkARhCgJQhUgMhBg5Qg0gugvhMQgbgtgvhdQg9h7gQgcQguhUgvg5Qgyg7hVgiQghgOg3gHQhMgJgOgDQgqglgggvQgog/gOhHQgOhLAThEIAkgzQAWgfANgWQA0hbgUh9QgIg3g1ihQgBgEgEABQgEABABAEIAoCKQAUBPABA+QABA2gWA1QgSArglA0QhJBlgQAqQghBTArBNIADADQgKghgCgiQAAgZAHgeQAIgvAmg8QgUBFAPBKQgFAzAfBAQAhBBAvAVQgXAGgUARQgTARgMAYQgUAlgHA4IgHAoIgHAlIAAABQgOAmglA7QgrBDgNAcQgvBlAyBaQADAEAFgCQAFgCgCgEQgRgogGgWQgIgiAFgfQAEgXAPgXIAegnQAhgsAOgbIAAACQgSCMAxCyQAdBwAwBDQhAgQgagrQgWgkgNhGQgShdgFgRQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAAAABQAFAdAABYQgBBKAQAqQATAyA3AeIASAMQAxAbBLADQByANDEAiQDeAmBYAMQAMABAcgcQAdggAIgHQAjgaBPgmQA5gaAdgPQgYAXgxAsQgmAjgUAhQgYAogEArQAAABAAAAQAAABAAAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAPgsAqgqQAOgPBAg2IBEg5QAmgmAHgkIAEgFQAOgBALgJQAegBA8AAQgDA9AAB7IAABsIggg1QgTgZgMgCIgcAyIhWCfQg0BigVAvIgEAKQAIiWArhdQABgDgCgCIgDgBIgCACgAHEWZQgQCDAJA3QAQBeBWAzQAEADADgEQADgEgDgDQgtgsgTgcQgdgqgHgvQgEghAEgwIAHhRQABgEgFAAQgEAAgBAEgAnVXCQgGABABAFQACAygDAcQgFAogTAjQgKASgeApQgaAkgLAYIAAACQABABAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQBFhKAZgzQAnhNgVhKQgCgEgEAAIgBAAgAPKRBIAAABQASABAegFQAigFAOgBQAfgBAbgYQAZgQAngkQA1gxBNhkQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQgRAOhTBQQg8A6gvAaIgBAAQhBALhSgCIiSgJQhPgGg7AOIhLATQgrAIgjAAIgBABQAAABAAAAQgBAAABABQAAAAAAAAQAAAAAAAAQAbANAeAAQAXABAkgHQBbgSBVAGIBrAKQA9AEAsgFQgWAJgiAIgAW2MzQgcBOgNAeQgZA5ghAqQgBAAAAABQAAAAAAAAQAAABABAAQAAAAABgBQAsgeAcg+QAag5ADg6QAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgCABgAm6EdQgHADACAIQAXBOAmAvQAxA+BFADQALABACgMQABgMgLgCQg6gOgsg0QgegkghhHQgDgEgEAAIgFABgAwHjsQAAAAAAABQAAABAAAAQAAABAAAAQABAAAAABQA8AiB7BCQBqA9BEA1QBYBEAtBgQArBaAGB1QAAANANAAQAMAAABgNQAJhugthlQgrhhhXhIQhLhAhyg4QgagMi1hOIgBgBIgDACgAAJsxQAAAAgBABQAAAAAAAAQAAAAAAABQAAAAAAABQAJA+AABcIgCCbQAAAFAFAAQAFAAAAgFQAEhvgBgtQgChXgOhDQAAgBgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgBAAgEgKPAgcQgJgSgOgMQgNgIgKAMIgJAKIgBgBQgIgegRgrIgdhJQAGhcAwg5QAmAQAWAUIAKAJIABABIAOAPQAHAJADAIIAAACQAGANAFAdQAAADgBACIAAABQgUAfgKAqQgIAnABAqIgDAaIAAABIABADIgCAAQgBADgDAAQgDAAgBgDgAJxeTQgKg4gegjQALgbARgUQAJgKANgIIAZgNIAPAiIAPAkQAEALAGAmIAAAAQAFAfgIAfQgHAfgTAYIgDADQgSAZgZALQAKg1gKg1gALCb0QgHgWgNgOIgBgCIgDgEIgBgBQAPgsAKgVQARgkAZgJIACAEQAWAugHBJQgHBMghAqQADgogWgwgAUTrsQgCggAChbQAChOgGguQgIhBgTgrQgJgTgTgTQgEgDgKgFQgCgBACgNQAJhjgvifQgHgZgFgOQgIgZgLgKQgMgLgYgLIgogRQg4gegfgMQg3gXgmAIQgQADgXAKQgZALgMAFQgSAHgWgPQgYgUgLgHIgdgRQgQgKgMgKIgagYQgSgNgOgDQgRgEgXACIgoAEQgZADgcgOQgPgIgfgYQgkgbgogNQgkgLgygDQgkgCgwAMQgYALgDgEQgOgPgLgKQgfgbgygHQAcgpAhgSQAKgFgCgMQgBgMgLgCQg9gNgmgTQgxgYgcgqQgigzAugoQAagXBAgjQAIgFABgJQACgKgHgHQg1g1gUgfQgZglAQgfQBVAICtATQA1AFBfACQBqACApADQA5AEBLALQAzAOBKAbQA8AWBRAuIAeAVQA5A3ARAOQA9A/AxBCQB3ChB/DxQBDB/AVCHQAVCKgcCLQgSBfgxBzIhcDIQgNhsgDgqgA2+sLQgxjcArjXQAjirBYiyQBSimBziUQBuiNCIhnQCQhrChg4QB6grCSgKQB2gJCcAMQgGARAEATQAGAiAaAkQASAYAhAjQhEApgUAVQgpAqAVA3QAjBeCRAnQgcAZgWAmQgugBhEAQIhxAcQheAWgtgDQhNgFglg/QgCgEgFAAQgEgBgEAEQg+A+hiAvQgyAYiDAvQh1Arg9AhQhdAzg6BHQg5BGg3BxIhaDDQgMAZgcAzQgWAugCAkQgDApATAlQAQAfAiAfQgrAWgVAPQgjAYgOAdIgCAEQgRgzgNg3g");
	this.shape.setTransform(159.7,234.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,319.5,468.5);


(lib.Символ38 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ah1B2QgxgxAAhFQAAhEAxgxQAxgxBEAAQBFAAAxAxQAxAxAABEQAABFgxAxQgxAxhFAAQhEAAgxgxg");
	this.shape.setTransform(16.8,16.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,33.5,33.5);


(lib.Символ31 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AjMDNQhUhWgBh3IAAAAICfhmIgZDfIBKg9Ig2CbICxjRIiUATIAKjPIjACjQAHhrBNhOQArgqAzgVICiBuIhxBuQBFgXA/ghQAsgYAlgkIiyhaIAMgjIAOgBQB4ABBVBUQBUBWAAB2QAABohABOIhwiDIAfDJQhBAmhPgBQh2AAhWhUg");
	this.shape.setTransform(29,29);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,58,58);


(lib.Символ29 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC3300").s().p("AoUIUQhwhvg3iIIgBg7IBGBLQAyBnBYBZQDNDMEfAAQEfAADMjJIgqBUIBNgpQjbDXkzAAQk3gBjdjdgALDDwIg6AWQAxh6AAiMQAAkgjNjMQjMjNkhAAQg1AAgzAHIBWgoIgmgVQAcgCAcAAQE4ABDdDcQDdDdAAE3QAADbhuCvIg9AigArxAAQAAk3DdjdQCdicDKguIAjASIiYAqIAjAYQiCAzhrBrQjNDMAAEgQAABMAPBGIgug6IgJBGQgQhMAAhSg");
	this.shape.setTransform(75.4,75.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,150.9,150.8);


(lib.Символ26 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("ApCJCQh6h6g7iTIgChAIBMBSQA3BwBgBhQDeDdE4AAQE4AADdjaIgtBbIBUgtQjuDplOABQlSgBjwjwgAMAEEIg/AYQA1iEAAiYQAAk5jejeQjejek6AAQg6AAg3AIIBdgsIgpgXQAfgCAeAAQFTAADwDwQDwDwAAFSQAADvh3C9IhDAmgAsyAAQAAlSDwjwQCqiqDcgxIAmATIilAtIAmAbQiNA3h0B0QjfDeAAE5QAABTAQBMIgyg/IgKBMQgRhTAAhZg");
	this.shape.setTransform(81.9,81.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,163.9,163.8);


(lib.Символ24 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AtWNXQh4h5hQiIIAcglIEdErIgCgYQE6EcGtAAQHQAAFHlJQBeheBEhpICchkQhYDFimCmQliFin1ABQn0gBliligAy5AAQABn0FiliQCaiaC2hXIBNAbIiqA8IA+AfQiBBKhwBwQlIFJgBHOQABDfBNDCIg8hRIgKCUQhijeAAkGgARgAAQAAnOlJlJQlHlInQAAQjHAAiwA/IBUhSIhWgOQCyg5DHAAQH1ABFiFiQFiFiABH0QAADfhHDCIh3A2QBjjYABj/g");
	this.shape.setTransform(121,121);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,242,242);


(lib.Символ21 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.376)").s().p("Eg2wAaOMAAAg0bMBthAAAMAAAA0bg");
	this.shape.setTransform(350.5,167.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,701,335.7);


(lib.Символ18 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#470902").s().p("AA+AgQgWgKAAgOQAAgMAWgKQAWgJAfAAQAfAAAWAJQAWAKAAAMQAAAOgWAKQgWAKgfAAQgfAAgWgKgAinAOQgWgJAAgMQAAgOAWgKQAWgKAfAAQAfAAAWAKQAWAKAAAOQAAAMgWAJQgWAKgfAAQgfAAgWgKg");
	this.shape.setTransform(19,4.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,38.1,8.5);


(lib.Символ17 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#02F3FE").s().p("Ah4DbIAAjkIAAgKIhCAAIgLAAIDFjHIDGDHIgLAAIhCAAIAAAKIAADkg");
	this.shape.setTransform(19.9,21.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#037176").s().p("Ah4B8IAAgKIDxAAIAAAKgAB5hxIAAgKIBCAAIALAKgAjFhxIALgKIBCAAIAAAKg");
	this.shape_1.setTransform(19.9,32.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,39.7,44.9);


(lib.Символ15 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#04F5FE").ss(4,2,0,3).p("Egx/gX0MBj/AAAMAAAAvpMhj/AAAg");
	this.shape.setTransform(320,152.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2,-2,644,309);


(lib.Символ11 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.blik();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,40,32);


(lib.Символ5 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.fog();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,640,155);


(lib.leg_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.leg();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,162,97);


(lib.hand2_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.hand2();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,155,415);


(lib.hand_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.hand();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,51,153);


(lib.chest_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.chest();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,70,65);


(lib.Символ57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ58();
	this.instance.setTransform(320,152.5,1,1,0,0,0,320,152.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},6).to({alpha:1},7).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.6,-2.6,645.3,310.3);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ54();
	this.instance.setTransform(0.1,25.7,0.842,0.842,0,0,0,16.5,25.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({guide:{path:[0.2,25.7,0.7,34.8,7.3,41.4,14.4,48.5,24.3,48.5,34.3,48.5,41.4,41.4,48.5,34.2,48.5,24.4,48.5,23.7,48.4,23.1]}},20,cjs.Ease.get(-1)).to({guide:{path:[48.4,22.9,48,13.6,41.3,7.2,34.2,0.1,24.3,0.1,14.3,0.1,7.2,7.2,1.1,13.1,0.3,21.5]}},19,cjs.Ease.get(1)).wait(1).to({guide:{path:[0.3,21.5,1.1,13.1,7.2,7.2,14.3,0.1,24.3,0.1,34.2,0.1,41.3,7.2,48,13.6,48.4,22.9]}},19,cjs.Ease.get(-1)).to({guide:{path:[48.4,23.1,48.5,23.7,48.5,24.4,48.5,34.2,41.4,41.4,34.3,48.5,24.3,48.5,14.4,48.5,7.3,41.4,0.7,34.8,0.2,25.7]}},20,cjs.Ease.get(1)).wait(1));

	// Слой 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.349)").s().p("AigChQhDhEABhdQgBhdBDhDQBDhCBdAAQBdAABDBCQBEBDAABdQAABehEBDQhDBDhdgBQhdABhDhDg");
	this.shape.setTransform(24.2,24.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(80));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,2,0,3).p("ADyAAQAABkhHBHQhHBHhkAAQhjAAhHhHQhChCgFhaQAAgIAAgHQAAgEAAgGQAEhdBDhDQBHhHBjAAQBkAABHBHQBHBHAABjg");
	this.shape_1.setTransform(24.3,24.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(80));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-13.8,-1,63.4,50.5);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ49();
	this.instance.setTransform(189.8,42,1,1,0,0,0,189.8,42);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14).to({alpha:0},15).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ50();
	this.instance_1.setTransform(189.8,42,1,1,0,0,0,189.8,42);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},14).to({alpha:1},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,379.6,84.1);


(lib.Символ45 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ42();
	this.instance.setTransform(274.2,41.1,1,1,0,0,0,116.5,34.2);

	this.instance_1 = new lib.Символ41();
	this.instance_1.setTransform(0,40.7,1,1,0,0,0,0,40.7);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,270.8,41.2);


(lib.Символ44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ45();
	this.instance.setTransform(137.1,20.6,1,1,0,0,0,137.1,20.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:139.1},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,270.8,41.2);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4
	this.instance = new lib.Символ44();
	this.instance.setTransform(137.1,20.6,1,1,0,0,0,137.1,20.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(64).to({_off:false},0).wait(1).to({regX:136.4,scaleX:1.01,scaleY:1.01,rotation:0.7,x:136.4},0).wait(1).to({scaleX:1.02,scaleY:1.02,rotation:1.3,x:136.5,y:20.7},0).wait(1).to({scaleX:1.03,scaleY:1.03,rotation:1.8,x:136.4},0).wait(1).to({scaleX:1.04,scaleY:1.04,rotation:2.2,x:136.5,y:20.6},0).wait(1).to({scaleX:1.05,scaleY:1.05,rotation:2.5,x:136.4},0).wait(1).to({scaleX:1.05,scaleY:1.05,rotation:2.8},0).wait(1).to({scaleX:1.06,scaleY:1.06,rotation:3},0).wait(1).to({scaleX:1.06,scaleY:1.06,rotation:3.2},0).wait(1).to({scaleX:1.06,scaleY:1.06,rotation:3.4},0).wait(1).to({scaleX:1.07,scaleY:1.07,rotation:3.6},0).wait(1).to({scaleX:1.07,scaleY:1.07,rotation:3.7},0).wait(1).to({scaleX:1.07,scaleY:1.07,rotation:3.9,y:20.5},0).wait(1).to({scaleX:1.08,scaleY:1.08,rotation:4,y:20.6},0).wait(1).to({scaleX:1.08,scaleY:1.08,rotation:4.1},0).wait(1).to({scaleX:1.08,scaleY:1.08,rotation:4.2},0).wait(1).to({scaleX:1.08,scaleY:1.08,rotation:4.3},0).wait(1).to({scaleX:1.08,scaleY:1.08,rotation:4.4},0).wait(1).to({scaleX:1.09,scaleY:1.09,rotation:4.5},0).wait(1).to({scaleX:1.09,scaleY:1.09,rotation:4.6},0).wait(1).to({scaleX:1.09,scaleY:1.09},0).wait(1).to({scaleX:1.09,scaleY:1.09,rotation:4.7},0).wait(1).to({scaleX:1.09,scaleY:1.09},0).wait(1).to({scaleX:1.09,scaleY:1.09,rotation:4.8},0).wait(1).to({scaleX:1.09,scaleY:1.09},0).wait(1).to({scaleX:1.09,scaleY:1.09,rotation:4.9},0).wait(2).to({scaleX:1.09,scaleY:1.09,rotation:5},0).wait(1).to({regX:137.1,scaleX:1.1,scaleY:1.1,x:137.1},0).wait(1).to({regX:136.4,scaleX:1.09,scaleY:1.09,x:136.4},0).wait(1).to({scaleX:1.09,scaleY:1.09,rotation:4.8,x:136.3},0).wait(1).to({scaleX:1.09,scaleY:1.09,rotation:4.6,x:136.4},0).wait(1).to({scaleX:1.08,scaleY:1.08,rotation:4.3,x:136.3},0).wait(1).to({scaleX:1.07,scaleY:1.07,rotation:3.8,x:136.4},0).wait(1).to({scaleX:1.06,scaleY:1.06,rotation:3.2},0).wait(1).to({scaleX:1.05,scaleY:1.05,rotation:2.4},0).wait(1).to({scaleX:1.03,scaleY:1.03,rotation:1.3},0).wait(1).to({regX:137.1,scaleX:1,scaleY:1,rotation:0,x:137.1},0).wait(1));

	// Символ 42
	this.instance_1 = new lib.Символ42();
	this.instance_1.setTransform(215.9,24,1,1,0,0,0,58.2,17.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(31).to({regX:116.5,regY:34.2,x:274.2,y:41.1},0).to({regY:34.3,rotation:-24.7,y:41.2},7,cjs.Ease.get(1)).to({regY:34.2,rotation:9.2,y:41.1},8,cjs.Ease.get(-1)).to({regY:34.3,rotation:-6.4,y:41.2},3,cjs.Ease.get(1)).to({regY:34.2,rotation:3.7,x:274.1},3,cjs.Ease.get(-1)).to({rotation:0,x:274.2,y:41.1},2,cjs.Ease.get(1)).wait(10).to({_off:true},1).wait(37));

	// Символ 41
	this.instance_2 = new lib.Символ41();
	this.instance_2.setTransform(0,40.7,1,1,0,0,0,0,40.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({regX:69.8,regY:20.4,rotation:-2.8,x:75.1,y:17.1},0).wait(1).to({rotation:-4.9,x:79,y:14.7},0).wait(1).to({rotation:-6.6,x:82.1,y:12.7},0).wait(1).to({rotation:-7.9,x:84.5,y:11.2},0).wait(1).to({rotation:-9,x:86.4,y:9.9},0).wait(1).to({rotation:-10,x:88.1,y:8.9},0).wait(1).to({rotation:-10.8,x:89.6,y:7.9},0).wait(1).to({rotation:-11.6,x:90.9,y:7.1},0).wait(1).to({rotation:-12.3,x:92.1,y:6.3},0).wait(1).to({rotation:-13,x:93.3,y:5.5},0).wait(1).to({rotation:-13.7,x:94.3,y:4.8},0).wait(1).to({rotation:-14.2,x:95.2,y:4.3},0).wait(1).to({rotation:-14.7,x:96,y:3.8},0).wait(1).to({rotation:-15.1,x:96.7,y:3.3},0).wait(1).to({rotation:-15.5,x:97.3,y:2.9},0).wait(1).to({rotation:-15.8,x:97.8,y:2.6},0).wait(1).to({rotation:-16,x:98.2,y:2.3},0).wait(1).to({rotation:-16.3,x:98.5,y:2.1},0).wait(1).to({rotation:-16.5,x:99,y:1.9},0).wait(1).to({rotation:-16.7,x:99.3,y:1.7},0).wait(1).to({rotation:-16.9,x:99.6,y:1.4},0).wait(1).to({rotation:-17.1,x:99.9,y:1.2},0).wait(1).to({rotation:-17.3,x:100.2,y:1},0).wait(1).to({rotation:-17.5,x:100.5,y:0.8},0).wait(1).to({regX:0.1,regY:40.7,rotation:-17.7,x:40.6,y:41.1},0).to({regX:0,regY:40.6,rotation:-23.5,x:40.5},4,cjs.Ease.get(-1)).to({regY:40.8,rotation:-2.7,y:41.2},4,cjs.Ease.get(1)).to({regY:40.7,rotation:0,x:0,y:40.7},6,cjs.Ease.get(-1)).wait(25).to({_off:true},1).wait(37));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,270.8,41.2);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ38();
	this.instance.setTransform(16.8,16.8,1,1,0,0,0,16.8,16.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},11).to({alpha:0},13).wait(1));

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("Ah1B2QgxgxAAhFQAAhEAxgxQAxgxBEAAQBFAAAxAxQAxAxAABEQAABFgxAxQgxAxhFAAQhEAAgxgxg");
	this.shape.setTransform(16.8,16.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(25));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,33.5,33.5);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Режим изоляции
	this.instance = new lib.Символ39();
	this.instance.setTransform(57.8,38.9,0.243,0.243,0,0,0,159.7,234.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:159.6,regY:234.3,scaleX:0.26,scaleY:0.26},6,cjs.Ease.get(-1)).to({regX:159.7,regY:234.2,scaleX:0.28,scaleY:0.28},6,cjs.Ease.get(1)).to({regX:159.8,regY:234.1,scaleX:0.26,scaleY:0.26},6,cjs.Ease.get(-1)).to({regX:159.7,regY:234.2,scaleX:0.24,scaleY:0.24},6,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(19.1,-17.9,77.6,113.7);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ31();
	this.instance.setTransform(29,29,1,1,0,0,0,29,29);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.8,scaleY:0.8},5,cjs.Ease.get(-1)).to({scaleX:0.64,scaleY:0.64},4,cjs.Ease.get(1)).to({regX:29.1,regY:29.1,scaleX:0.78,scaleY:0.78,x:29.1,y:29.1},4,cjs.Ease.get(-1)).to({regX:29,regY:29,scaleX:1,scaleY:1,x:29,y:29},6,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,58,58);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.setTransform(75.4,75.4,1,1,0,0,0,75.4,75.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:360},69).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,150.9,150.8);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ26();
	this.instance.setTransform(81.9,81.9,1,1,0,0,0,81.9,81.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-360},34).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,163.9,163.8);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ24();
	this.instance.setTransform(121,121,1,1,0,0,0,121,121);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:360},49).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,242,242);


(lib.Символ23 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ25();
	this.instance.setTransform(121,121,1,1,0,0,0,121,121);

	// Слой 3
	this.instance_1 = new lib.Символ27();
	this.instance_1.setTransform(121,121,1,1,0,0,0,81.9,81.9);

	// Слой 4
	this.instance_2 = new lib.Символ28();
	this.instance_2.setTransform(121,121,1,1,0,0,0,75.4,75.4);

	// Слой 1
	this.instance_3 = new lib.Символ30();
	this.instance_3.setTransform(121,121,1,1,0,0,0,29,29);

	this.addChild(this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,242,242);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(19).call(this.frame_19).wait(21));

	// Слой 1
	this.instance = new lib.Символ21();
	this.instance.setTransform(350.5,167.8,1,1,0,0,0,350.5,167.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},19).to({alpha:0},20).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,701,335.7);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ18();
	this.instance.setTransform(19,4.2,1,1,0,0,0,19,4.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:10.2},3).to({y:4.2},3).wait(1).to({y:10.2},3).to({y:4.2},3).to({_off:true},1).wait(46));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,38.1,8.5);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ17();
	this.instance.setTransform(19.9,22.4,1,1,0,0,0,19.9,22.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:16.2},4,cjs.Ease.get(-1)).to({y:8.4},5,cjs.Ease.get(1)).to({y:15.4},5,cjs.Ease.get(-1)).to({y:22.4},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,39.7,44.9);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ15();
	this.instance.setTransform(320,152.5,1,1,0,0,0,320,152.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},13).to({alpha:1},16).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.6,-2.6,645.3,310.3);


(lib.Символ12 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ11();
	this.instance.setTransform(16.3,14.9,0.813,0.813,0,0,0,20,16);

	this.instance_1 = new lib.Символ11();
	this.instance_1.setTransform(41.8,16,1,1,0,0,0,20,16);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,61.8,32);


(lib.Символ6 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ5();
	this.instance.setTransform(1600,77.5,1,1,0,0,0,320,77.5);

	this.instance_1 = new lib.Символ5();
	this.instance_1.setTransform(960,77.5,1,1,0,0,180,320,77.5);

	this.instance_2 = new lib.Символ5();
	this.instance_2.setTransform(320,77.5,1,1,0,0,0,320,77.5);

	this.addChild(this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,1920,155);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.chest_1();
	this.instance.setTransform(35,33.5,1,0.969,0,0,0,35,32.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:32.5},29).to({y:33.5},30).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,2,70,63);


(lib.body_1 = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ABPAhQgJgBgIgFQgIgFAAgLQAAgLAOgGQAOgHAUAAQAOAAAKADIAEACIAaAHQAWAFgXAKQgYAKgVAFQgRAEgJAAIgFAAgAiBAMQgRgDgCgDIgNgPQgLgPAPgBQAPgCAKgEQALgEATAJQATAJACAKQACAIgRAHQgLAFgMAAIgKgBg");
	mask.setTransform(87.1,66.2);

	// Слой 3
	this.instance = new lib.Символ19();
	this.instance.setTransform(86.2,59.9,1,1,0,0,0,19,4.2);

	this.instance.mask = mask;

	// Слой 1
	this.instance_1 = new lib.body();

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,198,355);


(lib.Символ56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 1
	this.instance = new lib.Символ14();
	this.instance.setTransform(320,152.5,1,1,0,0,0,320,152.5);

	this.instance_1 = new lib.Символ57();
	this.instance_1.setTransform(320,152.5,1,1,0,0,0,320,152.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.6,-2.6,645.3,310.3);


(lib.Символ55 = function() {
	this.initialize();

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhmBGIAAgcIhFAAIAAAcIgWAAIgCgvIAJAAIAFgFIAFgIIAEgMIACgVIADguIBLAAIAABcIANAAIgCAvgAiXAFIgDAKIgFAIIArAAIAAhKIgdAAgAICAqIAAhvIAYAAIAAApIATAAQAKAAAIACQAIADAGAEQAFAFADAHQADAGAAAGQAAAJgDAGQgDAHgFAFQgGAFgIADQgIACgKAAgAIaAXIATAAIAIgBIAHgEIADgGIABgHIgBgFIgDgFIgHgDQgDgCgFAAIgTAAgAFpAqIAAhvIAYAAIAABcIAgAAIAAhcIAXAAIAABcIAgAAIAAhcIAXAAIAABvgAE+AqIAAhvIAXAAIAABvgADfAqIAAhvIAYAAIAAApIASAAQAKAAAIACQAIADAGAEQAFAFADAHQADAGABAGQgBAJgDAGQgDAHgFAFQgGAFgIADQgIACgKAAgAD3AXIASAAIAJgBIAGgEQADgCABgEQABgDAAgEQAAgDgBgCQgBgCgDgDIgGgDQgEgCgFAAIgSAAgACzAqIAChTIgfBTIgQAAIgehSIACBSIgYAAIAAhvIAgAAIAcBQIAdhQIAgAAIAABvgAAAAqIAAhJIgsBJIgXAAIAAhvIAXAAIAABJIAshJIAXAAIAABvgAkVAqIAAhvIBNAAIAAASIg1AAIAAAcIAtAAIAAASIgtAAIAAAcIA1AAIAAATgAl7AqIAAhvIAoAAQAKAAAIABQAIACAGAEQAFAEADAGQADAGgBAIIAAAHIgDAHIgGAGIgHAEQAGABADADIAGAFIADAGIABAIQAAAQgLAJQgKAIgUAAgAljAXIAUAAIAIgBQADgBACgCIAEgEIABgGIgBgHIgDgDQgCgCgDgBIgIgBIgVAAgAljgWIASAAQAIAAAFgEQAEgDAAgHQAAgIgFgDQgEgEgKAAIgQAAgAmeAqIgIgXIgoAAIgIAXIgaAAIArhvIAVAAIArBvgAmsAAIgOgpIgPApIAdAAgAoSAqIAAguIguAAIAAAuIgXAAIAAhvIAXAAIAAAuIAuAAIAAguIAYAAIAABvg");
	this.shape.setTransform(118.6,38.8);

	// Слой 1
	this.instance = new lib.Символ53();
	this.instance.setTransform(28.6,38.2,0.753,0.753,0,0,0,24.2,24.2);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,19.5,178.6,37.5);


(lib.Символ52 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ43();
	this.instance.setTransform(167.6,39.4,1,1,0,0,0,137.1,20.6);

	this.instance_1 = new lib.Символ48();
	this.instance_1.setTransform(189.8,42,1,1,0,0,0,189.8,42);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,379.6,84.1);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(19).call(this.frame_19).wait(21));

	// Слой 2
	this.instance = new lib.Символ55();
	this.instance.setTransform(21.3,-72.1,1,1,0,0,0,23.7,18.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({x:41.3},5,cjs.Ease.get(1)).to({x:-361.8},10,cjs.Ease.get(-1)).wait(1).to({x:41.3},10,cjs.Ease.get(1)).to({x:21.3},5,cjs.Ease.get(-1)).wait(5));

	// Слой 1 - копия
	this.instance_1 = new lib.Символ52();
	this.instance_1.setTransform(159.3,53.2,1,1,0,0,0,189.8,42);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:179.3},5,cjs.Ease.get(1)).to({x:-228.7},14,cjs.Ease.get(-1)).wait(1).to({x:179.3},14,cjs.Ease.get(1)).to({x:159.3},5,cjs.Ease.get(-1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.5,-70.8,379.6,166.1);


(lib.Символ36 = function() {
	this.initialize();

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AM6A5QgIgLgDgLQgDgLgBgLIAAgPIACgJQADgLAEgLQAEgJAGgJQAIgLAIgFQAIgGALABQAOgBAMATQAFAGAFAIIAGARIABAEIACAbIgCAPIAAAAQgCAKgGAPQgHAPgIAHIgEADIgIAFQgJAFgDAAQgTAAgQgagANMgsQgEAEgDAHQgFAMgBAOQABAhAXAZQAJAEAEAAQALAAAGgKQAFgJABgTQAAgJgCgIQgDgLgEgLQgGgNgHgGQgHgHgHABQgGAAgFADgACyA0QgOgZgBgbQABgPAEgRQAEgRAIgQQAIgOADAAIA9gBQAJAAAAAHQAAAEgJAHQgKAIgGABIgBgBQgDgHgJgBIgbACIgDAFIgFATQAAADAKAAIAjgCQAHAAADABQAEABAAAEQAAADgIAHIgMAGIgBAAIgBgDIgBgBIgcAAIgIABIAAADQgBAPAGAQQAGAVAOAGIALAGIAKAAQAEAAAKgGIALgGQAGAAgBAEQgDAGgTAPQgTAQgFAAQgZAAgPgcgAgyA0QgOgZAAgbQAAgPAEgRQAEgRAJgQQAHgOAEAAIA6gBQAKAAgBAHQABAEgKAHQgJAIgGABIgCgBQgDgHgHgBIgbACIgCAFIgGATQAAADALAAIAggCQAIAAADABQADABABAEQAAADgIAHIgKAGIgBAAIgCgDIgBgBIgcAAIgIABIAAADQAAAPAGAQQAGAVANAGIALAGIAIAAQAEAAAKgGIALgGQAGAAAAAEQgEAGgTAPQgQAQgFAAQgZAAgQgcgAHGBQQgXAAgPgXQgNgUAAgZQAAgTAFgQQAEgMAMgWIgDgCIgFAAIgDABIgBAAQgJAAAAgEQAAgEAJgHQAJgHAEgBIANADIAgAAQAPAAAKAKQAJALADAUIAFAeQgEA+gkAUIgNAFgAG0g0IgEARIgFAbQAAAWAIARQAFAMAIAHQAHAFAKAAQAHAAAFgDQAFgEADgHQAEgMAAgOQAAgPgEgWIgDgKIgLgRQgHgKgJAAIgNAAQgDACgDAFgAlSBQQgXAAgPgXQgNgUAAgZQAAgTAFgQQAEgMAMgWIgEgCIgEAAIgDABIgCAAQgIAAAAgEQAAgEAJgHQAJgHAEgBIANADIAgAAQAQAAAJAKQAJALADAUIAFAeQgEA+gkAUIgNAFgAlkg0IgEARIgFAbQAAAWAIARQAFAMAHAHQAIAFAKAAQAGAAAGgDQAEgEAEgHQAEgMAAgOQAAgPgEgWIgDgKIgLgRQgHgKgJAAIgNAAQgDACgDAFgAm1BNQgDgDABgFIABhUIgBgOIAAgCQABgIAJgQIAAgCQgCgBgfgBIgBABQgCASAAAdIAAA/IAFACIABACQgBAGgJAIQgJAHgFAAQgEAAgCgEQgCgDAAgIIABgJIgBAAIAChsQAAgBAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAIgQgBQgGAAAAACIgBBhQAAAJgCAGQgBAGgDAEQgDADgGAEIgOAHQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAHgMAAgsIAAg4IgCgEIgFgCQAFgJAJgGQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIgKAAQgKABAAgGQAFgJAIgCQAHgGAEAAIADACIADACIB4AAQAGADgBAEIgFAJQgHAJABAEIgBBVIAAADIAAAJIAAAEIAEAEIABABIAAACIgMAMQgHAHgFAAgAA+A+IABhkIgDgCIgEgDIAOgPIgCgCIgMABQgLAAAAgEIAAgCIAKgJQAGgFAGgCIAGADIAIABIAzgBQASABAAARIAABAQAAAJgOAKQgGAGgFACQgFADgFAAIgPgBQgJAAgBACQgDABAAAIQAAAGADAEIADACIAAABQAAAFgKAIQgKAHgEABQgHAAAAgQgABYg6IAABQIABABIAJgIIARABQALAAAAgGIAAg8QAAgFgCgDQgCgCgFAAIgRAAQgIABgEABgAqfAkIABg/QAAgSgBgHIgEgCIgBgBIAAgBQAQgXAIAAQAEAAACADQADAFAAAHIgCBlQAAAPAKADQALABALgGQANgHAAgKIAAhPIgBgGIgDgBIgEgDIALgPQAJgJAGAAQAEAAADAEQABAEAAAIIAABsIAAAGIAGAEQAAAEgDAEIgIAIQgJAHgHAAQgEgBgCgIIAAgLQgEABgIAGIgMAIQgKAFgLABQgZAAAAgqgAIWBNQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAGgKQAHgKAAgGIAAhBIgBgFIAAgOIgBgCIgEgFQADgGAKgJIAAgCIgRABQgMAAAAgEQAAgGAIgHQAJgGAFAAIAEADIA9AAQAMAAAGAHQAGAHAAAOQAAAHgDAIQgEAIgGAIIgGAFIAIAHQAFAFADAEIACAMIAAAjIgBAFQAAAYghAAgAI4AIIABATQAAALgBAFQgCAFgHAIIABACIABABIAdAAQAKgBADgFQADgFgBgLQABgYgCgFQgFgMgSAAIgJAAQgEAAAAAMgAI5g5IAAAoQAAAAAAABQABAAAAABQAAAAAAAAQABAAAAAAQAHAAAHgCQAGgCAFgEQAGgEADgGQADgFAAgHQAAgGgEgEQgEgFgFAAIgVAAQgFAAAAADgAFhBJQgCgDAAgIIAAgnQAAg1ABgFQACgDAGgIQAGgHACgFIgCgCIgyAAIgBACIABBEQAAAVgEAcQgJAIgGAFQgGAFgEAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIACgEIABgDIABgCQACgHgBgQIgBgXQABgBAAgRIAAgcQABgPgFgBIgBgBQAAgDANgMIgBgCIgKABQgMAAABgFQgBgFAKgHQAIgFAGAAQAIADASAAIA1gBQAOABAAAHQAAADgGAIIgHAOQAAAFgBAvQABApAAAFQAFACAAACQAAAFgKAIQgKAIgFAAQgEAAgCgEgAhxBEIgBgLIAAgvQgEABgHAGIgNAJQgJAFgMgBQgKABgFgGQgEgFgCgKQgCgIAAgJIAAgUQAAgSgCgHIgEgCIAAgBIAAgBQAQgXAHAAQAFAAACADQACAFAAAHIgBA4QAAAOAJACQALAAAMgFQANgFgBgKIAAgGIABgcIgCgGIgCgBIgEgDIAMgPQAHgJAHAAQAFAAABAEQADAEAAAIIgCBsIACAGIAFAEQAAAEgDAEQgCADgFAFQgKAHgHAAQgEgBgCgIgAsYBNQgBAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIAHgKQAHgKAAgGIAAhBIAAgFIAAgOIgBgCIgFgFQADgGAKgJIAAgCIgRABQgMAAAAgEQAAgGAIgHQAJgGAFAAIAEADIBMAAQAFAAAFACQAEACAAAEIAAACIgBACIgJAJQgGAGgDAAIgDgCQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAQgCgCgDAAIgjAAQgEAAAAADIAAAoQAAAAAAABQAAAAABABQAAAAAAAAQABAAAAAAIAfgCIAMACIAIAHQAFAFADAEIACAMIAAAjIgBAFQAAAYggAAgAr2AIIABATQAAALgCAFQgBAFgGAIIAAACIACABIAcAAQAKgBADgFQADgFAAgLQAAgYgCgFQgEgMgTAAIgJAAQgEAAAAAMgAtoBHQgSgLgJgRQgKgTABgYIACgZIAKgeQAKgZAFABIAFgBIA7ABQAEABgBACIgDAHIgIAIQgGAFgEAAIgDgEQgFgCgDAAIgcAAQgEAEgDAMIgCAEIgCAQIAAAJQAAAQADAJQADALAGAHQABAGAJAGQAKAIAFgBQAIAAAKgEQALgFADAAQADAAAAAFQAAAEgDAAQgfAggMAAQgFAAgIgGg");
	this.shape.setTransform(179,38.7);

	// Слой 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AE8A1QgOgYAAgbQAAgPAEgSQAEgRAJgQQAHgOAEAAIA8gBQAJABAAAGQAAAFgJAHQgKAHgFACIgCgBQgDgIgJAAIgbACIgDAEIgFAUQAAACALAAIAigCQAHABAEABQADABAAADQAAAEgIAGIgMAHIgBgBIgBgCIgBgBIgcgBIgIABIAAADQAAAQAFAQQAHAUANAHIALAFIAKAAQAEAAAKgGIALgGQAGABgBAEQgDAFgTAPQgTAQgEABQgZgBgQgcgABWA1QgOgYAAgbQAAgPAFgSQAEgRAIgQQAHgOAEAAIA8gBQAKABAAAGQAAAFgKAHQgJAHgGACIgCgBQgCgIgKAAIgbACIgCAEIgFAUQAAACAKAAIAjgCQAHABADABQAEABAAADQAAAEgIAGIgMAHIgBgBIgCgCIgBgBIgbgBIgIABIgBADQAAAQAGAQQAGAUANAHIALAFIALAAQADAAALgGIALgGQAFABAAAEQgEAFgSAPQgTAQgFABQgZgBgQgcgAJRBRQgYAAgPgXQgNgTAAgZQAAgUAFgPQAEgNAMgVIgDgCIgFAAIgDAAIgBAAQgJABAAgFQAAgEAJgGQAJgIAEAAIANACIAgAAQAQABAJAJQAJALAEAUIAEAfQgDA9glAUIgNAFgAI/gyIgFAQIgEAbQAAAWAHASQAFAMAIAGQAHAGAKAAQAHAAAFgEQAFgDADgIQAEgMAAgOQAAgPgEgVIgDgKIgKgSQgIgJgJgBIgNAAQgDACgCAGgAjHBRQgYAAgPgXQgNgTAAgZQAAgUAFgPQAEgNAMgVIgDgCIgFAAIgDAAIgBAAQgJABAAgFQAAgEAJgGQAJgIAEAAIANACIAgAAQAQABAJAJQAJALAEAUIAEAfQgDA9glAUIgNAFgAjZgyIgFAQIgEAbQAAAWAHASQAFAMAIAGQAHAGAKAAQAHAAAFgEQAFgDADgIQAEgMAAgOQAAgPgEgVIgDgKIgKgSQgIgJgJgBIgNAAQgDACgCAGgAkrBPQgCgEAAgEIABhUIgBgPIABgBQAAgJAJgQIAAgBQgBgCgfgBIgCACQgCARAAAeIABA/IAEACIABABQgBAHgJAHQgJAIgFAAQgEAAgBgEQgCgEAAgHIAAgKIAAAAIAChsQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAgBIgQAAQgHAAAAACIgBBgQAAAKgBAFQgCAHgDADQgDAEgFADIgOAHQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQAGgLAAgsIAAg5IgCgEIgEgCQAFgIAIgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAIgKAAQgKAAAAgFQAGgJAHgDQAIgFADAAIADABIADACIB4AAQAGADAAAFIgGAJQgGAIAAAFIgBBUIAAAEIAAAJIAAAEIAEADIABACIAAABIgLAMQgIAIgFAAgADIA/IABhjIgDgCIgEgDIAOgQIgCgBIgLAAQgLAAAAgDIAAgCIAKgKQAGgEAFgCIAGADIAIABIAzgBQASAAAAASIAABAQAAAIgNALQgHAFgFADQgFADgFAAIgPgBQgJgBgBACQgDACAAAHQAAAHADADIADADIABABQAAAEgKAIQgKAIgFAAQgHAAAAgQgADig5IAABRIABABIAJgIIARAAQALAAAAgFIAAg9QAAgFgCgCQgCgCgFAAIgRAAQgHAAgFABgAoVAmIACg/QAAgTgCgGIgEgCIgBgCIAAgBQARgXAHAAQAFAAACAEQACAEAAAIIgBBlQAAAPAJADQALAAALgFQANgHAAgKIAAhPIgBgGIgDgBIgEgDIAMgPQAIgKAHAAQAEAAACAEQACAFAAAHIgBBsIABAHIAFAEQAAAEgDAEIgHAHQgKAIgHAAQgEgCgBgHIgBgMQgEACgIAFIgMAJQgJAFgMAAQgZAAAAgpgAKgBPQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAgBIAGgLQAHgKAAgFIAAhCIAAgEIAAgOIgBgDIgFgEQADgHAKgIIAAgCIgRAAQgMABAAgFQAAgFAIgHQAJgGAFAAIAEACIA9AAQAMABAGAHQAGAGAAAOQAAAIgDAIQgDAHgHAIIgGAFIAIAIQAFAEAEAFIABAMIAAAiIgBAFQAAAZggAAgALCAJIABAUQAAAKgBAFQgCAGgGAHIAAADIACAAIAcAAQAKAAADgGQADgEAAgLQAAgZgCgFQgEgLgTAAIgJAAQgEAAAAALgALDg3IAAAnQAAABABAAQAAABAAAAQAAAAABAAQAAAAAAAAQAIAAAGgCQAGgCAFgDQAGgEADgGQADgGAAgHQAAgFgEgFQgDgEgGgBIgVAAQgFAAAAAEgAHrBLQgCgEAAgHIAAgoQAAg0ACgFQABgEAGgHQAGgIACgEIgCgCIgyAAIgBACIABBDQAAAWgEAbQgIAJgHAFQgGAFgEAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIACgEIACgDIAAgCQACgGgBgQIAAgYQABgBAAgRIAAgbQAAgQgFgBIgBgBQAAgDANgMIgBgBIgKAAQgLABAAgGQAAgFAJgGQAJgGAFAAQAJAEARAAIA1gBQAOABAAAHQAAACgGAJIgGANQgBAFAAAwQAAApABAEQAEADAAABQAAAFgKAJQgKAHgFABQgEAAgCgEgAAYBGIgBgMIgBguQgEABgHAGIgLAIQgJAFgLAAQgKAAgFgFQgFgGgCgJQgCgJAAgIIAAgUQAAgTgBgGIgFgCIAAgCIAAgBQAQgXAIAAQAEAAACAEQADAEAAAIIgCA4QAAANAKADQAJAAALgGQANgFAAgJIgBgHIABgbIgBgGIgDgBIgEgDIAMgPQAIgKAHAAQAEAAACAEQACAFAAAHIgBBsIABAHIAFAEQAAAEgDAEQgCADgFAEQgKAIgHAAQgEgCgBgHgAqOBPQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAgBIAGgLQAHgKAAgFIAAhCIAAgEIAAgOIgBgDIgFgEQADgHAKgIIAAgCIgRAAQgMABAAgFQAAgFAIgHQAJgGAFAAIAEACIBMAAQAFABAFACQAEACAAAEIAAABIAAADIgJAIQgHAHgDgBIgDgBQAAgDgDgCQgCgCgDAAIgiAAQgFAAAAAEIAAAnQAAABABAAQAAABAAAAQAAAAABAAQAAAAAAAAIAggCIALACIAIAIQAFAEAEAFIABAMIAAAiIgBAFQAAAZggAAgApsAJIABAUQAAAKgBAFQgCAGgGAHIAAADIACAAIAcAAQAKAAADgGQADgEAAgLQAAgZgCgFQgEgLgTAAIgJAAQgEAAAAALgAreBJQgSgLgJgSQgJgTAAgZIACgXIALgeQAKgZAEAAIAGgBIA6ABQAEACAAACIgDAGIgJAIQgGAFgEABIgDgEQgEgCgEgBIgcABQgEADgDAMIgCAFIgCAQIAAAJQAAAPADAKQADALAGAHQABAFAJAHQAKAHAFAAQAIAAAKgEQALgGADAAQAEABAAAEQAAAEgDAAQggAggMABQgEAAgJgGg");
	this.shape_1.setTransform(165.2,39.1);

	// Слой 3
	this.instance = new lib.Символ37();
	this.instance.setTransform(266.2,39.3,1,1,0,0,0,16.8,16.8);

	// Слой 1
	this.instance_1 = new lib.Символ51();
	this.instance_1.setTransform(33.7,39.9,1,1,0,0,0,19,27.9);
	this.instance_1.alpha = 0.219;

	this.instance_2 = new lib.Символ35();
	this.instance_2.setTransform(49,40.8,0.49,0.49,0,0,0,52.9,40.8);

	this.addChild(this.instance_2,this.instance_1,this.instance,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(14.7,12,268.2,55.8);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 1
	this.instance = new lib.Символ23();
	this.instance.setTransform(58,58,0.479,0.479,0,0,0,121,121);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.setTransform(30.9,16,1,1,0,0,0,30.9,16);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},12).to({alpha:1},12).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,61.8,32);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ6();
	this.instance.setTransform(320,77.5,1,1,0,0,0,320,77.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-960},139).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1920,155);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ6();
	this.instance.setTransform(320,77.5,1,1,0,0,0,320,77.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-960},69).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1920,155);


(lib.Символ1 = function() {
	this.initialize();

	// Слой 2 - копия
	this.instance = new lib.Символ8();
	this.instance.setTransform(-320,38.8,1,0.5,180,0,0,960,77.5);
	this.instance.alpha = 0.391;

	// Слой 2
	this.instance_1 = new lib.Символ7();
	this.instance_1.setTransform(-316.5,77.5,1,1,180,0,0,956.5,77.5);
	this.instance_1.alpha = 0.391;

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],-84.9,0,85,0).s().p("AtQZTMAAAgylIahAAMAAAAylg");
	this.shape.setTransform(37,152);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],85,0.1,-84.9,0.1).s().p("AtQZTMAAAgylIahAAMAAAAylg");
	this.shape_1.setTransform(602.9,151.9);

	// Слой 1
	this.instance_2 = new lib.bg();

	this.addChild(this.instance_2,this.shape_1,this.shape,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1280,-10,1967.9,324);


(lib.skull_1 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ13();
	this.instance.setTransform(24.9,41.6,1,1,0,0,0,30.9,16);

	// Слой 1
	this.instance_1 = new lib.skull();

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6,0,64.1,85);


(lib.Символ59 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(19).call(this.frame_19).wait(21));

	// Слой 1
	this.instance = new lib.Символ36();
	this.instance.setTransform(-12.3,-10,0.838,0.838);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:148.8,regY:39.8,scaleX:0.87,scaleY:0.87,x:116.5,y:22.5},0).wait(1).to({scaleX:0.89,scaleY:0.89,x:119.6,y:21.9},0).wait(1).to({scaleX:0.91,scaleY:0.91,x:122,y:21.4},0).wait(1).to({scaleX:0.92,scaleY:0.92,x:123.9,y:21},0).wait(1).to({scaleX:0.94,scaleY:0.94,x:125.5,y:20.7},0).wait(1).to({scaleX:0.95,scaleY:0.95,x:127,y:20.4},0).wait(1).to({scaleX:0.96,scaleY:0.96,x:128.3,y:20.1},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:129.6,y:19.8},0).wait(1).to({scaleX:0.98,scaleY:0.98,x:130.8,y:19.6},0).wait(1).to({scaleX:0.98,scaleY:0.98,x:131.9,y:19.4},0).wait(1).to({scaleX:0.99,scaleY:0.99,x:132.8,y:19.2},0).wait(1).to({scaleX:1,scaleY:1,x:133.7,y:19},0).wait(1).to({scaleX:1,scaleY:1,x:134.3,y:18.9},0).wait(1).to({scaleX:1.01,scaleY:1.01,x:134.9,y:18.7},0).wait(1).to({scaleX:1.01,scaleY:1.01,x:135.5,y:18.6},0).wait(1).to({scaleX:1.01,scaleY:1.01,x:135.9,y:18.5},0).wait(1).to({scaleX:1.02,scaleY:1.02,x:136.3,y:18.4},0).wait(1).to({scaleX:1.02,scaleY:1.02,x:136.6},0).wait(1).to({regX:0,regY:0,scaleX:1.02,scaleY:1.02,x:-15,y:-22.3},0).wait(1).to({regX:148.8,regY:39.8,scaleX:0.99,scaleY:0.99,x:133,y:19.1},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:130,y:19.8},0).wait(1).to({scaleX:0.95,scaleY:0.95,x:127.7,y:20.2},0).wait(1).to({scaleX:0.94,scaleY:0.94,x:125.8,y:20.6},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:124.2,y:20.9},0).wait(1).to({scaleX:0.92,scaleY:0.92,x:122.8,y:21.3},0).wait(1).to({scaleX:0.91,scaleY:0.91,x:121.5,y:21.5},0).wait(1).to({scaleX:0.9,scaleY:0.9,x:120.2,y:21.8},0).wait(1).to({scaleX:0.89,scaleY:0.89,x:119,y:22},0).wait(1).to({scaleX:0.88,scaleY:0.88,x:118,y:22.2},0).wait(1).to({scaleX:0.87,scaleY:0.87,x:117,y:22.4},0).wait(1).to({scaleX:0.87,scaleY:0.87,x:116.1,y:22.6},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:115.4,y:22.8},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:114.8,y:22.9},0).wait(1).to({scaleX:0.85,scaleY:0.85,x:114.3,y:23},0).wait(1).to({scaleX:0.85,scaleY:0.85,x:113.8,y:23.1},0).wait(1).to({scaleX:0.85,scaleY:0.85,x:113.4,y:23.2},0).wait(1).to({scaleX:0.84,scaleY:0.84,x:113,y:23.3},0).wait(1).to({scaleX:0.84,scaleY:0.84,x:112.7},0).wait(1).to({regX:0,regY:0,scaleX:0.84,scaleY:0.84,x:-12.3,y:-10},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,224.7,46.8);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ16();
	this.instance.setTransform(-10.2,134.9,1,1,60,0,0,19.9,21.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:105,x:-10.1,y:134.8},14,cjs.Ease.get(-1)).to({rotation:45,y:134.9},14,cjs.Ease.get(1)).to({rotation:75,y:134.8},9).to({regY:21.8,rotation:60,y:134.9},4).wait(3).to({scaleX:1,scaleY:1,rotation:67.5,y:134.8},9,cjs.Ease.get(-1)).to({regY:21.9,scaleX:1,scaleY:1,rotation:75},9,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:67.5,y:134.9},9,cjs.Ease.get(-1)).to({regY:21.8,scaleX:1,scaleY:1,rotation:60},9,cjs.Ease.get(-1)).wait(1));

	// hand
	this.instance_1 = new lib.hand_1();
	this.instance_1.setTransform(65.5,200.5,1,1,0,0,0,25.5,76.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regY:76.4,scaleY:0.67,y:225.7},14,cjs.Ease.get(-1)).to({regY:76.5,scaleY:1.08,y:194.5},11,cjs.Ease.get(0.99)).to({scaleY:1,y:200.5},4,cjs.Ease.get(-1)).wait(8).to({scaleY:0.92,y:207},0).to({scaleY:0.95,y:204.5},4,cjs.Ease.get(1)).to({scaleY:1,y:200.5},3,cjs.Ease.get(1)).to({scaleY:0.98,y:202},9,cjs.Ease.get(-1)).to({scaleY:0.96,y:203.5},9,cjs.Ease.get(1)).to({scaleY:0.98,y:202},9,cjs.Ease.get(-1)).to({scaleY:1,y:200.5},9,cjs.Ease.get(1)).wait(1));

	// chest
	this.instance_2 = new lib.Символ3();
	this.instance_2.setTransform(162,240.5,1,1,0,0,0,35,32.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({scaleX:0.91,x:159},14,cjs.Ease.get(-1)).to({scaleX:1,x:162},11,cjs.Ease.get(0.99)).wait(19).to({regX:0,regY:0,x:127,y:208},0).wait(36).to({regX:35,regY:32.5,x:162,y:240.5},0).wait(1));

	// hand2
	this.instance_3 = new lib.hand2_1();
	this.instance_3.setTransform(212,207.5,1,1,0,0,0,21,207.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({rotation:9.7,y:207.6},14,cjs.Ease.get(-1)).to({rotation:0,y:207.5},11,cjs.Ease.get(0.99)).wait(12).to({y:208.5},4,cjs.Ease.get(1)).to({y:207.5},3,cjs.Ease.get(1)).to({rotation:2.3},27).to({rotation:0},9,cjs.Ease.get(1)).wait(1));

	// leg
	this.instance_4 = new lib.leg_1();
	this.instance_4.setTransform(81,366.5,1,1,0,0,0,81,48.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:87,y:358.5},14,cjs.Ease.get(-1)).to({x:81,y:366.5},11,cjs.Ease.get(0.99)).wait(12).to({y:367.5},4,cjs.Ease.get(1)).to({y:366.5},3,cjs.Ease.get(1)).wait(37));

	// skull
	this.instance_5 = new lib.skull_1();
	this.instance_5.setTransform(72,104.5,1,1,0,0,0,29,42.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({rotation:15,x:78,y:154},14,cjs.Ease.get(-1)).to({rotation:0,x:72,y:104.5},4,cjs.Ease.get(0.99)).to({rotation:360,x:70,y:42.5},10).to({rotation:720,x:72,y:115.5},9).to({regX:28.9,y:112.5},4,cjs.Ease.get(1)).to({regX:29,y:104.5},3,cjs.Ease.get(1)).to({y:107.5},9,cjs.Ease.get(-1)).to({y:110.5},9,cjs.Ease.get(1)).to({y:107.5},9,cjs.Ease.get(-1)).to({y:104.5},9,cjs.Ease.get(1)).wait(1));

	// body
	this.instance_6 = new lib.body_1();
	this.instance_6.setTransform(140,237.5,1,1,0,0,0,99,177.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({scaleX:0.97,x:137},14,cjs.Ease.get(-1)).to({scaleX:1,x:140},11,cjs.Ease.get(0.99)).wait(12).to({y:238.5},4,cjs.Ease.get(1)).to({y:237.5},3,cjs.Ease.get(1)).wait(37));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40,0,386.1,415);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.setTransform(173,207.5,1,1,0,0,0,173,207.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:215.5},24).to({y:207.8},24).to({y:207.5},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40,0,386.1,415);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(19).call(this.frame_19).wait(21));

	// Слой 1
	this.instance = new lib.Символ4();
	this.instance.setTransform(182.3,177.5,0.855,0.855,0,0,0,173,207.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:169.3,regY:220.1,scaleX:0.88,scaleY:0.88,x:165.8,y:195.2},0).wait(1).to({scaleX:0.9,scaleY:0.9,x:156.7,y:200},0).wait(1).to({scaleX:0.91,scaleY:0.91,x:150.5,y:203.2},0).wait(1).to({scaleX:0.92,scaleY:0.92,x:145.9,y:205.6},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:142.2,y:207.6},0).wait(1).to({scaleX:0.94,scaleY:0.94,x:138.9,y:209.3},0).wait(1).to({scaleX:0.94,scaleY:0.94,x:135.7,y:210.9},0).wait(1).to({scaleX:0.95,scaleY:0.95,x:132.8,y:212.4},0).wait(1).to({scaleX:0.95,scaleY:0.95,x:130.2,y:213.8},0).wait(1).to({scaleX:0.96,scaleY:0.96,x:128,y:214.9},0).wait(1).to({scaleX:0.96,scaleY:0.96,x:126.1,y:215.9},0).wait(1).to({scaleX:0.96,scaleY:0.96,x:124.5,y:216.8},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:123.1,y:217.5},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:122,y:218.1},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:121.1,y:218.6},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:120.3,y:219},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:119.6,y:219.3},0).wait(1).to({scaleX:0.98,scaleY:0.98,x:119.1,y:219.6},0).wait(1).to({regX:173,regY:207.5,scaleX:0.98,scaleY:0.98,x:122.3,y:207.5},0).wait(1).to({regX:169.3,regY:220.1,scaleX:0.95,scaleY:0.95,x:131.4,y:213.1},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:140.3,y:208.5},0).wait(1).to({scaleX:0.92,scaleY:0.92,x:146.5,y:205.3},0).wait(1).to({scaleX:0.91,scaleY:0.91,x:151.1,y:202.9},0).wait(1).to({scaleX:0.9,scaleY:0.9,x:154.7,y:201},0).wait(1).to({scaleX:0.9,scaleY:0.9,x:157.9,y:199.3},0).wait(1).to({scaleX:0.89,scaleY:0.89,x:160.9,y:197.8},0).wait(1).to({scaleX:0.89,scaleY:0.89,x:163.8,y:196.3},0).wait(1).to({scaleX:0.88,scaleY:0.88,x:166.4,y:194.9},0).wait(1).to({scaleX:0.88,scaleY:0.88,x:168.7,y:193.7},0).wait(1).to({scaleX:0.87,scaleY:0.87,x:170.7,y:192.7},0).wait(1).to({scaleX:0.87,scaleY:0.87,x:172.3,y:191.8},0).wait(1).to({scaleX:0.87,scaleY:0.87,x:173.8,y:191},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:174.9,y:190.4},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:176,y:189.9},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:176.9,y:189.4},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:177.6,y:189.1},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:178.2,y:188.8},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:178.6,y:188.5},0).wait(1).to({regX:173,regY:207.5,scaleX:0.86,scaleY:0.86,x:182.3,y:177.5},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,330.3,355.1);


// stage content:



(lib.girl_skull_640x305 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		var _this = this;
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		function fl_MouseOverHandler_5()
		{
		    _this.girl.gotoAndPlay(1);
		    _this.black.gotoAndPlay(1);
			_this.title.gotoAndPlay(1);
			_this.pricel.gotoAndPlay(1);
			_this.frame.gotoAndPlay(1);
			_this.score.gotoAndPlay(1);
		}
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		
		function fl_MouseOutHandler_2()
		{
		    _this.girl.gotoAndPlay(20);
		    _this.black.gotoAndPlay(20);
			_this.title.gotoAndPlay(20);
			_this.pricel.gotoAndPlay(0);
			_this.frame.gotoAndPlay(0);
			_this.score.gotoAndPlay(20);
		}
		
		stage.canvas.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		stage.canvas.style.cursor = "none";
		this.pricel.mouseEnabled = false;
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
			this.pricel.x = stage.mouseX;
			this.pricel.y = stage.mouseY;
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 2
	this.frame = new lib.Символ56();
	this.frame.setTransform(320,152.5,1,1,0,0,0,320,152.5);

	this.timeline.addTween(cjs.Tween.get(this.frame).wait(1));

	// Слой 4
	this.pricel = new lib.Символ32();
	this.pricel.setTransform(-152.3,208,1,1,0,0,0,58,58);

	this.timeline.addTween(cjs.Tween.get(this.pricel).wait(1));

	// Слой 6
	this.title = new lib.Символ40();
	this.title.setTransform(164.6,121.4,1,1,0,0,0,137.1,19.6);

	this.timeline.addTween(cjs.Tween.get(this.title).wait(1));

	// objects
	this.score = new lib.Символ59();
	this.score.setTransform(127.2,251.6,1,1,0,0,0,106.2,18.4);

	this.timeline.addTween(cjs.Tween.get(this.score).wait(1));

	// hand
	this.girl = new lib.Символ20();
	this.girl.setTransform(454.9,153.5,1,1,0,0,0,165.1,177.5);

	this.timeline.addTween(cjs.Tween.get(this.girl).wait(1));

	// Слой 3
	this.black = new lib.Символ22();
	this.black.setTransform(319.5,152,1,1,0,0,0,350.5,167.8);

	this.timeline.addTween(cjs.Tween.get(this.black).wait(1));

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.setTransform(320,152.5,1,1,0,0,0,320,152.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-960,128.5,1967.9,355.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;