(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 30,
	color: "#FFFFFF",
	manifest: [
		{src:"images/asdfasdfa.png?1469091996838", id:"asdfasdfa"},
		{src:"images/baba_03.png?1469091996838", id:"baba_03"},
		{src:"images/baba_06.png?1469091996838", id:"baba_06"},
		{src:"images/baba_09.png?1469091996838", id:"baba_09"},
		{src:"images/ddd5.jpg?1469091996838", id:"ddd5"}
	]
};



// symbols:



(lib.asdfasdfa = function() {
	this.initialize(img.asdfasdfa);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,20,25);


(lib.baba_03 = function() {
	this.initialize(img.baba_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,212,87);


(lib.baba_06 = function() {
	this.initialize(img.baba_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,168,407);


(lib.baba_09 = function() {
	this.initialize(img.baba_09);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,270);


(lib.ddd5 = function() {
	this.initialize(img.ddd5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.Символ65 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFF402").s().p("Ah1BVIAAipIBCAAIAABmICpAAIAABDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.8,-8.5,23.7,17.1);


(lib.Символ64 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACtCYIAAgNIhDAAIAAANIgYAAIAAgmIALAAIAnhaIANAAIAoBaIAMAAIAAAmgACbByIgQgpIgQApIAgAAgAnzCLQgHgDgFgFQgFgFgDgHQgCgIAAgJIAZAAQAAAGAEAEQADAFAHAAQAHAAAEgFQAEgDAAgFQAAgGgEgDQgEgEgHAAIgIAAIAAgYIAIAAQAFAAADgDQACgDAAgEQAAgEgCgCQgDgEgFAAQgFAAgDACQgCACAAADIgaAAQAAgHADgHQACgFAFgEQAFgEAHgCQAGgCAIAAQAJAAAHADQAIADAEAFQAFAEACAGQADAGAAAGQAAAGgDAGQgCAGgFADIAHAFIAFAHIADAIQABAEAAAFQAAAHgDAGQgDAHgFAFQgFAFgJADQgIACgLAAQgJAAgIgCgAHsCLIAAg4Ig5A4IgLAAIAAhxIAeAAIAAA3IA5g4IALAAIAABygAF9CLIgdhCIgdBCIgdAAIAAgEIAzhvIANAAIAzBvIAAAEgADTCLIAAhxIBHAAIAAAaIgqAAIAAAQIAnAAIAAAZIgnAAIAAAVIAsAAIAAAZgAAACLIAAhxIBFAAIAAAaIgqAAIAAAQIAnAAIAAAZIgnAAIAAAVIAsAAIAAAZgAg6CLIAAguIgjAAIAAAuIgeAAIAAhxIAeAAIAAAoIAjAAIAAgoIAeAAIAABxgAkLCLIAAgEIArg/IAEgHIABgHQAAgEgCgCQgCgCgFAAQgGAAgCACQgDADAAAGIgZAAQgBgJAEgHQACgHAGgFQAEgEAHgDQAHgCAHAAQAGgBAFACIAKAEIAIAGIAFAIQACAEAAAFQACAEgBAFQAAAFgCAGQgCAFgDAEIgXAgIAiAAIAAAagAlYCLIgHgOIgtAAIgHAOIgcAAIAAgEIAzhvIANAAIAzBvIAAAEgAloBkIgNgeIgNAeIAaAAgAkhgjQgHgDgFgFQgFgEgDgIQgCgIAAgJIAZAAQAAAHAEAEQAEAEAGAAQAHAAAEgEQAEgEAAgFQAAgFgEgEQgEgEgHAAIgIAAIAAgYIAIAAQAFAAADgDQADgDAAgEQAAgEgDgDQgDgCgFAAQgFAAgDABQgCACAAADIgaAAQAAgHACgHQADgFAFgEQAFgEAHgCQAGgCAIAAQAJAAAHADQAHADAFAEQAFAGACAFQACAGAAAGQAAAGgCAGQgCAGgFAEQAEABADAEIAFAGIADAHQABAEAAAGQAAAHgDAHQgDAHgFAEQgFAFgJADQgIACgLAAQgJAAgIgCgAFfgjIAAhXIgcAAIAAgaIBUAAIAAAaIgcAAIAABXgAEigjIgGgOIgtAAIgHAOIgcAAIAAgEIAzhvIANAAIAzBvIAAAEgAEShKIgNgeIgMAeIAZAAgACQgjIAAhXIgbAAIAAgaIBUAAIAAAaIgcAAIAABXgAAPgjIAAhxIAdAAIAAAiIAVAAQAHAAAKADQAIADAGAGQAFAFACAIQADAGAAAIQAAAIgDAHQgCAHgFAGQgGAFgIAEQgKADgHAAgAAsg9IAVAAQAGAAADgEQADgEAAgGQAAgFgDgEQgDgEgGAAIgVAAgAgagjIgdhCIgeBCIgcAAIAAgEIA0hvIAMAAIAxBvIAAAEgAjHgjIAAgDIARglIgmhFIAAgEIAgAAIAWAqIABAAIATgqIAgAAIAAAEIg2BtgAmRgjIAAhxIBHAAIAAAaIgqAAIAAAQIAmAAIAAAaIgmAAIAAAUIAsAAIAAAZgAoCgjIAAhxIAyAAQAOAAARANQAFAGADAHQACAIAAAIQAAAIgCAHQgDAIgFAGQgGAGgHADQgDACgFABQgEABgGAAIgVAAIAAAdgAnlhaIAVAAQAGAAAEgFQACgFAAgGQABgHgDgEIgEgEIgGgBIgVAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.3,-15.2,104.6,30.5);


(lib.Символ63 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkACLIAAgMIg9AAIAAAMIgXAAIAAgiIALAAIAkhUIALAAIAlBUIALAAIAAAigAkRBoIgOgmIgPAmIAdAAgAjBB+QgFgCgEgCIgIgGIgHgIIgGgJIgDgLQgBgGAAgHQAAgkA1gSQAHAAANAEIAJAEIAIAGIAHAHIAFAKIAEAKIABANQAAAlg2ARQgNgBgGgCgAi3AwQgFADgEADQgEADgBAGQgDAFAAAHQAAAHADAGQABAFAEAEQAEADAFACQAEACAFAAQAFAAAFgCQAFgCADgDQAEgEACgFQADgGAAgHQAAgHgDgFQgCgGgEgDQgDgDgFgDQgFgBgFAAQgFAAgEABgApZB/IgKgCIgJgFIgIgFIgHgHIgFgKQgDgEgBgGIgBgNIABgNQABgFADgFIAFgJIAHgIIAIgGIAJgEIAKgCIAKgCQAIAAAIADQAIACAHAFQAIAIADAFIAEAIIADAKIgbAAIgDgIIgFgEIgHgDIgHgBQgGAAgFACQgFACgDAEQgEAEgCAFQgBAFAAAHIABALQACAFAEAFQADADAFACQAFADAGAAIAIgBQADgBADgDQADgBACgDQADgEABgEIAaAAIgCALIgEAIQgCAEgEAEIgGAFQgHAEgIADQgIACgIAAgAJDB/IAAhoIBBAAIAAAYIgmAAIAAAPIAjAAIAAAYIgjAAIAAASIAoAAIAAAXgAIcB/Igbg9IgbA9IgaAAIAAgDIAvhnIAMAAIAvBnIAAADgAGAB/IAAhoIBBAAIAAAYIgnAAIAAAPIAkAAIAAAYIgkAAIAAASIAoAAIAAAXgAE8B/IAAhQIgaAAIAAgYIBOAAIAAAYIgaAAIAABQgADcB/IgGgNIgpAAIgGANIgaAAIAAgDIAvhnIALAAIAvBnIAAADgADNBbIgMgbIgLAbIAXAAgABkB/IAAgpIggAAIAAApIgbAAIAAhoIAbAAIAAAmIAgAAIAAgmIAcAAIAABogAhkB/IAAhoIAsAAQAHAAAGADQAGACAEAFQAFAEACAFQADAHAAAGQAAAFgDAFQgCAFgEADQAHADADAGQADAFAAAIQAAAGgCAGQgCAHgEADQgFAFgGADQgGACgIAAgAhLBoIAWAAQAEAAACgDQACgCAAgEQAAgEgCgCQgDgDgDAAIgWAAgAhLA/IARAAQAEABACgDQACgDAAgDQAAgDgCgCQgCgDgEAAIgRAAgAmgB/IAAhoIBBAAIAAAYIgmAAIAAAPIAjAAIAAAYIgjAAIAAASIAoAAIAAAXgAnIB/Igag9IgbA9IgaAAIAAgDIAvhnIAMAAIAvBnIAAADgAGjggQgMgEgFgEIgHgGIgGgIIgFgJIgCgLIgNAAIAAAqIgbAAIAAhoIAbAAIAAAmIANAAQAHgdAzgLQAGAAAMAFIAIAEIAHAGQADADADAFQADAEABAFIADAKIABAMQgFAegKAJQgVAOgNABQgNAAgGgCgAGohuIgIAEQgEAEgCAFQgCAHAAAGQAAAGACAHQACAEAEAEQAEAEAEABQAFADAFAAQAFAAAFgDQAEgBAEgEQAEgEACgEQACgHAAgGQAAgGgCgHQgCgFgEgEIgIgEQgFgCgFAAQgFAAgFACgAlwgiIgJgDIgIgHIgHgHIgFgKQgCgFgBgFQgCgHAAgGQAAgkA2gSQAHAAANADIAJAEIAIAGIAHAIIAFAJIADALIABANQAAAkg1ASQgOgBgGgDgAlmhuIgIAEQgEAEgCAFQgCAHAAAGQAAAGACAHQACAEAEAEQAEAEAEABQAFADAFAAQAFAAAEgDQAFgBAEgEQAEgEACgEQACgHAAgGQAAgGgCgHQgCgFgEgEIgJgEQgEgCgFAAQgFAAgFACgAjtggIgKgDIgJgDIgIgGQgEgEgDgEQgDgEgCgFQgDgFgBgGIgBgMIABgNQABgFADgFQACgFADgFQADgEAEgDIAIgGIAJgEIAKgCIAJgBQAJAAAIACQAIACAGAFQAJAHADAFIAEAIIACAKIgaAAIgDgHQgCgDgDgBIgHgEIgIgBQgFABgFACQgFACgDADQgEAEgCAGQgCAGAAAGQAAAFACAGQACAFAEAEQADAEAFACQAFADAFAAIAJgBIAGgEIAFgEQADgEABgEIAaAAIgCAKIgEAJIgGAHIgGAFQgHAFgIACQgIADgJAAgAILggIAAhRIgaAAIAAgXIBOAAIAAAXIgaAAIAABRgAEhggIAAgfIgOAAIgSAfIgeAAIAAgEIAUghIgIgIQgDgFgCgFIgCgLQAAgGABgFQACgGADgEQACgGAFgDQAFgEAGgCQAGgCAHAAIAuAAIAABogAEFhsQgDADAAAGQAAAEADAFQADADAFAAIAUAAIAAgaIgUAAQgFAAgDAFgADGggIgbg9IgbA9IgaAAIAAgEIAvhlIAMAAIAvBlIAAAEgAAeggIAAhoIAsAAQAHAAAGACQAFADAFAEQAEAFADAFQACAGAAAGQAAAGgCAEQgCAGgEACQAHADADAGQADAGAAAHQAAAHgCAFQgDAHgEAEQgEAFgGACQgGADgIAAgAA3g3IAVAAQAEAAADgEQABgCAAgDQAAgEgBgDQgDgCgEAAIgVAAgAA3hgIARAAQAEAAACgCQACgCAAgEQAAgDgCgDQgCgDgEAAIgRAAgAgIggIgGgNIgpAAIgHANIgaAAIAAgEIAwhlIALAAIAtBlIAAAEgAgXhEIgMgcIgMAcIAYAAgAiPggIAAhRIgZAAIAAgXIBNAAIAAAXIgZAAIAABRgAoNggIAAhoIBAAAIAAAXIgmAAIAAAPIAjAAIAAAYIgjAAIAAATIAoAAIAAAXgApDggIAAgqIggAAIAAAqIgcAAIAAhoIAcAAIAAAmIAgAAIAAgmIAbAAIAABog");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64.6,-13.9,129.3,27.9);


(lib.Символ62 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnPB6QgEgBgEgDQgEgCgEgEIgGgHIgFgIIgDgLIgBgMQAAghAygRQAGAAAMADIAJAEIAHAGIAGAHIAFAIIAEALIABALQAAAigyARQgNgBgGgCgAnFAyQgFACgDADQgEADgBAFQgDAFAAAGQAAAHADAFQABAFAEADQADAEAFABQAEACAFAAQAFAAAEgCQAEgBAEgEQADgDACgFQACgFAAgHQAAgGgCgFQgCgFgDgDIgIgFQgEgCgFAAIgJACgAozB7IgJgCIgIgEIgHgFQgEgDgDgEIgFgJQgCgEgBgGIgBgMIABgLQABgGACgEIAFgJQADgEAEgDIAHgFIAIgEIATgDQAIAAAHACQAIACAGAEQAIAHACAFIAEAHIACAKIgYAAQgBgEgCgDIgFgEIgGgDIgHgBQgGAAgEACQgFACgDAEQgDAEgCAEQgCAFAAAGQAAAGACAFQACAFADADQADAEAFACQAEACAGAAIAHAAIAHgEIAEgEIADgHIAZAAIgCAJIgEAIIgFAHIgGAFQgGAFgIACQgHACgIAAgAjbB7IAAgwIgxAwIgJAAIAAhhIAZAAIAAAwIAygwIAJAAIAABhgAk6B7IgZg5IgZA5IgYAAIAAgDIAshfIAKAAIAsBfIAAADgAquB7IAAgwIgxAwIgJAAIAAhhIAZAAIAAAwIAygwIAJAAIAABhgAjngOIAAgLIg6AAIAAALIgUAAIAAghIAJAAIAihNIAKAAIAjBNIAKAAIAAAhgAj3gvIgOgjIgNAjIAbAAgAB0gbIgIgEQgEgCgEgDIgGgHIgFgJIgDgKIgBgMQAAgiAxgQQAHAAAMADIAIAEIAIAFIAGAHIAFAJIADAKQACAGAAAGQAAAigzARQgMgBgGgDgAB+hjIgIAFQgEAEgCAFQgCAFAAAGQAAAGACAGQACAEAEAEQADADAFACQAEACAFAAQAEAAAEgCQAFgCAEgDQADgEACgEQACgGAAgGQAAgGgCgFQgCgFgDgEQgEgDgFgCQgEgBgEAAIgJABgAmAgbIgJgEQgEgCgDgDIgGgHIgFgJIgEgKIgBgMQAAgiAygQQAGAAANADIAIAEIAIAFIAGAHIAFAJIADAKQABAGAAAGQAAAigyARQgMgBgGgDgAl3hjQgEACgDADQgEAEgCAFQgCAFAAAGQAAAGACAGQACAEAEAEQADADAEACQAFACAEAAQAFAAAEgCQAFgCADgDQAEgEACgEQACgGAAgGQAAgGgCgFQgCgFgEgEIgIgFIgJgBIgJABgAFQgZIgJgCIgIgFIgIgFQgEgDgCgEIgFgIQgDgFgBgFIgBgMIABgMQABgFADgFIAFgIQACgEAEgDIAIgGIAIgEIAJgCIAJgBQAIAAAHACQAIACAGAFQAIAHADAEIAEAIIACAJIgZAAQgBgEgCgCIgEgFQgDgCgEAAIgHgBQgFAAgFACQgEACgDADQgEAEgBAFQgCAFAAAGQAAAFACAFQABAFAEAEQADAEAEACQAFACAFAAIAIgBIAGgDIAFgFIADgHIAYAAIgCAKIgEAIIgEAHIgGAFQgHAEgHACQgIACgIAAgALRgZIAAhiIAYAAIAABigAJxgZIAAhiIAZAAIAAAdIASAAQAFAAAKADQAGADAFAFQAEAFACAGQACAGAAAGQAAAHgCAGQgCAGgEAFQgFAFgGADQgKADgFAAgAKKgwIARAAQAFAAADgDQADgEAAgFQAAgEgDgEQgDgDgFAAIgRAAgAI/gZIAAgoIgfAAIAAAoIgZAAIAAhiIAZAAIAAAkIAfAAIAAgkIAZAAIAABigAHUgZIAAgwIgxAwIgJAAIAAhiIAaAAIAAAwIAxgwIAJAAIAABigAEEgZIgWgmIgJABIAAAlIgaAAIAAhiIAaAAIAAAlIABAAIAIgBQAEAAACgCQAFgDACgGQADgGAAgTIAaAAQAAAUgDAIQgCAHgDAGQgGAHgFADIAaArIAAAEgAAbgZIAAhLIgYAAIAAgXIBIAAIAAAXIgXAAIAABLgAhXgZIAAhLIgYAAIAAgXIBIAAIAAAXIgXAAIAABLgAiXgZIAAgdIgNAAIgQAdIgcAAIAAgEIATgfIgIgHQgDgEgCgGQgBgFAAgFQgBgFACgGQABgFADgEQACgFAFgDQAEgEAGgCQAFgCAHAAIArAAIAABigAixhhQgCAEAAAFQAAAEADAEQADAEAEAAIASAAIAAgYIgSAAQgFAAgDADgAnDgZIgRgfIgBAAIgSAfIgbAAIAAgEIAfgwIgcgqIAAgEIAaAAIAQAZIAAAAIAQgZIAaAAIAAAEIgcAqIAfAwIAAAEgAopgZIAAhiIAZAAIAABigAqJgZIAAhiIAZAAIAAAdIASAAQAGAAAJADQAGADAFAFQAEAFADAGQACAGAAAGQAAAHgCAGQgDAGgEAFQgFAFgGADQgJADgGAAgApwgwIASAAQAFAAADgDQACgEAAgFQAAgEgCgEQgDgDgFAAIgSAAgArogZIAAhiIApAAQAHAAAFADQAGACAEAEQAEAEACAFQADAGAAAGQAAAFgCAEQgDAFgDADQAGADADAFQADAFAAAHQAAAGgCAGQgCAGgEAEQgEAEgGACQgFADgIAAgArQgvIAUAAQADAAACgDQACgCAAgEQAAgDgCgCQgCgDgDAAIgUAAgArQhVIAQAAQADAAACgCQACgCAAgEQAAgDgCgCQgCgCgDAAIgQAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.6,-12.5,149.1,25.2);


(lib.Символ61 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ApwC6QgJgEgGgFQgFgGgEgIQgDgJAAgLIAeAAQAAAIAEAFQAFAEAHAAQAIAAAFgEQAEgFAAgGQAAgGgEgEQgFgEgIAAIgJAAIAAgcIAJAAQAGAAADgEQADgDAAgFQAAgEgDgDQgDgEgGAAQgFAAgEACQgCACAAAEIgeAAQgBgJADgHQAEgGAFgFQAGgEAIgDQAHgCAJAAQALAAAIADQAIAEAFAFQAGAGADAGQACAHAAAHQAAAHgCAHQgDAHgGAEIAIAGIAHAHIADAJIABAKQAAAJgDAHQgDAIgHAGQgGAFgKADQgJADgNAAQgKAAgJgCgANbC6IAAhAIhDBAIgMAAIAAiDIAiAAIAABAIBDhBIAMAAIAACEgALHC6IAAhAIhCBAIgMAAIAAiDIAiAAIAABAIBDhBIAMAAIAACEgAI1C6IAAg1IgpAAIAAA1IgiAAIAAiDIAiAAIAAAvIApAAIAAgvIAiAAIAACDgAF6C6IAAiDIBRAAIAAAeIgwAAIAAASIAsAAIAAAeIgsAAIAAAXIAyAAIAAAegAE2C6IAAg1IgpAAIAAA1IgiAAIAAiDIAiAAIAAAvIApAAIAAgvIAiAAIAACDgACzC6IgdgzIgHABIAAAyIgiAAIAAgyIgHgBIgdAzIglAAIAAgFIAjg6QgGgEgJgKQgFgHgCgJQgDgMAAgaIAjAAQgBAYADAJQADAHAGAEIAHADIAKACIAAgxIAiAAIAAAxIAKgCIAHgDQAGgEACgHQAEgJgBgYIAjAAQAAAagDAMQgDAJgEAHQgJAKgHAEIAkA6IAAAFgAABC6IgFgQIg0AAIgIAQIghAAIAAgFIA7iAIAPAAIA5CAIAAAFgAgtCNIAeAAIgQgjgAjSC6IAAiDIA5AAQAQAAAUAPQAFAHAEAJQACAIAAAKQAAAJgCAJQgEAJgFAGQgHAHgIAEIgKADIgLABIgYAAIAAAigAixB6IAYAAQAHAAAEgGQADgFAAgHQABgIgEgFQgCgDgDgCQgCgBgEAAIgYAAgAkWC6IAAhkIgpAAIAABkIgiAAIAAiDIBtAAIAACDgAnWC6IAAgEIAVgqIgshQIAAgFIAlAAIAZAwIABAAIAWgwIAlAAIAAAFIg+B+gAryC6IAAiDIBSAAIAAAeIgxAAIAAASIAtAAIAAAeIgtAAIAAAXIAzAAIAAAegAt0C6IAAiDIBeAAIAAAeIg8AAIAAAQIAYAAQAIAAAMADQAJAEAGAGQAGAGADAHQADAIAAAIQAAAIgDAIQgDAIgGAGQgGAGgJADQgMAEgIAAgAtSCcIAYAAQAGAAAEgEQADgEAAgFQAAgFgDgEQgEgDgGAAIgYAAgAM8AtQgGgCgEgEQgEgEgDgGQgCgGAAgHIATgCQAAAFAEADQADACAGAAQAGAAAEgCQADgDABgFIAUACQgBAHgCAGQgDAGgDAEQgFAEgGACQgGADgHAAQgIAAgGgDgALqgPIgMgDIgLgFIgLgHQgFgFgDgFQgEgFgDgHIgFgNIgBgQIABgPIAFgOQADgGAEgGIAIgJIALgIIALgFIAZgEQAKAAAKADQAKADAJAGQALAJADAGIAFALIADAMIghAAIgEgJIgHgGQgDgCgFgBQgEgCgFAAQgIAAgGADQgGADgEAFQgFAFgCAGQgCAHAAAIQAAAHACAHQACAHAFAFQAEAFAGACQAGAEAIAAIAKgCIAIgEIAHgGIAEgKIAhAAIgDANIgFALIgHAJIgIAHQgIAGgLADQgKADgKAAgAkogPIgMgDIgMgFIgKgHQgFgFgDgFQgEgFgDgHQgDgGgCgHIgBgQIABgPQACgIADgGIAHgMIAIgJIAKgIIAMgFIAMgDIAMgBQALAAAKADQAKADAIAGQALAJAEAGIAFALIADAMIghAAQgCgFgDgEIgGgGQgEgCgEgBQgEgCgGAAQgHAAgGADQgGADgFAFQgEAFgCAGQgDAHAAAIQAAAHADAHQACAHAEAFQAFAFAGACQAGAEAHAAQAGAAAEgCQAFgBAEgDIAGgGIAFgKIAgAAQAAAHgCAGIgFALIgHAJIgIAHQgJAGgKADQgKADgLAAgAtFgPIgMgDIgLgFIgLgHQgFgFgDgFQgEgFgDgHIgFgNIgBgQIABgPIAFgOQADgGAEgGIAIgJIALgIIALgFIAMgDIAMgBQALAAAKADQAKADAJAGQALAJADAGIAFALIADAMIghAAIgEgJIgHgGQgDgCgFgBQgEgCgGAAQgHAAgGADQgGADgEAFQgFAFgCAGQgCAHAAAIQAAAHACAHQACAHAFAFQAEAFAGACQAGAEAHAAQAGAAAFgCIAIgEQAEgCACgEQADgEACgGIAhAAIgDANIgFALIgHAJIgIAHQgIAGgLADQgKADgLAAgAJLgPIAAiDIBRAAIAAAeIgwAAIAAASIAsAAIAAAeIgsAAIAAAXIAyAAIAAAegAHKgPIAAiDIA4AAQAJAAAHADQAHADAGAFQAGAGADAHQADAIAAAIQAAAGgDAGQgDAHgFADQAJAEAEAIQADAGAAAJQAAAJgCAHQgDAIgFAGQgGAGgHADQgIADgKAAgAHqgtIAbAAQAFAAADgDQACgEAAgEQAAgEgCgEQgDgDgFAAIgbAAgAHqhfIAWAAQAEAAADgEQADgDAAgEQAAgEgDgDQgDgDgEAAIgWAAgAFUgPIAAhBIhDBBIgLAAIAAiDIAiAAIAABAIBChBIAMAAIAACEgADSgPIgHgRIg0AAIgIARIghAAIAAgFIA8iAIAOAAIA7CAIAAAFgACig8IAeAAIgPgjgAAAgPIAAiDIA2AAQAJAAAIADQAHADAFAFQAGAGADAHQAEAIAAAIQAAAGgDAGQgDAHgFADQAIAEAEAIQAEAGAAAJQAAAJgDAHQgCAIgGAGQgFAGgHADQgIADgKAAgAAfgtIAbAAQAFAAACgDQADgEAAgEQAAgEgDgEQgDgDgEAAIgbAAgAAfhfIAVAAQAFAAADgEQACgDAAgEQAAgEgCgDQgDgDgFAAIgVAAgAhDgPIAAiDIAiAAIAACDgAjEgPIAAiDIAiAAIAAAnIAYAAQAIAAAMAEQAJADAGAHQAGAGADAJQADAIAAAJQAAAJgDAIQgDAIgGAGQgGAHgJAEQgMAEgIAAgAiigtIAYAAQAHAAADgFQAEgFAAgGQAAgHgEgEQgEgFgGAAIgYAAgAmJgPIgIgRIg0AAIgHARIghAAIAAgFIA7iAIAPAAIA7CAIAAAFgAm6g8IAeAAIgPgjgApfgPIAAiDIA6AAQAQAAATAPQAGAHADAIQADAJAAAJQAAAKgDAIQgDAJgGAHQgGAHgIAEQgFACgFABIgLABIgYAAIAAAigAo9hPIAYAAQAHAAADgGQAEgFAAgIQAAgHgDgFIgFgFQgDgBgDAAIgYAAgArhgPIAAiDIBfAAIAAAeIg9AAIAAAQIAYAAQAIAAANADQAIAEAGAGQAGAGADAHQADAIAAAIQAAAIgDAIQgDAIgGAGQgGAGgIADQgNAEgIAAgAq/gtIAYAAQAGAAAEgEQAEgEAAgFQAAgFgEgEQgEgEgGAAIgYAAgAE1icQgGgCgEgEQgEgEgDgGQgCgGAAgIIAUgBQAAAFADACQADADAHAAQAFAAAEgCQADgDABgFIAUABQgBAIgCAGQgCAGgEAEQgFAEgFACQgHADgHAAQgIAAgGgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-89.3,-18.8,178.6,37.8);


(lib.Символ58 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ddd5();
	this.instance.setTransform(-304.7,-152.3,1.016,1.016);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-304.7,-152.3,609.4,304.7);


(lib.Символ56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJFBUIAAhSIhVBSIgQAAIAAilIAsAAIAABRIBWhSIAPAAIAACmgAGYBUIglhBIgQABIAABAIgsAAIAAilIAsAAIAAA/IADAAQAIAAAGgBQAGgCAFgDQAIgEAEgKQAEgMgBgfIAtAAQAAAhgEAPQgDAMgGAJQgLAMgIAEIAtBKIAAAGgADJBUIAAh/IgpAAIAAgmIB9AAIAAAmIgqAAIAAB/gAAhBUIAAilIBoAAIAAAmIg+AAIAAAYIA5AAIAAAkIg5AAIAAAdIBBAAIAAAmgAgdBUIgrhgIgsBgIgqAAIAAgFIBNiiIASAAIBJCiIAAAFgAkvBUIAAilIB5AAIAAAmIhOAAIAAAUIAfAAQAKAAAQAFQAMAFAHAHQAIAGAEAJQADALAAAKQAAAKgDAKQgEAKgIAIQgHAIgMAEQgQAEgKAAgAkEAuIAfAAQAJAAAFgFQADgEAAgIQAAgGgDgFQgFgEgJAAIgfAAgAlvBUIgJgVIhCAAIgKAVIgqAAIAAgFIBLiiIATAAIBMCiIAAAFgAmGAbIgUgrIgTArIAnAAgApHBUIAAh/IgpAAIAAgmIB8AAIAAAmIgoAAIAAB/g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.5,-8.5,125.1,17);


(lib.Символ55 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ApxBUIgQgEIgOgHIgNgJQgHgFgEgHQgFgHgEgIQgEgIgCgJQgBgKAAgKQAAgJABgJQACgKAEgIQAEgIAFgHQAEgGAHgGIANgJQAHgEAHgDIAQgEIAQgBQANAAANADQANAEALAIQAOAMAEAIQAEAGADAHIAEAQIgrAAQgCgHgDgEQgEgFgEgDQgFgDgGgCQgFgBgHAAQgKAAgHADQgIAEgGAGQgFAGgDAJQgDAIAAAJQAAAJADAIQADAJAFAGQAGAHAHADQAIAEAKAAQAHAAAGgBQAGgCAFgEQAEgDAEgFQADgFACgHIAqAAQgBAJgCAIQgDAHgEAHQgDAGgFAFIgKAJQgLAIgOAEQgMADgOAAgAJNBUIAAimIBpAAIAAAmIg+AAIAAAYIA5AAIAAAkIg5AAIAAAeIBAAAIAAAmgAH3BUIAAimIArAAIAACmgAFSBUIAAimIArAAIAAAyIAfAAQAKAAAQAFQALAFAIAIQAHAIAEAJQAEAKAAAMQAAALgEAKQgEALgHAIQgIAJgLAFQgQAFgKAAgAF9AtIAeAAQAJAAAFgGQAFgGgBgIQAAgIgEgGQgFgGgJAAIgeAAgAD7BUIAAhEIg0AAIAABEIgsAAIAAimIAsAAIAAA9IA0AAIAAg9IAsAAIAACmgABFBUIAAhEIg0AAIAABEIgqAAIAAimIAqAAIAAA9IA0AAIAAg9IAsAAIAACmgAhZBUIgKgVIhCAAIgKAVIgqAAIAAgGIBMiiIASAAIBMCiIAAAGgAhxAaIgTgqIgTAqIAmAAgAlqBUIAAimIBKAAQAUAAAZATQAHAJAEALQAEALAAAMQAAAMgEAJQgEAMgHAIQgIAJgLAFQgGADgGABIgOACIgfAAIAAArgAk/ACIAeAAQAJAAAFgFQAEgHAAgKQABgKgFgGQgCgEgEgCQgDgCgFAAIgeAAgAnYBUIAAiAIgpAAIAAgmIB8AAIAAAmIgpAAIAACAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69.7,-8.6,139.4,17.2);


(lib.Символ54 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADIBUIAAhSIhVBSIgPAAIAAilIAsAAIAABRIBVhSIAPAAIAACmgAAkBUIgKgVIhAAAIgKAVIgqAAIAAgFIBMiiIAQAAIBMCiIAAAFgAAMAbIgRgrIgTArIAkAAgAibBUIAAg6IgJAAQgLAAgJgBIgRgFQgHgCgGgEQgGgFgFgGQgFgDgDgHQgEgGgCgJQgDgLgBgcIAAgUIAsAAIAAAUQABAbAEAIQAEAHAHACQAHAEANAAIAIAAIAAhEIAsAAIAAClg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.5,-8.5,49,17);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACeBtIgQgDIgOgIIgNgIQgHgGgEgHQgFgGgEgJQgEgIgCgJQgBgKAAgKQAAgKABgKQACgIAEgHQAEgIAFgIQAEgGAHgFIANgKQAHgEAHgCIAQgFIAQgBQANAAANAEQANAEALAHQAOAMAEAIQAEAGADAHIAEAOIgrAAQgCgFgDgEQgEgFgEgDQgFgDgGgBQgFgCgHAAQgKAAgHADQgIAEgGAGQgFAHgDAGQgDAJAAAKQAAAJADAJQADAIAFAGQAGAHAHAEQAIAEAKgBQAHAAAGgBQAGgCAFgEQAEgCAEgGQADgFACgGIAqAAQgBAIgCAIQgDAHgEAHIgIAMIgKAJQgLAHgOAEQgMAEgOgBgAKDBtIAAimIBpAAIAAAnIg+AAIAAAVIA5AAIAAAnIg5AAIAAAdIBAAAIAAAmgAIsBtIAAhSIhVBSIgPAAIAAimIAsAAIAABRIBVhSIAPAAIAACngAGABtIglhBIgRABIAABAIgsAAIAAimIAsAAIAAA+IADAAQAIAAAGgCQAGgBAFgCQAIgEAEgKQAEgMAAgfIAsAAQAAAhgEAQQgDAKgGAIQgLANgIAFIAtBKIAAAHgAAMBtIAAhSIhTBSIgPAAIAAimIAsAAIAABRIBThSIAPAAIAACngAiXBtIgKgVIhCAAIgKAVIgqAAIAAgGIBMiiIASAAIBMCiIAAAGgAjVAzIAmAAIgTgsgAlwBtIAAh/IgpAAIAAgnIB9AAIAAAnIgpAAIAAB/gAngBtIAAhSIhUBSIgQAAIAAimIAsAAIAABRIBVhSIAQAAIAACngAqMBtIglhBIgQABIAABAIgsAAIAAimIAsAAIAAA+IADAAQAIAAAGgCQAGgBAEgCQAIgEAEgKQAFgMgBgfIAtAAQAAAhgEAQQgDAKgHAIQgKANgJAFIAuBKIAAAHgAgZhFQgHgDgGgFQgFgFgDgHQgDgIAAgKIAZgCQAAAGAEAEQAEACAIAAQAIABACgDQAFgEABgGIAZACQgBAKgDAIQgDAHgFAFQgFAFgIADQgIADgHAAQgKAAgIgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.1,-11.1,150.1,22.2);


(lib.Символ52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFyBRQgHgCgHgFQgHgEgGgFIgLgMQgFgHgEgIQgDgJgCgJQgCgKAAgKQAAg5BWgdQALAAAVAGIAOAHQAHAEAGAFIALAMQAFAHAEAIQADAJACAJQACAKAAAJQAAA6hWAdQgWgCgKgEgAGDgpQgIADgGAFQgGAGgDAJQgEAJAAAJQAAAKAEAKQADAIAGAGQAGAFAIADQAHADAIAAQAIAAAHgDQAIgDAGgFQAGgGAEgIQADgKAAgKQAAgJgDgJQgEgJgGgGQgGgFgIgDQgHgDgIAAQgIAAgHADgADABTIAAimIBoAAIAAAnIg9AAIAAB/gAAwBTIAAimIBoAAIAAAnIg+AAIAAAXIA5AAIAAAlIg5AAIAAAdIBBAAIAAAmgAglBTIAAg6IgIAAQgLAAgJgCIgRgEQgIgDgGgEQgGgEgFgGQgEgDgEgHQgDgHgCgIQgDgLgCgcIAAgVIAtAAIAAAVQAAAaAFAJQAEAGAGADQAIAEAMAAIAIAAIAAhFIAqAAIAACmgAjNBTIAAhSIhUBSIgQAAIAAimIAsAAIAABTIBVhTIAQAAIAACmgAmHBTIAAhDIg0AAIAABDIgsAAIAAimIAsAAIAAA9IA0AAIAAg9IAsAAIAACmg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.9,-8.7,97.8,17.5);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFJBTIAAilIAqAAIAAAxIAgAAQAJABARAFQAKAFAJAIQAHAIAEAJQADAKAAAMQAAALgDAKQgEALgHAIQgJAIgKAGQgRAEgJAAgAFzAtIAfAAQAJAAAFgHQAEgFAAgIQAAgIgFgHQgEgFgJAAIgfAAgABJBTIAAilIAsAAIAAB+IApAAIAAh+IArAAIAAB+IApAAIAAh+IAsAAIAAClgAhFBTIAAilIBnAAIAAAmIg8AAIAAAYIA2AAIAAAkIg2AAIAAAdIA+AAIAAAmgAkXBTIAAilIBoAAIAAAmIg9AAIAAAYIA5AAIAAAkIg5AAIAAAdIBAAAIAAAmgAluBTIAAhDIg0AAIAABDIgrAAIAAilIArAAIAAA8IA0AAIAAg8IAsAAIAAClg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46.3,-8.4,92.6,16.8);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGHBRQgIgCgHgFQgHgEgGgFIgLgMQgFgHgDgIQgEgJgCgJQgCgKAAgKQAAg5BWgdQALAAAVAGIAPAHQAHAEAGAFIALAMQAFAHADAIQAEAJACAJQACAKAAAJQAAA6hXAdQgVgCgKgEgAGXgpQgIADgFAFQgHAGgDAJQgEAJAAAJQAAAKAEAKQADAIAHAGQAFAFAIADQAIADAIAAQAIAAAHgDQAIgDAGgFQAGgGADgIQAEgKAAgKQAAgJgEgJQgDgJgGgGQgGgFgIgDQgHgDgIAAQgIAAgIADgADhBTQgLgEgHgHQgIgIgEgLQgEgLAAgNIAmAAQAAAJAGAGQAFAGAKAAQAKAAAGgGQAGgFAAgIQAAgIgGgFQgGgGgKAAIgMAAIAAghIALAAQAIAAAEgFQAEgEAAgGQAAgGgEgEQgEgEgHAAQgHAAgEACQgEADAAAFIgmAAQgBgMAEgJQAEgIAIgGQAHgFAKgDQAKgDALAAQANAAALAEQAKAEAHAHQAHAHAEAJQADAJAAAJQAAAJgDAIQgEAJgHAFQAGADAEADQAFAEADAFIAEALQACAGAAAIQAAALgEAJQgEAKgJAHQgIAHgMAEQgMAEgQAAQgOAAgLgDgAA7BTIAAimIBpAAIAAAnIg+AAIAAAXIA5AAIAAAlIg5AAIAAAdIBAAAIAAAmgAgDBTIgrhgIgrBgIgqAAIAAgGIBMiiIATAAIBJCiIAAAGgAj9BTIAAimIBoAAIAAAnIg+AAIAAAXIA5AAIAAAlIg5AAIAAAdIBBAAIAAAmgAlFBTIglhBIgJABIAABAIgsAAIAAhAIgJgBIgkBBIgwAAIAAgGIAthKQgIgEgLgMQgGgJgDgMQgEgPAAgiIAsAAQgBAfAFAMQADAJAHAFQAEADAGABQAFACAHABIAAhAIAsAAIAABAQAHgBAGgCIAJgEQAHgFADgJQAFgMgBgfIAsAAQAAAigEAPQgDAMgGAJQgLAMgIAEIAtBKIAAAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.9,-8.7,101.9,17.5);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFUBuIAAhTIhVBTIgPAAIAAimIAsAAIAABQIBVhRIAPAAIAACngACvBuIgKgVIhCAAIgKAVIgqAAIAAgGIBMiiIASAAIBMCiIAAAGgABxA0IAmAAIgTgsgAhABuIAAimIBmAAIAAAmIg7AAIAACAgAiWBuIAAgyIgWAAIgdAyIgwAAIAAgGIAhg2QgIgFgFgIQgGgHgDgJQgDgIAAgKQAAgHACgJQACgJAFgHQAFgIAHgGQAIgGAJgEQAKgDAMAAIBKAAIAACmgAjCgLQgFAGABAGQAAAIAEAGQAFAHAIAAIAfAAIAAgoIgfAAQgIAAgFAHgAlWBuIAAiAIgpAAIAAgmIB8AAIAAAmIgpAAIAACAgAEthEQgHgDgGgFQgFgFgDgIQgDgHAAgKIAZgDQAAAHAEADQAEADAIAAQAIAAAEgCQAFgEABgHIAZADQgBAKgDAHQgDAIgFAFQgFAFgIADQgIADgJAAQgKAAgIgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-38.5,-11,77,22.1);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.asdfasdfa();
	this.instance.setTransform(-7.4,-9.2,0.74,0.74);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.4,-9.2,14.8,18.5);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhYAsIAAgJIgvAAIAAAJIgRAAIAAgbIAIAAIAbg8IAJAAIAcA8IAIAAIAAAbgAhlARIgLgaIgMAaIAXAAgAGJAjIAAhOIAUAAIAAAZIAPAAQAEgBAIADQAFACAEAEQADAEACAFQACADAAAFQAAAGgCAEQgCAFgDAFQgEAEgFACQgIACgEAAgAGdARIAOAAQAFAAACgDQACgDAAgEQAAgEgCgDQgDAAgEAAIgOAAgAEQAjIAAhOIAVAAIAAA8IATAAIAAg8IAVAAIAAA8IATAAIAAg8IAVAAIAABOgADnAjIAAhOIAVAAIAABOgACZAjIAAhOIAVAAIAAAZIAOAAQAFgBAHADQAGACADAEQAEAEACAFQABADAAAFQAAAGgBAEQgCAFgEAFQgDAEgGACQgHACgFAAgACuARIAOAAQAEAAADgDQACgDgBgEQAAgEgCgDQgCAAgEAAIgOAAgABwAjIAAgjIgQARIgDAAIgQgRIAAAjIgVAAIAAhOIAHAAIAfAjIAggjIAHAAIAABOgAgPAjIAAglIgnAlIgIAAIAAhOIAVAAIAAAnIAognIAGAAIAABOgAjSAjIAAhOIAxAAIAAATIgdAAIAAALIAbAAIAAAQIgbAAIAAAOIAeAAIAAASgAkgAjIAAhOIAiAAQAFAAAFACQAEACADAEQAEADACAFQACAEAAAFQAAAEgCAEQgCADgDACQAFADADACQACAEAAAGQAAAFgCAEQgBAGgDACQgEAEgEACQgFACgGAAgAkMARIAQAAQAAAAABAAQABAAAAgBQABAAAAAAQABgBAAAAQACgCAAgDQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQgBgDgDAAIgQAAgAkMgLIAMAAQABAAABgBQAAAAABAAQAAAAABgBQAAAAABgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBAAgBAAIgMAAgAk+AjIgFgKIgfAAIgFAKIgUAAIAAgDIAkhLIAJAAIAkBLIAAADgAlJAIIgJgTIgJATIASAAgAmZAjIAAggIgZAAIAAAgIgVAAIAAhOIAVAAIAAAdIAZAAIAAgdIAVAAIAABOg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-45.6,-4.4,91.3,8.9);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AyYEyIAApjMAkxAAAIAAJjg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-117.7,-30.6,235.6,61.3);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-68.4,0,68.5,0).s().p("AqrYnMAAAgxNIVXAAMAAAAxNg");
	this.shape.setTransform(35,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-15.3,0,15.3,0).s().p("AiYYnMAAAgxNIExAAMAAAAxNg");
	this.shape_1.setTransform(-88.2,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-103.5,-157.6,207,315.2);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FF7600","#A81C03","#FF5F00","#FF4200"],[0,0.51,0.576,1],-1.5,49.5,-1.5,-0.7).s().p("Ay+E7IAAp1MAl9AAAIAAJ1g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-121.5,-31.6,243.1,63.2);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA/BTQgLgEgHgHQgIgHgEgLQgEgMAAgNIAmAAQAAAJAGAHQAFAFAKABQAKgBAGgFQAGgGAAgHQAAgJgGgFQgGgGgKAAIgMAAIAAghIALAAQAIAAAEgFQAEgEAAgFQAAgHgEgDQgEgFgHAAQgHAAgEADQgEACAAAFIgmAAQgBgLAEgKQAEgHAIgGQAHgGAKgDQAKgDALAAQANAAALAFQAKADAHAHQAHAIAEAIQADAJAAAJQAAAJgDAIQgEAJgHAFQAGADAEADQAFAEADAFIAEALQACAHAAAHQAAALgEAJQgEAKgJAHQgIAIgMADQgMAFgQAAQgOAAgLgEgApNBTQgLgEgHgHQgIgHgEgLQgEgMAAgNIAmAAQAAAJAGAHQAFAFAKABQAKgBAGgFQAGgGAAgHQAAgJgGgFQgGgGgKAAIgMAAIAAghIALAAQAIAAAEgFQAEgEAAgFQAAgHgEgDQgEgFgHAAQgHAAgEADQgEACAAAFIgmAAQgBgLAEgKQAEgHAIgGQAHgGAKgDQAKgDALAAQANAAALAFQAKADAHAHQAHAIAEAIQADAJAAAJQAAAJgDAIQgEAJgHAFQAGADAEADQAFAEADAFIAEALQACAHAAAHQAAALgEAJQgEAKgJAHQgIAIgMADQgMAFgQAAQgOAAgLgEgAHqBTIAAilIArAAIAAAxIAfAAQAKABAQAFQALAFAIAIQAHAIAEAJQAEAKAAAMQAAALgEAKQgEALgHAIQgIAIgLAGQgQAEgKAAgAIVAtIAeAAQAJAAAFgHQAFgFgBgIQAAgIgEgHQgFgFgJAAIgeAAgAF8BTIAAh/IgpAAIAAgmIB8AAIAAAmIgpAAIAAB/gAEjBTIgJgVIhDAAIgKAVIgqAAIAAgFIBMijIATAAIBLCjIAAAFgAEMAaIgUgrIgTArIAnAAgAgVBTIgJgVIhDAAIgKAVIgqAAIAAgFIBMijIATAAIBJCjIAAAFgAgsAaIgUgrIgTArIAnAAgAjHBTIglhBIgRABIAABAIgsAAIAAilIAsAAIAAA/IADAAQAIAAAGgBQAGgCAFgDQAIgEAEgKQAEgMAAgfIAsAAQAAAhgEAPQgDAMgGAJQgLAMgIAEIAtBKIAAAGgAlpBTIgJgVIhDAAIgKAVIgqAAIAAgFIBMijIATAAIBLCjIAAAFgAmAAaIgUgrIgTArIAnAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.4,-8.7,124.9,17.4);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#420000").s().p("Ay+ETIAAolMAl9AAAIAAIlg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-121.5,-27.5,243.1,55);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABjBeIAAgTIhjAAIAAATIgjAAIAAg4IASAAIA3iDIASAAIA8CDIASAAIAAA4gABHAmIgYg8IgXA8IAvAAgAHrBLIAAhQIhVBQIgQAAIAAimIAsAAIAABTIBWhUIAPAAIAACngAE+BLIglhBIgJABIAABAIgrAAIAAhAIgJgBIglBBIgvAAIAAgHIAthIQgJgFgKgNQgHgJgDgLQgDgQAAghIAsAAQgBAeAFAMQADAKAHAFQAEACAFACQAGACAHAAIAAg/IArAAIAAA/QAIAAAGgCIAJgEQAHgFADgKQAFgMgBgeIAsAAQAAAhgEAQQgDALgGAJQgLANgIAFIAtBIIAAAHgAhlBLIAAhQIhVBQIgPAAIAAimIAsAAIAABTIBVhUIAQAAIAACngAlwBLIAAimIBKAAQAVAAAYAUQAIAIAEAMQADAKABAMQgBAMgDAMQgEAJgIAIQgHAJgMAGQgFACgGABIgPACIgeAAIAAArgAlEgFIAeAAQAIAAAGgHQAEgHAAgKQABgJgFgHQgCgDgEgCQgEgCgEAAIgeAAgAoWBLIAAimIB5AAIAAAnIhOAAIAAAUIAfAAQAKAAAQAEQALAFAIAIQAIAIADAHQAEAKAAAKQAAAKgEAKQgDAKgIAIQgIAIgLAEQgQAFgKAAgAnrAlIAfAAQAIAAAFgGQAEgEAAgHQAAgGgEgFQgFgFgIAAIgfAAg");
	this.shape.setTransform(3.2,1.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.4,-8.4,107.1,18.9);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah/BRQgHgCgHgFQgHgEgGgFIgLgMQgFgHgEgIQgDgJgCgJQgCgKAAgKQAAg5BWgdQALAAAVAGIAOAHQAHAEAGAFIALAMQAFAHAEAIQADAJACAJQACAKAAAJQAAA6hWAdQgWgCgKgEgAhugpQgIADgGAFQgGAGgDAJQgEAJAAAJQAAAKAEAKQADAIAGAGQAGAFAIADQAHADAIAAQAIAAAHgDQAIgDAGgFQAGgGAEgIQADgKAAgKQAAgJgDgJQgEgJgGgGQgGgFgIgDQgHgDgIAAQgIAAgHADgABRBUIgPgEIgPgHIgNgJQgGgGgFgHQgFgGgDgIQgEgIgCgKQgCgJAAgKQAAgJACgKQACgJAEgIQADgIAFgHQAFgHAGgFIANgKQAHgEAIgCIAPgEIAQgCQAOAAAMAEQAOAEAKAHQAOAMAFAIQAEAGACAHIAEAQIgqAAQgCgGgEgFQgDgFgFgDQgFgDgFgBQgGgCgHAAQgJAAgIAEQgIADgFAGQgGAHgDAIQgDAJAAAJQAAAIADAJQADAIAGAHQAFAGAIAEQAIAEAJAAQAHAAAGgCQAGgCAFgDQAFgDADgFQAEgGACgGIAqAAQgBAIgDAIQgCAIgEAGIgJAMIgKAJQgLAHgNAEQgNAEgOAAgAE2BTIAAhSIhVBSIgPAAIAAimIAsAAIAABTIBVhTIAPAAIAACmgAkBBTIAAhDIg0AAIAABDIgsAAIAAimIAsAAIAAA9IA0AAIAAg9IAsAAIAACmg");
	this.shape.setTransform(-15.5,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51,-8.7,71,17.5);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGLBRQgHgCgHgFQgHgEgGgFIgLgMQgFgHgDgIQgEgJgCgJQgCgKAAgKQAAg5BWgdQALAAAVAGIAPAHQAHAEAFAFIALAMQAGAHADAIQAEAJACAJQABAKAAAJQAAA6hWAdQgWgCgKgEgAGcgpQgIADgGAFQgGAGgDAJQgEAJAAAJQAAAKAEAKQADAIAGAGQAGAFAIADQAIADAIAAQAIAAAGgDQAIgDAHgFQAFgGAEgIQAEgKgBgKQABgJgEgJQgEgJgFgGQgHgFgIgDQgGgDgIAAQgIAAgIADgAh3BRQgIgCgHgFQgHgEgGgFIgLgMQgFgHgEgIQgDgJgCgJQgCgKAAgKQAAg5BWgdQALAAAVAGIAOAHQAHAEAHAFIALAMQAEAHAEAIQAEAJABAJQADAKAAAJQAAA6hXAdQgWgCgJgEgAhngpQgIADgFAFQgHAGgDAJQgEAJAAAJQAAAKAEAKQADAIAHAGQAFAFAIADQAIADAHAAQAIAAAIgDQAHgDAGgFQAHgGADgIQADgKABgKQgBgJgDgJQgDgJgHgGQgGgFgHgDQgIgDgIAAQgHAAgIADgABZBUIgQgEIgOgHIgOgJQgGgGgEgHQgFgGgEgIQgEgIgCgKQgBgJgBgKQABgJABgKQACgJAEgIQAEgIAFgHQAEgHAGgFIAOgKQAGgEAIgCIAQgEIAQgCQANAAANAEQANAEAKAHQAOAMAFAIQAEAGADAHIADAQIgqAAQgCgGgEgFQgDgFgFgDQgEgDgGgBQgGgCgGAAQgKAAgHAEQgJADgFAGQgFAHgEAIQgDAJAAAJQAAAIADAJQAEAIAFAHQAGAGAHAEQAIAEAKAAQAHAAAFgCQAHgCAEgDQAFgDADgFQAEgGACgGIAqAAQgBAIgDAIQgCAIgEAGQgDAGgGAGIgKAJQgKAHgOAEQgMAEgOAAgADyBTIAAh/IgqAAIAAgnIB9AAIAAAnIgpAAIAAB/gAlKBTIAAimIBKAAQAUAAAZAUQAHAJAFALQADALAAAMQAAAMgDAJQgFALgHAJQgIAJgLAFQgGADgGABIgOABIgfAAIAAArgAkfACIAeAAQAJAAAFgGQAFgHgBgJQABgKgEgHQgDgDgEgCQgDgCgFAAIgeAAgAmgBTIAAh+Ig0AAIAAB+IgsAAIAAimICLAAIAACmg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51.4,-8.7,102.8,17.5);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjKBpIAAgUIhvAAIAAAUIgoAAIAAg/IATAAIBBiSIAVAAIBDCSIATAAIAAA/gAjnAqIgbhDIgbBDIA2AAgAEEBUIAAiPIguAAIAAgsICMAAIAAAsIguAAIAACPgABIBUIAAi7IB1AAIAAAsIhGAAIAAAZIA/AAIAAAqIg/AAIAAAhIBIAAIAAArgAgZBUIAAhbIhfBbIgSAAIAAi7IAyAAIAABdIBdhdIASAAIAAC7g");
	this.shape.setTransform(29,-8.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.5,-18.8,70.9,21.2);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACNBgQgNgFgJgHQgJgJgEgNQgFgNAAgQIAsAAQAAAMAHAGQAGAIALgBQAMABAHgIQAHgGAAgIQAAgJgHgHQgHgGgMgBIgNAAIAAgmIANAAQAIgBAFgFQAFgEAAgHQAAgIgFgEQgEgFgJAAQgIAAgFADQgEADAAAFIgsAAQgBgNAFgLQAEgIAJgHQAJgHAMgDQAKgEANAAQAQAAAMAGQAMADAIAJQAIAIAEAKQAFAKAAALQAAALgFAJQgEAKgIAHQAHADAFADQAFAFAEAGQADAGACAHQABAHAAAJQAAAMgEALQgFAMgKAIQgJAIgOAEQgOAFgTABQgPAAgNgFgAgyBhIAAjAIB3AAIAAAsIhGAAIAAAbIBBAAIAAArIhBAAIAAAiIBJAAIAAAsgAjzBhIAAjAICMAAIAAAsIhaAAIAAAXIAkAAQALAAATAGQANAFAJAJQAJAIAEAKQAEALAAAMQAAAMgEAMQgEALgJAJQgJAJgNAFQgTAGgLAAgAjBA0IAjAAQAKAAAGgFQAFgGAAgIQAAgHgFgFQgGgHgKAAIgjAAg");
	this.shape.setTransform(27.3,17.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.9,7.4,48.9,20.2);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABYDEIAAgfIihAAIAAAfIg7AAIAAhcIAcAAIBfjYIAbAAIBiDYIAdAAIAABcgAghBnIBMAAIgnhkgAJHCkIAAiHIiMCHIgZAAIAAkRIBIAAIAACFICLiGIAaAAIAAESgAC0CkIAAkRICsAAIAAA/IhmAAIAAAnIBdAAIAAA9IhdAAIAAAwIBpAAIAAA+gAlWCkIAAgHIArhZIhdimIAAgLIBPAAIA0BmIACAAIAvhmIBMAAIAAALIiCEGgAnbCkIgyhWIgDAAIgzBWIhLAAIAAgKIBZiHIhQh1IAAgLIBKAAIArBHIACAAIAshHIBJAAIAAALIhPB1IBZCHIAAAKgAIHiBQgNgEgJgIQgJgJgEgMQgFgMgBgRIAqgEQAAALAGAFQAIAFANAAQAMAAAHgEQAIgFABgMIApAEQgBARgEAMQgGAMgIAJQgJAIgMAEQgNAFgQAAQgQAAgMgFg");
	this.shape.setTransform(25.6,6.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39.9,-12.9,131,39.3);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.baba_03();
	this.instance.setTransform(-42.6,-17.5,0.402,0.402);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-42.6,-17.5,85.3,35);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C59D8F").s().p("ACcAmQgogBgQgEQgRgFgBgIQgBgIARgOQARgQAcgCQAbgBAVAJQAUAJACAGQABAIgJAOQgHANgiAAIgIAAgAifAUQgpgDgHgQQgHgNACgIQADgIAVgGQAXgGAaAEQAbAFAPASQAPAQgCAIQgCAIgRADIgQABQgPAAgZgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21.3,-3.9,42.7,7.8);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#990099","#FF9CFF"],[0,1],-216.6,-216.7,216.8,216.7).s().p("Egv4AYSMAAAgwjMBfxAAAMAAAAwjg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-306.5,-155.4,613,311);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFF402").s().p("ABpBgIAAgSIhkAAIAAASIghAAIAAg4IARAAIA3iDIASAAIA8CDIASAAIAAA4gABOAoIgYg7IgYA7IAwAAgAneBLQgIgCgHgFQgHgEgGgFIgLgMQgFgHgEgIQgDgJgCgJQgCgKAAgJQAAg6BWgdQALAAAVAGIAOAHQAHAEAHAFIAKAMQAFAHAEAIQADAJADAJQACAKAAAKQgBA5hWAdQgWgCgJgEgAnOgvQgIADgGAFQgGAGgDAJQgEAJAAAKQAAAJAEAKQADAIAGAGQAGAFAIADQAIADAHAAQAIAAAIgDQAHgDAGgFQAHgGADgIQADgKABgJQgBgKgDgJQgDgJgHgGQgGgFgHgDQgIgDgIAAQgHAAgIADgAG4BNIAAimIArAAIAAAyIAeAAQALAAAQAGQALAEAHAJQAIAIAEALQADAIABALQgBAMgDAKQgEALgIAIQgHAIgLAFQgQAFgLAAgAHjAnIAeAAQAJAAAFgHQAEgFAAgJQAAgIgEgGQgGgEgIAAIgeAAgAFKBNIAAh/IgqAAIAAgnIB9AAIAAAnIgpAAIAAB/gAChBNIAAimIBpAAIAAAnIg+AAIAAAXIA5AAIAAAlIg5AAIAAAdIBAAAIAAAmgAidBNIAAgEIAag3Ig4hkIAAgHIAwAAIAgA+IABAAIAcg+IAvAAIAAAHIhPCfgAjuBNIgfg1IgBAAIgfA1IguAAIAAgGIA2hRIgwhIIAAgHIAtAAIAaAsIABAAIAbgsIAtAAIAAAHIgxBIIA3BRIAAAGgAphBNIAAh+Ig0AAIAAB+IgsAAIAAimICMAAIAACmgAJ7BGIgFgHQgCgEAAgFQAAgFACgEIAFgHQAGgGAKAAQAKAAAHAGQADADACAEQACAEAAAFQAAAFgCAEQgCAEgDADQgHAGgKAAQgKAAgGgGgAJ2AaQAAgHAAgGIADgKQAEgGAIgJIANgOQAGgJABgIQAAgHgFgDQgFgEgHAAQgGAAgFAEQgFAFAAAIIgkAAQAAgOAEgKQAEgKAIgHQAHgHAKgDQAKgDALgBQANAAALAEQAKADAHAIQAIAGADAKQAEAJAAALIgCAMIgDAKIgMAQIgMANQgFAJABAKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70.6,-9.6,141.3,19.3);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFF402").s().p("AGgBRQgHgCgHgFQgHgEgGgFIgLgMQgFgHgEgIQgDgJgCgJQgCgKAAgKQAAg5BWgdQALAAAVAGIAOAHQAHAEAGAFIALAMQAFAHAEAIQADAJACAJQACAKAAAJQAAA6hWAdQgWgCgKgEgAGxgpQgIADgGAFQgGAGgDAJQgEAJAAAJQAAAKAEAKQADAIAGAGQAGAFAIADQAHADAIAAQAIAAAHgDQAIgDAGgFQAGgGAEgIQADgKAAgKQAAgJgDgJQgEgJgGgGQgGgFgIgDQgHgDgIAAQgIAAgHADgAg3BUIgQgEIgOgHIgNgJQgHgGgEgHQgFgGgEgIQgEgIgCgKQgBgJAAgKQAAgJABgKQACgJAEgIQAEgIAFgHQAEgHAHgFIANgKQAHgEAHgCIAQgEIAQgCQANAAANAEQANAEAJAHQAOAMAEAIQAEAGADAHIAEAQIgpAAQgCgGgDgFQgEgFgEgDQgFgDgGgBQgFgCgHAAQgKAAgHAEQgIADgGAGQgFAHgDAIQgDAJAAAJQAAAIADAJQADAIAFAHQAGAGAHAEQAIAEAKAAQAHAAAGgCQAGgCAFgDQAEgDAEgFQADgGACgGIAoAAQgBAIgCAIQgDAIgEAGQgDAGgFAGIgKAJQgKAHgNAEQgMAEgOAAgADOBTIAAimIBKAAQAUAAAZAUQAHAJAEALQAEALAAAMQAAAMgEAJQgEALgHAJQgIAJgLAFQgGADgGABIgOABIgfAAIAAArgAD5ACIAeAAQAJAAAFgGQAEgHAAgJQABgKgFgHQgCgDgEgCQgDgCgFAAIgeAAgABgBTIAAh/IgpAAIAAgnIB8AAIAAAnIgpAAIAAB/gAjJBTIAAimIArAAIAACmgAlvBTIAAimIArAAIAAAyIAfAAQAKAAAQAGQALAEAIAJQAIAIAEAJQADAKAAALQAAAMgDAKQgEALgIAIQgIAIgLAFQgQAFgKAAgAlEAtIAfAAQAJAAAFgHQAEgFAAgJQAAgIgFgGQgFgGgIAAIgfAAgAoVBTIAAimIB4AAIAAAnIhNAAIAAAUIAfAAQAKAAAQAFQALAEAIAIQAHAHAEAIQAEAKAAALQAAAKgEAKQgEAKgHAHQgIAIgLAEQgQAFgKAAgAnqAtIAeAAQAJAAAFgFQAEgFAAgHQAAgGgEgFQgFgFgJAAIgeAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.5,-8.7,107,17.5);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFF402").s().p("ADDBUIglhBIgRABIAABAIgsAAIAAilIAsAAIAAA/IADAAQAIAAAGgBQAGgCAFgDQAHgEAEgKQAFgMAAgfIAsAAQAAAhgEAPQgDAMgGAJQgLAMgIAEIAtBKIAAAGgAAhBUIgJgVIhBAAIgKAVIgqAAIAAgFIBMiiIARAAIBLCiIAAAFgAAJAbIgRgrIgTArIAkAAgAiPBUIglhBIgRABIAABAIgsAAIAAilIAsAAIAAA/IADAAQAIAAAGgBQAGgCAEgDQAJgEADgKQAFgMAAgfIAsAAQAAAhgEAPQgDAMgHAJQgKAMgJAEIAuBKIAAAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.2,-8.5,48.5,17);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.baba_06();
	this.instance.setTransform(-84,-203.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-203.5,168,407);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.baba_03();
	this.instance.setTransform(-106,-43.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-106,-43.5,212,87);


(lib.Символ60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 5
	this.instance = new lib.Символ65();
	this.instance.setTransform(-174,103.9,0.737,0.737,-45,0,0,0,-0.1);

	this.instance_1 = new lib.Символ65();
	this.instance_1.setTransform(-174,56.2,0.737,0.737,-45,0,0,0,-0.1);

	this.instance_2 = new lib.Символ65();
	this.instance_2.setTransform(-174,8.5,0.737,0.737,-45,0,0,0,-0.1);

	this.instance_3 = new lib.Символ65();
	this.instance_3.setTransform(-174,-39.2,0.737,0.737,-45,0,0,0,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Символ 63
	this.instance_4 = new lib.Символ63();
	this.instance_4.setTransform(-85.5,59.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// Символ 62
	this.instance_5 = new lib.Символ62();
	this.instance_5.setTransform(-75.5,12.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

	// Символ 61
	this.instance_6 = new lib.Символ61();
	this.instance_6.setTransform(-85.5,-36,0.723,0.723);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1));

	// Слой 1
	this.instance_7 = new lib.Символ64();
	this.instance_7.setTransform(-97.8,108);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-184.6,-49.8,183.6,173.1);


(lib.Символ57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 12
	this.instance = new lib.Символ12();
	this.instance.setTransform(16.5,9.7,1,1,0,0,0,-70.7,9.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(16).to({regX:0,regY:0,x:91.4,y:0},0).wait(1).to({x:95.4},0).wait(1).to({x:98.8},0).wait(1).to({x:101.5},0).wait(1).to({x:103.7},0).wait(1).to({x:105.5},0).wait(1).to({x:107},0).wait(1).to({x:108.3},0).wait(1).to({x:109.3},0).wait(1).to({x:110.1},0).wait(1).to({x:110.8},0).wait(1).to({x:111.4},0).wait(1).to({x:112},0).wait(1).to({x:112.6},0).wait(1).to({regX:-70.7,regY:9.7,x:42.5,y:9.7},0).wait(1).to({regX:0,regY:0,x:108.9,y:0},0).wait(1).to({x:104.9},0).wait(1).to({x:101.5},0).wait(1).to({x:98.8},0).wait(1).to({x:96.6},0).wait(1).to({x:94.8},0).wait(1).to({x:93.3},0).wait(1).to({x:92},0).wait(1).to({x:91},0).wait(1).to({x:90.2},0).wait(1).to({x:89.5},0).wait(1).to({x:88.9},0).wait(1).to({x:88.3},0).wait(1).to({x:87.7},0).wait(1).to({regX:-70.7,regY:9.7,x:16.5,y:9.7},0).wait(1).to({regX:0,regY:0,scaleX:1.07,scaleY:1.07,x:92.2,y:-0.7},0).wait(1).to({scaleX:1.13,scaleY:1.13,x:96.6,y:-1.3},0).wait(1).to({scaleX:1.18,scaleY:1.18,x:100.1,y:-1.8},0).wait(1).to({scaleX:1.22,scaleY:1.22,x:102.8,y:-2.1},0).wait(1).to({scaleX:1.25,scaleY:1.25,x:104.8,y:-2.4},0).wait(1).to({scaleX:1.27,scaleY:1.27,x:106.1,y:-2.6},0).wait(1).to({scaleX:1.28,scaleY:1.28,x:107.2,y:-2.8},0).wait(1).to({scaleX:1.3,scaleY:1.3,x:108.2,y:-2.9},0).wait(1).to({regX:-70.7,regY:9.7,scaleX:1.31,scaleY:1.31,x:16.5,y:9.7},0).wait(1).to({regX:0,regY:0,scaleX:1.24,scaleY:1.24,x:104.3,y:-2.4},0).wait(1).to({scaleX:1.18,scaleY:1.18,x:99.9,y:-1.7},0).wait(1).to({scaleX:1.13,scaleY:1.13,x:96.4,y:-1.3},0).wait(1).to({scaleX:1.09,scaleY:1.09,x:93.7,y:-0.9},0).wait(1).to({scaleX:1.07,scaleY:1.07,x:91.7,y:-0.6},0).wait(1).to({scaleX:1.05,scaleY:1.05,x:90.4,y:-0.4},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:89.3,y:-0.3},0).wait(1).to({scaleX:1.02,scaleY:1.02,x:88.3,y:-0.2},0).wait(1).to({regX:-70.7,regY:9.7,scaleX:1,scaleY:1,x:16.5,y:9.7},0).wait(26));

	// Символ 11
	this.instance_1 = new lib.Символ11();
	this.instance_1.setTransform(-46.8,8.1,1,1,0,0,0,-0.1,8.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(16).to({regX:0,regY:0,scaleX:1.08,scaleY:1.08,x:-46.7,y:-1.3},0).wait(1).to({scaleX:1.16,scaleY:1.16,y:-2},0).wait(1).to({scaleX:1.23,scaleY:1.23,y:-2.5},0).wait(1).to({scaleX:1.28,scaleY:1.28,y:-3},0).wait(1).to({scaleX:1.32,scaleY:1.32,y:-3.4},0).wait(1).to({scaleX:1.36,scaleY:1.36,y:-3.7},0).wait(1).to({scaleX:1.38,scaleY:1.38,y:-3.9},0).wait(1).to({scaleX:1.41,scaleY:1.41,y:-4.1},0).wait(1).to({scaleX:1.43,scaleY:1.43,y:-4.3},0).wait(1).to({scaleX:1.44,scaleY:1.44,y:-4.4},0).wait(1).to({scaleX:1.46,scaleY:1.46,y:-4.6},0).wait(1).to({scaleX:1.47,scaleY:1.47,y:-4.7},0).wait(1).to({scaleX:1.48,scaleY:1.48,y:-4.8},0).wait(1).to({scaleX:1.49,scaleY:1.49,y:-4.9},0).wait(1).to({regX:-0.1,regY:8.7,scaleX:1.5,scaleY:1.5,x:-46.8,y:8.1},0).wait(1).to({regX:0,regY:0,scaleX:1.42,scaleY:1.42,x:-46.7,y:-4.2},0).wait(1).to({scaleX:1.34,scaleY:1.34,y:-3.6},0).wait(1).to({scaleX:1.28,scaleY:1.28,y:-3},0).wait(1).to({scaleX:1.23,scaleY:1.23,y:-2.5},0).wait(1).to({scaleX:1.18,scaleY:1.18,y:-2.2},0).wait(1).to({scaleX:1.15,scaleY:1.15,y:-1.9},0).wait(1).to({scaleX:1.12,scaleY:1.12,y:-1.6},0).wait(1).to({scaleX:1.1,scaleY:1.1,y:-1.4},0).wait(1).to({scaleX:1.08,scaleY:1.08,y:-1.3},0).wait(1).to({scaleX:1.06,scaleY:1.06,y:-1.1},0).wait(1).to({scaleX:1.05,scaleY:1.05,y:-1},0).wait(1).to({scaleX:1.03,scaleY:1.03,y:-0.9},0).wait(1).to({scaleX:1.02,scaleY:1.02,y:-0.8},0).wait(1).to({scaleX:1.01,scaleY:1.01,y:-0.7},0).wait(1).to({regX:-0.1,regY:8.7,scaleX:1,scaleY:1,x:-46.8,y:8.1},0).wait(44));

	// Символ 10
	this.instance_2 = new lib.Символ10();
	this.instance_2.setTransform(-109.3,7.8,1,1,0,0,0,24.2,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({scaleX:1.55,scaleY:1.55},7).to({scaleX:1,scaleY:1},8).wait(1).to({regX:0,regY:0,x:-137.8,y:-0.7},0).wait(1).to({x:-141.8},0).wait(1).to({x:-145.2},0).wait(1).to({x:-147.9},0).wait(1).to({x:-150.1},0).wait(1).to({x:-151.9},0).wait(1).to({x:-153.4},0).wait(1).to({x:-154.7},0).wait(1).to({x:-155.7},0).wait(1).to({x:-156.5},0).wait(1).to({x:-157.2},0).wait(1).to({x:-157.8},0).wait(1).to({x:-158.4},0).wait(1).to({x:-159},0).wait(1).to({regX:24.2,regY:8.5,x:-135.3,y:7.8},0).wait(1).to({regX:0,regY:0,x:-155.3,y:-0.7},0).wait(1).to({x:-151.3},0).wait(1).to({x:-147.9},0).wait(1).to({x:-145.2},0).wait(1).to({x:-143},0).wait(1).to({x:-141.2},0).wait(1).to({x:-139.7},0).wait(1).to({x:-138.4},0).wait(1).to({x:-137.4},0).wait(1).to({x:-136.6},0).wait(1).to({x:-135.9},0).wait(1).to({x:-135.3},0).wait(1).to({x:-134.7},0).wait(1).to({x:-134.1},0).wait(1).to({regX:24.2,regY:8.5,x:-109.3,y:7.8},0).wait(44));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-157.8,-9.6,315.6,19.3);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 49
	this.instance = new lib.Символ49();
	this.instance.setTransform(-30,-13.1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-8.2,alpha:1},9).to({x:-21.2},3).wait(144).to({y:-22.8},0).wait(1).to({y:-28.1},0).wait(1).to({y:-31},0).wait(1).to({y:-32.6},0).wait(1).to({y:-15.1,alpha:0.735},0).wait(1).to({y:-2.5,alpha:0.545},0).wait(1).to({y:7.2,alpha:0.398},0).wait(1).to({y:15,alpha:0.282},0).wait(1).to({y:21.2,alpha:0.188},0).wait(1).to({y:25.7,alpha:0.12},0).wait(1).to({y:28.9,alpha:0.071},0).wait(1).to({y:31.4,alpha:0.033},0).wait(1).to({y:33.7,alpha:0},0).wait(13));

	// Символ 50
	this.instance_1 = new lib.Символ50();
	this.instance_1.setTransform(-29.7,15.5);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:-7.9,alpha:1},9).to({x:-20.9},3).wait(134).to({y:5.8},0).wait(1).to({y:0.5},0).wait(1).to({y:-2.4},0).wait(1).to({y:-4},0).wait(1).to({y:13.5,alpha:0.735},0).wait(1).to({y:26.1,alpha:0.545},0).wait(1).to({y:35.8,alpha:0.398},0).wait(1).to({y:43.6,alpha:0.282},0).wait(1).to({y:49.8,alpha:0.188},0).wait(1).to({y:54.3,alpha:0.12},0).wait(1).to({y:57.5,alpha:0.071},0).wait(1).to({y:60,alpha:0.033},0).wait(1).to({y:62.3,alpha:0},0).wait(23));

	// Символ 51
	this.instance_2 = new lib.Символ51();
	this.instance_2.setTransform(-174.9,-12.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(24).to({_off:false},0).to({x:-299.8,alpha:1},10).to({x:-286.8},3).wait(114).to({y:-22.3},0).wait(1).to({y:-27.6},0).wait(1).to({y:-30.5},0).wait(1).to({y:-32.1},0).wait(1).to({y:-14.6,alpha:0.735},0).wait(1).to({y:-1.9,alpha:0.545},0).wait(1).to({y:7.8,alpha:0.398},0).wait(1).to({y:15.5,alpha:0.282},0).wait(1).to({y:21.8,alpha:0.188},0).wait(1).to({y:26.3,alpha:0.12},0).wait(1).to({y:29.5,alpha:0.071},0).wait(1).to({y:32,alpha:0.033},0).wait(1).to({y:34.2,alpha:0},0).wait(18));

	// Символ 52
	this.instance_3 = new lib.Символ52();
	this.instance_3.setTransform(-174.9,13.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(24).to({_off:false},0).to({x:-299.8,alpha:1},10).to({x:-286.8},3).wait(117).to({y:3.7},0).wait(1).to({y:-1.6},0).wait(1).to({y:-4.5},0).wait(1).to({y:-6.1},0).wait(1).to({y:11.4,alpha:0.735},0).wait(1).to({y:24.1,alpha:0.545},0).wait(1).to({y:33.8,alpha:0.398},0).wait(1).to({y:41.5,alpha:0.282},0).wait(1).to({y:47.8,alpha:0.188},0).wait(1).to({y:52.3,alpha:0.12},0).wait(1).to({y:55.5,alpha:0.071},0).wait(1).to({y:58,alpha:0.033},0).wait(1).to({y:60.2,alpha:0},0).wait(15));

	// Символ 54
	this.instance_4 = new lib.Символ54();
	this.instance_4.setTransform(-211.4,112);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(48).to({_off:false},0).to({x:-370.9,alpha:1},9).to({x:-351.4},3).wait(89).to({y:102.3},0).wait(1).to({y:97},0).wait(1).to({y:94.1},0).wait(1).to({y:92.5},0).wait(1).to({y:110,alpha:0.735},0).wait(1).to({y:122.6,alpha:0.545},0).wait(1).to({y:132.3,alpha:0.398},0).wait(1).to({y:140.1,alpha:0.282},0).wait(1).to({y:146.3,alpha:0.188},0).wait(1).to({y:150.8,alpha:0.12},0).wait(1).to({y:154,alpha:0.071},0).wait(1).to({y:156.5,alpha:0.033},0).wait(1).to({y:158.8,alpha:0},0).wait(20));

	// Символ 53
	this.instance_5 = new lib.Символ53();
	this.instance_5.setTransform(-210.7,83.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(48).to({_off:false},0).to({x:-370.2,alpha:1},9).to({x:-350.7},3).wait(96).to({y:73.8},0).wait(1).to({y:68.5},0).wait(1).to({y:65.6},0).wait(1).to({y:64},0).wait(1).to({y:81.5,alpha:0.735},0).wait(1).to({y:94.2,alpha:0.545},0).wait(1).to({y:103.9,alpha:0.398},0).wait(1).to({y:111.6,alpha:0.282},0).wait(1).to({y:117.9,alpha:0.188},0).wait(1).to({y:122.4,alpha:0.12},0).wait(1).to({y:125.6,alpha:0.071},0).wait(1).to({y:128.1,alpha:0.033},0).wait(1).to({y:130.3,alpha:0},0).wait(13));

	// Символ 56
	this.instance_6 = new lib.Символ56();
	this.instance_6.setTransform(-131.8,112);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(72).to({_off:false},0).to({x:55.6,alpha:1},7).to({x:42.6},3).wait(73).to({y:102.3},0).wait(1).to({y:97},0).wait(1).to({y:94.1},0).wait(1).to({y:92.5},0).wait(1).to({y:110,alpha:0.735},0).wait(1).to({y:122.6,alpha:0.545},0).wait(1).to({y:132.3,alpha:0.398},0).wait(1).to({y:140.1,alpha:0.282},0).wait(1).to({y:146.3,alpha:0.188},0).wait(1).to({y:150.8,alpha:0.12},0).wait(1).to({y:154,alpha:0.071},0).wait(1).to({y:156.5,alpha:0.033},0).wait(1).to({y:158.8,alpha:0},0).wait(14));

	// Символ 55
	this.instance_7 = new lib.Символ55();
	this.instance_7.setTransform(-131.2,86);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(72).to({_off:false},0).to({x:56.2,alpha:1},7).to({x:43.2},3).wait(69).to({y:76.3},0).wait(1).to({y:71},0).wait(1).to({y:68.1},0).wait(1).to({y:66.5},0).wait(1).to({y:84,alpha:0.735},0).wait(1).to({y:96.7,alpha:0.545},0).wait(1).to({y:106.4,alpha:0.398},0).wait(1).to({y:114.1,alpha:0.282},0).wait(1).to({y:120.4,alpha:0.188},0).wait(1).to({y:124.9,alpha:0.12},0).wait(1).to({y:128.1,alpha:0.071},0).wait(1).to({y:130.6,alpha:0.033},0).wait(1).to({y:132.8,alpha:0},0).wait(18));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.6,-24.2,101.9,48.4);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ46();
	this.instance.setTransform(0.2,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({guide:{path:[0.3,0,0.9,-2.7,2.9,-4.5,5.7,-7.3,9.4,-7.3,12.3,-7.3,14.6,-5.8]}},7).to({guide:{path:[14.5,-5.8,15.3,-5.3,16.1,-4.6,18.9,-1.8,18.9,1.9,18.9,4.8,17.3,7.1]}},8).to({guide:{path:[17.3,7.1,16.7,7.9,16,8.6,13.3,11.4,9.4,11.4,7.6,11.4,5.9,10.7]}},8).to({guide:{path:[5.7,10.7,4,10,2.7,8.6,0.1,5.9,0.1,2.2,0.1,1.2,0.3,0.2]}},6).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.2,-9.2,14.8,18.5);


(lib.Символ44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ47();
	this.instance.setTransform(94.5,-6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ45();
	this.instance_1.setTransform(37.5,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8.1,-15.2,110.2,19.7);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ay+E7IAAp1MAl9AAAIAAJ1g");

	// Слой 2
	this.instance = new lib.Символ41();
	this.instance.setTransform(-184.3,-29.6,0.441,1,30);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:280.3},29).wait(31));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-121.5,-31.6,55.5,63.2);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ36();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.4,-8.7,124.9,17.4);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ39();
	this.instance.alpha = 0.43;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ38();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-302.7,-189,424.3,318.7);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 31
	this.instance = new lib.Символ31();
	this.instance.setTransform(22.4,37.1,1.711,1.711);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(66).to({_off:false},0).wait(1).to({regX:3.2,regY:1,x:61.3,y:38.8,alpha:0.229},0).wait(1).to({x:87.7,alpha:0.41},0).wait(1).to({x:107.9,alpha:0.547},0).wait(1).to({x:124.6,alpha:0.662},0).wait(1).to({x:140.1,alpha:0.769},0).wait(1).to({x:152.6,alpha:0.854},0).wait(1).to({x:161.6,alpha:0.916},0).wait(1).to({x:168.4,alpha:0.962},0).wait(1).to({regX:0,regY:0,x:168.5,y:37.1,alpha:1},0).wait(1).to({regX:3.2,regY:1,x:163,y:38.8},0).wait(1).to({x:156.9},0).wait(1).to({regX:0,regY:0,x:148.5,y:37.1},0).wait(30).to({x:168.5},3).to({x:22.4,alpha:0},9).wait(1));

	// Символ 30
	this.instance_1 = new lib.Символ30();
	this.instance_1.setTransform(24.2,-7.3,1.711,1.711);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(63).to({_off:false},0).wait(1).to({regX:-15.5,x:31.1,alpha:0.229},0).wait(1).to({x:57.5,alpha:0.41},0).wait(1).to({x:77.7,alpha:0.547},0).wait(1).to({x:94.4,alpha:0.662},0).wait(1).to({x:109.9,alpha:0.769},0).wait(1).to({x:122.4,alpha:0.854},0).wait(1).to({x:131.4,alpha:0.916},0).wait(1).to({x:138.2,alpha:0.962},0).wait(1).to({regX:0,x:170.3,alpha:1},0).wait(1).to({regX:-15.5,x:132.8},0).wait(1).to({x:126.7},0).wait(1).to({regX:0,x:150.3},0).wait(31).to({x:170.3},3).to({x:24.2,alpha:0},9).to({_off:true},1).wait(2));

	// Символ 29
	this.instance_2 = new lib.Символ29();
	this.instance_2.setTransform(25.3,-51.8,1.711,1.711);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(60).to({_off:false},0).wait(1).to({x:58.6,alpha:0.229},0).wait(1).to({x:85.1,alpha:0.41},0).wait(1).to({x:105.2,alpha:0.547},0).wait(1).to({x:122,alpha:0.662},0).wait(1).to({x:137.5,alpha:0.769},0).wait(1).to({x:149.9,alpha:0.854},0).wait(1).to({x:159,alpha:0.916},0).wait(1).to({x:165.8,alpha:0.962},0).wait(1).to({x:171.3,alpha:1},0).wait(1).to({x:160.4},0).wait(1).to({x:154.2},0).wait(1).to({x:151.3},0).wait(32).to({x:171.3},3).to({x:25.3,alpha:0},9).to({_off:true},1).wait(4));

	// Символ 24
	this.instance_3 = new lib.Символ27();
	this.instance_3.setTransform(0,43.5,1.632,1.632);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(6).to({_off:false},0).to({x:177.5,alpha:1},9).to({x:167.3},3).wait(24).to({x:177.5},3).to({x:0,alpha:0},9).to({_off:true},1).wait(66));

	// Символ 23
	this.instance_4 = new lib.Символ26();
	this.instance_4.setTransform(1.4,-0.3,1.632,1.632);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(3).to({_off:false},0).to({x:74.9,alpha:1},9).to({x:54.4},3).wait(24).to({x:74.9},3).to({x:1.4,alpha:0},9).to({_off:true},1).wait(69));

	// Символ 22
	this.instance_5 = new lib.Символ25();
	this.instance_5.setTransform(-1,-45.5,1.632,1.632);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({x:133.5,alpha:1},9).to({x:123.5},3).wait(25).to({x:133.5},3).to({x:-1,alpha:0},9).to({_off:true},1).wait(71));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.2,-66.5,213.8,64.1);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AllAsIADipILIArIgDCpg");
	var mask_graphics_1 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_2 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_3 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_4 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_5 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_6 = new cjs.Graphics().p("AllA+IADioILIArIgDCog");
	var mask_graphics_7 = new cjs.Graphics().p("AllAyIADioILIArIgDCog");
	var mask_graphics_8 = new cjs.Graphics().p("AllAsIADipILIArIgDCpg");
	var mask_graphics_9 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_10 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_11 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_12 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_13 = new cjs.Graphics().p("AllA/IADioILIArIgDCog");
	var mask_graphics_14 = new cjs.Graphics().p("AllA+IADioILIArIgDCog");
	var mask_graphics_15 = new cjs.Graphics().p("AllAyIADioILIArIgDCog");
	var mask_graphics_16 = new cjs.Graphics().p("AllAsIADipILIArIgDCpg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:1.8,y:-12.6}).wait(1).to({graphics:mask_graphics_1,x:1.8,y:-8.1}).wait(1).to({graphics:mask_graphics_2,x:1.8,y:-4.2}).wait(1).to({graphics:mask_graphics_3,x:1.8,y:-1.9}).wait(1).to({graphics:mask_graphics_4,x:1.8,y:-0.6}).wait(1).to({graphics:mask_graphics_5,x:1.8,y:-7.1}).wait(1).to({graphics:mask_graphics_6,x:1.8,y:-10.8}).wait(1).to({graphics:mask_graphics_7,x:1.8,y:-12}).wait(1).to({graphics:mask_graphics_8,x:1.8,y:-12.6}).wait(1).to({graphics:mask_graphics_9,x:1.8,y:-8.1}).wait(1).to({graphics:mask_graphics_10,x:1.8,y:-4.2}).wait(1).to({graphics:mask_graphics_11,x:1.8,y:-1.9}).wait(1).to({graphics:mask_graphics_12,x:1.8,y:-0.6}).wait(1).to({graphics:mask_graphics_13,x:1.8,y:-7.1}).wait(1).to({graphics:mask_graphics_14,x:1.8,y:-10.8}).wait(1).to({graphics:mask_graphics_15,x:1.8,y:-12}).wait(1).to({graphics:mask_graphics_16,x:1.8,y:-12.6}).wait(74));

	// Слой 1
	this.instance = new lib.Символ18();

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(90));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21.3,-3.9,42.7,0);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 12
	this.instance = new lib.Символ57();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-157.8,-9.6,315.6,19.3);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ58();
	this.instance.setTransform(-1.4,0.6);
	this.instance.alpha = 0.148;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(165));

	// Слой 2
	this.instance_1 = new lib.Символ16();
	this.instance_1.setTransform(-2,-1,1,1,180);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},74).to({alpha:1},90).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ16();

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(165));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-308.5,-156.5,615,312);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ17();
	this.instance.setTransform(11.8,-74.7);
	this.instance.alpha = 0.609;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.baba_09();
	this.instance_1.setTransform(-150,-135);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-135,300,270);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ3();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({y:0.6},0).wait(1).to({y:1.1},0).wait(1).to({y:1.7},0).wait(1).to({y:2.2},0).wait(1).to({y:2.7},0).wait(1).to({y:3.2},0).wait(1).to({y:3.7},0).wait(1).to({y:4.1},0).wait(1).to({y:4.6},0).wait(1).to({y:5},0).wait(1).to({y:5.3},0).wait(1).to({y:5.7},0).wait(1).to({y:6},0).wait(1).to({y:6.3},0).wait(1).to({y:6.6},0).wait(1).to({y:6.8},0).wait(1).to({y:7.1},0).wait(1).to({y:7.3},0).wait(1).to({y:7.6},0).wait(1).to({y:7.8},0).wait(1).to({y:8},0).wait(1).to({y:8.2},0).wait(1).to({y:8.4},0).wait(1).to({y:8.6},0).wait(1).to({y:8.8},0).wait(1).to({y:8.9},0).wait(1).to({y:9.1},0).wait(1).to({y:9.2},0).wait(1).to({y:9.3},0).wait(1).to({y:9.4},0).wait(1).to({y:9.5},0).wait(1).to({y:9.6},0).wait(1).to({y:9.7},0).wait(1).to({y:9.8},0).wait(1).to({y:9.9},0).wait(1).to({y:10},0).wait(1).to({y:10.1},0).wait(2).to({y:10.2},0).wait(1).to({y:10.3},0).wait(1).to({y:10.4},0).wait(1).to({y:10.5},0).wait(2).to({y:10.6},0).wait(1).to({y:10.7},0).wait(1).to({y:10.8},0).wait(2).to({y:10.9},0).wait(1).to({y:11},0).wait(1).to({y:10.4},0).wait(1).to({y:9.9},0).wait(1).to({y:9.4},0).wait(1).to({y:8.9},0).wait(1).to({y:8.4},0).wait(1).to({y:7.9},0).wait(1).to({y:7.4},0).wait(1).to({y:7},0).wait(1).to({y:6.6},0).wait(1).to({y:6.2},0).wait(1).to({y:5.8},0).wait(1).to({y:5.5},0).wait(1).to({y:5.2},0).wait(1).to({y:4.9},0).wait(1).to({y:4.6},0).wait(1).to({y:4.3},0).wait(1).to({y:4.1},0).wait(1).to({y:3.8},0).wait(1).to({y:3.6},0).wait(1).to({y:3.4},0).wait(1).to({y:3.2},0).wait(1).to({y:3},0).wait(1).to({y:2.8},0).wait(1).to({y:2.6},0).wait(1).to({y:2.4},0).wait(1).to({y:2.2},0).wait(1).to({y:2.1},0).wait(1).to({y:1.9},0).wait(1).to({y:1.8},0).wait(1).to({y:1.7},0).wait(1).to({y:1.6},0).wait(1).to({y:1.5},0).wait(1).to({y:1.4},0).wait(1).to({y:1.3},0).wait(1).to({y:1.2},0).wait(1).to({y:1.1},0).wait(1).to({y:1},0).wait(2).to({y:0.9},0).wait(1).to({y:0.8},0).wait(1).to({y:0.7},0).wait(2).to({y:0.6},0).wait(1).to({y:0.5},0).wait(1).to({y:0.4},0).wait(2).to({y:0.3},0).wait(1).to({y:0.2},0).wait(2).to({y:0.1},0).wait(1).to({y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-203.5,168,407);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.setTransform(16.4,-49.4,1.024,1.024);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.2,-93.9,217.1,89.1);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ43();
	this.instance.setTransform(0,-2.2);
	this.instance.alpha = 0.539;
	this.instance.compositeOperation = "lighter";
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ35();
	this.instance_1.setTransform(-0.1,-3.5,0.877,0.877);

	this.instance_2 = new lib.Символ34();
	this.instance_2.setTransform(0,-2,0.877,0.877);

	this.instance_3 = new lib.Символ33();
	this.instance_3.setTransform(0,5.6,0.877,0.877);
	this.instance_3.filters = [new cjs.BlurFilter(7, 7, 1)];
	this.instance_3.cache(-123,-29,247,59);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3,p:{scaleX:0.877,scaleY:0.877,y:5.6}},{t:this.instance_2,p:{scaleX:0.877,scaleY:0.877,y:-2}},{t:this.instance_1,p:{scaleX:0.877,scaleY:0.877,y:-3.5}}]}).to({state:[{t:this.instance_3,p:{scaleX:0.969,scaleY:0.969,y:6.2}},{t:this.instance_2,p:{scaleX:0.969,scaleY:0.969,y:-2.2}},{t:this.instance_1,p:{scaleX:0.969,scaleY:0.969,y:-3.9}}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-265.3,-167.6,378.8,279.3);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ42();
	this.instance.setTransform(-3.9,-29.8,1,1,0,0,0,-79.4,-28);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-189.8,-169.5,390.6,279.3);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ5();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({y:0.6},0).wait(1).to({y:1.1},0).wait(1).to({y:1.7},0).wait(1).to({y:2.2},0).wait(1).to({y:2.7},0).wait(1).to({y:3.2},0).wait(1).to({y:3.6},0).wait(1).to({y:4.1},0).wait(1).to({y:4.5},0).wait(1).to({y:4.9},0).wait(1).to({y:5.3},0).wait(1).to({y:5.7},0).wait(1).to({y:6},0).wait(1).to({y:6.4},0).wait(1).to({y:6.7},0).wait(1).to({y:7},0).wait(1).to({y:7.2},0).wait(1).to({y:7.5},0).wait(1).to({y:7.8},0).wait(1).to({y:8},0).wait(1).to({y:8.3},0).wait(1).to({y:8.5},0).wait(1).to({y:8.7},0).wait(1).to({y:8.9},0).wait(1).to({y:9.1},0).wait(1).to({y:9.3},0).wait(1).to({y:9.5},0).wait(1).to({y:9.7},0).wait(1).to({y:9.9},0).wait(1).to({y:10},0).wait(1).to({y:10.2},0).wait(1).to({y:10.3},0).wait(1).to({y:10.5},0).wait(1).to({y:10.6},0).wait(1).to({y:10.7},0).wait(1).to({y:10.9},0).wait(1).to({y:11},0).wait(1).to({y:11.1},0).wait(1).to({y:11.2},0).wait(1).to({y:11.4},0).wait(1).to({y:11.5},0).wait(1).to({y:11.6},0).wait(1).to({y:11.7},0).wait(1).to({y:11.8},0).wait(1).to({y:11.9},0).wait(1).to({y:12},0).wait(1).to({y:12.1},0).wait(1).to({y:12.2},0).wait(1).to({y:12.3},0).wait(1).to({y:11.7},0).wait(1).to({y:11.2},0).wait(1).to({y:10.7},0).wait(1).to({y:10.2},0).wait(1).to({y:9.7},0).wait(1).to({y:9.2},0).wait(1).to({y:8.7},0).wait(1).to({y:8.3},0).wait(1).to({y:7.9},0).wait(1).to({y:7.5},0).wait(1).to({y:7.1},0).wait(1).to({y:6.7},0).wait(1).to({y:6.4},0).wait(1).to({y:6},0).wait(1).to({y:5.7},0).wait(1).to({y:5.4},0).wait(1).to({y:5.1},0).wait(1).to({y:4.9},0).wait(1).to({y:4.6},0).wait(1).to({y:4.4},0).wait(1).to({y:4.1},0).wait(1).to({y:3.9},0).wait(1).to({y:3.7},0).wait(1).to({y:3.5},0).wait(1).to({y:3.3},0).wait(1).to({y:3.1},0).wait(1).to({y:2.9},0).wait(1).to({y:2.7},0).wait(1).to({y:2.5},0).wait(1).to({y:2.4},0).wait(1).to({y:2.2},0).wait(1).to({y:2.1},0).wait(1).to({y:1.9},0).wait(1).to({y:1.8},0).wait(1).to({y:1.7},0).wait(1).to({y:1.5},0).wait(1).to({y:1.4},0).wait(1).to({y:1.3},0).wait(1).to({y:1.2},0).wait(1).to({y:1},0).wait(1).to({y:0.9},0).wait(1).to({y:0.8},0).wait(1).to({y:0.7},0).wait(1).to({y:0.6},0).wait(1).to({y:0.5},0).wait(1).to({y:0.4},0).wait(1).to({y:0.3},0).wait(1).to({y:0.2},0).wait(1).to({y:0.1},0).wait(1).to({y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-135,300,270);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_15 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(15).call(this.frame_15).wait(15));

	// Символ 22
	this.instance = new lib.Символ44();
	this.instance.setTransform(384.2,143.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:130.6},3).to({y:230.6},7).wait(9).to({y:130.6},7).to({y:143.1},3).wait(1));

	// Символ 23
	this.instance_1 = new lib.Символ32();
	this.instance_1.setTransform(209.6,220.9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(6).to({_off:false},0).to({y:103.1},5).to({y:116.1},3).wait(1).to({y:103.1},3).to({y:173.8},3).to({y:220.9},2).to({_off:true},1).wait(6));

	// Слой 1
	this.instance_2 = new lib.Символ20();
	this.instance_2.setTransform(-47,-116.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:-17},2).to({x:-191},4).wait(17).to({x:-17},4).to({x:-47},2).wait(1));

	// Слой 5
	this.instance_3 = new lib.Символ9();
	this.instance_3.setTransform(207,-101.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:-235.8},6).wait(17).to({y:-101.7},6).wait(1));

	// Символ 6
	this.instance_4 = new lib.Символ6();
	this.instance_4.setTransform(201,165.8,0.893,0.893,0,0,0,5,128.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:181},4).to({x:511.5},5).to({x:709.8},3).wait(5).to({x:181},8).to({x:201},4).wait(1));

	// Символ 4
	this.instance_5 = new lib.Символ4();
	this.instance_5.setTransform(-266.9,64.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({x:6.2},4).to({x:-3.8},2).wait(17).to({x:36.2},0).to({x:46.2},2).to({x:-266.9},4).wait(1));

	// Символ 2
	this.instance_6 = new lib.Символ2();
	this.instance_6.setTransform(-20.9,-55.2);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(5).to({_off:false},0).wait(1).to({regX:16.3,regY:-49.4,x:38.7,y:-104.6,alpha:0.227},0).wait(1).to({x:77.7,alpha:0.431},0).wait(1).to({x:108.7,alpha:0.593},0).wait(1).to({x:131.5,alpha:0.712},0).wait(1).to({x:148.3,alpha:0.8},0).wait(1).to({x:161.2,alpha:0.868},0).wait(1).to({x:171.3,alpha:0.921},0).wait(1).to({x:179.5,alpha:0.964},0).wait(1).to({regX:0,regY:0,x:170.2,y:-55.2,alpha:1},0).wait(1).to({x:-20.9,alpha:0},9).to({_off:true},1).wait(5));

	// Слой 12
	this.instance_7 = new lib.Символ60();
	this.instance_7.setTransform(710.4,-68.8);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(9).to({_off:false},0).to({x:499.4,y:-67.2},5,cjs.Ease.get(1)).wait(1).to({x:710.4,y:-68.8},5).to({_off:true},1).wait(9));

	// Символ 24
	this.instance_8 = new lib.Символ28();
	this.instance_8.setTransform(20.7,12.4);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(9).to({_off:false},0).to({alpha:1},5).wait(1).to({alpha:0},5).to({_off:true},1).wait(9));

	// Слой 11
	this.instance_9 = new lib.Символ48();
	this.instance_9.setTransform(362.5,-15.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:0},6).wait(17).to({alpha:1},6).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-350.9,-138.7,837.2,407);


// stage content:



(lib._600x300 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		var _this = this;
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;	
		
		  function fl_MouseOverHandler_5()
		{
		    _this.main.gotoAndPlay(1);
		}
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;	
		  function fl_MouseOutHandler_2()
		{
		    _this.main.gotoAndPlay(16);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// baba_09.png
	this.main = new lib.Символ7();
	this.main.setTransform(92,138.7);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

	// Слой 5
	this.instance = new lib.Символ8();
	this.instance.setTransform(301.5,149.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(41.1,143,867,414.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;