(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 950,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bg.jpg", id:"bg"},
		{src:"images/btnw.png", id:"btnw"},
		{src:"images/check.png", id:"check"},
		{src:"images/logo.png", id:"logo"}
	]
};



// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1151,767);


(lib.btnw = function() {
	this.initialize(img.btnw);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,180,62);


(lib.check = function() {
	this.initialize(img.check);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,43,31);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,221,70);


(lib.Символ43 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEB3B").s().p("AB6A8QgFgDgEgDQgDgEgCgGQgDgFAAgGQAAgHADgGQACgFADgEQAEgEAFgDQAGgCAGAAQAHAAAFACQAFADAEAEQAEAEACAFQACAGAAAHQAAAGgCAFQgCAGgEAEQgEADgFADQgFACgHAAQgGAAgGgCgAB/ANIgGAFIgEAGIgBAJIABAHIAEAHIAGAEQADABAEABQAEgBADgBQAEgBACgDIAEgHIACgHQAAgFgCgEIgEgGQgCgDgEgCQgDgBgEgBQgEABgDABgAgdA9IgJgEQgIgDgGgHIAIgLQAFAGAFADQAHADAIAAQAJAAAHgEQAEgDAEgIQAFgGABgJQACgIAAgJIAAgCQgHAGgGAEIgIAEIgLACQgIAAgHgDQgHgCgGgEQgFgGgDgFQgDgHAAgKQAAgHACgHQAEgHAFgGQAGgFAHgEQAIgCAKgBQAGABAFABQAFABADADIAIAFIAHAIQAGAMACAIQACALAAALQAAAMgCALQgGAOgDAGIgHAIQgEADgFACQgCADgGABQgFABgHABIgKgBgAgcgtQgFACgDAEQgDAEgCAEIgCAJQAAAGACAGQACAFAEADQADACAGAAQAFACAGAAIAJgBIAGgCQAEgCADgDIAFgIIgBgLQgCgGgEgFQgEgFgDgDQgGgDgHAAQgHAAgGACgAiIA8QgIgDgFgEQgGgEgEgGQgDgHAAgHQAAgGACgFQACgFAEgEIAJgHIAMgCIgKgFQgGgCgDgDQgEgEgCgEQgCgGAAgFQAAgIADgGQAEgGAGgEQAGgEAHgCQAHgCAIAAQAHAAAIACQAHACAGAEQAGAEADAGQAEAGAAAIQAAAFgCAGQgCAEgEAEQgEADgFACIgJAFIAKACQAFADAEAEQAFAEACAFQACAFAAAGQAAAHgDAHQgEAFgGAFQgFAEgJADQgHACgJAAQgJAAgIgCgAiIAKQgFAEgDAEQgDAEAAAGQAAAEACAEQACAEAEADIAJAEIALABQAFAAAFgBIAJgEQAFgDABgEQACgEAAgEQAAgGgDgEQgDgEgFgEQgEgDgFgBIgHgCQgLADgGADgAiCgtQgEAAgEADQgEADgBAEQgCADAAAFQAAAFADAEQACADAFADQAGAEAKACQAJgCAGgEQAFgDADgDQADgEAAgFQAAgFgCgDIgGgHQgDgDgFAAIgKgCQgGAAgFACgAA8A8IBNh3IAJAAIhMB3gAA7gEQgEgCgFgDQgDgEgCgGQgCgFgBgHQABgGACgGIAFgJQAFgEAEgCQAGgCAHgBQAGABAFACQAGACADAEQAFAFACAEQACAGAAAGQAAAHgCAFQgCAGgFAEQgDADgGACQgFADgGAAQgHAAgGgDgABAgyIgGAFIgDAGIgBAIIABAIIADAHIAGAEQAEACAEAAQAEAAADgCIAFgEIAFgHIABgIIgBgIIgFgGIgFgFQgDgBgEAAQgEAAgEABg");
	this.shape.setTransform(16.4,6.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,32.7,12.4);


(lib.Символ42 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKvBMIADgMIAHABQAFAAADgCQADgCACgFIAGgNIglhWIAPAAIAdBFIAdhFIAPAAIgsBnIgEAIQgDADgDACQgHAEgJAAIgKgBgAq6BLIAAh2IAOAAIAAANQAFgHAIgEIAIgDIAJgBQAIAAAHADQAHADAGAGQAEAGADAJQADAIAAAKQAAAJgDAIQgDAJgEAGQgGAGgHADQgHADgIAAQgKAAgHgEQgIgEgFgHIAAAugAqhgdQgIAEgDAGIAAAlQADAGAIAEQAHAEAIAAQAGAAAGgDQAFgCAEgEQADgFACgGQACgGAAgGQAAgHgCgGQgCgGgDgFQgEgEgFgCQgGgDgGAAQgIAAgHAEgAFxBAIAAgWIhDAAIAAAWIgMAAIAAghIAFgDQACgBACgDIAEgKIAIg5IA9AAIAABJIAKAAIAAAigAE/AAQgCALgCAIQgEAHgEAEIA0AAIAAg9IgjAAgAMMApQgCgDAAgEQAAgEACgDQAEgDADAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAQgDAAgEgDgAHrAhQADAAADgCQACgCACgEQADgFADgUIAGgrIA8AAIAABVIgNAAIAAhJIgjAAIgEAfQgBALgDAJQgDAJgEAFQgDAGgFACQgFACgGAAgAGmApQgJgEgGgFQgFgHgEgIQgDgIAAgJQAAgJADgJQAEgIAFgGQAGgGAHgEQAIgDAKAAQAKAAAHADQAIAEAGAGQAFAGADAJQACAIABAJIAAADIhHAAQABAGACAGQACAFAEAEQAEAEAGADQAFACAIAAQAHAAAHgDQAHgDAGgFIAGAJQgHAHgIADQgJADgLAAQgKAAgHgDgAHSgFIgCgKIgEgKQgFgEgEgCQgHgDgHAAQgGAAgFACQgFADgEAEQgDAFgDAFIgCAKIA5AAIAAAAgADnApQgIgEgFgGQgHgGgCgJQgDgIAAgIQAAgJADgJQACgIAHgGQAFgGAIgEQAJgDAJAAIALABIAIADQAHAEAGAHIgJAJQgEgHgGgCQgFgDgIAAQgGAAgGADQgGACgEAEQgEAFgCAGQgCAGAAAHQAAAGACAGQACAGAEAFQAEAEAGACQAGADAGAAQAIAAAFgDQAGgCAEgHIAJAJQgGAHgHAEIgIADIgLABQgJAAgJgDgABUArQgFgCgEgEQgFgEgCgFQgDgGAAgGQAAgIADgGQACgCAFgFQAEgDAFgBQAGgCAFAAQAJAAAIACQAHAEAGAFIAAgPQgBgFgCgDIgEgFQgDgDgEgBQgEgBgFgBQgHAAgHAEQgGACgHAHIgGgJQAIgIAIgEQAGgCANgBQAHAAAGABQAHACAEAEQAFAEACAFQADAGAAAHIAAA6IgNAAIAAgKQgGAGgIADQgGADgKAAIgLgBgABcAAIgHACQgDACgBAEQgCAEAAAEQAAADACAEQABADADADIAHAEIAJACQAHgBAGgCQAGgDAFgFIAAgQQgFgGgGgCQgGgCgHABIgJABgAgCArIgLgCIgJgFIgHgGIAHgIQAGAFAIADQAIADAJAAIAKgBIAIgDQADgCACgDQACgDAAgDQAAgEgDgDIgFgEIgJgDIgcAAIAAgKIARAAIALgBIAHgCQAEgCACgDQACgDAAgDQAAgDgCgDIgFgEIgIgDIgKgBQgIAAgGADQgIACgGAGIgHgIQAHgGAIgEIAKgDIAJgBQAJAAAHABQAIACAFADQAGADADAEQADAFAAAGQgBAEgCAEIgGAGIgHAFIgIACIAIAAIAIADQAFADACADQACAFAAAFQAAAFgCAFQgDAFgFADQgFAEgIACQgIABgIAAIgLgBgAkSAhQACAAADgCQACgCACgEQADgFAEgUIAFgrIA9AAIAABVIgNAAIAAhJIgjAAIgFAfQgBALgCAJQgDAJgEAFQgEAGgFACQgFACgFAAgAncApQgIgEgGgHQgFgHgDgIQgDgKAAgIQAAgLADgRIAEgLIAEgIIAHgGIAIgGQAIgDAMgDQANgCAGgCQAFgBAAgDIANAAQAAAFgDAEQgDADgFACIgLAEIgMACQgKABgGADQgGADgFAEQgEADgCAFQgDAFgBAFIAGgHIAIgFIAJgFQAFgBAFAAQAJAAAIADQAIAEAEAGQAGAGADAIQADAJAAAJQAAAIgDAIQgDAIgGAHQgFAGgIAEQgIADgKAAQgKAAgIgDgAnXgeQgEADgFAEQgDAEgCAHQgCAGAAAGQAAAFACAGQACAGADAFQAFAEAEADQAGADAHAAQAHAAAFgDQAFgDAEgEQAEgFACgGQABgGABgFQgBgGgBgGQgCgHgEgEQgEgEgFgDQgFgDgHAAQgHAAgGADgAKTAqIgfgnIgOAOIAAAZIgOAAIAAhVIAOAAIAAAsIAtgsIASAAIgnAoIAnAtgAhqAqIAAhCIguBCIgOAAIAAhVIAOAAIAABBIAuhBIANAAIAABVgAkxAqIAAhVIANAAIAABVgAmIAqIAAhVIANAAIAAAiIAgAAQAHgBAFADQAGACADAEQADACACAEQACAFAAAGQAAAFgCAEQgCAFgDAEQgDAEgGACQgFACgHAAgAl7AeIAfAAQAHAAAEgEQAEgEAAgGQAAgHgEgEQgDgEgIgBIgfAAgAoYAqIAAhCIguBCIgNAAIAAhVIAOAAIAABBIAthBIANAAIAABVgArhAqIAAhJIguAAIAABJIgOAAIAAhVIBJAAIAABVgAMOAIIgDhUIARAAIgCBUg");
	this.shape.setTransform(79.8,7.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.6,15.5);


(lib.Символ40 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEB3B").s().p("AAJBOIAAgQIgMgCIgLgEIgKgGIgHgHIAJgMQAFAHAJAEIAIAEIAJACIAAgsIgNgEQgGAAgFgEQgGgEgDgFQgDgGAAgIQAAgHADgGQACgFAGgFQAFgEAGgDQAFgCAJgBIAAgRIAKAAIAAARQAMABAIAFIAFACQAGADAFAGIgJALIgCgCQgFgFgFgDQgHgDgIgBIAAAnIAOAFQAGACAFABIACABQAFAEADAGQAEAGgBAJQAAAGgBAGQgDAGgFAFIgEAEIgHAEQgHADgLABIAAAQgAATAwQAGAAAFgCIAHgFIAEgHIABgGQAAgEgCgEIgEgFQgGgEgLgDgAAAgtIgFAEIgFAGQgCADAAAEQAAAEACADQACADADACQAEADAKADIAAglIgJACgABQA7QgDgDAAgEQAAgEADgDQACgDAEAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAQgEAAgCgDgAhEA8IAAhjIgTAVIgJgJIAegfIAOAAIAAB2gABRAaIgDhUIARAAIgDBUg");
	this.shape.setTransform(9.7,7.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,19.4,15.7);


(lib.Символ39 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHaBHIAAgXIhCAAIAAAXIgOAAIAAgiIAGgCQACgCACgDIAEgKIAJg4IA8AAIAABJIAKAAIAAAigAGoAGQgCAMgCAIQgEAHgEAEIA0AAIAAg9IgjAAgAMsAxQgFgCgFgDQgEgFgCgEQgEgHAAgGQAAgHAEgGQACgFAEgEQAFgBAFgCQAFgCAGAAQAJAAAIADQAGACAGAFIAAgNQAAgFgCgDIgFgGQgCgCgFgBQgEgCgEAAQgIAAgGADQgHADgGAGIgGgJQAHgHAJgEQAGgCANgCQAHAAAFACQAHABAEAEQAFAEACAFQADAGAAAIIAAA5IgNAAIAAgKQgFAHgIACQgHADgJABIgLgCgAMzAEIgGAFQgEACgBAEQgCADABAEQgBAEACADQABAEAEADIAGADIAJACQAHAAAHgDQAGgDAEgFIAAgQQgEgFgGgDQgHgDgHAAIgJABgAJUAnQADAAACgCQADgBACgFQACgFAEgWIAGgoIA9AAIAABUIgOAAIAAhIIgjAAIgEAeQgCAMgCAJQgCAIgEAFQgEAGgFACQgFADgGAAgAIPAvQgIgDgHgGQgGgGgDgIQgDgJAAgKQAAgHADgJQADgIAGgGQAGgGAIgEQAHgEAKAAQAKAAAIAEQAHAEAGAGQAFAGADAJQADAIgBAIIAAADIhGAAQABAGACAGQACAFAEAEQAFAFAFACQAFACAIAAQAHAAAHgCQAIgEAFgFIAGAJQgGAHgJADQgJADgLABQgJgBgIgDgAI7AAIgBgIIgGgKQgEgEgFgCQgFgDgHAAQgHAAgGACQgEADgFAEQgCAEgCAGIgDAIIA5AAIAAAAgAFQAvQgHgDgHgHQgFgFgEgJQgCgJAAgJQAAgHACgJQAEgJAFgFQAHgHAHgDQAIgEAKAAIALACIAIADQAHAEAFAGIgJAJQgDgGgGgDQgGgDgGABQgIgBgFADQgFADgFAEQgDAFgCAFQgDAHAAAFQAAAHADAHQACAFADAFQAFAEAFADQAFADAIgBQAGABAGgDQAGgDADgGIAJAJQgFAGgHAEIgIADIgLACQgKAAgIgEgABbAxQgFgCgEgDQgEgFgDgEQgDgHAAgGQAAgHADgGQADgFAEgEQAEgBAFgCQAGgCAGAAQAIAAAIADQAHACAGAFIAAgNQAAgFgCgDIgFgGQgDgCgEgBQgEgCgFAAQgHAAgHADQgGADgHAGIgFgJQAGgHAJgEQAGgCANgCQAIAAAFACQAGABAFAEQAEAEADAFQADAGAAAIIAAA5IgNAAIAAgKQgGAHgIACQgHADgIABIgMgCgABiAEIgGAFQgDACgBAEQgCADAAAEQAAAEACADQABAEADADIAGADIAJACQAIAAAGgDQAHgDAEgFIAAgQQgEgFgHgDQgGgDgIAAIgJABgAjfAnQAEAAACgCQADgBABgFQADgFAEgWIAGgoIA8AAIAABUIgOAAIAAhIIgjAAIgDAeQgCAMgDAJQgCAIgEAFQgDAGgFACQgGADgGAAgAkkAxQgGgCgEgDQgFgFgCgEQgDgHAAgGQAAgHADgGQACgFAFgEQAEgBAGgCQAFgCAGAAQAIAAAIADQAHACAGAFIAAgNQAAgFgCgDIgFgGQgDgCgEgBQgEgCgEAAQgIAAgHADQgGADgGAGIgGgJQAGgHAJgEQAGgCANgCQAHAAAGACQAHABAEAEQAEAEADAFQADAGAAAIIAAA5IgNAAIAAgKQgGAHgHACQgIADgIABIgLgCgAkeAEIgGAFQgDACgCAEQgBADAAAEQAAAEABADQACAEADADIAGADIAJACQAIAAAGgDQAHgDAEgFIAAgQQgEgFgHgDQgGgDgIAAIgJABgAL8AwIgfgnIgPAPIAAAYIgNAAIAAhUIANAAIAAAsIAugsIARAAIgmAlIAmAvgADmAwIAAghIgZAAIgUAhIgQAAIAXghIgJgEQgEgCgDgDIgFgGQgBgEgBgGQAAgFACgFQACgFAEgDQAEgFAFgBQAEgCAHAAIAuAAIAABUgAC7gVQgDAFAAAGQAAAHADADQAEADAHAAIAgAAIAAgbIggAAQgHgBgEAEgAAlAwIAAgnIgsAAIAAAnIgNAAIAAhUIANAAIAAAkIAsAAIAAgkIAOAAIAABUgAhyAwIAAhUIAOAAIAAAhIAhAAQAGAAAGADQAEAAAEADQAEAEABAEQACAFAAAGQAAAGgCAEQgBAFgEADQgEAFgEABQgGACgGAAgAhkAlIAfAAQAHgBAFgDQADgFAAgGQAAgGgDgFQgFgEgHAAIgfAAgAlbAwIAAhBIgdBBIgEAAIgdhBIAABBIgOAAIAAhUIASAAIAbA+IAag+IASAAIAABUgAnOAwIAAhBIguBBIgOAAIAAhUIAOAAIAABAIAuhAIANAAIAABUgAoxAwIAAgnIguAAIAAAnIgOAAIAAhUIAOAAIAAAkIAuAAIAAgkIANAAIAABUgAqUAwIAAhBIguBBIgOAAIAAhUIAOAAIAABAIAuhAIANAAIAABUgAr6AwIAAhhIgoBhIgHAAIgohhIAABhIgQAAIAAh2IAWAAIAlBZIAmhZIAVAAIAAB2g");
	this.shape.setTransform(86.6,7.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,173.2,14.2);


(lib.Символ37 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#1C1D2C").ss(1,0,0,3).p("EhKNgHBMCUbAAAIAAODMiUbAAAg");
	this.shape.setTransform(475,45);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-1,952,92);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEB3B").s().p("AsBDhIAAnBIYCAAIAAHBg");
	this.shape.setTransform(77,22.5);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ35 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.btnw();
	this.instance.setTransform(-6.1,-5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.1,-5,180,62);


(lib.Символ32 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAMBXQgIgDgEgFQgGgGgDgHQgFgIAAgKQAAgKAFgIQADgIAGgFQAEgFAIgDQAIgDAIAAQAOAAAKAFQALAEAHAJIAAgXQAAgEgCgFQgDgFgEgEQgEgDgGgCQgGgCgHAAQgLAAgKAFQgJAEgIAJIgIgOQAJgKAMgFQAJgEATgBQAKAAAJACQAIACAHAFQAHAGAEAHQADAJAAAJIAABWIgTAAIAAgOQgHAJgLAEQgLAEgNAAQgIAAgIgCgAAXAXQgFACgFADQgEAEgCAFQgCAFAAAGQAAAGACAFQACAFAEAEQAFADAFACQAGACAGAAQALAAAJgEQAJgEAGgHIAAgYQgGgIgJgEQgJgEgLAAQgGAAgGADgAlIBYQgIgCgIgDQgJgDgGgFIgOgKQgGgGgFgIQgEgHgEgIIgFgRQgCgJAAgKQAAgIACgKIAFgRQAEgIAEgHQAFgHAGgGQAGgGAIgFQAGgEAJgDQAIgEAIgBQAJgCAJAAQAMAAAKADQAJACAJAFQAHAEAHAHQAHAGAFAHIgSAKQgDgFgGgFIgLgIQgGgDgHgCQgHgCgIAAQgOAAgMAFQgMAFgJAKQgKAJgEANQgFANgBAOQABAPAFANQAEANAKAJQAJAKAMAFQAMAFAOAAQAIAAAHgCIANgFIALgIQAGgFADgFIATAKQgGAIgHAGQgHAGgHAFQgJAEgJADQgLACgLAAQgJAAgJgBgAF8BWIAAhgIhCBgIgSAAIAAh7IATAAIAABeIBBheIAUAAIAAB7gADtBWIAAhgIgoBgIgIAAIgphgIAABgIgUAAIAAh7IAaAAIAmBbIAnhbIAaAAIAAB7gAhBBWIAAg4IhCAAIAAA4IgTAAIAAh7IATAAIAAAyIBCAAIAAgyIAUAAIAAB7g");
	this.shape.setTransform(40.1,9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,80.1,18);


(lib.Символ31 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AB9A+IAAh7IATAAIAAB7gAAAA+IAAh7IASAAIAAAwIAvAAQAKAAAHADQAHADAGAGQAFADACAHQACAHABAIQgBAIgCAHQgCAHgFAFQgGAFgHADQgHADgKAAgAASAtIAtAAQAKAAAGgGQAGgGAAgJQAAgKgGgFQgGgHgKAAIgtAAgAiQA+IAAh7IBGAAQAIAAAGACQAHACAFAFQAEAEACAGQADAGAAAHQAAALgGAIQgFAHgKADQAKAAAHAJQAGAJABAKQgBAIgCAGQgCAGgFAFQgFAEgGADQgIACgIAAgAh8AtIAvAAQAKAAAFgFQAGgFAAgJQAAgIgGgGQgFgGgKAAIgvAAgAh8gJIAuAAQAJAAAGgFQAEgFAAgHQAAgJgFgEQgFgFgJAAIguAAg");
	this.shape.setTransform(14.5,6.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,29,12.6);


(lib.Символ30 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADkBTQgLgFgJgJQgHgKgFgLQgEgNgBgNQABgOAEgKQAFgMAHgJQAJgJALgFQAMgFAOAAQAOAAAMAFQALAFAIAJQAIAJAFAMQAEAKAAAOQAAANgEANQgFALgIAKQgIAJgLAFQgMAFgOAAQgOAAgMgFgADsgVQgHAEgGAHQgFAHgDAHQgDAIAAAKQAAAKADAIQADAJAFAHQAGAHAHADQAIAEAKAAQAKAAAHgEQAIgDAGgHQAFgHACgJQAEgIAAgKQAAgKgEgIQgCgHgFgHQgGgHgIgEQgHgEgKAAQgKAAgIAEgAggBTQgLgFgIgJQgIgKgEgLQgFgNAAgNQAAgOAFgKQAEgMAIgJQAIgJALgFQAMgFAOAAQANAAALAFQAMAFAHAJQAJAJAEAMQAEAKABAOQgBANgEANQgEALgJAKQgHAJgMAFQgLAFgNAAQgOAAgMgFgAgYgVQgHAEgFAHQgGAHgCAHQgDAIgBAKQABAKADAIQACAJAGAHQAFAHAHADQAIAEAKAAQAIAAAIgEQAIgDAFgHQAFgHADgJQADgIAAgKQAAgKgDgIQgDgHgFgHQgFgHgIgEQgIgEgIAAQgKAAgIAEgAFcBTQgEgEgBgGQABgGAEgEQAEgEAGAAQAGAAAEAEQAEAEAAAGQAAAGgEAEQgEAEgGAAQgGAAgEgEgABWBVIAAh8IBYAAIAAARIhEAAIAABrgAh3BVIAAg4IhCAAIAAA4IgTAAIAAh8IATAAIAAAyIBCAAIAAgyIAUAAIAAB8gAkGBVIAAhhIgpBhIgIAAIgohhIAABhIgUAAIAAh8IAZAAIAnBbIAmhbIAaAAIAAB8gAFeAkIgFh7IAZAAIgEB7g");
	this.shape.setTransform(37.3,8.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,74.5,17.7);


(lib.Символ29 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEB3B").s().p("AniBuIAAirIAvAAIAAANQAHgJAKgEQAIgDAKAAQAMAAAKAEQAKAEAIAIQAHAJAEAMQAFANAAAOQAAAPgFANQgEAMgHAJQgIAIgKAEQgKAEgMAAQgKAAgIgDQgJgEgIgJIAAA9gAmqgVQgGADgDADIAAAeQADAEAGADQAGACAEAAQAKAAAHgGQADgEACgEQACgFAAgFQAAgEgCgFQgCgFgDgDQgHgGgKAAQgEAAgGACgAKmA9QgNgFgKgIQgJgJgFgMIgEgNIgCgOQAAgMAFgMQAFgMAJgJQAJgJANgFQANgFAOAAQAOAAAMAEQAMAFAJAJQAJAKAFANQAFASAAAJIAAAKIhVAAQACAGAGAFQAIAFALAAQAGAAAIgDQAKgCAEgEIAUAdQgFAEgGADIgOAFQgOADgPAAQgPAAgMgEgALUgOQgBgGgEgDQgFgGgLAAQgJAAgFAGQgEADgCAGIApAAIAAAAgAGgA9QgNgFgKgIQgJgJgFgMIgEgNIgCgOQAAgMAFgMQAFgMAJgJQAJgJANgFQANgFAOAAQAOAAAMAEQAMAFAJAJQAJAKAFANQAFASAAAJIAAAKIhVAAQACAGAGAFQAIAFALAAQAGAAAIgDQAKgCAEgEIAUAdQgFAEgGADIgOAFQgOADgPAAQgPAAgMgEgAHOgOQgBgGgEgDQgFgGgLAAQgJAAgFAGQgEADgCAGIApAAIAAAAgAEBA/QgIgDgGgFQgHgFgEgHQgEgJAAgKQAAgLAEgIQAEgGAHgFQAGgEAIgCQAHgCAHAAQANAAAKAEQAKADAFAHIAAgNQAAgHgGgEQgGgFgLAAQgJAAgJADQgJAEgIAFIgQgcQAJgHAUgIQAPgEAPAAQANAAAKACQAMADAIAFQAJAHAFAJQAFAQAAAKIAABKIgvAAIAAgMQgFAHgKAEQgLAEgMAAQgHAAgHgCgAEYARQgGACAAAGQAAAFAGADQAEACAHAAQAGAAAFgCQAFgCACgDIAAgHQgCgDgFgCQgFgCgGAAQgHAAgEADgAAMBAIgMgEQgNgFgJgKQgJgJgFgMQgFgLAAgNQAAgMAFgMQAFgMAJgJQAJgJANgFIAMgEIAQgBQALAAASAFQANAFAKAJQAJAJAFAMQAEAMAAAMQAAANgEALQgFAMgJAJQgKAKgNAFQgSAFgLAAgAALgQQgGAHAAAJQAAAKAGAHQAGAHALAAQAKAAAGgHQAGgHAAgKQAAgJgGgHQgGgHgKAAQgLAAgGAHgAiIBAIgOgEIgMgHIgKgIQgJgKgFgNQgFgNAAgNQAAgQAFgYIAFgQQADgHAFgGIAKgLIAMgIQAIgEAWgFIAKgDQAEgDAAgCIA0AAQAAAIgFAHQgEAGgIAEQgHAEgJADIgQADIgSAEQgIADgFADQgIAGgDAKQAHgJAJgEQAJgDANAAQANAAALAFQAKAFAIAJQAIAJAEAMQAEAMAAAMQAAAMgEAMQgFAMgJAJQgKAKgNAFQgSAFgLAAgAiJgQQgGAHAAAJQAAAKAGAHQAGAHALAAQAKAAAGgHQAGgHAAgKQAAgJgGgHQgGgHgKAAQgLAAgGAHgAkzA/QgIgDgGgFQgHgFgEgHQgEgJAAgKQAAgLAEgIQAEgGAHgFQAGgEAIgCQAHgCAHAAQANAAAKAEQAKADAFAHIAAgNQAAgHgGgEQgGgFgLAAQgJAAgJADQgJAEgIAFIgQgcQAJgHAUgIQAPgEAPAAQANAAAKACQAMADAIAFQAJAHAFAJQAFAQAAAKIAABKIgvAAIAAgMQgFAHgKAEQgLAEgMAAQgHAAgHgCgAkcARQgGACAAAGQAAAFAGADQAEACAHAAQAGAAAFgCQAFgCACgDIAAgHQgCgDgFgCQgFgCgGAAQgHAAgEADgApfA/QgIgDgGgFQgHgFgDgHQgEgJAAgKQAAgLAEgIQADgGAHgFQAGgEAIgCQAHgCAIAAQAMAAAKAEQALADAFAHIAAgNQAAgHgGgEQgGgFgMAAQgIAAgKADQgJAEgHAFIgQgcQAIgHAUgIQAPgEAQAAQANAAAKACQALADAIAFQAKAHAEAJQAGAQAAAKIAABKIgvAAIAAgMQgGAHgKAEQgLAEgLAAQgIAAgHgCgApIARQgFACAAAGQAAAFAFADQAFACAGAAQAGAAAFgCQAGgCACgDIAAgHQgCgDgGgCQgFgCgGAAQgGAAgFADgArXBAIgQgEIgOgHIgLgHIAVgcQAIAGAMADQAKADAJAAQAJAAADgCQAEgBAAgDQAAgDgEgCQgEgDgJAAIgYAAIAAggIAYAAQAJAAADgCQACgCAAgDQAAgDgDgCQgEgBgHAAQgLAAgJADQgJADgGAGIgWgaIAKgIIANgHQAHgDAIgCQAIgBAJAAQAQAAANACQAMADAIAEQAIAFAEAGQAEAHAAAIQAAAFgDAFIgGAIIgKAHIgNAEQAGAAAGAAQAGACAFAEQAFAEADAFQADAGAAAGQAAAIgEAIQgFAHgIAFQgIAFgMADQgMACgPAAQgJAAgKgBgAIjA+IAAhTIghAAIAAgoIBxAAIAAAoIghAAIAABTgACMA+IAAhTIghAAIAAgoIBxAAIAAAoIghAAIAABTg");
	this.shape.setTransform(76.9,11.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,153.9,22.2);


(lib.Символ24 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.check();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,43,31);


(lib.Символ22 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAWBHIAAgXIhAAAIAAAXIgNAAIAAghIAFgDQADgBACgEIADgKIAJg5IA6AAIAABKIAKAAIAAAigAgZAGQgCAMgDAIQgDAHgFAEIAyAAIAAg9IghAAgAO6AvQgDgCAAgFQAAgDADgEQADgDAEAAQAEAAADADQADAEAAADQAAAFgDACQgDADgEAAQgEAAgDgDgANqAxQgGgCgEgDQgEgFgDgEQgDgHAAgGQAAgHADgGQADgFAEgEQAEgBAGgCQAFgCAGAAQAJAAAHADQAHACAGAFIAAgNQAAgFgCgDIgFgGQgDgDgEAAQgEgCgEAAQgIAAgHADQgGADgGAGIgGgJQAHgIAIgDQAGgDANgBQAIABAFABQAHABAEAEQAFAEACAFQADAGAAAHIAAA6IgNAAIAAgKQgGAGgHADQgHADgJAAIgLgBgANxAEIgHAFQgDACgBADQgCAEAAAEQAAAEACADQABAEADADIAHADIAJACQAHAAAGgDQAHgDAEgFIAAgQQgEgFgHgEQgGgCgHAAIgJABgAMRAxIgKgCIgJgFIgIgFIAHgJQAGAGAIADQAJACAKAAIAKgBIAIgCQAEgCABgEQACgCAAgEQAAgEgCgCIgGgFIgJgCIgegBIAAgKIAUAAIAKAAIAIgDQAEgCABgCQACgDAAgEQAAgCgBgDIgGgEIgIgDIgKgCQgJABgHADQgIACgFAGIgHgIQAGgHAJgDIAJgEIAMgBQAIABAIABQAHACAFADQAGADADAEQADAFAAAFQAAAEgDAFIgFAGIgIACIgIACIAIABIAIAFQAFADACADQACAEAAAGQAAAEgCAGQgDAEgFAEQgFADgIACQgHABgJAAIgNgBgAKvAxQgGgCgEgDQgEgFgDgEQgDgHAAgGQAAgHADgGQADgFAEgEQAEgBAGgCQAFgCAGAAQAJAAAHADQAHACAGAFIAAgNQAAgFgCgDIgFgGQgDgDgEAAQgEgCgEAAQgIAAgHADQgGADgGAGIgGgJQAHgIAIgDQAGgDANgBQAIABAFABQAHABAEAEQAFAEACAFQADAGAAAHIAAA6IgNAAIAAgKQgGAGgHADQgHADgJAAIgLgBgAK2AEIgHAFQgDACgBADQgCAEAAAEQAAAEACADQABAEADADIAHADIAJACQAHAAAGgDQAHgDAEgFIAAgQQgEgFgHgEQgGgCgHAAIgJABgAH0AxQgGgCgEgDQgEgFgDgEQgDgHAAgGQAAgHADgGQADgFAEgEQAEgBAGgCQAFgCAGAAQAJAAAHADQAHACAGAFIAAgNQAAgFgCgDIgFgGQgDgDgEAAQgEgCgEAAQgIAAgHADQgGADgGAGIgGgJQAHgIAIgDQAGgDANgBQAIABAFABQAHABAEAEQAFAEACAFQADAGAAAHIAAA6IgNAAIAAgKQgGAGgHADQgHADgJAAIgLgBgAH7AEIgHAFQgDACgBADQgCAEAAAEQAAAEACADQABAEADADIAHADIAJACQAHAAAGgDQAHgDAEgFIAAgQQgEgFgHgEQgGgCgHAAIgJABgAGbAxIgKgCIgJgFIgIgFIAHgJQAGAGAIADQAJACAKAAIAKgBIAIgCQAEgCABgEQACgCAAgEQAAgEgCgCIgGgFIgJgCIgegBIAAgKIAUAAIAKAAIAIgDQAEgCABgCQACgDAAgEQAAgCgBgDIgGgEIgIgDIgKgCQgJABgHADQgIACgFAGIgHgIQAGgHAJgDIAJgEIAMgBQAIABAIABQAHACAFADQAGADADAEQADAFAAAFQAAAEgDAFIgFAGIgIACIgIACIAIABIAIAFQAFADACADQACAEAAAGQAAAEgCAGQgDAEgFAEQgFADgIACQgHABgJAAIgNgBgABLAvQgIgDgGgGQgGgGgDgJQgEgIAAgKQAAgIADgIQAEgIAFgGQAGgHAIgDQAIgDAJgBQAKABAIADQAHAEAGAGQAFAGADAJQADAIAAAIIAAAEIhHAAQABAFACAGQACAGAEADQAFAFAFACQAGADAHgBQAHAAAHgCQAIgDAFgFIAGAJQgGAGgJADQgJADgLAAQgJAAgIgDgAB3AAIgBgIIgFgKQgEgEgFgCQgGgDgHgBQgHAAgFADQgFACgEAFQgDAEgCAGIgDAIIA5AAIAAAAgAoFAxQgFgCgEgDQgFgFgCgEQgDgHAAgGQAAgHADgGQACgFAFgEQAEgBAFgCQAGgCAFAAQAJAAAIADQAHACAFAFIAAgNQAAgFgCgDIgEgGQgDgDgEAAQgEgCgFAAQgIAAgGADQgHADgGAGIgGgJQAHgIAJgDQAGgDANgBQAHABAGABQAGABAFAEQAEAEADAFQADAGAAAHIAAA6IgOAAIAAgKQgFAGgIADQgHADgJAAIgLgBgAn+AEIgGAFQgDACgCADQgBAEAAAEQAAAEABADQACAEADADIAGADIAJACQAIAAAGgDQAGgDAEgFIAAgQQgEgFgGgEQgGgCgIAAIgJABgAqAAnQADAAACgBQADgCACgFQACgFAEgWIAGgpIA8AAIAABVIgNAAIAAhIIgjAAIgEAeQgCAMgCAJQgDAIgEAFQgDAGgFACQgFACgGAAgAJ/AwIgfgmIgPANIAAAZIgNAAIAAhVIANAAIAAAtIAugtIARAAIgmAmIAmAvgAD9AwIAAhVIAOAAIAAAiIAgAAQAHAAAFACQAFABAEADQADAEACAEQACAFAAAGQAAAFgCAFQgCAFgDADQgEAFgFACQgFABgHAAgAELAlIAfAAQAHAAAEgFQAEgEAAgGQAAgHgEgEQgEgEgHAAIgfAAgADVAwIAAgmIgtAAIAAAmIgOAAIAAhVIAOAAIAAAkIAtAAIAAgkIAOAAIAABVgAi/AwIAAhVIAwAAQAGAAAEACIAIAFQADADACAEQACAEAAAFQAAAHgFAGQgDADgGABQAGADAFAFQAEAGAAAIQAAAFgBAFQgCAEgDADIgIAFQgFACgGgBgAixAlIAgAAQAHgBAEgDQADgDAAgHQAAgFgDgEQgEgEgHAAIggAAgAixAAIAgAAQAGAAADgEQAEgDAAgFQAAgGgEgDQgDgEgGABIggAAgAkVAwIAAhVIANAAIAABVgAltAwIAAhVIAOAAIAAAiIAgAAQAHAAAFACQAFABAEADQADAEACAEQACAFAAAGQAAAFgCAFQgCAFgDADQgEAFgFACQgFABgHAAgAlfAlIAfAAQAHAAAEgFQAEgEAAgGQAAgHgEgEQgEgEgHAAIgfAAgAmlAwIAAhIIgZAAIAAgNIBAAAIAAANIgZAAIAABIgAqeAwIAAhIIguAAIAABIIgNAAIAAhVIBIAAIAABVgAsCAwIAAhVIAOAAIAABVgAtZAwIAAhVIANAAIAAAiIAhAAQAGAAAGACQAFABADADQAEAEABAEQACAFAAAGQAAAFgCAFQgBAFgEADQgDAFgFACQgGABgGAAgAtMAlIAfAAQAHAAAFgFQADgEAAgGQAAgHgDgEQgEgEgIAAIgfAAgAvKAwIAAh1IA2AAQAHAAAHABQAGADAEAEQAFAEACAGQACAFAAAHQAAAFgBAFQgCAFgDADQgDAEgEADIgIACQAFABAEADQAFACADAEQADADACAEQACAGAAAFQAAAIgDAFQgCAGgEAEQgFAFgGACQgHADgIgBgAu7AjIAlAAQAFAAAEgCQAEgBADgDQADgCACgEQABgEAAgFIgBgIIgEgGQgDgBgEgCQgFgBgFAAIglAAgAu7gRIAkAAQAFAAAEgCIAHgEIAEgGIABgIIgBgHIgEgGQgDgDgEgCQgEgBgFAAIgkAAgAO7APIgDhUIARAAIgCBUg");
	this.shape.setTransform(100.5,13.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.4,6.6,194.3,14.2);


(lib.Символ21 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.check();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,43,31);


(lib.Символ18 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.check();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,43,31);


(lib.Символ16 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADxBMIAAh2IANAAIAAANQAFgHAHgEIAIgDIAJgBQAJAAAHADQAHADAFAGQAGAGACAJQADAIAAAJQAAAKgDAJQgCAIgGAGQgFAGgHADQgHADgJAAQgIAAgIgEQgIgEgFgHIAAAugAEIgcQgGAEgEAGIAAAlQAEAGAGAEQAIAEAIAAQAHAAAEgDQAGgCADgFQAEgEACgGQACgHAAgGQAAgGgCgGQgCgGgEgFQgDgEgGgDQgEgCgHAAQgIAAgIAEgAIBBBIAAgWIhCAAIAAAWIgNAAIAAghIAGgDQACgBACgDIAEgLIAIg4IA8AAIAABJIAKAAIAAAigAHQABQgCAMgDAHQgDAIgFADIA0AAIAAg9IgjAAgALrAqQgDgDAAgEQAAgEADgDQACgDAFAAQAEAAACADQAEADAAAEQAAAEgEADQgDADgDAAQgFAAgCgDgAI1ApQgIgDgGgGQgGgHgDgIQgCgIAAgJQAAgIACgIQADgJAGgGQAGgGAIgEQAHgDALAAQAJAAAJADQAHAEAGAGQAGAGACAJQADAIAAAIQAAAJgDAIQgCAIgGAHQgGAGgHADQgJAEgJAAQgLAAgHgEgAI6geQgFAEgEAEQgEAEgBAHQgDAGAAAFQAAAGADAGQABAHAEAEQAEAFAFACQAFADAIAAQAGAAAGgDQAFgCAEgFQADgEADgHQABgGAAgGQAAgGgBgFQgDgHgDgEQgEgEgFgEQgGgCgGAAQgIAAgFACgAFsAqQgHgDgGgHQgHgFgCgJQgEgIAAgKQAAgIADgIQADgJAGgGQAGgGAHgEQAJgDAJAAQAKAAAHADQAIAEAGAGQAFAHADAJQACAHABAJIAAADIhHAAQABAGACAGQACAFAEAEQAFAEAFACQAGADAGAAQAIAAAHgDQAHgDAFgFIAHAJQgHAGgJAEQgIADgLAAQgJAAgJgDgAGZgEIgCgKIgEgKQgFgEgEgCQgGgDgIAAQgGAAgFACQgGADgDAEQgDAEgDAGIgCAKIA5AAIAAAAgABJApQgHgDgHgGQgFgGgEgIQgDgJAAgJQAAgIADgIQAEgJAFgGQAHgHAHgDQAJgDAJAAIAKABIAJADQAHAEAFAHIgJAIQgEgFgFgEQgGgCgGAAQgHAAgGACQgFADgEAEQgFAFgBAGQgCAGAAAGQAAAGACAHQABAGAFAEQAEAFAFACQAGADAHAAQAGAAAGgDQAFgCAEgHIAJAJQgFAHgHAEIgJADIgKABQgJAAgJgEgAiPAqQgIgDgGgHQgGgFgDgJQgEgIABgKQAAgIACgIQAEgJAFgGQAHgGAHgEQAIgDAKAAQAJAAAIADQAIAEAFAGQAGAHADAJQACAHAAAJIAAADIhHAAQABAGADAGQACAFADAEQAFAEAFACQAGADAHAAQAIAAAGgDQAIgDAFgFIAHAJQgHAGgJAEQgJADgKAAQgKAAgIgDgAhigEIgCgKIgFgKQgEgEgFgCQgGgDgHAAQgGAAgGACQgFADgEAEQgDAEgCAGIgDAKIA6AAIAAAAgAl6ApQgHgDgHgGQgFgGgEgIQgCgJAAgJQAAgIACgIQAEgJAFgGQAHgHAHgDQAIgDAKAAIALABIAIADQAHAEAFAHIgJAIQgDgFgGgEQgGgCgGAAQgIAAgFACQgFADgFAEQgDAFgCAGQgDAGAAAGQAAAGADAHQACAGADAEQAFAFAFACQAFADAIAAQAGAAAGgDQAGgCADgHIAJAJQgFAHgHAEIgIADIgLABQgKAAgIgEgAnfAsQgFgCgEgEQgEgEgDgFQgDgGAAgGQAAgHADgHQADgDAEgEQAEgCAFgCQAGgCAGgBQAIABAIADQAHACAGAFIAAgOQAAgFgCgDIgFgFQgDgDgEgBQgEgBgFAAQgHgBgHADQgGAEgHAFIgFgJQAGgHAJgEQAGgCANgBQAIAAAFACQAGABAFADQAEAFADAFQADAFAAAIIAAA6IgNAAIAAgKQgGAGgIADQgHADgIAAIgMgBgAnYAAIgGADQgDADgCADQgBAEAAAEQAAAEABADQACADADADIAGAEIAJACQAIAAAGgEQAHgCAEgFIAAgQQgEgGgHgDQgGAAgIAAIgJAAgArwArQgGgDgEgEIAHgMQADADAFACQADADAGAAQAGAAAFgEQADgEAGgKIABgDIgthWIARAAIAmBLIAlhLIARAAIg1BgQgHANgFAFQgEADgEACQgFABgHAAQgHAAgHgCgAKHArIAAhVIAwAAQAFAAAFABIAIAGQADACACAEQACAFAAAEQgBAIgEAGQgDAEgHACQAHAAAEAGQAFAGAAAHQAAAFgBAFQgDAFgDADIgIAEQgFACgFAAgAKUAfIAhAAQAHAAADgDQAEgEAAgGQAAgGgEgDQgDgFgHAAIghAAgAKUgGIAhAAQAFAAAEgDQAEgDgBgFQABgHgEgCQgEgEgFAAIghAAgADIArIAAhJIgtAAIAABJIgNAAIAAhVIBIAAIAABVgAgwArIAAhJIgZAAIAAgMIBAAAIAAAMIgZAAIAABJgAjMArIAAgnIguAAIAAAnIgOAAIAAhVIAOAAIAAAkIAuAAIAAgkIANAAIAABVgAoVArIAAgnIguAAIAAAnIgNAAIAAhVIANAAIAAAkIAuAAIAAgkIAOAAIAABVgALsAKIgDhVIARAAIgDBVg");
	this.shape.setTransform(78.6,14.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2.2,6.6,152.8,15.3);


(lib.Символ15 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.check();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,43,31);


(lib.Символ13 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEB3B").s().p("Ar8BuIAAirIAvAAIAAANQAHgJAKgEQAIgDAKAAQAMAAAKAEQAKAEAHAIQAIAJAEAMQAEANABAOQgBAPgEANQgEAMgIAJQgHAIgKAEQgKAEgMAAQgKAAgIgDQgJgEgIgJIAAA9gArEgVQgGADgDADIAAAeQADAEAGADQAFACAFAAQAKAAAHgGQADgEABgEQACgFAAgFQAAgEgCgFQgBgFgDgDQgHgGgKAAQgEAAgGACgAhdAbQAHAAAEgGQAFgHACgPIAJg8IBwAAIAAB7IguAAIAAhTIgZAAIgEAYQgCAPgFALQgEAMgIAIQgHAIgLAEQgLAEgQAAgAmWBAIgOgEIgMgHIgKgIQgJgKgFgNQgEgNgBgNQABgQAEgYIAFgQQAEgHAEgGIAKgLIAMgIQAJgEAVgFIAKgDQAEgDABgCIAzAAQAAAIgEAHQgFAGgIAEQgGAEgKADIgQADIgSAEQgHADgGADQgIAGgDAKQAHgJAKgEQAJgDAMAAQANAAALAFQALAFAHAJQAJAJADAMQAFAMAAAMQgBAMgEAMQgFAMgJAJQgJAKgOAFQgSAFgLAAgAmXgQQgFAHAAAJQAAAKAFAHQAHAHAKAAQAKAAAHgHQAFgHABgKQgBgJgFgHQgHgHgKAAQgKAAgHAHgANsA+IAAg7IgpA7IgtAAIAAh7IAwAAIAAA4IAlg4IAvAAIAAB7gALOA+IAAhCIgYBCIgZAAIgZhCIAABCIgvAAIAAh7IA/AAIAVA8IAWg8IA+AAIAAB7gAINA+IAAh7IAvAAIAAB7gAF8A+IAAh7IAvAAIAAAlIAnAAQAMAAAKAEQAIADAGAGQAHAGACAGQAEAIAAAJQgBAJgDAIQgDAIgHAGQgGAGgIAEQgKADgLAAgAGrAaIAeAAQAKAAAAgIQAAgHgKAAIgeAAgAE0A+IAAgtIgmAAIAAAtIgwAAIAAh7IAwAAIAAAnIAmAAIAAgnIAvAAIAAB7gABHA+IAAh7IAvAAIAAAlIAnAAQAMAAAJAEQAJADAGAGQAHAGACAGQADAIAAAJQAAAJgDAIQgDAIgHAGQgFAGgKAEQgIADgMAAgAB2AaIAeAAQAKAAAAgIQAAgHgKAAIgeAAgAidA+IAAh7IAvAAIAAB7gAkuA+IAAh7IAvAAIAAAlIAnAAQAMAAAKAEQAIADAGAGQAHAGACAGQAEAIAAAJQgBAJgDAIQgDAIgHAGQgGAGgIAEQgKADgLAAgAj/AaIAeAAQAKAAAAgIQAAgHgKAAIgeAAgAoNA+IAAg7IgnA7IgtAAIAAh7IAvAAIAAA4IAlg4IAvAAIAAB7gAtFA+IAAhTIgmAAIAABTIgvAAIAAh7ICFAAIAAB7g");
	this.shape.setTransform(92.3,11.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,184.6,22.2);


(lib.Символ12 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiEBQIAAggIhiAAIAAh8IAgAAIAABfIA0AAIAAhfIAiAAIAABfIANAAIAAA9gAByAyIgNgEQgMgFgJgKQgIgJgFgMQgFgKAAgNQAAgOAFgLQAFgMAIgJQAJgKAMgFIANgEIAPgBQAKAAASAFQAMAFAIAKQAJAJAFAMQAEALAAAOQAAANgEAKQgFAMgJAJQgIAKgMAFQgSAFgKAAgABzgvQgGADgEAFQgEAFgDAHQgCAGAAAIQAAAHACAGQADAGAEAFQAEAFAGADQAGACAIAAQAHAAAGgCQAGgDAEgFQAFgFABgGQADgGAAgHQAAgIgDgGQgBgHgFgFQgEgFgGgDQgGgDgHAAQgIAAgGADgAnnAyIgMgEQgMgFgKgKQgIgJgFgMQgEgKAAgNQAAgOAEgLQAFgMAIgJQAKgKAMgFIAMgEIAPgBQALAAARAFQAMAFAJAKQAIAJAFAMQAFALgBAOQABANgFAKQgFAMgIAJQgJAKgMAFQgRAFgLAAgAnmgvQgFADgFAFQgEAFgCAHQgCAGAAAIQAAAHACAGQACAGAEAFQAFAFAFADQAHACAHAAQAHAAAHgCQAFgDAFgFQAEgFACgGQACgGAAgHQAAgIgCgGQgCgHgEgFQgFgFgFgDQgHgDgHAAQgHAAgHADgAH6AwIAAh8IAhAAIAAB8gAFyAwIAAh8IAhAAIAAArIArAAQAKAAAJAEQAIADAGAGQAFAFADAIQACAHABAGQAAAJgDAHQgDAIgGAFQgFAGgJADQgIAEgKAAgAGTAUIAmAAQAGAAAFgEQADgEAAgGQAAgGgDgBQgFgEgGAAIgmAAgAEwAwIAAgwIgzAAIAAAwIghAAIAAh8IAhAAIAAAvIAzAAIAAgvIAiAAIAAB8gAAFAwIAAhNIg0BNIgfAAIAAh8IAhAAIAABMIAyhMIAhAAIAAB8gAkoAwIAAhfIg0AAIAABfIghAAIAAh8IB2AAIAAB8g");
	this.shape.setTransform(54,8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,107.9,16.1);


(lib.Символ11 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgKBuIAAirIAfAAIAAAQQAHgKAKgFQAKgEALAAQANAAAKAEQAKAEAIAJQAHAIAEAMQAFANgBAOQABAPgFAMQgEAMgHAJQgIAJgKAEQgLAEgMAAQgKAAgKgEQgKgFgIgKIAABAgAAhgfQgIAEgEAGIAAArQAEAGAIAEQAIAEAIAAQAHAAAGgDQAGgCAEgFQAEgFACgHQADgHAAgHQAAgHgDgGQgCgHgEgFQgEgFgGgCQgGgDgHAAQgIAAgIAEgAIMA9QgNgFgJgIQgIgJgFgMQgGgNAAgOQABgMAEgMQAFgMAIgJQAKgJALgFQAMgFAOAAQAOAAAMAFQALAFAJAJQAIAJAFANQAEAMAAAOIAAAHIhdAAQABAGACAFQAEAGADAEQAGAEAFACQAHACAIAAQAIAAAJgDQALgEAGgFIAOAVQgJAIgOAFQgOAEgOAAQgPAAgMgEgAJDgKQAAgLgIgIQgDgEgGgDQgGgCgIAAQgHAAgGACQgFADgEAEQgHAIgCALIA+AAIAAAAgAiDA/QgHgDgHgFQgHgFgDgIQgEgIAAgKQAAgLAEgIQADgFAHgGQAGgEAIgDQAIgCAHAAQANAAALAEQAKAEAHAHIAAgQQgBgKgHgGQgIgFgMAAQgLAAgIADQgKAEgIAHIgNgWQAIgGASgJQAOgEAPAAQAMAAAJACQAKACAIAGQAHAGAFAIQAEAKABANIAABPIghAAIAAgNQgHAIgKAEQgMAEgMAAQgHAAgIgCgAh3AKQgHAGAAAJQAAAIAHAFQAHAFAKAAQAIAAAHgDQAIgDAEgFIAAgPQgEgGgIgDQgHgCgIAAQgKAAgHAEgAovBAIgNgEQgMgFgJgKQgIgKgFgNQgEgNAAgNQAAgQAEgYIAFgQQADgHAEgFIAJgKQAGgFAGgDQAIgEAUgFQAPgCAHgCQAGgDABgDIAiAAQgBAIgFAHQgEAGgIAEQgIADgJADIgRADQgLABgIADQgJADgFAEQgFAEgEAGQgDAEgBAGQAIgKALgFQALgFANAAQANAAALAFQAMAFAHAJQAIAJAEAMQAFAMgBAMQABAMgFAMQgFAMgIAJQgJAKgMAFQgRAFgLAAgAouggQgFADgFAFQgEAFgCAGQgCAHAAAGQAAAHACAGQACAHAEAFQAFAFAFADQAHADAHAAQAHAAAHgDQAFgDAFgFQAEgFACgHQACgHAAgGQAAgGgCgHQgCgGgEgFQgFgFgFgDQgHgDgHAAQgHAAgHADgAGqA+IAAh7IAhAAIAAB7gAEiA+IAAh7IAhAAIAAArIArAAQAKAAAJADQAIADAGAGQAFAGADAFQACAHABAJQAAAIgDAIQgEAHgFAGQgFAGgJADQgIADgKAAgAFDAiIAmAAQAHAAAEgDQAEgEgBgGQABgGgEgEQgEgEgHAAIgmAAgADgA+IAAgyIgzAAIAAAyIghAAIAAh7IAhAAIAAAuIAzAAIAAguIAhAAIAAB7gAjZA+IAAgyIg0AAIAAAyIggAAIAAh7IAgAAIAAAuIA0AAIAAguIAiAAIAAB7gAlvA+IAAhNIg1BNIggAAIAAh7IAhAAIAABKIAzhKIAiAAIAAB7g");
	this.shape.setTransform(61.2,11.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,122.3,22.2);


(lib.Символ10 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTBmIAAggIhMAAIAAAgIgiAAIAAg7QAJgCADgGQADgEACgHIALhNIBlAAIAABeIANAAIAAA9gAhLAIQgCALgEAIQgDAJgHAFIA7AAIAAhBIgoAAgAHIAuQAJAAAEgJQAEgGAEgZIAIg7IBmAAIAAB7IgiAAIAAheIgnAAIgFAhQgBARgFAMQgEAMgGAIQgHAIgIADQgKAEgMAAgAFbBHQgHgDgGgFQgHgFgEgIQgDgIAAgKQAAgLADgIQAEgHAHgGQAGgCAHgDQAIgCAIAAQAMAAALAEQAKADAHAHIAAgPQAAgKgIgGQgHgFgNAAQgKAAgJADQgJAEgJAHIgMgWQAIgGASgJQANgEAQAAQALAAAJACQALACAHAGQAIAGAEAIQAFAKAAANIAABPIghAAIAAgNQgHAIgKAEQgLAEgMAAQgHAAgJgCgAFnASQgGAGAAAJQAAAIAGAFQAHAFAKAAQAIAAAHgDQAIgDAEgFIAAgPQgEgGgIgDQgHgCgIAAQgKAAgHAEgAClAuQAIAAAEgJQAEgGAEgZIAJg7IBlAAIAAB7IghAAIAAheIgoAAIgEAhQgCARgEAMQgEAMgGAIQgHAIgJADQgJAEgMAAgABCBFQgNgFgJgIQgIgJgFgMQgFgNgBgPQAAgLAFgMQAFgMAIgJQAJgJAMgFQANgFAOAAQANAAAMAFQALAFAJAJQAIAJAFANQAEAMAAAOIAAAHIhdAAQAAAGAEAFQADAGADAEQAGAEAGACQAGACAIAAQAIAAAJgDQALgEAGgFIAOAVQgJAIgOAFQgOAEgOAAQgPAAgMgEgAB5gCQAAgLgIgIQgDgEgGgDQgGgCgHAAQgIAAgGACQgGADgDAEQgHAIgCALIA+AAIAAAAgAjXBEQgMgEgJgJQgJgJgEgMQgGgMAAgPQAAgMAGgMQAEgMAJgJQAJgJAMgFQANgEAOAAQAJAAAIABQAIACAHAEQAKAFAIAKIgWAUQgFgGgGgEQgHgDgIAAQgIAAgHADQgFACgFAFQgEAFgDAGQgDAGABAHQgBAIADAHQADAHAEAFQAFAFAFACQAHADAIAAQAIAAAHgEQAGgDAFgGIAWATQgIAKgKAGQgHAEgIABQgIACgJAAQgOAAgNgFgALABGIAAhNIg1BNIggAAIAAh7IAhAAIAABKIA0hKIAhAAIAAB7gAl7BGIAAh7IAiAAIAAB7gAoDBGIAAh7IAiAAIAAArIArAAQAKAAAJADQAHADAGAEQAFAGADAHQADAHAAAJQAAAIgDAIQgDAHgGAGQgFAGgIADQgJADgJAAgAnhAqIAlAAQAHAAAEgDQAEgEAAgGQAAgGgEgEQgEgEgHAAIglAAgApJBGIAAh3IgxB3IgQAAIgxh3IAAB3IglAAIAAirIA0AAIAqBnIAqhnIA0AAIAACrg");
	this.shape.setTransform(73.8,10.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,147.5,20.6);


(lib.Символ7 = function() {
	this.initialize();

	// Слой 1 - копия
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E5E5E5").s().p("A1eHOIAAuWMAq9gAFIkPObg");
	this.shape.setTransform(137.5,46.3);

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A1eHOIAAuWMAq9gAFIkPObg");
	this.shape_1.setTransform(137.5,46.3);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,275,92.6);


(lib.Символ6 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1F1F2D").s().p("EhdVAMbIAA41MC6rAAAIAAY1g");
	this.shape.setTransform(597.5,79.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,1194.9,159);


(lib.Символ4 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.bg();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,1151,767);


(lib.Символ2 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.logo();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,221,70);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ43();
	this.instance.setTransform(16.4,6.2,1,1,0,0,0,16.4,6.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.25,scaleY:1.25},4,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,32.7,12.4);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ40();
	this.instance.setTransform(9.7,7.8,1,1,0,0,0,9.7,7.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.83,scaleY:0.83},4,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,19.4,15.7);


(lib.Символ34 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ35();
	this.instance.setTransform(85,26,0.95,0.95,0,0,0,85,26);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1.5,-3.4,171,58.9);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 1
	this.instance = new lib.Символ34();
	this.instance.setTransform(85,26,1,1,0,0,0,85,26);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.05,scaleY:1.05},3,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-3.4,171,58.9);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 7
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEB3B").s().p("AhJBKQgegfAAgrQAAgqAegfQAfgeAqAAQArAAAfAeQAeAfAAAqQAAArgeAfQgfAegrAAQgqAAgfgeg");
	this.shape.setTransform(-35.5,-104.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},20).wait(80));

	//  btn
	this.btn = new lib.Символ33();
	this.btn.setTransform(474.5,18,1,1,0,0,0,85,26);
	this.btn.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(10).to({x:514.5,alpha:1},4,cjs.Ease.get(1)).to({x:504.5},5,cjs.Ease.get(1)).wait(70).to({x:484.5},5,cjs.Ease.get(1)).to({x:534.5,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// Символ 32
	this.instance = new lib.Символ32();
	this.instance.setTransform(-26.1,16.9,1.177,1.177,0,0,0,40.1,9);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:17.5,alpha:1},4,cjs.Ease.get(1)).to({x:6.6},5,cjs.Ease.get(1)).wait(78).to({x:-4.3},5,cjs.Ease.get(1)).to({x:39.3,alpha:0},5,cjs.Ease.get(1)).wait(3));

	// Символ 31
	this.instance_1 = new lib.Символ31();
	this.instance_1.setTransform(50.7,19.6,1.177,1.177,0,0,0,14.6,6.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(2).to({_off:false},0).to({x:94.3,alpha:1},4,cjs.Ease.get(1)).to({x:83.4},5,cjs.Ease.get(1)).wait(74).to({x:72.5},5,cjs.Ease.get(1)).to({x:116.1,alpha:0},5,cjs.Ease.get(1)).wait(5));

	// Символ 29
	this.instance_2 = new lib.Символ29();
	this.instance_2.setTransform(170.6,19.6,1.177,1.177,0,0,0,77,11);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(4).to({_off:false},0).to({x:214.2,alpha:1},4,cjs.Ease.get(1)).to({x:203.3},5,cjs.Ease.get(1)).wait(31).to({scaleX:1.25,scaleY:1.25,y:19.7},3,cjs.Ease.get(1)).to({scaleX:1.18,scaleY:1.18,y:19.6},4,cjs.Ease.get(1)).wait(32).to({x:192.4},5,cjs.Ease.get(1)).to({x:236,alpha:0},5,cjs.Ease.get(1)).wait(7));

	// Символ 30
	this.instance_3 = new lib.Символ30();
	this.instance_3.setTransform(319.4,17,1.177,1.177,0,0,0,37.3,8.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(6).to({_off:false},0).to({x:363,alpha:1},4,cjs.Ease.get(1)).to({x:352.1},5,cjs.Ease.get(1)).wait(66).to({x:341.2},5,cjs.Ease.get(1)).to({x:384.8,alpha:0},5,cjs.Ease.get(1)).wait(9));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-73.3,-115.3,632.3,162.7);


(lib.Символ25 = function() {
	this.initialize();

	// Символ 42
	this.instance = new lib.Символ42();
	this.instance.setTransform(126.6,14.4,1,1,0,0,0,79.8,7.8);

	// Символ 41
	this.instance_1 = new lib.Символ41();
	this.instance_1.setTransform(19.4,12.6,1,1,0,0,0,16.4,6.2);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3,6.4,203.4,15.7);


(lib.Символ23 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ22();
	this.instance.setTransform(139.8,15.3,1,1,0,0,0,104,14);

	this.instance_1 = new lib.Символ21();
	this.instance_1.setTransform(21.5,15.5,1,1,0,0,0,21.5,15.5);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,233.4,31);


(lib.Символ19 = function() {
	this.initialize();

	// Символ 39
	this.instance = new lib.Символ39();
	this.instance.setTransform(90,13.7,1,1,0,0,0,86.6,7.1);

	// Символ 38
	this.instance_1 = new lib.Символ38();
	this.instance_1.setTransform(194.1,12.8,1.4,1.4,0,0,0,9.7,7.8);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.4,1.9,204.3,21.9);


(lib.Символ17 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ16();
	this.instance.setTransform(116.5,15.1,1,1,0,0,0,81.5,13);

	this.instance_1 = new lib.Символ15();
	this.instance_1.setTransform(21.5,15.5,1,1,0,0,0,21.5,15.5);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,190,31);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_79 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(79).call(this.frame_79).wait(1));

	// Слой 8
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFEB3B").s().p("AgwAxQgUgVAAgcQAAgbAUgVQAVgVAbAAQAcAAAVAVQAVAVgBAbQABAcgVAVQgVAVgcAAQgbAAgVgVg");
	this.shape.setTransform(-280.9,-87.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(80));

	// Символ 13
	this.instance = new lib.Символ13();
	this.instance.setTransform(483.5,19.7,1,1,0,0,0,96.1,11.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).to({x:513.5,alpha:1},4,cjs.Ease.get(1)).to({x:503.5},5,cjs.Ease.get(1)).wait(22).to({scaleX:1.04,scaleY:1.04,y:14.7},4,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:19.7},3,cjs.Ease.get(1)).wait(16).to({x:493.5},5,cjs.Ease.get(1)).to({x:523.5,alpha:0},5,cjs.Ease.get(1)).wait(7));

	// Символ 12
	this.instance_1 = new lib.Символ12();
	this.instance_1.setTransform(324.9,21.1,1,1,0,0,0,54,8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(8).to({_off:false},0).to({x:354.9,alpha:1},4,cjs.Ease.get(1)).to({x:344.9},5,cjs.Ease.get(1)).wait(48).to({x:334.9},5,cjs.Ease.get(1)).to({x:364.9,alpha:0},5,cjs.Ease.get(1)).wait(5));

	// Символ 11
	this.instance_2 = new lib.Символ11();
	this.instance_2.setTransform(201.4,19.7,1,1,0,0,0,61.1,11.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(6).to({_off:false},0).to({x:231.4,alpha:1},4,cjs.Ease.get(1)).to({x:221.4},5,cjs.Ease.get(1)).wait(51).to({x:211.4},5,cjs.Ease.get(1)).to({x:241.4,alpha:0},5,cjs.Ease.get(1)).wait(4));

	// Символ 10
	this.instance_3 = new lib.Символ10();
	this.instance_3.setTransform(57.5,18.8,1,1,0,0,0,73.8,10.2);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(4).to({_off:false},0).to({x:87.5,alpha:1},4,cjs.Ease.get(1)).to({x:77.5},5,cjs.Ease.get(1)).wait(55).to({x:67.5},5,cjs.Ease.get(1)).to({x:97.5,alpha:0},6,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-287.9,-94.3,14,14);


(lib.Символ5 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ6();
	this.instance.setTransform(597.5,79.5,1,1,0,0,0,597.5,79.5);
	this.instance.alpha = 0.93;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,1194.9,159);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ5();
	this.instance.setTransform(590.5,184.5,1,1,0,0,0,597.5,79.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(360));

	// Слой 1 - копия
	this.instance_1 = new lib.Символ4();
	this.instance_1.setTransform(575.5,489.5,1,1,0,0,0,575.5,383.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:-121.8},354).to({y:-130.5,alpha:0},5).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ4();
	this.instance_2.setTransform(575.5,489.5,1,1,0,0,0,575.5,383.5);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(354).to({_off:false},0).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7,105,1194.9,768.1);


(lib.Символ1 = function() {
	this.initialize();

	// logo
	this.instance = new lib.Символ2();
	this.instance.setTransform(119.5,35,1,1,0,0,0,110.5,35);

	// bg
	this.instance_1 = new lib.Символ7();
	this.instance_1.setTransform(134.5,33.7,1,1,0,0,0,137.5,46.2);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3,-12.5,275,92.6);


(lib.Символ26 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ25();
	this.instance.setTransform(145.5,16.7,1,1,0,0,0,109,14.2);

	this.instance_1 = new lib.Символ24();
	this.instance_1.setTransform(21.5,16.1,1,1,0,0,0,21.5,15.5);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0.6,242.9,31);


(lib.Символ20 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ19();
	this.instance.setTransform(141,14.5,1,1,0,0,0,106,13);

	this.instance_1 = new lib.Символ18();
	this.instance_1.setTransform(21.5,15.5,1,1,0,0,0,21.5,15.5);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,242.7,31);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_99 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(99).call(this.frame_99).wait(1));

	// Слой 5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgpAqQgSgSAAgYQAAgXASgSQASgRAXAAQAZAAARARQARASAAAXQAAAYgRASQgRARgZAAQgXAAgSgRg");
	this.shape.setTransform(-151.9,-82.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(100));

	// 4
	this.instance = new lib.Символ26();
	this.instance.setTransform(385.7,48.7,1,1,0,0,0,127.2,15.8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(15).to({_off:false},0).to({x:425.7,alpha:1},4,cjs.Ease.get(1)).to({x:415.7},5,cjs.Ease.get(1)).wait(23).to({y:45.7},5,cjs.Ease.get(1)).to({y:48.7},5,cjs.Ease.get(1)).wait(26).to({x:405.7},5,cjs.Ease.get(1)).to({x:505.7,alpha:0},5,cjs.Ease.get(1)).wait(7));

	// 3
	this.instance_1 = new lib.Символ23();
	this.instance_1.setTransform(381,18.5,1,1,0,0,0,122.5,15.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({x:421,alpha:1},4,cjs.Ease.get(1)).to({x:411},5,cjs.Ease.get(1)).wait(27).to({y:15.5},5,cjs.Ease.get(1)).to({y:18.5},5,cjs.Ease.get(1)).wait(29).to({x:401},5,cjs.Ease.get(1)).to({x:501,alpha:0},5,cjs.Ease.get(1)).wait(5));

	// 2
	this.instance_2 = new lib.Символ20();
	this.instance_2.setTransform(87.5,49,1,1,0,0,0,123.5,15.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(5).to({_off:false},0).to({x:127.5,alpha:1},4,cjs.Ease.get(1)).to({x:117.5},5,cjs.Ease.get(1)).wait(31).to({y:46},5,cjs.Ease.get(1)).to({y:49},5,cjs.Ease.get(1)).wait(32).to({x:107.5},5,cjs.Ease.get(1)).to({x:207.5,alpha:0},5,cjs.Ease.get(1)).wait(3));

	// 1
	this.instance_3 = new lib.Символ17();
	this.instance_3.setTransform(63,18.5,1,1,0,0,0,99,15.5);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:103,alpha:1},4,cjs.Ease.get(1)).to({x:93},5,cjs.Ease.get(1)).wait(35).to({y:15.5},5,cjs.Ease.get(1)).to({y:18.5},5,cjs.Ease.get(1)).wait(35).to({x:83},5,cjs.Ease.get(1)).to({x:183,alpha:0},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-157.9,-88.7,311.9,122.8);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 3
	this.an3 = new lib.Символ27();
	this.an3.setTransform(229,19.5,1,1,0,0,0,187,19.5);
	this.an3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.an3).wait(179).to({_off:false},0).wait(101));

	// 2
	this.instance = new lib.Символ14();
	this.instance.setTransform(41.6,0,1.1,1.1,0,0,0,21.6,15.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(79).to({_off:false},0).to({_off:true},101).wait(100));

	// 1
	this.instance_1 = new lib.Символ9();
	this.instance_1.setTransform(383.4,32.9,1.05,1.05,0,0,0,371.4,32.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},80).wait(200));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-308.9,-100.6,14.7,14.7);


// stage content:



(lib.binarium_opciony_950x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		var _this = this;
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(link1, "_blank");
		}
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.knopka.addEventListener("mouseover", fl_MouseOverHandler_34);
		
		function fl_MouseOverHandler_34()
		{
		 _this.an.an3.btn.gotoAndPlay(1);
		}
		
		
		
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.knopka.addEventListener("mouseout", fl_MouseOutHandler_45);
		
		function fl_MouseOutHandler_45()
		{
		 _this.an.an3.btn.gotoAndPlay(5);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// ramka
	this.instance = new lib.Символ37();
	this.instance.setTransform(475,45,1,1,0,0,0,475,45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// knopka
	this.knopka = new lib.Символ36();
	this.knopka.setTransform(853,46.5,1,1,0,0,0,77,22.5);
	new cjs.ButtonHelper(this.knopka, 0, 1, 2, false, new lib.Символ36(), 3);

	this.timeline.addTween(cjs.Tween.get(this.knopka).wait(1));

	// logo
	this.instance_1 = new lib.Символ1();
	this.instance_1.setTransform(113.5,46,1,1,0,0,0,110.5,35);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// an
	this.an = new lib.Символ8();
	this.an.setTransform(666.4,60.2,1,1,0,0,0,371.4,32.9);

	this.timeline.addTween(cjs.Tween.get(this.an).wait(1));

	// m (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EhKNAHCIAAuDMCUbAAAIAAODg");
	mask.setTransform(475,45);

	// bg
	this.instance_2 = new lib.Символ3();
	this.instance_2.setTransform(522.5,232.6,1,1,0,0,0,575.5,383.5);

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(461.1,-28.3,964.5,164.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;