(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 305,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bg.jpg?1465822257691", id:"bg"},
		{src:"images/btn.png?1465822257691", id:"btn"},
		{src:"images/euro_logo.png?1465822257691", id:"euro_logo"},
		{src:"images/gold.png?1465822257691", id:"gold"},
		{src:"images/logo.png?1465822257691", id:"logo"},
		{src:"images/obj_03.png?1465822257691", id:"obj_03"},
		{src:"images/obj_06.png?1465822257691", id:"obj_06"},
		{src:"images/obj_10.png?1465822257691", id:"obj_10"},
		{src:"images/obj_15.png?1465822257691", id:"obj_15"},
		{src:"images/obj_18.png?1465822257691", id:"obj_18"}
	]
};



// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,436);


(lib.btn = function() {
	this.initialize(img.btn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,251,67);


(lib.euro_logo = function() {
	this.initialize(img.euro_logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,166,235);


(lib.gold = function() {
	this.initialize(img.gold);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,65,58);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,174,52);


(lib.obj_03 = function() {
	this.initialize(img.obj_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,83,72);


(lib.obj_06 = function() {
	this.initialize(img.obj_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,138,151);


(lib.obj_10 = function() {
	this.initialize(img.obj_10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,92,76);


(lib.obj_15 = function() {
	this.initialize(img.obj_15);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,164,173);


(lib.obj_18 = function() {
	this.initialize(img.obj_18);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,56,26);


(lib.Символ59 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDD00").s().p("AiIBxQgFAAgDgCQgDgDAAgGIAAi8QAAgHADgEQADgEAGgCQAMgFAQgCQAQgCARAAQARAAAMAEQANADAJAJQAHAHAEAMQAEAMAAAPIAAAmQABAOgFAMQgEAMgJAIQgJAJgNAEQgNAEgRAAQgLAAgNgDIAAA2QAAAGgCADQgCACgHAAgAhkhGQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAIAABNIAUABQAPAAAGgFQAHgFAAgMIAAgmQAAgLgHgFQgGgGgMAAQgLAAgLACgADcAvQgOgFgKgJQgIgJgEgMQgEgMgBgOIAAggQAAgQAFgNQAFgMAJgIQAJgJAOgEQANgEARAAQATAAANAEQAOAEAIAJQAKAJAEALQAFAMABAOIAAASQgBAIgEAEQgEAEgHAAIhVAAIAAAHQABAKAGAGQAHAGANAAQAKAAAIgDQAHgDAFgGQAEgEADgBQAEAAAGADIAPAFQAFADABAFQACAEgDAGQgFAHgGAFQgHAFgIAEQgIAEgKABQgKACgNAAQgSAAgNgEgADnhGQgGAFgBAMIAAAEIA2AAIAAgEQAAgMgGgFQgHgHgOAAQgNAAgHAHgAkSAvQgOgFgJgJQgIgJgFgMQgEgMAAgOIAAggQAAgQAFgNQAEgMAJgIQAJgJAOgEQAOgEARAAQASAAAOAEQANAEAJAJQAKAJAEALQAFAMAAAOIAAASQAAAIgFAEQgDAEgIAAIhUAAIAAAHQAAAKAHAGQAGAGAOAAQAKAAAHgDQAHgDAFgGQAEgEADgBQAEAAAHADIAOAFQAGADABAFQACAEgEAGQgEAHgHAFQgGAFgIAEQgJAEgJABQgLACgNAAQgSAAgNgEgAkGhGQgHAFAAAMIAAAEIA1AAIAAgEQAAgMgFgFQgIgHgNAAQgOAAgGAHgAGJAvQgGAAgDgDQgDgCABgHIAAhmIgjAAQgGAAgDgCQgBgCAAgHIAAgTQAAgGABgDQADgCAGAAIBzAAQAGAAADACQACADAAAGIAAATQAAAHgCACQgDACgGAAIgiAAIAABmQgBAHgCACQgDADgGAAgAB4AvQgHAAgCgDQgDgCAAgHIAAgtIguAAIAAAtQAAAHgDACQgDADgFAAIgYAAQgGAAgCgDQgDgCAAgHIAAiEQAAgGADgDQACgCAGAAIAYAAQAFAAADACQADADAAAGIAAAtIAuAAIAAgtQAAgGADgDQACgCAHAAIAXAAQAGAAACACQADADAAAGIAACEQAAAHgDACQgCADgGAAgAnNAvQgGAAgCgDQgDgCAAgHIAAiEQAAgGADgDQACgCAGAAIBJAAQALAAAKADQAJADAGAGQAGAGADAIQAEAIAAAKQAAAUgNALQAJAGAGAJQAEAKAAAKQAAAKgDAIQgEAJgHAFQgGAGgKAEQgJADgLAAgAmqALIAfAAQAIAAADgEQAEgDAAgFQAAgGgEgEQgDgDgIAAIgfAAgAmqgwIAcAAQAHAAADgEQAEgDAAgFQgBgGgDgDQgDgDgHAAIgcAAg");
	this.shape.setTransform(150.7,19);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AWbB0QgLgEgJgIQgHgIgFgLQgEgLAAgOIAAgoQAAgOAFgKQADgMAJgIQAIgIANgEQAMgFARAAQAPABANAEQAMAEAJAIQAIAJAFALQAEAKAAANIAAARQAAAJgJAAIhoAAIAAARQAAAKADAHQADAHAGAGQAGAFAIADQAJADAKAAQARAAAMgGQALgHAIgMQADgFAFADIAGADQAGADgDAGQgFAIgHAGQgGAGgHAEQgJAEgJACQgKACgMAAQgQAAgNgEgAWlgVQgIADgGAGQgGAGgDAGQgDAIAAAKIAAAKIBdAAIAAgKQAAgKgDgIQgDgGgGgGQgGgGgIgDQgKgDgKAAQgLAAgKADgAUBB0QgLgEgJgHQgIgIgDgLQgFgLAAgOIAAgsQAAgOAFgKQADgLAIgHQAJgHAMgEQANgFAPAAQANABAKACQAKACAIAFQAJAGAFAHQAFAHADALQACADgFADIgIADQgGABgCgGQgCgFgDgGQgFgFgEgEQgGgDgIgCQgGgBgKgBQgLABgJACQgHADgGAFQgGAFgDAHQgDAHAAAJIAAAuQABAJADAIQACAIAGAEQAGAGAIACQAIADALAAQAJAAAHgCQAHgCAGgDQAGgEAEgGQADgGACgHQADgFAFABIAIADQAGACgCAFQgDAKgHAJQgFAHgIAFQgIAGgKADQgLACgNAAQgPAAgNgEgAK9B2QgNgDgHgGQgHgGgEgJQgDgIAAgNQAAgMADgJQAFgJAHgFQAIgGANgDQAMgCASAAQAOAAAaADIAAgNQAAgKgDgHQgCgHgEgFQgGgGgHgCQgIgCgLgBQgPABgLAFQgKAFgGALQgDADgEgCIgIgBQgGgDAEgFQAQgfArgBQARAAALAFQAMADAHAIQAHAIAEALQADAIAAAPIAABPQgBAHgCAEQgCACgGADQgKAEgMACQgNACgPAAQgTAAgMgCgALHAtQgIADgGADQgFADgCAGQgCAGAAAHQAAAIACAGQACAGAEADQAGADAIACQAIACAMAAQAPAAAVgEQAGgDABgGIAAgsQgbgCgPAAQgMAAgIABgAp5BxQgMgDgIgHQgHgHgDgNQgFgMAAgTIAAhQIgeAAQgFgBAAgFIAAgIQAAgGAFAAIAeAAIAAggQAAgGAGAAIAKAAQAFAAABAGIAAAgIAuAAQAFAAAAAGIAAAIQAAAFgFABIguAAIAABPQAAAbAJAJQAFAFAIACQAJACAOAAQAFAAAAAGIAAAIQAAAGgFAAIgFAAQgQAAgLgDgARJB0QgGAAAAgGIAAiNQAAgFAGAAIBJAAQAKAAAIADQAIACAFAGQAGAEADAIQADAHAAAIQAAAMgFAIQgEAJgJAFQALAEAHAKQAFAKAAANQAAAKgCAIQgEAIgFAGQgHAFgIADQgIADgKAAgARXBjIA8AAQAMAAAHgIQAHgGABgNQgBgNgHgHQgHgHgNAAIg7AAgARXAcIA5AAQALAAAHgHQAGgGAAgMQABgKgHgGQgGgGgOAAIg3AAgAPIB0QgGAAAAgGIAAhSQAAgMADgXIAAAAQgFAKgKARIgjA+QgCAEgFABIgFAAQgFAAgCgFIgjg9QgIgNgHgPIgBAAQADAYAAANIAABQQAAAGgFAAIgIAAQgFAAAAgGIAAiNQgBgFAHAAIAGAAQAFAAADAEIA3BgIA3hgQACgEAFAAIAIAAQAGAAAAAFIAACNQAAAGgGAAgAIKB0QgFAAgBgGIAAiNQABgFAFAAIBJAAQAKAAAIADQAJACAFAGQAFAEADAIQAEAHAAAIQgBAMgEAIQgFAJgJAFQAMAEAGAKQAGAKAAANQAAAKgDAIQgEAIgFAGQgGAFgIADQgJADgKAAgAIYBjIA8AAQAMAAAHgIQAIgGAAgNQAAgNgIgHQgGgHgOAAIg7AAgAIYAcIA6AAQALAAAGgHQAHgGAAgMQAAgKgGgGQgHgGgNAAIg4AAgAsyBvQgMgDgJgJQgJgIgEgMQgEgMgBgOIAAgpQABgOAEgNQAFgMAIgIQAKgIANgGQAMgDARAAQARAAAOAEQAMAFAJAIQAJAIAEAMQAFANAAAMIAAARQAAAKgJgBIhtAAIAAATQAAAKACAIQADAIAHAGQAGAGAJACQAJADALAAQARAAAMgHQANgGAIgNQADgGAGAEIAGADQAGADgDAGQgFAIgHAHQgHAHgIAEQgJADgKADQgKACgMAAQgRAAgNgFgAsnggQgJADgHAGQgGAHgEAIQgCAIAAAJIAAALIBhAAIAAgLQAAgJgDgIQgDgIgHgHQgFgGgKgDQgJgCgMAAQgLAAgJACgAvYByQgNgDgKgEQgIgDgCgEQgDgEAAgGIAAjMQAAgFAGAAIAKAAQAGAAAAAFIAABHQAOgFANgCQAMgDAKABQAPAAANADQALAEAIAIQAHAHAFAMQADALAAAOIAAAtQAAAPgEANQgEANgJAHQgIAIgNAEQgNAEgQAAQgQAAgOgCgAvPgfQgLADgMAFIAABpQAAAGAFACIARAGIAUABQAMAAAKgDQAIgDAGgGQAGgFADgJQADgIAAgMIAAgrQAAgJgDgIQgDgIgFgGQgFgFgIgCQgIgDgLAAQgMAAgMACgA0uBwQgMgEgKgHQgIgIgFgLQgFgKAAgOIAAg3QAAgMAFgKQAFgLAIgHQAKgIAMgEQANgDAQAAQAQAAANADQANAEAJAIQAJAHAFALQAFAKgBAMIAAA3QABAOgFAKQgFALgJAIQgJAHgNAEQgNAEgQAAQgQAAgNgEgA0lgfQgIACgHAGQgGAFgDAHQgEAIAAAGIAAA3QABAJADAIQADAHAHAFQAFAFAJACQAJADALAAQALAAAJgDQAJgCAGgFQAGgFAEgHQADgIAAgJIAAg3QAAgGgDgIQgEgHgGgFQgGgGgJgCQgJgCgLAAQgLAAgJACgAwzBvQgFAAAAgEIAAhjQAAgJgDgIQgDgIgFgGQgGgFgIgCQgIgDgLAAIgWABQgKACgKAEQgEADAAAFIAAB9QgBAEgFAAIgKAAQgGAAgBgEIAAiEQABgHACgDQACgDAIgEQAMgFAQgDQAOgDARABQAPAAALADQANAEAHAIQAIAHAEAMQAEALAAAOIAABkQAAAEgGAAgA31BvQgGAAAAgFIAAjSQAAgFAGAAIB/AAQAGAAAAAFIAAAJQAAAHgGAAIhvAAIAABRIBgAAQAGAAAAAHIAAAGQAAAHgGgBIhgAAIAABeQABAFgHAAg");
	this.shape_1.setTransform(153.3,12.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,306.5,30.4);


(lib.Символ58 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDD00").s().p("AqCBtQgGAAgCgCQgDgDAAgGIAAi1QAAgGADgEQACgEAHgCQAMgEAPgDQAOgCARAAQAQAAAMAEQAMAEAJAHQAHAIAEALQAEAMAAAOIAAAkQAAAOgEALQgFAMgIAIQgJAIgMAFQgMADgRAAQgKAAgNgCIAAAzQAAAGgDADQgBACgHAAgApghDQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABAAAAIAABKIATABQAOAAAHgGQAGgEAAgMIAAgkQAAgKgGgGQgHgFgLAAQgLAAgKACgAzfBtQgGAAgCgCQgCgDgBgGIAAi1QABgGACgEQACgEAIgCQALgEAPgDQAOgCASAAQAQAAAMAEQAMAEAIAHQAHAIAFALQADAMAAAOIAAAkQAAAOgEALQgEAMgJAIQgIAIgMAFQgNADgQAAQgLAAgNgCIAAAzQABAGgDADQgCACgGAAgAy8hDQAAAAgBAAQAAABAAAAQAAAAAAAAQgBABAAAAIAABKIAUABQAOAAAGgGQAGgEAAgMIAAgkQAAgKgGgGQgGgFgMAAQgLAAgJACgANRAvQgNgDgHgGQgIgGgDgJQgEgJABgMQgBgMAEgJQAEgJAIgFQAIgGANgCQAMgDATAAIAUABIAAgHQABgKgGgGQgFgGgMABQgIAAgGADQgGACgEAGIgGAFQgDACgFgDIgQgGQgGgDgCgEQgBgDACgGQAFgIAFgFQAHgGAHgEQAIgEAKgBQAJgCALAAQARAAAMAEQAMADAIAIQAIAHAFAMQADAMAAAPIAABIQAAAHgCAEQgCADgHACQgRAJgmgBQgSAAgNgCgANegHQgEADAAAFQAAAHAEAEQAFADALAAIAWgBQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIAAgWIgYgBQgLAAgFAEgAI1AuQgMgFgJgHQgIgIgEgMQgFgLABgNIAAglQgBgOAFgMQAEgMAJgHQAJgIAMgEQANgEARAAQANAAAKADQALACAIAGQAIAEAGAHQAFAIADAJQACAFgBAEQgCADgGACIgTAGQgGADgDgCQgEgBgCgHQgDgHgGgEQgGgDgJAAQgXgBAAAWIAAApQAAAUAXgBQAJAAAGgDQAGgEADgFQACgGAEgBQADgCAGACIATAFQAGADACACQACADgCAGQgFAKgGAHQgGAHgIAFQgJAEgKADQgLADgMgBQgRAAgMgDgAFeAtQgNgFgIgIQgJgJgEgMQgEgLAAgNIAAgfQAAgQAEgLQAFgMAJgJQAIgIANgEQANgEASAAQAQAAAOAEQANAEAIAJQAKAIAEAMQAFAKgBAOIAAARQAAAIgDADQgEAFgIAAIhQAAIAAAHQgBAJAHAGQAGAGAOgBQAJAAAHgCQAHgDAFgGQADgEADgBQAEAAAGADIAOAFQAGADABAEQABAEgDAGQgEAHgHAFQgGAFgHADQgJAEgJACQgKABgMAAQgRABgOgFgAFqhEQgHAGABALIAAAEIAzAAIAAgEQAAgLgGgGQgGgFgNgBQgOABgGAFgAwoAuQgNgFgJgIQgIgIgFgLQgFgLAAgNIAAglQAAgOAFgMQAFgLAIgIQAJgIANgEQANgEAQAAQARAAANAEQANAEAKAIQAIAIAEALQAFAMAAAOIAAAlQAAANgFALQgEAMgIAHQgKAIgNAFQgNADgRAAQgQAAgNgDgAwkgwIAAAnQAAAUAZAAQANgBAHgFQAGgFAAgJIAAgnQAAgLgGgFQgHgGgNABQgZAAAAAVgAVpAtQgGAAgDgDQgDgCABgGIAAgjQgBgUAJgbIgCAAQgFANgLAVIgkA1QgFAGgGAAIgXAAQgGAAgCgDQgDgCABgGIAAh/QgBgGADgDQACgCAGAAIAXAAQAFAAADACQADADAAAGIAAAlQgDAegFASIABAAQAFgPAMgSIAkg5QAEgGAHAAIAWAAQAGAAACACQADADAAAGIAAB/QAAAGgDACQgCADgGAAgATTAtQgJAAgEgCQgDgBgDgHIgPgjQgCgFgFgCQgFgDgGAAIgLAAIAAAsQAAAGgCACQgDADgGAAIgVAAQgGAAgDgDQgCgCAAgGIAAh/QAAgGACgDQADgCAGAAIAVAAQAGAAADACQACADAAAGIAAAsIAIAAIAhguQADgGAFgCQADgBAJAAIAUAAQAIAAACADQACAEgFAGIgmA1QAJAGAHAPIAZAxQADAHgBADQgCADgHAAgAPXAtQgGAAgCgDQgCgCgBgGIAAh/QABgGACgDQACgCAGAAIBGAAQALAAAJADQAJADAFAGQAGAFAEAJQACAHAAAKQAAATgMALQAKAFAFAJQAEAJAAAKQAAAJgDAJQgEAHgGAGQgGAGgJADQgKADgKAAgAP4ALIAfAAQAGgBAEgDQADgDAAgFQAAgGgDgDQgEgDgGgBIgfAAgAP4guIAcAAQAGAAADgEQAEgDAAgFQgBgFgDgEQgDgCgGAAIgcAAgALXAtQgGAAgDgDQgCgCAAgGIAAhiIgiAAQgFAAgDgDQgCgBAAgHIAAgSQAAgGACgDQADgCAFAAIBvAAQAFAAADACQACADAAAGIAAASQAAAHgCABQgDADgFAAIghAAIAABiQAAAGgDACQgCADgHAAgAD+AtQgGAAgCgDQgCgCAAgGIAAh/QAAgGACgDQACgCAGAAIAXAAQAGAAADACQABADAAAGIAAB/QAAAGgBACQgDADgGAAgAByAtQgGAAgCgDQgCgCAAgGIAAh/QAAgGACgDQACgCAGAAIAXAAQAGAAACACQADADAAAGIAAAeIAfAAQAMAAALAEQAKAEAIAGQAHAIAEAKQAEAKAAANQAAALgEAKQgEAKgHAHQgIAIgKADQgLAEgMAAgACUAIIAYAAQAIgBAFgEQAFgDAAgIQAAgIgFgFQgFgEgIAAIgYAAgAAqAtQgGAAgDgDQgCgCAAgGIAAgsIgrAAIAAAsQAAAGgDACQgCADgGAAIgWAAQgHAAgCgDQgCgCAAgGIAAh/QAAgGACgDQACgCAHAAIAWAAQAGAAACACQADADAAAGIAAArIArAAIAAgrQAAgGACgDQADgCAGAAIAWAAQAGAAACACQACADAAAGIAAB/QAAAGgCACQgCADgGAAgAkPAtQgGAAgCgDQgCgCAAgGIAAh/QAAgGACgDQACgCAGAAIAXAAQAFAAADACQADADAAAGIAABiIAgAAIAAhiQAAgGACgDQADgCAFAAIAXAAQAHAAACACQACADAAAGIAABiIAhAAIAAhiQAAgGACgDQACgCAGAAIAWAAQAHAAACACQACADAAAGIAAB/QAAAGgCACQgCADgHAAgAlYAtQgFAAgDgDQgCgCAAgGIAAh/QAAgGACgDQADgCAFAAIAXAAQAGAAACACQACADAAAGIAAB/QAAAGgCACQgCADgGAAgAnkAtQgGAAgCgDQgCgCAAgGIAAh/QAAgGACgDQACgCAGAAIAXAAQAGAAACACQACADABAGIAAAeIAeAAQANAAALAEQAKAEAIAGQAHAIAEAKQAEAKAAANQAAALgEAKQgEAKgHAHQgIAIgKADQgLAEgNAAgAnCAIIAYAAQAIgBAFgEQAFgDAAgIQAAgIgFgFQgFgEgIAAIgYAAgAr/AtQgGAAgCgDQgCgCAAgGIAAh/QAAgGACgDQACgCAGAAIBWAAQAHAAACACQACADAAAGIAAASQAAAHgCABQgCADgHAAIg1AAIAABiQAAAGgCACQgDADgFAAgAtHAtQgHAAgCgDQgDgCAAgGIAAgjQABgUAHgbIgBAAQgFANgMAVIgkA1QgEAGgGAAIgXAAQgGAAgCgDQgDgCAAgGIAAh/QAAgGADgDQACgCAGAAIAXAAQAFAAADACQACADAAAGIAAAlQgCAegFASIACAAQAFgPAKgSIAkg5QAFgGAHAAIAWAAQAGAAACACQADADAAAGIAAB/QAAAGgDACQgCADgGAAgA0nAtQgGAAgCgDQgCgCgBgGIAAhiIgrAAIAABiQAAAGgDACQgCADgGAAIgWAAQgHAAgBgDQgDgCAAgGIAAh/QAAgGADgDQABgCAHAAIBuAAQAGAAACACQADADgBAGIAAB/QABAGgDACQgCADgGAAg");
	this.shape.setTransform(141.9,11);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,283.7,21.9);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Eg5PAclMAAAg5JMByfAAAMAAAA5Jg");
	this.shape.setTransform(366.5,183);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,733,366);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjbJ2IAAzrIG3AAIAATrg");
	this.shape.setTransform(22,63);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,44,126);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.btn();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,251,67);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ai/IxIAAxhIF/AAIAARhg");
	this.shape.setTransform(19.3,56.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,38.5,112.3);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghBXQgGAAgDgCQgCgCAAgGIAAgVIg0AAIAAAVQAAAGgCACQgCACgGAAIgjAAQgGAAgDgCQgCgCAAgGIAAg8QAAgFACgDQADgCAGAAIADAAQAFgGACgFQADgIAAgMIAAgwQAAgGACgCQACgCAGAAIBlAAQAGAAADACQACACAAAGIAABPIAGAAQAFAAACACQADADAAAFIAAA8QAAAGgDACQgCACgFAAgAhLgZQgCAYgDAIIARAAIAAgoIgMAAgAA5AzQgMgEgJgHQgJgJgEgKQgEgMAAgLIAAgZQAAgOAEgLQAEgLAJgIQAJgHAMgEQANgEAPAAQARAAAMAEQANAEAJAHQAIAIAEALQAFALAAAOIAAAZQAAAMgFALQgEAKgIAJQgJAHgNAEQgMAEgRAAQgPAAgNgEgABOgkQgCACAAAFIAAAdQAAADACACQADACAEgBQAGABACgCQADgCAAgDIAAgdQAAgJgLAAQgEAAgDACg");
	this.shape.setTransform(15.3,8.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,30.7,17.5);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3FA1DA").s().p("AA6BbIgNgGIgLgIQgFgFgEgFIgGgMQgEgJgBgVIAAgyQAAgKAFgTIAGgMQAEgFAFgFIALgIIANgGQAJgDAYgCQALAAAVAFIANAGIALAIIAJAKIAGAMQAFATAAAKIAAAyQgCAVgDAJIgGAMIgJAKIgLAIIgNAGQgVAFgLAAQgYgCgJgDgABOgnQgEAEAAAHIAAA5QAAAHAEAEQAFADAIAAQAHAAAFgDQAEgEAAgHIAAg5QAAgHgEgEQgFgDgHAAQgIAAgFADgAhuBbIgNgGIgLgIQgFgFgEgFIgGgMQgEgJgBgVIAAgyQAAgKAFgTIAGgMQAEgFAFgFIALgIIANgGQAJgDAYgCQALAAAVAFIANAGIALAIIAJAKIAGAMQAFATAAAKIAAAyQgCAVgDAJIgGAMIgJAKIgLAIIgNAGQgVAFgLAAQgYgCgJgDgAhagnQgEAEAAAHIAAA5QAAAHAEAEQAFADAIAAQAHAAAFgDQAEgEAAgHIAAg5QAAgHgEgEQgFgDgHAAQgIAAgFADgAkMBdQgNgCgKgFQgJgGgHgIQgHgIgEgLQgCgGABgDQACgEAGgCIAjgNQAFgDADACQAEABACAGQACAGAFADQAFACAHAAQAHAAAEgDQADgEAAgHQAAgHgEgDQgEgDgJAAIg2AAQgHAAgDgEQgCgDAAgHIAJhMQABgJADgEQAEgDAKAAIBjAAQAGAAADACQACADAAAGIAAAdQAAAHgCACQgDADgGAAIg9AAIgBAJIALAAQAMAAATAFQAOAEAIAJQAJAIAEAKQAFALAAAPQAAAOgFAMQgFALgKAJQgJAJgOAEQgNAFgRAAQgRAAgMgDgAEXBcQgKAAgEgCQgEgDgCgGIgKgfQgCgFgEAAIgCAAIAAAkQAAAGgDACQgCADgFAAIglAAQgGAAgCgCQgCgDAAgGIAAhwQAAgGACgCQACgCAGAAIAlAAQAFAAACACQADACAAAGIAAAgIAEAAIAPggQACgGAEgCQAEgCAIAAIAdAAQAIAAADADQACAEgDAHIgYAzIAZA1QAEAHgCAEQgDAEgIAAg");
	this.shape.setTransform(32.1,9.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,64.2,19.3);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhpBdIgCgFQgBAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAKgEAGgIQAFgGACgHQAFgdAAgZIAAgrQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAIBTAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAABIAAB9QAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgFAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAgBIAAh2IhEAAIAAAkQAAAYgCARQgDARgFAJQgFAJgFAFQgFAEgIAEIgCAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBgABCBdQgLgDgGgFQgFgEgDgIQgEgHAAgLQAAgLAEgHQACgHAIgFQAGgFALgCQALgCAPAAIAmADIAAgOQAAgIgBgHQgDgIgEgFQgFgFgIgDQgHgDgMAAIgNACIgLAEQgFADgEAEQgEAEgDAGQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAIgDgCQgBAAgBAAQAAgBgBAAQAAgBAAgBQAAAAABgBQADgHAGgFQAFgFAGgEQAGgDAIgCQAIgCAJAAQAOAAAKAEQAKADAGAHQAFAHADAJQACAJAAAKIAABEQAAAHgBADQgCADgGACQgHAEgLABQgKACgNAAQgQAAgLgCgABIAbQgIACgFADQgGAEgCAFQgCAGAAAIQAAAIACAGQACAFAFAEQAFAEAIACQAJACAMAAIATgCIAPgEIAFgDIABgGIAAgrIgngDQgMAAgJACgAkKBdQgKgDgHgFQgFgEgDgIQgDgHAAgLQAAgLADgHQADgHAHgFQAHgFALgCQAKgCAPAAIAnADIAAgOQAAgIgCgHQgCgIgEgFQgGgFgHgDQgIgDgLAAIgNACIgLAEQgGADgEAEQgEAEgCAGQgBAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgEgCQgBAAAAAAQgBgBAAAAQAAgBAAgBQAAAAABgBQADgHAFgFQAFgFAHgEQAFgDAIgCQAIgCAJAAQAOAAALAEQAKADAFAHQAFAHAEAJQACAJAAAKIAABEQAAAHgCADQgCADgFACQgIAEgKABQgLACgNAAQgQAAgLgCgAkDAbQgJACgFADQgFAEgCAFQgCAGgBAIQABAIACAGQACAFAEAEQAFAEAJACQAIACAMAAIATgCIAQgEIAFgDIABgGIAAgrIgogDQgMAAgIACgAFGBbQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAh9QAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAIBBAAQAJAAAGACQAGADAFAEQAFAEACAHQACAGAAAIQAAATgQAJQAVAHABAaQgBAJgCAGQgDAHgEAFQgFAEgHADQgHACgIAAgAFOBSIA7AAQAGAAAFgCQAFgCAEgEQAEgDABgFQACgFAAgHQAAgGgCgFQgCgFgDgEQgEgDgFgCQgFgCgHAAIg6AAgAFOASIA4AAQAMAAAGgHQAEgDACgFQACgDgBgGQABgGgCgEQgCgFgDgDQgDgDgFgCQgFgBgHAAIg3AAgAEWBbQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAhWQAAgMACgOIgBAAIhZBxQAAABAAAAQAAABgBAAQAAAAgBAAQAAAAAAAAIgGAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAh9QAAgBAAAAQAAgBAAAAQABAAAAAAQABgBAAAAIAGAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAABWQAAAOgBANIABAAIBYhzIACgBIAGAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABIAAB9QAAABgBABQAAAAAAABQAAAAgBAAQAAAAgBAAgAlLBbQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAg8IhWAAIAAA8QAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgGAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBgBgBIAAh9QABgBAAAAQAAgBAAAAQABAAAAAAQABgBAAAAIAGAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAA3IBWAAIAAg3QAAgBAAAAQAAgBABAAQAAAAABAAQABgBAAAAIAGAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABIAAB9QAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAgADChZQgBgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAEgCQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQADAMAHAGQAIAGAMAAQAMAAAHgGQAHgGADgMQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAEACQABAAAAAAQAAABAAAAQABABAAAAQAAAAgBABQgIAdgeAAQgfAAgIgdg");
	this.shape.setTransform(43.2,9.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,86.4,19.2);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aj+BCIgDgFQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAKgEAGgIQAFgGACgHQAGgdgBgXIAAgtQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIBUAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAB9QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgFAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAh2IhFAAIAAAmQAAAWgCARQgDARgFAJQgFAJgGAFQgFAEgHAEIgCAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBgAGyBAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhUQAAgOACgOIAAAAIhZBxQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgFAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAh9QAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABWQAAAOgBANIAAAAIBZhzIACgBIAGAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAB9QAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAgAEgBAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhUQAAgOACgOIAAAAIhZBxQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgFAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAh9QAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABWQAAAOgBANIAAAAIBYhzIADgBIAFAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAB9QAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgACPBAQgBAAgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAg8IhVAAIAAA8QAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAIgEAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAh9QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAEAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAA5IBVAAIAAg5QAAgBAAAAQAAgBABAAQAAgBABAAQABAAABAAIAEAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAB9QAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAgAgBBAQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAhUQAAgOACgOIAAAAIhZBxQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgEAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAh9QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAEAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABWQAAAOgBANIAAAAIBZhzIACgBIAEAAQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAB9QAAABAAAAQAAABAAAAQAAABgBAAQAAAAgBAAgAm2BAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAh9QAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIBAAAQAJAAAHACQAGADAFAEQAFAEACAHQACAGAAAIQAAAVgRAJQAWAFAAAaQAAAJgDAGQgCAHgFAFQgEAEgIADQgGACgJAAgAmuA3IA6AAQAHAAAFgCQAFgCADgEQAEgDABgFQACgFAAgHQAAgGgCgFQgCgFgDgEQgDgDgGgCQgFgCgHAAIg5AAgAmugHIA4AAQAMAAAGgHQADgDADgFQABgFAAgGQAAgGgBgEQgDgFgCgDQgEgDgFgCQgFgBgGAAIg3AAg");
	this.shape.setTransform(44.3,6.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,88.5,13.7);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghBXQgGAAgDgCQgCgCAAgGIAAgVIg0AAIAAAVQAAAGgCACQgCACgGAAIgjAAQgGAAgDgCQgCgCAAgGIAAg8QAAgFACgDQADgCAGAAIADAAQAFgGACgFQADgIAAgMIAAgwQAAgGACgCQACgCAGAAIBlAAQAGAAADACQACACAAAGIAABPIAGAAQAFAAACACQADADAAAFIAAA8QAAAGgDACQgCACgFAAgAhLgZQgCAYgDAIIARAAIAAgoIgMAAgAA5AzIgCAAQgLgFgIgGQgJgJgEgKQgEgMAAgLIAAgZQAAgOAEgLQAEgLAJgIQAJgHAMgEQANgEAPAAQARAAAMAEQANAEAJAHQAIAIAEALQAFALAAAOIAAAZQAAAMgFALQgEAKgIAJIgDACQgIAGgLADQgMAEgRAAQgPAAgNgEgABOgkQgCACAAAFIAAAdQAAADACACQADACAEgBQAGABACgCQADgCAAgDIAAgdQAAgJgLAAQgEAAgDACg");
	this.shape.setTransform(15.3,8.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,30.7,17.5);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3FA1DA").s().p("AAzBdQgEgBgCgFIgRgdQgEgHAIgFIAJgHQADgEADgLQADgKAAgQIAAgfQAAgGACgCQACgCAGAAIBiAAQAGAAACACQACACAAAGIAABwQAAAGgCACQgCADgGAAIgkAAQgGAAgCgDQgDgCAAgGIAAhLIgKAAIAAAFQgCAhgEALQgCAIgDAGQgEAGgEAEQgGAGgGADIgMAHIgFABIgCgBgAEHBaQgGAAgCgDQgCgCAAgGIAAghIgPAAIAAAhQAAAGgCACQgCADgGAAIglAAQgFAAgCgCQgDgDAAgGIAAhwQAAgGADgCQACgCAFAAIAlAAQAGAAACACQACACAAAGIAAAfIAPAAIAAgfQAAgGACgCQACgCAGAAIAkAAQAGAAACACQACACAAAGIAABwQAAAGgCADQgCACgGAAgAgXBaQgFAAgDgDQgDgDAAgFIABgWIAJgmIgCAAQgFAQgEAGIgHAQQgCAFgDACQgDABgGAAIgOAAQgFAAgDgBQgDgCgCgFIgOgiIgBgEIgCAAIAIAhIABAbQAAAFgDADQgDADgFAAIgdAAQgHAAgCgCQgCgCAAgHIAAhvQAAgHADgCQACgCAHAAIAdAAQAGAAADABQADACADAFIAXAsIAYgsQADgFACgCQADgBAGAAIAdAAQAHAAACACQACACAAAHIAABvQAAAGgCADQgCACgGAAgAj8BaQgGAAgDgDQgDgCAAgHIAAhdIgKAGQgGADgEgBQgEgBgDgGIgQgcQgCgFABgEQABgDAGgDIA2gfQAIgFAIAAIAQAAQAHAAACADQADACAAAHIAACfQAAAHgDACQgCADgHAAg");
	this.shape.setTransform(31,9.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,62,18.9);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.euro_logo();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,166,235);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.btn();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,251,67);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AM3BaIgOgGIgMgIIgJgLQgFgGgCgHIgFgPIgBgRIABg4IAFgPQACgHAFgGIAJgLQAFgFAHgDQAGgEAIgDQAKgDAZgCQANAAAWAFQAIADAGAEQAHADAFAFQAFAFAEAGIAHANIAFAPIABA4IgBARIgFAPIgHANQgEAGgFAFIgMAIIgOAGQgWAGgNAAQgZgCgKgEgANJgmQgFAFAAAKIAAAvQAAAKAFAEQAGAFALAAQALAAAGgFQAFgEABgKIAAgvQgBgKgFgFQgGgEgLAAQgLAAgGAEgAHXBaIgOgGQgGgDgFgFIgJgLIgHgNIgFgOIgBh1QAAgHADgCQADgDAGAAIAmAAQAFAAADADQACACAAAHIAABoQAAATAWAAQAVAAAAgTIAAhoQAAgHACgCQADgDAHAAIAkAAQAHAAACADQADACAAAHIAABkIgCARIgDAOQgDAHgEAGIgJALQgFAFgGADIgPAGQgVAGgNAAQgZgCgKgEgAB4BdQgMgCgIgFQgGgFgEgJQgDgIAAgMQAAgMADgJQAFgJAHgFQAHgEANgCQANgDARAAIAGAAIAAgHQgBgGgIAAQgGAAgCADIgEACIgBABQgDAEgCABQgEAAgGgCIgYgHQgFgDgBgEQgBgDACgFQADgHAGgFQAFgFAIgEQAIgDAJgCQAKgBALAAQAQAAAMADQAMAEAIAHQAHAIAEAKQADALABAMIAAA+QgBAHgBADQgDAEgFACQgKAEgNACQgNACgSAAQgSAAgNgDgACQAuQgCACAAAEQAAAIAJAAIAGAAIABgBIAAgQIgHAAQgEAAgDADgAp/BdQgMgCgHgFQgHgFgDgJQgEgIAAgMQAAgMAEgJQAEgJAIgFQAHgEAMgCQANgDASAAIAFAAIAAgHQAAgGgJAAQgFAAgDADIgDACIgBABQgDAEgDABQgDAAgHgCIgXgHQgFgDgBgEQgCgDADgFQADgHAGgFQAFgFAHgEQAIgDAJgCQAKgBAMAAQAQAAAMADQAMAEAIAHQAHAIADAKQAEALAAAMIAAA+QAAAHgCADQgCAEgGACQgJAEgNACQgNACgTAAQgSAAgNgDgApmAuQgCACgBAEQABAIAIAAIAGAAIABgBIAAgQIgGAAQgFAAgCADgAuJBcQgLgEgJgIQgHgHgEgLQgEgMAAgOIAAgYQAAgMAEgLQAFgLAHgIQAJgHANgEQAMgEARAAQAMAAAJACQAKADAIAFQAHAFAGAHQAFAHADAIQACAGgBACQgCADgGACIggAKQgGACgDgBQgDgCgCgGQgEgIgGAAQgHAAAAAJIAAAeQAAAKAHAAQAGAAAEgIQACgHADgBQADgBAGACIAhAJQAGACACAEQABAEgCAFQgEAKgGAHQgGAHgIAEQgIAFgKACQgKADgMAAQgQAAgNgEgALRBcQgKAAgGgEQgGgDgEgIIgOgfQgDgGgEgDQgCgDgFAAIgBAAIAAAuQAAAHgCACQgCADgHAAIglAAQgHAAgCgDQgDgCAAgHIAAifQAAgHADgCQACgDAHAAIBLAAQAQAAAMAEQAOAFAIAIQAJAJAEAMQAGAMAAAPQgBAKgBAIIgFAMQgEAHgEAGQgFAFgGAEIAIANIAUAmQAEAGgDAFQgCAEgHAAgAKagMIAUAAQAGAAAEgEQADgEAAgGQAAgGgDgDQgDgEgHAAIgUAAgAEcBcQgGAAgDgDQgDgCAAgHIAAifQAAgHADgCQADgDAGAAIBxAAQAGAAADADQADACAAAHIAAAdQAAAGgDADQgDACgGAAIhBAAIAAAOIAzAAQAGAAADACQACADAAAGIAAAbQAAAHgCACQgDADgGAAIgzAAIAAAOIBDAAQAGAAADADQACADABAGIAAAdQgBAHgCACQgDADgGAAgAAbBcQgFAAgDgDQgCgCAAgGIAAghIgOAAIAAAhQAAAGgDACQAAADgFAAIglAAQgFAAgDgCQgCgDAAgGIAAhwQAAgGACgCQADgCAFAAIAlAAQAFAAAAACQADACAAAGIAAAfIAOAAIAAgfQAAgGACgCQADgCAFAAIAlAAQAGAAACACQACACAAAGIAABwQAAAGgCADQgCACgGAAgAicBcQgHAAgCgDQgCgCAAgGIAAgJQACgZAFgVIgCAAIgTA6QgDAIgJAAIglAAQgFAAgCgDQgDgCAAgGIAAhwQAAgGADgCQACgCAFAAIAlAAQAGAAACACQADACAAAGIAAAJQgDAWgFAXIACAAIAUg4QACgIAKAAIAkAAQAGAAACACQACACAAAGIAABwQAAAGgCACQgCADgGAAgAkkBcQgKAAgEgCQgFgDgCgGIgKgfQgBgFgFAAIgCAAIAAAkQABAGgDACQgCADgGAAIglAAQgFAAgCgCQgDgDABgGIAAhwQgBgGADgCQACgCAFAAIAlAAQAGAAACACQADACgBAGIAAAgIAFAAIAOggQADgGAEgCQADgCAJAAIAdAAQAIAAADADQACAEgDAHIgYAzIAZA1QAEAHgDAEQgCAEgIAAgAoHBcQgFAAgDgDQgCgCAAgGIAAhwQAAgGACgCQADgCAFAAIBFAAQALAAAIACQAIADAGAFQAGAFADAHQADAHAAAJQAAAPgKAJQAHAFAEAIQAEAIAAALQAAAJgDAHQgDAHgGAFQgGAGgJACQgJADgLAAgAnaA6IAHAAQAFAAADgCQADgDgBgEQABgFgDgCQgDgDgFAAIgHAAgAnaAHIAGAAQAIAAAAgHQAAgIgIAAIgGAAgAr5BcQgFAAgCgDQgDgCAAgGIAAhLIgZAAQgFAAgDgDQgCgCAAgEIAAgcQAAgGACgCQADgCAFAAIBrAAQAGAAACACQADACAAAGIAAAcQAAAEgDACQgCADgGAAIgZAAIAABLQAAAGgCACQgDADgFAAg");
	this.shape.setTransform(94.2,9.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,188.3,19.3);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEDB31").s().p("An5BaIgNgGIgMgIIgJgLQgFgGgCgHIgFgPIgBgRIAAgnIABgRIAFgPQACgHAFgGIAJgLQAFgFAHgDQAGgEAHgDQALgDAZgCQAPAAANADQAMADAKAGQAKAGAHAJQAIAJADAMQADAGgCADQgBADgHACIgjANQgHABgCgBQgDgCgCgGQgDgIgFgDQgFgDgJAAQgNAAgFAFQgEAFAAAMIAAApQAAAMAEAFQAFAFANAAQARAAAFgOQACgHADgBQADgCAGACIAjANQAHACABADQACAEgDAGQgDALgIAJQgHAJgKAGQgKAGgMADQgNADgPAAQgZgCgLgEgADeBfQgDgBgDgGIgVgiQgCgGABgDQABgDAGgEQAHgEAFgGQAGgFADgGQADgGACgJQABgHAAgMIAAg+QAAgHACgCQADgDAGAAIB1AAQAHAAACADQADACAAAHIAACfQAAAHgDACQgCADgHAAIglAAQgHAAgCgDQgDgCABgHIAAh3IgVAAIAAAWQAAAtgOAaQgHAMgLAKQgKAKgPAIIgFABIgDAAgAPjBcQgHAAgCgDQgCgCgBgHIAAifQABgHACgCQACgDAHAAIBxAAQAHAAACADQADACgBAHIAAAdQABAGgDADQgCACgHAAIhAAAIAAAOIAxAAQAHAAACACQADADAAAGIAAAbQAAAHgDACQgCADgHAAIgxAAIAAAOIBCAAQAGAAADADQACADAAAGIAAAdQAAAHgCACQgDADgGAAgAORBcQgGAAgDgDQgBgCAAgGIAAihQAAgGABgCQADgDAGAAIAoAAQAFAAACADQADACAAAGIAAChQAAAGgDACQgCADgFAAgALtBcQgHAAgCgDQgDgCAAgHIAAifQAAgHADgCQACgDAHAAIAlAAQAGAAACADQADACAAAHIAAAnIAaAAQAQAAANAFQAMAEAKAIQAJAJAEAMQAGALAAAPQAAAQgGANQgFAMgIAJQgKAJgNAEQgNAFgQAAgAMdAoIASAAQAHAAAFgEQADgFAAgGQAAgHgDgEQgFgEgHAAIgSAAgAKcBcQgHAAgCgDQgDgCAAgHIAAg4IgnAAIAAA4QAAAHgCACQgCADgHAAIglAAQgGAAgDgDQgCgCAAgHIAAigQAAgGACgDQADgCAGAAIAlAAQAHAAACACQACADAAAGIAAA2IAnAAIAAg2QAAgGADgDQACgCAHAAIAlAAQAGAAADACQACADAAAGIAACgQAAAHgCACQgDADgGAAgAGPBcQgHAAgCgDQgDgCABgHIAAifQgBgHADgCQACgDAHAAIAlAAQAHAAACADQACACAAAHIAAAnIAaAAQARAAANAFQAMAEAJAIQAKAJAEAMQAFALAAAPQAAAQgFANQgFAMgJAJQgJAJgNAEQgNAFgQAAgAG/AoIASAAQAIAAAEgEQADgFAAgGQAAgHgDgEQgEgEgIAAIgSAAgACWBcQgJAAgFgDQgEgDgCgGIgDgOIgxAAIgEAOQgCAGgDADQgEADgJAAIgkAAQgHAAgBgDQgCgDACgFIA6iiQACgGADgCQACgCAHAAIAmAAQAHAAACACQAEACACAFIA6CjQABAFgBADQgCADgGAAgAByATIgFgTQgFgNAAgRIgBgFIgCAAQgBAYgDALIgGATIAXAAgAgvBcQgGAAgDgDQgCgCAAgGIAAgQQAAgRACgQQAEgRAIgaIgDAAIgaA+QgDAHgKAAIgXAAQgEAAgDgCQgDgBgCgEIgZg+IgDAAQAIAfADAPQACAPAAAPIAAAQQAAAGgDACQgCADgHAAIgiAAQgHAAgCgDQgCgCgBgGIAAihQABgGACgDQACgCAHAAIAgAAQAGAAAEABQADACADAFIAmBRIAmhRQADgFADgCQADgBAGAAIAhAAQAHAAACACQABADAAAGIAAChQAAAGgBACQgCADgHAAgAkHBcQgGAAgDgDQgCgCAAgHIAAgeQAAgSABgJIAKglIgCAAQgRAogHANIgZAwQgCAFgJAAIgoAAQgHAAgCgDQgDgCAAgHIAAifQAAgHADgCQACgDAHAAIAlAAQAGAAACADQADACAAAHIAAAeQAAAVgCALQgCAMgHAUIACAAQAUgtAFgJIAYgvQACgFAJAAIAoAAQAHAAACACQADADAAAGIAACgQAAAHgDACQgCADgHAAgApbBcQgLAAgEgDQgGgCgDgHIgWgsQgFgLgFAAIgDAAIAAA3QAAAHgCACQgCADgGAAIgmAAQgGAAgDgDQgDgCAAgHIAAifQAAgHADgCQADgDAGAAIAmAAQAGAAACADQACACAAAHIAAA1IADABIADAAIAdg3QADgHAEgCQADgCAKAAIAlAAQAHAAABAEQACADgDAGIgpBOIAJALIAjBCQAEAGgDAFQgCAEgHAAgAsHBcQgJAAgFgDQgEgDgCgGIgDgOIgxAAIgEAOQgCAGgDADQgEADgJAAIgkAAQgHAAgCgDQgBgDACgFIA6iiQACgGADgCQACgCAHAAIAmAAQAHAAACACQAEACACAFIA6CjQABAFgBADQgCADgGAAgAsrATIgFgTQgFgNAAgRIgBgFIgCAAQgBAYgDALIgGATIAXAAgAvOBcQgGAAgDgDQgCgCAAgGIAAgQQAAgRACgQQAEgRAIgaIgDAAIgaA+QgDAHgJAAIgYAAQgEAAgDgCQgDgBgDgEIgYg+IgDAAQAIAfADAPQACAPAAAPIAAAQQAAAGgDACQgCADgHAAIgiAAQgHAAgCgDQgCgCgBgGIAAihQABgGACgDQACgCAHAAIAgAAQAGAAAEABQADACADAFIAmBRIAmhRQADgFADgCQADgBAGAAIAhAAQAHAAACACQADADAAAGIAAChQAAAGgDACQgCADgHAAg");
	this.shape.setTransform(112.2,9.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,224.4,19.3);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGuByQgFAAAAgFIAAgfIhvAAIAAAfQAAAFgFAAIgHAAQgFAAAAgFIAAgrQAAgEAFAAIAHAAQAFgEADgGQAEgFACgIQADgHABgNIABhEQAAgFAEAAIBXAAQAEAAAAAFIAABvIAPAAQAEAAAAAEIAAArQAAAFgEAAgAFZgIQgBAfgDAMIgFAPQgCAHgEAFIBMAAIAAhkIg9AAgALeBPIgDgIQgCgEADgBQAJgFAGgHQAEgEACgIQAGgbAAgWIAAgqQAAgFAEAAIBUAAQAFAAAAAFIAAB6QAAAFgFAAIgIAAQgFAAAAgFIAAhvIg6AAIAAAgQAAAWgDARQgDARgFAJQgGAJgFAFQgFAEgJAEIgCABQAAAAgBgBQgBAAAAAAQgBAAAAgBQAAgBgBAAgAhtBPQgKgDgGgFQgGgGgDgLQgEgKAAgQIAAhCIgYAAQgFAAAAgFIAAgGQAAgFAFAAIAYAAIAAgaQAAgFAFAAIAIAAQAFAAAAAFIAAAaIAmAAQAEAAAAAFIAAAGQAAAFgEAAIgmAAIAABCQAAAWAIAHQADAEAIACQAHACALAAQAFAAAAAFIAAAHQAAAEgFAAIgEAAQgNAAgJgCgADHBOQgLgDgHgGQgHgHgEgIQgEgJAAgLIAAgsQAAgLAEgJQAEgJAHgGQAHgGALgEQAKgDAOAAQANAAALADQAKAEAIAGQAHAGAEAJQAEAJAAALIAAAsQAAALgEAJQgEAJgHAGQgIAGgKADQgLADgNAAQgOAAgKgDgADOgoQgHACgFAFQgFAEgDAGQgDAGAAAHIAAAsQAAAHADAGQADAGAFAEQAFAEAHACQAIADAJAAQAJAAAHgDQAIgCAFgEQAFgEADgGQACgGAAgHIAAgsQAAgHgCgGQgDgGgFgEQgFgFgIgCQgHgCgJAAQgJAAgIACgAkGBOQgKgEgHgHQgHgGgEgKQgEgKAAgMIAAggQAAgNAEgKQAEgKAHgHQAIgHAKgEQALgEAOAAQAOAAALAEQAKAEAIAHQAHAHAEAKQAEAKAAAMIAAAMQAAAIgIAAIhaAAIAAAPQAAAIACAHQADAGAFAFQAFAFAHACQAIACAJAAQAOAAAKgFQALgFAGgLQADgFAEADIAGADQAFACgDAFQgEAHgGAGQgFAFgHADQgHAEgJACQgIABgKAAQgOAAgLgDgAj9goQgIACgFAFQgFAFgDAHQgCAHAAAJIAAAHIBQAAIAAgHQAAgJgCgHQgDgHgFgFQgFgFgIgCQgHgDgKAAQgKAAgHADgAmPBPQgLgCgIgDQgHgDgCgDQgCgDAAgGIAAinQAAgFAFAAIAIAAQAFAAAAAFIAAA6IAWgGQALgCAIAAQANAAAKADQAJAEAHAGQAGAGADAKQADAJAAANIAAAjQAAANgDAKQgEALgHAGQgHAHgKADQgLADgOAAQgNAAgLgCgAmHgoIgUAHIAABXQAAAEAFACIAOAEIAQACQAKAAAIgDQAHgCAFgFQAFgFADgHQACgHAAgJIAAgiQAAgJgCgHQgDgGgEgFQgFgEgGgCQgHgDgJAAQgKAAgJACgAqqBOQgKgDgIgGQgHgHgEgIQgEgJAAgLIAAgsQAAgLAEgJQAEgJAHgGQAIgGAKgEQALgDANAAQANAAALADQALAEAHAGQAIAGAEAJQAEAJAAALIAAAsQAAALgEAJQgEAJgIAGQgHAGgLADQgLADgNAAQgNAAgLgDgAqigoQgHACgGAFQgFAEgDAGQgCAGAAAHIAAAsQAAAHADAGQACAGAGAEQAFAEAHACQAHADAJAAQAJAAAIgDQAHgCAFgEQAFgEADgGQADgGAAgHIAAgsQAAgHgDgGQgDgGgFgEQgFgFgHgCQgIgCgJAAQgJAAgHACgAK7BOQgFAAAAgFIAAgrIgqAAIgdAsQgDAEgGAAIgHAAQgIAAAEgGIAfgtQgHgBgGgEQgGgDgEgFQgEgFgCgHQgCgFAAgIQAAgKADgIQADgIAGgGQAFgFAIgDQAJgDAKAAIA8AAQAEAAAAAFIAAB6QAAAFgEAAgAJ9gkQgFABgDAEQgEAEgCAFQgCAFAAAGQAAAGACAFQACADAEAEQADADAFACQAFACAHAAIAtAAIAAg0IgtAAQgHAAgFACgAIxBOQgEAAAAgFIAAg4IhLAAIAAA4QAAAFgFAAIgIAAQgFAAAAgFIAAh6QAAgFAFAAIAIAAQAFAAAAAFIAAAyIBLAAIAAgyQAAgFAEAAIAJAAQAEAAAAAFIAAB6QAAAFgEAAgAB7BOQgFAAAAgFIAAhvIhKAAIAABvQAAAFgFAAIgIAAQgFAAAAgFIAAh6QAAgFAFAAIBkAAQAFAAAAAFIAAB6QAAAFgFAAgAnaBOQgFAAAAgFIAAhPQAAgJgCgHQgCgGgFgFQgEgEgHgCQgHgDgJAAIgSACQgJABgIADQgDACAAAFIAABmQAAAFgFAAIgIAAQgFAAAAgFIAAhsQAAgGACgDQACgCAGgDQAKgEANgDQAMgCANAAQANAAAKADQAKAEAGAGQAGAGAEAKQADAJAAANIAABQQAAAFgFAAgAtOBOQgFAAAAgFIAAitQAAgFAFAAIBpAAQAFAAAAAFIAAAIQAAAFgFAAIhcAAIAABDIBPAAQAFAAAAAFIAAAHQAAAGgFAAIhPAAIAABLQAAAFgFAAg");
	this.shape.setTransform(85.5,10.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.2,-0.8,170.6,22.9);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.logo();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,174,52);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.obj_18();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,56,26);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.obj_06();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,138,151);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.obj_03();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,83,72);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.obj_10();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,92,76);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.obj_15();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,164,173);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,640,436);


(lib.Символ57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ59();
	this.instance.setTransform(151,12.8,1,1,0,0,0,153.2,15.2);

	this.instance_1 = new lib.Символ58();
	this.instance_1.setTransform(151,50,1,1,0,0,0,141.8,11);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.2,-2.4,306.5,63.3);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ50();
	this.instance.setTransform(22,63.1,1.639,1.639,5.8,0,0,22,63.1);
	this.instance.alpha = 0.41;
	this.instance.compositeOperation = "lighter";
	this.instance.filters = [new cjs.BlurFilter(32, 32, 1)];
	this.instance.cache(-2,-2,48,130);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.3,-59.4,128,248);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ49();
	this.instance.setTransform(22,63,1,1,0,0,0,22,63);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:433,y:65},24).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.3,-59.4,128,248);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ57();
	this.instance.setTransform(148.2,33.9,1,1,0,0,0,152.2,29.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6.2,1.6,306.5,63.3);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ40();
	this.instance.setTransform(9.2,31.6,1,1,25,0,0,19.2,56.1);
	this.instance.alpha = 0.41;
	this.instance.compositeOperation = "lighter";
	this.instance.filters = [new cjs.BlurFilter(25, 25, 1)];
	this.instance.cache(-2,-2,43,116);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:197.2,y:96.1},24).wait(16));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.9,-53.4,140,176);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ39();
	this.instance.setTransform(19.2,56.1,1,1,0,0,0,19.2,56.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.9,-40.4,111,147);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ37();
	this.instance.setTransform(15.3,13.8,1,1,0,0,0,15.3,8.8);

	this.instance_1 = new lib.Символ36();
	this.instance_1.setTransform(67.9,9.6,1,1,0,0,0,32.1,9.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100,22.5);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 1
	this.instance = new lib.Символ35();
	this.instance.setTransform(42.2,-18.1,1,1,0,0,0,50,11.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// 2
	this.instance_1 = new lib.Символ34();
	this.instance_1.setTransform(42.1,3.9,1,1,0,0,0,43.2,9.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.8,-29.3,99.9,42.8);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.setTransform(15.3,13.4,1,1,0,0,0,15.3,8.8);

	this.instance_1 = new lib.Символ28();
	this.instance_1.setTransform(66.3,9.4,1,1,0,0,0,30.9,9.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,97.3,22.1);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ30();
	this.instance.setTransform(48,35.6,1,1,0,0,0,44.2,6.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// 1
	this.instance_1 = new lib.Символ31();
	this.instance_1.setTransform(48,11,1,1,0,0,0,48.6,11);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.6,0,97.3,42.4);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AguEbIhhgDIhegUIgxggIAHhbIglgeIgChbIBEgcIABhdIhKguIAEhRIAKgLQAKgLAEABQADAAAlgKIAlgKIBxgJIBugBICMAGIBMAQIAjAQIAAAWIABBVIBDAeIgCBhIhCAkIgBBOIAhAeIALBXIgNAUIhhAcIh6ARIgEAAIhtgCg");
	mask.setTransform(32,28.9);

	// Слой 3
	this.instance = new lib.Символ38();
	this.instance.setTransform(-47.9,21.5,1,1,0,0,0,19.2,56.1);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.gold();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.4,0,65.5,58);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// icon
	this.instance = new lib.Символ26();
	this.instance.setTransform(26.2,29,1,1,0,0,0,32.5,29);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// text
	this.instance_1 = new lib.Символ27();
	this.instance_1.setTransform(26.8,80.1,1,1,0,0,0,48.6,11);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-118.4,-75,193.3,186.5);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 1m
	this.instance = new lib.Символ25();
	this.instance.setTransform(52.5,26,1,1,0,0,0,32.5,29);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-98.4,-78,193.3,186.5);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Au6FOQh8AAhXhXQhZhZAAh8IAAhEQAAh8BZhXQBXhZB8AAId1AAQB8AABXBZQBZBXAAB8IAABEQAAB8hZBZQhXBXh8AAg");
	mask.setTransform(125.5,33.5);

	// Слой 3
	this.instance = new lib.Символ48();
	this.instance.setTransform(-47,48.6,1,1,0,0,0,22,63);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ47();
	this.instance_1.setTransform(125.5,33.5,1,1,0,0,0,125.5,33.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,251,67);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(1));

	// Слой 1
	this.instance = new lib.Символ22();
	this.instance.setTransform(125.5,33.5,1,1,0,0,0,125.5,33.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.06,scaleY:1.06,y:24.5},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,251,67);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 3
	this.instance = new lib.Символ19();
	this.instance.setTransform(85.1,59.8,1,1,0,0,0,94.2,9.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// 2
	this.instance_1 = new lib.Символ18();
	this.instance_1.setTransform(85,26.1,1.39,1.39,0,0,0,112.2,9.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// 1
	this.instance_2 = new lib.Символ17();
	this.instance_2.setTransform(85.1,-10,1,1,0,0,0,85.4,11);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70.9,-21.8,311.9,91.2);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ21();
	this.instance.setTransform(125.5,33.5,1,1,0,0,0,125.5,33.5);

	this.instance_1 = new lib.Символ20();
	this.instance_1.setTransform(125.5,33.5,1,1,0,0,0,125.5,33.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-109.4,-73.8,360.4,247);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4
	this.instance = new lib.Символ6();
	this.instance.setTransform(72.4,224.3,0.87,0.87,0,0,180,82,86.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({y:234.3},14,cjs.Ease.get(1)).to({y:224.3},10,cjs.Ease.get(1)).wait(1));

	// obj_18.png
	this.instance_1 = new lib.Символ12();
	this.instance_1.setTransform(103,114,1,1,0,0,0,28,13);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(2).to({y:124},14,cjs.Ease.get(1)).to({y:114},10,cjs.Ease.get(1)).wait(4));

	// obj_06.png
	this.instance_2 = new lib.Символ11();
	this.instance_2.setTransform(71,73.5,1,1,0,0,0,69,75.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:83.5},14,cjs.Ease.get(1)).to({y:73.5},10,cjs.Ease.get(1)).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1,-2,142.7,301.5);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 1
	this.instance = new lib.Символ10();
	this.instance.setTransform(69,98,1,1,0,0,0,69,98);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.1,scaleY:1.1,x:62},3,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1,x:69},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1,-2,142.7,301.5);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// obj_15.png
	this.instance = new lib.Символ6();
	this.instance.setTransform(-133.9,110.5,1,1,0,0,0,82,86.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({y:119.5},11,cjs.Ease.get(1)).to({y:110.5},13,cjs.Ease.get(1)).wait(1));

	// obj_10.png
	this.instance_1 = new lib.Символ7();
	this.instance_1.setTransform(-131,10,1,1,0,0,0,46,38);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(3).to({y:19},11,cjs.Ease.get(1)).to({y:10},14,cjs.Ease.get(1)).wait(2));

	// obj_03.png
	this.instance_2 = new lib.Символ8();
	this.instance_2.setTransform(-150.4,-61,1,1,0,0,0,41.5,36);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-52},12,cjs.Ease.get(1)).to({y:-61},15,cjs.Ease.get(1)).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-215.9,-97,164,294);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 1
	this.instance = new lib.Символ5();
	this.instance.setTransform(82,86.5,1,1,0,0,0,82,86.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.1,scaleY:1.1,x:112},3,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1,x:82},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-215.9,-97,164,294);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ3();
	this.instance.setTransform(320,217,1,1,0,0,0,320,218);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:97},99).to({y:217},125).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-1,640,436);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4).call(this.frame_4).wait(6));

	// Слой 2
	this.instance = new lib.Символ51();
	this.instance.setTransform(312.4,151,1,1,0,0,0,366.4,183);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({alpha:0.32},3,cjs.Ease.get(1)).wait(1).to({alpha:0},4,cjs.Ease.get(1)).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ2();
	this.instance_1.setTransform(320,218,1,1,0,0,0,320,218);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({scaleX:1.02,scaleY:1.02},3,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1},4,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-1,640,436);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.instance = new lib.Символ33();
	this.instance.setTransform(32.4,107.9,1,1,0,0,0,43.2,9.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// icon
	this.instance_1 = new lib.Символ26();
	this.instance_1.setTransform(31.3,34,0.84,0.84,0,0,0,32.5,29);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.3,-55.4,173.6,167.1);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_289 = function() {
		this.gotoAndPlay(0);
	}
	this.frame_314 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(289).call(this.frame_289).wait(25).call(this.frame_314).wait(41));

	// bonus
	this.instance = new lib.Символ41();
	this.instance.setTransform(72.5,393.5,1,1,0,0,0,133,31.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(195).to({_off:false},0).to({y:103.5},9,cjs.Ease.get(1)).to({y:113.5},5,cjs.Ease.get(1)).wait(70).to({y:123.5},5,cjs.Ease.get(1)).to({y:-66.5},5,cjs.Ease.get(1)).to({_off:true},1).wait(65));

	// 500k
	this.instance_1 = new lib.Символ32();
	this.instance_1.setTransform(167,318.3,1,1,0,0,0,32.5,29);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(124).to({_off:false},0).to({y:88.3},10,cjs.Ease.get(1)).to({y:98.3},5,cjs.Ease.get(1)).wait(45).to({y:108.3},5,cjs.Ease.get(1)).to({y:-121.7},5,cjs.Ease.get(1)).to({_off:true},1).wait(160));

	// 1m
	this.instance_2 = new lib.Символ24();
	this.instance_2.setTransform(-7.5,321.5,1,1,0,0,0,32.5,29);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(119).to({_off:false},0).to({y:91.5},10,cjs.Ease.get(1)).to({y:101.5},5,cjs.Ease.get(1)).wait(50).to({y:111.5},5,cjs.Ease.get(1)).to({y:-118.5},5,cjs.Ease.get(1)).to({_off:true},1).wait(160));

	// euro_logo
	this.instance_3 = new lib.Символ23();
	this.instance_3.setTransform(87,417.5,1,1,0,0,0,83,117.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(64).to({_off:false},0).to({y:117.5},10,cjs.Ease.get(1)).to({y:127.5},5,cjs.Ease.get(1)).wait(15).to({scaleX:1.07,scaleY:1.07},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},5,cjs.Ease.get(1)).wait(5).to({y:137.5},5,cjs.Ease.get(1)).to({y:-152.5},5,cjs.Ease.get(1)).to({_off:true},1).wait(235));

	// btn
	this.instance_4 = new lib.Символ15();
	this.instance_4.setTransform(86.5,519.5,1,1,0,0,0,125.5,33.5);
	this.instance_4._off = true;
	new cjs.ButtonHelper(this.instance_4, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(4).to({_off:false},0).to({y:219.5},9,cjs.Ease.get(1)).to({y:229.5},5,cjs.Ease.get(1)).wait(36).to({y:239.5},5,cjs.Ease.get(1)).to({y:-70.5},5,cjs.Ease.get(1)).wait(133).to({x:87.6,y:350.5},0).to({y:190.5},9,cjs.Ease.get(1)).to({y:200.5},5,cjs.Ease.get(1)).wait(68).to({y:210.5},5,cjs.Ease.get(1)).to({y:-79.5},5,cjs.Ease.get(1)).to({_off:true},1).wait(4).to({_off:false,x:86.5,y:519.5},0).to({y:219.5},9,cjs.Ease.get(1)).to({y:229.5},5,cjs.Ease.get(1)).wait(36).to({y:239.5},5,cjs.Ease.get(1)).to({y:-70.5},5,cjs.Ease.get(1)).wait(1));

	// text_1
	this.instance_5 = new lib.Символ16();
	this.instance_5.setTransform(87.8,401.6,1,1,0,0,0,85.4,11);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(2).to({_off:false},0).to({y:101.6},9,cjs.Ease.get(1)).to({y:111.6},5,cjs.Ease.get(1)).wait(38).to({y:121.6},5,cjs.Ease.get(1)).to({y:-188.4},5,cjs.Ease.get(1)).to({_off:true},226).wait(2).to({_off:false,y:401.6},0).to({y:101.6},9,cjs.Ease.get(1)).to({y:111.6},5,cjs.Ease.get(1)).wait(38).to({y:121.6},5,cjs.Ease.get(1)).to({y:-188.4},5,cjs.Ease.get(1)).wait(1));

	// logo
	this.instance_6 = new lib.Символ14();
	this.instance_6.setTransform(87,316,1,1,0,0,0,87,26);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({y:16},9,cjs.Ease.get(1)).to({y:26},5,cjs.Ease.get(1)).wait(40).to({y:36},5,cjs.Ease.get(1)).to({y:-274},5,cjs.Ease.get(1)).wait(133).to({y:46},9,cjs.Ease.get(1)).to({y:41},5,cjs.Ease.get(1)).wait(68).to({y:51},5,cjs.Ease.get(1)).to({y:-79},5,cjs.Ease.get(1)).wait(1).to({y:316},0).to({y:16},9,cjs.Ease.get(1)).to({y:26},5,cjs.Ease.get(1)).wait(40).to({y:36},5,cjs.Ease.get(1)).to({y:-274},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,290,174,52);


// stage content:



(lib._640x305 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var _this = this;
		
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		  function fl_MouseOverHandler_5()
		{
		    _this.an.gotoAndPlay(290);
			_this.bg.gotoAndPlay(1);
			_this.left.gotoAndPlay(1);
			_this.right.gotoAndPlay(1);
			
		
		    
		}
		
		
		stage.canvas.onmouseout = fl_MouseOutHandler_23;
		
		  function fl_MouseOutHandler_23()
		{
		    _this.an.gotoAndPlay(54);
			_this.bg.gotoAndPlay(5);
			_this.left.gotoAndPlay(5);
			_this.right.gotoAndPlay(5);
		
			
		
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// an
	this.an = new lib.Символ13();
	this.an.setTransform(320,49.5,1,1,0,0,0,87,26);

	this.timeline.addTween(cjs.Tween.get(this.an).wait(1));

	// obj_right
	this.right = new lib.Символ9();
	this.right.setTransform(577.5,107,1,1,0,0,0,69,98);

	this.timeline.addTween(cjs.Tween.get(this.right).wait(1));

	// obj_left
	this.left = new lib.Символ4();
	this.left.setTransform(267.5,192.5,1,1,0,0,0,82,86.5);

	this.timeline.addTween(cjs.Tween.get(this.left).wait(1));

	// bg
	this.bg = new lib.Символ1();
	this.bg.setTransform(320,218,1,1,0,0,0,320,218);

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(289.6,151.5,682.7,436);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;